### ISSUE TITLE
OKTA golang sdk appears to be dead?

### ISSUE THREAD

**Issue by pratikmallya** [okta/terraform-provider-okta#10]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Since this provider depends on the [sdk](https://github.com/okta/okta-sdk-golang), I'm a bit concerned if the sdk would become a bottleneck to continued development. That repo appears to be abandoned, with nobody responding to any issues, no recent commits etc. 

Is this provider at risk because of the dependency on that abandoned sdk? How can we avoid that?

### New or Affected Resource(s)

* okta_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://github.com/okta/okta-sdk-golang

**Comment by noinarisak** [comment]
Hi @pratikmallya, 

I agree the okta-sdk-golang has not seen any love in a while but this provider actually extends the SDK thanks to @quantumew and committers to close that gap. I and two other Okta employees with @quantumew help will continue work on this provider going forward. Please be aware, thou, we are volunteering our time on this project and it is not our full-time focus. We just big believers in the project and all the hard work from @quantumew and the community. 

Hopefully, it will bleed over to the okta-sdk-golang repo. =)

**Comment by pratikmallya** [comment]
Ah ok cool. I was curious if the provider would be constrained by the sdk but this appears to not be the case. Thanks!
