### ISSUE TITLE
Unexpected "Internal Server Error" on okta_group_rule resource

### ISSUE THREAD

**Issue by tgoodsell-tempus** [okta/terraform-provider-okta#100]
When running a `terraform apply` with numerous "okta_group_ruple" creation actions; there will randomly be a "500 Internal Server Error" return, which is not handled by the provider.

I am currently working on a case with Okta to try and diagnose this and comment on my thoughts on the proper solution.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform Version: 0.12.20
Okta Provider Version: 3.2.0

### Affected Resource(s)

* okta_group_rule

### Terraform Configuration Files

```hcl
Root Module (1 of 4 included for brevity):

module "eng_imx_engineer" {
  source      = "../../../modules/okta/group-rule-enterprise-role"
  prefix      = ""
  parent      = "ENG_IMX_Engineer"
  description = "Engineer on the IMX Engineering team"
  assignments = [
    "Github",
    "jira-software-users",
    "splunk-power_users",
    "A_ROLE_DEVELOPER",
    "B_TEAM_LabServices",
    "sundial-role:A_READER",
    "sundial-role:ORDERMGMT_READER",
    "sundial-role:DB_REPORT_READER",
    "sundial-role:DP_SEARCHER",
    "sundial-role:L_TECH",
    "sundial-role:P_READ_ONLY",
    "entitlement:aws/ENG-Team-Engineer",
    "entitlement:aws/IMX-Team-Engineer"
  ]
}


Source Definition:

resource "okta_group" "parent" {
  count       = var.create_parent ? 1 : 0
  name        = "${var.prefix}${var.parent}"
  description = var.description
}

data "okta_group" "parent" {
  count = var.create_parent ? 0 : 1
  name  = var.parent
}

locals {
  parent_group_id = var.create_parent ? okta_group.parent[0].id : data.okta_group.parent[0].id
}

data "okta_group" "assignments" {
  for_each = toset(var.assignments)
  name     = each.key
}

resource "okta_group_rule" "parent_assignments" {
  count             = length(var.assignments) > 0 ? 1 : 0
  status            = "ACTIVE"
  name              = substr("${local.parent_group_id}:${var.parent}", 0, 50)
  group_assignments = concat([for param in data.okta_group.assignments : param.id])
  expression_value  = "isMemberOfGroup(\"${local.parent_group_id}\")"
}
```

### Debug Output

https://gist.github.com/tgoodsell-tempus/40c2c24e5726f6ddd0ef2a0f14cd1723

### Panic Output

N/A

### Expected Behavior

Apply creates all the group rules as expected: `HTTP/2.0 200 OK`

### Actual Behavior

1. Some of the rule creations will return: `HTTP/2.0 500 Internal Server Error`

### Steps to Reproduce

1. Generate code with large number (3 - 4 or more) of Okta group rule additions/changes
2. Run: `TF_IN_AUTOMATION="true" TF_LOG=TRACE terraform apply -input=false -no-color -auto-approve local_tfplan`
3. View apply log file

### Important Factoids

Transient issue: Re-running the apply process will eventually have all the group rules correctly built. Generally, each run will have the issue occur for a smaller and smaller number of rules, does not appear to be a pattern to the selection in terms of inputs.

### References

* #0000

**Comment by tgoodsell-tempus** [comment]
Making a comment here, I made a mistake analyzing the trace logs for this. This is coming from an APPLY error, I will update this and working on providing better trace data once I'm able to re-produce again.

**Comment by tgoodsell-tempus** [comment]
I've updated the root comment with the corrected details and a new debug output; I've also opened a case with Okta to specifically investigate the 500 error which was returned in the debug posted.

**Comment by tgoodsell-tempus** [comment]
Updated on this, I've not got a resolution on my case. However, this does appear to be caused hitting that API in parallel. 

I've set my terraform apply to `-parallelism=1` and I've had 0 failures on group rule applies since then.

**Comment by ryber** [comment]
I started getting this same error today. Turning parallel off worked. It would be nice to get a better error than just 500 but maybe the Okta API doesn't return anything better?
