### ISSUE TITLE
okta_group_memberships doesn't check for dupe

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1000]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.0.11
on darwin_arm64
+ provider registry.terraform.io/okta/okta v3.20.7

Your version of Terraform is out of date! The latest version
is 1.1.7. You can update by downloading from https://www.terraform.io/downloads.html
```
### Affected Resource(s)

- okta_group_memberships

### Terraform Configuration Files

```hcl
resource "okta_group" "test" {
  name        = "test"
  description = ""
  skip_users  = false
}

resource "okta_user" "test1" {
  status       = "ACTIVE"
  login        = "test1@domain.com"
  email        = "test1@domain.com"
  first_name   = "test1"
  last_name    = "user"
  display_name = "test1 user"
}

resource "okta_user" "test2" {
  status       = "ACTIVE"
  login        = "test2@domain.com"
  email        = "test2@domain.com"
  first_name   = "test2"
  last_name    = "user"
  display_name = "test2 user"
}

resource "okta_group_memberships" "vega_app_owners" {
  group_id = okta_group.test.id
  users = [
    okta_user.test1.id,
  ]
}

resource "okta_group_memberships" "vega_app_owners1" {
  group_id = okta_group.test.id
  users = [
    okta_user.test2.id,
  ]
}
```

### Expected Behavior

I expect that i'd get an error telling me that the okta_group_memberships has already been defined for this group

### Actual Behavior

Not sure if this is expected behaviour that the you can define multiple okta_group_memberships resources for the same group
or if it is expected that okta_group_memberships should only be defined once per group

in my above example the resources have different names, but it also appears possible to have resources with the same name in different sub modules referencing the same Okta group

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by virgofx** [comment]
I'm not sure but I don't believe that's possible. In fact it's kind of an anti pattern to handle this behavior at the provider level.

The provider is responsible to manage resources in a box (for the most part) and it's up to the user to define and handle the logic appropriately. 

Similarly, that's like s defining 2 AWS S3 bucket resources with the same name - the first one will succeed and the second will error at the api level. In this case, there's no error at the api level just race condition that will never level out

**Comment by monde** [comment]
thanks for the report @exitcode0 and thanks for the feedback @virgofx . I'll try out the sample and talk with some other people in DevEx and give feedback.

**Comment by monde** [comment]
@exitcode0 under the hood there aren't any excess API calls to [Add User to Group](https://developer.okta.com/docs/reference/api/groups/#add-user-to-group) which are PUTs. This is how I capture a log of the API calls `TF_LOG=1 terraform apply 2>&1 | tee apply-1.log`

```
# grep " \/api.v1.groups.*users" apply-1.log
PUT /api/v1/groups/00g15w00awrAHcnx70h8/users/00u15w04n9x5gyTsE0h8 HTTP/1.1
PUT /api/v1/groups/00g15w00awrAHcnx70h8/users/00u15w00awsknWU3f0h8 HTTP/1.1
GET /api/v1/groups/00g15w00awrAHcnx70h8/users?limit=200 HTTP/1.1
GET /api/v1/groups/00g15w00awrAHcnx70h8/users?limit=200 HTTP/1.1
```

@exitcode0 are you saying that being able to have two `okta_group_memberships` in your TF configuration looks wonky from a stylistic point of view? Or can this cause a bug and/or unintended consequences in a more advance terraform config beyond the sample you provided?

**Comment by exitcode0** [comment]
More about the stylistic Point of view
Wasn't sure if these resources concatenated their contents before an apply and if that was expected or if having multiple of these resources pointing to the same group is not the expected design

This caused confusion for me as I had one submodule that had a Okta group membership resource that was defining a user that was deactivated
Took some time for me to realise what was going on as it appeared that the one that was in front of me was doing something outside the config defined
But instead it was a resource with the same name in another submodule

**Comment by monde** [comment]
@exitcode0 I'm going to close this issue for now.
