### ISSUE TITLE
okta_domain_certificate supplies invalid values to the API against unmodified fields

### ISSUE THREAD

**Issue by nick-jones** [okta/terraform-provider-okta#1002]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

- tf: 1.1.6
- terraform-provider-okta: 3.22.0

### Affected Resource(s)

- okta_domain_certificate

### Terraform Configuration Files

```hcl
resource "okta_domain_certificate" "example" {
  domain_id         = okta_domain.example.id
  type              = "PEM"
  certificate       = file("${path.module}/cert/example.crt.pem")
  private_key       = file("${path.module}/key/example.private.key.pem")
  certificate_chain = file("${path.module}/cert/example.crt.pem")
}
```

The underling `certificate` and `certificate_chain` files have been modified since last apply. `private_key` is unmodified.

### Debug Output

**Please note** that in the below example `privateKey` does not relate to an in-use private key in any shape or form - I've included an example value to help demonstrate the issue.

```
2022-03-07T13:34:50.307Z [INFO]  provider.terraform-provider-okta_v3.22.0: 2022/03/07 13:34:50 [DEBUG] Okta API Request Details:
---[ REQUEST ]---------------------------------------
PUT /api/v1/domains/***/certificate HTTP/1.1
Host: ***
User-Agent: okta-sdk-golang/2.9.2 golang/go1.17.7 linux/amd64 okta-terraform/3.22.0
Content-Length: 4270
Accept: application/json
Authorization: SSWS ***
Content-Type: application/json
Accept-Encoding: gzip

{
 "certificate": "-----BEGIN CERTIFICATE-----\n<snip>\n-----END CERTIFICATE-----\n",
 "certificateChain": "-----BEGIN CERTIFICATE-----\n<snip>\n-----END CERTIFICATE-----\n",
 "privateKey": "7iaw3Ur350mqGo7jwQrpkj9hiYB3Lkc_iBml1JQODbJ6wYX4oOHV-E-IvIh_1nsUNzLDBMxfqa2Ob1f1ACio_w==",
 "type": "PEM"
}

2022-03-07T13:34:50.391Z [INFO]  provider.terraform-provider-okta_v3.22.0: 2022/03/07 13:34:50 [DEBUG] Okta API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 400 Bad Request
Connection: close
Cache-Control: no-cache, no-store
Content-Type: application/json
Date: Mon, 07 Mar 2022 13:34:50 GMT
<snip>

{
 "errorCode": "E0000001",
 "errorSummary": "Api validation failed: privateKey",
 "errorLink": "E0000001",
 "errorId": "oae63L4IEkkS3SfOaDOJSRQtA",
 "errorCauses": [
  {
   "errorSummary": "privateKey: Invalid private key format. The format must be a valid PEM encoded RSA private key"
  }
 ]
}
```

### Expected Behavior

Ceritificates updated

### Actual Behavior

Error:

```
│ Error: failed to update domain's certificate: the API returned an error: Api validation failed: privateKey. Causes: errorSummary: privateKey: Invalid private key format. The format must be a valid PEM encoded RSA private key
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

We are looking to update the certificate and certificate chain - the private key remains unmodified. It seems the provider is supplying a sha512 hash of the private key instead of the real value. This is potentially down to the state being overridden - https://github.com/okta/terraform-provider-okta/blob/d40aa071ca835e89051b07875ae2010ef03b4ba5/okta/resource_okta_domain_certificate.go#L50-L54 - my assumption is this was done to avoid storing the private key in state, but it may have had unintended consequences.

The unfortunate workaround to all this is to submit the changes via the web UI.

### References

- https://github.com/okta/terraform-provider-okta/blob/d40aa071ca835e89051b07875ae2010ef03b4ba5/okta/resource_okta_domain_certificate.go

**Comment by monde** [comment]
hi @nick-jones thank you for the detailed debugging details and explanation to reproduce. Would you be interested in submitting a PR as well?

**Comment by nick-jones** [comment]
> hi @nick-jones thank you for the detailed debugging details and explanation to reproduce. Would you be interested in submitting a PR as well?

I'm happy to raise a PR, however I think this might require a bit of discussion over what an appropriate solution looks like.

Assuming it is reading state to populate the unmodified values, the most obvious thing would be to stop storing hashed values in state and just work with the way terraform wants to work. The compromise is that the private key will end up being stored in state - obviously the original intent was to avoid this. This would likely constitute a breaking change too, as there will now be state stored in the wild with hashed values.

A second option is to continue to pursue the hashed values route. Feasibly `ForceNew` could be used (untested), or some other option to coerce it into always reading from local config instead of state.

Another option might be to introduce a new resource type that looks to specify the path to private key file instead of the raw value.. this could potentially still maintain a hash too (e.g. `{"hash": "<value>", "path": "path/to/crt.pem"}`). This is probably a bit fidly though, as `StateFunc` can only return a string value.. so you'd need to an extra layer of encoding.

It's probably worth looking at other tf providers to see what approaches have been taken in similar circumstances? And like I say, this is all based on my current assumption of what is going on here - we need to confirm that it is indeed pulling the value from state rather than doing something else funky.
