### ISSUE TITLE
Missing email type "email.sunone.selfServiceUnlock"

### ISSUE THREAD

**Issue by martinhelfert** [okta/terraform-provider-okta#1006]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When doing a GET on `{{url}}/api/v1/templates/emails` you'll get a email type named `email.sunone.selfServiceUnlock` which is the template for **LDAP Self-Service Unlock Account** you can also view in your admin dashboard.

If you use this type, the resource gets rejected:

`Error: expected value to be one of 'email.welcome', 'email.forgotPassword', 'email.emailLinkRecoveryResetFactor', 'email.emailLinkRecoveryResetPwdFactor', 'email.emailLinkRecoveryAdResetFactor', 'email.emailLinkRecoveryAdResetPwdFactor', 'email.emailLinkRecoveryLdapResetPwdFactor', 'email.forgotPasswordDenied', 'email.tempPassword', 'email.ad.welcome', 'email.ad.forgotPassword', 'email.ad.forgotPasswordReset', 'email.sunone.welcome', 'email.sunone.forgotPassword', 'email.sunone.forgotPasswordDenied', 'email.selfServiceUnlock', 'email.emailLinkRecoveryUnlockFactor', 'email.emailLinkRecoveryAdUnlockFactor', 'email.emailLinkRecoveryUnlockPwdFactor', 'email.emailLinkRecoveryAdUnlockPwdFactor', 'email.emailLinkRecoveryLdapUnlockPwdFactor', 'email.ad.selfServiceUnlock', 'email.pushVerifyActivation', 'email.accountLockout', 'email.emailTransactionVerification', 'email.emailLinkAuthenticationTransaction', 'email.emailActivation', 'email.signInFromNewDevice', 'email.registrationActivation', 'email.emailChangeConfirmation', 'email.emailNewChangeNotification', 'email.emailNewAlreadyChangedNotification', 'email.registrationEmailVerification', 'email.emailLinkFactorVerification', 'email.selfServiceUnlockOnUnlockedAccount', 'email.endUserScheduledLifecycleStatusChange', 'email.adminUsersListScheduledLifecycleStatusChange', 'email.factorEnrollment', 'email.factorReset', 'email.authenticatorEnrollment', 'email.authenticatorReset', 'email.automation', 'email.passwordChanged', got 'email.sunone.selfServiceUnlock'`

Please add this type so we can deploy the template.

**Comment by monde** [comment]
thanks @martinhelfert I will see about getting this in next release

**Comment by martinhelfert** [comment]
thanks! @monde

**Comment by monde** [comment]
@martinhelfert v3.22.1 is released and includes this fix https://github.com/okta/terraform-provider-okta/releases/tag/v3.22.1 , thanks!
