### ISSUE TITLE
Expose custom group attributes in data_source_okta_groups

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1009]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Exposing custom group attributes in the okta_groups datasource would allow for powerful list comprehensions based on custom attributes 

### New or Affected Resource(s)

- data_source_okta_groups

### Potential Terraform Configuration

```hcl
data "okta_groups" "all_groups" {
  search = "type eq \"OKTA_GROUP\""
}

locals {
  org_name = "example"
  base_url = "okta.com"
}

resource "okta_resource_set" "example" {
  label       = "admin groups"
  description = "Groups that may grant privileged/sensitive access to an application"
  resources = [ 
    for group in data.okta_groups.all_groups.groups : 
    "https://${local.org_name}.${local.base_url}/api/v1/groups/${group.id}" 
    if group.profile.admin == True 
  ]
}
```

### References

- #0000

**Comment by monde** [comment]
thanks @exitcode0 , this looks like a good idea to me.
