### ISSUE TITLE
Expose issuer attribute in okta_server_auth data source

### ISSUE THREAD

**Issue by ryanwholey** [okta/terraform-provider-okta#101]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

tl;dr I would like to return the `issuer` field on the [`okta_server_auth` data source](https://github.com/terraform-providers/terraform-provider-okta/blob/6807eff6fc6443ccedf81c71856a41610a0f8754/okta/data_source_okta_auth_server.go#L14-L48), as it is present on the [`okta_server_auth` resource attribute](https://github.com/terraform-providers/terraform-provider-okta/blob/6807eff6fc6443ccedf81c71856a41610a0f8754/okta/resource_okta_auth_server.go#L58-L69). I would be happy to submit a PR if the idea is gets approval.

I ran into an issue trying to create authorization endpoints for configuring an AWS ALB to use Okta OIDC for auth. I was hoping to use the default auth server to fetch the `issuer` but `issuer` is not returned in the data response. `issuer` is exposed in the attributes of the `okta_server_auth` resource.

My current work around is to use an env var, `TF_VAR_okta_org_name` and a variable declaration to pass to the org name to the provider and use it within my project to interpolate the the issuer url. Maybe there's an alternate solution I missed? 

Thank you! 

### New or Affected Resource(s)
[* data.okta_server_auth](https://github.com/terraform-providers/terraform-provider-okta/blob/master/okta/data_source_okta_auth_server.go)

### Potential Terraform Configuration
no change

### References
[data.okta_server_auth](https://www.terraform.io/docs/providers/okta/d/auth_server.html)
[okta_server_auth](https://www.terraform.io/docs/providers/okta/r/auth_server.html)

**Comment by tgoodsell-tempus** [comment]
According to the [API reference docs](tm-uk-kolesar-organoid) for this, it looks like issuer is returned in the response, so we should be able to use it.

**Comment by ryanwholey** [comment]
I have a [PR open](https://github.com/terraform-providers/terraform-provider-okta/pull/104) for this issue. Is anyone available to review?

**Comment by ryanwholey** [comment]
Still hoping for a review!
