### ISSUE TITLE
[okta_users datasource] Allow logical operators for filter expressions 

### ISSUE THREAD

**Issue by cbrgm** [okta/terraform-provider-okta#1010]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm not sure this feature already exists or not. But I'm using this provider's `okta_users` datasource to query users from Okta and assign their IDs to `okta_group_membership` resources without having to manage the users in my HCL code. Right now I'm querying all users with status `ACTIVE` like this:

```hcl
data "okta_users" "foo" {
  search {
    name  = "status"
    value = "ACTIVE"
  }
}
```

Now I also want to include users with an expired password status `PASSWORD_EXPIRED`. So I created a new data source `okta_users` called `bar` and merge the results together into a local variable later on to actually make use of the combined results.

```hcl
data "okta_users" "foo" {
  search {
    name  = "status"
    value = "ACTIVE"
  }
}

data "okta_users" "bar" {
  search {
    name  = "status"
    value = "PASSWORD_EXPIRED"
  }
}
```

I'd like to see an option to link multiple filter expressions in a `okta_users` datasource together via logical operators (`and`,`or`,`xor`,...) . Is this already possible? I couldn't find anything in the docs and if so, I'd love to improve them.

### New or Affected Resource(s)

- okta_users

### Potential Terraform Configuration

```hcl
data "okta_users" "foo" {
  operator = "and"
  search {
    name  = "status"
    comparison = "eq"
    value = "ACTIVE"
  }
  search {
    name  = "status"
    comparison = "eq"
    value = "PASSWORD_EXPIRED"
  }
}
```

### References

* https://developer.okta.com/docs/reference/api/users/#list-users-with-a-filter
*  https://registry.terraform.io/providers/okta/okta/latest/docs/data-sources/users#example-usage

**Comment by monde** [comment]
@cbrgm the data source example for okta_user shows a multiple search criteria example https://github.com/okta/terraform-provider-okta/blob/master/examples/okta_user/datasource.tf#L31-L41
```terraform
data "okta_user" "test" {
  search {
    name  = "profile.firstName"
    value = okta_user.test.first_name
  }

  search {
    name  = "profile.lastName"
    value = okta_user.test.last_name
  }
}
```
Already, when multiple search blocks are present they are `and` together https://github.com/okta/terraform-provider-okta/blob/master/okta/data_source_okta_user.go#L99 . Given a cut down version of your sample:

```terraform
data "okta_users" "foo" {
  search {
    name  = "status"
    comparison = "eq"
    value = "ACTIVE"
  }

  search {
    name  = "status"
    comparison = "eq"
    value = "PASSWORD_EXPIRED"
  }
}
```
we can see the API call looking at the tf log output
```
# TF_LOG=1 terraform plan
GET /api/v1/users?limit=200&search=status+eq+%22ACTIVE%22+and+status+eq+%22PASSWORD_EXPIRED%22&sortOrder=0 HTTP/1.1
```

However, the Okta expression language only supports AND and OR https://developer.okta.com/docs/reference/okta-expression-language/#conditional-expressions so if we added `operator` to `okta_user` and `okta_users` it would only accept AND and OR.

When we do this work we should also implement a free form expression string as an alternative search criteria (and I 👍 this) 
(From the Okta User API docs for list users with search https://developer.okta.com/docs/reference/api/users/#list-users-with-search )
```terraform
data "okta_users" "zoo" {
  search {
    expression = "profile.department eq \"Engineering\" and (created lt \"2014-01-01T00:00:00.000Z\" or status eq \"ACTIVE\")"
  }
}
```
This all sounds like a great feature to implement, imo.

**Comment by cbrgm** [comment]
Thanks @monde for your kind reply!

 I think your idea of having a free form expression string is way better than introducing an `operator` attribute as suggested by me 👍 ! This is much more flexible and would allow all possible types of search expressions! 
 
 I'd be happy to provide a PR for this feature when I find some time in the next days!

**Comment by cbrgm** [comment]
I was more motivated than I thought and have already prepared a PR. I would be happy about a review and change requests

**Comment by monde** [comment]
Weird this didn't auto-closed.
