### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by tmatilai** [okta/terraform-provider-okta#1019]
Thanks for all the efforts with the provider! I have a small annoyance so I felt like sharing it. 🙂 

Looking at [the changelog](https://github.com/okta/terraform-provider-okta/blob/master/CHANGELOG.md), many patch releases include new features, for example new attributes for resources and data sources.
To use those in a root module, the version requirement has to be specified with e.g. `>= 3.20.8, < 4.0` (instead of e.g. `~> 3.21`).

Any chance you could try to follow [the semantic versioning](https://semver.org/)? 🤗

**Comment by monde** [comment]
Thanks for the feedback @tmatilai . fwiw, our practice of [semantic versioning](https://semver.org/) has been to reserve minor releases to those times when _**new**_ resources are introduced and leave addition of properties/attributes and other refinements of existing resources to patch releases. That said, I will take this feedback into consideration on the next release.

**Comment by monde** [comment]
Shouldn't have closed this issue, we'll reference it on the next release. Thanks again @tmatilai

**Comment by tmatilai** [comment]
Thanks for the quick response, @monde!

Your project, so of course you can decide the rules. But thanks for considering, and explaining the current logic.
