### ISSUE TITLE
New Custom SAML App Missing Provisioning Options from UI

### ISSUE THREAD

**Issue by Mrorya** [okta/terraform-provider-okta#1022]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/okta/okta v3.21.0
```
### Affected Resource(s)

- okta_app_saml

### Terraform Configuration Files

```hcl
resource "okta_app_saml" "fivetran_scim" {
  label                    = "Fivetran [SCIM-Only]"
  status                   = "ACTIVE"
  sso_url                  = "https://fivetran.com/login/saml/return"
  recipient                = "https://fivetran.com/login/saml/return"
  destination              = "https://fivetran.com/login/saml/return"
  audience                 = "Fivetran"
  subject_name_id_template = "$${user.userName}"
  subject_name_id_format   = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
  response_signed          = true
  assertion_signed         = true
  signature_algorithm      = "RSA_SHA256"
  digest_algorithm         = "SHA256"
  honor_force_authn        = true
  hide_ios                 = true
  hide_web                 = true
  authn_context_class_ref  = "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"
  admin_note               = "SCIM ONLY / Not used for authentication"

  attribute_statements {
    type      = "EXPRESSION"
    name      = "firstName"
    namespace = "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
    values    = ["user.firstName"]
  }
  attribute_statements {
    type      = "EXPRESSION"
    name      = "lastName"
    namespace = "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
    values    = ["user.lastName"]
  }
  attribute_statements {
    type      = "EXPRESSION"
    name      = "Role"
    namespace = "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
    values    = ["appuser.role"]
  }

  skip_users  = true
  skip_groups = false
  lifecycle { ignore_changes = [groups] }
}
```

### Expected Behavior

- The Features API as documented is not supported - but I would expect to be able to still configure these provisioning options via the UI after TF creates the application.
![image](https://user-images.githubusercontent.com/3143796/158242323-757419ef-9e93-441e-92fa-e7acbc220488.png)

### Actual Behavior

- Custom SAML app is created without any ability to switch to SCIM or On-Prem Provisioning, leading no ability to manually configure a SCIM setup after enabling on the provisioning tab
![image](https://user-images.githubusercontent.com/3143796/158242409-41f042e1-5d7a-455a-a11d-3e806f461c46.png)
- The application seems to have a provisioning tab, but it does not allow for any configuration
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/3143796/158242517-019bdb1f-80a9-4a07-be28-732c9d0f7cb4.png">

### Steps to Reproduce

- Create custom SAML app via TFE
- Attempt to configure provisioning options via API

### Important Factoids

- Not sure if this is something that should be directed to Okta Support, but given the behavior is not seen when manually creating the app, I assume it has to do with the way the app is created via the API from terraform

**Comment by monde** [comment]
Thanks for all the details to debug the gaps needed to be closed to implement the improvement @Mrorya !

**Comment by Mrorya** [comment]
Thanks @monde - As a heads up, when importing the manually created custom SAML app, the provisioning option was reset from SCIM to None. I assume this is a bug

**Comment by JasonBuckner** [comment]
Sounds like #655

**Comment by monde** [comment]
Marked this as bug per @Mrorya updated observation.

**Comment by JasonBuckner** [comment]
We're still seeing this issue. Please rm 'stale' label.

**Comment by nickrmc83** [comment]
👋  ~~We've just had this hit us in a production environment whereby our provisioning configuration was wiped out. Is there any expected fix date for this as it makes our ongoing use of terraform to configure Okta much more difficult.~~

I think we're actually hitting issue [655](https://github.com/okta/terraform-provider-okta/issues/655).

**Comment by monde** [comment]
@duytiennguyen-okta is working on this

**Comment by monde** [comment]
@Mrorya just checking, is once you go into edit the general settings you're not getting access to the settings you'd like to change?

General settings, before edit:
![image](https://github.com/okta/terraform-provider-okta/assets/201/19604b42-8ea3-4c6f-af42-3ba7017599d1)

General settings, edit:
![image](https://github.com/okta/terraform-provider-okta/assets/201/6ee4aa09-b012-4d5a-adfd-2a22d044e15b)

Thanks
