### ISSUE TITLE
Adding app_signon_policy resource, and adding a corresponding variable to app resources to assign it. 

### ISSUE THREAD

**Issue by ianwinsemius** [okta/terraform-provider-okta#1025]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently we're investigating the possibility of implementing terraform to manage our Okta resources. 
The things we've run into so far that are problematic when working with OIE is the lack of a resource for app_signon_policy. The app_signon_policy_rule is helpful, but having to create those policies to assign rules to manually, retrieve their ID, and hard code it into Terraform is problematic from a maintenance standpoint. 

The inability to assign an app_signon_policy to an app further exacerbates this issue, and means that any app that we create that we want associated with a non-default signon policy will require another manual intervention. 

I understand that the API endpoints currently do not exist for creating SignOn policies per this [previous request](https://github.com/okta/terraform-provider-okta/issues/145) and from looking at your documentation. I'd be happy to create an issue with your API team if there is a way to do that. The issue referenced is from quite a while back, prior to the production launch of Okta Identity Engine. We're hoping to start working with OIE, and the availability of these features would be an incredibly useful addition for us. 

### New or Affected Resource(s)
New resource: app_signon_policy (to match the corresponding data source)
Affected resource: app_saml, etc. which we would be able to associate to sign_on_policies

### Potential Terraform Configuration

```hcl
resource "okta_app_signon_policy" "odt" {
  name = "Require Device Certificates"
  sign_on_policy_rules = [
    "app_signon_policy_rule.trusted_mac_allow.id",
    "app_signon_policy_rule.trusted_windows_allow.id",
    "app_signon_policy_rule.untrusted_mac_deny.id",
    "app_signon_policy_rule.untrusted_windows_deny.id",
  ]
}


resource "okta_app_saml" "example" {
  label                    = "example"
  ...
  sign_on_policy = okta.app_signon_policy.odt.id
}
```

**Comment by monde** [comment]
@ianwinsemius thanks for detailing the use case and gathering all the background that will help with the implementation. This feature is necessary for more common use of OIE as you point out.

Re: "I'd be happy to create an issue with your API team" - please do this by contacting your Okta Custom Success Manager for your Organization. Reference this Github issue when you do.

**Comment by ianwinsemius** [comment]
@monde - I will do that this morning, thank you.

**Comment by monde** [comment]
@ianwinsemius actually, I think all of the APIs are there, I just need do the research on your details. Hold off on pinging your Okta CSM.

**Comment by ianwinsemius** [comment]
Sorry, I had already contact them before you sent that message.

It did get me wondering if I could create them with the API - which it turns out is possible, but not in the public documentation. That would suggest that these resources and attributes could be added to the TF provider in the future.

I am still unable to find an endpoint (documented or otherwise) that allows me to attach an access_policy/sign_on_policy to an application. When you query an App, it returns a "policy" but the link doesnt go anywhere. This point actually seems to be more of a sticking point, since each app would require manual intervention for policy assignment.

**Comment by monde** [comment]
Notes:

API endpoint to do this is:
[Update application policy](https://developer.okta.com/docs/reference/api/apps/#update-application-policy)
`PUT  /api/v1/apps/${applicationId}/policies/${policyId}`

That endpoint is not in the openapi spec used to generated Okta's SDK [oas v2 - okta/okta-management-openapi-spec](https://github.com/okta/okta-management-openapi-spec). And it isn't present in the upcoming oas v3 spec. So it essentially is not on the Okta SDK's roadmap.

We could implement this behavior in the [local sdk package](https://github.com/okta/terraform-provider-okta/tree/master/sdk) as a stop gap until okta-sdk-golang has support for that endpoint. We need to prioritize this feature relative to our overall roadmap.

**Comment by ianwinsemius** [comment]
I'm not having any success using that endpoint on either our sandbox without OIE (which isn't surprising), or our OIE preview, which is where I would expect it to work. I get a return like the one below (with unique error IDs):
```
{
    "errorCode": "E0000005",
    "errorSummary": "Invalid session",
    "errorLink": "E0000005",
    "errorId": "oaeqmWG_u4dR0qJstG5BbHNVQ",
    "errorCauses": []
}
```

Its certainly possible that I'm doing something wrong, but I'm using the same credentials and methodology that I am able to make other API calls to Okta.

If these endpoints are in fact available, and our team is able to get them to return successfully, what would the timeline for implementation in the Terraform provider be? Really, the existence of these resources in the terraform provider is the hope, and I was mostly asking about the API to understand whether I was looking to the right team for answers.

**Comment by ianwinsemius** [comment]
So I have managed to successfully set a policy through the API with the endpoint 
{{url}}/api/v1/apps/{{appID}}/policies/{{policyID}} on our OIE sandbox. 

I'm curious, if the API endpoint exists, and is functional, does that imply that the terraform provider will include it at some point down the road?

**Comment by monde** [comment]
I see okta-sdk-golang has an `UpdateApplicationPolicy` on the application resource now:
https://github.com/okta/okta-sdk-golang/blob/66ce9052167bc3da973e2685c378a46937ae1dd5/okta/application.go#L852-L868
That was brought since this ticket was opened. So we can support updating a policy now. @ianwinsemius can you do a PR? I'm not sure when I might get to the coding on this otherwise.

**Comment by monde** [comment]
Released https://github.com/okta/terraform-provider-okta/releases/tag/v3.31.0
