### ISSUE TITLE
resource okta_policy_signon priority error

### ISSUE THREAD

**Issue by kasirajans** [okta/terraform-provider-okta#1028]
I'm trying to create a sign-on policy in the below order but it errors with the message `failed to create sign-on policy: provided priority was not valid, got: 3, API responded with: 1. See schema for attribute`. variable type for the below data is a list of objects

Anything wrong?
```
[
    {
      name          = "admin-team"
      enable_policy = true
      description   = "Policy For Admin Team"
      groups        = ["admin-team"]
      priority      = 1
      rule          = {
        name        = "allow-all"
        enable_rule = true
        priority    = 1
      }
    },
    {
      name          = "hr-team"
      enable_policy = true
      description   = "Policy For HR Team"
      groups        = ["hr-team"]
      priority      = 2
      rule          = {
        name        = "deny-all"
        enable_rule = true
        priority    = 1
      }
    },
    {
      name          = "development-team"
      enable_policy = true
      description   = "Policy For Dev Team"
      groups        = ["development-team"]
      priority      = 3
      rule          = {
        name        = "deny-all"
        enable_rule = true
        priority    = 1
      }
    }
  ]
```

```
│ Error: failed to create sign-on policy: provided priority was not valid, got: 3, API responded with: 1. See schema for attribute details
│ 
│   with okta_policy_signon.signon[2],
│   on main.tf line 27, in resource "okta_policy_signon" "signon":
│   27: resource "okta_policy_signon" "signon" {
│ 
```

**Terraform and Provider version** 
```
terraform {
  required_version = "1.1.7"
  required_providers {
    okta = {
      source  = "okta/okta"
      version = "3.22.1"
    }
  }
}
```

**Comment by monde** [comment]
Hi @kasirajans . Can you provide me a terraform config example so I can attempt to reproduce your issue? Thanks. Also, if you run your command with TF_LOG=1 you'll be able to see the API calls at issue and if you can identify those that will also help focus my investigation.

**Comment by kasirajans** [comment]
Thanks @monde for you comments  I have added you as collaborator to my private project. Will that helps? 

Regarding Trace part I do see all the sign on policies created successfully with 2XX response per Trace but resource are marked as tainted.  Hopefully you can able to reproduce the issue with my project clone.



```
  # module.sign_on.okta_policy_signon.signon[1] is tainted, so must be replaced-/+ resource "okta_policy_signon" "signon" {
      ~ id              = "00p4bmx0zdWOfiRmf5d7" -> (known after apply)
        name            = "hr-team"
        # (4 unchanged attributes hidden)
    }

  # module.sign_on.okta_policy_signon.signon[2] is tainted, so must be replaced-/+ resource "okta_policy_signon" "signon" {
      ~ id              = "00p4bmxijpUN2xVzc5d7" -> (known after apply)
        name            = "development-team"
        # (4 unchanged attributes hidden)
    }
```

**Comment by mnovitsk** [comment]
I'm also experiencing similar issues when creating a sign on policy. Whatever policy that is created via Terraform gets sent immediately to priority 1 regardless of what priority you try to assign to it. It seems like the backend API just defaults each new policy to priority 1 and then errors out when trying to assign it to whatever priority value was passed in the Terraform configuration.

**Comment by kasirajans** [comment]
Any update @monde ?

**Comment by monde** [comment]
Triaging all the issues that have this bug dealing with a priority property.

**Comment by monde** [comment]
"bug(s) with resources having a priority setting" #1198

**Comment by monde** [comment]
0 value integers address [v3.44.0](https://github.com/okta/terraform-provider-okta/releases/tag/v3.44.0) release.

Probably not related to this thread. On second look, depends_on can help chain priority values that need to set synchronously.
