### ISSUE TITLE
Impending API Deprecation: Email Templates

### ISSUE THREAD

**Issue by tgoodsell-tempus** [okta/terraform-provider-okta#1031]
Saw in the Okta support panel that the API we're using for the email template resource will be removed in favor of the branding APIs. Creating this issue as a notification and tracker since we'll probably want to update the resources, or if the API changes are significant enough, create new ones to replace these.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- `okta_template_email`

### References

[Support Notification](https://support.okta.com/help/s/olc-announcement-notification/aMh4z0000004ClbCAE/service-notification-endoflife-for-internal-apis-that-manage-email-templates?language=en_US
)

https://support.okta.com/help/s/olc-announcement-notification/aMh4z0000004ClbCAE/service-notification-endoflife-for-internal-apis-that-manage-email-templates?language=en_US

**Comment by monde** [comment]
@tgoodsell-tempus thanks for posting this up! There was discussion today in the Okta DevEx private Slack channel about how we are going to deal with this for our openapi spec and all of our language SDKs.

**Comment by phaseOne** [comment]
Is [the refactor_email_templates branch](https://github.com/okta/terraform-provider-okta/tree/refactor_email_templates) the intended destination for the work that will address the deprecation of this API with the addition of the email template endpoints in the Brands API (`EmailTemplate`* resources in golang SDK)?

**Comment by phaseOne** [comment]
Yep looks like this will be resolved in #1089! Thanks @monde!

**Comment by monde** [comment]
@tgoodsell-tempus @phaseOne `okta_template_email` is deprecated now. Please switch over to the `okta_email_customization` resource.  https://registry.terraform.io/providers/okta/okta/latest/docs/resources/email_customization
