### ISSUE TITLE
scoped okta_user_admin_roles

### ISSUE THREAD

**Issue by phi1ipp** [okta/terraform-provider-okta#1038]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Is there a way to make `okta_user_admin_roles` scoped to a specific group/app? I know I can do that through a creation of an admin group, but maybe I'm just missing something?

### New or Affected Resource(s)

- okta_user_admin_roles

### Potential Terraform Configuration

```hcl
resource okta_user user-1 {
   ...
}

resource okta_user_admin_roles group-x-admin {
    user_id          = okta_user.test.id
    admin_roles = [ "APP_ADMIN" ]
    app_id          = data.okta_app_saml.app-x.id
}

```

**Comment by monde** [comment]
Thanks @phi1ipp I'll have to look into this, I don't have an answer top of mind without looking at some code.

**Comment by phi1ipp** [comment]
Sure @monde , I'm trying to see if it can be similar to `okta_group_role`

**Comment by monde** [comment]
The ask is for `app_id`, and `group_id` to be added to `okta_user_admin_roles`. In the abstract it seems we could add it in.

Currently, when a okta_user_admin_roles is created it associates roles to a user here:
https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_user_admin_roles.go#L50-L60
which calls to here:
`_, _, err := client.User.AssignRoleToUser(ctx, userID, okta.AssignRoleRequest{Type: role},`
https://github.com/okta/terraform-provider-okta/blob/2b98590aad77acbe39d8df2f3cc17cd80237d32c/okta/user.go#L188

In the case of group
okta-sdk-golang has an `AssignRoleToGroup` function:
https://github.com/okta/okta-sdk-golang/blob/master/okta/group.go#L351-L373
so it seems that coudl be utilized.

I'm not seeing the same 1-1 equivalence in application.go or in the Okta API https://developer.okta.com/docs/reference/api/apps/ just doing a quick search. @phi1ipp if you can find me the public API endpoints to associate a role to an application (not sure that is a thing) point me at the documentation.

**Comment by phi1ipp** [comment]
@monde, I think it's here https://developer.okta.com/docs/reference/api/roles/#group-administrator-role-group-targets

Check `PUT` a bit below `GET` operations (https://developer.okta.com/docs/reference/api/roles/#add-a-group-target-to-a-group-administrator-role-given-to-a-user)

**Comment by monde** [comment]
Thanks, okta-sdk-golang has that in `func (m *UserResource) AddGroupTargetToRole(ctx context.Context, userId string, roleId string, groupId string) (*Response, error)`

https://github.com/okta/okta-sdk-golang/blob/master/okta/user.go#L1097-L1113

**Comment by phi1ipp** [comment]
I think you also have this one `func (m *UserResource) AddApplicationTargetToAdminRoleForUser(ctx context.Context, userId string, roleId string, appName string) (*Response, error)` 
https://github.com/okta/okta-sdk-golang/blob/d80a944fe45625469479a6aaf9d026b7c344836b/okta/user.go#L1000

and `func (m *UserResource) AddApplicationTargetToAppAdminRoleForUser(ctx context.Context, userId string, roleId string, appName string, applicationId string) (*Response, error) `
https://github.com/okta/okta-sdk-golang/blob/d80a944fe45625469479a6aaf9d026b7c344836b/okta/user.go#L1038
