### ISSUE TITLE
crash/panic - okta_user_schema_property

### ISSUE THREAD

**Issue by eephillip** [okta/terraform-provider-okta#1047]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/okta/okta v3.22.1
```

### Affected Resource(s)

- okta_user_schema_property

### Panic Output

```
╷
│ Error: Plugin did not respond
│
│   with module.auth_server.okta_auth_server_claim.resource_claims["my_var_name"],
│   on modules/auth_server/main.tf line 201, in resource "okta_auth_server_claim" "resource_claims":
│  201: resource "okta_auth_server_claim" "resource_claims" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.auth_server.okta_auth_server_claim.resource_claims["threat_access_roles"],
│   on modules/auth_server/main.tf line 201, in resource "okta_auth_server_claim" "resource_claims":
│  201: resource "okta_auth_server_claim" "resource_claims" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.user_schema.okta_user_schema_property.my_var_name,
│   on modules/user_schema/schema.tf line 1, in resource "okta_user_schema_property" "my_var_name":
│    1: resource "okta_user_schema_property" "my_var_name" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-okta_v3.22.1 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 69 [running]:
github.com/okta/terraform-provider-okta/okta.buildEnum({0xc000282900, 0x4, 0x0}, {0xc00041a460, 0x6})
	github.com/okta/terraform-provider-okta/okta/user_schema_property.go:313 +0x2a9
github.com/okta/terraform-provider-okta/okta.buildUserCustomSchemaAttribute(0xc00041a250)
	github.com/okta/terraform-provider-okta/okta/user_schema_property.go:367 +0x1cd
github.com/okta/terraform-provider-okta/okta.resourceUserSchemaCreateOrUpdate({0x1b0e108, 0xc00051c300}, 0xc0007936c0, {0x18afa80, 0xc000242270})
	github.com/okta/terraform-provider-okta/okta/resource_okta_user_custom_schema_property.go:112 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0004500e0, {0x1b0e098, 0xc000664000}, 0x2, {0x18afa80, 0xc000242270})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:341 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004500e0, {0x1b0e098, 0xc000664000}, 0xc000468b60, 0xc000122600, {0x18afa80, 0xc000242270})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000440f00, {0x1b0e098, 0xc000664000}, 0xc00007eb90)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000284e80, {0x1b0e140, 0xc000108270}, 0xc0002a4380)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1988f40, 0xc000284e80}, {0x1b0e140, 0xc000108270}, 0xc000048480, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00029aa80, {0x1b1dd70, 0xc000198180}, 0xc00054e000, 0xc0004b1680, 0x20b6980, 0x0)
	google.golang.org/grpc@v1.41.0/server.go:1279 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00029aa80, {0x1b1dd70, 0xc000198180}, 0xc00054e000, 0x0)
	google.golang.org/grpc@v1.41.0/server.go:1608 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.41.0/server.go:923 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.41.0/server.go:921 +0x294

Error: The terraform-provider-okta_v3.22.1 plugin crashed!
```

### Expected Behavior

Would expect to be able to destroy and add custom profile attributes at will.

### Actual Behavior

The provider destroyed this custom attribute, when it was re-added the panic is consistently encountered. 
The okta instance also now appears to be in an unstable state. Adding the same variable name as a custom attribute using the admin console will cause an unspecified "Internal Server Error"

![image](https://user-images.githubusercontent.com/470759/162053601-78cc5b72-53f0-4c19-bca9-993ab55eede3.png)

### References

- #0000

**Comment by monde** [comment]
Thanks @eephillip look into this, thanks for the stack trace, that is helpful.

**Comment by eephillip** [comment]
Interestingly enough after a couple hours, the okta instance resolved whatever state it found itself in and was able to re-insert the custom attribute, without panicking.

**Comment by monde** [comment]
I can still put some bumpers on the panic, what do you think @eephillip ? https://github.com/okta/terraform-provider-okta/pull/1048/files

**Comment by eephillip** [comment]
@monde yeah I like it, and if it trips, would it be able to output some details about the bad endpoint return?
Would be nice be able to attach something to the okta support case showing them the failed api call. Perhaps that is already available with the debug option.

**Comment by monde** [comment]
@eephillip in fiddling around in this [goplayground example](https://go.dev/play/p/__q4b1QKvcZ) the only thing I can see on the function `func buildEnum(ae []interface{}, elemType string) ([]interface{}, error)` is the slice could possibly have an empty value that is actually nil. The casting check I added to `buildEnum` will protect against that. I feel like this is a good input protection. We have no way of ensuring the consistency of output from the API, only handling it in a flexible manner. The rest of the items in the `enum` interface slice are being set with typed values. In this implementation an implied value would be nil on the continue when casting fails.

**Comment by monde** [comment]
Actually, I'm looking at this a second time. My point about nil is invalid.

**Comment by monde** [comment]
Second pass with unit tests to illustrate intent is better (imo) https://github.com/okta/terraform-provider-okta/pull/1048/files
