### ISSUE TITLE
okta_auth_server import failing

### ISSUE THREAD

**Issue by chlsmith** [okta/terraform-provider-okta#105]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.10

### Affected Resource(s)

* okta_auth_server

### Terraform Configuration Files

```hcl
resource "okta_auth_server" "default" {
  audiences   = ["api://default"]
  description = "Default Authorization Server for your Applications"
  name        = "default"
  issuer_mode = "ORG_URL"
  status      = "ACTIVE"
}


### Debug Output

https://gist.github.com/chlsmith/cffdc947c8c1e0ddfb6686449e46ea12

### Panic Output


### Expected Behavior

Would expect to simply import the existing auth server.

### Actual Behavior

Crash without any state imported

### Steps to Reproduce

terraform import -var okta_api_token=$okta_api_token -var environment=$environment module.okta.okta_auth_server.default $AuthServerId



### Important Factoids

I'm supplying the api token directly via the command line, and using "environment" within mod_locals to pick out the appropriate Url and Org for the okta provider configuration.

### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor documentation? For example:
--->

* #0000

**Comment by thekbb** [comment]
I did successfully import an `okta_auth_server` with terraform `0.12.24` today. maybe upgrade?

**Comment by Ruffio** [comment]
@chlsmith what version are you using? Could you try with latest official version?
