### ISSUE TITLE
`okta_user_admin_roles` assignment gets removed by not having admin_roles defined for the user

### ISSUE THREAD

**Issue by phi1ipp** [okta/terraform-provider-okta#1052]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.0.8
on darwin_amd64
+ provider registry.terraform.io/okta/okta v3.22.1
```
### Affected Resource(s)

- okta_user_admin_roles

### Terraform Configuration Files

```hcl
resource "okta_user" "panther-report" {
  first_name   = "..........."
  last_name    = ".............."
  display_name = ".............."
  login        = "xxxxxxxxx@xyz.xyz"
  email        = "xxxxxxxxx@xyz.xyz"
}

resource "okta_user_admin_roles" "panther-report" {
  user_id     = okta_user.panther-report.id
  admin_roles = ["REPORT_ADMIN"]
}
```

### Debug Output

https://gist.github.com/phi1ipp/9758f57296a43bb38412037c01d8b3e9

### Expected Behavior

There should not be any changes detected/planned on subsequent calls with the same configuration 
### Actual Behavior

```
  # okta_user.panther-report will be updated in-place
  ~ resource "okta_user" "panther-report" {
      ~ admin_roles               = [
          - "REPORT_ADMIN",
        ]
        id                        = "00u16sqbudvJ24xxM0h8"
        # (9 unchanged attributes hidden)
    }
```
### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

**Comment by monde** [comment]
Thanks for the details @phi1ipp , I'll look into it.

**Comment by eephillip** [comment]
Duplicate of https://github.com/okta/terraform-provider-okta/issues/618 I think.
Needs the lifecycle statement as a work around

**Comment by phi1ipp** [comment]
Thx @eephillip , it's indeed the same thing.
