### ISSUE TITLE
`okta_group_role` : Unable to add application to APP_ADMIN role group 

### ISSUE THREAD

**Issue by BalaGanaparthi** [okta/terraform-provider-okta#1054]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
     Terraform v1.1.4
     on linux_amd64
     + provider registry.terraform.io/okta/okta v3.23.0

### Affected Resource(s)

- okta_group_role

### Terraform Configuration Files

```hcl
variable "group_roles_list" {
  description = "List of Group Roles mappings."
  type = map(object({
    group_name            = string
    role_type             = string
    target_group_list     = list(string)
    target_app_list       = list(string)
    disable_notifications = bool
  }))
}

group_roles_list={
  1 = {
    group_name            = "App A: User Group Admins"
    role_type             = "GROUP_MEMBERSHIP_ADMIN"
    target_group_list     = ["App A: Users Group"]
    target_app_list       = []
    disable_notifications = false
  },
  2 = {
    group_name            = "App A: App-Admins Group"
    role_type             = "APP_ADMIN"
    target_group_list     = []
    target_app_list       = ["App-A"]
    disable_notifications = false
  }
}

# 
# group_name_id_map and app_names_ids_map are passed as module parameters
#
resource "okta_group_role" "group_role_assignments" {
  for_each = var.group_roles_list

  group_id              = var.group_name_id_map[each.value.group_name]
  role_type             = each.value.role_type
  target_group_list     = [for group_name in each.value.target_group_list : var.group_name_id_map[group_name]]
  target_app_list       = each.value.target_app_list
  # target_app_list       = [for app_name in each.value.target_app_list : var.app_names_ids_map[app_name]]
  # target_app_list       = [for app_name in each.value.target_app_list : join(".", [app_name, var.app_names_ids_map[app_name]]) ]
  disable_notifications = each.value.disable_notifications
}
```

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

Panic output displayed during the first time execution 
(App-A exists in the system, tried with label, app id, label.appid)
    
    Error: unable to add app targets to role assignment IFIFAX2BIRGUSTQ for group 00g3fugeseSqJbJ0C1d7: failed to add an app 
    target to an app administrator role given to a group: the API returned an error: Not found: Resource not found: App-A (App)
   
    with module.group_roles.okta_group_role.group_role_assignments["2"],
    on modules/group_roles/main.tf line 1, in resource "okta_group_role" "group_role_assignments":
    1: resource "okta_group_role" "group_role_assignments" {
 
Panic output displayed from second and consecutive execution

    Error: failed to assign role APP_ADMIN to group 00g3fugeseSqJbJ0C1d7: the API returned an error: The role specified is already 
    assigned to the user.
    
    with module.group_roles.okta_group_role.group_role_assignments["2"],
    on modules/group_roles/main.tf line 1, in resource "okta_group_role" "group_role_assignments":
    1: resource "okta_group_role" "group_role_assignments" {
 
    ERROR: 1

### Expected Behavior

Application assigned to group assigned with `APP_ADMIN` role 

### Actual Behavior

The above mentioned panic happened

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by monde** [comment]
Thanks for all the details @BalaGanaparthi that will help greatly when I look into this.

**Comment by powellchristoph** [comment]
I get the same issue attempting to assign the `GROUP_MEMBERSHIP_ADMIN` role to a group.

```
  # okta_group_role.group_membership_admin_role["a_group"] will be created
  + resource "okta_group_role" "group_membership_admin_role" {
      + disable_notifications = true
      + group_id              = "1234567890"
      + id                    = (known after apply)
      + role_type             = "GROUP_MEMBERSHIP_ADMIN"
      + target_group_list     = [
          + "a_different_group",
        ]
    }
```
    
```
    │ Error: failed to assign role GROUP_MEMBERSHIP_ADMIN to group 1234567890: the API returned an error: The role specified is already assigned to the user.
```

**Comment by fatbasstard** [comment]
Also "randomly" hitting this:

```Error: failed to assign role USER_ADMIN to group 00g93e41x3GMV8DBA0i7: the API returned an error: The role specified is already assigned to the user.```

**Comment by fatbasstard** [comment]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/35613489/207293148-e883c323-175c-43f9-850a-f57b655deef4.png">

This might be related. Does the API have the "max 3" limitation?

**Comment by jakekiernanheb** [comment]
I'm getting an error with this resource:
Error: failed to assign role ACCESS_REQUESTS_ADMIN to group XXXXX : the API returned an error: Bad request.

**Comment by powellchristoph** [comment]
This is still an active issue. Can we ensure it stays open?

**Comment by jarodr47** [comment]
When passing the value for the `target_app_list` use `oidc_client.<app_id>` instead of using the `app name` or `appName.app_id`. This worked for my team.
