### ISSUE TITLE
`okta_policy_profile_enrollment_apps` :::  Api validation failed: Policy mappings are no longer supported on this endpoint

### ISSUE THREAD

**Issue by BalaGanaparthi** [okta/terraform-provider-okta#1055]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

    Terraform v1.1.4
    on linux_amd64
    + provider registry.terraform.io/okta/okta v3.23.0

### Affected Resource(s)

- okta_policy_profile_enrollment_apps

### Terraform Configuration Files

```hcl
resource "okta_policy_profile_enrollment_apps" "profile_enrollment_apps" {
  policy_id = okta_policy_profile_enrollment.profile_enrollment.id
  apps      = [okta_app_oauth.applications_oauth.id]
}
```

### Panic Output

```panic
# module.profile_enrollment.okta_policy_profile_enrollment_apps.profile_enrollment_apps will be created
  + resource "okta_policy_profile_enrollment_apps" "profile_enrollment_apps" {
      + apps              = [
          + "0oa3g0n8u2M7lBITd1d7",
        ]
      + default_policy_id = (known after apply)
      + id                = (known after apply)
      + policy_id         = "rst3g3h7d1gSWiNaR1d7"
    }
...
...
...
module.profile_enrollment.okta_policy_rule_profile_enrollment.profile_enrollment_rule: Creation complete after 1s [id=rul3g3h7d2uRBb9gE1d7]
╷
│ Error: failed to add an app to the policy, the API returned an error: Api validation failed: Policy mappings are no longer supported on this endpoint.
│ 
│   with module.profile_enrollment.okta_policy_profile_enrollment_apps.profile_enrollment_apps,
│   on modules/profile_enrollment/main.tf line 30, in resource "okta_policy_profile_enrollment_apps" "profile_enrollment_apps":
│   30: resource "okta_policy_profile_enrollment_apps" "profile_enrollment_apps" {
│ 
╵
ERROR: 1
```

### Expected Behavior

```text
Application assigned to profile enrollment policy
```

### Actual Behavior

```text
Above mentioned error occurred during apply 
```

### Steps to Reproduce

```text
1. Create App
2. Create Profile_Enrollment polict
3. Assign App to profile enrollment policy
```

1. `terraform apply`

### Important Factoids

```text
1. Application created
2. Profile enrollment created 
```

### References

- #0000

**Comment by monde** [comment]
Thanks @BalaGanaparthi . Given the error did you experiment with other ways of performing the operation? I think you have other issues with a classic org, do you have a feel if this is an classic org vs identity engine operation?

**Comment by BalaGanaparthi** [comment]
@monde, I am using OIE org. 
I am not aware if there is any other approach to assign app to the profile enrollment policy via Okta's terraform resource. I could use the provisioner (local-exec) route.. but din't want to use that approach.

**Comment by monde** [comment]
@BalaGanaparthi , noted, I'll be looking into this.

**Comment by monde** [comment]
@BalaGanaparthi I looked at the monolith's source code and this error is coming from orgs having the `SHARED_APP_SIGN_ON_POLICIES` feature flag. I'm not sure why orgs have that FF. I'm updating the documentation for that resource.

**Comment by jackvaughanjr** [comment]
@monde curious what the fix here was for the end user? I'm receiving this same error when attempting to add an app to a policy via the `/mappings` endpoint.
