### ISSUE TITLE
Change password set for okta_user

### ISSUE THREAD

**Issue by MichaelOtte-lhsystems** [okta/terraform-provider-okta#1060]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Change/Reset PW on okta_user should be possible without "old_password" property if password was changed outside of TF provider.

The process is:
1. to set the 'old_password' (you have to gather that from the user or set as admin in WEB-UI) + set 'password' to new password 
2. terraform apply
3. remove 'old_password' property from "okta_user" resource
4. terraform apply (again)

with the API you can set directly the PW  without old_password like https://developer.okta.com/docs/reference/api/users/#request-example-19

curl -v -X POST
-H "Accept: application/json"
-H "Content-Type: application/json"
-H "Authorization: SSWS ${api_token}"
-d '{
"credentials": {
"password" : { "value": "uTVM,TPw55" }
}
}' "https://${yourOktaDomain}/api/v1/users/00ub0oNGTSWTBKOLGLNR"

could the resource 'okta_user' make use of this API request and 'old_password' property becomes obsolete?

### New or Affected Resource(s)

- okta_user

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by monde** [comment]
Excellent details @MichaelOtte-lhsystems , pointing out the API documentation is very helpful. Do you have a hand at golang coding, would you like to work on PR?

**Comment by lucascantor** [comment]
For what it's worth, this proposed enhancement would also obviate the issue of the Okta Terraform provider not being able to change passwords for users' whose Okta password policy prohibits self-service password change.

This is an issue I just ran into today when trying to import hundreds of "service account" users into our Terraform state:
```
Error: failed to update user's password: the API returned an error: Change password not allowed on specified user.

  on service_accounts.tf line 32, in resource "okta_user" "service_accounts":
  32: resource "okta_user" "service_accounts" {
```

I'm not familiar with golang, but I'd guess [`PartialUpdateUser`](https://github.com/okta/okta-sdk-golang/blob/2e0d27210f938215f3e3b8d5d47f1b93bdc5b92c/okta/user.go#L182-L203) could be added to the logic within [`if passwordChange`](https://github.com/okta/terraform-provider-okta/blob/b2651746acc7128e8fcb336e69ebc151b6c16477/okta/resource_okta_user.go#L600-L620).

**Comment by monde** [comment]
@BalaGanaparthi has PR #1061 for this

**Comment by monde** [comment]
Updated the implementation in PR #1061

**Comment by lucascantor** [comment]
Amazing - @BalaGanaparthi and @monde thank you both so much.

Any chance a new release could be made to make this functionality available soon? 🙏🏼
