### ISSUE TITLE
Okta API Optimization for /api/v1/apps*

### ISSUE THREAD

**Issue by pc-mrousseau** [okta/terraform-provider-okta#1062]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Upon using the terraform provider for Okta pretty extensively, we've been experiencing some significant pain with the Okta API limits. Further researching into those it appears that the provider might make excessive use of the `/api/v1/apps*` API, as opposed to `/api/v1/apps/{id}`. The latter has a 500/m API limit but the former only has 100/m.

Ideally - the provider should do a single `GET /api/v1/apps` (List applications) at the onset and reuse that data to correlate the appropriate IDs of the terraform okta resources going forward. 

I have reviewed some of the data_source_okta_app* components and not sure I've found anything obviously wrong. This issue may also reside with the underlying way the Okta SDK implements the client.Application.

### New or Affected Resource(s)

Not 100% positive but assuming those calls are related to those resources:
* okta_app_saml
* okta_app_group_assignments

### Potential Terraform Configuration

Not related to any particular configuration.

### References

* [Apps API Reference](https://developer.okta.com/docs/reference/api/apps/)
* [Management rate limits](https://developer.okta.com/docs/reference/rl-global-mgmt/)

**Comment by monde** [comment]
@pc-mrousseau thank you for all of the detailed background. I'm in the middle of some upgrade work to the provider, hopefully I can see this addressed in that work as well.

**Comment by pc-mrousseau** [comment]
Amazing, thanks! Might be a great quality of life improvement for everyone.

**Comment by karlsequeira** [comment]
Please do let me know if this can be looked at sooner. Getting this on a prod deployment [/api/v1/apps*]  and I cant deploy anything to prod as the plan wont complete. I am getting this on okta_app_user_schema_property but that references okta_app_group_assignment

**Comment by monde** [comment]
@karlsequeira can you post up some example terraform config representative of how you are seeing this? Give me an idea about numbers of objects we are talking about (users, groups, apps, etc.). It may not be related but if I can get an estimate of objects and objects types I might be able suss out subtle performance optimizations given the config example. You can also email me your config mike.mondragon@okta.com if you'd prefer that.

**Comment by monde** [comment]
@pc-mrousseau @karlsequeira , I had a typo on my previous comment about samples. Consider my request as being for each you. Thanks!

**Comment by karlsequeira** [comment]
Yes. I will send you an email . Do let me know if I can schedule a support call.  I have deployed these before and not had an issue. I can see if I can go to an older version of the provider. Really appreciate your help.

**Comment by pc-mrousseau** [comment]
For the okta_app_group_assignment I believe it's in the 500-600 ballpark. The terraform is a bit tricky basically using a from json and for_each loop. Short answer is, it's many objects :)

**Comment by karlsequeira** [comment]
does it loop through all the users in the group as the group is just 1?

**Comment by monde** [comment]
@karlsequeira @pc-mrousseau I did some digging on a scenario that @karlsequeira gave me. I have 38K users associated with a saml app. In my config I'm making use of data source `okta_app_saml` (but this would be true for `okta_app_oauth`, and `okta_app` as well). During plan the data source will fetch all of the users associated with the app. Here is the call stack.

- https://github.com/okta/terraform-provider-okta/blob/master/okta/data_source_okta_app_saml.go#L314
- https://github.com/okta/terraform-provider-okta/blob/c9629563074433c0233d50a62d87957270bab939/okta/app.go#L702
- https://github.com/okta/terraform-provider-okta/blob/c9629563074433c0233d50a62d87957270bab939/okta/app.go#L512-L514
Landing this call through okta-sdk-golang `client.Application.ListApplicationUsers(ctx, id, &query.Params{Limit: defaultPaginationLimit})` 
https://github.com/okta/okta-sdk-golang/blob/66ce9052167bc3da973e2685c378a46937ae1dd5/okta/application.go#L958

With 38K users, the `/api/v1/apps/{appId}/users` endpoint will get called 193 times triggering rate limit alarms.

All of the apps have `skip_users` and `skip_groups` flags on them https://registry.terraform.io/providers/okta/okta/latest/docs/data-sources/app_saml . If you know your data source doesn't need user data as `users` or group data as `groups` on the data source then use the skip flags. In the sample config @karlsequeira gave me, they should make use of the `skip_users` and `skip_groups` flags. There isn't any optimization to be had here other than utilizing the skip flags that is why they were added.

I will close this issue for now.

/cc @noinarisak
