### ISSUE TITLE
okta_auth_server_policy priority argument not working as expected

### ISSUE THREAD

**Issue by LeeTann** [okta/terraform-provider-okta#1065]
### Expected Behavior

When setting the priority argument for okta_auth_server_policy from 1 to 10, I expect okta to sort the application from 1 to 10.

### Actual Behavior

I'm not sure what okta does behind the scene, but it does not always sort the app priorities in the correct order. Each time terraform apply happens, okta tries to sort it the app but misses the order of a few apps and put in the the wrong position. This can be resolved by running the terraform apply command a few more times until okta finally sorts out the priority correctly. Normally 3-4 applies until the expect order occurs.

### Steps to Reproduce

Create 10 apps and assign each app a priority from 1 to 10 utilizing the okta_auth_server_policy and run terraform apply. 

Example screenshot:
The drupal app is given a priority of 4 but in okta it is given a priority of 3
![image](https://user-images.githubusercontent.com/42705234/163653312-9587b8cc-4335-4c34-a3d9-88de16fc475f.png)

**Comment by monde** [comment]
Thanks @LeeTann , I'll be looking into this.

**Comment by LeeTann** [comment]
Thanks monde! Looking forward to see what you find and if there's a fix to this issue. Thanks again for looking into it
