### ISSUE TITLE
Please enforce or at least document the group rule name length limit

### ISSUE THREAD

**Issue by relsqui** [okta/terraform-provider-okta#1067]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When I `terraform plan` a group rule resource with a name greater than 50 characters, I'd like that plan to fail with an error. Currently, it succeeds and then fails to apply, which is more dangerous for state integrity.

Also, the apply error message tells me the name is too long, but the provider documentation doesn't give a length limit. I had to go find it in the API docs.

### New or Affected Resource(s)

- `okta_group_rule` and possibly others that are also missing documentation/validation

### Potential Terraform Configuration

n/a

### References

None that I could find.

**Comment by monde** [comment]
Hi @relsqui I can see updating the docs to say ["name of the Group rule (min character 1; max characters 50)" ](https://developer.okta.com/docs/reference/api/groups/#request-parameters-9) for the [group rule name property](https://github.com/okta/terraform-provider-okta/blame/master/website/docs/r/group_rule.html.markdown#L32). But I wouldn't want to get into the habit of putting granular input validators like this into the provider's code should the Okta API itself change.

**Comment by relsqui** [comment]
I don't quite follow the logic -- if the API changes, the documentation will also need to be updated, no? -- but I appreciate the quick response and the change. :)

**Comment by monde** [comment]
> I don't quite follow the logic -- if the API changes, the documentation will also need to be updated, no? -- but I appreciate the quick response and the change. :)

The Okta Terraform Provider has a layer of behavior it models on the public Okta API. The Okta core reflected through the public Okta API does input validation. The Okta Terraform Provider working as a small application that makes use of the Okta API should be doing the least amount of input validation as possible for a number of reasons. Okta API does input validation and coupling an open source project to do input validation on a service it has no authority over are the two biggest it seems to me.
