### ISSUE TITLE
Terraform crashes when creating a Policy Rule

### ISSUE THREAD

**Issue by mfulgo** [okta/terraform-provider-okta#107]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.12.24
+ provider.okta v3.2.0
```

### Affected Resource(s)

* `okta_auth_server_policy_rule`

### Terraform Configuration Files

```hcl
resource "okta_auth_server_policy_rule" "grant_all_scopes" {
  auth_server_id = okta_auth_server.example.id
  policy_id = okta_auth_server_policy.example.id
  name = "Grant all scopes"
  priority = 1
  grant_type_whitelist = ["client_credentials"]
  # group_whitelist = ["EVERYONE"]
  scope_whitelist = ["*"]
}
```

### Debug Output

https://gist.github.com/mfulgo/24ad21b611d9218d6c0ce2395f33f8b3

### Panic Output

(Omitted since there was too much in there to scrub.)

### Expected Behavior

Terraform shouldn't crash before saving the resource's state.

### Actual Behavior

Terraform crashed. The Rule was created in the Authorization Server's Policy but Terraform crashed before being able to add it to the state file.

### Steps to Reproduce

Just run a `terraform apply` with a policy rule like that defined above. **Uncommenting `group_whitelist` resolves the crash.** Interestingly, specifying any other grant types has Okta return an error about needing to specify either a people or group filter, which terraform correctly reports.

**Comment by mfulgo** [comment]
(Commenting to keep the issue open.)

**Comment by Jorge-Rodriguez** [comment]
Can reproduce with:

Terraform v0.12.28
+ provider.okta v3.4.1

**Comment by mithewt** [comment]
Reproduced with Terraform v0.13 with provider.okta v3.4.1. The logs appear to show it crashing inside okta.setPeopleAssignments when the rule's POST response looks like `"conditions": { "people": { "users": { "exclude": [] } }}`

**Comment by mfulgo** [comment]
Any chance of this getting fixed soon? (Also commenting to remove the stale label.)

**Comment by bogdanprodan-okta** [comment]
Hi @mfulgo, @Jorge-Rodriguez, @mithewt! I've tried to reproduce it, but no luck. Is this still an issue?

**Comment by Jorge-Rodriguez** [comment]
We moved away from Okta in our project as the cost of licenses to support our use case far exceeded our budget, so I'm no longer in a position where I can verify this, sorry.
