### ISSUE TITLE
okta_idp_social attributes keeps reapplying the same changes everytime

### ISSUE THREAD

**Issue by naveen-vijay** [okta/terraform-provider-okta#1071]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.1.8
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.10.0
+ provider registry.terraform.io/okta/okta v3.23.0

### Affected Resource(s)

- okta_idp_social

### Terraform Configuration Files

![CleanShot 2022-04-18 at 19 28 38](https://user-images.githubusercontent.com/342580/163893041-30c49ba4-1fde-4dc5-9c01-e518fa198593.png)

### Expected Behavior

Terraform should apply and subsequent plans should not include any changes with this resource.

### Actual Behavior

**protocol_type**, **groups_action** requires changes every time, though the Terraform Config specifies the same configuration.

### Steps to Reproduce

1. `terraform apply`

**Comment by monde** [comment]
Thanks @naveen-vijay I will look into this.

**Comment by naveen-vijay** [comment]
Commenting to keep the issue open

**Comment by monde** [comment]
not stale
