### ISSUE TITLE
okta_app_oauth resource doesn't permit login_scopes to contain "groups"

### ISSUE THREAD

**Issue by fredifice** [okta/terraform-provider-okta#1073]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.1.7
provider registry.terraform.io/okta/okta v3.24.0

### Affected Resource(s)

- okta_app_oauth

### Terraform Configuration Files

```hcl
resource "okta_app_oauth" "ng_SPA" {
  accessibility_self_service = false
  app_links_json = jsonencode(
    {
      oidc_client_link = true
    }
  )
  app_settings_json   = jsonencode({})
  auto_key_rotation   = true
  auto_submit_toolbar = false
  consent_method      = "REQUIRED"
  grant_types = [
    "authorization_code",
    "implicit",
    "refresh_token",
  ]
  hide_ios            = true
  hide_web            = false
  issuer_mode         = "DYNAMIC"
  label               = "Angular SPA"
  login_mode          = "SPEC"
  login_scopes = ["email","profile","groups"]
  login_uri = "http://localhost:8080/profile"
  post_logout_redirect_uris = [
    "http://localhost:8080",
  ]
  redirect_uris = [
    "http://localhost:8080/login/callback",
  ]
  refresh_token_leeway   = 30
  refresh_token_rotation = "ROTATE"
  response_types = ["code","id_token"]
  status                     = "ACTIVE"
  token_endpoint_auth_method = "none"
  type                       = "browser"
  wildcard_redirect          = "DISABLED"
}
```

### Debug Output

```
│ Error: expected value to be one of 'openid', 'profile', 'email', 'address', 'phone', got 'groups'
│
│   with okta_app_oauth.ng_SPA,
│   on angular_SPA.tf line 23, in resource "okta_app_oauth" "ng_SPA":
│   23:   login_scopes = ["email","profile","groups"]
│
```

### Expected Behavior

The oauth app can be configured in the Okta admin console with a login_scope of groups and it can be imported into terraform from an existing app, so it should be able to create or reconfigure an app with a login_scope of "groups".

### Actual Behavior

displays an error message indicating that groups is not valid

### Steps to Reproduce

1. `terraform plan or terraform apply`

### Important Factoids

Looks like the value is just missing from the validation list in the source https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_app_oauth.go#L206

### References

- #0000

**Comment by monde** [comment]
Thanks for the details @fredifice that will help me work this out.

**Comment by yahsiuhsieh** [comment]
Is there any update on this problem? I am also facing the same issue here.

**Comment by ebarriosjr** [comment]
This problem still exists. Has anyone found a solution for this?
```
│ Error: expected value to be one of 'openid', 'profile', 'email', 'address', 'phone', got 'groups'
│
│   with okta_app_oauth.test,
│   on test.tf line 39, in resource "okta_app_oauth" "test":
│   39:   login_scopes = ["email", "profile", "groups"]
│
