### ISSUE TITLE
SAML Custom

### ISSUE THREAD

**Issue by karlsequeira** [okta/terraform-provider-okta#1078]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

subject_name_id_template  does not allow for application name as custom and an expression.  I need to pass the uid of the user and not the user name
 user.getInternalProperty("id")

### New or Affected Resource(s)

- okta_app_saml

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by karlsequeira** [comment]
I got it to work. Guess the documentation did not have it but the terraform plan did

      + user_name_template         = "user.getInternalProperty(\"id\")"
      + user_name_template_type    = "CUSTOM"

https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_saml#subject_name_id_template

**Comment by monde** [comment]
Glad to hear this @karlsequeira , thanks for showing the details should someone search the issues for reference.
