### ISSUE TITLE
Unable to grant OKTA API scope using OAUTH 2.0 access token

### ISSUE THREAD

**Issue by pjebastingit** [okta/terraform-provider-okta#1080]
Hello,

Unable to grant okta API scopes (okta.users.read and okta.users.manage) using OAUTH 2.0 access token to service application. Terraform apply returns the below error, ERROR: failed to create application scope consent grant: failed to grant application api scope: the API returned an error: Invalid session, with okta_app_oauth_api_scope.<name> etc.. Getting the same error via postman test too. Please let me know the SCOPE needs to be provided for grant okta api scopes to service app. 
POST /api/v1/apps/<app_id>/grants

**Comment by monde** [comment]
Hi @pjebastingit we have the issue template format so you can provide more context to debug errors with the terraform provider. However, it sounds like you are asking for technical help, not reporting a bug. I'm not recognizing the error you are referencing. You might find some information in the API documentation https://developer.okta.com/docs/reference/api/apps/ . Also, you can open a support ticket.
