### ISSUE TITLE
Provider crashes when doing a data source lookup of an app with different type than the label it is using for the lookup.

### ISSUE THREAD

**Issue by iNoahNothing** [okta/terraform-provider-okta#1082]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform version: `1.1.9`

Provider version: `3.24.0`

### Affected Resource(s)

- `okta_app_oidc` data source
- `okta_app_bookmark` data source 

### Terraform Configuration Files

```hcl

resource "okta_app_oauth" "foo" {
  label                     = "foo OIDC Backend [${local.eks_cluster_name}]"
  hide_ios                  = true
  hide_web                  = true
  type                      = "native"
  omit_secret               = false
  grant_types               = ["authorization_code"]
  response_types            = ["code"]
  redirect_uris             = ***
  post_logout_redirect_uris = ***
  consent_method            = "TRUSTED"
  # Enable PKCE support
  token_endpoint_auth_method = "none"

  # Inject groups claim in tokens
  groups_claim {
    type        = "FILTER"
    filter_type = "STARTS_WITH"
    name        = "groups"
    value       = ***
  }

  lifecycle {
    ignore_changes = [
      groups
    ]
  }
}

resource "okta_app_bookmark" "foo {
  label = "foo [${local.eks_cluster_name}]"
  url   = ***
  logo  = ***

  lifecycle {
    ignore_changes = [
      groups
    ]
  }
}

data "okta_app_oauth" "foo" {
  label = "foo [${local.eks_cluster_name}]"
}
```

### Panic Output

```
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.

Stack trace from the terraform-provider-okta_v3.24.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x174a003]

goroutine 97 [running]:
github.com/okta/terraform-provider-okta/okta.dataSourceAppOauthRead({0x1b390a8, 0xc000246660}, 0x23043c8, {0x18d1860, 0xc0003cb860})
        github.com/okta/terraform-provider-okta/okta/data_source_okta_app_oauth.go:196 +0x7e3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0004d8460, {0x1b390e0, 0xc0008273b0}, 0xd, {0x18d1860, 0xc0003cb860})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:725 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0004d8460, {0x1b390e0, 0xc0008273b0}, 0xc0002bf080, {0x18d1860, 0xc0003cb860})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:944 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0000cc180, {0x1b39038, 0xc00021c280}, 0xc0000e4620)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/grpc_provider.go:1179 +0x408
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0000d00a0, {0x1b390e0, 0xc000826480}, 0xc00060c0f0)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:657 +0x45f
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x19ad400, 0xc0000d00a0}, {0x1b390e0, 0xc000826480}, 0xc000246120, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a8a80, {0x1b48e90, 0xc000001a00}, 0xc000630480, 0xc0000bcba0, 0x20f8a30, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0002a8a80, {0x1b48e90, 0xc000001a00}, 0xc000630480, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x294

Error: The terraform-provider-okta_v3.24.0 plugin crashed!
```

### Expected Behavior

The provider should not crash when it looks up a conflicting data source and should instead just post an message indicating the config error.

### Actual Behavior

The plugin crashes.

### Steps to Reproduce

1. Create two Okta apps. In my case, an `okta_app_oauth` and `okta_app_bookmark`
2. Give the apps different labels to identify their purpose like `foo OIDC Backend ` and `foo` respectively.
3. Do a data source lookup on one of the apps, but mismatch the label with the app type
   ```
   data "okta_app_oidc" "foo" {
     label = "foo"
   }
   ```
4. Run `terraform plan` and observe the crash.

**Comment by monde** [comment]
Thanks for the specific details @iNoahNothing , that should make this easy to fix.

**Comment by monde** [comment]
Note to self:
in `dataSourceAppOauthRead` https://github.com/okta/terraform-provider-okta/blob/master/okta/data_source_okta_app_oauth.go#L155
Fetches list of apps based on label/name, assigns the first app assuming it is the intended app, doesn't inspect app type
https://github.com/okta/terraform-provider-okta/blob/master/okta/data_source_okta_app_oauth.go#L168-L186

**Comment by swu-etsy** [comment]
Noting that the plugin for v.3.31.0 also crashes when an app label is misspelled for the `okta_app` data source. Please let me know if more information would be helpful!

**Comment by monde** [comment]
@iNoahNothing I put some nil guards on okta_app_oauth data source in PR #1300 . Noted, using the label query can be imprecise if your org has similarly named and labeled apps and the label query is used on this data source.

https://developer.okta.com/docs/reference/api/apps/#list-applications

https://github.com/okta/terraform-provider-okta/blob/1082_panic_okta_app_oauth/okta/data_source_okta_app_oauth.go#L169

https://registry.terraform.io/providers/okta/okta/latest/docs/data-sources/app_oauth#argument-reference
