### ISSUE TITLE
Associate `okta_inline_hook` with `okta_auth_server`

### ISSUE THREAD

**Issue by alldoami** [okta/terraform-provider-okta#1084]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We'd like to increase the lifetime of our JWT tokens, and after looking at [these docs](https://support.okta.com/help/s/article/What-is-the-lifetime-of-the-JWT-tokens?language=en_US#:~:text=When%20using%20the%20Okta%20authorization,Refresh%20Token%3A%20100%20days), it seems like that can be done with the `okta_inline_hook` terraform resource when looking at the [attached instructions](https://developer.okta.com/docs/reference/token-hook/?_ga=2.216322261.2118979162.1651525944-1326353346.1634676652#sample-response-to-modify-token-lifetime) from the first article. From what I can see in this provider, I can only find examples for how to associate the `okta_inline_hook` with the `okta_app_saml` and `okta_policy_rule_profile_enrollment` which I don't think is what I want for this use case. I can't find a `inline_hook_id` attribute for `okta_auth_server`, am I missing something?

Is it even possible to represent [this json](https://developer.okta.com/docs/reference/token-hook/#sample-response-to-modify-token-lifetime) in the `okta_inline_hook` resource?

### New or Affected Resource(s)

https://registry.terraform.io/providers/okta/okta/latest/docs/resources/inline_hook
and
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/auth_server

### Potential Terraform Configuration

```
resource "okta_inline_hook" "test" {
  name    = "increase-jwt-token-lifetime"
  status  = "ACTIVE"
  type    = "com.okta.identity.patch"

  # Not sure how to represent the json provided:
  {
   "commands":
     [
        {
            "type": "com.okta.identity.patch",
            "value": [
                 {
                     "op": "replace",
                     "path": "/token/lifetime/expiration",
                     "value": 36000
                  }
             ]
         },
         {
             "type": "com.okta.access.patch",
             "value": [
                  {
                     "op": "replace",
                     "path": "/token/lifetime/expiration",
                     "value": 36000
                   }
              ]
          }
      ]
}
}

resource "okta_auth_server" "example" {
  audiences   = ["api://example"]
  description = "My Example Auth Server"
  name        = "example"
  inline_hook_id = okta_inline_hook.test.id
  issuer_mode = "CUSTOM_URL"
  status      = "ACTIVE"
}
```

cc: @edulop91 to follow thread 😄

**Comment by monde** [comment]
@alldoami I'll have to look into this. Thanks for linking to the documentation and explaining the context. That is very helpful.

**Comment by alldoami** [comment]
@monde Thanks for taking a look! Do you know when you'd have a response by?

**Comment by alldoami** [comment]
@monde any luck?

**Comment by monde** [comment]
@alldoami I'm trying to stitch this together. I'm not familiar with all the ins and outs of online hooks. That said, the [okta_inline_hook resource](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/inline_hook) is pretty much just a wrapper over the [Okta Management API for creating an online hook](https://developer.okta.com/docs/reference/api/inline-hooks/#create-inline-hook).

When looking at [Sample response to modify token lifetime](https://developer.okta.com/docs/reference/token-hook/?_ga=2.216322261.2118979162.1651525944-1326353346.1634676652#sample-response-to-modify-token-lifetime) you referred to, to me that looks like a response to the an execution of an online hook. So, what we'd need is a resource in the terraform provider to call [Execute Inline Hook](https://developer.okta.com/docs/reference/api/inline-hooks/#execute-inline-hook). Perhaps it would be named `okta_inline_hook_execute` resource.

```terraform
resource "okta_inline_hook" "test" {
  # something, something
}

# payload json example is from https://developer.okta.com/docs/reference/token-hook/#sample-json-payload-of-a-request
resource "okta_inline_hook_execute" "test" {
  id = okta_inline_hook.test.id
  
  payload_json = <<JSON
{
  "source": "https://${yourOktaDomain}/oauth2/default/v1/authorize",
  "eventId": "3OWo4oo-QQ-rBWfRyTmQYw",
  "eventTime": "2019-01-15T23:20:47.000Z",
  "eventTypeVersion": "1.0",
  "cloudEventVersion": "0.1",
  "contentType": "application/json",
  "eventType": "com.okta.oauth2.tokens.transform",
  "data": {

... // the data portion of the payload

  }
}
JSON
}
```

@alldoami you've been looking at the hooks more than myself, does the psuedo config look right? Also, this is about firing off an event, execute is an action, not an object. I need to do some research on the best way to articulate this in terraform.

Lastly, would you be interested doing a PR for this feature? I can work with you to get the PR ready. Given the priorities of my team (see #1090) I don't think I'd be able to dedicate much time building this out.

**Comment by monde** [comment]
I have the pattern down for firing events, just need some feedback from @alldoami

**Comment by alldoami** [comment]
Sorry that I didn't respond the first time, haven't had time to look into this too much. I'm a little confused on `firing an event`, does that mean this resource will try and force an update every time a plan is executed?

**Comment by monde** [comment]
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-544415
