### ISSUE TITLE
Failure to destroy okta_app_user_schema_property

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1085]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_xxx

### Terraform Configuration Files

```hcl
resource "okta_app_user_schema_property" "appName-externalIdsOrganizationValue" {
  app_id        = okta_app_saml.appName.id
  description   = ""
  external_name = "externalIdsOrganizationValue"
  index         = "externalIdsOrganizationValue"
  master        = "PROFILE_MASTER"
  #     max_length    = 0
  #     min_length    = 0
  required = false
  scope    = "NONE"
  title    = "ExternalIds Organization Value"
  type     = "string"
}
```

### Expected Behavior

Terraform deletes the `okta_app_user_schema_property` when the containing file is deleted

### Actual Behavior

Terraform fails to delete `okta_app_user_schema_property` with error `Error: failed to delete application user schema property: the API returned an error: Not found: Resource not found: <APPID> (AppInstance)`

resource deleted at the same time as parent app, so not sure if dependency graph calculation issue or name attr issue or bug in deletion code

### Steps to Reproduce
Yet to reproduce this personally, creating this issue for myself to follow up on later
If Okta team is unable to repro this can likely be closed, have manually worked around this for now with state file modification 

1. `terraform apply`

### References

- #0000

**Comment by monde** [comment]
Thanks @exitcode0 . I think I have experienced this with other resources when running acceptance tests but don't recall the details. I will look into it.

**Comment by monde** [comment]
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-544417
