### ISSUE TITLE
[3.25] `okta_app_user_schema_property` JSON errors

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#1087]
Starting with version 3.25 the `okta_app_user_schema_property` now errors out for plan/applies/imports. Downgrading back to version 3.24 there are no issues.

```
Error: failed to get application user schema property: json: cannot unmarshal object into Go struct field 
UserSchemaAttributeItems.definitions.base.properties.items.enum of  type string
```

### Terraform Version
Terraform v1.1.7

### Affected Resource(s)

- okta_app_user_schema_property

### Terraform Configuration Files
```hcl
resource "okta_app_user_schema_property" "test" {}
```

### Steps to Reproduce

I'm testing a default Google Workspace preconfigured App with `emailAddresses` configured. [Link](https://help.okta.com/en/prod/Content/Topics/Provisioning/Google/email-alias.htm)

```
terraform import okta_app_user_schema_property.test  0oaczr3XXXXXXXXXX/emailAliases
```

### Output 

```
okta_app_user_schema_property.test: Refreshing state... [id=0oaczr3XXXXXXXXXX/emailAliases]
╷
│ Error: failed to get application user schema property: json: cannot unmarshal object into Go struct field UserSchemaAttributeItems.definitions.base.properties.items.enum of type string
```

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by monde** [comment]
Seems like the okta-sdk-golang upgrade had some type capabilities shift on it. Regressions make me so blue. Thanks for the details @exitcode0

**Comment by virgofx** [comment]
Any chance this could get prioritized for next release @monde , thanks :)

**Comment by monde** [comment]
@virgofx the acceptance test isn't kicking off the issue you are having. It uses this TF https://github.com/okta/terraform-provider-okta/blob/master/examples/okta_app_user_schema_property/basic.tf . How does your config look different? Email me directly if you don't to show it in the public.

**Comment by virgofx** [comment]
So after more investigation, the issue occurs when attempting to import/apply when crossing over between 3.24 to separate version. There must be some sort of JSON/data incompatibility.

When I removed the resource, then upgraded to 3.27 and then re-applied, everything works.

So I'll close this issue for now as there is a workaround. If anyone experiences this, simply remove the resources via old provider and then re-create via new provider.

**Comment by virgofx** [comment]
Ack. I was testing with 3.24 actually. Ignore previous comment. Investigating further.

**Comment by monde** [comment]
@virgofx send me a snippet of your config. I was going to do a release today but will be tomorrow. Perhaps this will make it in.

**Comment by virgofx** [comment]
Here ya go @monde 

I was a little swamped today so wasn't able to debug. If you're able to check it out before me, great ;P
```
# Create an app / google workspace

resource "okta_app_user_schema_property" "test" {
    app_id        = "XXXXXXXXXXXXXXXX" # Update this to ID of google workspace app
    array_enum    = []
    array_type    = "string"
    description   = "Google Email Aliases (must match domain name(s) configured in Google)"
    external_name = "emailAliases"
    index         = "emailAliases"
    master        = "PROFILE_MASTER"
    permissions   = "READ_ONLY"
    required      = false
    scope         = "SELF"
    title         = "Email Aliases"
    type          = "array"
    union         = false
    user_type     = "default"
}
```
```
 Error: failed to update custom app user schema property: json: cannot unmarshal object into Go struct field UserSchemaAttributeItems.definitions.base.properties.items.enum of type string│
│   with okta_app_user_schema_property.test,
│   on apps.tf line 15, in resource "okta_app_user_schema_property" "test":
│   15: resource "okta_app_user_schema_property" "test" {
```

**Comment by monde** [comment]
@virgofx granted my ACC test is with an oauth app in #1140 , even so, I'm not getting your serialization error.
I'd like to see the TF_LOG=1 output of your plan/apply/test. The serialization error seems to be coming from okta-sdk-golang and not the TF provider itself. Perhaps there aren't flexible enough guards on serialization of an object of nested objects (e.g. `UserSchemaAttributeItems.definitions.base.properties.items.enum`).

**Comment by monde** [comment]
Paired with @virgofx . Looks like the return from the API is not matching the schema in https://github.com/okta/okta-management-openapi-spec which in turn is causing a serialization error in okta-sdk-golang. He'll open a bug on okta-sdk-golang.

**Comment by virgofx** [comment]
@monde I haven't tested yet but should 3.30 fix this?

**Comment by monde** [comment]
@virgofx yes try out v3.30.0 . I was just in the process of looking through any of the existing open issues that may benefit from this.

**Comment by monde** [comment]
[v3.30.0](https://github.com/okta/terraform-provider-okta/releases/tag/v3.30.0) addresses this, please reopen if this isn't addressed correctly. One thing to note is the terraform runtime statically defines the schema at runtime and so we had make enum and one_of.const be string but under the hood the `type` ensures we handle the JSON call to the API correctly. Here's an example for `integer`:

```terraform
resource "okta_app_user_schema_property" "flex_sb_nesting" {
  # ...
  array_type  = "integer"
  array_enum  = ["4", "5"]
  array_one_of {
    const = "4"
    title = "four"
  }
  array_one_of {
    const = "5"
    title = "five"
  }
  #...
}
```

See "important note on" https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_user_schema_property that talks about enum/one_of

**Comment by virgofx** [comment]
@monde I've confirmed that 3.30.0 resolves the issue. Thanks so much!
