### ISSUE TITLE
Unplanned changes - `okta_app_group_assignments`

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1088]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.6.0
on darwin_arm64
+ provider registry.terraform.io/okta/okta v4.4.3
```

### Affected Resource(s)

- `okta_app_group_assignments`

### Terraform Configuration Files

```hcl
variable "num_groups" { default = null}
resource "okta_app_bookmark" "google" {
  label = "google"
  url = "https://www.google.com"
}
resource "okta_group" "okta_tf_provider_issue_1" {
  count = var.num_groups
  name = "okta_tf_provider_issue_1088_group_${count.index}"
}
resource "okta_app_group_assignments" "google" {
  app_id = okta_app_bookmark.google.id
  dynamic "group" {
    for_each = slice(
      okta_group.okta_tf_provider_issue_1[*].id, 0, var.num_groups)
    content { id = group.value }
  } 
}
resource "okta_group" "unrelated_group" {
  name = "okta_tf_provider_issue_1088_unrelated_group"
  depends_on = [ okta_app_group_assignments.google ]
}
resource "okta_app_group_assignment" "unrelated_group" {
  app_id = okta_app_bookmark.google.id
  group_id = okta_group.unrelated_group.id
}
```
### Expected Behavior

Any changes that will be carried out in the `Terraform Apply` should be shown in the `Terraform Plan`

### Actual Behavior

The `okta_app_group_assignments` resource will take drift remediation actions that are not surfaced in the `Terraform plan`
The `okta_app_group_assignments` resource will show "Terraform only" updates as expected in both the `Terraform Plan` and `Terraform Apply`

### Example Scenario
1. Day 0 - Okta App `Salesforce` created using Terraform by `User 1`
2. Day 2 - Okta group `Sales` is assigned to `Salesforce` app using Terraform by `User 1`
3. Day 10 - Okta Group `Marketing` is assigned to `Salesforce` by `User 2` using the Okta Admin console
4. Day 365 - Okta Group `Leadership` is assigned to `Salesforce` using Terraform by `User 3`  
Outage occurs as all of `Marketing` are unexpectedly unassigned and thus de-provisioned from `Salesforce`  
`User 3` checked the `Terraform Plan` diligently but still caused an outage

#### Step 1
`terraform apply --auto-approve -var num_groups=1`
As expected, app is created and has two groups assigned
- `okta_tf_provider_issue_1088_group_0`
- `okta_tf_provider_issue_1088_unrelated_group`

#### Step 2
`terraform apply --auto-approve -var num_groups=1`
no changes shown in terraform plan, suggesting read() fails to notice the click-ops group

#### Step 3
`terraform apply --auto-approve -var num_groups=2`
Note `-var num_groups=2` - This is to trigger a update to the resource
The only change shown in the plan here is the creation & assignment of the new group
`okta_tf_provider_issue_1088_unrelated_group` is not mentioned in the plan at all

Upon applying this plan `okta_tf_provider_issue_1088_unrelated_group` is silently unassigned from the application, leading to a potential outage

### References

- #0000

**Comment by monde** [comment]
Thanks @exitcode0 . I'm trying to wrap up new resources for the public branded email customization endpoints. I'll start knocking down bugs after that.

**Comment by stmyers** [comment]
I'm seeing this behavior too but also it means that if a group is added via the UI, subsequent Terraform runs won't remove that group UNLESS a new group being added to the resource.  This means that not only is drift not being detected in plan output, but also won't be corrected unless a new group is being added via TF.  We need to make sure that groups added to the UI are removed on subsequent runs even if no changes are made to the `okta_app_group_assignments` resource.

**Comment by exitcode0** [comment]
Hey @monde 
Do we know if this bug ended up getting fixed, or did stalebot just close this one out?

**Comment by exitcode0** [comment]
@monde  @duytiennguyen-okta @bogdanprodan-okta - is there an internal reference for this one?
Did this one end up getting fixed?

**Comment by exitcode0** [comment]
@monde Any chance we can re-open this one?
I don't think a fix has been merged for this one
I haven't had a chance to re-test this recently to see if this is still an issue, but I don't think this part of the code has been touched since I raised this one

**Comment by exitcode0** [comment]
I've done some testing on this again and the bug still appears to be present in the latest version(s)

`terraform -v`
```
Terraform v1.6.0
on darwin_arm64
+ provider registry.terraform.io/okta/okta v4.4.3
```

```hcl
variable "num_groups" { default = null}
resource "okta_app_bookmark" "google" {
  label = "google"
  url = "https://www.google.com"
}
resource "okta_group" "okta_tf_provider_issue_1" {
  count = var.num_groups
  name = "okta_tf_provider_issue_1088_group_${count.index}"
}
resource "okta_app_group_assignments" "google" {
  app_id = okta_app_bookmark.google.id
  dynamic "group" {
    for_each = slice(
      okta_group.okta_tf_provider_issue_1[*].id, 0, var.num_groups)
    content { id = group.value }
  } 
}
resource "okta_group" "unrelated_group" {
  name = "okta_tf_provider_issue_1088_unrelated_group"
  depends_on = [ okta_app_group_assignments.google ]
}
resource "okta_app_group_assignment" "unrelated_group" {
  app_id = okta_app_bookmark.google.id
  group_id = okta_group.unrelated_group.id
}
```

### Reproduction Steps
#### Step 1
`terraform apply --auto-approve -var num_groups=1`
As expected, app is created and has two groups assigned
- `okta_tf_provider_issue_1088_group_0`
- `okta_tf_provider_issue_1088_unrelated_group`

#### Step 2
`terraform apply --auto-approve -var num_groups=1`
no changes shown in terraform plan, suggesting read() fails to notice the click-ops group

#### Step 3
`terraform apply --auto-approve -var num_groups=2`
Note `-var num_groups=2` - This is to trigger a update to the resource
The only change shown in the plan here is the creation & assignment of the new group
`okta_tf_provider_issue_1088_unrelated_group` is not mentioned in the plan at all

Upon applying this plan `okta_tf_provider_issue_1088_unrelated_group` is silently unassigned from the application, leading to a potential outage

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-656137
