### ISSUE TITLE
"unique" property not supported when updating custom attributes in user schema

### ISSUE THREAD

**Issue by gustavo-chan** [okta/terraform-provider-okta#11]
**Is your feature request related to a problem? Please describe.**
I'm trying to enforce uniqueness on 2 custom attributes in my Okta user profile. Currently, it can be done via the Okta UI and by calling POST /api/v1/meta/schemas/user/default by setting "unique": "UNIQUE_VALIDATED"

**Describe the solution you'd like**
Add the "unique" attribute to user_schema

**Comment by noinarisak** [comment]
Resolved by PR #12
