### ISSUE TITLE
Failed to sync groups and users for OAuth application... context deadline exceeded

### ISSUE THREAD

**Issue by hueydn** [okta/terraform-provider-okta#1101]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform -v
Terraform v1.1.9
on linux_amd64

### Affected Resource(s)

- okta_app_oauth

### Terraform Configuration Files

```hcl
#OIDC Client for Profile Management App
resource "okta_app_oauth" "ProfileMGMT_WEBAPP" {
  label                       = "Profile Management"
  status                      = "ACTIVE"
  type                        = "browser"
  token_endpoint_auth_method  = "none"
  auto_key_rotation           = true
  redirect_uris               = var.pfmgmt_redirect_uris
  post_logout_redirect_uris   = var.pfmgmt_post_logout_redirect_uris
  response_types              = ["code"]
  grant_types                 = ["authorization_code"]
  consent_method              = "REQUIRED"
  issuer_mode                 = "CUSTOM_URL"
  hide_ios                    = true
  hide_web                    = true
  login_mode                  = "DISABLED"

  lifecycle {
     ignore_changes = [groups]
  }
}
```

### Debug Output

https://gist.github.com/huy-keydata/6bf7a15da1888a42c9af9458b7115412

### Expected Behavior

Terraform should have completed successfully, like in other environments where the same terraform code is run

### Actual Behavior

Terraform fails with error in stout provided

### Steps to Reproduce

We have several okta tenants to support our client and use terraform to keep our tenants functional configuration in sync. However we recently went live and currently have over 275k users in our main tenant where this is failing. 

During the "terraform plan" step we get the error you see in the logs provided.

### References

- #0000

**Comment by monde** [comment]
@huy-keydata are you sure you setting up your resource correctly? That error occurs when `implicit_assignment` is not present.

Here are the docs:
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_oauth#argument-reference

This the code
https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_app_oauth.go#L513-L519

**Comment by hueydn** [comment]
I'm not setting implicit_assignment since it was optional and I never used it in the past. What is the default value for it? I see its an early adopter feature and like I said i run this same config in 5 other environments but it fails in our highest env which is production and has over 275k users

**Comment by hueydn** [comment]
I noticed this "implicit_assignment" is an early access feature so it seems the issue is that my app is assigned the "everyone" group so that when terraform runs it goes through all the user and groups assignments and times out. In my tenant I'm not sure which early access feature i should enable because i don't see the options to turn this on in the Early Access Features because I don't see the settings in the General Tab of the application either...

https://help.okta.com/en/prod/Content/Topics/Apps/apps-fbm-enable.htm

**Comment by monde** [comment]
> I noticed this "implicit_assignment" is an early access feature so it seems the issue is that my app is assigned the "everyone" group so that when terraform runs it goes through all the user and groups assignments and times out. In my tenant I'm not sure which early access feature i should enable because i don't see the options to turn this on in the Early Access Features because I don't see the settings in the General Tab of the application either...
> 
> https://help.okta.com/en/prod/Content/Topics/Apps/apps-fbm-enable.htm

@huy-keydata I'm not sure about all of the settings you are needing here. Can you open a support ticket for that kind of help? https://support.okta.com/ .

**Comment by kochste** [comment]
@huy-keydata - we are running into a similar issue.  Did you by chance open a support ticket?  Did anything come out of that - if so?

**Comment by hueydn** [comment]
> @huy-keydata - we are running into a similar issue. Did you by chance open a support ticket? Did anything come out of that - if so?

We had to get our CSM to enable an early access feature that allows us to use the "implicit_assignment" flag on an application. I'm waiting on a prod deployment happening next monday to determine if this fixed our issue. It seems to have in our staging env so it's promising.
