### ISSUE TITLE
Issue with Adding DUO factor using okta_authenticator

### ISSUE THREAD

**Issue by rohithudupa** [okta/terraform-provider-okta#1102]
arguments required for duo factor host , integrationKey, secretKey are not available in terraform to configure DUO.

But the documents mention, terraform supports DUO configuration. 

okta_authenticator functions are missing parity between the UI console and the API and probably identify all the Authenticators.

**Comment by monde** [comment]
@rohithudupa per internal discussion, I will remove reference to Duo in the docs until the feature is complete in the provider.

**Comment by monde** [comment]
Documentation updated in #1103 and released in v3.27.0 . Duo is not supported by the public API for now, I'm closing this issue for now.
