### ISSUE TITLE
Terraform module for Citrix NetScalar SAML application

### ISSUE THREAD

**Issue by ghost** [okta/terraform-provider-okta#1105]
I'm able to create a Citrix NetScalar SAML application using Okta APIs using the below payload to` /api/v1/apps` endpoint. How can I do this through terraform?

`{
    "name": "citrixnetscalergateway_saml",
    "label": "Citrix API 2",
    "signOnMode": "SAML_2_0",
    "settings": {
        "app": {
            "baseUrl": "cxvxvx",
            "acsURL": null,
            "url": "https://example.com/login.html"
        },
        "signOn": {
            "destinationOverride": "http://www.okta.com",
            "attributeStatements": [
                {
                    "type": "EXPRESSION",
                    "name": "nameFromAPI",
                    "namespace": "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified",
                    "values": [
                        "Value1FromAPI",
                        "Value2FromAPI"
                    ]
                }
            ]
        }
    }
}`

**Comment by monde** [comment]
Hello @wellskyvasudev . The TF documentation for okta_app_saml and okta_app_saml settings are here:
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_saml
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_saml_app_settings
After doing your own investigation, if you can't make progress I'd suggest opening a support ticket https://support.okta.com/
These GH issues are for bugs / issues / feature requests.

**Comment by monde** [comment]
@wellskyvasudev forgot to mention, if you run terraform with env var `TF_LOG=1` you can see all the HTTP request, headers, and body of you plan/apply, etc printed to stdout. As you already experimented with direct API calls you can triangulate your terraform config by cross referencing your curl/postman log with the tf log.
