### ISSUE TITLE
okta_idp_oidc has stop working due to api validation

### ISSUE THREAD

**Issue by gabelazo** [okta/terraform-provider-okta#1106]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### Affected Resource(s)

- okta_idp_oidc

### Terraform Configuration Files

this is the example from the resource documentation

```hcl
resource "okta_idp_oidc" "example" {
  name                  = "example"
  authorization_url     = "https://idp.example.com/authorize"
  authorization_binding = "HTTP-REDIRECT"
  token_url             = "https://idp.example.com/token"
  token_binding         = "HTTP-POST"
  user_info_url         = "https://idp.example.com/userinfo"
  user_info_binding     = "HTTP-REDIRECT"
  jwks_url              = "https://idp.example.com/keys"
  jwks_binding          = "HTTP-REDIRECT"
  scopes                = ["openid"]
  client_id             = "efg456"
  client_secret         = "efg456"
  issuer_url            = "https://id.example.com"
  username_template     = "idpuser.email"
}

```

### Debug Output

https://gist.github.com/gabelazo/ee396765ff86030e0598a54e9649cee0

### Expected Behavior

oidc identity provider is created.

### Actual Behavior

oidc indentity provider fails to be created due to API validation error

### Steps to Reproduce

1. `terraform apply`

### References

- #1063

**Comment by monde** [comment]
I'll be looking into this @gabelazo

**Comment by dbalmain** [comment]
We ran into this issue and managed to get it working by adding:

```
  request_signature_algorithm = "SHA-256"
  request_signature_scope     = "REQUEST"
```

These parameters aren't documented anywhere for `okta_idp_oidc` but they do work. Also, I'm not sure what the default value was before setting this but this seems to work fine.

**Comment by monde** [comment]
Thank you @dbalmain . When I get to this ticket I'll verify the defaults and include example `request_signature_algorithm` and `request_signature_scope` that you've noted.

**Comment by natefredette** [comment]
Have also started seeing this very same issue as of today in our terraform provider:
```Error: failed to create OIDC identity provider: The API returned an error: Api validation failed: IdpTrust. Causes: errorSummary: The protocol.algorithms.request object cannot be left blank.```

This is significantly affecting our ability to push changes to our auth server. Any idea of an ETA for a possible fix?

**Comment by monde** [comment]
Released as [v3.28.0](https://github.com/okta/terraform-provider-okta/releases/tag/v3.28.0).

**Comment by michaeldop** [comment]
Hi @monde, Is there anyway we can add `SHA-256` back in as an option? I think that is the default btw for request algorithm. If I am forced to set `HS256` then it requires that my client secrets to be at least 32 characters. Unfortunately I do not have control over all of those values so I cannot upgrade past 3.27.

```
            "errorSummary": "The signing algorithm HS256 needs a client secret with a length of at least 32 characters."
```

Let me know and I can open up a PR for it.

**Comment by monde** [comment]
@mdop-wh I'll consider this a regression given your feedback. Is your org a classic org? A classic org that was upgraded to OIE? Or a pure OIE org? I added discovery to the provider to determine if it is a Classic or OIE org and I'm feeling suspicious that we need to account for org type here.

**Comment by michaeldop** [comment]
I believe I have Classic Orgs

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-544419

**Comment by monde** [comment]
It's looking like Okta Classic and Okta OIE have different behavior which is not documented in the API docs. The API doc only appear to document https://developer.okta.com/docs/reference/api/idps/#oidc-request-signature-algorithm-object OIE valid input.

```
algorithm | The Signature Algorithm used when signing an authorization request | HS256, HS384, or HS512. The following algorithms are  Early Access (Self-Service): RS256, RS384, or RS512. To use these algorithms, enable Private Key JWT Client Authentication for OIDC IdP for your org from the Settings > Features page in the Admin Console.
```

**Comment by monde** [comment]
v3.28.0 looks to be the source of the change https://github.com/okta/terraform-provider-okta/pull/1134

**Comment by monde** [comment]
@gabelazo did you see if this setting works for you
https://github.com/okta/terraform-provider-okta/issues/1106#issuecomment-1127149534
