### ISSUE TITLE
Authorization Server Policy does not Activate

### ISSUE THREAD

**Issue by mfulgo** [okta/terraform-provider-okta#111]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```bash
Terraform v0.12.24
+ provider.okta v3.2.0
+ provider.random v2.2.1
```

### Affected Resource(s)

* `okta_auth_server_policy`
* (Possibly others like `okta_auth_server`)

### Debug Output

Trimmed debugging output can be found here: https://gist.github.com/mfulgo/a8f757d2f944e520a15d3bf8c616759e. There's quite a bit that had to be removed to anonymize it, but the relevant request/responses are there.

One relevant message is
```bash
2020/04/13 15:31:34 [WARN] Provider "registry.terraform.io/-/okta" produced an unexpected new value for okta_auth_server_policy.example, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .status: was cty.StringVal("ACTIVE"), but now cty.StringVal("INACTIVE")
```

### Expected Behavior

The Authorization Server Policy should be marked as `ACTIVE`.

Terraform needs to call POST on the Policy's `lifecycle/activate` endpoint in order to activate it.

### Actual Behavior

The Authorization Server Policy keeps its status as `INACTIVE`.

### Steps to Reproduce

1. `terraform apply` to create an Authorization Server Policy.
1. Deactivate the Policy through the Okta UI (or API).
1. `terraform apply` to update the policy `INACTIVE ~> ACTIVE`. (The Policy remains `INACTIVE`.)

### References

* https://developer.okta.com/docs/reference/api/authorization-servers/#policy-object (Note the "_links" for deactivation.)

**Comment by mfulgo** [comment]
Commenting to dismiss the stale tag, as this is still an issue AFAIK.

**Comment by mfulgo** [comment]
(Dismissing "stale" tag.)

**Comment by jeremie0** [comment]
this is still an issue

**Comment by mfulgo** [comment]
@noinarisak - could we get this reopened?

**Comment by bogdanprodan-okta** [comment]
Hi @mfulgo! The problem is that official documentation, nor the official SDK contains information about the activation/deactivation of the auth server policy. I've figured out that there should be two additional endpoints:
```
https://{org}/api/v1/authorizationServers/{auth_server_id}/policies/{policy_id}/lifecycle/activate
```
and
```
https://{org}/api/v1/authorizationServers/{auth_server_id}/policies/{policy_id}/lifecycle/deactivate
```
For now, I'll add these into the internal SDK, and try to push these changes into the official Okta Golang SDK.
