### ISSUE TITLE
Error: failed to create user custom schema

### ISSUE THREAD

**Issue by schirayu-athenahealth** [okta/terraform-provider-okta#1114]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
terraform 0.13
terraform okta provider version 10.3.1

### Affected Resource(s)

- okta_user_schema

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior
It should add the new custom attribute to okta profile of the user.

### Actual Behavior

 Jenkins build failed at terraform apply while creating a user custom schema for our production workspace. because of it we are not able to add custom attribute in okta profile and due to that we are not able to migrate athenanet user to okta. 
 
 JENKINS BUILD ERROED RESULT LOGS : 
 

14:06:25 module.users.okta_user_schema.anet_session_timeout: Still creating... [1m10s elapsed] 14:06:36 module.users.okta_user_schema.anet_session_timeout: Still creating... [1m20s elapsed] 14:06:45 module.users.okta_user_schema.anet_session_timeout: Still creating... [1m30s elapsed] 14:06:55 module.users.okta_user_schema.anet_session_timeout: Still creating... [1m40s elapsed] 14:07:06 module.users.okta_user_schema.anet_session_timeout: Still creating... [1m50s elapsed] 14:07:16 module.users.okta_user_schema.anet_session_timeout: Still creating... [2m0s elapsed] 14:07:25 module.users.okta_user_schema.anet_session_timeout: Still creating... [2m10s elapsed] 14:07:34 module.users.okta_user_schema.anet_session_timeout: Still creating... [2m20s elapsed] 14:07:46 module.users.okta_user_schema.anet_session_timeout: Still creating... [2m30s elapsed] 14:07:55 module.users.okta_user_schema.anet_session_timeout: Still creating... [2m40s elapsed] 14:08:05 module.users.okta_user_schema.anet_session_timeout: Still creating... [2m50s elapsed] 14:08:15 module.users.okta_user_schema.anet_session_timeout: Still creating... [3m0s elapsed] 14:08:26 module.users.okta_user_schema.anet_session_timeout: Still creating... [3m10s elapsed] 14:08:35 module.users.okta_user_schema.anet_session_timeout: Still creating... [3m20s elapsed] 14:08:45 module.users.okta_user_schema.anet_session_timeout: Still creating... [3m30s elapsed] 14:08:54 module.users.okta_user_schema.anet_session_timeout: Still creating... [3m40s elapsed] 14:09:06 module.users.okta_user_schema.anet_session_timeout: Still creating... [3m50s elapsed] 14:09:15 module.users.okta_user_schema.anet_session_timeout: Still creating... [4m0s elapsed] 14:09:25 module.users.okta_user_schema.anet_session_timeout: Still creating... [4m10s elapsed] 14:09:34 module.users.okta_user_schema.anet_session_timeout: Still creating... [4m20s elapsed] 14:09:46 module.users.okta_user_schema.anet_session_timeout: Still creating... [4m30s elapsed] 14:09:55 module.users.okta_user_schema.anet_session_timeout: Still creating... [4m40s elapsed] 14:10:05 module.users.okta_user_schema.anet_session_timeout: Still creating... [4m50s elapsed] 14:10:14 module.users.okta_user_schema.anet_session_timeout: Still creating... [5m0s elapsed] 14:10:26 module.users.okta_user_schema.anet_session_timeout: Still creating... [5m10s elapsed] 14:10:35 module.users.okta_user_schema.anet_session_timeout: Still creating... [5m20s elapsed] 14:10:45 module.users.okta_user_schema.anet_session_timeout: Still creating... [5m30s elapsed] 14:10:56 module.users.okta_user_schema.anet_session_timeout: Still creating... [5m40s elapsed] 14:11:06 module.users.okta_user_schema.anet_session_timeout: Still creating... [5m50s elapsed] 14:11:15 module.users.okta_user_schema.anet_session_timeout: Still creating... [6m0s elapsed] 14:11:24 module.users.okta_user_schema.anet_session_timeout: Still creating... [6m10s elapsed] 14:11:36 module.users.okta_user_schema.anet_session_timeout: Still creating... [6m20s elapsed] 14:11:45 module.users.okta_user_schema.anet_session_timeout: Still creating... [6m30s elapsed] 14:11:55 module.users.okta_user_schema.anet_session_timeout: Still creating... [6m40s elapsed] 14:12:04 module.users.okta_user_schema.anet_session_timeout: Still creating... [6m50s elapsed] 14:12:16 module.users.okta_user_schema.anet_session_timeout: Still creating... [7m0s elapsed] 14:12:25 module.users.okta_user_schema.anet_session_timeout: Still creating... [7m10s elapsed] 14:12:35 module.users.okta_user_schema.anet_session_timeout: Still creating... [7m20s elapsed] 14:12:46 module.users.okta_user_schema.anet_session_timeout: Still creating... [7m30s elapsed] 14:12:55 module.users.okta_user_schema.anet_session_timeout: Still creating... [7m40s elapsed] 14:13:05 module.users.okta_user_schema.anet_session_timeout: Still creating... [7m50s elapsed] 14:13:16 module.users.okta_user_schema.anet_session_timeout: Still creating... [8m0s elapsed] 14:13:25 module.users.okta_user_schema.anet_session_timeout: Still creating... [8m10s elapsed] 14:13:35 module.users.okta_user_schema.anet_session_timeout: Still creating... [8m20s elapsed] 14:13:44 module.users.okta_user_schema.anet_session_timeout: Still creating... [8m30s elapsed] 14:13:56 module.users.okta_user_schema.anet_session_timeout: Still creating... [8m40s elapsed] 14:14:05 module.users.okta_user_schema.anet_session_timeout: Still creating... [8m50s elapsed] 14:14:16 module.users.okta_user_schema.anet_session_timeout: Still creating... [9m0s elapsed] 14:14:25 module.users.okta_user_schema.anet_session_timeout: Still creating... [9m10s elapsed] 14:14:34 module.users.okta_user_schema.anet_session_timeout: Still creating... [9m20s elapsed] 14:14:46 module.users.okta_user_schema.anet_session_timeout: Still creating... [9m30s elapsed] 14:14:55 module.users.okta_user_schema.anet_session_timeout: Still creating... [9m40s elapsed] 14:15:05 module.users.okta_user_schema.anet_session_timeout: Still creating... [9m50s elapsed] 14:15:16 module.users.okta_user_schema.anet_session_timeout: Still creating... [10m0s elapsed] 14:15:26 module.users.okta_user_schema.anet_session_timeout: Still creating... [10m10s elapsed] 14:15:35 module.users.okta_user_schema.anet_session_timeout: Still creating... [10m20s elapsed] 14:15:45 module.users.okta_user_schema.anet_session_timeout: Still creating... [10m30s elapsed] 14:15:56 module.users.okta_user_schema.anet_session_timeout: Still creating... [10m40s elapsed] 14:16:05 module.users.okta_user_schema.anet_session_timeout: Still creating... [10m50s elapsed] 14:16:15 module.users.okta_user_schema.anet_session_timeout: Still creating... [11m0s elapsed] 14:16:24 module.users.okta_user_schema.anet_session_timeout: Still creating... [11m10s elapsed] 14:16:36 module.users.okta_user_schema.anet_session_timeout: Still creating... [11m20s elapsed] 14:16:45 module.users.okta_user_schema.anet_session_timeout: Still creating... [11m30s elapsed] 14:16:55 module.users.okta_user_schema.anet_session_timeout: Still creating... [11m40s elapsed] 14:17:06 module.users.okta_user_schema.anet_session_timeout: Still creating... [11m50s elapsed] 14:17:15 module.users.okta_user_schema.anet_session_timeout: Still creating... [12m0s elapsed] 14:17:26 module.users.okta_user_schema.anet_session_timeout: Still creating... [12m10s elapsed] 14:17:35 module.users.okta_user_schema.anet_session_timeout: Still creating... [12m20s elapsed] 14:17:46 module.users.okta_user_schema.anet_session_timeout: Still creating... [12m30s elapsed] 14:17:55 module.users.okta_user_schema.anet_session_timeout: Still creating... [12m40s elapsed] 14:18:04 module.users.okta_user_schema.anet_session_timeout: Still creating... [12m50s elapsed] 14:18:16 module.users.okta_user_schema.anet_session_timeout: Still creating... [13m0s elapsed] 14:18:25 module.users.okta_user_schema.anet_session_timeout: Still creating... [13m10s elapsed] 14:18:32 [2022-05-12T08:48:32.124Z]

Error: failed to create user custom schema: Post "**https://$AthenahealthDomain/api/v1/meta/schemas/user/$USERSCHEMAID**": The API returned an error: Internal Server Error, giving up after 6 attempt(s)

### Steps to Reproduce

Try creating a resource "okta_user_schema" for okta provider version 3.10.1

1. `terraform apply`

### Important Factoids

 The jenkins build is not logging any error at terraform plan statge but is failing at terraform apply stage. and the strange part is out of the three workspace ( dev , int , prod ) it is only failing for prod workspace. It is adding custom okta profile attribute for dev and int workspace but its failing only for prod.

### References
Resource Documentation  Link : https://registry.terraform.io/providers/okta/okta/3.10.1/docs/resources/user_schema
- #0000

**Comment by monde** [comment]
@schirayu-athenahealth you are using v3.10.1? I'm not sure I'm going to be able to help here given the amount of issues on the backlog. We are on v3.27.0 released this Friday.  v3.10.1 was released more than a year ago Feb 26, 2021. Please open a support ticket if this needs to be escalated more quickly https://support.okta.com/

**Comment by monde** [comment]
Closing for now, please reopen when there is more information.
