### ISSUE TITLE
`okta_profile_mapping` fails to set in `okta_app_oauth`: Invalid properties in expression

### ISSUE THREAD

**Issue by erelado** [okta/terraform-provider-okta#1117]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.1.9
on windows_amd64
+ provider registry.terraform.io/okta/okta v3.26.0

### Affected Resource(s)

- okta_profile_mapping

#### okta_app_oauth
```hcl
resource "okta_app_oauth" "oauth_app" {
  label                     = "OAuth App"
  type                      = "web"
  grant_types               = ["authorization_code", "refresh_token", "implicit"]
  response_types            = ["code", "id_token"]
  login_uri                 = "https://${local.APP_URI}"
  issuer_mode               = "CUSTOM_URL"
  consent_method            = "TRUSTED"
  groups_claim {
    type        = "FILTER"
    filter_type = "REGEX"
    name        = "groups"
    value       = ".*"
  }
}
```
#### okta_app_user_schema_property
```hcl
resource "okta_app_user_schema_property" "oauth_app_profile_optional_languages" {
  app_id      = okta_app_oauth.oauth_app.id
  index       = "optional_languages"
  title       = "Optional Languages"
  type        = "array"
  array_type  = "string"
  scope       = "SELF"
  description = "Optional languages to be used in the Okta tenant."
  depends_on = [
    okta_app_oauth.oauth_app
  ]
}
resource "okta_app_user_schema_property" "oauth_app_profile_account_name" {
  app_id      = okta_app_oauth.oauth_app.id
  index       = "account_name"
  title       = "Account Name"
  type        = "string"
  scope       = "SELF"
  description = "The name of the account to be used in the Okta tenant."
  depends_on = [
    okta_app_oauth.oauth_app
  ]
}
resource "okta_app_user_schema_property" "oauth_app_profile_account_guid" {
  app_id      = okta_app_oauth.oauth_app.id
  index       = "account_guid"
  title       = "Account GUID"
  type        = "string"
  scope       = "SELF"
  description = "The account (randomly generated) GUID for the Okta tenant."
  depends_on = [
    okta_app_oauth.oauth_app
  ]
}
```
#### okta_profile_mapping
```hcl
data "okta_user_profile_mapping_source" "user" {}

resource "okta_profile_mapping" "oauth_app_mappings" {
  source_id          = data.okta_user_profile_mapping_source.user.id
  target_id          = okta_app_oauth.oauth_app.id
  delete_when_absent = false
  always_apply       = true

  mappings {
    id          = "optional_languages"
    expression  = "{\"en\", \"de\", \"fr\"}"
    push_status = "PUSH"
  }

  mappings {
    id          = "account_name"
    expression  = "test_account"
    push_status = "PUSH"
  }

  mappings {
    id          = "account_guid"
    expression  = uuid()
    push_status = "PUSH"
  }
  depends_on = [
    okta_app_oauth.oauth_app,
    okta_app_user_schema_property.oauth_app_profile_optional_languages,
    okta_app_user_schema_property.oauth_app_profile_account_name,
    okta_app_user_schema_property.oauth_app_profile_account_guid
  ]
}
```

### Expected Behavior

I'm expecting this code to generate a mapping override like the one I can create via the `Okta Admin Console`:
![image](https://user-images.githubusercontent.com/20738487/168993965-7361b269-3091-4a59-9fe5-13f4c8cd2c06.png)

### Actual Behavior

```hcl
╷
│ Error: failed to create profile mapping: the API returned an error: Api validation failed: updateMapping. Causes: errorSummary: Invalid property e344 in expression eded3ccc-e344-f618-fa22-af43098e9c38, errorSummary: Invalid property fa22 in expression eded3ccc-e344-f618-fa22-af43098e9c38, errorSummary: Invalid property eded3ccc in expression eded3ccc-e344-f618-fa22-af43098e9c38, errorSummary: Invalid property f618 in expression eded3ccc-e344-f618-fa22-af43098e9c38, errorSummary: Invalid property af43098e9c38 in expression eded3ccc-e344-f618-fa22-af43098e9c38
│
│   with module.tenant_common.okta_profile_mapping.oauth_app_mappings,
│   on ..\..\modules\tenant_common\mappings.tf line 3, in resource "okta_profile_mapping" "oauth_app_mappings":
│    3: resource "okta_profile_mapping" "oauth_app_mappings" {
│
╵
```

### Steps to Reproduce
1. Use the Terraform code provided above
2. `terrafirm plan` → should work fine
3. `terraform apply` → fails with above error

### References

- [okta_profile_mapping](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/profile_mapping)

**Comment by monde** [comment]
I'll be looking into this @E-RELevant

**Comment by monde** [comment]
@E-RELevant can you send me the TF_LOG=1 output and your config when you run your apply mike.mondragon@okta.com . The error "Invalid property e344 in expression eded3ccc-e344-f618-fa22-af43098e9c38 ..." is coming straight from the API. I can't tell if the TF provider is sending an incorrectly formatted POST or what you've put on the resource is in correct.

**Comment by erelado** [comment]
Thank you, @monde. Based on my further research, it appears that the issue was that I requested the `optional_languages` attribute as a type of `list(string)` which was unable to accept quotes (passing it as `["en","de","fr"]`).
I have changed the type to a simple `string` and am passing it to the module as: `OPTIONAL_LANGUAGES = "{\"en\",\"de\",\"fr\"}"`

In that regard, is there a more _user-friendly_ method of transferring this type of array of strings using Terraform?

**Comment by monde** [comment]
@E-RELevant the public API is part of the limitation here, it doesn't appear to be as expressive as the admin UI per your example screen shots
https://developer.okta.com/docs/reference/api/mappings/#property-mapping-object
https://developer.okta.com/docs/reference/okta-expression-language/

Also, I think you can use HEREDOC syntax https://www.terraform.io/language/expressions/strings#heredoc-strings instead of passing the value in by ENV VAR

```terraform
resource "okta_profile_mapping" "oauth_app_mappings" {
  # ...
  mappings {
    id          = "optional_languages"
    expression  = <<JSON
{"en", "de", "fr"}
JSON
    push_status = "PUSH"
  }
  # ...
}
```
Reopen the issue if there is a specific bug in the terraform provider.
