### ISSUE TITLE
Not possible to change User Schema attribute 'locale' to READ-WRITE 

### ISSUE THREAD

**Issue by rachrdfds** [okta/terraform-provider-okta#112]
### Terraform Version
0.12.8
### Affected Resource(s)

okta_user_base_schema

### Terraform Configuration File

`
resource okta_user_base_schema base_lastName {
  index       = "lastName"
  title       = "Last name"
  type        = "string"
  master      = "PROFILE_MASTER"
  required	  = false
  permissions = "READ_WRITE"
}

resource okta_user_base_schema base_locale {
  index       = "locale"
  title       = "Locale"
  type        = "string"
  permissions = "READ_WRITE"
}
`
### Expected Behavior

I should be able to change the locale attribute in schema for User, just as I can change the attribute for lastName, firstName etc. My ultimate goal is to make the locale attribute 'READ_WRITE' in permissions.

### Actual Behavior

The user attribute lastName is found and changed by Terraform by the above configuration, but Terraform can't find the locale attribute and just wants to create a new attribute:
![image](https://user-images.githubusercontent.com/57186882/79434036-1fb27100-7fce-11ea-9ce3-2b0f4d9e6856.png)

Also locale's data type is not one of the standard (string, string array etc.), it is ISOxxx format. IMHO the go file it misconfigured to be string: https://github.com/terraform-providers/terraform-provider-okta/blob/71e363be2678f66f999699351f57a98350e52ddb/okta/user.go#L79

### Steps to Reproduce

Use above configuration

**Comment by bogdanprodan-okta** [comment]
Hi @rachrdfds! This issue should be fixed in the latest terraform provider.
