### ISSUE TITLE
Allow for fetching new client_secret from exsiting okta_app_oauth

### ISSUE THREAD

**Issue by ReeceBlack123** [okta/terraform-provider-okta#1124]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Have an existing `okta_app_oauth` app managed by Terraform. When creating a new `client_secret` in the okta console followed by running `terraform plan` & `terraform apply`, Terraform **does not** pick up the new `client_secret` it still keeps the old the old `client_secret` in the terraform state file.

### New or Affected Resource(s)

- okta_app_oauth

### Potential Terraform Configuration

N/A

### References

- [client-secret-rotation-key](https://developer.okta.com/docs/guides/client-secret-rotation-key/main/#rotate-a-client-secret)

**Comment by monde** [comment]
@ReeceBlack123 I could see how this could be viewed as a bug, adding that label also. Are you interested in working with me on coding up a PR?

**Comment by ReeceBlack123** [comment]
@monde I am happy to pair with you to code up a PR 😄

**Comment by monde** [comment]
> @monde I am happy to pair with you to code up a PR 😄

Right, the backlog of issues is deep and I'm also creating new resources to support the greater features in OIE, so if I could get you to code a fix that would be very helpful. I'll help out for sure.

**Comment by monde** [comment]
@ReeceBlack123 where are you at on the PR we were looking at? Have you been able to make progress?
