### ISSUE TITLE
Support for Identity Engine (authenitcation policies and rules)

### ISSUE THREAD

**Issue by mcrobbj-SilverBullet** [okta/terraform-provider-okta#1135]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
https://developer.okta.com/docs/reference/api/policy/#profile-enrollment-policy this is required to support the example https://developer.okta.com/docs/guides/telephony-inline-hook/nodejs/main/#create-a-group-and-add-a-user where Twilio is used to send SMS using an inline hook

### New or Affected Resource(s)

- okta_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by exitcode0** [comment]
#1025 exists for updating the app signon policies to support assiciation with apps 
[policy_profile_enrollment](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_profile_enrollment) and [policy_profile_enrollment_apps](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_profile_enrollment_apps) might be what you're after for your related links

**Comment by monde** [comment]
We have `policy_profile_enrollment` "This resource allows you to create and configure a Profile Enrollment Policy."  https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_profile_enrollment and `policy_profile_enrollment_apps` "This resource allows you to manage the apps in the Profile Enrollment Policy. " https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_profile_enrollment_apps

And the missing support for `com.okta.telephony.provider` hook #1132 is going to be released tomorrow.

**Comment by mcrobbj-SilverBullet** [comment]
I think what you suggested covers the policy but not the rule, here are
some of the details in the rule that I dont see covered:

rulename
usertype ( with conditional list is selected ["user"]
groupMemberships (inclusion and exclusion groups)
Users ( list of users)
devicePlatform   ( with conditional list is selected ["ios","android",
"windows", "macos"]
UsersIP
Risk
CustomExpression
Access is (( denied, allowed)
Authenticatewith
PossessionFactorConstraint (Phising, Hardware, Device)
PasswordReauthFrequency
OtherFactorReauthFrequency

**Comment by monde** [comment]
got it @mcrobbj-SilverBullet , I'll keep this open and come back around to it

**Comment by procule** [comment]
Reviving that but for a request to add the "Assign an application to a specific policy"
https://developer.okta.com/docs/reference/api/apps/#update-application-policy

Should be quite straight-forward with that function:
https://github.com/okta/okta-sdk-golang/blob/master/okta/application.go#L849-L865

Available since okta-sdk-golang 2.12

**Comment by monde** [comment]
Grouping this with the "policy" related work we'd like to address in a sprint.

**Comment by procule** [comment]
> Grouping this with the "policy" related work we'd like to address in a sprint.

@monde Wasn't it added here ? https://github.com/okta/terraform-provider-okta/commit/ab97160e85a95c00582edd61a9c757089f7f3c6a

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-544438
