### ISSUE TITLE
Dynamic issue mode not supported in okta_auth_server_default

### ISSUE THREAD

**Issue by NeenuAVarghese** [okta/terraform-provider-okta#1141]
Looks like the current set of allowed values for `issuer_mode` in [Default Authorization Server](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/auth_server_default#argument-reference) terraform resource are "CUSTOM_URL" or "ORG_URL". 

However, the UI allows setting the issuer as "Dynamic"
![image](https://user-images.githubusercontent.com/15176286/170793357-b1265ca4-0392-4cac-8d17-c8b757d38244.png)

Bug: Terraform resource does not support "Dynamic" issuer mode for default server

**Comment by monde** [comment]
I will look into this @NeenuAVarghese

**Comment by NeenuAVarghese** [comment]
Just checking in - was any progress made on this?

**Comment by monde** [comment]
Released https://github.com/okta/terraform-provider-okta/releases/tag/v3.31.0

**Comment by NeenuAVarghese** [comment]
Thank you @monde!
