### ISSUE TITLE
okta_app_group_assignments - group priority doesn't enforce uniqueness

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1143]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
It appears that the `group` sub-block for `okta_app_group_assignments` does not currently enforce uniqueness for the `priority` attribute

```
Terraform v1.0.11
on darwin_arm64
+ provider registry.terraform.io/okta/okta v3.23.0

Your version of Terraform is out of date! The latest version
is 1.2.1. You can update by downloading from https://www.terraform.io/downloads.html
```

### New or Affected Resource(s)

- okta_app_group_assignments

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by monde** [comment]
I will look into this @exitcode0

**Comment by monde** [comment]
Not stale, will be addressing the rest of the priority property bugs soon.

**Comment by monde** [comment]
@exitcode0 is this still an issue for you?

**Comment by exitcode0** [comment]
@monde ive not tried to reproduce this in a while
Should be fairly easy to reproduce this on a test repo and account though

If this is still an issue I'd like for the provider or terraform to catch this at plan time

Ive taken to using the 'dynamic' terraform syntax for the group sub blocks more recently when I don't nerd to define a profile or priority
Or I just don't define priority on the sub block and let terraform or Okta sort out the order
