### ISSUE TITLE
Okta Group Rules - User Removal Issue Despite remove_assigned_users = true

### ISSUE THREAD

**Issue by pc-esekercan** [okta/terraform-provider-okta#1144]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_group_rule

### Terraform Configuration Files

```hcl
resource "okta_group_rule" "Role_DEPT_RoleName" {
  name              = "Role_DEPT_RoleName [A]"
  status            = "ACTIVE"
  expression_value  = "isMemberOfGroup('${resource.okta_group.security_roles_groups["SG_Role_DEPT_RoleName"].id}')"
  group_assignments = [
    # Inherited Roles
    resource.okta_group.security_roles_groups["SG_Role_foo"].id,
    # Access Groups
    resource.okta_group.app_name_1.groups["SG_SSO_AppName_1"].id,
    module.app_name_2.groups["SG_SSO_AppName_2"].id,
    module.app_name_3.groups["SG_SSO_AppName_3"].id,
    module.app_name_4.groups["SG_SSO_AppName_4"].id,
    module.app_name_5.groups["SG_SSO_AppName_5"].id,
  ]
  expression_type   = "urn:okta:expression:1.0"
  remove_assigned_users = true
  lifecycle { create_before_destroy = true }  
}
```

### Debug Output

No debug output, we're seeing that users change from "managed by Rule $RuleName" to "Manual" in the UI

### Panic Output

N/A

### Expected Behavior

We expect upon the deletion of the Group Rule that the users would be removed from the "child groups" (e.g., group_assignments)

### Actual Behavior

When a group rule is modified (e.g., deleted and recreated via Terraform) to remove a group_assignment (let's say Group A), the users who are in Group A as a result of the original Group Rule, should be removed from the group - not retained in the group, but with a "state" change from "managed by Rule Foobar" to " Managed Manually".

### Steps to Reproduce

1. Create Group Rule A with 3 group_assignments
2. Modify Group Rule A in TF File (simply add a suffix to make it a unique rule name) and remove one of the group_assignments
3. `terraform plan`
4. `terraform apply`
5. Users remain in removed group but no longer show as "Managed by Group Rule A" and instead show "Managed Manually"

### Important Factoids

Other than that - this provider has been truly awesome for us scaling our Okta infra and being consistent in our application of configurations!

### References
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/group_rule#remove_assigned_users
https://github.com/okta/okta-sdk-golang/blob/3e873731bbcce66c8f44e7f8051166c8c17ed155/okta/groupRule.go#L64
- #0000

**Comment by monde** [comment]
Thanks @pc-esekercan I'll look into this.

**Comment by pc-mrousseau** [comment]
One note which may be helpful, the provider appears to pass a parameter here "RemoveUsers" (bool) which isn't documented in Okta's formal API description. Perhaps someone vanished the undocumented option?

https://github.com/okta/terraform-provider-okta/blob/9059f5c9c9c8dd91976232a30410ef852b83f5a8/okta/resource_okta_group_rule.go#L171
