### ISSUE TITLE
okta_policy_password cannot set question_recovery to INACTIVE

### ISSUE THREAD

**Issue by gabelazo** [okta/terraform-provider-okta#1148]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
1.1.7
### Affected Resource(s)

- okta_policy_password

### Terraform Configuration Files

```hcl
resource "okta_policy_password" "debug" {
  name                   = "debug"
  status                 = "ACTIVE"
  description            = "Example"
  password_history_count = 4
  question_recovery      = "INACTIVE"
  groups_included        = []
}
```

### Debug Output

https://gist.github.com/gabelazo/97f1cf17fb06319a71e01cb141214548

### Expected Behavior

question_recovery should be set to INACTIVE

### Actual Behavior

failed to apply due to API validation

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by monde** [comment]
Thanks for the gist with the API calls @gabelazo , that is really helpful. Hopefully this can be addressed with the other `okta_policy_password` issues that open.
