### ISSUE TITLE
Behavior change in okta_group_memberships resource >=3.26

### ISSUE THREAD

**Issue by dli-spoton** [okta/terraform-provider-okta#1149]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.4
on linux_amd64

### Affected Resource(s)

- okta_group_memberships

### Terraform Configuration Files

```hcl
resource "okta_group_memberships" "group_a_direct" {
  group_id = okta_group.group_a.id
  users = ["00ue640grabcdbA04465", "00u4pjzdcbalzJCP123"] # two users
}

resource "okta_group_rule" "group_b_to_a_rule" {
  name                  = "Group B -> A rule" # say this contains 10 additional users
  status                = "ACTIVE"
  group_assignments     = [okta_group.group_a.id]
  expression_type       = "urn:okta:expression:1.0"
  expression_value      = "isMemberOfAnyGroup(\"${okta_group.group_b.id}\")"
  remove_assigned_users = true
}
```

### Expected Behavior

In `<=3.25`, the resource only tracked the state of the users defined in the config. Would ignore all drift in the target group.
In the example, it would ignore any users synced from `group b` by the group rule.

### Actual Behavior

In `>=3.26`, the resource tracks all group members and will mark any users added outside of the Terraform resource as drift.
In the example, it'll mark all users synced from `group b` by the group rule as drift and try to remove them.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This is a recreation of #1094 as requested there.
I can work around this if needed by restructuring groups. (unpleasant but doable)
Mainly looking for confirmation this is an intended behavior change and won't be fixed.

### References

- #1094

**Comment by virgofx** [comment]
Personally I think that having `okta_group_memberships` be authoritative is the correct behavior. Meaning it should be able to do a global set for all group memberships/ overwriting any drift.

However, I understand the other side of the coin. Either way, adding documentation to the provider resource docs would help clarity-wise.

**Comment by monde** [comment]
Linking related issues #1119, #1094
Thanks @dli-spoton, your explanation of the previous behavior is concise.

I see the strong case for reverting to the previous behavior of `okta_group_memberships` resource. In addition add in the ability for it to concern itself for all users in the group even if they've been added outside of the resource. Looking back at the recent changes I was involved with you can see my comments about how the established implementation was muddy:
https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_group_memberships.go#L148-L155

Reverting back to the established behavior and accounting for the new behavior using a flag is the solution I'm thinking about. Check out this example on my thoughts.

```terraform
data "okta_group" "example" {
  name = "Some Group"
}

resource "okta_group_memberships" "specific_users" {
  group_id = data.okta_group.example.id
  users = ["a", "b"]

  # classic/default behavior only cares if users a or b are removed or
  # if the hard coded users slice is changed in the config file
}

resource "okta_group_memberships" "all_users" {
  group_id = data.okta_group.example.id
  users = data.okta_group.example.users

  track_all_users = true
  # will show drift if users are added/removed from the group
  # outside of this resource after the last apply
}
```

Looking for feedback from @parente @tmatilai @exitcode0 @dli-spoton @virgofx

**Comment by virgofx** [comment]
I'm in favor of the flag. It satisfies both use cases. As for what the default action is -- no preference there - maybe revert to how it was before such that it's opt-in.

**Comment by dli-spoton** [comment]
I'm also in favor of the flag.

Personally, I think the default should be the new behavior, since it's more inline with how generally Terraform resources are expected to behave. But it is more disruptive and probably not worth it.

One nice to have that's beyond the scope of this issue is to have the option to only ignore users added by group rules, but be authoritative for all manually managed users. The UI reports if the user is manual or group rule managed, but I don't think the APIs return this information, so it probably a much bigger ask.

**Comment by monde** [comment]
> One nice to have that's beyond the scope of this issue is to have the option to only ignore users added by group rules, but be authoritative for all manually managed users. The UI reports if the user is manual or group rule managed, but I don't think the APIs return this information, so it probably a much bigger ask.

That one sounds cool. I just checked in postman that the response to `GET /api/v1/groups/{groupId}/users` doesn't list hte origin of membership like it does in the UI. In my test org I added a user to the group by UI and added another in the group by rule. Sad.

**Comment by tmatilai** [comment]
A flag would be perfect for me, too.

> Personally, I think the default should be the new behavior, since it's more inline with how generally Terraform resources are expected to behave.

I agree on this. The downside is that it's still a breaking change to the earlier behaviour, but that has been like this already for a couple of releases. But for me personally that wouldn't matter much.

@monde sorry for not responding to your request earlier. Been busy weeks, and now I'll be probably even offline for a couple of weeks. 🙂

**Comment by lucascantor** [comment]
@monde I'm happy to open a separate issue if needed, but I think this is impacting group memberships of some users that **ARE** defined in Terraform code too.

Here's my code:

```HCL
resource "okta_group" "service_accounts" {
  name        = "Type - Service Accounts"
  description = "DO NOT EDIT - Managed by Terraform - Used by Okta policies"
  skip_users  = false
}

resource "okta_group_memberships" "group_service_accounts_membership" {
  group_id = okta_group.service_accounts.id
  users    = local.service_account_user_ids
}
```

Here's the debug output from a plan with `version = "3.25.0"`:
```
2022-06-06T22:55:22.222Z [TRACE] writeChange: recorded NoOp change for okta_group_memberships.group_service_accounts_membership
```

And here's the debug output from a plan with `version = "3.27.0"`:
```
2022-06-06T22:26:47.310Z [WARN]  Provider "registry.terraform.io/okta/okta" produced an unexpected new value for okta_group_memberships.group_service_accounts_membership during refresh.


      - .users: planned set element cty.StringVal("00u11e71i2u6R6HSe2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u1b1r6u5qE2fmGQ2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u1m1jp8h3FY5WHo2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u1m21n98gb9rHG82p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u1qbyfxmXaAk8Nj2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u1ra4xxaJdoXT9w2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u1txseuv47hQoru2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u1wpw0tx3JGdGoA2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u2a2gddbEvhvIZh2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u2a5joniixuldSe2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u2fniv9e3m9onie2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u2gi16xrVt3X8Ql2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u2ntmuex0ngDowf2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u2upac4hdmIkJSx2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u339g0u70CAgETa2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u34j803kJVWwbVP2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u34vv56o80pGyll2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u36nkoy3JS90uGf2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u3a1q3hukVumJs82p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u3a468p2qMosJ3q2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u3e6bovsB2jQtXF2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u3mlui2cL7fXseX2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u3nyzpi13xsgw9P2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u3wkbvno26JAPyy2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u3x1vs6z5T2etGq2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u3yi8tj3MjX6OMZ2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u46u21jqj9khD1N2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u4cq2imq3NBXtlJ2p7") does not correlate with any element in actual


      - .users: planned set element cty.StringVal("00u4ewevf2JRs30rm2p7") does not correlate with any element in actual
```

...which results in the following plan:
```
Terraform will perform the following actions:

  # okta_group_memberships.group_service_accounts_membership will be updated in-place
  ~ resource "okta_group_memberships" "group_service_accounts_membership" {
        id       = "00getvr4cgE1y7apQ2p7"
      ~ users    = [
          + "00u11e71i2u6R6HSe2p7",
          + "00u1b1r6u5qE2fmGQ2p7",
          + "00u1m1jp8h3FY5WHo2p7",
          + "00u1m21n98gb9rHG82p7",
          + "00u1qbyfxmXaAk8Nj2p7",
          + "00u1ra4xxaJdoXT9w2p7",
          + "00u1txseuv47hQoru2p7",
          + "00u1wpw0tx3JGdGoA2p7",
          + "00u2a2gddbEvhvIZh2p7",
          + "00u2a5joniixuldSe2p7",
          + "00u2fniv9e3m9onie2p7",
          + "00u2gi16xrVt3X8Ql2p7",
          + "00u2ntmuex0ngDowf2p7",
          + "00u2upac4hdmIkJSx2p7",
          + "00u339g0u70CAgETa2p7",
          + "00u34j803kJVWwbVP2p7",
          + "00u34vv56o80pGyll2p7",
          + "00u36nkoy3JS90uGf2p7",
          + "00u3a1q3hukVumJs82p7",
          + "00u3a468p2qMosJ3q2p7",
          + "00u3e6bovsB2jQtXF2p7",
          + "00u3mlui2cL7fXseX2p7",
          + "00u3nyzpi13xsgw9P2p7",
          + "00u3wkbvno26JAPyy2p7",
          + "00u3x1vs6z5T2etGq2p7",
          + "00u3yi8tj3MjX6OMZ2p7",
          + "00u46u21jqj9khD1N2p7",
          + "00u4cq2imq3NBXtlJ2p7",
          + "00u4ewevf2JRs30rm2p7",
            # (200 unchanged elements hidden)
        ]
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

...and applies without error:
```
okta_group_memberships.group_service_accounts_membership: Modifying... [id=00getvr4cgE1y7apQ2p7]
okta_group_memberships.group_service_accounts_membership: Modifications complete after 3s [id=00getvr4cgE1y7apQ2p7]
```

Note that all of these users are indeed already members of the Okta group in question, and they were added to this Okta group by Terraform in the past, so this apply doesn't actually do anything.

**Comment by dli-spoton** [comment]
@lucascantor that's a pagination bug introduced in `3.26`. Issue #1119. Should've been fixed in `3.28`.

**Comment by lucascantor** [comment]
@dli-spoton thanks so much for the heads up. Unfortunately, we can't upgrade to `3.28` yet due to it reintroducing https://github.com/okta/terraform-provider-okta/issues/1079

**Comment by monde** [comment]
Working on this PR " Reestablish old behavior of okta_group_memberships resource" #1161 . Trying to get a v3.29.0 release out today.

**Comment by monde** [comment]
Hey all, let me know if https://github.com/okta/terraform-provider-okta/releases/tag/v3.29.0 fixes this for you. `okta_group_memberships` reverted back to it's original behavior. If you want it to track all users set the property `track_all_users=true`. Also took extra care to not deviate from the ordering of users ids as they were originally assigned in the update.
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/group_memberships

**Comment by dli-spoton** [comment]
`3.29` looks good to me.

**Comment by monde** [comment]
Going to close this one 🤞
