### ISSUE TITLE
data.okta_user(s) and user ID

### ISSUE THREAD

**Issue by cgetzen** [okta/terraform-provider-okta#115]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to be able to add existing okta users to an okta_group, and need to be able to look them up by email. This proposal would change the type of data returned by data.okta_user and data.okta_users from "userProfileDataSchema", to a new "userDataScheme" which has userProfile embedded in it.

### New or Affected Resource(s)

* data.okta_users

Thanks!

**Comment by cgetzen** [comment]
On further investigation, "id" is a usable attribute on data.okta_user, but not on data.okta_users.

**Comment by cgetzen** [comment]
This serves our purpose: https://github.com/terraform-providers/terraform-provider-okta/pull/116

**Comment by bogdanprodan-okta** [comment]
Support for this field will available in the upcoming v.3.8.0 release.
