### ISSUE TITLE
Missing email Resource EmailNewAlreadyChangedNotification

### ISSUE THREAD

**Issue by icsrmontano** [okta/terraform-provider-okta#1150]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

okta_email_customization

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

failed to create email customization: the API returned an error: Not found: Resource not found: EmailNewAlreadyChangedNotification

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by monde** [comment]
Thanks @icsrmontano . I believe the type you are looking to utilize is `email.emailNewAlreadyChangedNotification`
https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_template_email.go#L28-L75

**Comment by monde** [comment]
@icsrmontano if you can give some more context, like a sample config, or log output with TF_LOG=1 would be helpful.

**Comment by icsrmontano** [comment]
Hi,

No luck. I had to remove the "email." prefix for the other three templates I'm working on to make it work as before.

The three templates that work fine are:

ForgotPasswordDenied
PasswordChanged
ForgotPassword

Only one that fails

emailNewAlreadyChangedNotification 

Here's the output using the original name. Unfortunately I can't set the debug flag because the script runs via Ansible-Jenkins and a different team controls TF settings.

[2022-06-05T11:05:26.987Z]         "\u001b[1m\u001b[31mError: \u001b[0m\u001b[0m\u001b[1mfailed to create email customization: the API returned an error: Not found: Resource not found: email.emailNewAlreadyChangedNotification (String)\u001b[0m",
[2022-06-05T11:05:26.987Z]         "",
[2022-06-05T11:05:26.987Z]         "\u001b[0m  on okta.tf line 368, in resource \"okta_email_customization\" \"email_templates\":",
[2022-06-05T11:05:26.987Z]         " 368: resource \"okta_email_customization\" \"email_templates\" \u001b[4m{\u001b[0m",
[2022-06-05T11:05:26.987Z]         "\u001b[0m",
[2022-06-05T11:05:26.987Z]         "\u001b[0m\u001b[0m"

**Comment by monde** [comment]
@icsrmontano can you use curl or postman and jq to show me the templates that are available on your org? The type is showing up as `email.emailNewAlreadyChangedNotification` for me. I'm wondering if that template is not available for some reason on your org.

```
curl --location --request GET 'https://{yourOrg}/api/v1/templates/emails' \
--silent \
--header 'Accept: application/json' \
--header 'Authorization: SSWS {yourAPIToken}' \
| jq ".[].type" | sort
```

```
# macos with postman
# execute a GET 'https://{yourOrg}/api/v1/templates/emails'
# in postman UI copy body of response into
# clip board then use pbpaste to pipe that into jq on the command line
pbpaste| jq ".[].type" | sort
```

for example, this is what I'm seeing on my test org:

```
"email.accountLockout"
"email.ad.forgotPassword"
"email.ad.forgotPasswordReset"
"email.ad.selfServiceUnlock"
"email.ad.welcome"
"email.adminUsersListScheduledLifecycleStatusChange"
"email.authenticatorEnrollment"
"email.authenticatorReset"
"email.automation"
"email.emailActivation"
"email.emailChangeConfirmation"
"email.emailLinkAuthenticationTransaction"
"email.emailLinkFactorVerification"
"email.emailLinkRecoveryAdResetFactor"
"email.emailLinkRecoveryAdResetPwdFactor"
"email.emailLinkRecoveryAdUnlockFactor"
"email.emailLinkRecoveryAdUnlockPwdFactor"
"email.emailLinkRecoveryLdapResetPwdFactor"
"email.emailLinkRecoveryLdapUnlockPwdFactor"
"email.emailLinkRecoveryResetFactor"
"email.emailLinkRecoveryResetPwdFactor"
"email.emailLinkRecoveryUnlockFactor"
"email.emailLinkRecoveryUnlockPwdFactor"
"email.emailNewAlreadyChangedNotification"
"email.emailNewChangeNotification"
"email.emailTransactionVerification"
"email.endUserScheduledLifecycleStatusChange"
"email.factorEnrollment"
"email.factorReset"
"email.forgotPassword"
"email.forgotPasswordDenied"
"email.idpMyAccountChangeConfirmation"
"email.passwordChanged"
"email.pushVerifyActivation"
"email.registrationActivation"
"email.registrationEmailVerification"
"email.selfService.registrationActivation"
"email.selfService.registrationVerification"
"email.selfServiceUnlock"
"email.selfServiceUnlockOnUnlockedAccount"
"email.signInFromNewDevice"
"email.sunone.forgotPassword"
"email.sunone.forgotPasswordDenied"
"email.sunone.selfServiceUnlock"
"email.sunone.welcome"
"email.tempPassword"
"email.welcome"
```

If you are not seeing `email.emailNewAlreadyChangedNotification` open a support ticket at https://support.okta.com/ and reference this GH issue.

**Comment by icsrmontano** [comment]
I can confirm emailNewAlreadyChangedNotification with the original value:

        "type": "email.emailNewAlreadyChangedNotification",

Scratching my head on this one.

Additional context: with the old **okta_email_templates** , I used these four template types just fine:

okta_email_templates = {
  "forgotPasswordDenied" = {
    type       = "email.forgotPasswordDenied"
	...
  }
  "PasswordChanged" = {
    type       = "email.passwordChanged"
	...
  }
  "EmailChanged" = {
    type       = "email.emailNewAlreadyChangedNotification"
	...
  } 
  "forgotPassword" = {
    type       = "email.forgotPassword"
	...
  }
}

When I replaced **okta_email_templates** with **okta_email_customization**, the original email types failed with the "Resource Not Found" message. Then I noticed the example provided in the official documentation uses "ForgotPassword" instead of the expected "email.forgotPassword" as "template_name". I gave it a try and removed the "email." from the template name and that trick worked for all templates but the one in question.

resource "okta_email_customization" "email_templates" {
  for_each = var.okta_email_templates 
  brand_id      = tolist(data.okta_brands.singlebrand.brands)[0].id
  template_name = each.value.type
  language      = "en"
  is_default    = true
  subject       = each.value.subject
  body          = each.value.template
}

My take is that something in the new code is expecting an alias instead of the original type. I'll create a case with Okta Support.

Thank you,

**Comment by icsrmontano** [comment]
Case  01408710. Should I close this issue?

**Comment by monde** [comment]
@icsrmontano let's keep this open, I want to look into it further from the implementation side.

**Comment by monde** [comment]
@icsrmontano taking a second look at this. I missed the email templates is using the brands API [`GET /api/v1/brands/${brandId}/templates/email`](https://developer.okta.com/docs/reference/api/brands/#list-email-templates). I wrote this script to get the template names off the primary brand on my test org:

```terraform
data "okta_brands" "test" {
}

data "okta_email_templates" "test" {
  brand_id = tolist(data.okta_brands.test.brands)[0].id
}

output "templates_names" {
  value = flatten([for t in data.okta_email_templates.test.email_templates : t.name[*]])
}
```
This is what I'm seeing on my org for email templates. I'm not seeing anything about `EmailNewAlreadyChangedNotification`. 
```
 $ terraform plan

Changes to Outputs:
  + templates_names = [
      + "ADForgotPassword",
      + "ADForgotPasswordDenied",
      + "ADUserActivation",
      + "ForgotPassword",
      + "ForgotPasswordDenied",
      + "LDAPForgotPassword",
      + "LDAPForgotPasswordDenied",
      + "LDAPUserActivation",
      + "PasswordResetByAdmin",
      + "UserActivation",
    ]
```
Apologies for going the rabbit hole looking at `/api/v1/templates/emails'` . Let me know if this gets you farther along with the config you are writing.

**Comment by icsrmontano** [comment]
Yes.  can confirm that I see the same 10 templates using the brands API (not a big fan now). I used Postman (rather than TF) to verify this, so this is certainly an API limitation.

**Comment by monde** [comment]
@icsrmontano I don't think I have anything more I can do for you from the TF side, can I close this ticket?

**Comment by icsrmontano** [comment]
Please go ahead and close it. Thank you.

**Comment by rtlong** [comment]
@icsrmontano FYI the [GET /api/v1/brands/${brandId}/templates/email](https://developer.okta.com/docs/reference/api/brands/#list-email-templates) API is _paginated_. Add `?limit=60` and you should see them all. I get 27, for what it's worth.
