### ISSUE TITLE
Email Change Confirmed Notification options

### ISSUE THREAD

**Issue by s50600822** [okta/terraform-provider-okta#1152]
### Description

Terraform options for "Email Change Confirmed Notification" - "Administrators" vs "Administrators and end-users"
<img width="1401" alt="Screen Shot 2022-06-07 at 10 25 36 am" src="https://user-images.githubusercontent.com/5586453/172289896-ad0415e7-adfe-4e54-b925-6be8f561a0ae.png">

### New or Affected Resource(s)

- okta_template_email (maybe) ?

**Comment by monde** [comment]
Hi @s50600822
I'm not certain on the ask here. This is how to list out the template names on a brand in your org:
```terraform
data "okta_brands" "test" {
}

data "okta_email_templates" "test" {
  brand_id = tolist(data.okta_brands.test.brands)[0].id
}

output "templates_names" {
  value = flatten([for t in data.okta_email_templates.test.email_templates : t.name[*]])
}
```
This is what I'm seeing on my org for email templates.
```
 $ terraform plan

Changes to Outputs:
  + templates_names = [
      + "ADForgotPassword",
      + "ADForgotPasswordDenied",
      + "ADUserActivation",
      + "ForgotPassword",
      + "ForgotPasswordDenied",
      + "LDAPForgotPassword",
      + "LDAPForgotPasswordDenied",
      + "LDAPUserActivation",
      + "PasswordResetByAdmin",
      + "UserActivation",
    ]
```
I'm not familiar with how the data is surfaced in the Okta Admin UI. The way the brands api is modeled is:

* an org can have many brands
* a brand has many templates
* email customization are working copies of a specific template

I would open a support ticket and ask if all of the email templates/customizations in the Okta Admin UI  are available through the API. My Admin UI looks the same as yours, but per my example there are only 10 templates on the brand. So my suspicion is there are advanced features built into the Admin UI that are not available through the public API.

**Comment by monde** [comment]
Closing for now, please reopen when there is more information.

**Comment by s50600822** [comment]
In the screenshot, pay attention to the **radio boxes** at the top. There are options for the side effect when an email for a particular template is sent. It has nothing to do with templating but with the behavior when emails of that template are triggered.
