### ISSUE TITLE
okta_group_roles - support custom roles

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1153]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently if I want to re-use custom admin roles and resource sets I have to define a singular `okta_admin_role_custom_assignments` that references every `member` that should have the role & resource set combo

I'm currently re-structuring my okta admins sub-module such that I have a tf document for each team im assigning admin permissions to, as such i'd like to be able to define a `okta_admin_role_custom_assignments` in each of these documents to sit along side their okta admin group

Currently I dont believe this is possible as `okta_admin_role_custom_assignments` uses the ID of the custom admin role and resource set as its ID in state, I can't define two `okta_admin_role_custom_assignments` that re-use the same resource set and custom admin role combo

I'd be open to using `okta_group_role` or `okta_group_roles` and passing in the ID of the custom role and resource set and having the provider do the work behind the scenes it looks like there is an internal API for this, unsure if there is a public API for this `/api/internal/resourceSets/assignments`

### New or Affected Resource(s)

- okta_group_role
- okta_group_roles
- okta_user_admin_roles
- okta_admin_role_custom_assignments

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by monde** [comment]
Thanks @exitcode0 . Can we work on this as a PR together? You have a better understanding of the resource surface area you are trying to define here. Let me know, thanks.
