### ISSUE TITLE
Okta saml app does not allow to add certificate

### ISSUE THREAD

**Issue by sanketr404** [okta/terraform-provider-okta#1154]
### Community Note
 
Okta saml app does not allow to add certificate

### Terraform Version
❯ terraform version
Terraform v1.1.9
on darwin_arm64

### Affected Resource(s)

3.28.0

- okta_xxx

### Terraform Configuration Files

```hcl

resource "okta_app_saml" "example" {
  label                    = "example"
  sso_url                  = "https://example.com"
  recipient                = "https://example.com"
  destination              = "https://example.com"
  audience                 = "https://example.com/audience"
  subject_name_id_template = "$${user.userName}"
  subject_name_id_format   = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
  response_signed          = true
  signature_algorithm      = "RSA_SHA256"
  digest_algorithm         = "SHA256"
  honor_force_authn        = false
 certificate = "Aaaaaaadaddnjsdfosbfjbfcjabfcjabvcjbvjodbvcojbvojbvjoedbvjobvjobdwvjobdwvjowdbnvjdwbvodbvobdewvoubdwvbwvwbvbvwdbvbdwvudwbvbdwvbdwvwdbvjubdwvjubdwvobdwvuobdwnvoubdwnvoudwbvoubdwnvdwbvoeqdbvoiueqbvipeqbvioqebviopqebviouqbvqeuobvouieqbvqeiovbeioqpvbioqbevqp"
  authn_context_class_ref  = "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"

  attribute_statements {
    type         = "GROUP"
    name         = "groups"
    filter_type  = "REGEX"
    filter_value = ".*"
  }
}


```

### Debug Output
 Error: Value for unconfigurable attribute
 
 │ Can't configure a value for "certificate": its value will be decided automatically based on the result of applying this configuration.

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by monde** [comment]
Thanks @sanketr404 . I see the `certificate` was established as a readable attribute on the the `okta_app_saml` resource https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_saml#attributes-reference . I'll have to look into changing the implementation to allow for `certificate` to be a property that can be set. If you are interested in working on a PR I can help you out. Given the backlog of issues I'm not sure when I'll get to this issue.
