### ISSUE TITLE
`okta_user_schema_property` - Integer "Attribute Range Support" a.k.a Validation Keywords

### ISSUE THREAD

**Issue by eephillip** [okta/terraform-provider-okta#1165]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating a `okta_user_schema_property` as type integer. There are validation attributes available that aren't yet available in the provider resource. 

```
Attribute Range Support Examples

    Between 1 and 10
        minimum: 1
        maximum: 10

    Less than 1
        maximum: 1

    Greater Than 1
        minimum: 1

    Equals 1
        minimum: 1
        maximum: 1
```
UI configuration option

![image](https://user-images.githubusercontent.com/470759/173923393-d0bb9852-d914-4b17-b4d9-e988ccafed60.png)

### New or Affected Resource(s)

- okta_user_schema_property

### Potential Terraform Configuration

```hcl
resource "okta_user_schema_property" "test_prop" {
  index       = "test_prop"
  title       = "test_prop"
  type        = "integer"
  description = "test_prop int value"
  required    = false
  scope       = "NONE"    
  permissions = "READ_WRITE" 
  master      = "PROFILE_MASTER" 

  minimum = 1     # <--- new property 
  maximum = 10    # <--- new property 
}

```

### References

- #0000

**Comment by monde** [comment]
Thanks @eephillip . This sounds cool, I'm in flight trying to get the array_enum on okta_user_schema_property to correctly have typed values that the API allows, so this is adjacent for sure.

**Comment by eephillip** [comment]
bumpity bump 🤜🤛

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-524185

**Comment by eephillip** [comment]
> https://oktainc.atlassian.net/browse/OKTA-524185

Is their a public link available? I don't think I have access.

**Comment by monde** [comment]
@eephillip the link to Jira is an internal reference, apologies I should have noted that.

**Comment by eephillip** [comment]
So the tldr is an upstream blocker?

**Comment by monde** [comment]
@eephillip the blocker is the amount of bandwidth I have for bugs / features on the TF provider, okta-sdk-golang, and some other internal work that is not in the public yet. You can open a support ticket and reference this issue, that can add some signal on how much priority this gets.

**Comment by eephillip** [comment]
🎉party bump 🤜🤛
