### ISSUE TITLE
Question: Factor Sequencing 

### ISSUE THREAD

**Issue by itrann** [okta/terraform-provider-okta#117]
Hi, 

Just wondering if anyone's currently working on supporting factor sequencing for Sign On Policy? 

Any comments would be greatly appreciated! 

Thanks!

**Comment by tgoodsell-tempus** [comment]
Currently this probably isn't being work on, as I do not see management of the factor sequencing settings supported by the public management API.

Ref: https://developer.okta.com/docs/reference/api/policy/
