### ISSUE TITLE
Enable terraform to maintain order of redirect_uris

### ISSUE THREAD

**Issue by garmishr** [okta/terraform-provider-okta#1170]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In Okta , if we enable wildcard for redirect_uri, and wildcard urls are entered before non wild card ones, then uri matching would match with wildcard ones first which might not be ideal in some scenarios. Hence it is better to have non wild card entries before wild card ones. However even after doing that, the order is not being maintained causing http 500.

### New or Affected Resource(s)

- okta_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by monde** [comment]
@garmishr looking for some clarification.

I this with the oauth app resource https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_oauth only? Or also with the data source https://registry.terraform.io/providers/okta/okta/latest/docs/data-sources/app_oauth . Seems like just the resource.

Next, are you making use of the early access feature [wildcard_redirect](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_oauth#wildcard_redirect)? https://developer.okta.com/docs/reference/api/apps/#settings-10

Next, are you saying that you are getting an API error if you enter non-wildcard URLs before wildcard URLs when you initially create the an oauth app? Or are you only getting the error if you try to update the resource after reordering the redirect URLs in your config?

It would be really helpful to see a sample config.

**Comment by garmishr** [comment]
Hi @monde , 1.Yes this is with the oauth app resource only. 2. Yes we are using early access feature wildcard_redirect 3.We are getting API error if we enter wildcard URL before non-wildcard URLs when an app is initially created.

**Comment by monde** [comment]
@garmishr does this represent ordering of  redirect_uris that would cause the error you are seeing?

```terraform
resource "okta_app_oauth" "example" {
  label = "example"
  type = "web"
  wildcard_redirect  = "SUBDOMAIN"
  redirect_uris = [
    "https://one.example.com/",
    "https://two.example.com/",
    "https://*.example.com/"
  ]
}
```

**Comment by monde** [comment]
@garmishr never mind my question, I found the answer. This is bug where we were using the set scheme type in the TF sdk and the ordering was not being retained. `redirect_uris` should by schema typed list. See my PR #1171

**Comment by garmishr** [comment]
@monde Thank you so much for looking into the issue and creating the PR. Sorry, could not answer your questions as I work in IST time zone.
