### ISSUE TITLE
Support for enabling oAuth provisioning for org2org

### ISSUE THREAD

**Issue by slichtenthal** [okta/terraform-provider-okta#1174]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As documented on the following page: [https://developer.okta.com/docs/guides/secure-oauth-between-orgs/main/#enable-provisioning-in-the-org2org-app](https://developer.okta.com/docs/guides/secure-oauth-between-orgs/main/#enable-provisioning-in-the-org2org-app), it is possible to enabling provisioning across two okta instances via oauth instead of an api key by making the following API call: `POST /api/v1/apps/${Org2OrgAppId}/connections/default?activate=TRUE`.  Ideally this feature could be added into terraform as well so not a manual step.

### New or Affected Resource(s)

- okta_app_provisioning_oauth

or 

- okta_app_*

### Potential Terraform Configuration

```hcl
resource "okta_app_provisioning_oauth" "oauth_provisioning_of_org2org" {
   application_id: ${okta_app_saml.org2org}.id
   client_id: "[client id from service app]"
}

```

or

```hcl
resource "okta_app_saml" "hub_to_spoke_org2org" {
  label = "Org2Org from TF"
  preconfigured_app = "okta_org2org"
  status = "ACTIVE"
  oauth_provisioning_client_id: "[client id from service app]"
}
```
- #0000

**Comment by monde** [comment]
Thanks @slichtenthal . We need to finish the or2org funtionality and your config suggestions look good to me.

**Comment by slichtenthal** [comment]
Thanks!  FWIW I’m not sure if this is specific to org2org as the API call makes it look like it could work for any generic app where okta can provision users.

**Comment by monde** [comment]
Peeling off the stale lable.

**Comment by GraemeMeyerGT** [comment]
@monde any chance of reviving this? I didn't realise this feature even existed, but the ability to configure Org2Org provisioning with OAuth via Terraform would be super useful, and much more robust than just scripting up something against the API

**Comment by michaeldop** [comment]
we want to move to oauth as well for org2org and looks like we cannot
