### ISSUE TITLE
Ability to configure `inactivityPeriod` in `okta_app_signon_policy_rule` 

### ISSUE THREAD

**Issue by BalaGanaparthi** [okta/terraform-provider-okta#1181]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Must be able to configure the app sign-on policy rule with `inactivityPeriod`

### New or Affected Resource(s)

- okta_app_signon_policy_rule

### Potential Terraform Configuration

```hcl
resource "okta_app_signon_policy_rule" "test" {
  name                        = "testAcc_replace_with_uuid"
  policy_id                   = data.okta_app_signon_policy.test.id
  access                      = "ALLOW"
  ...
  inactivity_period           = "PT1H"
  re_authentication_frequency = "PT3H"
}
```

### References

- #0000

**Comment by monde** [comment]
Thank you @BalaGanaparthi

**Comment by monde** [comment]
@BalaGanaparthi I see the `inactivityPeriod` property in the public API documents but not a `reAuthenticationFrequency`/`re_authentication_frequency` property: https://developer.okta.com/docs/reference/api/policy/#verification-method-object 
Is the `reAuthenticationFrequency` something that you are able to see when you were experimenting with curl/postman calls to the API?

**Comment by monde** [comment]
Released in https://github.com/okta/terraform-provider-okta/releases/tag/v3.31.0
