### ISSUE TITLE
Profile mapping with AD

### ISSUE THREAD

**Issue by jackmurphy89** [okta/terraform-provider-okta#1186]
Is it possible when doing profile mapping to have the source be Active directory? I seem to only find answers that state the source must be an app or a user type and I don't think that solves my issue. Below is what I am looking to map for attributes. Also if this is the wrong place to ask, let me know and I will move it. Thanks!

Attribute Name | String
-- | --
honorificPrefix | appuser.generationQualifier
honorificSuffix | appuser.personalTitle
managerId | getManagerUser("active_directory").login
manager | getManagerUser("active_directory").displayName
lastPasswordChangeTimestamp | appuser.pwdLastSet
proxyAddresses | appuser.proxyAddresses
msExchHideFromAddressLists | appuser.msExchHideFromAddressLists
immutableId | appuser.externalId
managerDn | appuser.managerDn

**Comment by monde** [comment]
Thanks @jackmurphy89 I'd open a support ticket to get more a more immediate answer. I don't know top of mind. Also checkout the examples that used in the acceptance tests.

- https://github.com/okta/terraform-provider-okta/tree/master/examples/okta_profile_mapping
- https://registry.terraform.io/providers/okta/okta/latest/docs/resources/profile_mapping
- https://developer.okta.com/docs/reference/okta-expression-language/
