### ISSUE TITLE
datasource app_user_base_schema_property & app_user_schema_property

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1195]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A bit of a niche feature request

currently we're using semgrep to look for instances of  hardcoded IDs `id = "..."` in `mapping` blocks inside `okta_profile_mapping` resources
We're doing this because hardcoded `id` attributes without a `depends_on` can cause the `okta_profile_mapping` to be provisioned before the `okta_app_user_schema_property` resources, causing deployment failure
Currently we're getting false positive findings when base schema fields are references in the `okta_profile_mapping` 

As per terraform's guidance [here](https://www.terraform.io/language/meta-arguments/depends_on#processing-and-planning-consequences)
>Instead of depends_on, we recommend using [expression references](https://www.terraform.io/language/expressions/references) to imply dependencies when possible

We're trying to work around this by using implicit dependancies by replacing all `id` attributes with expression references

we dont use `okta_app_user_base_schema_property` due to the okta object being mostly immutable, the resource must be imported as creating it from scratch in terraform config will mean the provider will attempt to "create" the object which (iirc) causes an API layer error as the base schema field already exists
This means we can't use attribute references to reference base schema properties

A datasource for these resources would solve my problem, I could define the base schema fields as data sources and use attribute references to reference their index from the `okta_profile_mapping` 

### New or Affected Resource(s)

- datasource okta_app_user_base_schema_property

### Potential Terraform Configuration

```hcl
resource "okta_app_saml" "exampleApp" {
  label = "exampleApp"
}


data "okta_app_user_base_schema_property" "exampleApp-givenName" {
  app_id = okta_app_saml.exampleApp.id
  # Ideally can lookup via index or title
  index  = "givenName"
  # title = "Given name"
}
resource "okta_app_user_schema_property" "exampleApp-userType" {
  app_id = okta_app_saml.exampleApp.id
  enum = [
    "Basic",
    "Corp",
    "Licensed",
  ]
  external_name      = "userType"
  external_namespace = "urn:ietf:params:scim:schemas:core:2.0:User"
  index              = "userType"
  master             = "PROFILE_MASTER"
  required = false
  scope    = "NONE"
  title    = "User Type"
  type     = "string"

  one_of {
    const = "Basic"
    title = "Basic"
  }
  one_of {
    const = "Corp"
    title = "Corp"
  }
  one_of {
    const = "Licensed"
    title = "Licensed"
  }
}

data "okta_user_profile_mapping_source" "user" {}

resource "okta_profile_mapping" "exampleApp-to_app" {
  source_id = data.okta_user_profile_mapping_source.user.id
  target_id = okta_app_saml.exampleApp.id

  # Base Fields
  mappings {
    id          = okta_app_user_base_schema_property.exampleApp-givenName.index
    expression  = "user.firstName"
    push_status = "PUSH"
  }

  # Custom Fields
  mappings {
    id          = okta_app_user_schema_property.exampleApp-userType.index
    expression  = "user.userType"
    push_status = "DONT_PUSH"
  }
}

```

### References

- #0000

**Comment by monde** [comment]
Thanks @exitcode0 , I'll have to look into this.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-526341

**Comment by monde** [comment]
not stale
