### ISSUE TITLE
bug(s) with resources having a `priority` setting

### ISSUE THREAD

**Issue by monde** [okta/terraform-provider-okta#1198]
## Synopsis

We are looking closer at two bugs with resources that have a `priority` attribute. The bugs may be discrete or related. The resources that could possibility be affected are listed below.

## Bug 1 - Parallelism

The terraform runtime operates with a parallelism mechanism wherein it can make many API calls in parallel as it runs commands such as `plan` and `apply`. The [default is 10](https://www.terraform.io/cli/commands/apply#parallelism-n) and has a CLI flag of [-parallelism=n](https://www.terraform.io/cli/commands/apply#parallelism-n) to override the default. When unrestrained calls are made in this manner the API can 500 or 400 errors.

There is some feedback internally at Okta, that API resources having a `priority` property should not be called concurrently. Therefore the Okta Terraform provider needs to identify which resources can be affected by this. Then develop a mechanism to prevent the terraform runtime interacting with these resources in a parallel manner (beyond running the CLI in [-parallelism=n](https://www.terraform.io/cli/commands/apply#parallelism-n) mode). This might be tough to solve as the provider will be attempting to bend the TF runtime outside of its base behavior.

## Bug 2 - Ordering

A `priority` attribute implies ordering. However, it seems that if the all of the elements that are ordered are not present in an API call to Okta then the API result can be inconsistent. This is likely an input validation issue in the Okta Terraform Provider, and if this is the case, it could be handled with some additional API calls under the hood.

An example: imagine an [`okta_auth_server_policy_rule`](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_signon_policy_rule) resource in a TF config (as reported in issue #713). Let's say that there is one rule being managed by the TF config but the policy has other rules not managed by TF.

| rule | priority | managed by TF |
|-----|--------|-----------------|
| A     | 1          | no                       |
| B     | 2         | yes                      |
| C     | 3         | no                       |

```terraform
resource "okta_auth_server_policy_rule" "test" {
  auth_server_id       = okta_auth_server.test.id
  policy_id            = okta_auth_server_policy.test.id
  status               = "ACTIVE"
  name                 = "B"
  priority             = 2
}
```
It appears that the initial `apply` when the `B` rule is created (and/or subsequent updates) can cause an Okta API error where the response is referencing the `priority` property of the TF resource. It seems as if the Okta Terraform provider first needs to inspect the parent of a resource (like `okta_auth_server_policy` is to `okta_auth_server_policy_rule`) and then gather all of the existing children (even those not manged by TF). Then any creates or updates need to be made in the context of all of the children associated with the parent. This is a hunch and needs to be verified and addressed.

## Resources
- okta_auth_server_policy
- okta_policy_rule_password
- okta_auth_server_policy_rule
- okta_policy_rule_signon
- okta_policy_rule_idp_discovery
- okta_user_schema_property
- okta_policy_password
- okta_user_schema
- okta_policy_signon
- okta_app_group_assignment
- okta_policy_rule_mfa
- okta_app_group_assignments
- okta_policy_mfa_default
- okta_app_signon_policy_rule
- okta_policy_password_default
- okta_policy_mfa
- okta_group_schema_property
- okta_auth_server_policy

**Comment by tmatilai** [comment]
I'm not sure if the Okta API would even allow this, but the Datadog provider has an interesting take on ordered lists by specifying a separate resource for ordering, e.g. [datadog_logs_pipeline_order](https://github.com/DataDog/terraform-provider-datadog/blob/master/datadog/resource_datadog_logs_pipeline_order.go) ([docs](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/logs_pipeline_order)).

In my experience the `priority` attribute is quite annoying to maintain, so this might be help there, too. Another option (which definitely would require changes in Okta API and web console) would be to allow non-consecutive priorities, like with AWS Network ACL rules.

**Comment by monde** [comment]
Dropping this example for the upcoming v3.34.0 release that demonstrates how to chain resources (that will now have proper concurrency coordination) using the `depends_on` meta argument so that the Okta service will respect the desired priority assignments.

```terraform
data "okta_group" "all" {
  name = "Everyone"
}
resource "okta_auth_server" "test" {
  name        = "testAcc_replace_with_uuid"
  description = "test"
  audiences   = ["whatever.rise.zone"]
}
resource "okta_auth_server_policy" "test" {
  name             = "test"
  description      = "test"
  priority         = 1
  client_whitelist = ["ALL_CLIENTS"]
  auth_server_id   = okta_auth_server.test.id
}

resource "okta_auth_server_policy_rule" "test_00" {
  auth_server_id       = okta_auth_server.test.id
  policy_id            = okta_auth_server_policy.test.id
  status               = "ACTIVE"
  name                 = "Test Policy Rule 00"
  priority             = 1 
  group_whitelist      = [data.okta_group.all.id]
  grant_type_whitelist = ["implicit"]
  
}
resource "okta_auth_server_policy_rule" "test_01" {
  auth_server_id       = okta_auth_server.test.id
  policy_id            = okta_auth_server_policy.test.id
  status               = "ACTIVE"
  name                 = "Test Policy Rule 01"
  priority             = 2 
  group_whitelist      = [data.okta_group.all.id]
  grant_type_whitelist = ["implicit"]
  depends_on = [okta_auth_server_policy_rule.test_00]
}
resource "okta_auth_server_policy_rule" "test_02" {
  auth_server_id       = okta_auth_server.test.id
  policy_id            = okta_auth_server_policy.test.id
  status               = "ACTIVE"
  name                 = "Test Policy Rule 02"
  priority             = 3 
  group_whitelist      = [data.okta_group.all.id]
  grant_type_whitelist = ["implicit"]
  depends_on = [okta_auth_server_policy_rule.test_01]
}
resource "okta_auth_server_policy_rule" "test_03" {
  auth_server_id       = okta_auth_server.test.id
  policy_id            = okta_auth_server_policy.test.id
  status               = "ACTIVE"
  name                 = "Test Policy Rule 03"
  priority             = 4 
  group_whitelist      = [data.okta_group.all.id]
  grant_type_whitelist = ["implicit"]
  depends_on = [okta_auth_server_policy_rule.test_02]
}
resource "okta_auth_server_policy_rule" "test_04" {
  auth_server_id       = okta_auth_server.test.id
  policy_id            = okta_auth_server_policy.test.id
  status               = "ACTIVE"
  name                 = "Test Policy Rule 04"
  priority             = 5 
  group_whitelist      = [data.okta_group.all.id]
  grant_type_whitelist = ["implicit"]
  depends_on = [okta_auth_server_policy_rule.test_03]
}
resource "okta_auth_server_policy_rule" "test_05" {
  auth_server_id       = okta_auth_server.test.id
  policy_id            = okta_auth_server_policy.test.id
  status               = "ACTIVE"
  name                 = "Test Policy Rule 05"
  priority             = 6 
  group_whitelist      = [data.okta_group.all.id]
  grant_type_whitelist = ["implicit"]
  depends_on = [okta_auth_server_policy_rule.test_04]
}
resource "okta_auth_server_policy_rule" "test_06" {
  auth_server_id       = okta_auth_server.test.id
  policy_id            = okta_auth_server_policy.test.id
  status               = "ACTIVE"
  name                 = "Test Policy Rule 06"
  priority             = 7 
  group_whitelist      = [data.okta_group.all.id]
  grant_type_whitelist = ["implicit"]
  depends_on = [okta_auth_server_policy_rule.test_05]
}
resource "okta_auth_server_policy_rule" "test_07" {
  auth_server_id       = okta_auth_server.test.id
  policy_id            = okta_auth_server_policy.test.id
  status               = "ACTIVE"
  name                 = "Test Policy Rule 07"
  priority             = 8 
  group_whitelist      = [data.okta_group.all.id]
  grant_type_whitelist = ["implicit"]
  depends_on = [okta_auth_server_policy_rule.test_06]
}
resource "okta_auth_server_policy_rule" "test_08" {
  auth_server_id       = okta_auth_server.test.id
  policy_id            = okta_auth_server_policy.test.id
  status               = "ACTIVE"
  name                 = "Test Policy Rule 08"
  priority             = 9 
  group_whitelist      = [data.okta_group.all.id]
  grant_type_whitelist = ["implicit"]
  depends_on = [okta_auth_server_policy_rule.test_07]
}
resource "okta_auth_server_policy_rule" "test_09" {
  auth_server_id       = okta_auth_server.test.id
  policy_id            = okta_auth_server_policy.test.id
  status               = "ACTIVE"
  name                 = "Test Policy Rule 09"
  priority             = 10 
  group_whitelist      = [data.okta_group.all.id]
  grant_type_whitelist = ["implicit"]
  depends_on = [okta_auth_server_policy_rule.test_08]
}
```

**Comment by monde** [comment]
I'm going to close this issue, if anyone runs into it again ask to open it back up. I solved the concurrency for `okta_auth_server_policy_rule` in #1248 released as [v3.34.0](https://github.com/okta/terraform-provider-okta/releases/tag/v3.34.0) and no doubt the fix and be reapply in new found offenders.

**Comment by monde** [comment]
0 value integer serialization is fixed now in [v3.44.0](https://github.com/okta/terraform-provider-okta/releases/tag/v3.44.0) release.

**Comment by d02540315** [comment]
Hey @monde, could you share why we have to supply priority for auth_server_policy? Here are the reasons I ask and want to learn how it is supposed to work:

- In our organization, we have >10 business units and each BU has more than one API tokens assigned with okta admin access. We don't want to manage the priorities since all our access policies are specific to Okta applications (clients). Therefore the priority doesn't matter to us.
- During my testing, I wanted to create 10 auth server policies with one signle TF apply. If I supply same priority (e.g, 1) for these 10 auth server policies, tf apply errored and all I could see is 500 Internal Error from Okta TF provider without more specific error message. It often ends up I have to run "tf apply" many times and eventually it would apply. Same issue with "tf destroy".
- I tried to set priority 99999 (or any random big number) for all my 10 auth server policies, it worked. It also worked with "tf detroy".

So, what would be suggestion in our case since we don't want to manage the priorities and would rather have Okta to manage it for us.

**Comment by monde** [comment]
@d02540315 I believe that is indicative of a bug in the Okta service where it is sensitive to asynchronous calls on resources that have a priority attribute. Can you run your script with parallelism set to 1? `tf apply -parallelism=1` and see if the 500s go away? If yes, then that is a bug on the Okta side and please open a support ticket https://support.okta.com/

**Comment by d02540315** [comment]
@monde Tried with setting the priority as 1 for all my auth_server_policy with -parallelism=1, it worked! Thanks.

Its interesting, since I supplied priority as 1 for all my auth server policies, actually Okta still would assign a priority by its own. It seems to me Okta would add the newly added access_server_policy as priority 1, re-sort all the access policies. It looks like priority should be optional (instead of required field) to me.

**Comment by wcarson** [comment]
Can this bug be re-opened? This is still an issue for `okta_app_group_assignments`. Every apply will include a change to this resource if priority is specified. Is there a workaround?
