### ISSUE TITLE
Change #1193 requires the Identity Engine functionality to be active on the okta tenant to work

### ISSUE THREAD

**Issue by timgates42** [okta/terraform-provider-okta#1202]
Terraform provider 3.31 update raises the error "The request was not valid: Invalid policy type specified." when querying the available policies of type ACCESS_POLICIES for an Okta tenant that does not use the IDENTITY_ENGINE functionality.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.4

### Affected Resource(s)

- [`okta_app_signon_policy`](https://github.com/okta/terraform-provider-okta/pull/1193) but even having zero of these seems to trigger the issue

### Debug Output

```
[INFO]  provider.terraform-provider-okta_v3.31.0: 2022/07/12 01:31:47 [DEBUG] Okta API Request Details:

---[ REQUEST ]---------------------------------------

GET /api/v1/policies?type=ACCESS_POLICY HTTP/1.1


022-07-12T01:31:47.341Z [INFO]  provider.terraform-provider-okta_v3.31.0: 2022/07/12 01:31:47 [DEBUG] Okta API Response Details:

---[ RESPONSE ]--------------------------------------

HTTP/2.0 400 Bad Request


{

 "errorCode": "E0000002",

 "errorSummary": "The request was not valid: Invalid policy type specified.",

 "errorLink": "E0000002",

 "errorId": "oaenzcfa75UQjK2Yac7cNzuCQ",

 "errorCauses": []

}
```

### Important Factoids

ACCESS_TYPE on get policies request requires IDENTITY_ENGINE upgrade see...

https://developer.okta.com/docs/reference/api/policy/#policy-object
![image](https://user-images.githubusercontent.com/47873678/178407749-44ef46a7-5491-47bf-aeb8-5b004b219756.png)

### References

- #1193

**Comment by VictorGFM** [comment]
I believe I'm facing the same "invalid policy type" issue when trying to create an Okta App using the resource `okta_app_saml`. It throws the  following error:
```
╷
│ Error: failed to set authentication policy for an SAML application: failed delete authentication policy: 
│ the API returned an error: The request was not valid: Invalid policy type specified.
...
│   24: resource "okta_app_saml" "this" {
│ 
```
Is it possible to make this `authentication_policy` update to be backward compatible with `okta_app_saml` created on Okta orgs that are still using the Okta Classic Engine? Right now the only option I see to be able to continue using the `okta_app_saml` resource is to pin the provider version to `3.30.0` or be forced to upgrade to Identity Engine.

**Comment by sklarsa** [comment]
Also seeing the same thing as @VictorGFM

**Comment by lyndoh** [comment]
Also seeing a similar issue when creating an `okta_app_oauth` resource. eg. just try the example https://github.com/okta/terraform-provider-okta/blob/master/examples/okta_app_oauth/native.tf and get
```
okta_app_oauth.test: Creating...
╷
│ Error: failed to set authentication policy for an OAuth application: failed delete authentication policy: the API returned an error: The request was not valid: Invalid policy type specified.
```

We only have "API Access Management" functionality/product enabled.

Cheers

**Comment by Mrorya** [comment]
Seeing the same issue on 3.31 with an okta_app_oauth resource on _update_ - interestingly, this did not trigger for all applications when upgrading from TFE 3.24 to 3.31

```
okta_app_oauth.redacted: Modifying... [id=####################]
╷
│ Error: failed to set authentication policy an OAuth application: failed delete authentication policy: the API returned an error: The request was not valid: Invalid policy type specified.
│ 
│   with okta_app_oauth.redacted,
│   on apps.tf line ####, in resource "okta_app_oauth" “redacted”:
│ ####: resource "okta_app_oauth" “redacted” {
````

We have no signon policies configured for this application (as we're on classic still)

**Comment by monde** [comment]
Just getting back from vacation, apologies for a delayed response and apologies for what I believe is a breaking change. I will give this my top priority.

**Comment by CodyDunlap** [comment]
I'm getting this same issue for the `okta_app_oauth` resource. I also have no signon policies configured and use Okta Classic engine. 

This breaking change effects previous versions of the provider also. My configuration was on version 3.22 of the Okta TF provider and we started getting this error recently when we create a new oauth app. Upgrading to the latest version of the provider has not resolved the issue.

**Comment by cavila-evoliq** [comment]
My company is also presently experiencing this error. We were previously on provider version 3.18 and upgraded all of our providers, which upgrade Okta to 3.31. Our applies are failing after this upgrade with the following:

`Error: failed to set authentication policy an OAuth application: failed delete authentication policy: the API returned an error: The request was not valid: Invalid policy type specified.`

We had successful runs as recently as two days ago, prior to upgrading the provider, and our okta tf has not changed in that time.

**Comment by monde** [comment]
I'm going to be going after the policy bugs next week. I just added to ability for the provider to discover easily if the org is Classic or OIE, so that will be helpful to put bumpers around resource behavior is that mutually exclusive OIE to Classic and visa versa.

**Comment by pro4tlzz** [comment]
> I believe I'm facing the same "invalid policy type" issue when trying to create an Okta App using the resource `okta_app_saml`. It throws the following error:
> 
> ```
> ╷
> │ Error: failed to set authentication policy for an SAML application: failed delete authentication policy: 
> │ the API returned an error: The request was not valid: Invalid policy type specified.
> ...
> │   24: resource "okta_app_saml" "this" {
> │ 
> ```
> 
> Is it possible to make this `authentication_policy` update to be backward compatible with `okta_app_saml` created on Okta orgs that are still using the Okta Classic Engine? Right now the only option I see to be able to continue using the `okta_app_saml` resource is to pin the provider version to `3.30.0` or be forced to upgrade to Identity Engine.

I'm facing the same issue on classic and the latest provider version

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-524637

**Comment by ianwinsemius** [comment]
So I ran into this today and found an easy workaround. Add the following line to your `okta_app_saml`, or `okta_app_oauth` resources. As far as I can tell from limited testing, this doesn't affect okta-classic, app defined sign-on policy rules.

```
 authentication_policy = null
```

**Comment by tmatilai** [comment]
Setting an attribute to `null` is the same as not setting it at all, i.e. using the default value specified in the provider. So I don't think that only explains the success. 🤔 

The error doesn't seem to occur consistently, so hard to say. And I don't really understand the issue and haven't investigated it, so I can be wrong of course. 🙂

**Comment by ianwinsemius** [comment]
It was occurring intermittently in different environments until I set it to null in the configuration. I agree that this should be the same as not setting it at all, but after explicitly setting it to `null`, I haven't encountered these errors.

Just trying to give people an option to try in a pinch, I do not think this is an actual resolution.
