### ISSUE TITLE
Error when trying to create a `okta_app_oauth` resource

### ISSUE THREAD

**Issue by rsheppardsos** [okta/terraform-provider-okta#1204]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v1.2.5
on darwin_amd64
+ provider registry.terraform.io/okta/okta v3.31.0
```

### Affected Resource(s)

- `okta_app_oauth`

### Terraform Configuration Files
```hcl
resource "okta_app_oauth" "k8s_oidc" {
  label                      = "kubernetes-${var.environment}"
  type                       = "native"
  token_endpoint_auth_method = "none"
  grant_types                = ["authorization_code"]
  response_types             = ["code"]
  redirect_uris              = ["http://localhost:8000"]
  post_logout_redirect_uris  = ["http://localhost:8000"]

  lifecycle {
    ignore_changes = [groups]
  }
}
```

I am following the instructions from here: https://developer.okta.com/blog/2021/11/08/k8s-api-server-oidc

### Debug Output
https://gist.github.com/rsheppardsos/d6379e8d95f18b75e2e4d02ec752f9f2
I omitted quite a bit so let me know if there's more log lines needed.

### Panic Output
n/a

### Expected Behavior
The resource should create successfully and Terraform should exit without an error. 

### Actual Behavior
The resource is created in Okta, but Terraform exits with this error code: 
```
│ Error: failed to set authentication policy for an OAuth application: failed delete authentication policy: the API returned an error: The request was not valid: Invalid policy type specified.
│
│   with module.oidc.okta_app_oauth.k8s_oidc,
│   on ../modules/kubernetes_oidc/main.tf line 1, in resource "okta_app_oauth" "k8s_oidc":
│    1: resource "okta_app_oauth" "k8s_oidc" {
```
The resource is then tainted, leading to this error occuring on the next apply and any subsequent resources not being created. Manually un-tainting the resource and running `terraform apply` will work however.

### Steps to Reproduce

1. Install the Okta provider version `v3.31`
2. Attempt to create an `okta_app_oauth` resource with the configuration above
3. Run `terraform apply`
4. The error will be displayed

### Important Factoids
Rolling back to v3.30 works just fine. I was able to manually untaint the resource and create everything just fine in v3.31, as the OAuth App is created in the Okta dashboard.

I am currently running this against our Okta Preview environment.

### References
n/a

**Comment by vglen** [comment]
I am seeing the exact same behavior on `3.31`.

**Comment by fatbasstard** [comment]
Hit the same issue and the `untaint` option is indeed a hotfix. Looking forward for the structural fix in a new release

**Comment by slichtenthal** [comment]
Same issue, though in `okta_app_saml`

I did a little bit of research and found the call that is failing is to `/api/v1/policies?type=ACCESS_POLICY`.  This only works if you have the Identity Engine enabled in Okta, which not all environments do, as documented [here](https://developer.okta.com/docs/reference/api/policy/#authentication-policy).

 I think the fix would be to either have a setting in the provider config to say whether or not identity engine is enabled or not set the authentication policy at all if no value is passed in.

**Comment by monde** [comment]
Apologies for the slow ack on this bug, I'm just getting back from vacation. Marking this a bug.

**Comment by conradchan1213** [comment]
I am encountering the exact same issue and identified the same conclusion as https://github.com/okta/terraform-provider-okta/issues/1204#issuecomment-1185504995

**Comment by monde** [comment]
fyi, I consider this a regression, I'm investigating a similar item with @dkulchinsky

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-524631
