### ISSUE TITLE
Public API and associated Terraform resources for custom signin page

### ISSUE THREAD

**Issue by sebman-metro** [okta/terraform-provider-okta#1205]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We are trying to completely automate our Okta deployments with Terraform and 1 of the thing missing right now is the ability to push custom signin pages and error pages via Terraform.

Now I understand that you also need a public API for that, which does not exist.

So what I am asking is the following:

- Public API for managing custom signin pages and error pages (which I will not be using)
- A terraform resource that consume this API so I can push my custom signin/error pages Terraform.

### New or Affected Resource(s)

- okta_XXXXX   

### Potential Terraform Configuration

At minimum, I would like to have somthing like this:
```hcl
resource okta_signin {
	signin_html 		= file("path_to_signin_file.html")
	error_html		= file("path_to_error_file.html")
	major_version		= 6
	minor_version		= latest
}
```

### References

- #0000

**Comment by monde** [comment]
Apologies for the slow reply @sebman-fizz-vl  , I'm just getting back from vacation. We'll have to prioritize working on this enhancement.

**Comment by sebman-metro** [comment]
No problem. (I changed my username)

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-524630
