### ISSUE TITLE
data_source_okta_user - remove suppression of custom roles

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1208]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently if you were to try to use the datasource `okta_user` to determine if a user was an admin using the `admin_roles` attribute, this would be unreliable as we suppress custom roles from making it to this field
This was likely an intentional choice at some point (it might've been me in a previous PR) likely because of how we pass the role type back up instead of the whole role object [here](https://github.com/okta/terraform-provider-okta/blob/2759a0e79ffd4be435dae093364f013f44a3d713/okta/user.go#L261)
thus at the top level where only role types are presented we'd only have the string `CUSTOM` which is not helpful in determining which role a user might have, thus it might've been chosen to be omitted
however, this info is useful in determining if a user has admin permissions at all (useful for signon policies and whatnot)

I can also see that we seem to limit the roles returned to roles with scope `USER` its unclear to me if this would omit roles inherited from a group and limit the returned roles to those only assigned directly to the user 
I believe the `admin_roles` attribute should return all roles a user has access to, whether directly assigned or via a group

For the Custom roles, perhaps we can surface the role ID instead of the `CUSTOM` string, curious to hear peoples thoughts

### New or Affected Resource(s)

- data_source_okta_user

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by monde** [comment]
Thanks @exitcode0 , I'll have to look into this further, thanks for the detail description.

**Comment by monde** [comment]
I'll call wishy washy behavior a bug.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-524628

**Comment by exitcode0** [comment]
@monde
Just wanting to clarify if this was closed by stale-bot or if this is considered a won't fix?

**Comment by monde** [comment]
@exitcode0 - reopening. Stalebot, Stalebot'ing.

**Comment by monde** [comment]
@duytiennguyen-okta from our postman debugging `GET /api/v1/users/00u6uk65c2pwlHgfX1d7/roles`:

```json
[
    {
        "id": "ra16v80vol2Owg1ho1d7",
        "label": "Read-only Administrator",
        "type": "READ_ONLY_ADMIN",
        "status": "ACTIVE",
        "created": "2023-01-31T20:42:06.000Z",
        "lastUpdated": "2023-01-31T20:42:06.000Z",
        "assignmentType": "USER",
        "_links": {
            "assignee": {
                "href": "https://test.oktapreview.com/api/v1/users/00u6uk65c2pwlHgfX1d7"
            }
        }
    },
    {
        "id": "irb6v7zrflApky1QV1d7",
        "label": "View Users",
        "type": "CUSTOM",
        "status": "ACTIVE",
        "created": "2023-01-31T20:42:42.000Z",
        "lastUpdated": "2023-01-31T20:42:42.000Z",
        "assignmentType": "USER",
        "resource-set": "iam6v7zquga77Taf71d7",
        "role": "cr06v7xzlxb7uhMig1d7",
        "_links": {
            "role": {
                "href": "https://test-admin.oktapreview.com/api/v1/iam/roles/cr06v7xzlxb7uhMig1d7"
            },
            "resource-set": {
                "href": "https://test.oktapreview.com/api/v1/iam/resource-sets/iam6v7zquga77Taf71d7"
            },
            "permissions": {
                "href": "https://test-admin.oktapreview.com/api/v1/iam/roles/cr06v7xzlxb7uhMig1d7/permissions"
            },
            "member": {
                "href": "https://test.oktapreview.com/api/v1/iam/resource-sets/iam6v7zquga77Taf71d7/bindings/cr06v7xzlxb7uhMig1d7/members/irb6v7zrflApky1QV1d7"
            },
            "assignee": {
                "href": "https://test.oktapreview.com/api/v1/users/00u6uk65c2pwlHgfX1d7"
            }
        }
    }
]
```

**Comment by duytiennguyen-okta** [comment]
@exitcode0 In this case I don't think we should modified the behaviour of the admin_roles attribute as it could lead to unwanted complication. So what I can do is create a roles attribute that should return all roles that the user has access to. What do you think?

**Comment by exitcode0** [comment]
No stalebot 🙂

**Comment by exitcode0** [comment]
> @exitcode0 In this case I don't think we should modified the behaviour of the admin_roles attribute as it could lead to unwanted complication. So what I can do is create a roles attribute that should return all roles that the user has access to. What do you think?

My apologies for missing this, I think a custom roles attribute makes sense in order to avoid needing to communicate the behavior change
