### ISSUE TITLE
resource_okta_app_group_assignments - add attribute "groups"

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1211]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the `okta_app_group_assignments` resource does not have a `groups` attribute, meaning if I want to pass an array of group IDs that are assigned to a given app I need to use a datasource for `okta_app_group_assignments` 
This is API inefficient if the `okta_app_group_assignments` are already managed by Terraform 

If we add a `groups` attribute to the `okta_app_group_assignments` resource the data can be retrieved without the need to hit the Okta API again
This will save on calls against the `/api/v1/apps*` rate limit (often a bottleneck for TF deployments)

### New or Affected Resource(s)

- resource_okta_app_group_assignments
- data_source_okta_app_group_assignments

### Potential Terraform Configuration

Current HCL
```hcl
data "okta_group" "google" {
  for_each = toset(data.okta_app_group_assignments.google.groups[*])
  id       = each.key
}

resource "okta_group_role" "google" {
  group_id  = okta_group.tf_testing_admin.id
  role_type = "GROUP_MEMBERSHIP_ADMIN"
  target_group_list = [
    for group in data.okta_group.google : group.id if
    group.type == "OKTA_GROUP" &&
    group.id != okta_group.tf_testing_admin.id
  ]
}
```

Proposed HCL
```hcl
data "okta_group" "google" {
  for_each = toset(okta_app_group_assignments.google.groups[*])
  id       = each.key
}

resource "okta_group_role" "google" {
  group_id  = okta_group.tf_testing_admin.id
  role_type = "GROUP_MEMBERSHIP_ADMIN"
  target_group_list = [
    for group in data.okta_group.google : group.id if
    group.type == "OKTA_GROUP" &&
    group.id != okta_group.tf_testing_admin.id
  ]
}
```

### References

- #0000

**Comment by monde** [comment]
Thanks @exitcode0 , sounds good to me.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-524623

**Comment by exitcode0** [comment]
I must've been not been sufficiently caffeinated when I opened this issue, revisted this today and the below works
The data is there, its just in a more complex objects structure than flat list of strings, i think its a list of objects

I think we can mark this as closed with a workaround
```hcl
resource "okta_group_role" "google" {
  group_id  = okta_group.group.id
  role_type = "GROUP_MEMBERSHIP_ADMIN"

  target_group_list = [
    for group in okta_app_group_assignments.name.group : group.id if
    group.id != okta_group.group.id
  ]
}
```

**Comment by monde** [comment]
@exitcode0 can this issue be closed? I'll put the stale label back on it.
