### ISSUE TITLE
okta_app_user_schema_property - failed to update custom app user schema property: the API returned an error

### ISSUE THREAD

**Issue by Mrorya** [okta/terraform-provider-okta#1219]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform 1.1.5
Provider v3.31.0

### Affected Resource(s)

- okta_app_user_schema_property

### Terraform Configuration Files

```hcl
resource "okta_app_user_schema_property" "flex_prod_checking_direct" {
  app_id     = okta_app_saml.twilio_flex_prod.id
  index      = "topic_skills_checkingDD"
  title      = "Checking Account - Direct Deposit"
  type       = "array"
  master     = "PROFILE_MASTER"
  scope      = "NONE"
  array_type = "integer"
  array_enum = ["5", "10"]
  array_one_of {
    const = "5"
    title = "5"
  }
  array_one_of {
    const = "10"
    title = "10"
  }
  permissions = "READ_WRITE"
  union       = true
  user_type   = "default"
}
```

### Expected Behavior

We've just updated to v3.31.0 and we're attempting to update a custom attribute on an application with array values as noted above. We were previously on 3.24.0 and updated similar attributes with similar array values.

### Actual Behavior

```
│ Error: failed to update custom app user schema property: the API returned an error: The enum constraint com.fasterxml.jackson.databind.node.TextNode "5" is not valid for the given property type java.lang.Long., x-okta-request-id=
│ 
│   with okta_app_user_schema_property.flex_prod_checking_direct,
│   on twilio_flex_prod-app_user_schema_properties.tf line 368, in resource "okta_app_user_schema_property" "flex_prod_checking_direct":
│  368: resource "okta_app_user_schema_property" "flex_prod_checking_direct" {
│ 
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nothing that I'm aware of! Let me know if the log file is necessary

### References

- #1175 - Not sure if it's related to the fix for this issue. @monde had helped debug+resolve that one.

**Comment by Mrorya** [comment]
I think the comment in the original issue explains the error here - closing this out ! https://github.com/okta/terraform-provider-okta/issues/1175#issuecomment-1167963587

**Comment by Mrorya** [comment]
I lied! This is _not_ fixed by modifying the array_enum or array_one_of values - updated the description and reopening the issue

**Comment by monde** [comment]
Thanks for the details @Mrorya . The TF SDK schema inflexibility is a pita when trying to give the Okta API explicit types. Hopefully I can smooth that out as well.

**Comment by Mrorya** [comment]
FWIW, this also failed on attribute creation with the same error (attempted to delete + re-create)

**Comment by Mrorya** [comment]
Any update here? We're kinda stuck making any new attributes with arrays due to this issue, but rolling back to a previous provider version would reintroduce other bugs that have been fixed between 3.24->3.33

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-520008

**Comment by monde** [comment]
Released https://github.com/okta/terraform-provider-okta/releases/tag/v3.37.0
