### ISSUE TITLE
okta_inline_hook data source with name attribute reference

### ISSUE THREAD

**Issue by oreni** [okta/terraform-provider-okta#1228]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We wish to access inline hook resources by name to associate it to policy rules in different folders.

### New or Affected Resource(s)

new data source:
okta_inline_hook 
with name as attribute reference

### Potential Terraform Configuration

```hcl
data "okta_inline_hook" "example" {
  type    = "com.okta.oauth2.tokens.transform"
  id        = cal47ymrs5jexamplex7
  name  = "inlineHookName"
}

```

- #0000

**Comment by monde** [comment]
Thanks @oreni . Would bring parity to the corresponding resource https://registry.terraform.io/providers/okta/okta/latest/docs/resources/inline_hook

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-524618

**Comment by oreni** [comment]
Please keep open and update on development for this. 
Thanks.

**Comment by richard-collette-precisely** [comment]
Please re-open this issue.  Creating and using an inline hook is currently a two step manual process.  Deploy new hook, get Id, deploy again with id referenced in access policy rules.

**Comment by taigapup** [comment]
Hi, I understand this is a stale issue but there is a definite need to add okta_inline_hook data source with either a name or id reference. Currently the resource for an inline hook has to be in the same terraform state file as its consumers, which in turn means all the authorization policies must be in the same terraform file as the inline hook. It's possible to do but unnecessarily complicated. Requesting you reopen this issue and address.
