### ISSUE TITLE
okta_app_signon_policy_rule -> Add CHROMEOS to the values list for the os_type

### ISSUE THREAD

**Issue by eduhamel** [okta/terraform-provider-okta#1236]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

CHROMEOS platform cannot be used for the time being using:
platform_include {
      os_type = "CHROMEOS"
      type    = "DESKTOP"
  }
It can be achieved using Okta APIs so I believe this is a minor enhancement! 

### New or Affected Resource(s)

- okta_app_signon_policy_rule
- any resource leveraging platform criteria

### Potential Terraform Configuration

platform_include {
      os_type = "CHROMEOS"
      type    = "DESKTOP"
  }

**Comment by monde** [comment]
@eduhamel I'll try and get this quick fix into the next release.

**Comment by monde** [comment]
fyi @eduhamel this work is in my current sprint.

Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-521256
