### ISSUE TITLE
support import of okta_app_signon_policy_resource

### ISSUE THREAD

**Issue by AnnaGiliaeva** [okta/terraform-provider-okta#1238]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Import of resource okta_app_signon_policy is currently not supported. It is possible to import okta_app_signon_policy_rule resource from Okta and it would be helpful to have a functionality to import okta_app_signon_policy as well.

### New or Affected Resource(s)

- okta_app_signon_policy

### References

- #0000

**Comment by monde** [comment]
Thanks @AnnaGiliaeva

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-524215

**Comment by monde** [comment]
Need to look at this in the policy focused sprint.

**Comment by duytiennguyen-okta** [comment]
I fixed this https://github.com/okta/terraform-provider-okta/pull/1670 and will be released later this week.
