### ISSUE TITLE
Provide SAML Metadata URL

### ISSUE THREAD

**Issue by netflash** [okta/terraform-provider-okta#124]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Provide SAML Metadata URL as Attribute.
This is helpful for applications that can download XML data directly from Okta SAML App metadata URL, e.g. Jenkins.

### New or Affected Resource(s)

* okta_app_saml

### Potential Terraform Configuration

```hcl
resource okta_saml_app jenkins {
...
}

output jenkins_saml_metadata_url {
  value = okta_saml_app.jenkins.metadata_url
} 
```

### References

There is a `GetSAMLMetdata` API Supplement already - see https://github.com/terraform-providers/terraform-provider-okta/blob/71e363be2678f66f999699351f57a98350e52ddb/sdk/api_supplement.go#L21

So it should be relatively easy to implement.

**Comment by ivan-sukhomlyn** [comment]
@netflash Hi,
I'm looking forward to this attribute as well)

It's pretty similar to https://github.com/terraform-providers/terraform-provider-okta/issues/72

**Comment by netflash** [comment]
Hopefully, this can be added relatively soon.

**Comment by bogdanprodan-okta** [comment]
Currently, there is a `"metadata"` attribute available, which contains raw data from the metadata URL.
