### ISSUE TITLE
Add support for Device Assurance

### ISSUE THREAD

**Issue by lucascantor** [okta/terraform-provider-okta#1240]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With the release of [Device Assurance](https://help.okta.com/oie/en-us/Content/Topics/identity-engine/devices/device-assurance.htm), Terraform-managed `okta_app_signon_policy_rule` resources cannot [have Device Assurance policies added to them](https://help.okta.com/oie/en-us/Content/Topics/identity-engine/devices/device-assurance-policy-rule.htm) until an Okta Terraform provider version is released with support for this.

A new resource should also be created to manage [Device Assurance policies](https://help.okta.com/oie/en-us/Content/Topics/identity-engine/devices/device-assurance-add.htm) themselves, for example, `okta_policy_device_assurance`

### New or Affected Resource(s)

Affected
- `okta_app_signon_policy_rule`

New
- `okta_policy_device_assurance`

**Comment by monde** [comment]
Thanks @lucascantor , agreed we need to create this.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-524213

**Comment by lucascantor** [comment]
Okta just [published a YouTube video advertising Device Assurance](https://www.youtube.com/watch?v=UERaxr743gk).

It looks like a critical capability to have, but we unfortunately still can't use it until this functionality is added.
Does this video's release mean it's any closer?

**Comment by lucascantor** [comment]
Commenting to keep this alive.

@monde could the `no-stalebot` label maybe be added so this doesn't get closed?

I assume Okta is still committed to supporting Device Assurance.

**Comment by pennethus** [comment]
@lucascantor Do we need this issue closed out before we can close [this risk](https://simplerisk.security.intercom.io/management/view.php?id=1101)? And we're waiting on Okta to release something?

**Comment by lucascantor** [comment]
@pennethus this GitHub issue is for Okta Device Assurance, which doesn't strictly relate to [that risk](https://simplerisk.security.intercom.io/management/view.php?id=1101), which is for Okta Device Trust.

However, once this GitHub issue is resolved, we can use Okta Device Assurance to require various device security posture criteria to be met when signing in to various apps via Okta, even on non-managed devices.

**Comment by lucascantor** [comment]
Not stale 🥲

**Comment by gabrielsroka** [comment]
https://developer.okta.com/docs/api/openapi/okta-management/management/tag/DeviceAssurance/#tag/DeviceAssurance/operation/createDeviceAssurancePolicy

**Comment by lucascantor** [comment]
Thanks @gabrielsroka 

Good to see the necessary public API is finally available to unblock this.

**Comment by pro4tlzz** [comment]
Hopefully it's added to the golang SDK soon

**Comment by gabrielsroka** [comment]
It looks like there's some mention of it:

https://github.com/okta/okta-sdk-golang/blob/3bb2eb53d07eca8ebeb90ddac990a0da9e07b1a0/.generator/okta-management-APIs-oasv3-noEnums-inheritance.yaml#L5973

Also in the .net SDK:
https://github.com/okta/okta-sdk-dotnet/blob/41ac3fde0b83b8eb0a708990cf843b119fa18dc5/docs/DeviceAssuranceApi.md

And in this repo:
https://github.com/okta/terraform-provider-okta/blob/6c88ddaf60648fb8cb3e4d702a1ffba2ea96e3c8/okta/internal/apimutex/rate_limit_lines.go#L348-L352

**Comment by pro4tlzz** [comment]
> It looks like there's some mention of it:
> 
> https://github.com/okta/okta-sdk-golang/blob/3bb2eb53d07eca8ebeb90ddac990a0da9e07b1a0/.generator/okta-management-APIs-oasv3-noEnums-inheritance.yaml#L5973
> 
> Also in the .net SDK: https://github.com/okta/okta-sdk-dotnet/blob/41ac3fde0b83b8eb0a708990cf843b119fa18dc5/docs/DeviceAssuranceApi.md
> 
> And in this repo:
> 
> https://github.com/okta/terraform-provider-okta/blob/6c88ddaf60648fb8cb3e4d702a1ffba2ea96e3c8/okta/internal/apimutex/rate_limit_lines.go#L348-L352

That is great, it might be part of the big OpenAPI release https://github.com/okta/terraform-provider-okta/issues/1147#issuecomment-1433341500

**Comment by monde** [comment]
cc: @jefftaylor-okta

**Comment by karthig-okta** [comment]
Okta will review this request

**Comment by lucascantor** [comment]
@karthig-okta thank you so much!

**Comment by karthig-okta** [comment]
Hi @lucascantor and everyone else. You can expect Device Assurance support to land sometime between June and August this year.

**Comment by lucascantor** [comment]
Not stale

**Comment by jesseadams** [comment]
@karthig-okta Any updates? June is almost over

**Comment by monde** [comment]
I'm going to be working on this starting in mid-July.

**Comment by mhrono** [comment]
Is [this](https://github.com/okta/terraform-provider-okta/issues/1240#issuecomment-1507599360) release timeline still accurate? This functionality is critical to unblocking internal projects.

**Comment by jefftaylor-okta** [comment]
@mhrono, the timeline is still accurate! We are currently working on finishing this feature up, and hope to release mid-August.

**Comment by duytiennguyen-okta** [comment]
This is fixed in the release [4.2.0](https://github.com/okta/terraform-provider-okta/releases/tag/v4.2.0) from https://github.com/okta/terraform-provider-okta/pull/1659

**Comment by reinoudk** [comment]
Cool stuff @duytiennguyen-okta ! 🚀 

One question: the issue also mentions support for referencing device assurance policies in `okta_app_signon_policy_rule` resources, but I don't think that was added. Is this on the roadmap? 

I can see that the SDK does not support it yet, as the `DeviceAccessPolicyRuleCondition` in the OpenAPI [file](https://github.com/okta/okta-sdk-golang/blob/master/.generator/okta-management-APIs-oasv3-enum-inheritance.yaml#L21063) does not have the `assurance` property. The API does support it though, is there anything preventing this property from being added to the OpenAPI spec?

**Comment by duytiennguyen-okta** [comment]
It was added as attribute [here](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_signon_policy_rule#device_assurances_included)

**Comment by reinoudk** [comment]
Shoot, my bad! Don't know how I missed that. Thanks for pointing it out!
