### ISSUE TITLE
Add support to pkce_required property for OIDC app integrations

### ISSUE THREAD

**Issue by martinstuga** [okta/terraform-provider-okta#1241]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is a new property available in OAuth Application: https://developer.okta.com/docs/release-notes/2022-okta-identity-engine/#monthly-release-2022-08-0

PKCE validation for OIDC app integrations is GA in Preview

[You can now require Proof Key for Code Exchange (PKCE) as an additional verification for any OpenID Connect app integration except service apps. This more closely aligns with the OAuth Security Best Current Practice recommendation to use PKCE with the authorization code flow regardless of the client type. Use the pkce_required ](https://developer.okta.com/docs/release-notes/2022-okta-identity-engine/#pkce-validation-for-oidc-app-integrations-is-ga-in-preview)[property](https://developer.okta.com/docs/reference/api/apps/#oauth-credential-object) with the Apps API to require PKCE for your app.

It would be good to support this new property in this module.

### New or Affected Resource(s)

- okta_app_oauth

### References

https://developer.okta.com/docs/release-notes/2022-okta-identity-engine/#monthly-release-2022-08-0

- #0000

**Comment by monde** [comment]
Thanks @martinstuga . I see `pkce_required` listed in the public API documentation https://developer.okta.com/docs/reference/api/apps/#oauth-credential-object . We'll need to get that surfaced in okta-sdk-golang .

**Comment by monde** [comment]
This will be a quick fix once the property is accessible via okta-sdk-golan

**Comment by martinstuga** [comment]
Thank you @monde ! Do you have a rough idea when this feature might be available for usage? This week? This month? This year?

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-524201

**Comment by faganihajizada** [comment]
Hi 👋🏻 Is there any update on this?
cc @monde

**Comment by monde** [comment]
@faganihajizada I'll looking to have this addressed in the v3.36.0 release I'm currently preparing for later today or tomorrow.
