### ISSUE TITLE
okta_app_signon_policy_rule created without possession constraint

### ISSUE THREAD

**Issue by Mrorya** [okta/terraform-provider-okta#1242]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.1.5
+ provider registry.terraform.io/okta/okta v3.33.0

### Affected Resource(s)

- okta_app_signon_policy_rule

### Terraform Configuration Files

```hcl
resource "okta_app_signon_policy" "policy_test" {
  name        = "Auth Policy"
  description = "Auth Policy Test"
}

resource "okta_app_signon_policy_rule" "policy_require_mfa" {
  policy_id                   = okta_app_signon_policy.policy_test.id
  name                        = "Require MFA"
  access                      = "ALLOW"
  re_authentication_frequency = "PT43800H"
  constraints = [
    jsonencode({
      knowledge = {
        reauthenticateIn = "PT43800H"
        types            = ["password"]
      }
      posession = {
        deviceBound = "REQUIRED"
      }
    })
  ]
}
```

### Expected Behavior

Expected to create an application sign on policy rule with the following configuration:

```
  # okta_app_signon_policy_rule.policy_require_mfa will be created
  + resource "okta_app_signon_policy_rule" "policy_require_mfa" {
      + access                      = "ALLOW"
      + constraints                 = [
          + jsonencode(
                {
                  + knowledge = {
                      + reauthenticateIn = "PT43800H"
                      + types            = [
                          + "password",
                        ]
                    }
                  + posession = {
                      + deviceBound = "REQUIRED"
                    }
                }
            ),
        ]
      + factor_mode                 = "2FA"
      + id                          = (known after apply)
      + inactivity_period           = "PT1H"
      + name                        = "Require MFA"
      + network_connection          = "ANYWHERE"
      + policy_id                   = (known after apply)
      + re_authentication_frequency = "PT43800H"
      + status                      = "ACTIVE"
      + type                        = "ASSURANCE"
    }
```
### Actual Behavior

The application sign on policy rule is created without the deviceBound constraint, and results in an attempted re-creation on every successive apply:

```
  # okta_app_signon_policy_rule.vpn_require_mfa will be updated in-place
  ~ resource "okta_app_signon_policy_rule" "policy_require_mfa" {
      ~ constraints                 = [
          - jsonencode(
                {
                  - knowledge = {
                      - reauthenticateIn = "PT43800H"
                      - types            = [
                          - "password",
                        ]
                    }
                }
            ),
          + jsonencode(
                {
                  + knowledge = {
                      + reauthenticateIn = "PT43800H"
                      + types            = [
                          + "password",
                        ]
                    }
                  + posession = {
                      + deviceBound = "REQUIRED"
                    }
                }
            ),
        ]
        id                          = "rul4b1gxuebNuk0Nl1d7"
        name                        = "Require MFA"
        # (13 unchanged attributes hidden)
    }
```
It shows up without the possession factor in the UI as well:
![image](https://user-images.githubusercontent.com/3143796/183764877-56302a5b-b23b-4017-9e51-d4290b713930.png)

### Steps to Reproduce

1. Create app sign on policy rule noting deviceBound set to REQUIRED
2. Apply plan
3. View misconfigured policy rule in the UI

### Important Factoids

This was tested and validated an issue in both our production Okta (OIE) and our preview instance (OIE)

### References

- #0000

**Comment by monde** [comment]
Thanks for writing up the bug @Mrorya

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-524200

**Comment by Mrorya** [comment]
@monde - This is still an issue, should I open a new github issue with the same description since this was auto-closed?

**Comment by monde** [comment]
[#policy](https://github.com/okta/terraform-provider-okta/labels/policy) related

**Comment by Mrorya** [comment]
This is not resolved and should still be addressed - can this be re-opened @monde?

**Comment by Mrorya** [comment]
Commenting to remove stale label, still an issue

**Comment by Mrorya** [comment]
just noting that this is still an issue to prevent this from becoming stale

**Comment by Mrorya** [comment]
still an issue afaik

**Comment by monde** [comment]
@Mrorya this isn't a bug, it's a typo, see your constraint `posession` should be spelled `possession`. We did add an ACC test to the provider so we can check constraints in tests in the future.

https://github.com/okta/terraform-provider-okta/pull/1788/commits/b0c7d4213d9eeba029938a8d2c40ff2f67ff0cae

**Comment by Mrorya** [comment]
ty!!
