### ISSUE TITLE
List all Email template by provider okta_email_templates

### ISSUE THREAD

**Issue by ppanan33** [okta/terraform-provider-okta#1246]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

currently the provider `okta_email_templates` and API `api/v1/brands/{{brandId}}/templates/email` can only return below 10 email templates, but they are not all Email templates as in `Customizations -> Emails`, there are many templates missing, e.g. Identity Governance templates, Other templates ..., so it's nice to return all of them in the provider and API.
UserActivation
ForgotPassword
ForgotPasswordDenied
PasswordResetByAdmin
ADUserActivation
ADForgotPasswordDenied
ADForgotPassword
LDAPUserActivation
LDAPForgotPassword
LDAPForgotPasswordDenied

### New or Affected Resource(s)

- okta_email_templates

**Comment by monde** [comment]
@ppanan33 please open a support ticket (support.okta.com), and reference this GH issue. The data coming off the `/api/v1/brands/{brandId}/templates/email` endpoint is controlled by the Okta service itself, or perhaps one level higher in the API layer. That is data is not controlled by the SDKs or the Okta TF provider that consume this data downstream from the API. I'd not want to hard code template values into the TF code.

**Comment by ppanan33** [comment]
@monde thanks, I created a Case with Number 01481146.

**Comment by monde** [comment]
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-01481146 (I think)

**Comment by ppanan33** [comment]
Hello @monde , just got updates from the Case 01481146, the [Pagination](https://support.okta.com/help/s/article/Pagination-Overview?language=en_US) is required to list all email templates, e.g. `{{url}}/api/v1/brands/{{brandId}}/templates/email?limit=50`, can terraform provider  `okta_email_templates` align with this change?
