### ISSUE TITLE
priority = 0 is ignored for okta_app_signon_policy_rule resource

### ISSUE THREAD

**Issue by Mrorya** [okta/terraform-provider-okta#1247]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/okta/okta v3.33.0

### Affected Resource(s)

- okta_app_signon_policy_rule

### Terraform Configuration Files

```hcl
resource "okta_app_signon_policy" "policy_test" {
  name        = "Auth Policy"
  description = "Auth Policy Test"
}

resource "okta_app_signon_policy_rule" "rule_test" {
  policy_id = okta_app_signon_policy.policy_test.id
  name      = "Rule A - Priority 0"
  priority  = 0
}

resource "okta_app_signon_policy_rule" "rule_test_2" {
  policy_id = okta_app_signon_policy.policy_test.id
  name      = "Rule B - Priority 1"
  priority  = 1
}
```

### Expected Behavior

The Okta API stores policy rules with a priority starting with 0 (this can be seen by doing a GET on existing policy application rules)

The expectation from the above configuration is that the policy=0 rule will be set with the highest priority, and all other rules will go below until the catch-all rule (set defaulted to priority=99)

### Actual Behavior

The provider treats policy = 0 as a null value, and does not include it in the terraform plan or apply. See below for plan:
```
  # okta_app_signon_policy_rule.rule_test will be created
  + resource "okta_app_signon_policy_rule" "rule_test" {
      + access                      = "ALLOW"
      + factor_mode                 = "2FA"
      + id                          = (known after apply)
      + inactivity_period           = "PT1H"
      + name                        = "Rule A - Priority 0"
      + network_connection          = "ANYWHERE"
      + policy_id                   = "rst4c2lxb9APB6xdK1d7"
      + re_authentication_frequency = "PT2H"
      + status                      = "ACTIVE"
      + type                        = "ASSURANCE"
    }

  # okta_app_signon_policy_rule.rule_test_2 will be created
  + resource "okta_app_signon_policy_rule" "rule_test_2" {
      + access                      = "ALLOW"
      + factor_mode                 = "2FA"
      + id                          = (known after apply)
      + inactivity_period           = "PT1H"
      + name                        = "Rule B - Priority 1"
      + network_connection          = "ANYWHERE"
      + policy_id                   = "rst4c2lxb9APB6xdK1d7"
      + priority                    = 1
      + re_authentication_frequency = "PT2H"
      + status                      = "ACTIVE"
      + type                        = "ASSURANCE"
    }
```

Note the lack of priority = 0 on the resource created with policy=0 - this will result in the rule being created by default at the lowest priority above the catch all rule.
 
### Steps to Reproduce

1. Create an app signon policy rule with the priority set to 0
2. Terraform plan/apply
3. Rule will be created with incorrect priority

### References

- #0000

**Comment by monde** [comment]
@Mrorya I wasn't able to reproduce what you are seeing with the snippet you've provided. That said, what happens when you use a `depends_on` meta argument? This snippet plan/apply/destroys for me without error.

```terraform
resource "okta_app_signon_policy" "policy_test" {
  name        = "Auth Policy"
  description = "Auth Policy Test"
}

resource "okta_app_signon_policy_rule" "rule_test" {
  policy_id = okta_app_signon_policy.policy_test.id
  name      = "Rule A - Priority 0"
  priority  = 0
}

resource "okta_app_signon_policy_rule" "rule_test_2" {
  policy_id = okta_app_signon_policy.policy_test.id
  name      = "Rule B - Priority 1"
  priority  = 1
  depends_on = [okta_app_signon_policy_rule.rule_test]
}
```

**Comment by Mrorya** [comment]
Utilizing `depends_on` in the resource does appear to create with the proper priorities, despite the priority attribute still not showing up in the terraform plan

```
Terraform will perform the following actions:

  # okta_app_signon_policy.policy_test will be created
  + resource "okta_app_signon_policy" "policy_test" {
      + description = "Auth Policy Test"
      + id          = (known after apply)
      + name        = "Auth Policy"
    }

  # okta_app_signon_policy_rule.rule_test will be created
  + resource "okta_app_signon_policy_rule" "rule_test" {
      + access                      = "ALLOW"
      + factor_mode                 = "2FA"
      + id                          = (known after apply)
      + inactivity_period           = "PT1H"
      + name                        = "Rule A - Priority 0"
      + network_connection          = "ANYWHERE"
      + policy_id                   = (known after apply)
      + re_authentication_frequency = "PT2H"
      + status                      = "ACTIVE"
      + type                        = "ASSURANCE"
    }

  # okta_app_signon_policy_rule.rule_test_2 will be created
  + resource "okta_app_signon_policy_rule" "rule_test_2" {
      + access                      = "ALLOW"
      + factor_mode                 = "2FA"
      + id                          = (known after apply)
      + inactivity_period           = "PT1H"
      + name                        = "Rule B - Priority 1"
      + network_connection          = "ANYWHERE"
      + policy_id                   = (known after apply)
      + priority                    = 1
      + re_authentication_frequency = "PT2H"
      + status                      = "ACTIVE"
      + type                        = "ASSURANCE"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

okta_app_signon_policy.policy_test: Creating...
okta_app_signon_policy.policy_test: Creation complete after 1s [id=rst4diqeu19cWwjmp1d7]
okta_app_signon_policy_rule.rule_test: Creating...
okta_app_signon_policy_rule.rule_test: Creation complete after 0s [id=rul4dip1tlQtZav1z1d7]
okta_app_signon_policy_rule.rule_test_2: Creating...
okta_app_signon_policy_rule.rule_test_2: Creation complete after 1s [id=rul4diq1lcK88KZN61d7]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```
![image](https://user-images.githubusercontent.com/3143796/184259542-117e6fb5-c032-4264-84aa-c46ac1ad4146.png)

**Comment by Mrorya** [comment]
It looks like the behavior is inconsistent after going through destroy->create a few times. Sometimes, this does seem to set properly - others, the priorities aren't set properly. I'm not sure if it's some API execution timing thing here

**Comment by monde** [comment]
Reference for others reading along https://developer.okta.com/docs/reference/api/policy/#authentication-policy
"When you create an authentication policy, you automatically also create a default policy rule with the lowest priority of 99. The highest priority that an authentication policy rule can be set to is 0."
The API docs are kind of muddy, it seems like any other policy rule other than type `ACCESS_POLICY` can only have `1` as its highest priority.

**Comment by monde** [comment]
@Mrorya, coincidentally, I'm working on a PR to fix the currency issue on all the resources that have a priority property  as described in https://github.com/okta/terraform-provider-okta/issues/1198. The solution will be using good concurrency protections protections https://github.com/okta/terraform-provider-okta/pull/1248

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-524184

**Comment by Mrorya** [comment]
@monde - This is still an issue, should I open a new github issue with the same description since this was auto-closed?

**Comment by monde** [comment]
@Mrorya I'll open it back up.

**Comment by monde** [comment]
I'll be dedicating a sprint in the near future, for everything that is [#policy](https://github.com/okta/terraform-provider-okta/labels/policy) related

**Comment by Mrorya** [comment]
This is not resolved and should still be addressed - can this be re-opened @monde?

**Comment by Mrorya** [comment]
Commenting to remove stale label, still an issue

**Comment by monde** [comment]
0 value integers are fixed as of https://github.com/okta/terraform-provider-okta/releases/tag/v3.44.0
