### ISSUE TITLE
Add attribute to okta_app_signon_policy to create a 'Catch All' rule that's 'DENY'

### ISSUE THREAD

**Issue by edlott** [okta/terraform-provider-okta#1251]
okta_app_signon_policy creates a default 'Catch All' rule.  Once such a rule is created, it's difficult to change anything about it with terraform since the codebase implementing okta_app_signon_policy_rule is designed to work with mutable rules vs. all the restrictions associated with the 'Catch All' rule.

If you could add an attribute to okta_app_signon_policy (catchAll = "DENY"), then okta_app_signon_policy could create policies with 'Catch All' being a noop - the mutable rules could be used for everything else.  As it stands, I have to go and manually configure the 'Catch All' rules to 'DENY' while using terraform scripts to configure all the other rules.

**Comment by monde** [comment]
@edlott I like this idea.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-524183

**Comment by lucascantor** [comment]
I strongly agree with this, given Okta's official instruction when enforcing Device Trust is to do exactly this.

Currently, we're forced to implement a regular DENY rule at the lowest priority above the catch-all rule, since importing the catch-all rule into Terraform state requires painful bureaucracy and toil in our org.

**Comment by edlott** [comment]
@lucascantor - that's my exact work-around.

**Comment by mnovitsk** [comment]
@monde I recently upgraded provider version to 3.34.0 and ran into similar issues managing the default Catch-all rule. The primary reason behind upgrading the provider version was to be able to explicitly create and associate app_signon_policy resources to applications when the app is created. This works, but it seems that the catch-all rule is not able to properly be managed by Terraform after importing the resource.

The Okta Terraform Provider docs (https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_signon_policy_rule and https://registry.terraform.io/providers/okta/okta/3.34.0/docs/resources/app_signon_policy_rule) both state that you can manage the catch-all rule by manually importing the rule, but the provider throws errors when trying to set the rule to "DENY" after importing it.

It wouldn't even attempt to apply if the name, priority, or constraints had been altered. Setting all of the values to be the same as the default settings (determined via Console and API calls), except for changing access from "ALLOW" to "DENY", would still result in an error being thrown. 

Being able to truly manage the catch-all rule would be useful. Being able to automatically set it to deny by default would be even better.

**Comment by monde** [comment]
not stale

**Comment by lucascantor** [comment]
not stale

**Comment by lucascantor** [comment]
not stale

**Comment by njtrettel** [comment]
also worth mentioning that the docs imply that you could import into terraform state and then modify the `access`, but as mentioned above that gives an error due to modifying constraints.

> A default or Catch-all Rule sign-on policy rule can be imported and managed as a custom rule. The only difference is that these fields are immutable and can not be managed: `network_connection`, `network_excludes`, `network_includes`, `platform_include`, `custom_expression`, `device_is_registered`, `device_is_managed`, `users_excluded`, `users_included`, `groups_excluded`, `groups_included`, `user_types_excluded` and `user_types_included`.

that is, `access` is not in that list

**Comment by lucascantor** [comment]
Not stale

**Comment by adantop** [comment]
Hey @monde do you have an ETA for the addition of this feature?

**Comment by teads-sylvain** [comment]
Interested in this feature too

**Comment by asmlalpaca** [comment]
waiting for this

**Comment by BartBartBartBartBart** [comment]
Any updates? 
It reached 17 votes.

**Comment by ianwinsemius** [comment]
This would be a nice feature to have, we have resorted to simply ignoring the catchall and creating our own that serves the same "any request" purpose. 

```terraform
implicit_deny = {
      name       = "Implicit Deny"
      priority   = 98
      access     = "deny"
      managed    = false
      registered = false
    }
```

**Comment by j-zehnder** [comment]
Any updates on this issue?

**Comment by scothomp** [comment]
Any updates on this issue?

**Comment by duytiennguyen-okta** [comment]
@lucascantor @edlott I am currently working on this. My question is given your current pipeline, is it better to have a catch_all attribute in `okta_app_signon_policy` that will make the default rule = DENY or make a datasource to help importing the catch all rule `okta_app_signon_policy_rule` easier?

**Comment by lucascantor** [comment]
@duytiennguyen-okta thank you.

For our org, the former option is definitely strongly preferred.

(a catch_all attribute in `okta_app_signon_policy` that will make the default rule = DENY)

**Comment by duytiennguyen-okta** [comment]
@lucascantor is it that hard to import the catchAll policy rule or is there something else? Can you elaborate?

**Comment by lucascantor** [comment]
It's hard to import anything in general in a lot of Terraform pipelines, but more importantly, no Terraform resource type should ever _require_ users both be able to and remember to import something in order to function properly.

There should be a standard attribute for configuring this, just like everything else about this resource type, and Terraform resources in general.

**Comment by MScottBlake** [comment]
The Terraform description should be idempotent. If you are defining a new okta_app_signon_policy, you should be able to define all aspects of it. Right now, you cannot define a catchAll rule, so the proposed solution is to onclude the options within `okta_app_signon_policy`. You could instead implement another resource, but doing it as a data source does not conform to Terraform standards.
Going back to the example of a new policy, you have no way of defining the catchAll rule and you would need to wait until after the policy is created before even attempting to read it, forcing a definition to be run twice to achieve results. Using a data source also prevents modification of the rule, so it still doesn't really address the underlying problems.

**Comment by duytiennguyen-okta** [comment]
<img width="948" alt="Screenshot 2024-12-11 at 3 54 08 PM" src="https://github.com/user-attachments/assets/d5aaca51-27b6-4e99-ac98-d4cdc07d2352" />
@MScottBlake @lucascantor @edlott just to confirm, after the policy is create with catchAll = "DENY", this is what you would expect from the catchall rule?

**Comment by MScottBlake** [comment]
I would expect that `Access` is denied as pictured, yes.

However, if there is not going to be a way to configure the other rule settings, this is still only partially addressed. The crux of the problem is that the catch-all rule is not modifiable at all via terraform. As stated above, this rule could be tied to the policy configuration, but that is more complex than simply allowing the access to be denied. This is a great first step though.

**Comment by lucascantor** [comment]
@MScottBlake this single setting (Access is `Denied` or `Allowed after successful authentication`) is the only setting that's modifiable in the catch-all rule.

It's not easy to see in @duytiennguyen-okta's screenshot, but all other settings are always greyed out for catch-all rules. That's what makes them catch-all rules.

**Comment by MScottBlake** [comment]
That's a great point, however, I was referring to the options for an allow rule. Apologies for not being very clear about that.

**Comment by lucascantor** [comment]
Thanks, and yes I agree - the new argument being proposed here should be able to be used to configure the catch-all rule to _either_ DENY _or_ ALLOW.
