### ISSUE TITLE
role_type of okta_role_subscription need to be updated to latest

### ISSUE THREAD

**Issue by ppanan33** [okta/terraform-provider-okta#1257]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_role_subscription

The [role_type](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/role_subscription) in okta_role_subscription is not the same as what they are in API [docs](https://developer.okta.com/docs/reference/api/admin-notifications/#role-types), for example, `GROUP_MEMBERSHIP_ADMIN ` is missing, `API_ACCESS_MANAGEMENT_ADMIN` is outdated and so on. which may cause issue when using these wrong/missing type..

**Comment by monde** [comment]
Thanks @ppanan33 , we'll have to get that updated.

Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-526325
