### ISSUE TITLE
Background image and favicon is not getting applied for okta theme

### ISSUE THREAD

**Issue by Navya-R-Rao** [okta/terraform-provider-okta#1258]
I have been trying to implement branding on Okta tenants,
And I am using the below code for implementing it. I have imported the brandid and themeid from the state file.
I am not getting any error when applying the changes but after applying, the background image and the favicon is not getting updated or applied.Everything else is applied.I have given the right path but seems like it's not taking it.

@monde edit, formatting
```terraform
resource "okta_theme" "okta_brand_theme" {
  brand_id                               = okta_brand.okta_branding_privacy_policy.id
  logo                                   = "/logo.png"
  favicon                                = "/favicon.png"
  background_image                       = "/image.png"
  primary_color_hex                      = "#00338d"
  secondary_color_hex                    = "#dedede"
  sign_in_page_touch_point_variant       = "BACKGROUND_SECONDARY_COLOR"
  end_user_dashboard_touch_point_variant = "WHITE_LOGO_BACKGROUND"
  error_page_touch_point_variant         = "BACKGROUND_SECONDARY_COLOR"
  email_template_touch_point_variant     = "FULL_THEME"
}
```

Can I get help sorting this out please

**Comment by monde** [comment]
Hi @Navya-R-Rao seems like there is a bug with logo, background image, and favicon not being uploaded/updated/deleted.  I don't see the corresponding endpoints being called from the provider for images when I run my apply with `TF_LOG=1`. I can change colors, etc.
```
# API docs at https://developer.okta.com/docs/reference/api/brands/#themes-operations
POST /api/v1/brands/${brandId}/themes/${themeId}/logo
POST /api/v1/brands/${brandId}/themes/${themeId}/favicon
POST /api/v1/brands/${brandId}/themes/${themeId}/background-image
```
This is the TF I was experimenting with:

```terraform
terraform {
  required_providers {
    okta = {
      source = "okta/okta"
    }
  }
}

data "okta_brands" "test" {
}

data "okta_brand" "test" {
  brand_id = tolist(data.okta_brands.test.brands)[0].id
}

data "okta_themes" "test" {
    brand_id = data.okta_brand.test.id
}

data "okta_theme" "test" {
    brand_id = data.okta_brand.test.id
    theme_id = tolist(data.okta_themes.test.themes)[0].id
}

resource "okta_theme" "test" {
  brand_id = data.okta_brand.test.id
  theme_id = tolist(data.okta_themes.test.themes)[0].id
  logo = "/logo.png"
  favicon = "/favicon.png"
  background_image = "/image.png"
  primary_color_hex = "#ff0000"
  secondary_color_hex = "#00ff00"
  sign_in_page_touch_point_variant = "BACKGROUND_SECONDARY_COLOR"
  end_user_dashboard_touch_point_variant = "WHITE_LOGO_BACKGROUND"
  error_page_touch_point_variant = "BACKGROUND_SECONDARY_COLOR"
  email_template_touch_point_variant = "FULL_THEME"
}

output "brand_id" {
  value = data.okta_brand.test.brand_id
}

output "theme_id" {
  value = okta_theme.test.id
}
```

**Comment by monde** [comment]
@Navya-R-Rao , missed this bit in your TF example:
```
  logo = "/logo.png"
  favicon = "/favicon.png"
  background_image = "/image.png"
```
When I changed the path to not be absolute  like the following, the TF worked for me to update theme.
```
  logo = "logo.png"
  favicon = "favicon.png"
  background_image = "image.png"
```
I'll still leave this a bug as the provider should error if it can't open the image files.

**Comment by monde** [comment]
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-526846

**Comment by Navya-R-Rao** [comment]
Thank you for the solution. It is working now.

**Comment by Navya-R-Rao** [comment]
I tried this solution and it's working fine.
But every time when I do a change and push the code , the primary colour and the secondary colour get's updated to null.
Is there a possibility to avoid that change?

**Comment by monde** [comment]
@Navya-R-Rao are you variants matching the behavior described in the API documentation? https://developer.okta.com/docs/reference/api/brands/#variants-for-the-okta-sign-in-page

**Comment by monde** [comment]
Following up on my previous question, is everything OK for you now?
