### ISSUE TITLE
Resource for managing factors on Okta Classic?

### ISSUE THREAD

**Issue by pro4tlzz** [okta/terraform-provider-okta#1260]
Hi,

With some help I found this resource which is used on OIE to enable authenticators https://registry.terraform.io/providers/okta/okta/latest/docs/resources/authenticator

However I am struggling to find the OIE equivalent resource to manage Multifactor Types eg enable OTP disable Okta Verify etc

Am I being stupid or is there no resource to manage this on Okta Classic?

Thanks

**Comment by monde** [comment]
@pro4tlzz I'd open a support ticket https://support.okta.com/help/s/?language=en_US to get help with setting up a configuration. Sounds like you are trying to get your policies set up https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_mfa ? A support engineer would be better help than in a github issue. I'm going to close this issue.

**Comment by pro4tlzz** [comment]
> 

Hi @monde I have my mfa policies setup correctly.

What i can't see within your terraform resources is a way to manage (enable, disable) mfa authenticators.

Thats why I am asking if there is a resource to manage mfa authenticators, not the policies or rules themselves

**Comment by monde** [comment]
@pro4tlzz please open a support ticket to get the help you looking for. It will be specific and dedicated to your situation.
