### ISSUE TITLE
client_secret is missing from okta_app_oauth data source

### ISSUE THREAD

**Issue by rickardp** [okta/terraform-provider-okta#1279]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$terraform -v
Terraform v1.2.2
on linux_arm64
```

### Affected Resource(s)

- `okta_app_oauth` data source

### Expected Behavior

When defining an OAuth app, I can receive the client secret trough the `client_secret` attribute.
When referencing an OAuth app defined elsewhere, I can do the same by using the data source with the same name.

### Actual Behavior

The `client_secret` attribute is only available on the resource, not the data source, hence it is difficult to reuse an Okta OAuth app across different IaC projects.

I can get the client secret from the UI and it looks like there is an API for it, so it should be possible to implement.

I am not sure if this is a bug or a feature request, but it is actually the first time I've come across a data source in terraform that does not expose the same set of features as the resource, so I believe this goes against the intent of this data source.

**Comment by rickardp** [comment]
I added a draft PR that adds this fields and make my Terraform IaC work the way I expected it to w.r.t. client_secret.

**Comment by monde** [comment]
@rickardp thanks for the report and the PR illustrating desired behavior.

**Comment by rickardp** [comment]
Any thought on how to get this fixed? I'm happy to help out, continuing on that PR with some guidance on how to best proceed

**Comment by monde** [comment]
@dkulchinsky fixed it in #1285 . This will go out in the next release. I'm going to try and get one out tomorrow.

**Comment by rickardp** [comment]
Nice! Just a heads up, I tried this and got an empty client secret back. I had to specifically request the secrets to get it to work in #1280, though I must admit that this is my first shot at calling the Okta API so I might miss something obvious.

A simple curl to `/api/v1/apps/(appid)` does not reveal a client_secret in credentials/oauthClient, I see only the following keys: "autoKeyRotation", "client_id", "token_endpoint_auth_method"

**Comment by dkulchinsky** [comment]
> Nice! Just a heads up, I tried this and got an empty client secret back. I had to specifically request the secrets to get it to work in #1280, though I must admit that this is my first shot at calling the Okta API so I might miss something obvious.
> 
> A simple curl to `/api/v1/apps/(appid)` does not reveal a client_secret in credentials/oauthClient, I see only the following keys: "autoKeyRotation", "client_id", "token_endpoint_auth_method"

That's a good point @rickardp! perhaps my PR is somewhat naive and `client_secret` is only for setting a "custom" secret when creating an App, however to retrieve it might need to use the method in your PR.

**Comment by monde** [comment]
I'll revert #1285 and put some bumpers around it before doing a release.

**Comment by monde** [comment]
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-531872

**Comment by monde** [comment]
I'm looking to knock this one down this week.

**Comment by rickardp** [comment]
Nice! Will there be a release build out of this, so I can kill off my locally built version?

**Comment by monde** [comment]
@rickardp It's been picked up as v3.36.0 in the registry
- https://registry.terraform.io/providers/okta/okta/latest/docs
- https://github.com/okta/terraform-provider-okta/releases/tag/v3.36.0
