### ISSUE TITLE
okta_app_oauth_redirect_uri is not correctly updating w.r.t changes

### ISSUE THREAD

**Issue by rickardp** [okta/terraform-provider-okta#1283]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$terraform -v
Terraform v1.2.2
on linux_arm64
```

### Affected Resource(s)

- okta_app_oauth_redirect_uri

### Terraform Configuration Files

```hcl
resource "okta_app_oauth_redirect_uri" "example" {
    app_id = var.app_id
    uri = "https://${var.oauth2_host_name}/oauth2/callback"
}

```

### Expected Behavior

When changing the URL in the .tf, the reply URL in Okta is changed.

### Actual Behavior

Reply URL is correctly created. When it is changed, it is not updated to reflect the changes. "terraform plan" does not show any changes.

### Steps to Reproduce

1. Create file as per above
2. `terraform apply`
3. Verify reply URL created
4. Change "uri" property to another value
5. `terraform plan`
6. Shows no changes
7. `terraform apply` 
8. Observe that the old value is still present in Okta

**Comment by rickardp** [comment]
Another issue is that if there are existing (conflicting) reply URLs, the Okta API will yield a 4xx error message saying duplicate reply URLs. The correct behaviour IMHO would be for Terraform to recognize this as a resource outside of its state and suggest to import it. I wasn't able to verify if "terraform import" solved the issue since I didn't immediately figure out the resource ID to specify.

**Comment by monde** [comment]
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-531874

**Comment by monde** [comment]
@rickardp we'll have to knock this bug down. Your description is very helpful.

**Comment by rickardp** [comment]
Any update on the issue?

**Comment by SimonVHB** [comment]
Hi @monde, it looks like this is still an existing issue.
Do you have an update on it?
