### ISSUE TITLE
okta_idp_oidc does not support DYNAMIC issuer_mode

### ISSUE THREAD

**Issue by AndreyZhilinskyCoherent** [okta/terraform-provider-okta#1288]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

okta_idp_oidc.**issuer_mode** supports "ORG_URL" or "CUSTOM_URL", but does not support "DYNAMIC" that I can set manually
documentation: https://registry.terraform.io/providers/okta/okta/latest/docs/resources/idp_oidc#issuer_mode

When I try to use "DYNAMIC":
Error: expected value to be one of 'ORG_URL', 'CUSTOM_URL', got 'DYNAMIC'

### New or Affected Resource(s)

- okta_idp_oidc 

### Version

okta v3.35.0

**Comment by monde** [comment]
@AndreyZhilinskyCoherent this is definately a bug [idp](https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_idp_oidc.go#L60-L66)

**Comment by monde** [comment]
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-531880

**Comment by petercdl** [comment]
Hi, the issue_mode in okta_idp_social was not seen updated, it does not support dynamic.
