### ISSUE TITLE
okta_group_role - unexpected forceNew when adding to target_group_list

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1290]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.0.11
on darwin_arm64
+ provider registry.terraform.io/okta/okta v3.31.0

Your version of Terraform is out of date! The latest version
is 1.2.8. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

- okta_group_role

### Terraform Configuration Files

```hcl
resource "okta_group_role" "example" {
  group_id  = var.example_group
  role_type = "GROUP_MEMBERSHIP_ADMIN"
  target_group_list = [
    var.blah,
    var.blah123,
 }
```

### Expected Behavior

when adding new groups to `target_group_list` the resource should not be replaced

### Actual Behavior
we're seeing new groups being added to `target_group_list` causing forced replacement e.g 
```hcl
# module.MODULENAME.okta_group_role.EXAMPLE must be replaced
-/+ resource "okta_group_role" "EXAMPLE" {
      ~ id                    = "REDACTED ID" -> (known after apply)
      ~ target_group_list     = [
          - "REDACTED ID",
          - "REDACTED ID",
          ] -> (known after apply) # forces replacement
          # (3 unchanged attributes hidden)
      }
```
I believe its due to something funky happening with [these pieces of code](https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_group_role.go#L24-L53) 

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by monde** [comment]
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-531883

**Comment by monde** [comment]
Thanks for running down where the code flaw is at @exitcode0 . Hopefully it is an easy fix.
