### ISSUE TITLE
Okta saml "unknown error" due to subject_name_id_template

### ISSUE THREAD

**Issue by ghost** [okta/terraform-provider-okta#1291]
### Terraform Version
v1.2.7
### Affected Resource(s)
okta terraform provider 3.35

### Terraform Configuration Files

```hcl
resource "okta_app_saml" "app" {
  label                    = "label"
  sso_url                  = local.endpoint_url
  recipient                = local.endpoint_url
  destination              = local.endpoint_url
  audience                 = local.entity_id
  subject_name_id_template = "$${user.email}"
  subject_name_id_format   = "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
  response_signed          = true
  assertion_signed         = true
  signature_algorithm      = "RSA_SHA256"
  digest_algorithm         = "SHA256"
  honor_force_authn        = true
  authn_context_class_ref  = "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"

  implicit_assignment = true
}
```

With this code, following the syntax of the documentation the app creation worked well at first. However, on the 06/09/22 this changed and we received an "unknown error":

```
╷
│ Error: failed to create SAML application: the API returned an unknown error
│
│   with okta_app_saml.co2ai,
│   on main.tf line 1, in resource "okta_app_saml" "co2ai":
│    1: resource "okta_app_saml" "co2ai" {
│
```

The terraform debug output revealed a 403 response. 
We managed to resolve the error by escaping the name format "\\$\\$\\{user.email\\}".

### Expected Behavior

- Better error message on 403 
- Updated documentation / "$${user.email}" to continue to work

**Comment by monde** [comment]
Okta  internal reference https://oktainc.atlassian.net/browse/OKTA-531888

**Comment by monde** [comment]
Thanks @jheyder213 for describing the bug and showing a work around. Sounds like we changed some preparation on the request that is posted to the API.

**Comment by ghost** [comment]
Great, please let us know when the bug is fixed. I noticed that our mappers do not work correctly anymore, e.g. assigning a username "\$\$\{user.email\}" instead of the Okta username with the workaround.

**Comment by ghost** [comment]
I am attempting to move from using API key for authentication to OAUTH and my resources are throwing the error:
`Error: failed to get app's SAML metadata: the API returned an unknown error`
Which is believe is related to this same conversation
While using the API key for authentication, everything works file, but once moving to OAUTH, it starts to fail with this error on my SAML app resources

I attempted to escaping workaround posted in this thread but terraform doesn't take the escaped [$, { ,  }] characters 

"$${user.userName}" - WORKS with API token but errors while using OAUTH
"\$\$\{user.userName\}" - Invalid escape sequence. The symbols are not a valid escape sequence selector.
