### ISSUE TITLE
Okta Social IDP with Type Github

### ISSUE THREAD

**Issue by venkatakanupuru** [okta/terraform-provider-okta#1293]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

- okta_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

Hi Team,

For a Social IDP, resource "okta_idp_social" the type of Social IdP can be "FACEBOOK", "LINKEDIN", "MICROSOFT", "GOOGLE" or "APPLE". I have another type GITHUB. I am able to configure it manually through Admin UI and also able to import the resource to Terraform script. However when I run a plan or apply, it wont accept the Type as GITHUB. 
And receiving a error :
**Error: expected value to be one of 'FACEBOOK', 'LINKEDIN', 'MICROSOFT', 'GOOGLE', 'APPLE', got 'GITHUB'**

Steps for configuring manually IDP 
OKTA Admin UI >> Security >> Identity Providers 

Type : GITHUB
Account mode: JIT

Please Help.

Thank you
Venkata

**Comment by monde** [comment]
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-531895

**Comment by monde** [comment]
Thanks @venkatakanupuru . I should be able to address this quickly in the next release.
