### ISSUE TITLE
Plugin crash when importing okta_policy_signon

### ISSUE THREAD

**Issue by cabtech** [okta/terraform-provider-okta#1294]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
1.2.9

### Okta Provider Version
3.35

### Affected Resource(s)
okta_policy_signon

### Terraform Configuration Files
```hcl
resource "okta_policy_signon" "pswdAndFido2" {
}
```

### Debug Output
No was no extra output from enabling TF_LOG and TF_LOG_PATH

### Panic Output
https://gist.github.com/cabtech/a56a58f1db898b3d15f340d13382b1ff

### Expected Behavior
Terraform should have imported the signon policy

### Actual Behavior
Plugin crashed

### Steps to Reproduce
`terraform import okta_policy_signon.pswdAndFido2 ${POLICY_ID}`
The policy exists and the reference is valid.

### References

- #0000

**Comment by monde** [comment]
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-531899

**Comment by monde** [comment]
Thanks @cabtech I'll try to deal with this panic in the next release.
