### ISSUE TITLE
Documentation doesn't show how to make a SAML app a profile mastering app.

### ISSUE THREAD

**Issue by amosdavis** [okta/terraform-provider-okta#1295]
I want to use this resource to map an attribute from Example App -> Okta user. I get the error " Push status is allowed for profile mastering enabled apps only."  This is not an IdP, it is a connected SAML app that needs to push a couple attributes to Okta.  How do I turn this app into a profile mastering enabled app?  

@monde edit, formatting:
```terraform
resource "okta_profile_mapping" "example" {
  source_id          = okta_app_saml.example.id 
  target_id          = "${data.okta_user_profile_mapping_source.example.name}"  
  always_apply = true
  mappings {
    id          = okta_user_schema_property.custom["b"].index
    expression  = "user.${okta_app_user_schema_property.example["j"].index}"
    push_status = "PUSH"
  }
}
```

**Comment by amosdavis** [comment]
Also, source_id and target_id are interchangeable, and the only thing apparently changing the direction of the mapping is the push_status variable.

**Comment by monde** [comment]
@amosdavis can you open a support ticket on this? A support engineer will help you get your config set up http://support.okta.com/ . I'll leave this open if they find it is a bug, but for now it seems like a support question to me.
