### ISSUE TITLE
Add support for group/app whitelist for administrative roles

### ISSUE THREAD

**Issue by tgoodsell-tempus** [okta/terraform-provider-okta#13]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The administrative roles "Helpdesk Admin" and "Group Admin" support the ability to define a whitelist of groups whose members they're allowed to exercise those functions against.

The "Application Admin" roles also supports a whitelist of applications which functions the same as described above.

My request thusly is either an addition to the admin roles; or if deemed more appropriate, the creation of a new resource which can provide ability to pass these optional whitelists.

This is a bit complicated by the fact the API references the ID of the admin role assignment; so we'd have to ensure that we've got a way to reference what "role" we're trying to whitelist. This may lend itself better to a design pattern of "HELPDESK_ADMIN_WHITELIST", "GROUP_ADMIN_WHITELIST", and "APP_ADMIN_WHITELIST" optional vars in the current resource; where when populated we look for the ID based on what whitelist is being used.

### New or Affected Resource(s)

* okta_group_roles
** okta_group_roles_group_whitelist <if we go new resource route>
** okta_group_roles_app_whitelist <if we go new resource route>

### Potential Terraform Configuration

If we go extend current resource route
```hcl
resource "okta_group_roles" "example" {
  group_id    = "<group id>"
  admin_roles = ["GROUP_ADMIN"]
  group_admin_whitelist = ["<group id>","<group id>"]
}

```

### References

https://developer.okta.com/docs/reference/api/roles/#add-a-group-target-to-a-group-administrator-role-given-to-a-user

https://developer.okta.com/docs/reference/api/roles/#add-a-group-target-to-a-group-administrator-role-given-to-a-user
--->

* #0000

**Comment by rtlong** [comment]
I'd be happy to implement this.

I can see the complication, as you mentioned @tgoodsell-tempus.

I feel like it may be best solved by normalizing the `okta_group_roles` resource to be singular and then represent the role-group target assignments using a new resource:

```hcl
resource "okta_group_role" "example" {
  group_id  = "<group id>"
  role_type = "GROUP_ADMIN"
}

resource "okta_group_role_target_group" "example" {
  role_id  = okta_group_role.example.id
  group_id = "<target group id>"
}

``` 

[Hashicorp recommends that resources should represent single API object.](https://www.terraform.io/docs/extend/hashicorp-provider-design-principles.html#resources-should-represent-a-single-api-object-mapping-event) As the Okta API represents the role assignment and target assignments as separate resources, the provider should as well. 

Before I put the time in on implementing that approach, I'd love to hear opinions on this change, as it would deprecate the existing `okta_group_roles` resource.

**Comment by tgoodsell-tempus** [comment]
I agree with your stance on refactoring the okta_group_roles to being a singular instance of the admin assignment operation. I think the Hashicorp recommendation + the Okta API architecture would lend this to being the better design choice for the resource. 

There's the other side of this, which is the current resource more closely mimics the experience of configuring this in the Okta UI versus what it would look like post refactor. I personally don't hold that in high regard though to sway my thinking.

**Comment by netflash** [comment]
Hi there,

I was wondering if there are any plans to implement this soon?

Cheers!

**Comment by awagneratzendesk** [comment]
Just a note of interest on this - we would love to be able to control the APPLICATION_ADMIN assignment for all of our TF controlled applications through a mechanism like this.

**Comment by fatbasstard** [comment]
To prevent the issue from closing itself: we also need this feature

**Comment by jlaundry** [comment]
Commenting to prevent the issue from closing itself

**Comment by jlaundry** [comment]
Can we please reopen this?

**Comment by rtlong** [comment]
@jlaundry  I was just checking in on this to see if it still needs doing; I see you said over in #74 that you were working on this, back in July. Are you still indeed actively working on it? I definitely still have the need for this feature, as do a number of other users it seems. I have some time to tackle this finally and I'll get started on it if you're not actively working on it. I'd love to see and work off what you have, if you've made any progress.

**Comment by jlaundry** [comment]
Hi @rtlong, I ended up submitting PR #154 but haven't heard anything back.

If you could please review, it was my first Terraform extension, so undoubtedly I did something wrong 🙂

**Comment by noinarisak** [comment]
Reopening, still reviewing @jlaundry PR #154.
