### ISSUE TITLE
okta/okta provider v 3.35.0 "archive has incorrect checksum zh:"

### ISSUE THREAD

**Issue by mashokaspire123** [okta/terraform-provider-okta#1306]
While running terraform Init for the okta/okta provider , receiving following error
>>>>>>>>>>>>>>>>>>>>>>
Initializing the backend...

Initializing provider plugins...
- Finding okta/okta versions matching "~> 3.35"...
- Finding latest version of hashicorp/local...
- Installing okta/okta v3.35.0...
- Installing hashicorp/local v2.2.3...
- Installed hashicorp/local v2.2.3 (signed by HashiCorp)
╷
│ Error: Failed to install provider
│ 
│ Error while installing okta/okta v3.35.0: archive has incorrect checksum zh:baa6ab9148c26847828664f0f3e9983441da3ff97c18fefb88c78de08a4b2ca8 (expected
│ zh:0106eac3bd692f15e98cef37242b983951b4d3ceff7f3fc941b68204db88c2d5)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Checksum doesnt match while downloading, how to resolve this issue, will your team able to fix this or is there any alternative?

**Comment by monde** [comment]
@mashokaspire123 I'm not able to reproduce what you are experiencing.

I'm seeing`0106eac3bd692f15e98cef37242b983951b4d3ceff7f3fc941b68204db88c2d5` in my .terraform.lock.hcl

```
$ grep 0106eac3bd692f15e98cef37242b983951b4d3ceff7f3fc941b68204db88c2d5 .terraform.lock.hcl
    "zh:0106eac3bd692f15e98cef37242b983951b4d3ceff7f3fc941b68204db88c2d5",
```

Do you have something overriding your provider installation in `$HOME/.terraformrc` ? https://www.terraform.io/cli/config/config-file

```
tf init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of okta/okta...
- Installing okta/okta v3.35.0...
- Installed okta/okta v3.35.0 (signed by a HashiCorp partner, key ID 6438EEBF187672EE)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

**Comment by mashokaspire123** [comment]
Thanks for your response. I don't recollect overriding the provider installation, i tried reinstalling the terraform binary both as homebrew and binary, still running into issue - will debug further .  Since you have stated that you are able to run successfully , i think this is my local setup issue , will update here once i resolve it

**Comment by monde** [comment]
@mashokaspire123 open this back up if it is still an issue and I can work on it more with you. Email mike.mondragon@okta.com and we can do a live pairing over zoom.
