### ISSUE TITLE
Terraform plan fails if Okta inline hook has been deleted outside of terraform

### ISSUE THREAD

**Issue by bahatelos** [okta/terraform-provider-okta#131]
Hello!

*Symptoms*:
terraform plan fails if an Okta inline hook has been deleted in Okta outside terraform.

*Steps to replicate*:
use terraform to create an inline hook (in this case it was a SAML inline hook).
Go to Okta and delete the hook manually.
Re-run terraform

*Expected behaviour*:
Terraform does not find the key, plans to create it and creates it during the apply phase

*Actual behaviour*:

`aws_api_gateway_base_path_mapping.authorisation_deployment-base-path-mapping: Refreshing state... (ID: blahblahblah)`

`Error: Error refreshing state: 1 error(s) occurred:`

`* okta_inline_hook.authorisation_saml-inline-hook: 1 error(s) occurred:`

`* okta_inline_hook.authorisation_saml-inline-hook: okta_inline_hook.authorisation_saml-inline-hook: The API returned an error: Not found: Resource not found: xxxxxxxxxxxxx (InlineHook)`

I had a quick look at the code and it seems that the okta provider creates the hook and stores the hook's id in the state file.
When it does the state refresh, it tries to retrieve the inline hook based on the id.
It checks for a 404 response but things still seem to go wrong.

I *think* the code is here:
https://github.com/terraform-providers/terraform-provider-okta/blob/master/okta/resource_okta_inline_hooks.go#L142

This is from the Okta API doc, saying the error above should be a 404:
https://developer.okta.com/docs/reference/error-codes/#E0000007

**Comment by bogdanprodan-okta** [comment]
Hi @bahatelos! This will be fixed in the upcoming v.3.8.0 version.

**Comment by bahatelos** [comment]
Smashing, thank you!
