### ISSUE TITLE
okta_app_signon_policy fails with Error: failed to create authentication policy: the API returned an error: The request was not valid: Invalid policy type specified.

### ISSUE THREAD

**Issue by msweaver** [okta/terraform-provider-okta#1311]
Hi. I'm trying to create an okta_app_signon_policy using okta/okta 3.36.0 and I'm facing the following issue: Error: failed to create authentication policy: the API returned an error: The request was not valid: Invalid policy type specified.

You can reproduce this really easily with just a 4 liner:

    resource "okta_app_signon_policy" "my_policy" {
      name        = "my_policy_name"
      description = "My policy description"
    }

According to the docs, type isn't even an input on this resource, which is really confusing: https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_signon_policy

It also doesn't matter if I add it to an app or not, nor if I add rules to the policy or not. Appreciate any insight into why this isn't working.

**Comment by monde** [comment]
@msweaver Can you run your terraform command with TF_LOG=1 ? Tell me if your error looks like what is posted below. I'd like to see the debug output of the the API call that is having the error `POST /api/v1/policies` and the error response itself if yours are different. Scrub out any private data.

Something like:
```
POST /api/v1/policies HTTP/1.1
{
 "description": "The app signon policy used by our test app.",
 "name": "Test_App_5279157329804366832",
 "type": "ACCESS_POLICY"
}

HTTP/2.0 400 Bad Request
{
 "errorCode": "E0000002",
 "errorSummary": "The request was not valid: Invalid policy type specified.",
 "errorLink": "E0000002",
 "errorId": "oaeGvDGO94rRNKzMxss7PMgiw",
 "errorCauses": []
}
```

Also, is your org a classic org or an OIE org? When I run the test for this resource against a classic org I get the same error:

https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_app_signon_policy_test.go

Looking at the API docs: https://developer.okta.com/docs/reference/api/policy/#policy-object for the `type` parameter:
"Note: The following policy types are available only with the Identity Engine: ACCESS_POLICY or PROFILE_ENROLLMENT."

```
 ± TF_ACC=1 go test -tags unit -mod=readonly -test.v -run ^TestAccOktaAppSignOnPolicy_crud$ ./okta 2>&1
=== RUN   TestAccOktaAppSignOnPolicy_crud
    resource_okta_app_signon_policy_test.go:19: Step 1/3 error: Error running apply: exit status 1

        Error: failed to create authentication policy: the API returned an error: The request was not valid: Invalid policy type specified.

          with okta_app_signon_policy.test,
          on terraform_plugin_test.tf line 1, in resource "okta_app_signon_policy" "test":
           1: resource "okta_app_signon_policy" "test" {

--- FAIL: TestAccOktaAppSignOnPolicy_crud (1.19s)
FAIL
FAIL    github.com/okta/terraform-provider-okta/okta    1.442s
FAIL
```

It's on my TODO list to give warnings and/or errors, and update the documentation to state on the resources which are valid for both Classic and OIE, or just Classic, or just OIE.

**Comment by monde** [comment]
Internal Okta reference: https://oktainc.atlassian.net/browse/OKTA-534212

**Comment by msweaver** [comment]
Thanks for replying! I'll run through these ideas and report back.

**Comment by msweaver** [comment]
yo @monde . Thanks again for helping with this. Here's the request/response. It happens basically as you showed:

      ---[ REQUEST ]---------------------------------------
      POST /api/v1/policies HTTP/1.1
      Host: <redacted>.oktapreview.com
      User-Agent: okta-sdk-golang/2.15.0-beta.2 golang/go1.17.13 windows/amd64 okta-terraform/3.36.0
      Content-Length: 87
      Accept: application/json
      Authorization: SSWS 00c-8mDJ7IBU3hI_uG5ZiGTnCTdNcy40wBMS8Q7Q3T
      Content-Type: application/json
      Accept-Encoding: gzip
      
      {
       "description": "My policy description",
       "name": "my_policy_name",
       "type": "ACCESS_POLICY"
      }
      
      -----------------------------------------------------: timestamp=2022-09-22T10:40:06.645-0400
      2022-09-22T10:40:06.761-0400 [INFO]  provider.terraform-provider-okta_v3.36.0.exe: 2022/09/22 10:40:06 [DEBUG] Okta API Response Details:
      ---[ RESPONSE ]--------------------------------------
      HTTP/2.0 400 Bad Request
      Connection: close
      Cache-Control: no-cache, no-store
      Content-Security-Policy: <I'm thinking this is irrelevant, but I can redact private stuff and post the rest if it will help>
      Content-Type: application/json
      Date: Thu, 22 Sep 2022 14:40:07 GMT
      Expect-Ct: report-uri="https://oktaexpectct.report-uri.com/r/t/ct/reportOnly", max-age=0
      Expires: 0
      P3p: CP="HONK"
      Pragma: no-cache
      Public-Key-Pins-Report-Only: pin-sha256="jZomPEBSDXoipA9un78hKRIeN/+U4ZteRaiX8YpWfqc="; pin-sha256="axSbM6RQ+19oXxudaOTdwXJbSr6f7AahxbDHFy3p8s8="; pin-sha256="SE4qe2vdD9tAegPwO79rMnZyhHvqj3i5g1c2HkyGUNE="; pin-sha256="ylP0lMLMvBaiHn0ihLxHjzvlPVQNoyQ+rMiaj0da/Pw="; max-age=60; report-uri="https://okta.report-uri.com/r/default/hpkp/reportOnly"
      Server: nginx
      Set-Cookie: sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
      Set-Cookie: autolaunch_triggered=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
      Set-Cookie: JSESSIONID=18B45DBCC9E0FBF67E4709690B321AF7; Path=/; Secure; HttpOnly
      Strict-Transport-Security: max-age=315360000; includeSubDomains
      X-Content-Type-Options: nosniff
      X-Okta-Request-Id: Yyxzx4neKsy-GNVUHgnJwwAAAIw
      X-Rate-Limit-Limit: 300
      X-Rate-Limit-Remaining: 299
      X-Rate-Limit-Reset: 1663857667
      X-Xss-Protection: 0
      
      {
       "errorCode": "E0000002",
       "errorSummary": "The request was not valid: Invalid policy type specified.",
       "errorLink": "E0000002",
       "errorId": "oaed1pm9Rl5TOKgPLQE0pQoDQ",
       "errorCauses": []
      }

I can confirm that our org is classic, not OIE. So can I override the type that the provider is adding? I think I want and OKTA_SIGN_ON policy. The policy that I am trying to represent in tf already exists in my okta instance so I believe it should be a valid use case for our org.

**Comment by monde** [comment]
Just throwing this out there for others when they search issues for `okta_app_signon_policy`:
Our official docs for `okta_app_signon_policy`
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_signon_policy
have the warning: "This feature is only available as a part of the Identity Engine. [Contact support](mailto:dev-inquiries@okta.com) for further information."

@msweaver I can see I allowed type `ACCESS_POLICY` to be set on on resource `okta_app_signon_policy` this in on PR https://github.com/okta/terraform-provider-okta/pull/1193 in this specifc commit a288e76bbec76288fe731f75ddfd6ee1dfd43ec7 . Which is kind of confusing/misleading, imo.

@msweaver I see this is broken for Classic orgs, like yours, and I will use this bug to help me make `okta_app_signon_policy` flexible for classic and oie orgs (again?). I'll will give this bug priority. My apologies for this vampiring your time.

**Comment by monde** [comment]
@msweaver I will address this in our next sprint that starts on Monday.

**Comment by msweaver** [comment]
@monde All good sir. I appreciate your attention to this!

**Comment by monde** [comment]
@msweaver I'm currently working on this ticket. This resource is kind of mis-named as `okta_app_signon_policy` but it is in fact relating to an OIE Access Policy https://developer.okta.com/docs/reference/api/policy/#policy-object

So I can massage the notion of a "sign on" resource that works for both OIE and Classic orgs can you explain to me what you are trying to accomplish? You can email me mike.mondragon@okta.com and we can set up a zoom if needed.

Right now, I'm thinking the resource should just raise an error if it is attempted to be used with a Classic org but want to gather more feedback.

**Comment by monde** [comment]
Ok @msweaver I have some more information.

We don't have public API endpoints for managing app policies for Classic orgs, therefore we won't have support for that in the Terraform provider. The only way to manage app policies in your Classic org is manually through the Admin UI. Apologies for this being a time sync to `/dev/null` for you. 

I am going to do add a preemptive error message about attempting to use `okta_app_signon_policy` on a Classic org so that others get some immediate remediation feedback.

**Comment by msweaver** [comment]
hi @monde . Appreciate the offer to checkin with you and sync up on what we are doing. FWIW, I was/am open to this, but it sounds like from your last message that we won't be able to manage these configs in code until we migrate to OIE. 

I'll bring this back to my teams and we'll figure out what we want to do. Appreciate you and your direction!

**Comment by monde** [comment]
I put an error blocker on the datasources and resources that are OIE specific. The error message refers the TF documentation now, also. Apologies for the time sync you had with this @msweaver . Closing this issue now.

Release https://github.com/okta/terraform-provider-okta/releases/tag/v3.37.0

**Comment by tyronboyd** [comment]
> yo @monde . Thanks again for helping with this. Here's the request/response. It happens basically as you showed:
> 
> ```
>   ---[ REQUEST ]---------------------------------------
>   POST /api/v1/policies HTTP/1.1
>   Host: <redacted>.oktapreview.com
>   User-Agent: okta-sdk-golang/2.15.0-beta.2 golang/go1.17.13 windows/amd64 okta-terraform/3.36.0
>   Content-Length: 87
>   Accept: application/json
>   Authorization: SSWS 00c-8mDJ7IBU3hI_uG5ZiGTnCTdNcy40wBMS8Q7Q3T
>   Content-Type: application/json
>   Accept-Encoding: gzip
>   
>   {
>    "description": "My policy description",
>    "name": "my_policy_name",
>    "type": "ACCESS_POLICY"
>   }
>   
>   -----------------------------------------------------: timestamp=2022-09-22T10:40:06.645-0400
>   2022-09-22T10:40:06.761-0400 [INFO]  provider.terraform-provider-okta_v3.36.0.exe: 2022/09/22 10:40:06 [DEBUG] Okta API Response Details:
>   ---[ RESPONSE ]--------------------------------------
>   HTTP/2.0 400 Bad Request
>   Connection: close
>   Cache-Control: no-cache, no-store
>   Content-Security-Policy: <I'm thinking this is irrelevant, but I can redact private stuff and post the rest if it will help>
>   Content-Type: application/json
>   Date: Thu, 22 Sep 2022 14:40:07 GMT
>   Expect-Ct: report-uri="https://oktaexpectct.report-uri.com/r/t/ct/reportOnly", max-age=0
>   Expires: 0
>   P3p: CP="HONK"
>   Pragma: no-cache
>   Public-Key-Pins-Report-Only: pin-sha256="jZomPEBSDXoipA9un78hKRIeN/+U4ZteRaiX8YpWfqc="; pin-sha256="axSbM6RQ+19oXxudaOTdwXJbSr6f7AahxbDHFy3p8s8="; pin-sha256="SE4qe2vdD9tAegPwO79rMnZyhHvqj3i5g1c2HkyGUNE="; pin-sha256="ylP0lMLMvBaiHn0ihLxHjzvlPVQNoyQ+rMiaj0da/Pw="; max-age=60; report-uri="https://okta.report-uri.com/r/default/hpkp/reportOnly"
>   Server: nginx
>   Set-Cookie: sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
>   Set-Cookie: autolaunch_triggered=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
>   Set-Cookie: JSESSIONID=18B45DBCC9E0FBF67E4709690B321AF7; Path=/; Secure; HttpOnly
>   Strict-Transport-Security: max-age=315360000; includeSubDomains
>   X-Content-Type-Options: nosniff
>   X-Okta-Request-Id: Yyxzx4neKsy-GNVUHgnJwwAAAIw
>   X-Rate-Limit-Limit: 300
>   X-Rate-Limit-Remaining: 299
>   X-Rate-Limit-Reset: 1663857667
>   X-Xss-Protection: 0
>   
>   {
>    "errorCode": "E0000002",
>    "errorSummary": "The request was not valid: Invalid policy type specified.",
>    "errorLink": "E0000002",
>    "errorId": "oaed1pm9Rl5TOKgPLQE0pQoDQ",
>    "errorCauses": []
>   }
> ```
> 
> I can confirm that our org is classic, not OIE. So can I override the type that the provider is adding? I think I want and OKTA_SIGN_ON policy. The policy that I am trying to represent in tf already exists in my okta instance so I believe it should be a valid use case for our org.

**EDIT** Understand that this cannot be done in classic org.

Hi @msweaver, did you find a solution to this? I am facing a similar problem, and trying to use the OKTA_SIGN_ON policy.

Thanks,
Tyron
