### ISSUE TITLE
okta_policy_mfa_default: Documented method results in api validation failure

### ISSUE THREAD

**Issue by LeaderXFX** [okta/terraform-provider-okta#1314]
Using the Okta Documentation to create a okta_policy_mfa_default resource in an OIE tenant results in an `Api validation failed` error.

Resource from documentation:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/46538638/191972366-158f041a-ab86-44ce-ad27-758e33648c76.png">

Resource in my code:
```hcl
resource "okta_policy_mfa_default" "oie_example" {
  is_oie = true

  okta_password = {
    enroll = "REQUIRED"
  }

  # The following authenticator can only be used when `is_oie` is set to true
  okta_verify = {
    enroll = "REQUIRED"
  }
}
```

Results:
> Error: failed to update default MFA policy: the API returned an error: Api validation failed: mediationPolicy. Causes: errorSummary: Password authenticator for default mfa enrollment policy must be required.

Tenant features validated by Okta support:
<img width="707" alt="image" src="https://user-images.githubusercontent.com/46538638/191980553-bc843eb7-0fa5-47f0-81b1-feaaef345882.png">

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.2.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.31.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/okta/okta v3.36.0
```

### Affected Resource(s)

- okta_policy_mfa_default

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.31.0"
    }
    okta = {
      source  = "okta/okta"
      version = "~> 3.36.0"
    }
  }
}
```

### Debug Output

```hcl
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # okta_policy_mfa_default.oie_example will be created
  + resource "okta_policy_mfa_default" "oie_example" {
      + default_included_group_id = (known after apply)
      + description               = (known after apply)
      + id                        = (known after apply)
      + is_oie                    = true
      + name                      = (known after apply)
      + okta_password             = {
          + "enroll" = "REQUIRED"
        }
      + okta_verify               = {
          + "enroll" = "REQUIRED"
        }
      + priority                  = (known after apply)
      + status                    = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "REDACTED"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

okta_policy_mfa_default.oie_example: Creating...
╷
│ Error: failed to update default MFA policy: the API returned an error: Api validation failed: mediationPolicy. Causes: errorSummary: Password authenticator for default mfa enrollment policy must be required.
│ 
│   with okta_policy_mfa_default.oie_example,
│   on mfa.tf line 45, in resource "okta_policy_mfa_default" "oie_example":
│   45: resource "okta_policy_mfa_default" "oie_example" {
```

### Expected Behavior

Successful transaction without Error.

### Actual Behavior

> Error: failed to update default MFA policy: the API returned an error: Api validation failed: mediationPolicy. Causes: errorSummary: Password authenticator for default mfa enrollment policy must be required.

### Steps to Reproduce

Use the terraform Okta documentation to create a resource in an OIE tenant, as they have listed in their documentation.

Link: https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_mfa_default

**Comment by monde** [comment]
@LeaderXFX sorry to see this. I'm about to spend a bunch of time on the policy related bugs.

**Comment by monde** [comment]
Okta internal reference.
