### ISSUE TITLE
okta_policy_password_default fails if another policy exists

### ISSUE THREAD

**Issue by dli-spoton** [okta/terraform-provider-okta#1319]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.2.1
on darwin_amd64
+ provider registry.terraform.io/okta/okta v3.36.0
```

### Affected Resource(s)

- okta_policy_password_default

### Terraform Configuration Files

```hcl
resource "okta_policy_password_default" "default" {
  # this can be anything as long as it causes an change
  password_min_length = 24
}
resource "okta_group" "test" {
  name = "okta-test-group"
}
resource "okta_policy_password" "test" {
  name            = "okta-test-policy"
  status          = "ACTIVE"
  groups_included = [okta_group.test.id]
  auth_provider   = "OKTA"
}
```

### Expected Behavior

Updates the default policy.

### Actual Behavior

```terraform
│ Error: failed to update default password policy: the API returned an error: Cannot modify the priority attribute because it is read-only.
│ 
│   with okta_policy_password_default.default,
│   on policy_password.tf line 3, in resource "okta_policy_password_default" "default":
│    3: resource "okta_policy_password_default" "default" {
│ 
```

### Steps to Reproduce

1. `terraform import 'okta_policy_password_default.default' .`
2. `terraform apply -target 'okta_group.test'`
3. `terraform apply -target 'okta_policy_password.test'`
4. `terraform apply`

### Important Factoids

Only fails if there's one or more other password policies.
Will work just fine if the default policy is the only one.

### References

- #992

**Comment by monde** [comment]
Thanks @dli-spoton . I'm taking on all of these [#policy](https://github.com/okta/terraform-provider-okta/issues?q=is%3Aissue+is%3Aopen+label%3Apolicy) bugs in my next sprint.

Okta internal reference https://oktainc.atlassian.net/browse/OKTA-536442

**Comment by Matt-Hodgs0n** [comment]
Hi @monde, wanted to check if a fix for this issue was released? I'm on 3.41.0 and getting the same error as above for okta_policy_password_default and okta_policy_mfa_default policies. Thanks

**Comment by MichaelOtte-lhsystems** [comment]
I got still the same issue with Okta TF 3.42.0 . Is there a workaround available?

**Comment by MichaelOtte-lhsystems** [comment]
Workaround was to delete the resource "terraform state rm okta_policy_password_default.default " and "apply" again.
After recreating even updates are running smooth.

So i assume that the update is working with newer versions of Okta TF provider but TF state created with old Okta TF provider for  okta_policy_password_default is incompatible.

**Comment by ETrejosS** [comment]
Hi there, the error continues to appear on my case. I imported the resource using version 5.2.0 and then upgraded to 6.9.0, but still it appears when I try to update the default password policy, I'm not setting the priority on the code, but it always seems to try to apply a priority change.

The error code: 
`Error: failed to update default password policy: the API returned an error: Cannot modify the priority attribute because it is read-only.`

**Comment by dli-spoton** [comment]
@ETrejosS, don't know if this was ever fixed. My suggestion would be to leave the default policy alone. Use the standard password policy resource, and create and manage your own copy of the default policy.
