### ISSUE TITLE
Upload code programmatically for okta-hosted sign-in-widget

### ISSUE THREAD

**Issue by pmatpadi** [okta/terraform-provider-okta#1321]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Is there a terraform resource to programmatically either directly upload html code, or specify S3 bucket link to customize the okta-hosted sign-in widget and error page?

### New or Affected Resource(s)

- okta_theme

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- ![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/11234015/192867892-a4caad2c-b7f0-481f-bc77-44cdc84e15df.png)

**Comment by monde** [comment]
@pmatpadi we don't have any datasource/resources for SIW customization. So far, only branding and email using the public APIs.

I would open a [support ticket](https://support.okta.com/) asking for a work around and to also register that you'd like it in the public API. I don't see anything in the public API about modification of the SIW, so it would first have to be exposed as a public API before it would show up in any of our language SDKs or the TF provider.
