### ISSUE TITLE
Use okta_behavior (data/resource) to modify existing behaviors

### ISSUE THREAD

**Issue by bcoquard** [okta/terraform-provider-okta#1326]
Hello,

This is a question to understand how to correctly use the module okta_behavior.

I am trying to modify the existing behaviors provided by Okta to make some of them INACTIVE.

I can't find a way to reference the data object using the : 
data "okta_behavior" "okta_new-geo-location" { ... }

And then find a way to change the status to :
status                    = "INACTIVE"

Can you please provide a way to do it if it is possible ?

I tried :
* Changing the status from the data module (Status can't be changed)
```
data "okta_behavior" "okta_new-geo-location" {
  name   = "New Geo-Location"
  status = "INACTIVE"
}
```
* Making a resource the exact same, hoping it would overide (Had a name conflict)
```
resource "okta_behavior" "okta_new-geo-location" {
  name                      = "New Geo-Location"
  status                    = "INACTIVE"
  type                      = "ANOMALOUS_LOCATION"
  number_of_authentications = 20
  location_granularity_type = "LAT_LONG"
  radius_from_location      = 20
}
```
* Specifyng the ID in the resource and then changing the status (Invalid or unknown key id)
```
resource "okta_behavior" "okta_new-geo-location" {
  id                        = "myid"
  name                      = "New Geo-Location"
  status                    = "INACTIVE"
  type                      = "ANOMALOUS_LOCATION"
  number_of_authentications = 20
  location_granularity_type = "LAT_LONG"
  radius_from_location      = 20
}
```

Thank you.

**Comment by monde** [comment]
Hi @bcoquard 
I'm not as familiar with the behavior datasource and resource but hopefully this gives some threads to pull on.
I see behaviors used in conjunction with [`okta_policy_rule_signon`](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_rule_signon)
Also, here are the datasource and resource docs:

- https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_rule_signon
- https://registry.terraform.io/providers/okta/okta/latest/docs/data-sources/behaviors
- https://registry.terraform.io/providers/okta/okta/latest/docs/data-sources/behavior
- https://registry.terraform.io/providers/okta/okta/latest/docs/resources/behavior

Specifically with regards to your example, I believe you are saying the behavior already exists? If so, do a TF import first to get the existing external values of the resource into the tf state. Assuming you know the ID of the behavior, the command would be something like:

`$ terraform import okta_behavior.okta_new-geo-location <behavior id>`

```terraform
resource "okta_behavior" "okta_new-geo-location" {
  name                      = "New Geo-Location"
  status                    = "INACTIVE"
  type                      = "ANOMALOUS_LOCATION"
  number_of_authentications = 20
  location_granularity_type = "LAT_LONG"
  radius_from_location      = 20
}
```

Let me know what you find @bcoquard

**Comment by bcoquard** [comment]
Thank you for the answer I get that I need to select the behaviors I want to apply on my signons (`okta_policy_rule_signon`).
I already imported the existing behaviors but I can't modify them.

You made me think of two others questions :
* What if I don't give any behavior to my signons ? Are they all applied by default or none are ? (Doc says it's optionnal, what does that mean ?)
* How do you programmatically disable the existing behaviors ?

Thank you.
