### ISSUE TITLE
Okta - User > Group Assignment Automation (Attempt)

### ISSUE THREAD

**Issue by mentlak0** [okta/terraform-provider-okta#1329]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.3.2
+ provider registry.terraform.io/okta/okta v3.36.0

### Affected Resource(s)

- okta_app_group_assignments
- okta_group_memberships
- okta_user

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,

#main.tf
# # Create Okta groups

locals {
  # get DEV group
  dev_group = [for group in var.groupList: group if group.name == "DevOps" ][0]
  # filter okta admins
  okta_admins = [for user in var.userList: join("-", [user.first_name, user.last_name]) if user.okta_bool]
}

resource "okta_group" "groups" {
  for_each = var.groupList
  name        = each.value.name
  description = each.value.description
}

# Assign users to groups
resource "okta_group_memberships" "test" {

  group_id = [for group in var.groupList: group if group.name == "DevOps" ][0]

  # get IDs of okta_admins only
  users = [for okta_bool in local.okta_admins: okta_user.user[okta_bool].id]
}

# Assgins groups to apps
resource "okta_app_group_assignments" "everyone" {
for_each = { for app, v in var.samlAppList: app => v}
    app_id = okta_app_saml.saml_apps[each.key].id
  group {
    id = okta_group.everyone.id
    priority = 1
  }
}

#variables.tf
variable "groupList"{
  type = map(object({
    name          = string
    description   = string
  }))
}

#auto.tfvars
#Group Details
groupList = {
  devOps = {
    name : "DevOps"
    description : "DevOps"
  },
  DS = {
    name : "DS"
    description : "DS"
  },
  BA = {
    name : "BA"
    description : "BA"
  },
  FrontEnd = {
    name : "FrontEnd"
    description : "FrontEnd"
  },
  BackEnd = {
    name : "BackEnd"
    description : "BackEnd"
  }
}
##

```
# Debug Output

### Expected Behavior

If this is the wrong place to be creating the issue then I do apologise. However, I am trying to configure and implement Okta SSO / MFA via Terraform. Reasoning is because I want to manage my organisation accounts and app integrations via terraform as I am wanting to achieve an automated approach to creating a user > assigning user to a group dependent on department > assign apps to user all through a github repo where the user can change the auto .tfvars file, input their user information and request via a PR (approved by myself who is a super admin). 

This will be very cool, as the config will ultimately automate group assignment and apps dependent on the department inputted. 

I am struggling discovering a nice easy way to loop over an iterate user / group ids with a conditional on where, lets say;

okta_user.user.department == okta_group_description (this would be very cool)

The code above may not necessarily show a clear understanding, but almost an attempt to get this working.

If anyone could aid or show configured code from my use case. That would be brill :)

### Actual Behavior

errors on multiple different reasons on my attempts to configure like this.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

N/A

**Comment by mentlak0** [comment]
To add: + provider registry.terraform.io/okta/okta v3.36.0

**Comment by monde** [comment]
@mentlak0 is the `if` clause on a for_each what you are looking for?

- https://stackoverflow.com/questions/63620298/terraform-how-to-use-conditional-if-in-for-each-into-map-object
- https://www.terraform.io/language/meta-arguments/for_each
- https://www.terraform.io/language/expressions/conditionals

The TF docs don't seem to show a good example of combining for each and if, but that stackoverflow answer looks promising.

Something like
```terraform

# Assgins groups to apps
resource "okta_app_group_assignments" "everyone" {
  for_each = {
    for app, v in var.samlAppList: app => v
    if okta_user.user.department == okta_group_description 
  }
    app_id = okta_app_saml.saml_apps[each.key].id
  group {
    id = okta_group.everyone.id
    priority = 1
  }
}```

**Comment by mentlak0** [comment]
Thank you for you're assistance. It is muchly appreciated. I have tried a few things but doesn't work and getting this error.

│ Error: Reference to "each" in context without for_each
│ 
│   on main.tf line 146, in resource "okta_app_group_assignments" "everyone1":
│  146:   if okta_user.user[each.key].department == okta_group.groups[each.key].description
│ 
│ The "each" object can be used only in "module" or "resource" blocks, and only when the "for_each" argument is set.
╵
╷
│ Error: Reference to "each" in context without for_each
│ 
│   on main.tf line 146, in resource "okta_app_group_assignments" "everyone1":
│  146:   if okta_user.user[each.key].department == okta_group.groups[each.key].description
│ 
│ The "each" object can be used only in "module" or "resource" blocks, and only when the "for_each" argument is set.

If you have any ideas on this then great. I will continue researching from the guides you have sent me.

Thank you :)

**Comment by mentlak0** [comment]
Ultimately, I have realised I am trying to map different keys to values from different lists. I don't think its possible to state this in my current direction. 

If this is possible then it would be good to have some assistance if anyone can aid or has a similar use case. For now, I am settling with applications to assign for everyone.
