### ISSUE TITLE
Not able to provision custom `sub` claim

### ISSUE THREAD

**Issue by lasektom** [okta/terraform-provider-okta#133]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14
+ provider.aws v2.64.0
+ provider.okta v3.3.0

### Affected Resource(s)

* okta_auth_server_claim

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Defining a new authorisation server and new custom`sub` claim should create them correctly.
```
resource "okta_auth_server" "main" {
  audiences   = ["example"]
  description = "Example auth server"
  name        = "example-server"
  issuer_mode = "ORG_URL"
  status      = "ACTIVE"
}

resource "okta_auth_server_claim" "sub" {
  auth_server_id = "${okta_auth_server.main.id}"
  name           = "sub"
  value          = "user.id"
  scopes         = ["Any"]
  claim_type     = "RESOURCE"
}
```

### Actual Behavior

The authorisation server is created alongside with default claims, one of which is already called `sub`. This is blocking me from providing a custom `sub` claim due to name collision, the following error is thrown when applying the above code:
```
Error: Error applying plan:

1 error occurred:
	* module.auth_server.okta_auth_server_claim.sub: 1 error occurred:
	* okta_auth_server_claim.sub: The API returned an error: Api validation failed: name. Causes: errorSummary: name: ''name'' must be unique within an authorization server.
```

This forces me to use `terraform import` to import the resource and then modify it.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by bogdanprodan-okta** [comment]
Hi @lasektom! The problem is that `"sub"` is a build-in claim, that's why you get an error. System claims are immutable, so you can not update them either.
