### ISSUE TITLE
`okta_authenticator` adds non-null provider_ attributes to every authenticator type

### ISSUE THREAD

**Issue by ashleyfrost** [okta/terraform-provider-okta#1339]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.3.3
+ provider registry.terraform.io/okta/okta v3.37.0

### Affected Resource(s)

- okta_authenticator

### Terraform Configuration
```
resource "okta_authenticator" "google_otp" {
  name     = "Google Authenticator"
  key      = "google_otp"
  status   = "ACTIVE"
}

resource "okta_authenticator" "okta_password" {
  name     = "Password"
  key      = "okta_password"
  status   = "ACTIVE"
}
```

### Expected Behavior

Attribute values shouldn't be added to authenticator types they don't apply to.  This is especially true for imported resources.  The attributes `provider_auth_port`, `provider_hostname` and `provider_user_name_template` are being set to non-trivial values no matter what authenticator type is specified.  This happens even if they are explicitly set to null in the configuration file and show null in the terraform.tfstate file.  It should be noted that the [documentation](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/authenticator#argument-reference) specifies those three attributes are used only for the "security_key" authenticator type.

### Actual Behavior
```
# okta_authenticator.google_otp will be updated in-place
~ resource "okta_authenticator" "google_otp" {
      id                          = "aaaaaaaaaaaaaaaaaaaa"
      name                        = "Google Authenticator"
    + provider_auth_port          = 9000
    + provider_hostname           = "localhost"
    + provider_user_name_template = "global.assign.userName.login"
      # (4 unchanged attributes hidden)
  }

# okta_authenticator.okta_password will be updated in-place
~ resource "okta_authenticator" "okta_password" {
      id                          = "bbbbbbbbbbbbbbbbbbbb"
      name                        = "Password"
    + provider_auth_port          = 9000
    + provider_hostname           = "localhost"
    + provider_user_name_template = "global.assign.userName.login"
      # (3 unchanged attributes hidden)
  }
```

### Steps to Reproduce

1. `terraform import okta_authenticator.google_otp aaaaaaaaaaaaaaaaaaaa`
2. `terraform import okta_authenticator.okta_password bbbbbbbbbbbbbbbbbbbb`
3.  `terraform plan`

### Additional Comments

While I detailed the import scenario, it also happens on newly created authenticator resources.

**Comment by monde** [comment]
Thanks @ashleyfrost . Thinking out loud, it looks like the provider using the default values out of the schema https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_authenticator.go#L67-L73 , but as you point out, that is incorrect on import. If it is happening here it is likely happening on all the resources, sadly. This needs to be corrected.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-544409

**Comment by ashleyfrost** [comment]
@monde I am absolutely thrilled that the Okta provider for terraform exists and is so well maintained.  I discovered it after we were nearly done configuring our Preview tenant, but before we started working on configuring Production.  I've been carefully crafting terraform configuration to match what I see in the Admin UI and in Postman queries to the Okta API.  This means I am interacting with many resource types as I progress.  So far everything has imported cleanly, except for this issue and the bug referenced in #1176.   

Keep up the good work!  I'll be sure to open issues if I come across other abnormalities.

**Comment by ashleyfrost** [comment]
> Thanks @ashleyfrost . Thinking out loud, it looks like the provider using the default values out of the schema https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_authenticator.go#L67-L73 , but as you point out, that is incorrect on import. If it is happening here it is likely happening on all the resources, sadly. This needs to be corrected.

I fear you are right.  I saw this happen again when I imported a okta_policy_password_default resource type.  The values for minLength, historyCount and autoUnlockMinutes did not match what Postman was returning for the same resource.  Instead the values written into terraform.tfstate on import were the values in https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_policy_password_default.go#L34-L39

**Comment by lukasindre** [comment]
Hey all.  I tested actually applying this on my preview tenant, and all functionality seemed to remain the same.  Have you guys also tried this?  I guess the danger still is that unnecessary/unwanted/invalid write actions are happening when you don't want them
