### ISSUE TITLE
Bump Okta SDK to 2.0

### ISSUE THREAD

**Issue by tgoodsell-tempus** [okta/terraform-provider-okta#134]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The new version of the Okta Golang SDK, version 2.0, has been released. I'm creating this as a mechanism to inform and track progress to migrate the provider to the newly supported version.

My first glance at the new version doesn't show anything which should require us to make a breaking change in the Terraform provider, but I'm not certain that'll remain true as we code the changes.

### New or Affected Resource(s)

All

### Potential Terraform Configuration

N/A

### References

https://github.com/okta/okta-sdk-golang

**Comment by noinarisak** [comment]
Thanks, @tgoodsell-tempus! 

I started to investigate how heavy the lift to move to okta-sdk-golang v2 and my first scan (~15 minutes) there are possible breaking changes. My plate has been pretty packed in the last couple of months (regular day job, I volunteer on this project at Okta 😉 ). Hopefully, there will be some helping hands coming our way to aid effort. 🤞

**Comment by ymylei** [comment]
@noinarisak Good to hear! I've actually started a draft for this in #153 so I can certainly assist here with the necessary code changes and such. There's some upstream work to be done on the SDK itself to get some of the easy stuff working, probably more work done to get support for some of the features we're doing with the articulate and provider custom sdks (but those don't really need to be done immediately either).

Also glad to hear you may be potentially getting help! If you've got good connections at Okta, I think getting some help with the CI environment on the Golang SDK (getting the builds working, ideally using throw away Okta tenant with all the necessary features) and maybe getting a tenant for our full acceptance test suite to run here would be a great addition.

**Comment by ymylei** [comment]
Would you also be able to start a v4 branch we can use to start staging up some of the changes which will be breaking? I know this upgrade in the SDK will be one, there's the PR #154 which looks to be another (though that one is certainly more ready go to than the SDK change).

**Comment by jlaundry** [comment]
@noinarisak would it be helpful for you if we raised Okta support tickets to review open PR's?

We need #154 in order to continue using Okta for our use case, and we pay for premium support, so it seems (from the outside) to be reasonable to have non-volunteer support assigned time for this - but I don't know your internal politics, just an idea 😊

**Comment by RichiCoder1** [comment]
Late September bump. I'd also be interested in contributing to this (and pushing via our support channels).

**Comment by ymylei** [comment]
I'm not super keen on going to v2 until https://github.com/okta/okta-sdk-golang/pull/150 is pushed in (or at least the underlying dependency mixup is dealt with).

**Comment by ymylei** [comment]
Looks like that was merged in, next release of the sdk I'll rebase and update my PR for updating the provider. It'll still be a breaking change but it should be ready at that point for us to use.

**Comment by noinarisak** [comment]
Hi @jlaundry and @ymylei. Apologies for being MIA, still juggling multiple projects, but some cycles opened up for me to review some PRs. 

🎉  I'm getting some help to support the project, but on the initial stage of onboarding the individual and identifying some priorities, more to come. Plus, okta-sdk-golang maintainer (@bretterer) will help with this transition and hopefully help close some of the gaps between the provider and SDK.  

@ymylei I created and push a branch name `v4.0.0-alpha` please re-adjust your PRs to target this branch and Thank you, for starting it off! 💯 👍 🦄 

@jlaundry I going to review your PRs and address anything in the PRs. Thank you, too!

**Comment by noinarisak** [comment]
Closing PR #203 address this now.
