### ISSUE TITLE
Updating recovery attributes in a `okta_policy_password` resource succeeds but returns API read-only error

### ISSUE THREAD

**Issue by ashleyfrost** [okta/terraform-provider-okta#1343]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.3.3
+ provider registry.terraform.io/okta/okta v3.37.0

### Affected Resource(s)

- okta_policy_password

### Terraform Configuration Files

```hcl
resource "okta_policy_password" "example" {
  name                           = "Active Directory Policy"
  auth_provider                  = "ACTIVE_DIRECTORY"
  email_recovery                 = "INACTIVE"
  recovery_email_token           = 60
  sms_recovery                   = "INACTIVE"
}
```

### Expected Behavior

Running apply should either generate an error and not succeed or succeed and not generate an API error.

### Actual Behavior

Running `terraform apply` generates the following error.  However running `terraform plan` or `terraform apply` again finds no changes pending.  I have confirmed with the Okta API that the changes were actually written.

```hcl
│ Error: failed to update password policy: activation has failed: the API returned an error: Cannot modify the status attribute because it is read-only.
```

### Steps to Reproduce

1. Pick an okta_policy_password resource that has an `auth_provider` of ACTIVE_DIRECTORY or LDAP
2. `terraform import okta_policy_password.example aaaaaaaaaaaaaaaaaaaa`
3. Update any of `email_recovery`, `recovery_email_token` or `sms_recovery` attributes
4. Run and confirm `terraform apply` to see the error
5. Run `terraform apply` to see no more pending changes

### Additional Comments

1. There is no error when the auth_provider is OKTA. The error shows up when the auth_provider is ACTIVE_DIRECTORY or LDAP
2. I only reported the `email_recovery`, `recovery_email_token` and `sms_recovery` attributes, as the other recovery attributes generated a different, but appropriate API Policy error when I tried to test them.
3. It is entirely possible that the error is correct behavior and I just misinterpreted it.  I felt it was worth reporting.

**Comment by ashleyfrost** [comment]
It may also be worth mentioning that I am testing on an Identity Engine instance.

**Comment by monde** [comment]
Thanks @ashleyfrost . Agreed, an apply shouldn't make changes and still result in an error. We'll be having a sprint dedicated to policies.

Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-546550
