### ISSUE TITLE
okta_app_swa resource: API returned an error for optional fields

### ISSUE THREAD

**Issue by Devi0909** [okta/terraform-provider-okta#1344]
**Terraform Version**

Terraform v1.2.7
on linux_amd64
provider registry.terraform.io/okta/okta v3.37.0

**Affected Resource(s)**
okta_app_swa

**Terraform Configuration file**
```terraform
resource "okta_app_swa" "example" {
  label          = "example"
  button_field   = "btn-login"
  //password_field = "txtbox-password"
 // username_field = "txtbox-username"
 // url            = "https://example.com/login.html"
}
```

**Error in while doing Terraform apply command **
As per argument reference,username,password and url fileds are optional for above resource.but getting below error if these fields are non mandatory.

Error: failed to create SWA application: the API returned an error: Api validation failed: url. Causes: errorSummary: url: The field cannot be left blank, errorSummary: usernameField: The field cannot be left blank, errorSummary: passwordField: The field cannot be left blank

**Comment by monde** [comment]
Hi @Devi0909 . I know that `url` is not optional, and given the error you've received from the API `password_field` is not optional either. I can see that our TF documentation is incorrect in this regard https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_swa and the Okta API documentation is vague in regard to required attributes for an SWA app https://developer.okta.com/docs/reference/api/apps/#add-plugin-swa-application . Also, our TF provider should have marked `password_field`, `username_field`, `url` as  required so you'd have gotten an error in your plan before attempting an apply: https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_app_swa.go#L33-L48

So, in the meantime before we update the documentation and change the optional settings in the provider, I'd try setting `password_field`, `username_field`, `url` in your swa app resource.

Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-546548
