### ISSUE TITLE
Support import for `okta_app_signon_policy` resource

### ISSUE THREAD

**Issue by Mrorya** [okta/terraform-provider-okta#1347]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow importing of https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_signon_policy resource in order to modify existing policies without pulling in as a data source

Interestingly enough, app_signon_policy_rules already allow importing, so I'm a little confused that this one does not

### New or Affected Resource(s)

- okta_app_signon_policy

### References

- #0000

**Comment by monde** [comment]
@Mrorya my sense is that the original work in our provider didn't give import operations much consideration and we've not been good at supporting it going forward (refs #1244 #1275 ). I'm looking to dedicating a sprint to improving import operations with our provider.

Okta internal reference https://oktainc.atlassian.net/browse/OKTA-546611

**Comment by Mrorya** [comment]
This is not resolved and should still be addressed - commenting to remove stale label

**Comment by ClintonianSunBlaster** [comment]
Any update on this?  I'm having the same issue. Since Okta comes out of the box with a bunch of authentication policies and each of those policies has a catch-all rule, it would be extremely helpful to be able to import rules using a data block then update them using a resource block. Thanks!

**Comment by exitcode0** [comment]
No stalebot 🙂

**Comment by exitcode0** [comment]
No stalebot 🙂

**Comment by critical-mass** [comment]
Having the same issues on my end. Trying to import catch all rules results in a seg. violation. Happy to provide output if needed!

**Comment by icsrmontano** [comment]
I'm also experiencing the same problem. Any luck on this one @monde?

**Comment by duytiennguyen-okta** [comment]
I fixed this https://github.com/okta/terraform-provider-okta/pull/1670 and will be released later this week.
