### ISSUE TITLE
Create User with Authentication Provider

### ISSUE THREAD

**Issue by MichaelOtte-lhsystems** [okta/terraform-provider-okta#1349]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Based on this API example "Create User with Authentication Provider " https://developer.okta.com/docs/reference/api/users/#create-user-with-authentication-provider could the okta_user resource be enhanced to support this feature?

Request example 

```bash
curl -v -X POST \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
-H "Authorization: SSWS ${api_token}" \
-d '{
  "profile": {
    "firstName": "Isaac",
    "lastName": "Brock",
    "email": "isaac.brock@example.com",
    "login": "isaac.brock@example.com",
    "mobilePhone": "555-415-1337"
  },
  "credentials": {
    "provider": {
      "type": "FEDERATION",
      "name": "FEDERATION"
    }
  }
}' "https://${yourOktaDomain}/api/v1/users?provider=true"

```

### New or Affected Resource(s)

- okta_user

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by monde** [comment]
@MichaelOtte-lhsystems this sounds like a great enhancement. I've added it to our internal backlog and see if we can work it in for development. If you'd like to try working on a PR for this feature, regardless of your development experience, I will help you out as well. We can do some in person pairing over zoom. Let me know.

Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-547428

**Comment by MichaelOtte-lhsystems** [comment]
@monde  Thanks for the offer I would go for it if I would be familar with GO but only a JAVA guy :)

**Comment by MichaelOtte-lhsystems** [comment]
@monde I can't access https://oktainc.atlassian.net/browse/OKTA-547428 so can you please provide a status update about this enhancement?

Thanks,
Michael

**Comment by monde** [comment]
@MichaelOtte-lhsystems that is a link to internal Jira at Okta. This is still an open issue / no change.
