### ISSUE TITLE
 okta_policy_mfa resource: Enrollment factors are not getting updated for mfa policy

### ISSUE THREAD

**Issue by Devi0909** [okta/terraform-provider-okta#1359]
Terraform Version

Terraform v1.2.7
on linux_amd64
provider registry.terraform.io/okta/okta v3.37.0

Affected Resource(s)
okta_policy_mfa

**From:**
```hcl
resource "okta_policy_mfa" "custom_policy" {
  name        = "MFA custom policy"
  status      = "ACTIVE"
  is_oie      = true

  okta_password = {
    enroll = "REQUIRED"
  }

  okta_email = {
    enroll = "REQUIRED"
  }

  phone_number = {
    enroll = "OPTIONAL"
  }

  okta_verify = {
    enroll = "OPTIONAL"
  }

  }
```

Post applying the terraform apply updated as below

  okta_password = "DISABLED"

  okta_email = "REQUIRED"
  
  phone_number = "OPTIONAL"
    
  okta_verify = "OPTIONAL"
    
  security_question ="DISABLED"
  
In above case password is getting "DISABLED" though passing as "REQUIRED"

Here I am not passing any value for security question still its updated as DISABLED by default it was in "OPTIONAL" status.

**Comment by monde** [comment]
I need an Okta support engineer to help shift through the issues here. I'm not 100% if this is a bug or a configuration issue. Please open a support https://support.okta.com/help/s/?language=en_US and I'll get internal feedback about it. I'm not sure if you checked out the documentation, there are some notes in there about requirements.
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_mfa
I'll leave this issue open for now.

**Comment by monde** [comment]
I'm hearing from @balaganaparthi-okta he is experiencing this also. I'll mark it as a bug.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-556732
