### ISSUE TITLE
Support `OVERRIDE` type for `master` on `okta_user_schema`

### ISSUE THREAD

**Issue by fschmager** [okta/terraform-provider-okta#136]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
The `okta_user_schema` resource currently only supports setting of `master` to either `OKTA` and `PROFILE_MASTER`. Okta however also supports `OVERRIDE`. This is to set the priority order of profile masters.

Here is what it looks like in the UI:
<img width="690" alt="Screen Shot 2020-06-11 at 17 02 27" src="https://user-images.githubusercontent.com/10031576/84438996-bcdcff00-ac37-11ea-9016-743f7c01ba6e.png">

This is unfortunately [undocumented in the API docs](https://developer.okta.com/docs/reference/api/schemas/#get-user-schema).

Here is what the API accepts/returns for `OKTA` (and `PROFILE_MASTER` resp)
```json
"master": {
    "type": "OKTA"
}
```

Here is what the API accepts/returns for `OVERRIDE`:
```json
"master": {
    "type": "OVERRIDE",
    "priority": [
        {
            "value": "0oargwb86c5zMZY000h7",
            "type": "APP"
        },
        {
            "value": "0oarjixb3bCS2kL5F0h7",
            "type": "APP"
        }
    ]
}
```

### Affected Resource(s)

* [`okta_user_schema`](https://www.terraform.io/docs/providers/okta/r/user_schema.html#master)

The following resources also have `master`, but I'm not sure if `OVERRIDE` applies to them as well:
* [`okta_app_user_schema`](https://www.terraform.io/docs/providers/okta/r/app_user_schema.html#master)
* [`okta_app_user_base_schema `](https://www.terraform.io/docs/providers/okta/r/app_user_base_schema.html#master)

### Potential Terraform Configuration
This is what it could look like to override the master priority. `OVERRIDE` is mutually exclusive with `OKTA`/`PROFILE_MASTER`. So having either `master` xor `master_priority` (implying `OVERRIDE`) would make sense.

#### Attribute declaration example
```hcl
resource "okta_user_schema" "my_attribute" {
  index       = "myAttribute"
  title         = "My Attribute"
  type        = "string"
  master   = "OVERRIDE" // technically superfluous because XOR with OKTA/PROFILE_MASTER
  master_priority {
      type = "APP" 
      app_id = okta_app_user.first_app.id
  }
  master_priority {
      type = "APP" 
      app_id = okta_app_user.second_app.id
  }
}
```
I've only ever seen `type` to be `APP`. Not sure what other types there are. If it is always `APP`, then we could simplify to 
```hcl
master_priority = [okta_app_user.first_app.id, okta_app_user.second_app.id]
```

**Comment by eatplaysleep** [comment]
See https://github.com/terraform-providers/terraform-provider-okta/issues/129

**Comment by fschmager** [comment]
As @eatplaysleep points out, this is a duplicate of #129.
