### ISSUE TITLE
okta_app_saml resource:Inactive applications are getting imported from source tenant

### ISSUE THREAD

**Issue by Devi0909** [okta/terraform-provider-okta#1364]
Terraform Version

Terraform v1.2.7
on linux_amd64
provider registry.terraform.io/okta/okta v3.37.0

Affected Resource(s)
okta_app_saml

**Issue 1:**

Inactive saml applications are fetching from source tenant and same is creating in generated folder(terraformer). Please see below code.

```hcl
resource "okta_app_saml" "tfer--oa6jy3owks7jjs905d7-salesforce" {
  accessibility_self_service = "false"
  app_links_json             = "{\"mc\":true}"
  app_settings_json          = "{\"instanceType\":\"SANDBOX\",\"integrationType\":\"STANDARD\",\"loginUrl\":\"https://hcs-md-dev-ed.my.salesforce.com\"}"
  assertion_signed           = "false"
  auto_submit_toolbar        = "true"
  hide_ios                   = "false"
  hide_web                   = "false"
  honor_force_authn          = "false"
  implicit_assignment        = "false"
  label                      = "Salesforce_Application"
  preconfigured_app          = "salesforce"
  response_signed            = "false"
  saml_version               = "2.0"
  status                     = "INACTIVE"
  user_name_template         = "$${source.login}"
  user_name_template_type    = "BUILT_IN"
}
```

**Issue 2:**
Fetching by default applications amazon-aws-redshift/amazon-appstream  and causing the below error.

```
resource "okta_app_saml" "tfer--oa9i4o5ugpklisrt5d7-amazon-aws-redshift" {
  accessibility_self_service = "false"
  app_links_json             = "{\"login\":true}"
  app_settings_json          = "{\"redshiftAutoCreate\":true,\"redshiftDbUserFormat\":\"$${user.username}\",\"sessionDuration\":3600}"
  assertion_signed           = "false"
  auto_submit_toolbar        = "false"
  hide_ios                   = "false"
  hide_web                   = "false"
  honor_force_authn          = "false"
  implicit_assignment        = "false"
  label                      = "Amazon Web Services Redshift"
  preconfigured_app          = "amazon_aws_redshift"
  response_signed            = "false"
  saml_version               = "2.0"
  status                     = "INACTIVE"
  user_name_template         = "$${source.login}"
  user_name_template_type    = "BUILT_IN"
}
```

**Below  are the errors:**

 Error: failed to create SAML application: the API returned an error: Operation on application settings failed.. Causes: errorSummary: roleARN: The field cannot be left blank
│
│   with okta_app_saml.tfer--oa6a4o5ugpzuisrt5d7-amazon-aws-redshift,
│   on app_saml.tf line 43, in resource "okta_app_saml" "tfer--oa6a4o5ugpzuisrt5d7-amazon-aws-redshift":
│   43: resource "okta_app_saml" "tfer--oa6a4o5ugpzuisrt5d7-amazon-aws-redshift" {
│
╵
│ Error: failed to create SAML application: the API returned an error: Operation on application settings failed.. Causes: errorSummary: roleARN: The field cannot be left blank, errorSummary: sessionDuration: The field cannot be left blank
│
│   with okta_app_saml.tfer--oa6a4pundfes082b5d7-amazon-appstream,
│   on app_saml.tf line 62, in resource "okta_app_saml" "tfer--oa6a4pundfes082b5d7-amazon-appstream":
│   62: resource "okta_app_saml" "tfer--oa6a4pundfes082b5d7-amazon-appstream" {
│
╵
╷
│ Error: failed to create SAML application: the API returned an error: Operation on application settings failed.. Causes: errorSummary: location: The field cannot be left blank, errorSummary: acsURL: The field cannot be left blank
│
│   with okta_app_saml.tfer--oa6a4q34ua3y31zz5d7-amazon-business,
│   on app_saml.tf line 81, in resource "okta_app_saml" "tfer--oa6a4q34ua3y31zz5d7-amazon-business":
│   81: resource "okta_app_saml" "tfer--oa6a4q34ua3y31zz5d7-amazon-business" {

**Comment by monde** [comment]
@Devi0909 I'm not seeing a bug here, the errors look to indicate you are missing required settings in the Okta API, please open a support ticket [support.okta.com](https://support.okta.com/help/s/?language=en_US) for help with configuration usage and setup.

**Comment by Devi0909** [comment]
> @Devi0909 I'm not seeing a bug here, the errors look to indicate you are missing required settings in the Okta API, please open a support ticket [support.okta.com](https://support.okta.com/help/s/?language=en_US) for help with configuration usage and setup.

Regarding issue1:

This issue is from terraform/terraformer side.

We are importing the resources from source okta tenant via terraformer to target tenant, Here Okta_ app_saml data is importing from Okta UI to generated terraform file by using below command.

terraformer import okta --resources=okta_app_saml

Here terraformer is fetching the inactive applications from okta UI and generating the tf file. Post that we are trying to create the resouce(okta_app_saml) in target okta tenant.

terraform init
terraform plan

**Comment by monde** [comment]
Terraformer issue https://github.com/okta/terraform-provider-okta/issues/1382#issuecomment-1320289387
