### ISSUE TITLE
okta_authenticator: failure creating google_otp if it was not created via the UI

### ISSUE THREAD

**Issue by antonmos** [okta/terraform-provider-okta#1367]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform 1.3.2
okta provider 3.38.0

### Affected Resource(s)

- okta_authenticator

### Terraform Configuration Files

```hcl
resource "okta_authenticator" "google_otp" {
  name = "Google Authenticator"
  key  = "google_otp"
}
```

### Debug Output

```
Terraform will perform the following actions:

  # okta_authenticator.google_otp will be created
  + resource "okta_authenticator" "google_otp" {
      + id                          = (known after apply)
      + key                         = "google_otp"
      + provider_auth_port          = 9000
      + provider_hostname           = "localhost"
      + provider_instance_id        = (known after apply)
      + provider_type               = (known after apply)
      + provider_user_name_template = "global.assign.userName.login"
      + status                      = "ACTIVE"
      + type                        = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
....
okta_authenticator.google_otp: Creating...
╷
│ Error: authenticator with key 'google_otp' does not exist
│ 
│   with okta_authenticator.google_otp,
│   on main.tf line 195, in resource "okta_authenticator" "google_otp":
│  195: resource "okta_authenticator" "google_otp" {
│ 
╵
```

### Expected Behavior
 
Apply should succeed

### Actual Behavior
Apply should fail

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
In another org, I created the Google OTP authenticator via the UI.
I could not figure out how to `terraform import` so I ran the apply and it just worked.  A second Google OTP authenticator was NOT added in the UI.

**Comment by monde** [comment]
Thanks @antonmos . I did some debugging, this list authenticators in the create should not be used for verification: https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_authenticator.go#L106 . I verified you can add an authenticator with `POST /api/v1/authenticators` even if the authenticator is not listed in `GET /api/v1/authenticators`

![image](https://user-images.githubusercontent.com/201/201997472-3d62f5ac-f486-4b3d-b64d-ce08ae124667.png)

I did ask internally, the list of authenticators that can be added that is rendered in the UI:
![image](https://user-images.githubusercontent.com/201/201996932-4001453f-2db9-43ce-8993-1bbbe68bdb83.png)
that list of not-added authenticators is not available on a public endpoint. It would be nice of the API exposes those as well. I I'll create Jira tickets for this.

**Comment by antonmos** [comment]
Thanks for looking into this!
I wonder - given that `key` is an enumeration, is it necessary for the okta provider to find in the response  from `GET /api/v1/authenticators` before calling `POST /api/v1/authenticators`?
