### ISSUE TITLE
Duo and IDP authenticators require additional provider information that is not supported 

### ISSUE THREAD

**Issue by csanders-git** [okta/terraform-provider-okta#1375]
### Terraform Version

terraform version v1.1.7
registry.terraform.io/okta/okta v3.38.0

### Affected Resource(s)

- okta_authenticators

### Terraform Configuration Files
Note: these are suggested 

```hcl
resource "okta_authenticator" "duo_classic" {
  name     = "Duo Security"
  key      = "duo"
  settings = {}
  provider_hostname = "xyz.duosecurity.com"
  provider_user_name_template = jsonencode({"template": "oktaId"})
  provider_integration_key = "xxxx"
  provider_secret_key = "XXXXX"
}
```

```hcl
resource "okta_authenticator" "duo_idp" {
  name     = "Duo Universal Prompt"
  key      = "external_idp"
  provider_type = "CLAIMS"
  provider_config = jsonencode({"idpId": "0oa3hr3xxxxxxxxx7"})
}

```

### Expected Behavior

duo and custom IDP factors should be configurable and manageable via Terraform, due to missing options they are not without importing first.

A correctly configured duo and custom idp authenticator requires additional provider config that the terraform provider does not support or incorrectly marks as `Used only for authenticators with type "security_key".`

### Actual Behavior

```
 Error: failed to update authenticator: the API returned an error: Api validation failed: provider. Causes: errorSummary: provider: The field cannot be left blank
│ 
│   with okta_authenticator.duo_classic,
│   on authenticators.tf line 3, in resource "okta_authenticator" "duo_classic":
│    3: resource "okta_authenticator" "duo_classic" {
│ 
╵
╷
│ Error: failed to update authenticator: the API returned an error: Api validation failed: provider. Causes: errorSummary: provider: The field cannot be left blank
│ 
│   with okta_authenticator.duo_idp,
│   on authenticators.tf line 15, in resource "okta_authenticator" "duo_idp":
│   15: resource "okta_authenticator" "duo_idp" {
```

### Important Factoids

The duo configuration is documented in an example directly within the authenticators API page: https://developer.okta.com/docs/reference/api/authenticators-admin/#request it clearly shows the usage of additional provider configs compared to what the docs indicate.

**Comment by monde** [comment]
@csanders-git lucky coincidence, I have an active branch I'm looking to finish today that brings in provider json for #1367
