### ISSUE TITLE
primary_color_contrast_hex and secondary_color_contrast_hex when not set will continuously force updates

### ISSUE THREAD

**Issue by csanders-git** [okta/terraform-provider-okta#1377]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_theme

### Terraform Configuration Files

```hcl
resource "okta_theme" "okta_brand_theme" {
  brand_id                               = okta_brand.footer.id
  logo                                   = "./data/logo.png"
  favicon                                = "./data/favicon.png"
  background_image                       = "./data/background.jpeg"
  primary_color_hex                      = "#fe0111"
  secondary_color_hex                    = "#fafafa"
  sign_in_page_touch_point_variant       = "BACKGROUND_IMAGE"
  end_user_dashboard_touch_point_variant = "LOGO_ON_FULL_WHITE_BACKGROUND"
  error_page_touch_point_variant         = "BACKGROUND_IMAGE"
  email_template_touch_point_variant     = "FULL_THEME"
}

```

### Expected Behavior

After initial apply, no changes are made unless the resource is changed

### Actual Behavior

```
  # okta_theme.okta_brand_theme will be updated in-place
  ~ resource "okta_theme" "okta_brand_theme" {
        id                                     = "thexxxxxxxxxxxxx"
      - primary_color_contrast_hex             = "#000000" -> null
      - secondary_color_contrast_hex           = "#000000" -> null
        # (13 unchanged attributes hidden)
    }
```

### Important Factoids

It seems the issue stems from these values being null and that being silently equated to #000000 by okta 
Setting these values as follows:

```hcl
  primary_color_contrast_hex             = "#000000"
  secondary_color_contrast_hex           = "#000000"
```

Silences the notifications

**Comment by monde** [comment]
@csanders-git I agree with your intuition on the source of the bug which is an unhappy side effect of how golang treats nil/null/blank values and we aren't accounting for that, it seems.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-551711
