### ISSUE TITLE
When `okta_app_user_schema_property` resources are deleted from Terraform, the attributes are not deleted from Okta, despite Terraform reporting the resources are successfully deleted and not showing drift in subsequent `plan` runs.

### ISSUE THREAD

**Issue by swu-etsy** [okta/terraform-provider-okta#1378]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.5

### Affected Resource(s)

- okta_app_user_schema_property
- okta_user_schema_property

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.0.0, ~>1.3.0"
  required_providers {
    okta = {
      source  = "okta/okta"
      version = "~> 3.34"
    }
  }
}

provider "okta" {
  private_key = file("privatekey.pem") 
  client_id   = var.hub_auth_configuration.client_id
  scopes      = var.hub_auth_configuration.api_scopes_required
  org_name    = var.hub_configuration.okta.org_name
  base_url    = var.hub_configuration.okta.base_url
}

locals {
    app_attributes = [
        "testDeleteApp1",
        "testDeleteApp2",
        "testDeleteApp3",
        "testDeleteApp4",
        "testDeleteApp5",
        "testDeleteApp6",
        "testDeleteApp7",
        "testDeleteApp8",
        "testDeleteApp9",
        "testDeleteApp10",
    ]
}

# Commenting the below out to illustrate deletion of prior resources.

# resource "okta_app_user_schema_property" "testDeleteApp" {
#   for_each = toset(local.app_attributes)

#   app_id     = "0oa5hsahubMFqDRjl1d7"
#   index      = each.key
#   title      = each.key
#   type       = "string"
#   required   = false
# }
```

### Debug Output

https://gist.github.com/swu-etsy/835ea710c0f9b50ee9f7a7542ee9bcd6

### Expected Behavior

The app attributes, `testDeleteApp*`, should have been deleted in the Okta instance.

### Actual Behavior

The app attributes continue to exist in the Okta instance, and must be deleted via the Okta UI.

### Steps to Reproduce

1. In terraform, create ~10 `okta_app_user_schema_property` resources, and apply the change.
2. In terraform, delete (or comment out) the resources you created in Step 1. Apply the change, deleting those resources. Terraform should report that the resources were successfully deleted.
3. Run `terraform plan` to confirm there is no drift showing that the resources deleted in Step 2 still exist.
4. In the Okta UI, visit the profile schema for the App containing the resources you created. You should see that some/all of the resources still exist, despite being deleted in step 2.

### Important Factoids

We have also seen this behavior in our Org infrastructure with attempts to delete `okta_user_schema_property` resources. However, failure to delete  `okta_user_schema_property` resources is more rare than failure to delete `okta_app_user_schema_property` resources. I did not include `okta_user_schema_property` in the reproduction steps because I'm not able to reproduce it in my testing environment, but I did want to flag that we have seen  `okta_user_schema_property`  impacted before.

This behavior happens >50% of the time for attempts to delete`okta_app_user_schema_property` resources.

### References

I believe this is the same bug as reported in https://github.com/okta/terraform-provider-okta/issues/889

**Comment by monde** [comment]
Thanks for fresh information on `okta_app_user_schema_property` @swu-etsy . Your details will make for clear steps in an IT to reproduce this bug. I have run into an error with the Okta API on `DELETE /api/v1/meta/schemas/user/{typeId}` where the Okta service is 500'ing. It has locked me out of my test orgs before. I'm not sure if this ticket is exactly the same. The schema endpoints have synchronicity issues we've had to battle as well.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-551863
