### ISSUE TITLE
Access userid of a federated user 

### ISSUE THREAD

**Issue by ahmei0** [okta/terraform-provider-okta#1386]
I need to to get userid of a federated user in my tf code but okta_user data resource doesn't provide that

https://registry.terraform.io/providers/okta/okta/latest/docs/data-sources/user

I need to update billing and technical contact through automation but okta_org_configuration resource expects user_id but I have not way of finding userid of a user?

![image](https://user-images.githubusercontent.com/62230464/203667498-8d50c4e5-bc63-4555-8d26-3d7b3c79b1ab.png)

**Comment by monde** [comment]
@ahmei0 , I don't see `id` documented in the otka user data source docs https://registry.terraform.io/providers/okta/okta/latest/docs/data-sources/user (but it should be). Does `data.okta_user.billing_contact.id` work for you?
