### ISSUE TITLE
`OTHER` os_type leads to weird `os_expression` behavior

### ISSUE THREAD

**Issue by lukasindre** [okta/terraform-provider-okta#1390]
https://github.com/okta/terraform-provider-okta/blob/1cd977230579450a6140994e249dda7af93ea08f/okta/resource_okta_app_signon_policy_rule.go#L402-L406

Hey okta TF devs.  I'm having a weird issue with `os_type` and `os_expression` when creating an `okta_app_signon_policy_rule`.    My initial digging has led me to believe that you may know already what is going on, via [this](https://github.com/okta/terraform-provider-okta/blob/1cd977230579450a6140994e249dda7af93ea08f/examples/okta_app_signon_policy_rule/basic_updated.tf#L94-L105}).

Basically, I have to run a `terraform apply`, while having `os_expression` set to `".*"` (and `os_type` = `OTHER`), then I have to change `os_expression` to `""`, then run a `terraform apply -refresh-only`.  Is there a better way to handle this that I'm missing?

Attached are files that i use to create some rules via child module, and pasted are the specific blocks being used

```
# resource block
resource "okta_app_signon_policy_rule" "device_trust_deny_rule" {
  name            = "${var.policy_rule_name} - deny"
  policy_id       = var.policy_id
  groups_excluded = var.groups_excluded

  # iterate through unsanctioned os local to put them all in the block
  # of platforms to include in the deny
  dynamic "platform_include" {
    for_each = local.unsanctioned_os
    content {
      os_type       = platform_include.value["os_type"]
      type          = platform_include.value["type"]
      os_expression = platform_include.value["os_expression"]
    }
  }

  access = "DENY"
}

# locals block
locals {
  unsanctioned_os = [
    {
      os_type       = "WINDOWS",
      type          = "DESKTOP",
      os_expression = ""
    },
    {
      os_type       = "ANDROID",
      type          = "MOBILE",
      os_expression = ""
    },
    {
      os_type       = "IOS",
      type          = "MOBILE",
      os_expression = ""
    },
    {
      os_type       = "OTHER",
      type          = "DESKTOP",
      os_expression = ""
    },
    {
      os_type       = "OTHER",
      type          = "MOBILE",
      os_expression = ""
    }
  ]

  sanctioned_os = [
    {
      os_type       = "MACOS",
      type          = "DESKTOP",
      os_expression = ""
    }
  ]
}
```

[main.txt](https://github.com/okta/terraform-provider-okta/files/10109902/main.txt)
[variables.txt](https://github.com/okta/terraform-provider-okta/files/10109903/variables.txt)

**Comment by monde** [comment]
Note to self, json encoding issue? Will follow up with more details.

**Comment by lukasindre** [comment]
Thank you sir!  If you need anything more from me, i'd be happy to help!

**Comment by noinarisak** [comment]
Hey @lukasindre, could you try using the [jsonencode](https://developer.hashicorp.com/terraform/language/functions/jsonencode) function, like below, if that is a workaround? 

```
...
  dynamic "platform_include" {
    for_each = local.unsanctioned_os
    content {
      os_type       = platform_include.value["os_type"]
      type          = platform_include.value["type"]
      os_expression = jsonecode(platform_include.value["os_expression"])
    }
  }
...
```

If not, you might have to encode the string like `"\.\*"`.

**Comment by monde** [comment]
@lukasindre if @noinarisak's suggestion resolves your issue please close the issue. If not I can add it to our backlog.

**Comment by lukasindre** [comment]
[resource-block.txt](https://github.com/okta/terraform-provider-okta/files/10116309/resource-block.txt)
[tf-apply-plan.txt](https://github.com/okta/terraform-provider-okta/files/10116310/tf-apply-plan.txt)

heyo, here is the resource block displayed with `jsonencode`, as well as showing a `terraform apply`, followed immediately by `terraform plan`, showing that the statefile still has some drift
