### ISSUE TITLE
Can not create SAML app in OKTA using TF

### ISSUE THREAD

**Issue by callmesukhi** [okta/terraform-provider-okta#1391]
Error: 

`Error: failed to create SAML application: the API returned an error: Api validation failed: mediated. Causes: errorSummary: Cannot create an existing App Wizard App`

**Comment by monde** [comment]
In the future @callmesukhi please use the issue template and provide example config when reporting a bug. Given your error, this sounds like a support issue. Please open a support ticket to get help with using the Okta Terraform provider https://support.okta.com/help/s/?language=en_US
Googling I found this reference https://support.okta.com/help/s/question/0D51Y00005lG693SAC/add-another-instance-of-custom-swa-app-with-the-same-name?language=en_US
