### ISSUE TITLE
Request for new Resource and Datasource `okta_logstream`

### ISSUE THREAD

**Issue by BalaGanaparthi** [okta/terraform-provider-okta#1392]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Request for new resource and datasource for Okta Log Streams 
[Log Streaming API](https://developer.okta.com/docs/reference/api/log-streaming/)

### New or Affected Resource(s)

- okta_logstream

### Potential Terraform Configuration

```hcl
#AWS Eventbridge
resource "okta_logstream" "aws_eventbridge" {
  name     = "AWS EventBridge"
  type     = "aws_eventbridge"
  status   = "ACTIVE"
  settings = {
    eventSourceName = "your-event-source-name",
    accountId       = "123456789012",
    region          = "us-east-2"
  }
}

#Splunk Cloud
resource "okta_logstream" "splunk" {
  name     = "Splunk"
  type     = "splunk_cloud_logstreaming"
  status   = "ACTIVE"
  settings = {
    host  = "acme.splunkcloud.com"
    token = "11111111-1111-2222-2222-222222222222"
  }
}

data "okta_logstream" "logstream" {
  id = "0oa1orzg0CHSgPcjZ0g4"
}
```

### References

`status` : `ACTIVE` or `INACTIVE`
`type` : [Log Stream type](https://developer.okta.com/docs/reference/api/log-streaming/#log-stream-type)
`AWS EventBridge Settings` : [AWS EventBridge Settings](https://developer.okta.com/docs/reference/api/log-streaming/#aws-eventbridge-settings-example)
`Splunk Cloud Settings object ` : [Splunk Cloud Settings object](https://developer.okta.com/docs/reference/api/log-streaming/#splunk-cloud-settings-object)

**Comment by monde** [comment]
Thank you @BalaGanaparthi 
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-555400

**Comment by clementdenis** [comment]
This feature is still needed. Any chance we get it soon ?

**Comment by sseekamp0** [comment]
Yes @monde. Could this still be added?

**Comment by clementdenis** [comment]
Until this is finally implemented in the provider, I made a workaround using the restapi provider:

```hcl
terraform {
  required_providers {
    restapi = {
      source  = "Mastercard/restapi"
      version = "~> 1.18.1"
    }
  }
}

variable "okta_config" {
  type = object({
    org_name = string
    base_url= string
    api_token = string
  })

variable "eventbridge_config" {
  type = object({
    account_id = string
    region     = string
  })
}

provider "restapi" {
  uri = "https://${var.okta_config.org_name}.${var.okta_config.base_url}/"
  headers = {
    Authorization = "SSWS ${var.okta_config.api_token}"
  }
  write_returns_object = true
}

resource "restapi_object" "log_stream" {
  path = "/api/v1/logStreams"
  data = jsonencode({
    "type"     = "aws_eventbridge",
    "name"     = "Log Stream created with Terraform",
    "settings" = {
      "eventSourceName" = "mysource",
      "accountId"       = var.eventbridge_config.account_id,
      "region"          = var.eventbridge_config.region
    }
  })
}

output "log_stream_url" {
  value = "https://${var.okta_config.org_name}-admin.${var.okta_config.base_url}/reports/log-streaming/edit/${restapi_object.log_stream.id}"
}
```

**Comment by nottooshort** [comment]
Just set this up (testing) and was surprised this resource wasn't available.

Sorely needed to maintain consistency in lieu of "terraform everything" principles for all supported providers.

**Comment by dmbaJoe** [comment]
one more company looking for this to be done.

**Comment by randomVariable2** [comment]
Opened PR #1830

**Comment by Azmah-Bad** [comment]
Interested in this 👍
