### ISSUE TITLE
Changes to `okta_policy_mfa` to compose authenticators/factors with `dynamic block`

### ISSUE THREAD

**Issue by BalaGanaparthi** [okta/terraform-provider-okta#1393]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

 
Requesting to change the existing `okta_policy_mfa` to make the authenticators (or factors in case of classic tenant) be dynamically composed in the resource

Example of resource that can be used dynamically is `okta_policy_rule_profile_enrollment`.. as it is possible to compose the resource with multiple profile_attributes using [dynamic-block](https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks) 

### New or Affected Resource(s)

- okta_policy_mfa

### Potential Terraform Configuration

```hcl
# From
resource "okta_policy_mfa" "example_mfa_policy" {
  name        = "MFA Policy OIE"
  status      = "ACTIVE"
  description = "Example MFA policy that uses Okta Identity Engine (OIE) with authenticators"
  is_oie      = true

  okta_password = {
    enroll = "REQUIRED"
  }

  # The following authenticator can only be used when `is_oie` is set to true
  okta_verify = {
    enroll = "REQUIRED"
  }

  groups_included = ["${data.okta_group.everyone.id}"]
}
```

```hcl
# To
resource "okta_policy_mfa" "example_mfa_policy" {
  name        = "MFA Policy OIE"
  status      = "ACTIVE"
  description = "Example MFA policy that uses Okta Identity Engine (OIE) with authenticators"
  is_oie      = true

  #`authenticator` for OIE (can use `factor` for classic)
  authenticator = {
    type = "okta_password"
    enroll = "REQUIRED"
  }

  authenticator = {
    type = "okta_verify"
    enroll = "REQUIRED"
  }

  groups_included = ["${data.okta_group.everyone.id}"]
}
```

By making the changes to the resources as mentioned above the TF scripts using the resource can be composed from : 

(This is the way the resource block must be composed.. and is not conducive to dynamically include the authenticators)
```hcl
# From
resource "okta_policy_mfa" "mfa_enroll_policy" {
  for_each = var.mfa_enroll_policy_list

  name        = each.value.name
  description = each.value.description
  status      = each.value.status
  is_oie      = each.value.is_oie

  okta_password = {
    enroll = each.value.okta_password.enroll
  }

  okta_verify = {
    enroll = each.value.okta_verify.enroll
  }
  
  groups_included = [for group_name in each.value.groups_included : var.group_name-id_map[group_name]]

}
```

To (This is very useful to dynamically compose the resource with configured authenticators that can be input from variables.. .tfvars .. )

```hcl
# To
resource "okta_policy_mfa" "mfa_enroll_policy" {
  for_each     = var.mfa_enroll_policy_list

  name           = each.value.name
  description = each.value.description
  status          = each.value.status
  is_oie           = each.value.is_oie

  dynamic "authenticator" {
    for_each = each.value.rule.authenticator
    content {
      type     = authenticator.value.type
      enroll   = authenticator.value.enroll
    }
  }
  
  groups_included = [for group_name in each.value.groups_included : var.group_name-id_map[group_name]]

}
```

### References

- #0000

**Comment by monde** [comment]
Thank you @BalaGanaparthi 
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-555401
