### ISSUE TITLE
AccTest Failed on TestAccOktaAppSignOnPolicy_destory

### ISSUE THREAD

**Issue by noinarisak** [okta/terraform-provider-okta#1395]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

- Terraform v1.3.3

### Affected Resource(s)

- Data source `okta_policy`: ie  `data "okta_policy" "esample"`
- Possible: data source okta_app_signon_polcy: i.e. `data "okta_app_signon_policy" "example"`

### Terraform Configuration Files

- n/a

### Debug Output

```
▶ make testacc TEST=./okta TESTARGS='-run=TestAccOktaAppSignOnPolicy_destroy'                       
TF_ACC=1 go test ./okta -v -run=TestAccOktaAppSignOnPolicy_destroy  -timeout 120m
=== RUN   TestAccOktaAppSignOnPolicy_destroy
2022/12/06 03:18:00 [INFO]  running with backoff http client, wait min 30000000000, wait max 300000000000, retry max 5
2022/12/06 03:18:00 [DEBUG] performing request: method=GET url=https://terraform-provider-okta.oktapreview.com/api/v1/users/me
2022/12/06 03:18:01 [DEBUG] performing request: method=GET url=https://terraform-provider-okta.oktapreview.com/.well-known/okta-organization
2022/12/06 03:18:01 [DEBUG] performing request: method=GET url=https://terraform-provider-okta.oktapreview.com/api/v1/policies?type=ACCESS_POLICY
    resource_okta_app_signon_policy_test.go:56: Step 1/2 error: Error running pre-apply refresh: exit status 1
        
        Error: failed to list policies: the API returned an error: The request was not valid: Invalid policy type specified.
        
          with data.okta_policy.test,
          on terraform_plugin_test.tf line 5, in data "okta_policy" "test":
           5: data "okta_policy" "test" {
        
--- FAIL: TestAccOktaAppSignOnPolicy_destroy (1.09s)
FAIL
FAIL    github.com/okta/terraform-provider-okta/okta    1.473s
FAIL
make: *** [testacc] Error 1
```

### Panic Output

- n/a

### Expected Behavior

- AccTest to Pass.

### Actual Behavior

- AccTest Failed/Skip

### Steps to Reproduce

1. Contributor environment setup
2. Execute `make testacc TEST=./okta TESTARGS='-run=TestAccOktaAppSignOnPolicy_destroy'`

### Important Factoids

- Only Fails on Okta Classic tenant/org, since  HTTP GET `/api/v1/policies?type=ACCESS_POLICY` only pertains to OIE tenant/org feature.
- The following [line of code](https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_app_signon_policy_test.go#L67-L70) start the bug/issue.

### References

- n/a

**Comment by monde** [comment]
Thanks @noinarisak 
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-556747
