### ISSUE TITLE
`okta_user_schema_property` is replaced when `apply` executed without any changes to resource

### ISSUE THREAD

**Issue by BalaGanaparthi** [okta/terraform-provider-okta#1396]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```version
Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/okta/okta v3.39.0
```

### Affected Resource(s)

- okta_user_schema_property

#### Data
```json
{
    "basic":[
        {
            "index"                 : "FavoriteMovie",
            "title"                 : "Favorite Movie",
            "description"           : "Customer's Favorite Movie",
            "type"                  : "string",
            "min_length"            : 1,
            "max_length"            : 50,
            "required"              : false,
            "master"                : "PROFILE_MASTER",
            "permissions"           : "READ_WRITE",
            "scope"                 : "SELF",
            "unique"                : "NOT_UNIQUE"
        }
    ]
}
```

#### TF Script
```hcl
resource "okta_user_schema_property" "basic_user_schema_property" {
  for_each = { for property in var.user_schema_properties_map.basic : property.index => property }

  user_type   = "${data.okta_user_type.okta_default_user.id}"
  index       = each.value.index
  title       = each.value.title
  description = each.value.description
  type        = each.value.type
  required    = each.value.required
  master      = each.value.master
  min_length  = each.value.min_length
  max_length  = each.value.max_length
  permissions = each.value.permissions
  scope       = each.value.scope
  unique      = each.value.unique
}
```

### Debug Output

```debug
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.user_schema_properties.okta_user_schema_property.basic_user_schema_property["FavoriteMovie"] must be replaced
-/+ resource "okta_user_schema_property" "basic_user_schema_property" {
      ~ id          = "FavoriteMovie" -> (known after apply)
      + unique      = "NOT_UNIQUE" # forces replacement
        # (11 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
module.user_schema_properties.okta_user_schema_property.basic_user_schema_property["FavoriteMovie"]: Destroying... [id=FavoriteMovie]
module.user_schema_properties.okta_user_schema_property.basic_user_schema_property["FavoriteMovie"]: Destruction complete after 0s
module.user_schema_properties.okta_user_schema_property.basic_user_schema_property["FavoriteMovie"]: Creating...
module.user_schema_properties.okta_user_schema_property.basic_user_schema_property["FavoriteMovie"]: Creation complete after 2s [id=FavoriteMovie]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
```

### Panic Output

[tf.trace](https://gist.github.com/BalaGanaparthi/f135329ff4eb00d152e4acbc05edff41)

### Expected Behavior

The resource must not be replaced when the `terraform apply` is executed without any changes to the resource data.

### Actual Behavior

The resource is being replaced (`destroy` and `add`) when the `terraform apply` is executed without any changes to the resource data. This is undesired and will have implications when there are large volumes of user data already onboarded to UD

### Steps to Reproduce

1. Create TF with `okta_user_schema_property` resource (sample mentioned above)
2. `terraform apply`
3. execute `terraform apply` again (without any changes)

### Important Factoids

This issue is not seen when the `okta_user_schema_property` resource is created with 
`type : string` with `enum`
or
`type : array` with `array_enum`

### References

- #0000

**Comment by monde** [comment]
Thanks @BalaGanaparthi 
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-556749

**Comment by rizaak** [comment]
If you send a null instead of NOT_UNIQUE it works fine, while the problem is solved I think it can work without problems
