### ISSUE TITLE
okta_authenticator - okta_verify key only enabling TOTP 

### ISSUE THREAD

**Issue by Matt-Hodgs0n** [okta/terraform-provider-okta#1397]
Hi - I'm using Terraform to add Authenticators to an OIE Okta tenant.

One of the authenticators I've added is Okta Verify using the below Terraform code:

--

```hcl
resource "okta_authenticator" "okta_mfa_factor_okta_verify" {
  name = "Okta Verify "
  key  = "okta_verify"
```

--

The issue I'm having is this will only activate the TOTP type and not the Push type. So I have to manually check Push from the Admin Console.

Looking through the Okta Provider and Authentication API document I've tried to use the **provider_json** and **settings** attributes to specify the 'push' type without success - such as:

--

```hcl
resource "okta_authenticator" "okta_mfa_factor_okta_verify_push" {
  name = "Okta Verify Push"
  key  = "okta_verify"
  provider_json = jsonencode(
    {
      "methods.type" : "push",
    }
  )
}
```

--

OR

--
```hcl

resource "okta_authenticator" "okta_mfa_factor_okta_verify_push" {
  name = "Okta Verify Push"
  key  = "okta_verify"
  settings = jsonencode(
    {
      "factorsType" : "push",
    }
  )
}
```
--

Both these above example return no errors and the Terraform Apply is successful, however, Okta Verify Push remains un-activated.

Can I get some advice how configure this correctly without having to manually activate Push for Okta Verify?

Thanks.

**Comment by monde** [comment]
@mhodgson4 the Okta admin UI is misleading to the TF provider in that the UI knows what authenticators are available to your org, but as you have found, they don't show up as available in API calls until they've been added to the org. So the human has to click the button to add the authenticator first before being able to interact with it in terraform. If you know the specific attributes for the authenticator you can create it with json but that requires the operator to have that knowledge. Similar information is discussed here https://github.com/okta/terraform-provider-okta/issues/1367

There isn't anything the TF provider can do about this. The issue exists on the Okta service side and the Admin UI is making use of private APIs to know the list of authenticators to render on that page. Please open a support ticket https://support.okta.com/help/s/?language=en_US for further help with your config if you need that.
