### ISSUE TITLE
Add an Okta IP ranges data source

### ISSUE THREAD

**Issue by tomelliff** [okta/terraform-provider-okta#1400]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be helpful to have a way to fetch Okta IP ranges via this provider. [These docs](https://help.okta.com/en-us/Content/Topics/Security/ip-address-allow-listing.htm) point out that it's available at https://s3.amazonaws.com/okta-ip-ranges/ip_ranges.json similarly to [AWS' IP ranges](https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html).

Terraform's AWS provider has the [`aws_ip_ranges` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ip_ranges) which helps filter this by eg region or service.

Right now the alternative is to use the [`http` data source](https://registry.terraform.io/providers/hashicorp/http/latest/docs/data-sources/http) and parse it clunkily in HCL with eg:

```hcl
data "http" "okta_ip_range_json" {
  url = "https://s3.amazonaws.com/okta-ip-ranges/ip_ranges.json"
}

locals {
  okta_ip_range_data = jsondecode(data.http.okta_ip_range_json.response_body)
  okta_cell_ranges   = [for key in keys(local.okta_ip_range_data) : local.okta_ip_range_data["${key}"].ip_ranges if key == "us_cell_1"]
  okta_ip_ranges     = sort(distinct(flatten(local.okta_cell_ranges)))
}
```

### New or Affected Resource(s)

- okta_ip_ranges

### Potential Terraform Configuration

```hcl
data "okta_ip_ranges" "us_cell_1_and_apac_cell_2" {
  cells = ["us_cell_1", "apac_cell_2"]
}
```

### References

- https://help.okta.com/en-us/Content/Topics/Security/ip-address-allow-listing.htm
- https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ip_ranges

**Comment by monde** [comment]
@tomelliff we don't have an API endpoint for this. Please open a support ticket https://support.okta.com/help/s/?language=en_US and ask for this information to be made available. The support ticket helps establish the internal process of promoting a feature request to the corresponding feature team.

**Comment by monde** [comment]
Just calling out Okta TF provider is a representation of the Okta Management API. What we need is that data to exist in the management API and not some JSON file published on a CDN.

**Comment by tomelliff** [comment]
> Just calling out Okta TF provider is a representation of the Okta Management API. What we need is that data to exist in the management API and not some JSON file published on a CDN.

Ah okay, so you're not open to adding Okta relevant things that aren't available directly via the API such as how [the AWS provider does the equivalent](https://github.com/hashicorp/terraform-provider-aws/blob/83a21fba7aedf61bda48669611c3fe8e22577198/internal/service/meta/ip_ranges_data_source.go)?

So would the plan be to have Okta expose that via their API in some way, then have the Go SDK autogenerate the relevant parts for that API endpoint and then use it here?

I've raised a ticket for the API to expose this at https://ideas.okta.com/app/#/case/167202?section=requests but let me know if I need to do something different there.

**Comment by 0x91** [comment]
> Just calling out Okta TF provider is a representation of the Okta Management API. What we need is that data to exist in the management API and not some JSON file published on a CDN.

This would be an edge case but there is precedent for this in other providers, i.e. Fastly: https://github.com/fastly/go-fastly/blob/main/fastly/ip.go#L9 and I think it makes sense for a narrow case like this.

Given that this is the list published by Okta, and the [docs](https://help.okta.com/en-us/Content/Topics/Security/ip-address-allow-listing.htm) point to that file, I hope you can reconsider.

**Comment by scadu** [comment]
That would be an immense help for us too. Sure, one could process provided JSON with Terraform but this is cumbersome.

**Comment by denzhel** [comment]
This is a must
