### ISSUE TITLE
This page needs an error message that includes the flag to enable

### ISSUE THREAD

**Issue by amosdavis** [okta/terraform-provider-okta#1403]
This [page](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/idp_saml) needs a support message like this

If you receive the error You do not have permission to access the feature you are requesting [contact support](mailto:dev-inquiries@okta.com) and request feature flag MAPPINGS_API be applied to your org.

**Comment by amosdavis** [comment]
This is similar to this page's message https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_saml

**Comment by monde** [comment]
Thanks @amosdavis . Edits to the documentation and PRs are easy to do in the web browser. I updated the docs in the is PR #1406 .
