### ISSUE TITLE
add additional attribute for okta_app_saml resource

### ISSUE THREAD

**Issue by heydonovan** [okta/terraform-provider-okta#1410]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the Okta UI, if you click on an app, and then `Sign on`, scroll to `SAML Signing Certificates`, then click on `Actions`, and then `View Idp metadata`, you'll get a URL like this: `https://thezebra.okta.com/app/<id>/sso/saml/metadata`. Was unable to find an attribute in the `okta_app_saml` resource to grab this value. Had to use this:

```
output "metadata_url" {
  value = "https://<company>.okta.com/app/${okta_app_saml.this.entity_key}/sso/saml/metadata"
}
```

Can we get that added? I thought `metadata_url` would be it, but it gives this:

```
https://<company>.okta.com/api/v1/apps/<id>/sso/saml/metadata?kid=<random_id>
```

### New or Affected Resource(s)

- okta_app_saml

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by monde** [comment]
Hi @heydonovan `metadata_url` provides the "Preview SAML metadata for application" URL
https://developer.okta.com/docs/reference/api/apps/#preview-saml-metadata-for-application

Your example `value` is not an API URL, do you have it formatted correctly? Also, doesn't your example make the point that you can format a string from resource values in any manner you wish?
