### ISSUE TITLE
New resource request for WS Federated Apps

### ISSUE THREAD

**Issue by itzkumaran** [okta/terraform-provider-okta#1414]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This request is to add 2 new resources to support WS Federation Apps in Okta. We confirmed that the Okta SDK for Golang supports this. 

### New or Affected Resource(s)

- okta_app_ws_federation
- data_source_okta_app_ws_federation

### Potential Terraform Configuration

```hcl
# Resource - Okta WS Federated App
resource "okta_app_ws_federation" "exampleWsFedApp" {
	label    = "exampleWsFedApp"
	site_url = "https://signin.test.com/saml"
	reply_url = "https://test.com"
	reply_override = false
	name_id_format = "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
	audience_restriction = "https://signin.test.com"
	authn_context_class_ref = "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"
	group_filter = "app1.*"
	group_name = "username"
	group_value_format = "dn"
	username_attribute = "username"
	attribute_statements = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname|bob|,http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname|hope|"
	visibility = false
	status = "ACTIVE"
}

# Data Source - Okta WS Federated App
data "okta_app_ws_federation" "exampleWsFedApp" {
  id = "0oa0otab0sRZZPcjZ0z9"
}
```

### References

Okta Golang SDK link for WS Federated Apps below:

- [wsFederationApplication.go](https://github.com/okta/okta-sdk-golang/blob/master/okta/wsFederationApplication.go)
- [wsFederationApplicationSettings.go](https://github.com/okta/okta-sdk-golang/blob/master/okta/wsFederationApplicationSettings.go)
- [wsFederationApplicationSettingsApplication.go](https://github.com/okta/okta-sdk-golang/blob/master/okta/wsFederationApplicationSettingsApplication.go)

- #0000

**Comment by monde** [comment]
Thanks @itzkumaran this data source and resource for WS apps sounds good to me.
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-565040

**Comment by monde** [comment]
Notes from today's internal triage:

We should have a generic "app" resource and data source that allows the operator to give the proper API input for the app such as [WS-Fed](https://developer.okta.com/docs/reference/api/apps/#add-ws-federation-application). Then, where there is a new app in the API we don't have to write go/tf code to support that resource.

@itzkumaran we are still considering this PR and I applaud your effort. We don't typically get 100% encompassing PRs like this.

**Comment by cruscio** [comment]
@monde - any chance this could be revisited?
