### ISSUE TITLE
okta_policy_mfa_default Failing Even When Password is Required

### ISSUE THREAD

**Issue by srvrguy** [okta/terraform-provider-okta#1416]
When trying to configure settings for okta_policy_mfa_default, a message of "failed to update default MFA policy: the API returned an error: Api validation failed: mediationPolicy. Causes: errorSummary: Password authenticator for default mfa enrollment policy must be required." is returned.

Based on my resource configuration where I set okta_password to required, and the debug output, it looks like the provider doesn't send the value of this item when configuring, causing this error to show up.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.3.6
on darwin_arm64
+ provider registry.terraform.io/okta/okta v3.39.0

### Affected Resource(s)

- okta_policy_mfa_default

### Terraform Configuration Files

```hcl
resource "okta_policy_mfa_default" "example" {
  is_oie = true

  okta_email = { "enroll" = "OPTIONAL" }

  okta_verify = { enroll = "OPTIONAL" }

  okta_password = { "enroll" = "REQUIRED" }

  phone_number = { "enroll" = "OPTIONAL" }
}
```

### Debug Output

I had to redact a few things, but the debug output should still be sufficient. If you need more, let me know.

https://gist.github.com/srvrguy/dbdfb9fd4dd1fa8c2123c5a1fc763aef

### Expected Behavior

The default policy should have been updated

### Actual Behavior

An error occurred stating that password needs to be required.

### Steps to Reproduce

1. `terraform apply`

**Comment by monde** [comment]
Thanks @srvrguy , we have a PR #1210 "Enable okta_password authenticator for okta_policy_mfa" related to this we are going to resolve in our next sprint. We can take care of `okta_policy_mfa` and `okta_policy_mfa_default` at the same time.

Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-532535
