### ISSUE TITLE
okta_profile_mapping very slow performance

### ISSUE THREAD

**Issue by merrilladam** [okta/terraform-provider-okta#1428]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform -v
Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.86.0
+ provider registry.terraform.io/mastercard/restapi v1.17.0
+ provider registry.terraform.io/okta/okta v3.40.0

### Affected Resource(s)

- okta_profile_mapping 

### Terraform Configuration Files

```hcl
data "okta_user_profile_mapping_source" "user" {}

resource "okta_profile_mapping" "af_idp_oidc_mapping" {
  source_id          = data.okta_user_profile_mapping_source.user.id
  target_id          = okta_app_oauth.seb_oidc_federation_support.id
  delete_when_absent = false

  mappings {
    id          = "name"
    expression  = "user.displayName"
    push_status = "PUSH"
  }

  mappings {
    id          = "nickname"
    expression  = "user.nickName"
    push_status = "PUSH"
  }

  mappings {
    id          = "given_name"
    expression  = "user.firstName"
    push_status = "PUSH"
  }

  mappings {
    id          = "middle_name"
    expression  = "user.middleName"
    push_status = "PUSH"
  }

  mappings {
    id          = "family_name"
    expression  = "user.lastName"
    push_status = "PUSH"
  }

  mappings {
    id          = "email"
    expression  = "user.email"
    push_status = "PUSH"
  }

  mappings {
    id          = "profile"
    expression  = "user.profileUrl"
    push_status = "PUSH"
  }

  mappings {
    id          = "zoneinfo"
    expression  = "user.timezone == null ? \"America/Los_Angeles\" : user.timezone"
    push_status = "PUSH"
  }

  mappings {
    id          = "locale"
    expression  = "user.countryCode == null ? \"en_US\" : user.countryCode"
    push_status = "PUSH"
  }

  mappings {
    id          = "phone_number"
    expression  = "user.primaryPhone"
    push_status = "PUSH"
  }

  mappings {
    id          = "street_address"
    expression  = "user.streetAddress"
    push_status = "PUSH"
  }

  mappings {
    id          = "locality"
    expression  = "user.city"
    push_status = "PUSH"
  }

  mappings {
    id          = "region"
    expression  = "user.state"
    push_status = "PUSH"
  }

  mappings {
    id          = "postal_code"
    expression  = "user.zipCode"
    push_status = "PUSH"
  }

  mappings {
    id          = "country"
    expression  = "user.countryCode"
    push_status = "PUSH"
  }

  mappings {
    id          = "sebUserId"
    expression  = "user.sebUserId"
    push_status = "PUSH"
  }

  mappings {
    id          = "sebUserTenant"
    expression  = "user.sebUserTenant"
    push_status = "PUSH"
  }

  mappings {
    id          = "sebAuthUserId"
    expression  = "user.sebAuthUserId"
    push_status = "PUSH"
  }

  mappings {
    id          = "sebMembershipId"
    expression  = "user.sebMembershipId"
    push_status = "PUSH"
  }

  mappings {
    id          = "sebUserType"
    expression  = "user.sebUserType"
    push_status = "PUSH"
  }

  depends_on = [
    okta_app_user_schema_property.sebAuthUserId,
    okta_app_user_schema_property.sebMembershipId,
    okta_app_user_schema_property.sebUserId,
    okta_app_user_schema_property.sebUserTenant,
    okta_app_user_schema_property.sebUserType
  ]
}

```

### Debug Output

[Terraform log snippet](https://gist.github.com/merrilladam/5261e37d42b04c7dca89d4ea51751155)

### Expected Behavior

The same terraform completes in less than 60s on several of our Okta tenants that have less than 200 users. However, it takes 40 mins to complete on our production okta tenant which has 56k+ users. I am only assuming the number of users has something to do with it, but am not certain of that. Number of users is really the only difference between our Okta tenants.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

The performance problems only exist in our production okta tenant where we have 56k users. The performance problem does not exist on our other lower environment okta tenants where we have about 200 users.

### References

- #0000

**Comment by merrilladam** [comment]
Ah yes, I see that my token is being rate limited by Okta which probably causing the perf issues. I see a large number of the following api calls being made. 
/api/v1/apps/{app id}/users?after={user id}&limit=200

Curious, does the terraform really need to loop through every one of my users? This makes okta_profile_mapping unusable if we have a significant number of users. At the same time, our number of users will grow significantly in the coming days/months.

**Comment by monde** [comment]
@merrilladam I'll get this onto our backlog, maybe there can be an optimization to skip user data that signaled by the operator like [`okta_app_oauth`](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_oauth) and other resources that expose skip toggles

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-568936
