### ISSUE TITLE
Updating app group assignments after adding a new okta group causes group assignment deletion failures

### ISSUE THREAD

**Issue by amartopoulos** [okta/terraform-provider-okta#1429]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.5, okta provider 3.30.0

### Affected Resource(s)

- okta_group
- okta_app_group_assignments

### Terraform Configuration Files

We have a list (var.aws_accounts) with the names of our various AWS accounts (e.g. dev).  In our okta group module, we iterate over that list, creating groups and then assigning them to the Okta AWS SSO (now IAM Identity) app, like so:

```hcl
// Create Okta group(s) per AWS account
resource "okta_group" "okta_group" {
  for_each = toset(var.aws_accounts)
  name     = "aws-${var.okta_group_name}-${each.key}"
}

// Add Okta groups(s) to the application
resource "okta_app_group_assignments" "okta_group_assignments" {
  app_id = var.okta_group_app
  dynamic "group" {
    for_each = toset(var.aws_accounts)
    content {
      id = okta_group.okta_group["${group.key}"].id
    }
  }
}
```

Additionally, the okta_app_saml resource to which these groups are being assigned, has the following lifecycle rules:

```hcl
  lifecycle {
      ignore_changes = [
        groups,
        features,
      ]
    }
```

### Expected Behavior

When adding an Okta group (which occurs when we add another value to the var.aws_accounts list), the plan output correctly shows it will add the group and then change a number of assignments in-place (1:1 ratio of adds to changes).  When running the apply, I would have expected the new group to be created and then be added to the Okta AWS SSO app.

### Actual Behavior

Terraform fails with 3 errors of the same type in a way that seems like there's resource drift (but there can't be, as this was just freshly deployed from scratch, then a group was added to reproduce the problem):

```
│ Error: failed to delete group assignment: could not delete assignment for group XXXXXXXXXX, to application XXXXXXXXXX: the API returned an error: Not found: Resource not found: XXXXXXXXXXXXXXXXXXXXX (GroupAppAssignment)
│ 
│   with module.okta_group.okta_app_group_assignments.okta_group_assignments,
│   on okta_group/main.tf line 11, in resource "okta_app_group_assignments" "okta_group_assignments":
│   11: resource "okta_app_group_assignments" "okta_group_assignments" {
```

### Steps to Reproduce

1. Create a list of group names, such as ["dev, "prd", "tst"] etc.
2. Create a second list of permission names, such as ["read", "write", "admin"]
3. Nested loop: for each item in the permission list (from step 2), call a module called okta_group, passing to it the group list (from step 1).   Within the module, use for_each again to create each of these Okta groups, then also use a _dynamic_ to assign each group to the Okta AWS SSO app.  This would create group names like dev-read, dev-write, dev-admin, prd-read, prd-write, prd-admin, etc.
4. Apply successfully
5. Add another group name to the list in step 1
6. Reapply -> failure

**Comment by amartopoulos** [comment]
The workaround we found was to not use okta_app_group_assignments at all, but rather use individual okta_app_group_assignment (singular) resources with for_each, instead.  Subsequent updates only added or removed resources instead of trying to update the assignments in place, avoiding the API errors above.  Example:

```hcl
resource "okta_app_group_assignment" "okta_group_assignment" {
  for_each = toset(var.aws_accounts)
  app_id   = var.okta_group_app
  group_id = okta_group.okta_group[each.key].id
}
```

**Comment by kouk** [comment]
@amartopoulos our of curiosity have you tried using the `skip_groups` option on the saml app? I have a similar config and haven't run into this issue. One difference is I have skip_groups=true. Another is i'm not using `toset()`.

**Comment by amartopoulos** [comment]
@kouk Hmm well I'm not sure I understand the behavior of that option.  Wouldn't I want the groups to sync with the app?

**Comment by kouk** [comment]
@amartopoulos In my understanding, what you want today is for your group assignments to be in sync with the okta_app_group_assignments resource, and not with the various app resources such as okta_app_saml. Don't take my word for it, test first, but I believe that if you add `skip_groups` to your app resource that means that the group assignments will be removed from the app resource's TF state and when they change this will leave the app resource's TF state unaffected. So the lifecycle.ignore_changes field is no longer necessary. Unfortunately when adding the `skip_groups` field to an app resource that already exists in the TF state then the plan will report that any pre-existing group assignments are being removed from the resource. Based on my testing this is just removal from the TF state and not from the actual resource in Okta's API.

**Comment by monde** [comment]
Thanks for giving feedback @kouk . @amartopoulos I'll need to look into this further but let me know first if @kouk's suggestion helped out.
