### ISSUE TITLE
okta_app_signon_policy_rule constraints issue

### ISSUE THREAD

**Issue by ClintonianSunBlaster** [okta/terraform-provider-okta#1434]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.3.7
on windows_amd64
+ provider registry.terraform.io/okta/okta v3.41.0

### Affected Resource(s)

okta_app_signon_policy_rule

### Terraform Configuration Files

```hcl
resource "okta_app_signon_policy_rule" "sso_no_mfa_rule" {
  policy_id                   = okta_app_signon_policy.test_authn_policy.id
  name                        = "SSO No MFA"
  priority                    = "2"
  access                      = "ALLOW"
  factor_mode                 = "1FA"
  type                        = "ASSURANCE"
  re_authentication_frequency = "PT43800H"
  groups_included             = ["00g79iqv9eac8lapr5d7"]
  constraints = [
    jsonencode({
      "possession" : {
        "deviceBound": "REQUIRED",
        "hardwareProtection" : "REQUIRED"
      }
    })
  ]
}
```

### Expected Behavior

I'm expecting a new Authentication Policy Rule to be created.  Please note that the code block I've included on this issue works perfectly as long as there are no constraints defined.

### Actual Behavior

If I include a possession constraint of "deviceBound" with or without "hardwareProtection" and/or "phishingResistant" and then run terraform apply, I receive the error "failed to create app sign on policy rule: the API returned an error: Api validation failed: mediationRule. Causes: errorSummary: This rule uses authenticators that have not been set up for your org. Please add at least one of the following authenticators in order to activate this rule: Okta Verify, YubiKey Authenticator".

If I omit "deviceBound" but include "hardwareProtection" and/or "phishingResistant" and run terraform apply, I get the error, "Error: failed to create app sign on policy rule: the API returned an error: Api validation failed: actions.appSignOn.verificationMethod.constraints. Causes: errorSummary: actions.appSignOn.verificationMethod.constraints: 'verificationMethod.constraints' is invalid."

### Steps to Reproduce

Run terraform apply with any combination of possession constraints for "deviceBound" , "hardwareProtection" or "phishingResistant" and you will receive one of the two errors listed above.

### Important Factoids

Nothing atypical. We're boring old normal ;-)

### References

- #0000

**Comment by monde** [comment]
Thanks @ClintonianSunBlaster I can see the corresponding ACC test `TestAccOktaAppSignOnPolicyRule` is failing for this on my preview org. I will have to look into this further. Also looks like you are just using the example from the docs https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_signon_policy_rule . I'll have to be sure / double check the example is work correctly, perhaps have an ACC test based on the example.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-572382

**Comment by ClintonianSunBlaster** [comment]
> Thanks @ClintonianSunBlaster I can see the corresponding ACC test `TestAccOktaAppSignOnPolicyRule` is failing for this on my preview org. I will have to look into this further. Also looks like you are just using the example from the docs https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_signon_policy_rule . I'll have to be sure / double check the example is work correctly, perhaps have an ACC test based on the example.

Hi Mike,

I struggled with how to format the "constraint" portion of the block. The documentation and examples at https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_signon_policy_rule are fuzzy at best (could also be user error). Also, about half way down the page of the link provided above is a line that reads, "More examples can be found here"...the "here hyperlinks to https://developer.okta.com/docs/reference/api/policy/#any-single-factor which has constraint examples for matted completely different from the examples on the TF documentation page...Hopefully, this is just a matter of documentation and not something that needs lots of research to resolve.  Thanks again for your help!

**Comment by monde** [comment]
```
$ TF_ACC=1 go test -tags unit -mod=readonly -test.v -run ^TestAccOktaAppSignOnPolicyRule$ ./okta

2023/01/31 08:23:52 [INFO]  running with default http client
=== RUN   TestAccOktaAppSignOnPolicyRule
    resource_okta_app_signon_policy_rule_test.go:21: Step 2/2 error: Error running apply: exit status 1
        
        Error: failed to create user: the API returned an error: Api validation failed: testAcc_7334087311348261718. Causes: errorSummary: testAcc_7334087311348261718: Value for required property testAcc_7334087311348261718 is missing
        
          with okta_user.test[0],
          on terraform_plugin_test.tf line 30, in resource "okta_user" "test":
          30: resource "okta_user" "test" {
        
        
        Error: failed to create user: the API returned an error: Api validation failed: testAcc_7334087311348261718. Causes: errorSummary: testAcc_7334087311348261718: Value for required property testAcc_7334087311348261718 is missing
        
          with okta_user.test[1],
          on terraform_plugin_test.tf line 30, in resource "okta_user" "test":
          30: resource "okta_user" "test" {
        
        
        Error: failed to create user: the API returned an error: Api validation failed: testAcc_7334087311348261718. Causes: errorSummary: testAcc_7334087311348261718: Value for required property testAcc_7334087311348261718 is missing
        
          with okta_user.test[3],
          on terraform_plugin_test.tf line 30, in resource "okta_user" "test":
          30: resource "okta_user" "test" {
        
        
        Error: failed to create user: the API returned an error: Api validation failed: testAcc_7334087311348261718. Causes: errorSummary: testAcc_7334087311348261718: Value for required property testAcc_7334087311348261718 is missing
        
          with okta_user.test[2],
          on terraform_plugin_test.tf line 30, in resource "okta_user" "test":
          30: resource "okta_user" "test" {
        
        
        Error: failed to create user: the API returned an error: Api validation failed: testAcc_7334087311348261718. Causes: errorSummary: testAcc_7334087311348261718: Value for required property testAcc_7334087311348261718 is missing
        
          with okta_user.test[4],
          on terraform_plugin_test.tf line 30, in resource "okta_user" "test":
          30: resource "okta_user" "test" {
        
--- FAIL: TestAccOktaAppSignOnPolicyRule (10.82s)
FAIL
FAIL	github.com/okta/terraform-provider-okta/okta	11.251s
FAIL
```

**Comment by monde** [comment]
@ClintonianSunBlaster I'm going to close this out. We've had a number of fixes to the okta app signon policy rule lately. That said, I'm not convinced this was even hitting a bug.

On the first error:
apply w/ possession constraint of "deviceBound" with or without "hardwareProtection" and/or "phishingResistant"

The error is prescriptive:
This rule uses authenticators that have not been set up for your org. Please add at least one of the following authenticators in order to activate this rule: Okta Verify, YubiKey Authenticator".

On the second error:
apply w/ omit "deviceBound" but include "hardwareProtection" and/or "phishingResistant" and run terraform apply

The error is complaining about your combination. So I'd experiment in the Admin UI and see what it allows you to do then mimic that in your terraform config. The provider is dumb and just passes whatever the operator sets on the constraints back in the API call back to Okta. This error doesn't look like a coding bug to me.
