### ISSUE TITLE
okta_policy_rule_password missing variables to set recovery "additional verification" options

### ISSUE THREAD

**Issue by ClintonianSunBlaster** [okta/terraform-provider-okta#1435]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.3.7
on windows_amd64
+ provider registry.terraform.io/okta/okta v3.41.0

### Affected Resource(s)
okta_policy_rule_password resource

### Terraform Configuration Files

No code to paste as the issue is the okta_policy_rule_password resource does not have variables that allow you to set the recovery additional verification options in the default rule of the default password policy.

### Expected Behavior

Out of the box the "Security Questions" authenticator is enabled, set to recovery only, and set to disabled in the MFA enrollment policy. But, oddly the default password policy rule is set to require additional recovery verification using "Security Questions".

This is a problem because when you attempt to disable/remove "Security Questions" using the okta_authenticator resource, it is not allowed because "Security Questions" is referenced in the default password policy rule.

Normally, I'd just use the okta_policy_rule_password resource to remove "Security Questions" from the rule but unfortunately, there are no arguments to manipulate this setting.

I'm not sure if this is a bug fix or an enhancement request as it depends on your expectation of the functions of the okta_policy_rule_password resource.

### Actual Behavior

okta_policy_rule_password resource cannot manipulate the recovery additional verification options in the default rule of the default password policy

### Steps to Reproduce

create a okta_policy_rule_password resource block

### Important Factoids

Nothing special

### References

- #0000

**Comment by monde** [comment]
Thanks @ClintonianSunBlaster I need to check internally if there are defaults on the org that causes subsequent changes to not be possible in the provider.

**Comment by monde** [comment]
cc: @jefftaylor-okta

**Comment by monde** [comment]
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-572387

**Comment by ClintonianSunBlaster** [comment]
> ```
> $ TF_ACC=1 go test -tags unit -mod=readonly -test.v -run ^TestAccOktaAppSignOnPolicyRule$ ./okta
> 
> 2023/01/31 08:23:52 [INFO]  running with default http client
> === RUN   TestAccOktaAppSignOnPolicyRule
>     resource_okta_app_signon_policy_rule_test.go:21: Step 2/2 error: Error running apply: exit status 1
>         
>         Error: failed to create user: the API returned an error: Api validation failed: testAcc_7334087311348261718. Causes: errorSummary: testAcc_7334087311348261718: Value for required property testAcc_7334087311348261718 is missing
>         
>           with okta_user.test[0],
>           on terraform_plugin_test.tf line 30, in resource "okta_user" "test":
>           30: resource "okta_user" "test" {
>         
>         
>         Error: failed to create user: the API returned an error: Api validation failed: testAcc_7334087311348261718. Causes: errorSummary: testAcc_7334087311348261718: Value for required property testAcc_7334087311348261718 is missing
>         
>           with okta_user.test[1],
>           on terraform_plugin_test.tf line 30, in resource "okta_user" "test":
>           30: resource "okta_user" "test" {
>         
>         
>         Error: failed to create user: the API returned an error: Api validation failed: testAcc_7334087311348261718. Causes: errorSummary: testAcc_7334087311348261718: Value for required property testAcc_7334087311348261718 is missing
>         
>           with okta_user.test[3],
>           on terraform_plugin_test.tf line 30, in resource "okta_user" "test":
>           30: resource "okta_user" "test" {
>         
>         
>         Error: failed to create user: the API returned an error: Api validation failed: testAcc_7334087311348261718. Causes: errorSummary: testAcc_7334087311348261718: Value for required property testAcc_7334087311348261718 is missing
>         
>           with okta_user.test[2],
>           on terraform_plugin_test.tf line 30, in resource "okta_user" "test":
>           30: resource "okta_user" "test" {
>         
>         
>         Error: failed to create user: the API returned an error: Api validation failed: testAcc_7334087311348261718. Causes: errorSummary: testAcc_7334087311348261718: Value for required property testAcc_7334087311348261718 is missing
>         
>           with okta_user.test[4],
>           on terraform_plugin_test.tf line 30, in resource "okta_user" "test":
>           30: resource "okta_user" "test" {
>         
> --- FAIL: TestAccOktaAppSignOnPolicyRule (10.82s)
> FAIL
> FAIL	github.com/okta/terraform-provider-okta/okta	11.251s
> FAIL
> ```

Hi Mike, did you mean to post this chunk of TF to this issue? okta_user is not in question...just double-checking...
