### ISSUE TITLE
For resource `okta_policy_mfa` the `yubikey_token` authenticator configuration is ignored

### ISSUE THREAD

**Issue by Mrorya** [okta/terraform-provider-okta#1436]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.1.5
on darwin_arm64
+ provider registry.terraform.io/okta/okta v3.41.0

### Affected Resource(s)

- okta_policy_mfa

### Terraform Configuration Files

```hcl
resource "okta_policy_mfa" "yubikey_or_fido2" {
  name        = "Allow Yubikey OTP OR FIDO2"
  status      = "ACTIVE"
  description = "Disable Authenticators Outside of Yubikey OTP + FIDO2"
  priority    = 2
  is_oie      = true

  okta_email = {
    enroll = "NOT_ALLOWED"
  }
  google_otp = {
    enroll = "NOT_ALLOWED"
  }
  okta_verify = {
    enroll = "NOT_ALLOWED"
  }
  okta_password = {
    enroll = "REQUIRED"
  }
  webauthn = {
    enroll = "OPTIONAL"
  }
  security_question = {
    enroll = "NOT_ALLOWED"
  }
  yubikey_token = {
    enroll = "OPTIONAL"
  }
  groups_included = [okta_group.test_group_mfa.id]
}

resource "okta_group" "test_group_mfa" {
  name        = "Test Group MFA"
  description = "Test Group MFA"
  skip_users  = true
  lifecycle { ignore_changes = [users] }
}
```

### Expected Behavior

A policy is created or modified that lists `yubikey_token` as OPTIONAL or REQUIRED, depending on configuration. The above example sets `yubikey_token` as OPTIONAL

### Actual Behavior

When `enroll` is set to `OPTIONAL` or `REQUIRED`, `yubikey_token` is set to `NOT_ALLOWED` / Disabled
![image](https://user-images.githubusercontent.com/3143796/216185915-857b9c86-7ede-41da-a900-7dcb72fc8b7e.png)

### Steps to Reproduce

1. Create an Okta MFA Policy via terraform (or modify an existing one) to set yubikey_token to OPTIONAL or REQUIRED
2. Apply Terraform Plan
3. Note policy details in the enrollment policy page at `https://{{okta_url}}.com/admin/access/multifactor#policies`

Reproduced on Production Okta + Preview Instance on Okta, both on Identity Engine

### Important Factoids

Potentially related to the fix for https://github.com/okta/terraform-provider-okta/issues/1176 / https://github.com/okta/terraform-provider-okta/pull/1210

### References

- #1176

**Comment by monde** [comment]
Thanks @Mrorya . My hunch is the payload to the API is out of the alignment some how or the API endpoint needs some other kind of coordination when there are many authenticators listed. I'll have to look into this.

Okta Internal reference: https://oktainc.atlassian.net/browse/OKTA-575319

**Comment by exitcode0** [comment]
No stalebot 🙂

**Comment by Mrorya** [comment]
un-stale
