### ISSUE TITLE
[ERROR] REPORT_ADMIN is not a valid Okta role

### ISSUE THREAD

**Issue by szymon-lyszkowski-dragon** [okta/terraform-provider-okta#144]
Probably simple validation require fixing:

https://github.com/terraform-providers/terraform-provider-okta/blob/v3.3.0/vendor/github.com/articulate/oktasdk-go/okta/users.go#L624
https://github.com/terraform-providers/terraform-provider-okta/blob/v3.3.0/sdk/group_role.go#L19

Documentation clearly says `REPORT_ADMIN` is supported: 
https://github.com/terraform-providers/terraform-provider-okta/blob/v3.3.0/website/docs/r/group_roles.html.markdown#L30

**Comment by ymylei** [comment]
will be fixed by #138

**Comment by noinarisak** [comment]
Closed #138.
