### ISSUE TITLE
Support SWA Shared Credentials with Two Page Template 

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#1441]
The `okta_app_shared_credentials` resource currently uses the `template_swa`. This must be coded somewhere in the source. There are various times where it's crucial to use the `template_swa_two_page` as modern websites have a next button.

If we could add a variable or flag that would allow specifying the template type (obviously defaulting `template_swa` for backwards compatibility) that would be amazing.

### Reference

The template can be added via OIN:

![image](https://user-images.githubusercontent.com/98786457/216717907-f9e804cc-5f76-469b-9780-3827853545ae.png)

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

`okta_app_shared_credentials`

**Comment by monde** [comment]
Thanks @virgofx . Just double checking, this would be a new app resource for SWA browser plugin?
https://developer.okta.com/docs/reference/api/apps/#add-plugin-swa-application

**Comment by monde** [comment]
I might have to coordinate with an internal feature team at Okta to get all of the behavior surfaced into the API, fyi.

cc: @jefftaylor-okta

**Comment by virgofx** [comment]
@monde I'm not quite sure about the internals. I had a need for this for awhile and eventually called to complain about existing out-of-date vendor apps in the OIN. Then Okta support mentioned that there's a special app in the system for the two-page template that I could use to just do it custom -- which is what I've done.

If you browse to apps and configure it, you'll see it adds a next button and the next password URL and some internal timing delay/logic to handle this. It works great.

![image](https://user-images.githubusercontent.com/739719/217955945-ae04dda9-31ca-4608-8622-7d4a19457e6f.png)


I was unable to get a few of the fields to line up on the existing shared credentials provider / API call and hence the need for either update to existing resource or ability to specify this type of template with the few different/extra fields.

**Comment by virgofx** [comment]
No stalebot

**Comment by exitcode0** [comment]
no stalebot :)
