### ISSUE TITLE
Error: "okta_app_signon_policy" is a resource for OIE Orgs only

### ISSUE THREAD

**Issue by ahmei0** [okta/terraform-provider-okta#1443]
I am experiencing following error on okta_policy_rule_idp_discovery resource while I' not using app_signon_policy anywhere

Error: "okta_app_signon_policy" is a resource for OIE Orgs only, see https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_signon_policy
│ 
│   with data.okta_policy.idp_discovery_policy,
│   on policy_rule_idp_discovery.tf line 3, in data "okta_policy" "idp_discovery_policy":
│    3: data "okta_policy" "idp_discovery_policy" {

Code here:

```
#idp routing policy and rule
data "okta_policy" "idp_discovery_policy" {
  name = "Idp Discovery Policy"
  type = "IDP_DISCOVERY"
}

#idp routing rule for OKTA
resource "okta_policy_rule_idp_discovery" "idp_discovery_rule_okta" {
  policy_id            = data.okta_policy.idp_discovery_policy.id
  priority             = 1
  name                 = "AAD Discovery Exception for myacc customers"
  status               =  "ACTIVE"
  app_include {
    id = okta_app_oauth.myacc_spa.id
    type = "APP"
  }
}
```

**Comment by monde** [comment]
Hi @ahmei0 I can see the error is misleading on the incorrectly identified resource. Beyond that, you shouldn't even get this error. I've fixed the bug, we'll get it out in the next release: #1445
