### ISSUE TITLE
Add Support for VPN Notifications to okta_app_saml/oauth/settings Resources

### ISSUE THREAD

**Issue by awagneratzendesk** [okta/terraform-provider-okta#1446]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Okta supports setting a VPN Required notification on applications with a custom message, URL, and settings on how to handle different networks for the notificiation.

https://help.okta.com/en-us/Content/Topics/Apps/Apps_VPN_Notification.htm

App Admins cannot set this on applications themselves, so this would be really handy to be able to cover in the app_settings_json or a new "notifications_settings_json".

https://github.com/okta/okta-sdk-golang/blob/master/okta/applicationSettings.go shows the structs available for application settings. 

### New or Affected Resource(s)

- okta_app_saml
- okta_app_oauth
- okta_app_saml_app_settings

### Potential Terraform Configuration

```hcl
resource "okta_app_saml" "test-app" {
  app_settings_json = jsonencode(
    {
      app                   = {
		<app settings here>
      },
      notifications    = {
                              "vpn": {
                                "network": {
                                  "connection": "ZONE"
                                  "exclude": [
                                    "ALL_ZONES"
                                  ]
                                },
                                "message": "The VPN is required to access this application.",
                                "helpUrl": "VPN URL Here"
                              }
                            }
    }
  )
```

### References
I haven't seen any past references to this in the repository since the implementation of application JSON settings in 

- #0000

**Comment by monde** [comment]
Thanks @awagneratzendesk I see VPN notifications documented in the public API https://developer.okta.com/docs/reference/api/apps/#notifications-object and it looks like okta-sdk-golang has it also okta-sdk-golang/okta/applicationSettingsNotifications.go . Just need to make time for this work.

Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-579751

**Comment by exitcode0** [comment]
Not stale :)
