### ISSUE TITLE
Implement ability to Filter Custom Profile Attributes on User

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#1449]
For some custom profile attributes, it would be nice to have these excluded from Terraform such that they could be managed from within Okta UI. This may be applicable for those fields that are more sensitive and should be kept out of Terraform state.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

- `okta_user`

**Comment by monde** [comment]
@virgofx thanks for the PR. I need to give the PRs some love and get a release out.

**Comment by monde** [comment]
I'm not going to write a Jira on this, it will get pulled in on the next release. Applying the triaged label.

**Comment by monde** [comment]
Released in [v3.43.0](https://github.com/okta/terraform-provider-okta/releases/tag/v3.43.0)
