### ISSUE TITLE
Add sign on policy for apps

### ISSUE THREAD

**Issue by sme123999** [okta/terraform-provider-okta#145]
Can you add a sign on policy for applications so that I can require MFA and conditional access for my apps via terraform

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* okta_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by noinarisak** [comment]
Hi @sme123999! Sadly there is no API endpoint to manage Application Sign-On Policy. Unfortunately, many UI configuration is not exposed via Okta API. 

Please search and/or submit this request at https://ideas.okta.com/ to let Okta know! 👍
