### ISSUE TITLE
Resource to manage authentication policies for built-in applications

### ISSUE THREAD

**Issue by ClintonianSunBlaster** [okta/terraform-provider-okta#1451]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

A resource is needed that will allow management of authentication policies for built-in applications like Okta Admin Console, Okta Dashboard, and Okta Browser Plugin. As it stands today, an admin needs to manually adjust the authentication via the "Applications" menu of the Admin Console.

Perhaps a new resource called "okta_app_builtin"

- okta_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by monde** [comment]
@ClintonianSunBlaster I need to do research to see if this is possible through the Okta Public API endpoints. Unfortunately not all functions surfaced in the Admin UI are surfaced in the public API. But this is good feature request, regardless.
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-579748
cc: @jefftaylor-okta

**Comment by exitcode0** [comment]
Not stale :)

**Comment by shk3bq4d** [comment]
Hello!

Is it possible to get a formal response on this one instead of the confusing and the not very explicit closure reason by github-actions.

This seems like a rational idea and a blind spot in the current capability of the platform to be fully configured by API which seems, as an outsider, to be the underlying goal of this project.

Quoting [README.md](README.md)

```quote
The Terraform Okta provider is a plugin for Terraform that allows for the full lifecycle management of Okta resources. [..]
```

P.S.
is there more info on https://oktainc.atlassian.net/browse/OKTA-579748 that can be shared publicly?

**Comment by exitcode0** [comment]
@shk3bq4d 
This should be possible with the provider today
You can use the same resources as other app sign-on rules and then import the rule
From there you'll need to use a lifecycle policy to ignore changes on attributes that are immutable on the "system" objects

I'll defer to a maintainer like @monde to confirm the above and to speak to the system attribute and any plans in this space

**Comment by shk3bq4d** [comment]
@exitcode0 : thank you for your answer and follow up.

I seem to have been able to change my Okta Dashboard sign on policy by importing it as an `okta_app_oauth` and then setting its `authentication_policy`

The following snippet should work provided it is read carefully

```
data "okta_app" "okta_dashboard" {
  label = "Okta Dashboard"
}

output "import_app_okta_dashboard" {
  value = "terraform import okta_app_oauth.okta_dashboard ${data.okta_app.okta_dashboard.id}"
}

resource "okta_app_oauth" "okta_dashboard" {
  app_settings_json          = jsonencode({})
  hide_ios                   = true
  hide_web                   = true
  implicit_assignment        = false
  label                      = "Okta Dashboard"
  type                       = ""

  authentication_policy = okta_app_signon_policy.example.id # replace with yours

  lifecycle {
    ignore_changes = [
      auto_key_rotation,
      consent_method,
      issuer_mode,
      login_mode,
      omit_secret,
      refresh_token_leeway,
      refresh_token_rotation,
      token_endpoint_auth_method,
      wildcard_redirect,
      ]
  }
}
```
