### ISSUE TITLE
app_settings_json in okta_saml_app can have a permanent drift with null values

### ISSUE THREAD

**Issue by lix5686** [okta/terraform-provider-okta#1454]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v1.3.8
on darwin_arm64
+ provider registry.terraform.io/okta/okta v3.42.0

### Affected Resource(s)

- okta_app_saml

### Terraform Configuration Files

```hcl
resource "okta_app_saml" "atlassian_test" {
  app_links_json             = jsonencode(
        {
          bitbucket               = false
          compass                 = false
          confluence              = false
          jira                    = false
          jira_service_management = false
          statuspage              = false
          trello                  = true
        }
    )
  app_settings_json          = jsonencode(
        {
          bitbucketUrl             = null
          compassUrl               = null
          confluenceUrl            = null
          jiraServiceManagementUrl = null
          jiraUrl                  = null
          opsgenieUrl              = null
          statusPageUrl            = null
          strideUrl                = "https://app.stride.com"
          trelloUrl                = null
          uniqueID                 = null
        }
    )
  honor_force_authn          = false
  label                      = "Atlassian Cloud test"
  preconfigured_app          = "atlassian"
  saml_version               = "2.0"
  skip_groups                = true
  skip_users                 = true
  status                     = "ACTIVE"
}
```

### Debug Output

```bash
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.hub_apps.okta_app_saml.apps will be updated in-place
  ~ resource "okta_app_saml" "apps" {
      ~ app_settings_json          = jsonencode(
          ~ {
              + bitbucketUrl             = null
              + compassUrl               = null
              + confluenceUrl            = null
              + jiraServiceManagementUrl = null
              + jiraUrl                  = null
              + opsgenieUrl              = null
              + statusPageUrl            = null
              + trelloUrl                = null
              + uniqueID                 = null
                # (1 unchanged element hidden)
            }
        )
        id                         = "0oa8bzvc1ldWmxP2G5d7"
        name                       = "atlassian"
        # (30 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Panic Output

Terraform does not panic in this case.

### Expected Behavior

After creating the app for the first time via terraform, there should be no drifts when running `terraform plan`.

### Actual Behavior

There are always drifts in `app_settings_json` where it's assigning values to null again.

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

Reproduced on personal developer account's Okta and staging Preview Instance on Okta, both on Identity Engine

### References

- #0000

**Comment by monde** [comment]
Thanks @lix5686 . We need better change detection on the fields that are literal JSON object. The Okta API often responds with JSON that is equivalent to what the operator has configured but the literal strings are different causing change detection.

This is what occurs. Assume this is operator provided JSON
```
{
  "one": 1,
  "two": 2
}
```
And the Okta API response is
```
{"two":2,"one": 1}
```
This will cause change detection even though the two objects are equivalent.

**Comment by monde** [comment]
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-579444

**Comment by lix5686** [comment]
@monde Could you remove the stale label since it's unresolved? thank you!

**Comment by lix5686** [comment]
Still active

**Comment by lix5686** [comment]
still active
