### ISSUE TITLE
Support `jwks_uri` in `okta_app_oauth` resource

### ISSUE THREAD

**Issue by clementdenis** [okta/terraform-provider-okta#1455]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `okta_app_oauth` resource currently supports the `jwks` argument to set a single JWKS key.
Supporting `jwks_uri` is required to implement proper key rotation. 

### New or Affected Resource(s)

- okta_app_oauth

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "okta_app_oauth" "example" {
  label          = "example"
  type           = "service"
  response_types = ["token"]
  grant_types    = ["client_credentials"]
  token_endpoint_auth_method = "private_key_jwt"

  jwks_uri = "https://www.example-application.com/oauth2/jwks-uri"
}
```

### References

- [API reference for Application resource](https://developer.okta.com/docs/reference/api/apps/#settings-10)

**Comment by monde** [comment]
Thanks @clementdenis . We will be updating the okta-sdk-golang client from v2 to v3 of our openapi spec this quarter which will cover this missing gag in our SDK's API coverage.

Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-579429
