### ISSUE TITLE
Okta_app_saml resource does not activate certificate as expected

### ISSUE THREAD

**Issue by sseekamp0** [okta/terraform-provider-okta#1459]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
1.3.9

### Affected Resource(s)

- okta_app_saml

### Terraform Configuration Files

```hcl
resource "okta_app_saml" "test" {
  count                 = var.environment == "test" ? 1 : 0
  preconfigured_app     = "amazon_aws"
  label                 = "test"
  status                = "ACTIVE"
  key_name              = "test123"
  key_years_valid       = 2
  lifecycle {
    ignore_changes = [
      groups
    ]
  }
}
```

### Expected Behavior
A new saml application is created and an active certificate is added with a 2 year expiration date.

### Actual Behavior
A saml certificate was created with 2 years validity, but placed in an inactive state. There is no way to activate the new certificate and no way to delete other certificates within the application.

When the application is originally created, I believe that it's creating a default certificate and adding the second certificate with a 2 year validity. So having the option to create a new certificate is essentially pointless if there is no way to activate it and no way to delete the default.

### Steps to Reproduce

1. `terraform apply` with the code block provided

### Important Factoids

Running OIE

- #0000

**Comment by sseekamp0** [comment]
View this dev forum link for context https://devforum.okta.com/t/activate-a-saml-certificate-via-terraform/23425

**Comment by sseekamp0** [comment]
Ideally this should be setup via the following
```
resource "okta_app_saml" "test" {
  count                 = var.environment == "test" ? 1 : 0
  preconfigured_app     = "amazon_aws"
  label                 = "test"
  status                = "ACTIVE"
  keys = [{
      key_name          = "test123"
      key_years_valid   = 2
      status            = ACTIVE
  }]
  

  lifecycle {
    ignore_changes = [
      groups
    ]
  }
}
```

**Comment by monde** [comment]
Just updating status, my colleague @duytiennguyen-okta is currently working on this.

Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-580084

**Comment by sseekamp0** [comment]
Hi @duytiennguyen-okta any updates on this one? Just starting to do a decent amount of work with the SAML resource and hoping to implement some code with the correct certificate validity years.

**Comment by duytiennguyen-okta** [comment]
Hi @sseekamp0 This issue is complete and are on the v3.44.0
