### ISSUE TITLE
Identity Provider custom attribute configuration

### ISSUE THREAD

**Issue by venkatakanupuru** [okta/terraform-provider-okta#1462]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

- okta_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

Hi Team,

For a SAML IDP, resource "okta_idp_saml" I am able to configure the IDP with no issues. However if I require more custom attributes I have to configure them manually. Is there a Terraform resource using which I can configure more attributes for the Identity provider. Configuring a IDP using resource "okta_idp_saml" will configure some basic attributes

Steps for configuring manually IDP attributes : 
OKTA Admin UI >> Security >> Identity Providers >> your IDP >> configure >> Edit Profile and Mappings >> Add Attribute.

In General to configure a custom attribute in Profile editor I use the resource "okta_user_schema_property", but I dont see a way to link the attribute to a IDP.

Please Help.

Thank you
Venkata

![idp attribute](https://user-images.githubusercontent.com/66885752/221053980-08d496cc-6cba-4a60-87ca-1b19c61d593a.png)

**Comment by monde** [comment]
Thanks @venkatakanupuru I'll have look at the API calls but we may just be missing a needed attribute to effect this behavior. I'll mark this as a bug.

Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-581730

**Comment by rtlong** [comment]
@venkatakanupuru  You can use these resource types to augment the IdP user profile with custom attributes and map values into them. For the purposes of the API, I've found that IdP's count as "apps".

```hcl
resource "okta_app_user_schema_property" "email" {
  app_id        = okta_idp_saml.this.id
  ...
}

resource "okta_profile_mapping" "this" {
  source_id = okta_idp_saml.this.id
  target_id = data.okta_user_profile_mapping_source.user.id
 
  mappings {
    id          = "email"
    expression  = "appuser.email"
    push_status = "PUSH"
  }

  depends_on = [
    okta_app_user_schema_property.email
  ]
}

data "okta_user_profile_mapping_source" "user" {}
```

**Comment by venkatakanupuru** [comment]
@rtlong thank you so much, above resource resolved my issue.

**Comment by amaryasin** [comment]
Hi, I have an issue whereby we create the Okta IDP OIDC, then create the custom attribute and applying the mappings, I then need to set on the IDP OIDC field - username_template  = "idpuser.new_custom_attribute".  

How can I update the IDP resource (that was created a few steps earlier) with the new custom attribute?

**Comment by rtlong** [comment]
@amaryasin Yes, there's definitely a dependency loop/confusion with these resources. I'm working around it by using a combination of TF input variables to temporarily rename things to avoid collisions plus some clever/hacky workarounds to make TF and Okta happy while pushing changes. If it helps anyone else, I can share more details and some sample code to illustrate what I mean.

**Comment by amaryasin** [comment]
- @rtlong - If you can provide further details/sample code, that would be great.

I am new to TF, so any help is much appreciated.

Thanks for you assistance
