### ISSUE TITLE
New resource okta_self_service_registration

### ISSUE THREAD

**Issue by mcrobbj** [okta/terraform-provider-okta#1463]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is no resource to set the self service registration details

### New or Affected Resource(s)

- okta_self_service_registration

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "okta_self_service_registration" "example" {
  self_service_registration = true
  sign_in_widget = true
  assign_to_groups = ["myGroup"]
  login_field_form_label= "login"
  password_field_form_label= "password"
.....
 activation_email_verification = true
 default_redirect = "dashboard"
}
```

### References

- #0000

**Comment by venkatakanupuru** [comment]
Hi, I requested for the self service and this was marked as no-api, wontfix 
https://github.com/okta/terraform-provider-okta/issues/235

**Comment by monde** [comment]
@mcrobbj is this a profile enrollment policy? Using these resources?
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_profile_enrollment
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_rule_profile_enrollment
The API docs backing those resources are here https://developer.okta.com/docs/reference/api/policy/#profile-enrollment-policy
Let me know if this helps out.

**Comment by mcrobbj** [comment]
I think it is in Identity Engine, were not on that yet.
Maybe gives us another reason to migrate.

**Comment by monde** [comment]
@mcrobbj were you able to resolve your use case? Can you let me know version of our TF provider you are on? Are you self service registration on Classic.
