### ISSUE TITLE
Cannot update default okta_auth_server_policy created with the server

### ISSUE THREAD

**Issue by NamanChimnani** [okta/terraform-provider-okta#1472]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_auth_server_policy

### Expected Behavior

Setting the default policy created with the auth server to Inactive should update the policy.

### Actual Behavior

An error stating we cannot create an inactive policy and that only existing ones can be deactivated.

### Note
We have other policies defined in our auth server. Our goal is to be able to set the "default policy" to inactive and the resource okta_auth_server_policy does not work as expected

**Comment by monde** [comment]
@NamanChimnani I'll have to look into this. Can you give some sample TF config that will illustrate what you have described so I can be sure I'm trying to repo the correct symptom? Thanks

Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-585644

**Comment by NamanChimnani** [comment]
Thank you for looking into this. Here is what I was trying to do.
```
// setting up auth server
resource "okta_auth_server_default" "auth_server" {
  name                      = "default"
  description               = "A default auth server"
  status                    = "ACTIVE"
  .
  .
  . Other settings
}

// trying to turn off default policy
resource "okta_auth_server_policy" "default_policy" {
  auth_server_id = okta_auth_server_default.auth_server.id
  name           = "Default Policy"
  status         = "INACTIVE"
  description    = "Default Policy for your Authorization Server"
  priority       = 1
  grant_type_whitelist = ["client_credentials"]
}
```

**Comment by tduong10101** [comment]
Hi @monde, thank you for looking into this issue. It is not only affecting default policy, but we are also getting the same error for custom okta_auth_server_policy resource as well.
Error message:
Error: can not create an inactive auth server policy, only existing ones can be deactivated
Terraform resource:

> resource "okta_auth_server_policy" "custom_okta_auth_server_policy" {
>     auth_server_id = resource.okta_auth_server.test.id
>     name = "okta_auth_server_policy"
>     description = "description"
>     priority = "1"
>     status = "INACTIVE"
>     client_whitelist = ["ALL_CLIENTS"]
> }
