### ISSUE TITLE
attribute naming consistency

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1473]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`okta_idp_saml` uses `username_template` and `okta_app_*` uses `user_name_template`
should thees be consistent or was the difference here an intentional decision?

### New or Affected Resource(s)

- okta_idp_saml
- okta_app_saml

**Comment by monde** [comment]
@exitcode0 I agree on the naming consistency, but it probably is too risky in v3.x.x . PM is saying we should look at this in v5.0.0 in our upgrade roadmap.

**Comment by monde** [comment]
The plan this is year is a deprecation and other cruft clean up for a v4.0.0 release. And then everything that is shiny and new in a v5.0.0 release. Both will happen this year.
