### ISSUE TITLE
Create user in group fails due to password policy failed the default policy in okta

### ISSUE THREAD

**Issue by peijiinsg** [okta/terraform-provider-okta#148]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v0.12.24

### Affected Resource(s)

* resource_okta_user

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "okta_user" "login_test_user" {
  first_name                = "login"
  last_name                 = "test"
  login                     = "login.test@example.com"
  email                     = "login.test@example.com"
  password                  = "**********"
  custom_profile_attributes = "{\"customerId\" : \"00000000-0000-0000-0000-000000000000\"}"
  group_memberships         = ["group-id"]
}
```

### Panic Output

Error: [ERROR] Error Creating User from Okta: The API returned an error: Api validation failed: password. Causes: errorSummary: password: Password requirements were not met. Password requirements: at least 8 characters, a lowercase letter, an uppercase letter, a number, no parts of your username. Your password cannot be any of your last 4 passwords.

### Expected Behavior

The user should be successfully created in the given groupID

### Actual Behavior

The user is not created due to the password is not met the password policy.

### Steps to Reproduce

1. Have a default password policy in okta for `Everyone` which has rules:
    - Lower case letter
    - Upper case letter
    - Number (0-9)
    - Symbol (e.g., !@#$%^&*)
    **- Does not contain part of username**
2. Create a new group in okta with new password policy:
    - Lower case letter
    - Upper case letter
    - Number (0-9)
    - Symbol (e.g., !@#$%^&*)
3. Create a user in the group created in step 2.

### Important Factoids

It seems like terraform is creating the user with profile + password first, and then assign the user to the dedicated groups. However, if the password in the new group is weaker than the default one, the creating will fail due to the password policy violation.

Ideally we should just create the user in dedicated group at the same time, I understand this currently is limited by okta-golang-sdk v1, but we might need to find a better way to handle it (by customising the endpoint or upgrading to okta-golang-sdk v2).

### References

* #0000

**Comment by bogdanprodan-okta** [comment]
Hi @peijiinsg! Basically, you are right. Before a user is added to the custom group with different `password` requirements, the password should meet the requirements of the default group. Users can not be added to the group before creation, thus this how it currently works. 
Probably, creating the user can be split into several parts: 1- create user, 2-add it to the group, 3-set password. But there should be logic that will check whether or not the user should be added into the group, where the `password` is set, etc.

**Comment by MichaelOtte-lhsystems** [comment]
@bogdanprodan-okta  is it not possible to set the PW without the old_password like https://developer.okta.com/docs/reference/api/users/#request-example-19 ?


curl -v -X POST \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
-H "Authorization: SSWS ${api_token}" \
-d '{
  "credentials": {
    "password" : { "value": "uTVM,TPw55" }
  }
}' "https://${yourOktaDomain}/api/v1/users/00ub0oNGTSWTBKOLGLNR"

**Comment by monde** [comment]
@MichaelOtte-lhsystems can you please open a new issue provide an example Terraform config so I can see what you are trying to accomplish. Also, if you run terraform with TF_LOG=1 to enable logging you can see what the actual data in the HTTP requests and responses. It might be good to see those, scrub out private information before posting anything.
