### ISSUE TITLE
groups created that are part of a group push rule are not able to be assigned to policies (and likely more) in a single apply

### ISSUE THREAD

**Issue by slichtenthal** [okta/terraform-provider-okta#1487]
### Community Note

Preconditions:
-  an app with group Push Group rules configured.  For example, all groups that begin with `PUSH` get pushed to the target app

Code changes made:
- New groups are created that matches the group push rule. 
- An authentication policy's rule is modified to utilize these push groups

When this happens, what we see is the policy is actually marked as disabled and requires a second apply to enabled it.  Looking at the logs it seems to be a race condition where so much time is taken to setup the group and push group rules that the policy is modified too soon and cannot utilize the group yet.  That causes the policy to be disabled.

Note, this seems to happen much more frequently depending on the number of push groups created and assigned in a single apply.  For example when we create 4 groups that all get pushed, the issue seems to occur 100% of the time.  It is much less frequent with one.

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not le~ave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.0

### Affected Resource(s)

- okta_group
- okta_app_signon_policy_rule
- possibly more?  I would not be surprised if this is an issue for things like okta_app_group_assignment as well.

### Terraform Configuration Files

In the example below, assume all groups that begin with `PUSH` get pushed to a target app

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "okta_group" "my_push_group_1" {
  name        = "PUSH_my_push_group_1"
  description = "Sample Push Group 1"
}

resource "okta_group" "my_push_group_2" {
  name        = "PUSH_my_push_group_2"
  description = "Sample Push Group 2"
}

resource "okta_group" "my_push_group_3" {
  name        = "PUSH_my_push_group_3"
  description = "Sample Push Group 3"
}

resource "okta_group" "my_push_group_4" {
  name        = "PUSH_my_push_group_4"
  description = "Sample Push Group 4"
}

resource "okta_app_signon_policy_rule" "my_new_rule" {
  name      = "Medium Security Rule - Linux"
  policy_id = "[my id]"
  priority  = 1
  groups_included = [
    okta_group.my_push_group_1,
    okta_group.my_push_group_2,
    okta_group.my_push_group_3,
    okta_group.my_push_group_4
  ]

  network_connection          = "ANYWHERE"
  access                      = "ALLOW"
  re_authentication_frequency = "PT2H"
  factor_mode                 = "2FA"
  type                        = "ASSURANCE"

  constraints = [
    jsonencode({
      "possession" : {
        # This property corresponds to what is displayed as "Exclude phone and email authenticators" in the Okta GUI
        "deviceBound" : "REQUIRED",
        "phishingResistant" : "REQUIRED",
      }
    })
  ]
}

```

### Debug Output
https://gist.github.com/slichtenthal/5ec396190afcaf0268fe4773caa8f32f

### Expected Behavior

The groups should be created and the rules updated properly, with them being active

#### Can this be done in the Admin UI?

Yes.  And there's no issue there

#### Can this be done in the actual API call?

Yes, not sure if issue can be recreated there.

### Actual Behavior

groups are created, policy rule is created, but rule is inactive.

### Steps to Reproduce

See above for sample code and notes for steps to reproduce.  Terraform apply is sufficient.

**Comment by monde** [comment]
Thanks @slichtenthal . There isn't a public api endpoint supporting this feature at the present time. Speaking with our PM he is going to work with the Okta feature team to close that API gap so we can make this feature in the TF provider.

Okta internal reference https://oktainc.atlassian.net/browse/OKTA-588023

**Comment by slichtenthal** [comment]
Not stale; still an issue.
