### ISSUE TITLE
SIGSEGV in okta.syncSettings

### ISSUE THREAD

**Issue by hollow** [okta/terraform-provider-okta#1489]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```❯ terraform -v
Terraform v1.3.9
on darwin_arm64
+ provider registry.terraform.io/e-breuninger/netbox v3.1.0
+ provider registry.terraform.io/hashicorp/google v4.56.0
+ provider registry.terraform.io/hashicorp/googleworkspace v0.7.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.17.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/tfe v0.42.0
+ provider registry.terraform.io/okta/okta v3.43.0
```

### Affected Resource(s)

- okta_group

### Terraform Configuration Files

```hcl
resource "okta_group" "teams" {
  for_each    = local.teams
  name        = "${each.value.name} Team"
  description = "Team: ${each.value.name}"
}
```

### Panic Output

https://gist.github.com/hollow/ea7876b157d0d50ba179022ebc4b466a

### Expected Behavior

No segmentation fault.

### Actual Behavior

Segmentation fault.

### Steps to Reproduce

1. Upgrade from 3.42.0 to 3.43.0
2. Run `terraform plan`
3. Unchanged Terraform code causes segmentation fault in the provider

**Comment by monde** [comment]
@hollow you shouldn't see this in v3.44.0 which was the fix for the panic you saw.
https://github.com/okta/terraform-provider-okta/releases/tag/v3.44.0
Let me know if v3.44.0 works for you here.

**Comment by hollow** [comment]
@monde sorry for the noise, this was still open in my terminal from last week. I should have checked the latest release which indeed fixes the issue 🙏
