### ISSUE TITLE
supporting format character restriction in Profile Editor

### ISSUE THREAD

**Issue by mihzaidi** [okta/terraform-provider-okta#149]
Hello Team,
     It seems that the old functionality for pattern isn't working as intended and in fact can't be currently done in the Terraform object for user schema today. I'm linking over an old release that had the pattern functionality but for some reason seems to have been removed.
https://github.com/articulate/terraform-provider-okta/releases/tag/v3.0.29

I also noticed that there was an issue opened with pattern, min length, and max length for login, but the issue went stale and was closed: https://github.com/terraform-providers/terraform-provider-okta/issues/53

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.13.0-beta2
+ provider registry.terraform.io/terraform-providers/okta v3.3.0

### Affected Resource(s)

resource "okta_user_schema" schema_login
resource "okta_user_base_schema" login

### Terraform Configuration Files

resource "okta_user_base_schema" "login" {
    index = "login"
    permissions = "READ_ONLY"
    required = true
    title = "Username"
    type = "string"
    pattern = ".+"	
}

```

### Debug Output
   
  Error: Unsupported argument
  on user_schema.tf line 2, in resource "okta_user_base_schema" "login":
   2:   pattern = ".+"
<!---


### Expected Behavior

I believe based on the old configuration this should have passed through without any issues.
### Actual Behavior

  Error: Unsupported argument
  on user_schema.tf line 2, in resource "okta_user_base_schema" "login":
   2:   pattern = ".+"

Steps to reproduce.
1. Add the artifact in a tf file
2. output a plan
3. Apply the plan

**Comment by bogdanprodan-okta** [comment]
Hi @mihzaidi! There is PR #159 that will add the `pattern` property for the `login` resource.
