### ISSUE TITLE
Terraform Registry not referencing correct latest release of this provider

### ISSUE THREAD

**Issue by slichtenthal** [okta/terraform-provider-okta#1490]
### Community Note

In [github](https://github.com/okta/terraform-provider-okta/releases), it looks like the latest released version of the terraform provider is 3.44.0.  Yet the [Terraform registry](https://registry.terraform.io/providers/oktadeveloper/okta/latest) is still showing it as 3.37.0

**Comment by virgofx** [comment]
@slichtenthal The official provider changed namespaces awhile back and that's why.

Use `okta/okta`.

https://registry.terraform.io/providers/okta/okta/latest

**Comment by monde** [comment]
Good eyes @virgofx thanks. I was just about to email our Hashi contact ...
