### ISSUE TITLE
okta_group_role doesn't support role_type = "CUSTOM"

### ISSUE THREAD

**Issue by ppanan33** [okta/terraform-provider-okta#1491]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_group_role

### Terraform Configuration Files

```hcl
resource "okta_group_role" "example" {
  group_id  = "00g6znhq3aJEJVuRz1d7"
  role_type = "CUSTOM"
}
```

### Debug Output

Terraform Plan pass, but Terraform Apply throws an Error. saying "The request was not valid: Custom role id or name required for a CUSTOM assignment"

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/97427854/225840344-bd8aa2ad-c084-453d-8e68-605868a75276.png">

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

I don't know

### Steps to Reproduce

1. `terraform apply`

**Comment by monde** [comment]
Thanks @ppanan33 we need to get that updated. I'd like to get rid of those hard coded validators in the provider. They are artificial, the API will input validation regardless.

Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-589536

**Comment by virgofx** [comment]
We actually had a need for this as we have custom groups and wanted to Terraform those.  I believe what happened here is the actual API updated and we didn't add the corresponding required fields in the Okta/TF land. I'll throw up a PR for this @monde

**Comment by virgofx** [comment]
Edit: Been super busy on my side and won't be woke to look at this anytime soon. If anyone wants to grab this by all means please do so.

**Comment by JasonBuckner** [comment]
Also related to #1153
