### ISSUE TITLE
The inline registration hook currently does not support OAuth authorization header.

### ISSUE THREAD

**Issue by mc185282** [okta/terraform-provider-okta#1496]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The inline registration hook currently does not support OAuth feature.

### New or Affected Resource(s)

- okta_inline_hook

### Potential Terraform Configuration

```hcl
resource "okta_inline_hook" "example" {
  name    = "example"
  version = "1.0.0"
  type    = "com.okta.oauth2.tokens.transform"

  channel = {
    version = "1.0.0"
    uri     = "https://example.com/test"
    method  = "POST"
  }

  auth = {
    key   = "Authorization"
    type  = "HEADER"
    client_id = "CLIENT_ID"
    client_secret = "CLIENT_SECRET"
    token_url = "URL"
    scope = "scope"
  }
}
```

### References

- #0000

**Comment by monde** [comment]
I'm not sure if the different post types were available when this resource was created but I can see in the API docs that the secrete post type is not supported by the resource and needs to be updated:
https://developer.okta.com/docs/reference/api/inline-hooks/#config-object-parameters-for-client-secret-post
Thanks @mc185282

**Comment by monde** [comment]
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-592048
