### ISSUE TITLE
Question: Create API Token from Terraform

### ISSUE THREAD

**Issue by m-mykytyn** [okta/terraform-provider-okta#1499]
Hi! Is there a way to create a new API Token for the User from Terraform?
![image](https://user-images.githubusercontent.com/127191589/226932961-1faab577-d67b-46b5-8198-634ed90dafec.png)

Terraform is running with a user API Token. So if I want to create the new User and the API Token for this user and it might be a problem I think. Do you have some thoughts about that?

**Comment by monde** [comment]
@m-mykytyn You can only create Okta API tokens (SSWS) via the Admin UI (where you are at in the screen shot) https://developer.okta.com/docs/guides/create-an-api-token/main/
