### ISSUE TITLE
Support OIDC Pre-Configured Apps

### ISSUE THREAD

**Issue by ReeceBlack123** [okta/terraform-provider-okta#1511]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I can't find a way to set up OIDC Pre-Configured Apps e.g https://www.okta.com/integrations/xakia/ using the Okta Terraform Provider.

At the moment, the terraform Okta provider only supports `okta_app_saml` & `okta_app_swa`.

It would be great to support pre-configured applications that use OIDC.

### New or Affected Resource(s)

- okta_app_oauth - https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_oauth

### References

An example of an OIDC Preconfigured App from the Okta App catalogue - https://www.okta.com/integrations/xakia/

**Comment by monde** [comment]
@ReeceBlack123 not all of the Okta Integration Apps are represented in the Okta Management API that backs our SDKs and the Terraform Provider. I know that the PMs and feature teams responsible for OIN and working on making a fully feature API for OIN apps. Until we have that capability in the API we will not be able to address the issue you are having.

**Comment by albertchen-okta** [comment]
+1 this year, the OIN team is working on improvements to api/v1/apps to allow creation of any OIN app, stay tuned!

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-602007

**Comment by Reflejo** [comment]
Is this supported now?
