### ISSUE TITLE
Perpetual Drift - `app_settings_json` & `app_links_json` accept invalid updates

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1518]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.1.6
on darwin_arm64
+ provider registry.terraform.io/okta/okta v3.41.0
```

### Affected Resource(s)
- okta_app_*

### Terraform Configuration Files
```hcl
resource "okta_app_bookmark" "test" {
  label = "google"
  url   = "https://www.google.com"
  app_links_json = jsonencode({
    fizz        = "buzz"
    google_link = false
    link        = false
  })
}

resource "okta_app_saml" "salesforce_fedid" {
  app_links_json = jsonencode({})
  app_settings_json = jsonencode({
    link                  = false
    salesforce-fedid_link = false
  })

  label             = "salesforce-fedid"
  preconfigured_app = "salesforce-fedid"
  status            = "ACTIVE"
}
```

### Expected Behavior
The Okta Terraform Provider and/or the Okta API should reject the invalid updates to `app_settings_json` and `app_links_json`

The Okta Terraform Provider should also use `diffsupressfunc` to ensure `login = true` or similar doesn't appear in the plan as this value appears to be immutable as this seems to be managed by `hide_web` and `hide_ios`

#### Can this be done in the Admin UI?
As far as I know both `app_settings_json` & `app_links_json` can be updated via the Admin UI
#### Can this be done in the actual API call?
As far as I know both  `app_settings_json` & `app_links_json` can be updated via the API

### Actual Behavior
Invalid Key-values in these attributes don't cause a failure during `validate`, `plan`, or `apply`
But all subsequent plans will then show perpetual drift
Either Okta allows these updates to proceed and then immediately corrects the value, or the Okta API is incorrectly returning a 200 for an update that has not succeeded

Perpetual drift can make reviewing plans more difficult

### Steps to Reproduce

1. `terraform apply -auto-approve`
2. `terraform apply -auto-approve`
3. `terraform apply -auto-approve`
4.  `terraform plan`

### Important Factoids
These attributes exist in my config in part because I imported `okta_app_*` resources using terraform import when onboarding to the Okta Terraform Provider
They continue to persist in our config because :
1. Engineers will copy existing known-working TF config and modify as required 
2. Engineers will the following workflow:
    -  Create resource via click-ops in a lower env
    -  import config to state
    - `terraform state show >> temp.hcl`
    - `terraform validate` -> remote invalid lines -> repeat until `terraform validate` passes
    -  Commit resulting known-good / known-valid config to main TF repo

I plan to eliminate these from our config where they are not required to address point 1

With all that said, I felt this should be raised as a bug as:
IMO these attributes should not cause perpetual drift if miss-used, they should either fail to apply and/or should use `diffsuppressfunc` where applicable
The API accepting invalid updates and returning a 200 is certainly an upstream issue, but I'm not sure where I should've raised this issue, the [open api spec](https://github.com/okta/okta-management-openapi-spec)?

### References

- #1454

**Comment by monde** [comment]
Thanks @exitcode0 . Big picture I know have to come up with a robust ability to have proper change detection on the object represented by JSON and not the JSON string itself. We will have to look into the bugs you are seeing if we are able to settle change detection on JSON strings in an acceptable manner.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-602002

**Comment by exitcode0** [comment]
No StaleBot 🙂
