### ISSUE TITLE
Support IdP username filter in the okta_idp_oidc resource

### ISSUE THREAD

**Issue by thatguythat1031** [okta/terraform-provider-okta#1522]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform: 1.3.6
okta provider: 3.38

### Affected Resource(s)

okta_idp_oidc

### Problem

The okta_idp_oidc resource does not have a field to support the IdP username filter. 

This setting can be seen in the  in the authentication settings of the identity provider by checking the box to the right of filter, shown
![here:](https://user-images.githubusercontent.com/41173139/230957077-96b6bbc1-705c-44eb-a26f-791893720e6d.png)

It's also available in the IdP API as policy.subject.filter here: https://developer.okta.com/docs/reference/api/idps/#example. 

However, if you set a username filter using either the console or the API, then run terraform apply on that same IdP resource, the filter will be removed without the change showing in the terraform plan.

### Expected Behavior

The field should be supported on the terraform resource, or at least not be modified by terraform if it can't be changed by terraform.

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

Yes

**Comment by monde** [comment]
Thanks @thatguythat1031 we'll get this into our backlog to prioritize implementing this missing behavior that is documented in the the public management API.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-601995
