### ISSUE TITLE
`okta_policy_mfa` - sub-block structure

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1533]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`okta_policy_mfa` currently has each of the authenticators defined as attributes, the value of these attributes is a `map` containing values for `enroll` and `consent`
This is inconsistent to say `okta_app_group_assignments` where we use the `group` sub-block instead

Should `okta_policy_mfa` instead use sub-blocks for each authenticator with the blocks being called `authenticator` or `factor` for example?

This would make it somewhat more friendly to the `dynamic` syntax and modules
Currently if you wanted to make a module for `okta_policy_mfa` you would have to define the attributes for all possible authenticators ahead of time and then use `try()` or similar to fall back to `null` if input was omitted
The Module would also require an update if Okta ever added a new authenticators

If we instead use a `authenticator` sub-block, module authors could pipe the authenticators module input straight into a `dynamic` config block and wouldn't need to update their module if Okta ever releases a new authenticator type

Its worth calling out that I can't recall if a top level `for_each` will prevent defining `dynamic` sub-blocks - if this is the case then my module use-case likely falls apart
That said, I think its still worth making this consistent with other resources so that the `dynamic` syntax may be used on the authenticators for this resource
Terraform users may choose to still wrap the resource in a module to hard code allowed or forbidden values for the resource to enforce convention in their environment

This feature req would need to be a part of a major release as it would involve deprecating existing code

### New or Affected Resource(s)

- okta_policy_mfa

### Potential Terraform Configuration

Current workaround
```hcl
resource "okta_policy_mfa" "mfa_policies" {
  for_each = {for index, policy in local.mfa_policies: policy.name => policy}
  priority    = each.value.priority
  status      = each.value.status
  is_oie      = true
  name        = each.value.name
  description = each.value.description
  groups_included = each.value.groups_included

  webauthn = try({"enroll" = each.value.authenticators.webauthn}, null)
  okta_verify = try({"enroll" = each.value.authenticators.okta_verify}, null)
  okta_password = try({"enroll" = each.value.authenticators.okta_password}, null)
  okta_email = try({"enroll" = each.value.authenticators.okta_email}, null)
  phone_number = try({"enroll" = each.value.authenticators.phone_number}, null)
}
```

proposed config (written from memory, so likely wont pass validate without tweaking)
```hcl
resource "okta_policy_mfa" "mfa_policies" {
  for_each = {for index, policy in local.mfa_policies: policy.name => policy}
  priority    = each.value.priority
  status      = each.value.status
  is_oie      = true
  name        = each.value.name
  description = each.value.description
  groups_included = each.value.groups_included

  dynamic "authenticator" {
    for_each = each.value.authenticators
    iterator = authenticator
    content {
      name = authenticator.name
      enroll = authenticator.enroll
      consent = authenticator.consent
    }
  }
}
```

### References

- #0000

**Comment by monde** [comment]
Thanks @exitcode0 . We'll get this on the backlog to prioritize work. The config seems reasonable to me.
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-604154
