### ISSUE TITLE
`okta.appGrants.manage` Scope is missing from the valid scope list

### ISSUE THREAD

**Issue by asiyani** [okta/terraform-provider-okta#1535]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_app_oauth_api_scope

### Terraform Configuration Files

```hcl
resource "okta_app_oauth_api_scope" "example" {
  app_id = okta_app_oauth.example.id
  issuer = "https://org.okta.com"
  scopes = [
    "okta.appGrants.manage",
    "okta.apps.manage",
  ]
}
```

### Panic Output
```
Error: expected value to be one of 'okta.agentPools.manage', 'okta.agentPools.read', 'okta.apiTokens.manage', 'okta.apiTokens.read', 'okta.apps.manage', 'okta.apps.read', 'okta.authorizationServers.manage', 'okta.authorizationServers.read', 'okta.authenticators.manage', 'okta.authenticators.read', 'okta.behaviors.manage', 'okta.behaviors.read', 'okta.brands.manage', 'okta.brands.read', 'okta.captchas.manage', 'okta.captchas.read', 'okta.clients.manage', 'okta.clients.read', 'okta.clients.register', 'okta.deviceAssurance.manage', 'okta.deviceAssurance.read', 'okta.devices.manage', 'okta.devices.read', 'okta.domains.manage', 'okta.domains.read', 'okta.emailDomains.manage', 'okta.emailDomains.read', 'okta.emailServers.manage', 'okta.emailServers.read', 'okta.eventHooks.manage', 'okta.eventHooks.read', 'okta.events.read', 'okta.features.read', 'okta.factors.manage', 'okta.factors.read', 'okta.features.manage', 'okta.features.read', 'okta.groups.manage', 'okta.groups.read', 'okta.identitySources.manage', 'okta.identitySources.read', 'okta.idps.manage', 'okta.idps.read', 'okta.inlineHooks.manage', 'okta.inlineHooks.read', 'okta.linkedObjects.manage', 'okta.linkedObjects.read', 'okta.logStreams.manage', 'okta.logStreams.read', 'okta.logs.read', 'okta.networkZones.manage', 'okta.networkZones.read', 'okta.oauthIntegrations.manage', 'okta.oauthIntegrations.read', 'okta.orgs.manage', 'okta.orgs.read', 'okta.policies.manage', 'okta.policies.read', 'okta.principalRateLimits.manage', 'okta.principalRateLimits.read', 'okta.profileMappings.manage', 'okta.profileMappings.read', 'okta.pushProviders.manage', 'okta.pushProviders.read', 'okta.rateLimits.manage', 'okta.rateLimits.read', 'okta.realms.manage', 'okta.realms.read', 'okta.riskEvents.manage', 'okta.riskProviders.manage', 'okta.riskProviders.read', 'okta.roles.manage', 'okta.roles.read', 'okta.schemas.manage', 'okta.schemas.read', 'okta.sessions.manage', 'okta.sessions.read', 'okta.templates.manage', 'okta.templates.read', 'okta.threatInsights.manage', 'okta.threatInsights.read', 'okta.trustedOrigins.manage', 'okta.trustedOrigins.read', 'okta.users.manage', 'okta.users.read', 'okta.users.manage.self', 'okta.users.read.self', 'okta.userTypes.manage', 'okta.userTypes.read', got 'okta.appGrants.manage'
```
### Expected Behavior

`okta.appGrants.manage` & `okta.appGrants.read` should be allowed. 

#### Can this be done in the Admin UI?
Yes

#### Can this be done in the actual API call?

 I don't know

### Actual Behavior

terraform validation failed 

### Steps to Reproduce

1. `terraform apply`

### References

- complete list of scopes https://developer.okta.com/docs/api/oauth2/
- variable holding this list  https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_app_oauth_api_scope.go#L14

**Comment by monde** [comment]
Thanks @asiyani , we'll get this fixed in the next 3.x release. Just putting this out there, we are about to release 4.0.0 which removes these artificial input validations that the API will ultimately perform for itself.

Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-604153
