### ISSUE TITLE
`okta_app_oauth` : groups_claim ignored

### ISSUE THREAD

**Issue by the-nando** [okta/terraform-provider-okta#1536]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.4.5
on darwin_arm64
+ provider registry.terraform.io/okta/okta v3.46.0
```

### Affected Resource(s)

- okta_app_oauth

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    okta = {
      source  = "okta/okta"
      version = "3.46.0"
    }
  }
}

provider "okta" {
  org_name = "xxx"
  base_url = "okta.com"
}

resource "okta_app_oauth" "default" {
  label                     = "test-app"
  type                      = "web"
  consent_method            = "REQUIRED"
  grant_types               = ["authorization_code", "implicit"]
  hide_web                  = true
  issuer_mode               = "ORG_URL"
  login_mode                = "DISABLED"
  login_uri                 = "http://localhost"
  post_logout_redirect_uris = []
  redirect_uris             = "http://localhost"
  response_types            = ["code", "id_token"]
  groups_claim {
    type  = "FILTER"
    filter_type = "REGEX"
    value = "groups"
    name  = "^foo.*$"
  }
}
```

### Expected Behavior

groups_claim filter is imported as part of the resource. 

#### Can this be done in the Admin UI?

n/a

#### Can this be done in the actual API call?

Yes

### Actual Behavior

The state contains instead an empty list:
```
{
      "mode": "managed",
      "type": "okta_app_oauth",
      "name": "default",
      "provider": "provider[\"registry.terraform.io/okta/okta\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
[...]
            "enduser_note": "",
            "grant_types": [
              "authorization_code",
              "implicit"
            ],
            "groups": null,
            "groups_claim": [], <---- Empty list
            "hide_ios": true,
            "hide_web": true,
[...]
}
```

### Steps to Reproduce

1. Create an application with a groups claim filter
![Screenshot 2023-04-26 at 07 36 44](https://user-images.githubusercontent.com/89834752/234479194-33e07718-e70e-42f9-8e33-5e1b103786fc.png)
2. `terraform import okta_app_oauth.default  <client_id> `
3. The state is populated with the resource but the groups_claim is empty
4. `terraform plan`
```
  # okta_app_oauth.default will be updated in-place
  ~ resource "okta_app_oauth" "default" {
        id                         = "<client_id>"
        name                       = "oidc_client"
      + omit_secret                = false
      + skip_groups                = false
      + skip_users                 = false
        # (27 unchanged attributes hidden)

      + groups_claim {
          + filter_type = "REGEX"
          + name        = "groups"
          + type        = "FILTER"
          + value       = "^foo.*$"
        }
```

Similar issue can be seen by:
1. Creating an application without groups claim in Terraform (groups_claim = null)
2. Manually add the groups claim in the UI
3.  Re-run Terraform

**Comment by monde** [comment]
Thanks for the precise details to reproduce the bug @the-nando . Sounds like a bug to me, we'll get this onto our backlog.
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-606426

**Comment by monde** [comment]
This is on my current sprint
