### ISSUE TITLE
okta_policy_rule_mfa forces destroy/create when renaming policy mfa rule

### ISSUE THREAD

**Issue by Jinra** [okta/terraform-provider-okta#1538]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v1.4.5
on darwin_arm64
+ provider registry.terraform.io/okta/okta v3.46.0

### Affected Resource(s)

- `okta_policy_rule_mfa` (possibly other policy rules as well, but only tested mfa)

### Terraform Configuration Files

```hcl
resource "okta_policy_rule_mfa" "tf_policy_rule_mfa" {
  for_each  = var.mfa_rule_policies.resource.okta_policy_rule_mfa
  policy_id = var.policy_mfa_map["${each.key}"]
  name      = each.value.name
  status    = each.value.status
  enroll    = each.value.enroll
}
```

### Expected Behavior

Name change should have been an in place change

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

I don't know

### Actual Behavior

resources were planned to be destroyed and recreated
![image](https://user-images.githubusercontent.com/36873193/234718668-56c4012b-7f48-406f-bdd8-cd72ecf1846b.png)

### Steps to Reproduce

1. Create or import a resource for policy rule mfa
2. Change the name of the rule
3. Run `terraform plan`

### Important Factoids

This was worked around by renaming the rule in GUI to match the resource in TF configuration files. Running `terraform plan` after this showed no configuration changes.

### References

- #0000

**Comment by monde** [comment]
Thanks @Jinra we'll get this on to our backlog and take a look.
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-606423
