### ISSUE TITLE
Problems with the install/setup

### ISSUE THREAD

**Issue by trijohn** [okta/terraform-provider-okta#1546]
Hello, I am trying to setup this provider on my local MAC and am running into issues.
Following the instructions, I installed GO. I then tried to get the repository from github using the following command:

git clone git@github.com:okta/terraform-provider-okta.git

and it basically said i did not have access. Then downloaded via HTTPS and put in the required directory.
I was able to run make tools but when i tried to run make build - failed with the following message:

make: gofumpt: No such file or directory
make: *** [fmtcheck] Error 1

not sure if it matters but there is nothing defined for $GOPATH

Thoughts?

background:

My end goal is to integrate with Terraform Cloud and automate application creation via Service Now, so - i want to make sure i understand what does and what does not require CLI?

Anyway to put the code in my own github repository? Also, how would I init the Okta provider? is that only via CLI?

Thanks,

John

**Comment by monde** [comment]
@trijohn we need to update the README but I think this is what you need for your clone: `git clone https://github.com/okta/terraform-provider-okta.git`
That said, when you say install, are you looking to check out the code so you can hack on it? Or are you looking to install the provider to run with a TF config you are working on?

**Comment by trijohn** [comment]
Hi Mike, I was looking to use it but don’t think I need it anymore. I have a GitHub and terraform setup that is working. I appreciate you getting back to me. Thank you,JohnOn May 9, 2023, at 8:33 AM, Mike Mondragon ***@***.***> wrote:﻿
@trijohn we need to update the README but I think this is what you need for your clone: git clone https://github.com/okta/terraform-provider-okta.git
That said, when you say install, are you looking to check out the code so you can hack on it? Or are you looking to install the provider to run with a TF config you are working on?
