### ISSUE TITLE
Support Okta IGA resources

### ISSUE THREAD

**Issue by omelnyk1** [okta/terraform-provider-okta#1557]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi guys 👋

Do you have any plans to support resources of Okta IGA (Identity Governance and Administration)?
It would be nice to have it.
The API link available below in References.

Thank you.

### References

[Okta Identity Governance API](https://developer.okta.com/docs/api/iga/)

**Comment by jefftaylor-okta** [comment]
Hey @omelnyk1! Thanks for the request! We definitely do have plans to support Okta's Identity Governance product. We have been following the team's progress intently. We don't like to commit to supporting Beta APIs as the contracts on these new APIs may change. But look for more updates as this API goes GA! 😄

**Comment by omelnyk1** [comment]
Thank you for reply. That's clear 👍

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-612967

Looking for suggestions: Support IGA in Okta Core (this provider) TF provider or have new Okta IGA TF provider

**Comment by ollytheninja** [comment]
Just wondering if there's any update on this @monde ?
