### ISSUE TITLE
okta_app_user profile attribute, ends up with unwanted diffs

### ISSUE THREAD

**Issue by Reflejo** [okta/terraform-provider-okta#1565]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When updating the `profile` of an `okta_app_user`, it's not possible to ignore the attributes that are mapped, therefore there is a diff on every terraform plan. For example:

```hcl
resource "okta_app_user" "google_workspace" {
  app_id   = okta_app_saml.google_workspace.id
  user_id  = okta_user.employees.test.id
  username = "martin@something.io"
  profile = jsonencode(
    {
      emailAliases = ["test"]
    }
  )
```

ends up with

```diff
  # okta_app_user.google_workspace["martin@something.io"] will be updated in-place
  ~ resource "okta_app_user" "google_workspace" {
        id                  = "dasodasji"
      ~ profile             = jsonencode(
          ~ {
              - addressesWorkCountryCode    = null
              - addressesWorkLocality       = null
              - addressesWorkPostalCode     = null
              - addressesWorkRegion         = null
              - addressesWorkStreetAddress  = null
              + emailAliases                = ["test"]
              - emailsOtherAddress          = null
              - emailsWorkAddress           = null
              - licenses                    = null
              - nameFamilyName              = "Martin"
              - nameGivenName               = "Conte"
              - orgUnitPath                 = "/"
              - organizationsWorkCostCenter = null
              - organizationsWorkDepartment = null
              - organizationsWorkName       = null
              - organizationsWorkTitle      = "Some title"
              - phonesWorkMobileValue       = null
              - phonesWorkValue             = "321321321"
              - relationsManagerValue       = "whatevs"
              - unassignmentConfig          = null
                # (3 unchanged attributes hidden)
            }
        )
        # (5 unchanged attributes hidden)
    }
```

Is there any way to ignore the attributes that are mapped?

**Comment by monde** [comment]
Similar to #1454 we need to implement change detection on JSON values. You can count on the JSON that the operator sets in a resource to be different character by character than the JSON coming back from the API although they are equivalent JSON objects.

Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-579444

**Comment by Reflejo** [comment]
@monde I don't think that's the case in my example. Because for the fields that are mapped, terraform state in fact has a different value set compared to upstream (since those values in the profile are sync'ed with the okta user's profile). So I think even if JSON drift is properly calculated, in my case you'd still see a diff, right? Or am I misunderstanding what you said?

**Comment by monde** [comment]
imo, it's complications from allowing the convenience and flexibility of setting `profile` as JSON . First the different strings of equivalent objects. Also with you, it seems like you are setting one item on profile but in fact the API will return everything in the profile. Perhaps there needs to be a list of attributes that should be monitored for change something like `profile_attributes = [ "emailAliases" ]` and ignore the rest. Because profile is so expensive we exposed it as JSON. You could lifecycle ignore the profile as well.

**Comment by Reflejo** [comment]
@monde I guess I can modify https://github.com/okta/terraform-provider-okta/pull/1566 slighly to take the keys in the profile as the allow list and ignore the rest?

**Comment by Reflejo** [comment]
Is there any news with this @monde ? I hit this every day when I modify anything on terraform

**Comment by Reflejo** [comment]
That change did not fix my issue, I'm still seeing all unwanted diffs / changes using custom profile

**Comment by monde** [comment]
@Reflejo just checking, you are using the v4.5.0 release of the provider? Please open a new issue and give us as much detail as you can so we can attempt to reproduce error you are seeing now. Preferably sample terraform config and a copy/paste of the error you are seeing.
