### ISSUE TITLE
terraform import okta_user_schema_property issue

### ISSUE THREAD

**Issue by tduong10101** [okta/terraform-provider-okta#1575]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

4.0.0

### Affected Resource(s)

- okta_user_schema_property

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

```
resource "okta_user_schema_property" "test"{
    index = "test"
    title = "test"
    type = "string"
    description = "testing tf schema"
    scope = "NONE"
    permissions = "READ_ONLY"
    master = "PROFILE_MASTER"
    user_type = "default"
}
```

### Expected Behavior

Import command should finish succesfully

### Actual Behavior

Run the below import command would throw below error

`terraform import okta_user_schema_property.test #custom.test`

`Error: failed to get user custom schema property: failed to get user type: json: cannot unmarshal array into Go value of type sdk.UserType`

### Steps to Reproduce

1. `terraform import okta_user_schema_property.test #custom.test`

### Important Factoids

NA

### References

Might be similar to this case: 

- #0000

**Comment by duytiennguyen-okta** [comment]
@tduong10101 Did this issue happened in the previous version of the tf provider?

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-616644

**Comment by tduong10101** [comment]
Hi @duytiennguyen-okta, 
Thanks for looking into this, sorry for the late response! 
I tested the import command on provider version 3.34 and 4.0.0. Both are having the same issue.
I found that by create a schema resource with same "index/title" of an existing schema on okta, Terraform would just go ahead a use the existing schema and returned with created schema successfully.
I think the expected behavior should be:
- Create a duplicate schema with same "index/title". As the new schema is not imported to Terraform tfstate yet.
- OR throw an error saying the schema with same "index/title" is existed in okta. So we are then force to either use import command or use a different "index/title".

Let me know if you'd like me to raise a different issue for the above behavior issue.
Regards,
Terry

**Comment by tduong10101** [comment]
closing off this issue as we've found the correct import command would be just
$ terraform import okta_user_schema_property.example <variableName>
even for custom schemas under default user
I'll raise a separate issue for terraform use existing schema instead of create a new one

**Comment by duytiennguyen-okta** [comment]
Thanks @tduong10101
