### ISSUE TITLE
iframe embed scope in trusted origin

### ISSUE THREAD

**Issue by venkatakanupuru** [okta/terraform-provider-okta#1581]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_xxx

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

Hi Team,

For configuring a trusted origin, resource "okta_trusted_origin"  I am able to configure the trusted origin with no issues. For scopes redirect and CORS. How ever the iFrame embed scope is not present. 

Steps for manually configure trusted origin:
OKTA Admin UI >> Security >> API >> Trusted Origins >> Add Origin

example usage : 
resource "okta_trusted_origin" "example" {
  name   = "example"
  origin = "https://example.com"
  scopes = ["CORS"]
}

scopes - (Required) Scopes of the Trusted Origin - can be "CORS" and/or "REDIRECT".

Can you please help in including the iframe embed.

Thank you
Venkata

<img width="885" alt="image" src="https://github.com/okta/terraform-provider-okta/assets/66885752/d53ac980-1fbd-4922-8b3c-7480a627762a">

**Comment by duytiennguyen-okta** [comment]
@venkatakanupuru do you know which version of tf provider is this? We have remove the validation in the v4 of the tf provider

**Comment by venkatakanupuru** [comment]
Hi @duytiennguyen-okta

The TF provider version i am using is 3.36.0.

Update : 
The documentation needs to be updated on the TF page as the scopes should also include IFRAME_EMBED as one of them. I just manually configured from Okta UI and imported the resource to TF script to check what scopes come up and the scope is included. 

scopes = [
        "IFRAME_EMBED",
    ]
 
Thank you,
Venkata

**Comment by hosvr** [comment]
can we get the documentation updated in order to show this value?
