### ISSUE TITLE
Set jwks-uri on 

### ISSUE THREAD

**Issue by mcrobbj** [okta/terraform-provider-okta#1583]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Can you add jwks_uri as this is available on the API, this would allow binding to the URI location of the public key, which allows for more dynamic configuration

### New or Affected Resource(s)

- okta_app_oauth

### Potential Terraform Configuration

https://developer.okta.com/docs/reference/api/apps/#settings-10
API supports:
jwks_uri - URL string that references a JSON Web Key Set (opens new window)for validating JWTs presented to Okta.

Currently you have to bind it
  jwks {
    kty = "RSA"
    kid = "SIGNING_KEY"
    e   = "AQAB"
    n   = "xyz"
  }
}

Where n is the private key

```hcl
resource "okta_app_oauth" "example" {
  label          = "example"
  type           = "service"
  response_types = ["token"]
  grant_types    = ["client_credentials"]
  token_endpoint_auth_method = "private_key_jwt"

  jwks_uri = "https://myjwks"
```

### References

- #0000
jwks_uri	URL string that references a [JSON Web Key Set (opens new window)](https://tools.ietf.org/html/rfc7517#section-5)for validating JWTs presented to Okta.

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-616651

**Comment by duytiennguyen-okta** [comment]
This is fixed in the release [4.0.3](https://github.com/okta/terraform-provider-okta/releases/tag/v4.0.3) from https://github.com/okta/terraform-provider-okta/pull/1608

**Comment by clementdenis** [comment]
The fix does not seem to work:
- When setting `token_endpoint_auth_method = "private_key_jwt"` with jwks_uri, I'm getting the error `Error: failed to create OAuth application: 'jwks' is required when 'token_endpoint_auth_method' is 'private_key_jwt'`
- I checked [the example](https://github.com/okta/terraform-provider-okta/pull/1608/files#diff-7b037e3158af42bf108c8a67afb0e94b14c694337aa7e1e8d659e3912fbeb1f7), and it does not set a token_endpoint_auth_method value => when I do the same, I end up with an application with `client_secret_basic` auth, which is obviously not what I want ...

I suppose you just need to change the validation here:
https://github.com/okta/terraform-provider-okta/blob/d0eb8488b0f28bc6f0a3e24625ef16f3ba95e7d8/okta/resource_okta_app_oauth.go#L846-L848 

The test should also be updated to test the actual application, not the TF state:
https://github.com/okta/terraform-provider-okta/blob/ec3fc925089c2383f3226747fd9020d217cad54f/okta/resource_okta_app_oauth_test.go#L302-L305

**Comment by clementdenis** [comment]
@monde Should I open a new ticket for this, or will you reopen this one?

**Comment by exitcode0** [comment]
@monde I think this one closed out when stalebot ran next after my most recent PRs - not sure if this one should actually be closed out, looks like @clementdenis was still having some issues?

**Comment by clementdenis** [comment]
It works fine with the latest release !

**Comment by monde** [comment]
Thanks @clementdenis . @virgofx do you call this one done also?

**Comment by virgofx** [comment]
Yep, confirm closing this as resolved via https://github.com/okta/terraform-provider-okta/pull/1649
