### ISSUE TITLE
okta provider v4.0.1 is missing in terraform registry

### ISSUE THREAD

**Issue by suhasgaddam-trueaccord** [okta/terraform-provider-okta#1589]
Hi, I've noticed that v4.0.1 is missing in the terraform registry, as of right now. Is there a secondary step that needs to happen to publish to the terraform registry?

https://registry.terraform.io/providers/okta/okta/latest

**Comment by danpeckardt** [comment]
We're having the same issue trying to upgrade to v4.0.1. When will this version be published to the registry?

**Comment by duytiennguyen-okta** [comment]
We are waiting for terraform to update their registry

**Comment by duytiennguyen-okta** [comment]
Terraform has update their registry to 4.0.1 https://registry.terraform.io/providers/okta/okta/latest/docs
