### ISSUE TITLE
Import okta_auth_server_scope crashed

### ISSUE THREAD

**Issue by johnhurst-redenergy** [okta/terraform-provider-okta#1590]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.3.2
on linux_amd64
+ provider registry.terraform.io/okta/okta v4.0.0

### Affected Resource(s)

- okta_auth_server_scope

(+others?)

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

An error message saying the auth server / scope is invalid.

#### Can this be done in the Admin UI?

N/A

#### Can this be done in the actual API call?

N/A

### Actual Behavior

```bash
module.redenergy_dev.okta_auth_server_scope.cdr-biza: Importing from ID "scp2puknka9k4e3ZW3l7"...
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ImportResourceState call. The plugin logs may contain more details.
╵

╷
...


Error: The terraform-provider-okta_v4.0.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
### Steps to Reproduce

Enter an invalid import for okta_auth_server_scope (should have auth server ID/scope ID, not just scope ID as last argument):

```bash
terraform import module.mymodule.okta_auth_server_scope.scope_name scp2puknka9k4e3ZW3l7
```

**Comment by duytiennguyen-okta** [comment]
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/auth_server_scope
The format to import okta_auth_server_scope is terraform import okta_auth_server_scope.example auth_server_id/scope_id
Please reopen if this does not resolve your issue

**Comment by johnhurst-redenergy** [comment]
Sure, the correct format worked fine. I just thought I'd mention this behaviour since Terraform says "This is always indicative of a bug within the plugin.", and it would be nice if the plugin did not crash. But no worries, thanks for your attention.
