### ISSUE TITLE
`diffsupressfunc` - `okta_app_group_assignments.profile`

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1597]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
`okta_app_group_assignments` uses `group` sub-blocks, each of these defines a json `profile` attribute - this attribute lacks `diffsupressfunc` meaning that perpetual drift is possible in certain scenarios
The scenario i'm currently encountering is that the Okta api treats json attribute values of `"true"` (string) and `true` (bool) as equivalent but ultimately normalises them to strings before storing
This means that if you have `attr = true` in the json group assignment profile, you will experience perma-drift as terraform attempts to correct the read value of `attr = "true"` back to the configured value of `attr = true` despite these being functionally equivalent 

### New or Affected Resource(s)

- okta_app_group_assignments

### Potential Terraform Configuration

```hcl
resource "okta_app_group_assignments" "example" {
  app_id = okta_app_saml.example.id
  group {
    id = data.okta_groups.example_group.id
    profile = jsonencode({
      admin = "true" # no perma drift
      admin = true   # causes perma drift
    })
  }
}

```

### References

- A similar diffsupressfunc issue #1518

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-620357

**Comment by duytiennguyen-okta** [comment]
@MikeMondragon-okta @monde This could be a good stepping stone to bring in the tf plugin frameworks
