### ISSUE TITLE
Failure on undocumented okta_group_rules status "INVALID"

### ISSUE THREAD

**Issue by tgoodsell-tempus** [okta/terraform-provider-okta#16]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform 0.12.20

### Affected Resource(s)

*  okta_group_rule

### Terraform Configuration Files

```hcl
resource "okta_group_rule" "parent_assignments" {
  name              = "00g2zzwlxcyz77tF0297:<redacted>"
  group_assignments = ["00g2zym3chkeQFWKi297"]
  expression_type   = "urn:okta:expression:1.0"
  expression_value  = "isMemberOfGroup(\"00g2zzwlxcyz77tF0297\")"
}

```

### Debug Output

https://gist.github.com/tgoodsell-tempus/07211d3c4e79649c3d29a7c609544adc

### Expected Behavior

This is not "expected", however the status "INVALID" is undocumented, in that I could not find a reference to it in the [okta group rules reference](https://developer.okta.com/docs/reference/api/groups/#group-rule-operations).

The "INVALID" status seems to occur when the one or more of the groups in the group_assignments section is deleted, this is accompanied with the following status in the object metadata:
JSON Response of GET on group rule: `'allGroupsValid': False`

An invalid rule can only be deleted, as it's no longer allowed to be change or cycled using the update, activate, and deactivate ops. Generally, I've seen this occur for us when a group manually managed or managed separately was deleted before the rule could be dealt with accordingly.

IMO the behavior should follow the "terraform taint" behavior, in that the rule is deleted and then dealt with according to the contents of the TF code.

I'm not sure of the specific "best practice" of how to deal with this type of situation from a terraform standpoint, as I was attempting to remove/delete the rule in my example here.

### Actual Behavior

The API validation failed during the `updateRuleStatus` operation, as there is no handling ready for when the status is returned as "INVALID".

### Steps to Reproduce

1. Create valid `okta_group_rule` resource.
2. Delete the group which is being assigned in the "group_assignments" field. 
3. Attempt to modify the resource (update or delete).

### Important Factoids

We're more prone to this occurring as the vast majority of the groups we use are either "legacy" (non-terraform managed) or mastered in a separate base module + state. Therefore our rules are tied to calling the data.okta_group resources to validate + get necessary information.

### References

https://www.terraform.io/docs/providers/okta/r/group_rule.html

https://gist.github.com/tgoodsell-tempus/07211d3c4e79649c3d29a7c609544adc

https://developer.okta.com/docs/reference/api/groups/

**Comment by ymylei** [comment]
I'm going to PR a fix for this based on some similar patterns I've seen
