### ISSUE TITLE
Add `name` attribute to brand data source and resource

### ISSUE THREAD

**Issue by monde** [okta/terraform-provider-okta#1604]
The [`name`](https://developer.okta.com/docs/api/openapi/okta-management/management/tag/Customization/#tag/Customization/operation/getBrand!c=200&path=name&t=response) attribute should be surfaced in the Okta Management API and is available in v3 okta-sdk-golang . This will allow operators to create a selector in their config to select a brand from the brands data source based on a comparison of a brand's name.

/cc @duytiennguyen-okta @ClintonianSunBlaster

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-621580

**Comment by duytiennguyen-okta** [comment]
This is fixed in the release [4.0.3](https://github.com/okta/terraform-provider-okta/releases/tag/v4.0.3) from https://github.com/okta/terraform-provider-okta/pull/1605
