### ISSUE TITLE
okta_email_domain: resource block returns empty list for the `dns_validation_records` -> `values` attributes reference

### ISSUE THREAD

**Issue by bigfantech** [okta/terraform-provider-okta#1612]
Arguments Reference `dns_validation_records` -> `values` returns empty list. Thus can't create DNS records, for example in Route53, with Terraform itself.

```
dns_validation_records = tolist([
    {
      "expiration" = ""
      "fqdn" = "_oktaverification.adomain.com"
      "record_type" = "TXT"
      "values" = tolist([])
    },
    {
      "expiration" = ""
      "fqdn" = "mail.adomain.com"
      "record_type" = "cname"
      "values" = tolist([])
    },
    {
      "expiration" = ""
      "fqdn" = "k09._domainkey.adomain.com"
      "record_type" = "cname"
      "values" = tolist([])
    },
    {
      "expiration" = ""
      "fqdn" = "k092._domainkey.adomain.com"
      "record_type" = "cname"
      "values" = tolist([])
    },
  ])
  "domain" = "adomain.com"
  "id" = "abc123"
  "user_name" = "noreply"
  "validation_status" = "VERIFIED"
}
```

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v1.4.6

### Affected Resource(s)

- okta_email_domain

### Terraform Configuration Files

```hcl
data "okta_brands" "all" {
}

resource "okta_email_domain" "this" {
  brand_id     = tolist(data.okta_brands.all.brands)[1].id
  domain       = "adomain.com"
  display_name = "noreply"
  user_name    = "noreply"
}
```

### Debug Output

https://gist.github.com/bigfantech/d9695fd7ffda1778560fd0b35231c309

### Expected Behavior

Arguments Reference `dns_validation_records` `values` must contain values.

dns_validation_records = tolist([
    {
      "expiration" = ""
      "fqdn" = "_oktaverification.adomain.com"
      "record_type" = "TXT"
      "values" = tolist(["abc123"])
    },
    {
      "expiration" = ""
      "fqdn" = "mail.adomain.com"
      "record_type" = "cname"
      "values" = tolist(["def123"])
    },
    {
      "expiration" = ""
      "fqdn" = "k09._domainkey.adomain.com"
      "record_type" = "cname"
      "values" = tolist(["ghi123"])
    },
    {
      "expiration" = ""
      "fqdn" = "k092._domainkey.adomain.com"
      "record_type" = "cname"
      "values" = tolist(["xyz123"])
    },
  ])
  "domain" = "dev.daphnetechplatform.io"
  "id" = "OeD82[642](https://gitlab.com/daphnetech/devops/iac/layers/application/-/jobs/4548660299#L642)4mwC1stjf417"
  "user_name" = "noreply"
  "validation_status" = "VERIFIED"
}

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

I don't know

### Actual Behavior

Arguments Reference `dns_validation_records` `values` returns empty list.

dns_validation_records = tolist([
    {
      "expiration" = ""
      "fqdn" = "_oktaverification.adomain.com"
      "record_type" = "TXT"
      "values" = tolist([])
    },
    {
      "expiration" = ""
      "fqdn" = "mail.adomain.com"
      "record_type" = "cname"
      "values" = tolist([])
    },
    {
      "expiration" = ""
      "fqdn" = "k09._domainkey.adomain.com"
      "record_type" = "cname"
      "values" = tolist([])
    },
    {
      "expiration" = ""
      "fqdn" = "k092._domainkey.adomain.com"
      "record_type" = "cname"
      "values" = tolist([])
    },
  ])
  "domain" = "adomain.com"
  "id" = "abc123"
  "user_name" = "noreply"
  "validation_status" = "VERIFIED"
}

### Steps to Reproduce

1. `terraform apply`

### References

- #1537

**Comment by duytiennguyen-okta** [comment]
This is fixed in the release [4.0.3](https://github.com/okta/terraform-provider-okta/releases/tag/v4.0.3) from https://github.com/okta/terraform-provider-okta/pull/1609. We are still waiting for the TF registry to be updated so look out for that
