### ISSUE TITLE
Resource `okta_policy_rule_profile_enrollment`  does not allow managing scopes

### ISSUE THREAD

**Issue by AaronFriel** [okta/terraform-provider-okta#1624]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

- okta_policy_rule_profile_enrollment

Originally reported by a Pulumi user here:
- https://github.com/pulumi/pulumi-okta/issues/346

### Description

After creating an `okta_policy_rule_profile_enrollment`, performing a `GET` on `/api/v1/policies/:policyId/rules` returns scopes like below. 

```
...
     "actions": {
            "profileEnrollment": {
                "access": "ALLOW",
                "preRegistrationInlineHooks": [
                    {
                        "inlineHookId": "valid-hook-id",
                        "scopes": [
                            "SELF_SERVICE_REGISTRATION"
                        ]
                    }
                ],
                "profileAttributes": [
                    {
                        "name": "email",
                        "label": "Primary Email",
                        "required": true
                    }
                ],
                "targetGroupIds": null,
                "unknownUserAction": "DENY",
                "activationRequirements": {
                    "emailVerification": true
                },
                "uiSchemaId": "valid-schema-id",
                "progressiveProfilingAction": "ENABLED"
            }
        },
...
```

However, on opening the Okta admin console, this configuration changes scopes to `["PROGRESSIVE_PROFILING"]` without any action taken by the user except clicking save.

The user in this case would like to manage scopes, but I am out of my depth on understanding the Okta API here and what these scopes mean. :) Any advice would be helpful to our mutual users! See the Pulumi issue linked above for more context.

**Comment by rodriguesgm** [comment]
Just to make sure, the flag `"progressiveProfilingAction": "ENABLED"` is also not present when creating the resource via Pulumi/TF. It's only added in the policy after doing the edit/save in the UI without changing anything

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-626964

**Comment by duytiennguyen-okta** [comment]
@rodriguesgm I cannot reproduce this issue in the 4.5.0 provider with your description. Can you provide the log of what happened with `TF_LOG=debug terraform apply` or shoot a video on what happened?

**Comment by duytiennguyen-okta** [comment]
Closing due to no response. Feel free to open it back up if the issue still persists
