### ISSUE TITLE
Email Customisations no longer support load from file

### ISSUE THREAD

**Issue by mcrobbj** [okta/terraform-provider-okta#1625]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_email_customization

### Terraform Configuration Files

```hcl
resource "okta_email_customization" "forgot_password_en" {
  brand_id      = okta_brand.example.id
  template_name = "ForgotPassword"
  language      = "en"
  is_default    = true
  subject       = "Account password reset"
body          = "Hola $$user.firstName,"
}
```

This means you have to escape large html files as a string.
The previous implementation okta_template_email used to allow you to read it from a file

template = file("orgotPassword.html")

and the resource okta_template_sms still works in this way.

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by duytiennguyen-okta** [comment]
@mcrobbj so is the file is not being read (in your example missing the f of the forgotpassword). Or are you saying the file is being read but does not escape correctly?

**Comment by monde** [comment]
Seems like a syntax error

~~`template = file("orgotPassword.html")`~~

`template = file("forgotPassword.html")`

Please reopen if more details can be given.
