### ISSUE TITLE
Causes: errorSummary: ''rotation_type'' is required. Not documented in terraform

### ISSUE THREAD

**Issue by mcrobbj** [okta/terraform-provider-okta#1629]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
      version = "4.1.0" introduces this we are OK with 3.46

### Affected Resource(s)

- okta_app_oauth

### Terraform Configuration Files

```hcl
resource "okta_app_oauth" "test" {
  label                      = "AML"
  type                       = "test"
  grant_types                = ["authorization_code", "refresh_token"]
  redirect_uris              = ["https://oauth.pstmn.io/v1/browser-callback", "https://www.thunderclient.io/oauth/callback", var.redirect]
  response_types             = ["code"]
  # Note have to explicitly set to false as automatically setting 
  pkce_required              = false
}
```

### Panic Output

│ Error: failed to create OAuth application: the API returned an error: Api validation failed: App Instance. Causes: errorSummary: ''rotation_type'' is required.

### Actual Behavior

This fails, if its a mandatory field then document it, and what the valid values are.

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by duytiennguyen-okta** [comment]
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-626970

**Comment by MurrayGill** [comment]
Note: issue appears to be related to refresh token rotation.  Adding the following parameters works around the issue:
  refresh_token_rotation     = "ROTATE"
  refresh_token_leeway       = 30

Presumably refresh_token_rotation = "STATIC" or a different refresh_token_leeway value would also work

**Comment by dmsolutionsmn** [comment]
Just tried `refresh_token_rotation = "STATIC"` and it works.  We didn't need to add this in the past as it would default to `STATIC` in the past.

**Comment by Shocktrooper** [comment]
I just ran into this as well with 4.1.0

**Comment by polymorcodeus** [comment]
It's non-nullable according to the API docs - https://developer.okta.com/docs/reference/api/apps/#refresh-token-object

So presumably just need to add validation or default to `STATIC` as previous behavior if grant_type includes `refresh_token`

**Comment by duytiennguyen-okta** [comment]
Close with #1738
