### ISSUE TITLE
Okta Brands API has exposed create brand, TF provider should be updated

### ISSUE THREAD

**Issue by monde** [okta/terraform-provider-okta#1630]
When the brands API was released it did not include a create method for brands. The TF provider’s brand resource was created just after the API was released. Since then, the API has exposed a create brands endpoint https://developer.okta.com/docs/api/openapi/okta-management/management/tag/Customization/#tag/Customization/operation/createBrand

The Okta Terraform Provider should be updated accordingly.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-626985

**Comment by duytiennguyen-okta** [comment]
Closed with #1677
