### ISSUE TITLE
metadata_url attribute doesn't return the proper value

### ISSUE THREAD

**Issue by ruzickap** [okta/terraform-provider-okta#1632]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```bash
❯ terraform -v
Terraform v1.5.2
on darwin_amd64
+ provider registry.terraform.io/okta/okta v4.0.2
```

### Affected Resource(s)

- okta_app_saml

### Actual Behavior

I would like to get the "SAML xml metadata URL" using `metadata_url` attribute. 
When I use `okta_app_saml.my_okta_app.metadata_url` I'm getting the different URL which looks different `https://exxxxxx3-mxxxd-us.okta.com/api/v1/apps/0xxxxxxxxxxxxxxxxxx7/sso/saml/metadata?kid=Oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc` comparing to what I can see in Okta GUI.

In the Okta GUI I can see "Metadata URL" with "correct" format:
![image](https://github.com/okta/terraform-provider-okta/assets/1434387/d1fa9cd7-2f03-4e16-9a14-8eb31cc32835)

I'm not sure if this is a bug or missing feature, but is there a proper way how to "extract"" the Metadata URL mentioned on the screenshot.

Thank you

**Comment by monde** [comment]
Note to self:
Instead of hand crafting the URL:
https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_app_saml.go#L494-L495
```go
		_ = d.Set("metadata_url", fmt.Sprintf("%s/api/v1/apps/%s/sso/saml/metadata%s",
			getOktaClientFromMetadata(m).GetConfig().Okta.Client.OrgUrl, d.Id(), q))
```
it should probably be set from the links data
```go
  _ = d.Set("metadata_url", linksValue(app.Links, "metadata", "href"))
```
from looking at how the API presents it in the response:
https://developer.okta.com/docs/reference/api/apps/#response-example-3

cc: @duytiennguyen-okta

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-628099

**Comment by monde** [comment]
@arvindkrishnakumar-okta fyi
