### ISSUE TITLE
Unable to Create/Update IdP Authenticator

### ISSUE THREAD

**Issue by emanor-okta** [okta/terraform-provider-okta#1633]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.4.6
on darwin_amd64
+ provider registry.terraform.io/okta/okta v3.41.0

### Affected Resource(s)

- okta_authenticator

### Terraform Configuration Files

```hcl
resource "okta_authenticator" "duo_idp" {
  name     = "DUO-MFA-ONLY"
  key      = "external_idp"
  provider_json = jsonencode(
  {
        "type": "CLAIMS",
        "configuration": {
            "idpId": "0oa1qd4m68G3QcAfv1d7"
        }
  }
  )
}
```

### Debug Output

https://gist.github.com/emanor-okta/0cae00d5a4cef74229d1a9a90180f3ef

```
│ Error: failed to update authenticator: the API returned an error: Api validation failed: provider.configuration.idpId. Causes: errorSummary: provider.configuration.idpId: The field cannot be left blank
│ 
│   with okta_authenticator.duo_idp,
│   on main.tf line 33, in resource "okta_authenticator" "duo_idp":
│   33: resource "okta_authenticator" "duo_idp" {
│ 
╵
```

### Expected Behavior

The IdP Authenticator is *created if creating for the first time, or is updated to use a new OIDC/SAML IdP provided in the `idpId` attribute.

* Note because of the way Authenticators work if an IdP Authenticator type has already been added to the Org and then deleted it does not really get deleted, instead it is marked as inactive. Because of this testing in a Org that previously had an IdP Authenticator configured will give incorrect results when testing the create functionality. The SDK will check id an IdP Authenticator has been previously setup, if so will not attempt to create a new one (which would show the bug), but rather use the returned Authenticator. 
https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_authenticator.go#L162

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

Yes
```
curl --location --request PUT 'https://domain.oktapreview.com/api/v1/authenticators/aut3wx2513aJbq87J1d7' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: SSWS ...' \
--data-raw '{  
    "name": "DUO-MFA-ONLY",
    "provider": {
        "type": "CLAIMS",
        "configuration": {
            "idpId": "0oa7dnjyru1jOrCsp1d7"
        }
    }
}'
```

### Actual Behavior

If the IdP Authenticator type has never been configured in the Org, or trying to update an existing IdP Authenticator with a new IdP ID will get an error.

https://github.com/okta/terraform-provider-okta/blob/master/sdk/v2_authenticatorProviderConfiguration.go#L5
needs to expose `idpId`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This is only relevant for OIE Orgs

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://github.com/okta/terraform-provider-okta/issues/1633
