### ISSUE TITLE
Add an okta app policy assignment similar to `okta_app_group_assignment`

### ISSUE THREAD

**Issue by adantop** [okta/terraform-provider-okta#1641]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To be able to give flexibility of configuration for different teams, we would like to have a new resource similar to [`okta_app_group_assignment`](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_group_assignment) that manages the application sign on policy assignment.

With this, an application can be created and configured in the UI while the authentication policy is in Terraform.

### New or Affected Resource(s)

- okta_app_policy_assignment

### Potential Terraform Configuration

```hcl
resource "okta_app_policy_assignment" "my_app_policy_assignment" {
  app_id = data.okta_app_saml.myapp.id
  policy_id = okta_app_signon_policy.id
}
```

### References

The Okta API supports this by issuing the following request:

```http
PUT /api/v1/apps/{{appId}}/policies/{{policyId}}
```

- #0000

**Comment by adantop** [comment]
I made a PR with a demo of how it could work.

https://github.com/okta/terraform-provider-okta/pull/1646

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-631366
