### ISSUE TITLE
Ability to add additional JWKS to an OIDC App

### ISSUE THREAD

**Issue by mcrobbj** [okta/terraform-provider-okta#1647]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

You can only add a single JWKS key to an app which means it you are doing key rotation and want to have multiple keys present during the rotation you have to add the key manually.

We probably want to remove the key from the okta_app_oauth so we can more easily remove old keys just by removing the associated resource.

A seperate okta_app_oauth_jwks supports better lifecycle management of keys.

### New or Affected Resource(s)

- okta_app_oauth

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
    resource "okta_app_oauth_jwks" "example" {
      kty = "RSA"
      kid = "SIGNING_KEY"
      e   = "AQAB"
      n   = "xyz"
  }


```

### References

- #0000

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-633513

**Comment by duytiennguyen-okta** [comment]
@mcrobbj I am closing this as we already support multiple jwks in okta_app_oauth. So something like this should work for create, update and delete

```
resource "okta_app_oauth" "example" {
  label          = "example"
  type           = "service"
  response_types = ["token"]
  grant_types    = ["client_credentials"]
  token_endpoint_auth_method = "private_key_jwt"

  jwks {
    kty = "RSA"
    kid = "SIGNING_KEY"
    e   = "AQAB"
    n   = "xyz"
  }
  jwks {
    kty = "EC"
    kid = "SIGNING_KEY2"
  }
}
```
