### ISSUE TITLE
Brand 'name' was introduced in 4.0.3 but isn't user configurable

### ISSUE THREAD

**Issue by csanders-git** [okta/terraform-provider-okta#1657]
### Terraform Version

v1.5.4 - Provider version 4.1.0

### Affected Resource(s)

okta_brand

### Terraform Configuration Files

```hcl
# Bug in Okta Auth provider
resource "okta_brand" "x_footer" {
  remove_powered_by_okta = true
  name                   = "Test Brand Name #1"
}
```

### Expected Behavior

Applies brand name and/or overrides default/existing value

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

Yes

### Actual Behavior

```
│ Error: Value for unconfigurable attribute
│ 
│   with okta_brand.x_footer,
│   on okta_theme.tf line 6, in resource "okta_brand" "x_footer":
│    6:   name                   = "Test Brand Name #1"
│ 
│ Can't configure a value for "name": its value will be decided automatically based on
│ the result of applying this configuration.
```

### Additional Info
Removing the name field from `okta_brand` on an imported brand will forcefully rename existing brands to 'New Brand'

```
  ~ resource "okta_brand" "x_footer" {
      - brand_id               = "bnd1234" -> null
        id                     = "bnd1234"
        name                   = "Test Brand Name #1"
        # (2 unchanged attributes hidden)
    }
```

So really, it isn't possible to change an imported brand that has a custom name 

### References

- https://github.com/okta/terraform-provider-okta/pull/1605

**Comment by duytiennguyen-okta** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-601950

**Comment by duytiennguyen-okta** [comment]
Closed with https://github.com/okta/terraform-provider-okta/pull/1677
