### ISSUE TITLE
Unable to upgrade provider to 4.2.0 or 4.3.0 from 4.1.0

### ISSUE THREAD

**Issue by mbulgatz** [okta/terraform-provider-okta#1682]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.5.6

### Affected Resource(s)

Okta Provider 4.2.0/4.3.0

### Terraform Configuration Files

```hcl
terraform {
  cloud {
    organization = "[redacted]"
    workspaces {
      name = "secit-okta-prod"
    }
  }  

  required_providers {
    okta = {
      source = "okta/okta"
      version = "~> 4.1.0"
    }
  }
}
```

### Expected Behavior

Should have been a successful plan for the provider upgrade to 4.3.0

#### Can this be done in the Admin UI?

I don't know

### Steps to Reproduce

Updated Terraform Okta Provider -> 4.3.0, then ran a terra init -upgrade -> terra plan

### References

- #0000

**Comment by monde** [comment]
@mbulgatz I'm not able to reproduce your bug report. What was the error you were seeing? I tried to reproduce the issue with the following simple tf config.

```hcl
terraform {
  required_providers {
    okta = {
      # OKTA_API_TOKEN etc. from ENV VARs
      source = "okta/okta"
      # before
      # tf init && tf plan && tf apply
      #version = "~> 4.1.0"

      #after
      # tf init -upgrade && tf plan && tf apply
      version = "~> 4.3.0"
    }
  }
}

data "okta_group" "all" {
  name = "Everyone"
  include_users = true
}

data "okta_app" "dashboard" {
  label = "Okta Dashboard"
}
```

```
$ tf init

Initializing the backend...

Initializing provider plugins...
- Finding okta/okta versions matching "~> 4.1.0"...
- Installing okta/okta v4.1.0...
- Installed okta/okta v4.1.0 (signed by a HashiCorp partner, key ID 6438EEBF187672EE)

...

$ tf plan
data.okta_group.all: Reading...
data.okta_app.dashboard: Reading...
data.okta_app.dashboard: Read complete after 0s [id=0oa5qwjvixUgETvka1d7]
data.okta_group.all: Read complete after 1s [id=00g5qwjvgrD3WR89l1d7]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

$ tf apply
data.okta_app.dashboard: Reading...
data.okta_group.all: Reading...
data.okta_app.dashboard: Read complete after 0s [id=0oa5qwjvixUgETvka1d7]
data.okta_group.all: Read complete after 0s [id=00g5qwjvgrD3WR89l1d7]

No changes. Your infrastructure matches the configuration.

$ tf init -upgrade

Initializing the backend...

Initializing provider plugins...
- Finding okta/okta versions matching "~> 4.3.0"...
- Installing okta/okta v4.3.0...
- Installed okta/okta v4.3.0 (signed by a HashiCorp partner, key ID 6438EEBF187672EE)

...

$ tf plan
data.okta_app.dashboard: Reading...
data.okta_group.all: Reading...
data.okta_app.dashboard: Read complete after 0s [id=0oa5qwjvixUgETvka1d7]
data.okta_group.all: Read complete after 0s [id=00g5qwjvgrD3WR89l1d7]

No changes. Your infrastructure matches the configuration.
```

**Comment by fmasuhr** [comment]
We are seeing an issue on the upgrade as well. 
In our case we are getting an error:

>│ Error: failed to get groups claim for OAuth application: the API returned an error: Invalid session, Status: 403 Forbidden
│ 
│   with okta_app_oauth.this,
│   on main.tf line 1, in resource "okta_app_oauth" "this":
│  1: resource "okta_app_oauth" "this" {

This seems to be related to the changes made in https://github.com/okta/terraform-provider-okta/pull/1638/files#diff-4a5904220b736cd8cd158c3c3e4814fda830aff6ccae710cecbd52aedcac897cL520-L527. 
As this function is using an [internal okta API](https://github.com/okta/terraform-provider-okta/blob/master/sdk/app_oauth_group_claim.go#L32), it is not working with the oauth token as discussed in an old issue [here](https://github.com/okta/terraform-provider-okta/issues/568).
Therefore the latest changes on the `okta_app_oauth` are not working as expected when using oauth tokens.

**Comment by zlitberg** [comment]
seeing the same error as @fmasuhr on 4.3.0

**Comment by monde** [comment]
Thanks for code research @fmasuhr . I wonder if we should put a gate around those internal API calls to groups claim when the okta-sdk-golang client is in OAuth mode.

**Comment by monde** [comment]
Maybe implement, log warning, and document that `groups_claim` is disabled if the client is authenticated with oauth.

**Comment by chrismorgan-even** [comment]
@monde I work with @mbulgatz. We were looking at the original problem that caused him to open this Issue and found the following (which is a separate problem from the other issue found in this thread).


The stack trace points to an issue here:
`2023-09-01T18:54:12.813Z [DEBUG] provider.terraform-provider-okta_v4.3.0: github.com/okta/terraform-provider-okta/okta.resourceAppSignOnPolicyRuleRead({0x1966468, 0xc000631560}, 0xc00029a380, {0x15fd840?, 0xc00062e240?})
2023-09-01T18:54:12.813Z [DEBUG] provider.terraform-provider-okta_v4.3.0: 	github.com/okta/terraform-provider-okta/okta/resource_okta_app_signon_policy_rule.go:257 +0x9db`

We turned on TRACE level logs and found the resource API response which was leading to this issue. Parsing out the relevant portion of the response here for reference:
```json
"conditions": {
   "people": {
      "users": {
       "exclude": []
      },
      "groups": {
       "include": [
         REDACTED
       ]
    }
  },
  "network": {
    "connection": "ANYWHERE"
  },
  "device": {
    "registered": true,
    "managed": true
  },...
```

The important thing to note here is that "device" is defined with "registered" and "managed" subnodes, but not an "assurance" node.

The stack trace referenced [line 257 in resource_okta_app_signon_policy_rule.go](https://github.com/okta/terraform-provider-okta/blob/55e65af9f2b3b0235d62606913d32b0673e25558/okta/resource_okta_app_signon_policy_rule.go#L257). This line attempted to reference the subnode `Include` of `Conditions.Device.Assurance` without first checking to see if the `Assurance` subnode exists. Given the shape of the response for our policy rule (in the policy rule web UI, we have Device Registered and Device Managed set, but DAP set to "No Policy"), I believe this is leading to this failure.

I believe the fix here is something like expanding line 257 to:
```go
if rule.Conditions.Device.Assurance != nil {
   m["device_assurances_included"] = convertStringSliceToSetNullable(rule.Conditions.Device.Assurance.Include)
}
```

**Comment by monde** [comment]
Guards and protections discussed/suggested here will be in the next release. PR is merged.
