### ISSUE TITLE
change `okta_app_group_assigments` group schema from `schema.TypeList` to `schema.TypeSet` or `schema.TypeMap`

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1687]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

inserting or deleting a `group` block from `okta_app_group_assigments` causes plan outputs that are quite difficult to read, this makes the plan less useful and thus engineers less likely to catch mistakes
my limited understanding is that if we change from `[schema.TypeList](https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_app_group_assignments.go#L33)` to `schema.TypeSet` or `schema.TypeMap` this will address this problem

While we're at hopefully we can resolve https://github.com/okta/terraform-provider-okta/issues/1088 where `okta_app_group_assignments` will fail to show drift remediation actions in the plan

### New or Affected Resource(s)

- `okta_app_group_assigments`

### Potential Terraform Configuration

I'm not enitrely clear on how this would change the configuration, I believe `TypeSet` would be largely backwards compatible (but would require a state migration)

### References

- #1088
- https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_app_group_assignments.go#L33

**Comment by duytiennguyen-okta** [comment]
hi @exitcode0 can you show us how noisy the output is?

**Comment by exitcode0** [comment]
I've Looked into this a bit further today
I think what I'm seeing is that `data "okta_groups"` returns groups in an unknowable sequence when new groups are created outside of Terraform

assuming I'm correct about what I'm seeing, I think a `set` or `map` could resolve this
My config looks somewhat like the following
```hcl
rresource "okta_group" "groups" {  # representing groups managed by another system
  count = 50
  name = "tf_provider_testing_${count.index}"
}

resource "okta_app_bookmark" "google" {
  label = "google"
  url = "https://www.google.com"
  skip_groups = true
  skip_users = true
  lifecycle {
    ignore_changes = [
      users,
      groups
    ]
  }
}
data "okta_groups" "example" { q = "tf_" }
resource "okta_app_group_assignments" "google" {
  app_id = okta_app_bookmark.google.id
  dynamic "group" {
    for_each = [for group in data.okta_groups.example.groups : group.id]
    content {
      id = group.value
    }
  }
}
# resource "okta_group" "tf_extra" {  # uncomment before 2nd apply
#   name = "tf_extra"
# }
```
when a new group is added to Okta by systems external to Terraform the order the groups are returned in by the Okta api can change, the new group could be inserted anywhere in the list the API returns
This can lead to a tiny plan, or a plan that looks to change all assignments on the application, making it hard for engineers to know if they've made a mistake

e.g the following plan was output after creating one additional group

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # okta_app_group_assignments.google will be updated in-place
  ~ resource "okta_app_group_assignments" "google" {
        id     = "0oab4mtqkyUiwrRya5d7"
        # (1 unchanged attribute hidden)

      ~ group {
          ~ id       = "00gafrqv0dDQOJWLs5d7" -> "00gb4p72502HEKbU75d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gagx3fuw7HfCAZc5d7" -> "00gafrqv0dDQOJWLs5d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafrtnndYpn7LQU5d7" -> "00gagx3fuw7HfCAZc5d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafrt05p5hqhyYR5d7" -> "00gafrtnndYpn7LQU5d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafrwfxnHiKCgcK5d7" -> "00gafrt05p5hqhyYR5d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafrvltvJu8RoBl5d7" -> "00gafrwfxnHiKCgcK5d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafrv4tmlOwlnfC5d7" -> "00gafrvltvJu8RoBl5d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafrubmrJij3VFp5d7" -> "00gafrv4tmlOwlnfC5d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafrt0mevBu5zC25d7" -> "00gafrubmrJij3VFp5d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafru5ev4zUuLdj5d7" -> "00gafrt0mevBu5zC25d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafrvsszN7QrWkr5d7" -> "00gafru5ev4zUuLdj5d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafrwfxrKbIX4S85d7" -> "00gafrvsszN7QrWkr5d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafrsudvE9bTqtb5d7" -> "00gafrwfxrKbIX4S85d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafrs008QahXaQ65d7" -> "00gafrsudvE9bTqtb5d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafrsoanaeVYI9h5d7" -> "00gafrs008QahXaQ65d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafruaofcCFUafO5d7" -> "00gafrsoanaeVYI9h5d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafrudy1NTlOJtT5d7" -> "00gafruaofcCFUafO5d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafrt0md39BbIdt5d7" -> "00gafrudy1NTlOJtT5d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafrukxpAzJpvXI5d7" -> "00gafrt0md39BbIdt5d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafrq2igTj4H2rl5d7" -> "00gafrukxpAzJpvXI5d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafrs53icFmVH6V5d7" -> "00gafrq2igTj4H2rl5d7"
            # (2 unchanged attributes hidden)
        }
      ~ group {
          ~ id       = "00gafrq9gn47JV5bq5d7" -> "00gafrs53icFmVH6V5d7"
            # (2 unchanged attributes hidden)
        }
      + group {
          + id      = "00gafrq9gn47JV5bq5d7"
          + profile = jsonencode({})
        }
        # (50 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 
```

**Comment by tgoodsell-tempus** [comment]
Yes `TypeSet` would be the most appropriate value for this as to the API, this is a unique list of groups (meaning you can't assign a group more than once) in which order is irrelevant to operations with the caveat the `priority` value is how Okta is ordering the evaluation. I do not know if the API returns the groups in "priority" order or not, but `TypeList` could be useful in the event you wanted to use the index value as the setting for priority.

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-651869

**Comment by duytiennguyen-okta** [comment]
@tgoodsell-tempus @exitcode0 I have been trying to get those working but turns out we do want to keep those priority order so I am going to close this issue

**Comment by exitcode0** [comment]
> @tgoodsell-tempus @exitcode0 I have been trying to get those working but turns out we do want to keep those priority order so I am going to close this issue

Could you expand upon that a bit more (for my own curiosity)?
Is this because when constructing group assignments we want to assign them to the application in ascending order by priority to avoid the Okta API re-indexing the assignment list on us?
