### ISSUE TITLE
Import of okta_group_memberships does not import users

### ISSUE THREAD

**Issue by tfmm** [okta/terraform-provider-okta#1695]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### Affected Resource(s)

- okta_group_memberships

### Terraform Configuration Files

```hcl
resource "okta_group_memberships" "example" {
  group_id = data.okta_group.aws_okta_groups["example"].id
  users = [
    data.okta_user.user["user1"].id,
    data.okta_user.user["user2"].id
  ]
  track_all_users = true
}

```

### Expected Behavior

Import of `okta_group_memberships` should include users in the group.

#### Can this be done in the Admin UI?

Yes 

#### Can this be done in the actual API call?

I don't know 

### Actual Behavior

After running import of resource, state only shows very generic information, not including list of users in the group, causing terraform to want to replace the users

### Steps to Reproduce

1. `terraform import okta_group_memberships.example example_group_id`
2. Run `terraform plan` and see drift. Issue can also be seen by looking directly at state file.

**Comment by monde** [comment]
Note to self: change resource_okta_group_memberships.go to have importer something like `Importer:      createNestedResourceImporter([]string{"id", "track_all_users"}),` which would allow import with extra info on the argument like `terraform import okta_group_memberships.example <group id>/<track all users - true/false>`. To import group 00g9i76ex80h4oNt81d7 and track all its users: `terraform import okta_group_memberships.example 00g9i76ex80h4oNt81d7/true`

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-646747

**Comment by monde** [comment]
@tfmm I looked at this further with @arvindkrishnakumar-okta . I think this is a bug, but not in the way that you've reported it. This resource shouldn't have an import function.

The behavior of the resource is simply to add/remove users to a group. The actual resource `okta_group_memberships` is conceptual and only exists in the terraform state file, there isn't a concrete resource in the Okta monolith that is a membership. Users have group membership, but the membership itself is not a concrete resource.

To specifically address what you were seeing in your config. The import command was simply establishing the shell of a `okta_group_memberships` in your tf state file that assigns the ID, something like this:

```
  "resources": [
    {
      "mode": "managed",
      "type": "okta_group_memberships",
      "name": "example",
      "provider": "provider[\"registry.terraform.io/okta/okta\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "group_id": null,
            "id": "00ga9o8pslNAR3tTD1d7",
            "track_all_users": null,
            "users": null
          },
          "sensitive_attributes": [],
          "private": "eyJzY2hlbWFfdmVyc2lvbiI6IjAifQ=="
        }
      ]
    }
  ],
```
When you run apply on that resource it then goes and adds/removes users from the group on the Okta side to match what you've scripted in your config. Therefore it doesn't really make sense to have an import on this resource and @arvindkrishnakumar-okta is going to remove it from the provider.

In general the behavior of `okta_group_memberships` is this:

w/o `track_all_users` the resource will only concern itself with the identified users in the `users` array.  If the operator removes a user id from the local array the user will be removed from the group at Okta on the next apply. The same can be said if the operator adds a new user id to the users array, that user is added to the group on the Okta side.

w/ `track_all_users` the resource will detect if users have been added to the group outside of the resource, and if their id is not in the local users array, will perform the API call to remove that user from the group on the Okta side. w/o `track_all_users` the add user on on the Okta side is ignored in the local terraform state file.

**Comment by tfmm** [comment]
I'm sad this is your reply.  To be in line with other terraform resources from other providers, I believe this functionality should be added, especially when using `track_all_users`.  Without being able to import this information, there is no way to properly see the changes terraform is going to make to the group.

**Comment by monde** [comment]
@tfmm import is just reading in state. Even if we keep the import command, the next apply would modify memberships on the group to match the local tf state. Effectively the import command is meaningless because it is a reader, it doesn't take action itself.

For example
Given real state at Okta:
Group A, User 1, User 2, User 3
User 1 and User 2 are already assigned to Group A

Operator has a okta_group_memberships with only User 1 as a member.

```
resource "okta_group_memberships" "example" {
  group_id = "group A id"
  users = [
    "user 1 id"
  ]
  track_all_users = true
}
```

Import just establishes a okta_group_memberships named example with an id in the local tf state file.

In the next apply in terraform the provider attempts to make the remote Okta state match the state that is implied from the terraform config. So in my example above, terraform apply the provider would remove User 2 from Group A.

**Comment by tfmm** [comment]
Right, but with other resources (outside of the Okta provider) when you import and then run a plan/apply, it will show you what changes are to be made, and it does not just overwrite the entire resource. In an environment where we are using terraform/IaC as a tracking method for changes, this makes this largely useless.

**Comment by monde** [comment]
@tfmm noted, I need to take another look at this given your feedback. Stand by.

**Comment by monde** [comment]
@tfmm thanks for pushing back, my original reflection was correct (we need to add a track all users flag to the import input). Also the behavior you describe is what import should do on that resource - include all users on the group when importing and track all users present on the group. The implementation of this resource is kind of sloppy (it is long lived code) and I was off when @arvindkrishnakumar-okta and I were looking at it.

The command will be:

`terraform import okta_group_memberships.example <the group id>/true`

@arvindkrishnakumar-okta Is new to the project and will be doing this work as well as adding to our acceptance tests for this resource.

**Comment by tfmm** [comment]
@monde Thanks for being willing to listen and work with me on this, it is appreciated!

**Comment by tfmm** [comment]
Any chance we have a timeline when this may get merged? I have another large group I need to import in the next day or so, and was hoping to do it cleanly if possible. 

Thanks!

**Comment by duytiennguyen-okta** [comment]
We plan to do a release on Tuesday or Wednesday.

**Comment by fishpen0** [comment]
What happened here? This issue is open, but `track_all_users` is documented as released. Simultaneously we're having issues when `track_all_users` is enabled that's causing 100% changes every time an okta group membership is updated (basically emptying and readding everyone to the group every run)

**Comment by duytiennguyen-okta** [comment]
@fishpen0 This issue supposed to be closed, the one fixing it forgot to close it. Can you create a new issue with your problem?
