### ISSUE TITLE
"description" attribute of okta_app_saml resource is not valid

### ISSUE THREAD

**Issue by ThomasWatling** [okta/terraform-provider-okta#171]
In the documentation for the okta_app_saml resource (https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/app_saml) one of the optional attributes listed is "description". If you add this to a resource block and run terraform validate or plan, you get an error "An argument named "description" is not expected here." Looking at the source code for the Okta provider https://github.com/oktadeveloper/terraform-provider-okta/blob/master/okta/resource_okta_app_saml.go the attribute "description" is not defined. It should be removed from the documentation.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.26
+ provider.okta v3.4.1

### Affected Resource(s)

okta_app_saml 

### Terraform Configuration Files

```hcl
resource "okta_app_saml" "example" {
  label         = "SAML App Name"
  description   = "Description of SAML App"
}
```

### Debug Output

Error: Unsupported argument
An argument named "description" is not expected here.

**Comment by bogdanprodan-okta** [comment]
Hi @ThomasWatling! This issue will be fixed in v3.8.0.
