### ISSUE TITLE
4.4.0 Plugin Crash

### ISSUE THREAD

**Issue by jcbw1835** [okta/terraform-provider-okta#1712]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.5.7

### Affected Resource(s)

-terraform-provider-okta_v4.4.0 plugin

### Terraform Configuration Files

https://gist.github.com/jcbw1835/ebbe789217969b02a89d97b84177c24c

### Debug Output

https://gist.github.com/jcbw1835/c27aac95de26033d4cc7da84c838f472

### Expected Behavior

"terraform plan" runs as expected without the plugin crashing

### Actual Behavior

Plugin immediately crashes (see gist above for output)

### Steps to Reproduce
1. terraform init -> success
2. terraform plan -> crashes

### Important Factoids

Ubuntu 22 running in vmware

### References

- #0000

**Comment by mvitt** [comment]
I am receiving the same issue via terraform apply

**Comment by monde** [comment]
Thanks @jcbw1835 @mvitt I will try to get a bug fix and release out asap.
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-646727

**Comment by mvitt** [comment]
Thank you for the quick response @monde! I know this is probably not said enough, but you guys do an amazing job on this provider and I appreciate all the work you guys put into it! :)

**Comment by jcbw1835** [comment]
Perfect, thank you for the quick response!

JACOB CUNNINGHAM | Solutions Architect | BLACKWOOD | 410.934.4003 (C) | ***@***.******@***.***>

**Comment by monde** [comment]
@jcbw1835 let me know your go version, an example from me:
```
$ go version
go version go1.21.0 darwin/amd64
```

@jcbw1835 also I'm stumped on this, in your gist when I step into the code for okta-sdk-golang I can see these lines:
https://gist.github.com/jcbw1835/c27aac95de26033d4cc7da84c838f472#file-gistfile1-txt-L21-L22
correspond to the okta API URL being parsed which is derived in the provider with org_name and base_url being joined together. Can you email me your org_name value to mike.mondragon@okta.com , or just send me a mail and I'll give you a zoom invite so I can see it live. Thanks

**Comment by monde** [comment]
Actually, @jcbw1835 @mvitt just make sure `org_name` is your Okta org name. For instance, if the URL to my org is "https://example.okta.com/" then the `org_name` value is `example` and `base_url` is `okta.com`.

In the exmaple the org name is scrubbed out `org_name = "{xxxxxxxxxxxxxxxx}"` but doing some more debugging I can see that error will happen if the org_name value contains invalid URL characters. Like `exa^mple` would cause that error.

I'm going to add some protections into the provider, our sdk library is not catching it correctly. Thanks!

**Comment by monde** [comment]
Provider will give a useful error here going forward:
```

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: [ERROR] failed to load sdk clients: Malformed OKTA API URL (org_name+base_url value, or http_proxy value): parse "https://iadf^dfads.okta.com": invalid character "^" in host name
│
│   with provider["registry.terraform.io/okta/okta"],
│   on main.tf line 14, in provider "okta":
│   14: provider "okta" {
│
```
