### ISSUE TITLE
Okta OAuth App Does Not Support EC Key Configurations

### ISSUE THREAD

**Issue by tgoodsell-tempus** [okta/terraform-provider-okta#1714]
The issue documented means we cannot use anything other than RSA keys properly in this resource.

While there is the simple solution of adding the `x` and `y` optional attributes to the resource. My preference is a larger breaking change where the schema for `jwks` is converted to a list with elem of `schema.TypeString` using the JSON validations (or perhaps a custom validation to ensure both type and JWKS validation).

This would allow a configuration such as:
```hcl
data "jwks_from_key" "public_key" {
  key = file("${path.root}/public-keys/test.pem")
  kid = "test"
}

resource "okta_app_oauth" "client" {
  label                      = "test"
  type                       = "service"
  token_endpoint_auth_method = "private_key_jwt"
  grant_types                = ["client_credentials"]
  response_types             = ["token"]
  jwks = [data.jwks_from_key.public_key.jwks]
}
```

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### Affected Resource(s)

- okta_app_oauth

### Terraform Configuration Files

```hcl
resource "okta_app_oauth" "test" {
  label                      = "testAcc_replace_with_uuid"
  type                       = "service"
  response_types             = ["token"]
  grant_types                = ["client_credentials"]
  token_endpoint_auth_method = "private_key_jwt"

  jwks {
    kty = "EC"
    kid = "SIGNING_KEY"
    x   = "1234ajkldjfa"
    y   = "abc1234"
  }
}
```

### Expected Behavior

Plans and applied successfully. 

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

Yes

### Actual Behavior

Fails validation for the app schema

### Important Factoids

Schema is currently hardcoded in Terraform to use RSA format.

See: https://github.com/okta/terraform-provider-okta/blob/9ed172411e84bb1ceec0e8ac7b2edf5e63be6515/okta/resource_okta_app_oauth.go#L303C1-L328

### References

https://developer.okta.com/docs/reference/api/oauth-clients/#json-web-key

- #0000

**Comment by tgoodsell-tempus** [comment]
Another thing which maybe I could spin off into another issue/Okta ticket is support for `EdDSA` keys in the Okta API ecosystem: https://www.rfc-editor.org/rfc/rfc8037.html

**Comment by monde** [comment]
Thanks @tgoodsell-tempus I put this on our internal backlog https://oktainc.atlassian.net/browse/OKTA-646726
I can see the Okta API allows flexibility in the pk format in the jwks:
https://developer.okta.com/docs/reference/api/apps/#application-json-web-key-request-properties
We should make the implementation flexible as you point out.

**Comment by tgoodsell-tempus** [comment]
@monde Cheers, I created https://github.com/okta/terraform-provider-okta/pull/1715 for a "Quick fix", if possible please try running my acceptance test in some proper environments (since my test account isn't for all the various Okta types).

I'll do a follow up PR, with my proposal for the alternate input format, done in a:
1. Add new var with the proper input schema, deprecate the old one, then update the handling code to allow both while we run on this version.
2. Let the removal / cleanup of the "handle both" method be done in `5.0.0` or whatever applicable major version.
