### ISSUE TITLE
Port ignored on providers `http_proxy` directive 

### ISSUE THREAD

**Issue by robgero** [okta/terraform-provider-okta#1723]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
`v1.5.7`

### Affected Resource(s)

- provider

### Terraform Configuration Files

```hcl
provider "okta" {
  api_token  = "foo"
  http_proxy = "http://localhost:3000"
}
```

This can be easily tested by opening two terminals, one listening on port 80 and the other on port 3000.
```sh
# Terminal 1
nc -l 80
```

```sh
# Terminal 2
nc -l 3000
```

The initial `GET /api/v1/users/me` request appears in the port 80 terminal and terraform freezes when I run `terraform plan`.
### Debug Output
https://gist.github.com/robgero/ed3110fc774bf5bd6f3b0477d5129a31

### Expected Behavior

The port should be included in the host.

### Actual Behavior

If my `http_proxy` contains `http://` it gets defaulted to port 80

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-648042
