### ISSUE TITLE
okta_idp_saml.user_type_id incorrectly contains the base user profiles ID instead of the IDP profile ID

### ISSUE THREAD

**Issue by wh185044** [okta/terraform-provider-okta#1727]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.82.0
+ provider registry.terraform.io/okta/okta v4.4.2

### Affected Resource(s)

- okta_idp_saml

### Terraform Configuration Files

```hcl
resource "okta_idp_saml" "test" {
  name                 = "Test"
  username_template    = "idpuser.subjectNameId"
  subject_match_type   = "USERNAME"
  account_link_action  = "AUTO"
  provisioning_action  = "AUTO"
  suspended_action     = "UNSUSPEND"
  deprovisioned_action = "REACTIVATE"
  profile_master       = true

  issuer                       = "***"
  sso_url                      = "***"
  kid                          = okta_idp_saml_key.test.id
  sso_binding                  = "HTTP-POST"
  request_signature_scope      = "REQUEST"
  request_signature_algorithm  = "SHA-256"
  response_signature_scope     = "ANY"
  response_signature_algorithm = "SHA-256"
  sso_destination              = "***"

  acs_type       = "INSTANCE"
  max_clock_skew = 120000
}

data "okta_user_profile_mapping_source" "user" {}

resource "okta_profile_mapping" "test" {
  source_id    = okta_idp_saml.test.user_type_id
  target_id    = data.okta_user_profile_mapping_source.user.id
  always_apply = true

  mappings {
    id          = "email"
    expression  = "appUser.username"
    push_status = "PUSH"
  }
}
```

### Debug Output

N/A

### Panic Output

None

### Expected Behavior

The value for okta_idp_saml.test.user_type_id used as the source_id for the resource okta_profile_mapping.test should have been the okta user type ID of the IDP.

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

Yes

### Actual Behavior

okta_idp_saml.test.user_type_id was the base User profile user_type_id instead of the IDP's user_type_id

Plan Output (notice both source_id and target_id are the same, oty5iousm2zTz4zFX1d7 is the base user profile's ID)
```hcl
# okta_profile_mapping.test will be created
  + resource "okta_profile_mapping" "test" {
      + always_apply = true
      + id           = (known after apply)
      + source_id    = "oty5iousm2zTz4zFX1d7"
      + source_name  = (known after apply)
      + source_type  = (known after apply)
      + target_id    = "oty5iousm2zTz4zFX1d7"
      + target_name  = (known after apply)
      + target_type  = (known after apply)

      + mappings {
          + expression  = "appUser.username"
          + id          = "email"
          + push_status = "PUSH"
        }
    }
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

No important facts

### References

- #957

**Comment by monde** [comment]
Thanks @wh185044 I've marked this as a bug and added it to our internal backlog https://oktainc.atlassian.net/browse/OKTA-649280

**Comment by duytiennguyen-okta** [comment]
@wh185044 Just want to clarify, what problem are you trying to solve here? Because in the docs we already mentioned that user_type_id is used for target_id in [okta_profile_mapping](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/idp_saml#user_type_id)

**Comment by wh185044** [comment]
> @wh185044 Just want to clarify, what problem are you trying to solve here? Because in the docs we already mentioned that user_type_id is used for target_id in [okta_profile_mapping](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/idp_saml#user_type_id)

I want to set up an IDP using okta_idp_saml, then configure the mapping of profile properties from that IDP to the default user profile.  Which would require the ability to get the user_type_id for the newly created IDP and use it for the source_id.  I realize the docs said "for use in target" but in my test the value coming back is the default user profile's user type id instead of the IDP's ID so it wouldn't be usable for target_id either.

Note - Even if this is fixed I couldn't accomplish my goal, as https://github.com/okta/terraform-provider-okta/issues/1728 would prevent me from configuring mappings for an IDP user type.

**Comment by duytiennguyen-okta** [comment]
@wh185044 If your goal is to config the profile mapping from idp to user, then you can simply use the idp.id for that purpose. I have tried your example with idp_saml and it worked. We also have an example of that in for idp_social [here](https://github.com/okta/terraform-provider-okta/blob/master/examples/resources/okta_profile_mapping/basic.tf). In this example we were configuring the idp to user for that profile mapping. Let me know if that help

**Comment by wh185044** [comment]
Thank you, that works and also allows the use of okta_profile_mapping with the IDP.

**Comment by duytiennguyen-okta** [comment]
Thanks @wh185044. I will close this issue now
