### ISSUE TITLE
support IDP mapping in okta_profile_mapping

### ISSUE THREAD

**Issue by wh185044** [okta/terraform-provider-okta#1728]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently if you provide okta_profile_mapping a source_id that is an Identity Provider it will fail with an error:

The request was not valid: Invalid source or target id. Source or target id must be of either App Instance or UserType id, Status: 400 Bad Request

We are creating an identify provider using the okta_idp_saml resource and would like to configure the profile mappings for that IDP in terraform.

### New or Affected Resource(s)

- okta_profile_mapping

### Potential Terraform Configuration

```hcl
resource "okta_idp_saml" "test" {
  name                 = "Test"
  ...
}

data "okta_user_profile_mapping_source" "user" {}

resource "okta_profile_mapping" "test" {
  # source_id is wrong, see https://github.com/okta/terraform-provider-okta/issues/1727
  source_id    = okta_idp_saml.test.user_type_id # <--- This should support an IDP's user type ID
  target_id    = data.okta_user_profile_mapping_source.user.id
  always_apply = true

  mappings {
    id          = "email"
    expression  = "appUser.username"
    push_status = "PUSH"
  }
}
```

### References

I believe #1727 is making it so the source ID is wrong with the TF code above, but even if you take the IDP's user type ID from the UI and substitute it into the source_id property you will still received the error stating only apps and user types are allowed.

- #1727

**Comment by monde** [comment]
Thanks @wh185044 I've added this to our internal backlog https://oktainc.atlassian.net/browse/OKTA-649278

**Comment by wh185044** [comment]
See #1727 .  If you use the IDP's ID as the source instead of the user profile ID then you are able to configure IDP mapping via okta_profile_mapping

**Comment by duytiennguyen-okta** [comment]
Thanks @wh185044. I will close this issue now
