### ISSUE TITLE
Latest Preview release is throwing an exception to update the profile enrollment policy rule

### ISSUE THREAD

**Issue by vignesh-okta** [okta/terraform-provider-okta#1733]
### Terraform Version
1.5.7

### Affected Resource(s)

- okta_policy_rule_profile_enrollment

### Terraform Configuration Files

```hcl

resource "okta_policy_profile_enrollment" "profile_enrollment" {
  for_each = var.profile_enrollment_map

  name   = each.value.name
  status = "ACTIVE"
}

resource "okta_policy_rule_profile_enrollment" "profile_enrollment_rule" {

  for_each = var.profile_enrollment_map

  policy_id          = local.name-id[each.value.name]
  target_group_id    = try(var.group_name-id_map[each.value.rule.target_group_name], null)
  email_verification = each.value.rule.email_verification

  access              = "ALLOW"
  unknown_user_action = try(each.value.rule.unknown_user_action, "REGISTER")

  dynamic "profile_attributes" {
    for_each = each.value.rule.profile_attributes
    content {
      name     = profile_attributes.value.name
      label    = profile_attributes.value.label
      required = profile_attributes.value.required
    }
  }

}

resource "okta_policy_profile_enrollment_apps" "profile_enrollment_apps" {
  for_each = var.profile_enrollment_map

  policy_id = local.name-id[each.value.name]
  apps      = [for app_label in each.value.apps : var.application_label-id_map[app_label]]
}
```

### Expected Behavior

The resource should refresh successfully and complete the terraform run for other modified resources

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

Yes

### Actual Behavior

The run is throwing an exception `failed to update profile enrollment policy rule: the API returned an error: Api validation failed: actions.profileEnrollment.progressiveProfilingAction. Causes: errorSummary: actions.profileEnrollment.progressiveProfilingAction: The rule could not be created or updated because the progressiveProfilingAction field in the requirement contained an invalid value or was incorrectly formatted`. The reason for this exception correlates with Okta preview having a new feature flag released for Profile enrolment which allows to separate progressive profiling and self service registration.

### Steps to Reproduce

Run the `okta_policy_rule_profile_enrollment` resource against a preview org which has `MAKE_ENROLLMENT_GREAT_AGAIN` FF turned on.

1. `terraform apply`

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-651857

**Comment by SilverCory** [comment]
Same issue for us, tried making a PR #1563 however it's outdated since there are more required fields and the field I tried to add has since changed name.
