### ISSUE TITLE
Updating a resource set that contains delegated Workflows causes a provider panic

### ISSUE THREAD

**Issue by steveAG** [okta/terraform-provider-okta#1735]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### Affected Resource(s)

- okta_resource_set

### Terraform Configuration Files

```hcl
resource "okta_resource_set" "resources" {
  label       = "Test Resource Set"
  description = "Test Resource Set"
  resources   = ["https://xxx.okta.com/api/v1/groups/00gxxx/users"]
}
```

### Debug Output

I was having issues generating these logs, I can give it another shot if needed.

### Panic Output

https://gist.github.com/sgal-dm/206ddf76ab7df916fcde27d560668999

### Expected Behavior

The resource set removes the Delegated Workflows because they aren't defined in Terraform.

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

Yes

### Actual Behavior

- The Terraform resource set doesn't see that the delegated Workflows are added to the resource set (presumably being dropped by the read function due to the data structure). Producing no plan change when they've been added outside Terraform using the admin console or API.
- If you then remove a Terraform-managed value in the resource set (like the above group members), and attempt to fix the drift with Terraform, then it causes the above provider crash.
- Note the change appears to be processed fine (removed groups/users from a set are added back), but the provider crashes afterward.

### Steps to Reproduce

1. Create a resource set with Terraform.
2. Manually add at least one Delegated Workflow to the resource set using the admin console or API.
3. Run a `terraform plan` and observe that Terraform doesn't see the manual change.
4. Remove one of the Terraform-managed values from the resource set.
5. Run a `terraform apply` and observe that the Terraform provider crashes when updating the resource set.

### References

- Example Get Resource Set API response with delegated flows added:

```
{
    "resources": [
        {
            "id": "irea0ruefylEfAY8p1d7",
            "orn": "orn:oktapreview:directory:00o2m4nhow8wfzDNs1d7:groups:00gaxxx:contained_resources",
            "created": "2023-09-12T14:12:07.000Z",
            "lastUpdated": "2023-09-12T14:12:07.000Z",
            "_links": {
                "self": {
                    "href": "https://xxx.oktapreview.com/api/v1/groups/00gaxxx/users"
                }
            }
        },
        {
            "id": "irea6zhf0bN1RVsvj1d7",
            "orn": "orn:oktapreview:workflow:00oxxx:flows:597xxx",
            "created": "2023-09-22T15:43:58.000Z",
            "lastUpdated": "2023-09-22T15:43:58.000Z"
        },
        {
            "id": "irea6zhf0cUcv6qm21d7",
            "orn": "orn:oktapreview:workflow:00oxxx:flows:597xxx",
            "created": "2023-09-22T15:43:58.000Z",
            "lastUpdated": "2023-09-22T15:43:58.000Z"
        }
    ],
    "_links": {
        "resource-set": {
            "href": "https://xxx.oktapreview.com/api/v1/iam/resource-sets/iama0ruefxHf1krjQ1d7"
        },
        "self": {
            "href": "https://xxx.oktapreview.com/api/v1/iam/resource-sets/iama0ruefxHf1krjQ1d7/resources"
        }
    }
}
```

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-651859
