### ISSUE TITLE
Inconsistent Validation of `array_enum` in `okta_app_user_schema_property`

### ISSUE THREAD

**Issue by vtremblay** [okta/terraform-provider-okta#1745]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
When creating a resource using okta_app_user_schema_property, it's possible to set the array_type property to "object," allowing JSON objects as attribute values. However, attempting to configure the array_enum property by setting objects in it results in inconsistent behavior.

### Expected Behavior
The provider should accept JSON objects as values in the array_enum property when array_type is set to "object."

### Actual Behavior
The provider rejects the configuration, stating that the field should contain strings, even though the Okta API allows JSON objects in this context.

### Steps to Reproduce

1. Create a resource using okta_app_user_schema_property with the following configuration:
```hcl
resource "okta_app_user_schema_property" "test" {
  # ...
  array_type  = "object"
  array_enum  = [{"value": "test_value_1"}, {"value": "test_value_2"}]
  # ...
}
```

2. The provider rejects the configuration with the error message:
```
Error: Incorrect attribute value type
Inappropriate value for attribute "array_enum": element 0: string required.
```

3. Attempt to set an array of strings that represent objects (aka JSON encoded strings), resulting in an Okta API error:
```
{
 "errorCode": "error",
 "errorSummary": "The enum constraint com.fasterxml.jackson.databind.node.TextNode \"{\\\"value\\\": \\\"test_value_1\\\"}\" is not valid for the given property type java.util.Map.",
 "errorLink": "error",
 "errorId": "oaepR18Vct-RmSdxZkDhoRDGg",
 "errorCauses": []
}
```

### Additional Information
I have confirmed that the scenario works correctly when calling the Okta API directly and providing JSON objects in the array_enum field. The issue appears to be specific to the provider's validation logic.

### Terraform Version

terraform: v1.5.2
okta provider: 4.4.2

### Affected Resource(s)

- okta_app_user_schema_property

### Terraform Configuration Files

```hcl
resource "okta_app_oauth" "test" {
	label          = "testAcc_replace_with_uuid"
	type           = "native"
	grant_types    = ["authorization_code"]
	redirect_uris  = ["http://d.com/"]
	response_types = ["code"]
	}
	
resource "okta_app_user_schema_property" "test" {
	app_id      = okta_app_oauth.test.id
	index       = "testAcc_replace_with_uuid"
	title       = "terraform acceptance test"
	type        = "array"
	description = "testing"
	required    = false
	permissions = "READ_ONLY"
	master      = "PROFILE_MASTER"
	array_type  = "object"
	array_enum  = [{"value": "test_value_1"}, {"value": "test_value_2"}]
	array_one_of {
		const = {"value": "test_value_1"}
		title = "object one"
	}
	array_one_of {
		const = {"value": "test_value_2"}
		title = "object two"
	}
}
```
#### Can this be done in the Admin UI?

No

#### Can this be done in the actual API call?

Yes

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-654747
