### ISSUE TITLE
nil bumpers in utils.go

### ISSUE THREAD

**Issue by monde** [okta/terraform-provider-okta#1746]
All of the convert functions like `func convertInterfaceToStringArr(purportedList interface{}) []string` in utils.go should do a nil check on the input parameter since it is an interface and can be nil. Should the surface of Okta API responses change then we'll be protected from nil panics that will arise unexpectedly in the future.

https://github.com/okta/terraform-provider-okta/blob/master/okta/utils.go#L137-L144

This report is from customer feedback about a nil panic.

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-654748

**Comment by duytiennguyen-okta** [comment]
Close with #1760
