### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by seanmill** [okta/terraform-provider-okta#1759]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Latest 1.5 version

### Affected Resource(s)

terraform-provider-okta_v3.46.0 plugin

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).ImportResourceState request was cancelled.

### Panic Output

Stack trace from the terraform-provider-okta_v3.46.0 plugin:
panic: runtime error: index out of range [1] with length 1
goroutine 125 [running]:
github.com/okta/terraform-provider-okta/okta.createCustomNestedResourceImporter.func1({0x103e240?, 0xc0001f0f60?}, 0xc000853080, {0xd?, 0xed4062?})
	github.com/okta/terraform-provider-okta/okta/utils.go:177 +0x238
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).ImportState(0xc0000a2180, {0x103e240, 0xc0001f0f60}, 0xc000093618, {0xc0004debb8, 0x14})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/provider.go:385 +0x1ac
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ImportResourceState(0xc000421920, {0x103e240?, 0xc0001f0060?}, 0xc00014aae0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1088 +0xf4
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ImportResourceState(0xc0000ce0a0, {0x103e240?, 0xc000469560?}, 0xc0002b34a0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:848 +0x1f6
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ImportResourceState_Handler({0xe8dbe0?, 0xc0000ce0a0}, {0x103e240, 0xc000469560}, 0xc0001413b0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:403 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00025e1e0, {0x10421d8, 0xc000487520}, 0xc0008cfd40, 0xc0000bbda0, 0x15e96b8, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc00025e1e0, {0x10421d8, 0xc000487520}, 0xc0008cfd40, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a
Error: The terraform-provider-okta_v3.46.0 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

This happened when I mistakenly had an import block without the authorisation server in the id

```
import {
 to = something
 id = 1234abc <-- forgot the auth server id prefix here
 }
```

### References

- #0000

**Comment by monde** [comment]
@seanmill which resource were you importing? I want to make sure we fix the code path in our helper function for importing.

**Comment by seanmill** [comment]
I was importing a scope

**Comment by duytiennguyen-okta** [comment]
Can you show us the import command you were trying to run?

**Comment by monde** [comment]
and @seanmill specifically which resource, e.g. `okta_group`, `okta_user`, etc. as the internal import function has different parameters is takes action upon as we've DRY'd up that code in general. So we won't to understand the edge case here.

**Comment by seanmill** [comment]
I have a resource "okta_auth_server_scope" block like this

```
resource "okta_auth_server_scope" "SomeName" {
  auth_server_id = ...
  name           = "SomeName"
  description    = "Description"
}
```

and an import block like this
```
import { 
to = okta_auth_server_scope.SomeName
id = "the_id_of_the_scope" 
}
```

I forgot to add the auth server id as part of the id in the import block, then I got the 'index out of range' message when I did the 'terraform plan' command

I corrected the import block like so

```
import { 
to = okta_auth_server_scope.SomeName
id = "auth_server_id/the_id_of_the_scope" 
}
```
then the import was successful

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-658711
