### ISSUE TITLE
Inline Hook documentation references wrong version number

### ISSUE THREAD

**Issue by askouras** [okta/terraform-provider-okta#176]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
N/A

### Affected Resource(s)

* [okta_inline_hook](https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/inline_hook)

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Terraform documentation samples states resource version is 1.0.1, https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/inline_hook

### Actual Behavior
Okta documentation samples states correct version is 1.0.0: https://developer.okta.com/docs/reference/api/inline-hooks/#response-example-3

### Steps to Reproduce
N/A, user reported hook wasn't working

### Important Factoids
N/A

### References
N/A

* #0000

**Comment by noinarisak** [comment]
Resolved #175
