### ISSUE TITLE
Receiving Terraform Cyclical Error between the okta_brand and okta_email_domain Resources

### ISSUE THREAD

**Issue by mvitt** [okta/terraform-provider-okta#1771]
It seems that `okta_brand` and `okta_email_domain` cause a cyclical error. specifically on the `brand_id` in the `okta_email_domain` resource and `email_domain_id` in the `okta_brand` resource.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.7

### Affected Resource(s)

- okta_email_domain
- okta_brand

### Terraform Configuration Files

```hcl
resource "okta_brand" "custom_brand" {
  name                                = "brandName"
  default_app_classic_application_uri = var.brand_app_redirect_url
  email_domain_id                     = var.email_domain_id
  remove_powered_by_okta              = false
}

resource "okta_email_domain" "vanity_email_address" {
  brand_id     = var.custom_brand_id
  domain       = var.vanity_email_domain
  display_name = "Customer Service"
  user_name    = "customerservice"
}
```

### Panic Output

No panic, but an error from Terraform:
<img width="1162" alt="image" src="https://github.com/okta/terraform-provider-okta/assets/31548861/d7f700cc-bda0-4616-a3e9-8da0cbb5804a">

### Expected Behavior

brand should link to the email domain correctly

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

I believe so

### Actual Behavior

I receive a cyclical error:
<img width="1162" alt="image" src="https://github.com/okta/terraform-provider-okta/assets/31548861/3afd890a-f258-42fd-b599-54e68b0a5192">

### Steps to Reproduce

1. Create a `okta_email_domain` resource with a `brand_id` of your `okta_brand`
2. Create a `okta_brand` resource with  a`email_domain_id` value of the id from the `okta_email_domain` created in step 1.
3. Cyclical error happens.

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-660887

**Comment by duytiennguyen-okta** [comment]
Close with #1831
