### ISSUE TITLE
4.5.0 Release Breaks `okta_app_signon_policy_rule` Resource Due to `risk_score` Attribute

### ISSUE THREAD

**Issue by lucascantor** [okta/terraform-provider-okta#1772]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

- 1.5.6

### Affected Resource(s)

- okta_app_signon_policy_rule

### Terraform Configuration Files

```hcl
resource "okta_app_signon_policy_rule" "default_1" {
  policy_id = var.okta_auth_policies["default"]
  name      = "Allow Breakglass Service Account"
  priority  = 1
  access    = "ALLOW"
  users_included = [
    okta_user.service_accounts["okta.breakglass.admin"].id,
  ]
  factor_mode                 = "2FA"
  type                        = "ASSURANCE"
  re_authentication_frequency = "PT0S"
  constraints = [
    jsonencode({
      "possession" : {
        "deviceBound" : "REQUIRED"
      }
    })
  ]
}
```

### Debug Output

- N/A

### Panic Output

- N/A

### Expected Behavior

- The `risk_score` argument is optional, so the default value (`"ANY"`) should remain unchanged.
- No changes to `risk_score` should be planned or applied if the argument remains omitted.
- Terraform apply should not fail.

#### Can this be done in the Admin UI?

- Yes

#### Can this be done in the actual API call?

- Yes

### Actual Behavior

1. Terraform plans to change `risk_score` from `"ANY"` to `null`:
```
# okta_app_signon_policy_rule.default_1 will be updated in-place
~ resource "okta_app_signon_policy_rule" "default_1" {
      id                          = "rul16iwmnqaQRHuw10h8"
      name                        = "Allow Breakglass Service Account"
    - risk_score                  = "ANY" -> null
      # (14 unchanged attributes hidden)
  }
```

2. Okta API returns an error and Terraform apply fails:
```
Error: failed to create app sign on policy rule: the API returned an error: Api validation failed: conditions.riskScore.level. Causes: errorSummary: conditions.riskScore.level: The field cannot be left blank
--
  | │
  | │   with okta_app_signon_policy_rule.default_1,
  | │   on policy_authentication.tf line 4, in resource "okta_app_signon_policy_rule" "default_1":
  | │    4: resource "okta_app_signon_policy_rule" "default_1" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

- N/A

### References

- N/A

**Comment by lucascantor** [comment]
In case it might be related, Terraform on my local machine (or maybe just the Terraform extension in Visual Studio Code?) is telling me `risk_score` is not an expected argument:

<img width="703" alt="Screenshot 2023-10-19 at 11 37 12 AM" src="https://github.com/okta/terraform-provider-okta/assets/3372960/3c7c8c17-b425-40ec-bcb6-fb80e79e663c">

Clearly, it _is_ an expected argument, as this code plans and applies successfully with no problems (using the Okta provider version 4.5.0) when the `risk_score` argument is supplied.

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-660890

**Comment by duytiennguyen-okta** [comment]
@lucascantor from your original config file, I don't see the risk_score. Can you check that? Risk score is currently does not have a default value from terraform so I will add that but otherwise I don't see any issue

**Comment by lucascantor** [comment]
@duytiennguyen-okta that's the problem - the original Terraform config file I shared worked just fine before upgrading to 4.5.0 but then resulted in a failed apply after upgrading to 4.5.0, with the Okta API indicating a risk score value is mandatory:
```
errorSummary: conditions.riskScore.level: The field cannot be left blank
```

I believe adding a default risk_score value of `"ANY"` should resolve this, so Terraform doesn't incorrectly plan to change risk_score from `"ANY"` to `null` but then actually fail during Terraform apply.

**Comment by duytiennguyen-okta** [comment]
@lucascantor yeah I get it. When was the last time you ran tf apply? The reason I ask is because risk score is required sometimes ago and that should have result in an error

**Comment by lucascantor** [comment]
@duytiennguyen-okta we were on version 4.4.2 and running `terraform apply` just fine as recently as October 16, until we upgraded to version 4.5.0 on October 18.

Also, [you just added the `risk_score` argument to the `okta_app_signon_policy_rule` resource in the 4.5.0 release](https://github.com/okta/terraform-provider-okta/releases/tag/v4.5.0), so it definitely couldn't have been required before then, right...?
