### ISSUE TITLE
OAuth app failing to list policies to create Okta saml app

### ISSUE THREAD

**Issue by tbronsonCoveo** [okta/terraform-provider-okta#1773]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
When trying to create an Okta SAML app, we are getting an error saying our Okta provider token doesn't have the required scopes.
We use an Okta OAuth app to pass credentials to our provider. It worked fine with the existing scopes about ~1 year ago, but we haven't required creating new apps until this month, which has revealed the issue. 

Since we went from 3.x to 4.x provider, we also can't revert easily to find when the issue happened.
Through my research in this repo's git history, I can't tell what major changes could have caused this. So this could also be related to the API instead.

### Terraform Version
terraform: v1.5.2
okta provider: 4.4.2

### Affected Resource(s)

- okta_app_oauth
- okta_app_saml

### Terraform Configuration Files

```hcl
# Our automated deployments pass this app's credentials to the Okta provider to create new apps.
# These required scopes were sufficient last year. Looking through Okta documentation, 
# there still is only one scope for reading policies which is included.
resource "okta_app_oauth_api_scope" "terraform_app_admin" {
  app_id = okta_app_oauth.terraform_app_admin.id
  issuer = "https://company-cloud.okta.com"
  scopes = [
    "okta.apps.manage",
    "okta.apps.read",
    "okta.groups.read",
    "okta.policies.read",
  ]
}

# This is an example app that we are trying to create. The Okta provider uses the above OAuth app credentials.
resource "okta_app_saml" "snowflake" {
  preconfigured_app = "snowflake"
  label             = "Snowflake - ${var.env} - ${var.region}"
  app_settings_json = jsonencode({
    subDomain = local.privatelink_regionless_domain
  })

  auto_submit_toolbar = true
}

```

### Expected Behavior

Create a new Okta SAML app using permissions granted from an OAuth App. It previously worked fine with Okta provider 3.21.0 (in 2022). 

### Actual Behavior
Provider gets an error from the API by calling an endpoint that our app doesn't have the required scopes. I can't figure out what scope it is missing as we already do give read access to Okta policies.
```
╷
│ Error: failed to set authentication policy for an SAML application: error finding default ACCESS_POLICY the API returned an error: The access token provided does not contain the required scopes.
│ 
│   with okta_app_saml.snowflake_2,
│   on okta_snowflake_app.tf line 14, in resource "okta_app_saml" "snowflake_2":
│   14: resource "okta_app_saml" "snowflake_2" {
│ 
╵
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

n/a

### References

- n/a

**Comment by monde** [comment]
@tbronsonCoveo the code where that error is coming from is at:
https://github.com/okta/terraform-provider-okta/blob/master/okta/policy.go#L259-L289
Specifically, it is calling the `GET /api/v1/policies` endpoint https://developer.okta.com/docs/api/openapi/okta-management/management/tag/Policy/ . I'm assuming your Okta TF provider is using OAuth authentication (given the error message) and calling `GET /api/v1/policies` requires the grant `okta.policies.read`.

So does your provider config have that scope in its scopes list?
```
provider "okta" {
  org_name = "[ORG NAME e.g. dev-123456]"
  base_url = "[okta.com|oktapreview.com]"
  client_id = "[APP CLIENT_ID]"
  private_key_id = "[PRIVATE KEY ID - KID]"
  private_key = "[PRIVATE KEY]"
  scopes = "okta.policies.read, ... [COMMA,SEPARATED,SCOPE,VALUES]"
}
```
And does the app associated with your Terrform authentication `client_id = "[APP CLIENT_ID]"` have the `okta.policies.read` scope granted to it?

Those two points are completely different from the scopes that your are referencing in `resource "okta_app_oauth_api_scope" "terraform_app_admin"`

**Comment by monde** [comment]
Provider config settings listed here https://registry.terraform.io/providers/okta/okta/latest/docs

**Comment by tbronsonCoveo** [comment]
> @tbronsonCoveo the code where that error is coming from is at: https://github.com/okta/terraform-provider-okta/blob/master/okta/policy.go#L259-L289 Specifically, it is calling the `GET /api/v1/policies` endpoint https://developer.okta.com/docs/api/openapi/okta-management/management/tag/Policy/ . I'm assuming your Okta TF provider is using OAuth authentication (given the error message) and calling `GET /api/v1/policies` requires the grant `okta.policies.read`.
> 
> So does your provider config have that scope in its scopes list?
> 
> ```
> provider "okta" {
>   org_name = "[ORG NAME e.g. dev-123456]"
>   base_url = "[okta.com|oktapreview.com]"
>   client_id = "[APP CLIENT_ID]"
>   private_key_id = "[PRIVATE KEY ID - KID]"
>   private_key = "[PRIVATE KEY]"
>   scopes = "okta.policies.read, ... [COMMA,SEPARATED,SCOPE,VALUES]"
> }
> ```
> 
> And does the app associated with your Terrform authentication `client_id = "[APP CLIENT_ID]"` have the `okta.policies.read` scope granted to it?
> 
> Those two points are completely different from the scopes that your are referencing in `resource "okta_app_oauth_api_scope" "terraform_app_admin"`

Ah you are right. We output the scopes from the OAuth app and pipe them into the provider so I didn't second guess it. But as it turns out that output didn't update when I added the new read.policies scope (due to  an implementation reason unrelated to this tf provider). Our provider was not being transferred the updated output which contained the "read.policies" scope. 

Apologies for the noise, I fixed it and it works now.
Thank you!

**Comment by monde** [comment]
Great to hear this @tbronsonCoveo !
