### ISSUE TITLE
datasource_okta_group - `limit` value 

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1783]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Expected Behavior

We should throw an explicit error if okta_group would return an non-deterministic result

### Actual Behavior

we [set `limit` to `1`](https://github.com/okta/terraform-provider-okta/blob/master/okta/data_source_okta_group.go#L88) rather than 2 and then explicitly check the length after

I expect that this could lead to buggy behavior where two or more groups match the dataSource criteria

### References

- #0000

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-663326
