### ISSUE TITLE
IdP Request / Response Signature Algorithms not expected on okta_idp_social

### ISSUE THREAD

**Issue by Pigment-RomainLoisel** [okta/terraform-provider-okta#1790]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.6.2
+ provider registry.terraform.io/hashicorp/google v5.3.0
+ provider registry.terraform.io/hashicorp/google-beta v5.3.0
+ provider registry.terraform.io/okta/okta v4.5
```

### Affected Resource(s)

- okta_idp_social

### Terraform Configuration Files

```hcl
resource "okta_idp_social" "resource" {
  ...

  request_signature_algorithm  = "SHA-256"
  response_signature_algorithm = "SHA-256"
  status                       = "ACTIVE"
}
```

### Debug Output

```
│ Error: Unsupported argument
│ 
│   on ../../../modules/okta/identity_providers.tf line 21, in resource "okta_idp_social" "resource":
│   21:   request_signature_algorithm  = "SHA-256"
│ 
│ An argument named "request_signature_algorithm" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on ../../../modules/okta/identity_providers.tf line 22, in resource "okta_idp_social" "resource":
│   22:   response_signature_algorithm = "SHA-256"
│ 
│ An argument named "response_signature_algorithm" is not expected here.
```

### Expected Behavior

According to documentation, field should be valid.
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/idp_social#request_signature_algorithm

### Actual Behavior

```
An argument named "request_signature_algorithm" is not expected here.
An argument named "response_signature_algorithm" is not expected here.
```

### Steps to Reproduce

1. `terraform apply`

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-663335

**Comment by monde** [comment]
@Pigment-RomainLoisel I double checked the code, this arguments are listed incorrectly in the idp social resource. I think it was a copy paste error from the idp saml docs back in 2021. PR #1814 updates the docs.

- `request_signature_algorithm`
- `request_signature_scope`
- `response_signature_algorithm`
- `response_signature_scope`
