### ISSUE TITLE
data "okta_group" breaks due to different in behaviour in 4.6.0

### ISSUE THREAD

**Issue by fatbasstard** [okta/terraform-provider-okta#1797]
With the latest versions (`4.6.0`) there has been a change in the Group search behaviour (https://github.com/okta/terraform-provider-okta/pull/1794).

This impacts the `okta_group` datasource from an "exact" search to a "starts with" search which I think is not the intention.

Have to okta groups:

- `my_employees`
- `my_employees_pmo`

And retrieve the first with a datasource:

```hcl
data "okta_group" "my_employees" {
  name = "my_employees"
}
```

Which now gives the following error:

```log
Error: group starting with name "my-employees" matches 2 groups, select a more precise name parameter
with data.okta_group.sbp_employee
on xxxx.tf line xx, in data "okta_group" "my-employees":
data "okta_group" "my-employees" {
```

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### References

- [#1794](https://github.com/okta/terraform-provider-okta/pull/1794)

**Comment by fatbasstard** [comment]
So looks documented: https://registry.terraform.io/providers/okta/okta/latest/docs/data-sources/group#arguments-reference

But this is a functional change with a pretty big impact it seems

**Comment by monde** [comment]
I see how this change is a flaw from your feedback @fatbasstard https://github.com/okta/terraform-provider-okta/blob/master/okta/data_source_okta_group.go#L106-L110
Although the query can return multiple groups based on name, if one of the names is an exact match, then the group has been found.

I will do a bug fix and release today.

**Comment by monde** [comment]
cc'ing the 👍's @sviatlo @mbelchev
