### ISSUE TITLE
Lost all app asignments

### ISSUE THREAD

**Issue by fatbasstard** [okta/terraform-provider-okta#1798]
Haven't found the detail/culprit exaclty, but seems related to https://github.com/okta/terraform-provider-okta/issues/1797.

After a Terraform apply (with no notible changes in the plan) this morning we've lost ALL group assignments to the Github application (so the entire team is blocked working).

 Looking at the timing, the related issue and the change (https://github.com/okta/terraform-provider-okta/pull/1794) I've lost trust in the latest version. 

Now pinning to the previous version.

Just wanted to throw this out here...

**Comment by monde** [comment]
@fatbasstard I see the flaw you pointed out in #1797 but the data source `okta_group` doesn't make any create or update calls. Just looking for clarification here how the flaw in #1797 caused your config to un-assign groups to a specific application? This is awful to hear about and I want to make sure to get this fixed correctly.

Reproducing locally when I start with a group "Test More" and the name parameter `Test Mo` then my plan is ok, so I apply. Then in the Admin UI I create another group "Test Most" then the next plan causes an error `Error: group starting with name "Test Mo" matches 2 groups, select a more precise name parameter`. At that point the error is blocking my plan and even if I try to apply terraform exits with error 1 at the command line.

**Comment by monde** [comment]
Fix for multiple groups matching name query flaw in ds `okta_group` in #1797 released https://github.com/okta/terraform-provider-okta/releases/tag/v4.6.1

**Comment by fatbasstard** [comment]
Hi @monde ,

Mainly wanted to put it out here, I had a really bad day yesterday 🤣  It could have been a unhappy incident, where the root cause is in Okta, Github, Terraform or all of the above. Thanks for the fix applied at least, that really helps!

And happy to hear that that datasource is truly not making any changes, gives back a bit of trust. 

We're back online and stable now, I will remove the version lock soonish (today or monday) and if everything stays online as it should I'll close the issue then

**Comment by monde** [comment]
Thanks @fatbasstard . I'll keep this bug open for a while in case others land here because of v4.6.0 and point out that they should update to https://github.com/okta/terraform-provider-okta/releases/tag/v4.6.1 or greater.

**Comment by fatbasstard** [comment]
Lost all assignments to our Github app again. Investigating how/why/what happened

**Comment by fatbasstard** [comment]
Got it! 

Summary: We were using `okta_app_group_assignments` and `okta_app_group_assignment` mixed together on different locations.

So totally unrelated to this provider release.

1st outage: refactored a `okta_app_group_assignments` with a foreach into a foreach using `okta_app_group_assignments`. Removing `okta_app_group_assignments` caused all assingments to be lost

2nd outage: When removing some "shadow infrastructe" (to call it like that) I removed some additional Github-team assignments. 2 teams, but assigned with a `okta_app_group_assignments` resource. Remove the resource removed ALL assignments...

We also lost other assignments, but since it's all in code (🎉 ) a simple Terraform rerun fixed it. GIthub is just a bit more annoying: You get kicked out of the org, emails are send, when added again you have to explicitly join, reauthenticate tokens/ssh keys etc.

So some lessons learned here 😉  One of them: Don't assign groups to an application on multiple places. And especially not using the `okta_app_group_assignmentS` resource....

**Comment by monde** [comment]
Thanks for the follow up @fatbasstard . It made me feel ill to hear you experienced this. And I'm happy you've shared your experience here should some one in the future search in the GH issues with a similar situation.
