### ISSUE TITLE
okta_inline_hook seems to require the type parameter at the very least when using the channel argument

### ISSUE THREAD

**Issue by zamerman** [okta/terraform-provider-okta#180]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
0.12.21
```

### Affected Resource(s)

* okta_inline_hook

### Terraform Configuration Files

```hcl
provider "okta" {
  org_name = "#########"
  base_url = "#########"
  api_token = "##########"
}

resource "okta_inline_hook" "registration_hook" {
  name    = "registration_hook"
  version = "1.0.0"
  type    = "com.okta.user.pre-registration"

  channel = {
    version = "1.0.0"
    uri     = "PUBLICLY_ACCESSIBLE_URL" # https://www.google.com for example
    method  = "POST"
  }

  auth = {
    key   = "Authorization"
    type  = "HEADER"
    value = "secret"
   }
}
```

### Expected Behavior
When executed Terraform should send a POST api request to the okta instance in order to create an inline hook. With the following body.
```json
{
    "name": "registration_hook",
    "type": "com.okta.user.pre-registration",
    "version": "1.0.0",
    "channel": {
        "type": "HTTP",
        "version": "1.0.0",
        "config": {
            "uri": "https://www.google.com",
            "method": "POST",
            "authScheme": {
                "type": "HEADER",
                "key": "Authorization",
                "value": "secret"
            }
        }
    }
}
```

### Actual Behavior
However, instead when executed the following error is received.
```
Error: The API returned an error: The request body was not well-formed.

on main.tf line 7, in resource "okta_inline_hook" "registration_hook":
   7: resource "okta_inline_hook" "registration_hook" {
```

A solution to this is to add a type argument to the map of the channel argument with the value of "HTTP" as follows:
```hcl
provider "okta" {
  org_name = "#########"
  base_url = "#########"
  api_token = "##########"
}

resource "okta_inline_hook" "registration_hook" {
  name    = "registration_hook"
  version = "1.0.0"
  type    = "com.okta.user.pre-registration"

  channel = {
    version = "1.0.0"
    uri     = "PUBLICLY_ACCESSIBLE_URL" # https://www.google.com for example
    type = "HTTP"
    method  = "POST"
  }

  auth = {
    key   = "Authorization"
    type  = "HEADER"
    value = "secret"
   }
}
```

When executed the apply succeeds and the inline_hook is created successfully. According to the documentation for the okta_inline_hook.

"type - (Optional) The type of hook to trigger. Currently only "HTTP" is supported."

The type argument of channel is optional, and it only supports the HTTP value. Perhaps, in the future there will be more values and so it shouldn't default to "HTTP" but then at the very least it should be required.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### References

* https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/inline_hook#channel

**Comment by moein** [comment]
Can we reopen this issue? Since yesterday I've been going crazy thinking I'm doing something wrong but it's basically type field being optional in terraform and being mandatory in the api.
Even worse is that the api just gives a generic error about the request not being well-formed instead of saying it's missing type.

**Comment by bogdanprodan-okta** [comment]
Hi @moein and @zamerman! So you still encounter this issue?

**Comment by moein** [comment]
@bogdanprodan-okta Unless you have made type field in channel mandatory it should be still an issue.
Clearly both me and @zamerman already have put the type in channel but it's for future developers that might not put the type and get the generic error from api.
I could do a PR to make type mandatory for channel.

**Comment by bogdanprodan-okta** [comment]
@moein I've added [this code](https://github.com/oktadeveloper/terraform-provider-okta/blob/master/okta/resource_okta_inline_hooks.go#L246), so by default, `method` is always `POST`.

**Comment by moein** [comment]
@bogdanprodan-okta The piece of code you referred to effictively fixes this issue. Sorry for the confusion

**Comment by bogdanprodan-okta** [comment]
Hi @moein! Thanks for the response! In this case, I'm closing this issue.
