### ISSUE TITLE
okta_app_signon_policy_rule is throwing error - > Causes: errorSummary: conditions: Invalid condition type specified: riskScore 

### ISSUE THREAD

**Issue by NiravShahHelix** [okta/terraform-provider-okta#1802]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
- With okta provider 4.60 and above, there is a default risk_score("ANY") under okta_app_signon_policy_rule. When I try to apply this plan, I am shown specified error. 

- I tried to omit this field by using okta provider 4.5.0. But in that case I am getting following error:
```hcl
Error: failed to create app sign on policy rule: the API returned an error: Api validation failed: conditions.riskScore.level. Causes: errorSummary: conditions.riskScore.level: The field cannot be left blank, errorSummary: conditions: Invalid condition type specified: riskScore.
```
- I also tried different risk levels with 4.6.0(HIGH, LOW, MEDIUM), but no help.

### Terraform Version

v1.6.3

### Affected Resource(s)

okta_app_signon_policy_rule (okta provider version 4.6.1)

### Terraform Configuration Files

```hcl
resource "okta_app_signon_policy_rule" "sso" {
  policy_id   = okta_app_signon_policy.default.id
  name        = "MY Rule"
  priority    = 1
  factor_mode = "1FA"
  groups_included = [
    okta_group.sso.id
  ]
}
```

### Debug Output
https://gist.github.com/NiravShahHelix/f0013a1dda7fef83522af04459c9084b

### Panic Output

```hcl
Error: failed to create app sign on policy rule: the API returned an error: Api validation failed: conditions. Causes: errorSummary: conditions: Invalid condition type specified: riskScore.
```

### Expected Behavior
Plan should be applied successfully

#### Can this be done in the Admin UI?
I don't know

#### Can this be done in the actual API call?
I don't know

### Actual Behavior

Terraform apply fails with specified error.
### Steps to Reproduce

1. `terraform apply`

### References
https://registry.terraform.io/providers/okta/okta/4.6.1/docs/resources/app_signon_policy_rule#risk_score

**Comment by exitcode0** [comment]
@NiravShahHelix Are you on an OIE or classic Okta instance?
[This article](https://support.okta.com/help/s/article/How-to-Check-the-Version-Number-of-an-Okta-TenantOrg?language=en_US) outlines how to check this

**Comment by NiravShahHelix** [comment]
> @NiravShahHelix Are you on an OIE or classic Okta instance? [This article](https://support.okta.com/help/s/article/How-to-Check-the-Version-Number-of-an-Okta-TenantOrg?language=en_US) outlines how to check this

@exitcode0  Thanks for reaching out. 

The version number I can see in our staging instance is 'Version 2023.10.2 E' So it's an OIE instance.

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-665605

**Comment by NiravShahHelix** [comment]
Hi @duytiennguyen-okta Wanted know usually how much time does it take to resolve such issues?

**Comment by jefftaylor-okta** [comment]
@NiravShahHelix I just tested the functionality and took a look at your output. It looks like you are using *`riskScore`* instead of `risk_score`. Please update your module and try it again.

```log
2023-11-03T11:08:48.802-0400 [ERROR] vertex "okta_app_signon_policy_rule.sso" error: failed to create app sign on policy rule: the API returned an error: Api validation failed: conditions. Causes: errorSummary: conditions: Invalid condition type specified: riskScore.
```

**Comment by NiravShahHelix** [comment]
@jefftaylor-okta No I am using risk_score only. The error message shows different format. 
The issue appears even when I don't pass that argument at all (in which case okta inserts default value for risk_score)

**Comment by duytiennguyen-okta** [comment]
@NiravShahHelix I cannot reproduce the issue. Can you provided the TF script and the debug log from `TF_LOG=debug terraform apply`?

**Comment by NiravShahHelix** [comment]
@duytiennguyen-okta Can' share entire debug logs as it may contain some private information.
Please see this gist: https://gist.github.com/NiravShahHelix/f0013a1dda7fef83522af04459c9084b

Kindly let me know if you are looking for something specific in the logs. I can try to find and share it with you.
Also, TF config file is already there in the issue description.

**Comment by emanor-okta** [comment]
@NiravShahHelix - thank you.
I have repo'd this and will share the debug logs with @duytiennguyen-okta
