### ISSUE TITLE
okta_theme resource requires theme_id

### ISSUE THREAD

**Issue by ClintonianSunBlaster** [okta/terraform-provider-okta#1823]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
1.6.2

### Affected Resource(s)

- okta_theme

### Terraform Configuration Files

```hcl
resource "okta_theme" "our_theme" {
  brand_id                               = okta_brand.our_brand.id
  logo                                   = "files/images/logo-resize-420-120.png"
  favicon                                = "files/images/favicon.ico"
  primary_color_hex                      = "#005ead"
  secondary_color_hex                    = "#005ead"
  primary_color_contrast_hex             = "#ffffff"
  secondary_color_contrast_hex           = "#ffffff"
  sign_in_page_touch_point_variant       = "BACKGROUND_SECONDARY_COLOR"
  end_user_dashboard_touch_point_variant = "WHITE_LOGO_BACKGROUND"
  error_page_touch_point_variant         = "BACKGROUND_SECONDARY_COLOR"
  email_template_touch_point_variant     = "FULL_THEME"
}
```

### Expected Behavior

A theme should be created for the our_brand brand

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

IDK

### Actual Behavior

'terraform apply' produces the following error:

│ Error: theme_id required to create theme
│ 
│   with module.branding.okta_theme,
│   on ../../modules/okta/customizations/branding/main.tf line 40, in resource "okta_theme" "our_theme":
│   40: resource "okta_theme" "our_theme" {

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The documentation for okta_theme (https://registry.terraform.io/providers/okta/okta/4.6.0/docs/resources/theme) indicated that theme_id is optional but that does not appear to be the case. Instead, theme_id is a required element which defeats the purpose of a TF resource. How can we know the id of an object we're haven't created yet?

### References

- #0000

**Comment by monde** [comment]
@ClintonianSunBlaster "This resource allows you to get and update an Okta - The Okta Management API does not have a true Create or Delete for a theme. Therefore, the theme resource must be imported first into the terraform state before updates can be applied to the theme."
