### ISSUE TITLE
okta_brand requires email_domain_id

### ISSUE THREAD

**Issue by ClintonianSunBlaster** [okta/terraform-provider-okta#1824]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
1.6.2

### Affected Resource(s)

- okta_brand
- okta_email_domain

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "okta_brand" "our_brand" {
  name                           = "Our Brand"
  agree_to_custom_privacy_policy = true
  remove_powered_by_okta         = true
  email_domain_id                = var.email_domain_id 
}
```

### Expected Behavior

okta_brand documentation (https://registry.terraform.io/providers/okta/okta/4.6.0/docs/resources/brand) lists the email_domain_id as an optional element but it is not. It is a required element if you have set a brand_id for the okta_email_domain resource. This creates a circular dependency.

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

I don't know

### Actual Behavior
Subsequent runs of 'terraform apply' will disassociate the okta_brand from its okta_email_domain unless the email_domain_id is hard coded into the okta_brand resource block.

### Steps to Reproduce

1. Create okta_brand resource block but do not set an email_domain_id
2. Create okta_email_domain resource block and set a brand_id to the id of the brand that was created in step 1.
3. Run 'terraform apply' and both the brand and email domain are both created perfectly.
4. Run 'terraform plan' and 'terraform apply' a 2nd time and Terraform will disassociate the email_domain_id from the okta_brand (see below)

```
 module.branding.okta_brand.our_brand will be updated in-place
  ~ resource "okta_brand" "our_brand" {
      ~ brand_id                       = "bndbe6h9i2DDDOO9sc1d7" -> (known after apply)
      - email_domain_id                = "OeDFFFRAsu2DSNy6L1d7" -> null
        id                             = "bndbe6h9i23gYB9sc1d7"
      ~ is_default                     = false -> (known after apply)
      ~ links                          = jsonencode(
```

### References

- #0000

**Comment by monde** [comment]
Notes before TF triage - I can see the ACC tests for `okta_brand` include `local` so I'm not sure if this resource fluctuates its behavior based on what argument combinations it takes.

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-669848
