### ISSUE TITLE
`okta_app_user_schema_property` - infer `array_enum` from `array_one_of`

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1828]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At some point in the future (probably V5 or beyond)
Should we consider updating `okta_app_user_schema_property` so that `array_enum` can be inferred from the `one_of` blocks?

I think this would result in a cleaner resource and would allow for inline support of the `dynamic` block, currently I think you'd need to pass it in via a local variable

### New or Affected Resource(s)

- resource_okta_app_user_schema_property

#### Current HCL

```hcl
resource "okta_app_bookmark" "okta" {
  label = "okta"
  url   = "https://www.okta.com"
}
locals {
  example_var = [
    { title = "object 1", const = jsonencode({ value = "test_value_1" }) },
    { title = "object 2", const = jsonencode({ value = "test_value_2" }) },
    # repeat for your hundreds 200-300 of enums across ~30 attrs
  ]
}
resource "okta_app_user_schema_property" "test" {
  app_id      = okta_app_bookmark.google.id
  index       = "testAcc_replace_with_uuid"
  title       = "terraform acceptance test"
  type        = "array"
  description = "testing"
  required    = false
  permissions = "READ_ONLY"
  master      = "PROFILE_MASTER"
  array_type  = "object"

  array_enum  = local.example_var[*].title

  dynamic "array_one_of" {
    for_each = local.example_var
    content {
      title = array_one_of.value.title
      const = array_one_of.value.const
    }
  }
}
```

#### Future HCL

```hcl
resource "okta_app_bookmark" "okta" {
  label = "okta"
  url   = "https://www.okta.com"
}
resource "okta_app_user_schema_property" "test" {
  app_id      = okta_app_bookmark.google.id
  index       = "testAcc_replace_with_uuid"
  title       = "terraform acceptance test"
  type        = "array"
  description = "testing"
  required    = false
  permissions = "READ_ONLY"
  master      = "PROFILE_MASTER"
  array_type  = "object"
  
  # array_enum  = local.example_var[*].title

  dynamic "array_one_of" {
    for_each = [
    { title = "object 1", const = jsonencode({ value = "test_value_1" }) },
    { title = "object 2", const = jsonencode({ value = "test_value_2" }) },
    # repeat for your hundreds 200-300 of enums across ~30 attrs
  ]
    content {
      title = array_one_of.value.title
      const = array_one_of.value.const
    }
  }
}
```

### References

- #1745
- #1827

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-671033

**Comment by wrprice** [comment]
Related: https://github.com/okta/terraform-provider-okta/issues/1840#issuecomment-1845676717
