### ISSUE TITLE
v4.6.2 suddenly fails with cannot unmarshal object into Go struct field _UserGetSingleton.type of type string

### ISSUE THREAD

**Issue by dmikalova** [okta/terraform-provider-okta#1836]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
terraform -v
Terraform v1.5.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.26.0
+ provider registry.terraform.io/hashicorp/external v2.3.2
+ provider registry.terraform.io/hashicorp/vault v3.23.0
+ provider registry.terraform.io/okta/okta v4.6.2
```

### Affected Resource(s)

- okta provider configuration

### Terraform Configuration Files

```hcl
provider "okta" {
  api_token = var.okta_api_token
  base_url  = "okta.com"
  org_name  = "my_org"
}
```

### Debug Output

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: [ERROR] failed validate configuration: error with v3 SDK client: json: cannot unmarshal object into Go struct field _UserGetSingleton.type of type string
│
│   with provider["registry.terraform.io/okta/okta"],
│   on main.tf line 25, in provider "okta":
│   25: provider "okta" {
```

### Expected Behavior

During plan/apply, the provider should be able to configure itself like it did with v4.6.1 using the same configuration.

### Actual Behavior

The provider errors with the above output.

### Steps to Reproduce

1. Use Okta v4.6.2
2. `terraform apply`

**Comment by SamuZad** [comment]
Can verify, downgrading to Okta v4.6.1 makes the error go away and the plan/apply succeeds

**Comment by ben-contreras** [comment]
I am getting the same error with v3.36

**Comment by tgoodsell-tempus** [comment]
FYI, this appears to be the source of the issue based on the research I've done so far: https://github.com/okta/okta-sdk-golang/issues/419#issuecomment-1832786664

**Comment by pro4tlzz** [comment]
> FYI, this appears to be the source of the issue based on the research I've done so far: [okta/okta-sdk-golang#419 (comment)](https://github.com/okta/okta-sdk-golang/issues/419#issuecomment-1832786664)

Thanks for investigating. This error a slight panic this morning.

**Comment by duytiennguyen-okta** [comment]
It was a panic for me too. Please update to 4.6.3
