### ISSUE TITLE
Add Active directory  okta_user_type and  okta_user_attributes

### ISSUE THREAD

**Issue by SBerda** [okta/terraform-provider-okta#184]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Woud like to be able to configure these fields using terraform  (Directory -> Profile editor ) :

[https://imgur.com/QIKZPML](https://imgur.com/QIKZPML)
[https://imgur.com/yNjcuny](https://imgur.com/yNjcuny)

* okta_user_type
* okta_user_attributes

* data.okta_user_type
* data.okta_user_attributes

Thank you, Have a nice day

**Comment by bogdanprodan-okta** [comment]
To configure these fields via terraform you can use `okta_user_base_schema` and `okta_user_schema`
