### ISSUE TITLE
When trying to apply an `okta_brand` resource with a `default_app_classic_application_uri` value, it will result in an error and actually remove the current value in the GUI

### ISSUE THREAD

**Issue by mvitt** [okta/terraform-provider-okta#1846]
When trying to apply an `okta_brand` resource with a `default_app_classic_application_uri` value, it will result in an error and actually remove the current value in the GUI.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
1.5.7

### Affected Resource(s)

- `okta_brand`

### Terraform Configuration Files

```hcl
resource "okta_brand" "custom_brand" {
  name                                = var.brand_name
  default_app_classic_application_uri = var.brand_app_redirect_url
  remove_powered_by_okta              = true
}
```

### Debug Output

<img width="1133" alt="oktaError" src="https://github.com/okta/terraform-provider-okta/assets/31548861/cf21e7f2-55bd-455c-8f80-ce16b086a8ff">

### Expected Behavior

The default application for sign in widget setting (under a brand's "Pages" section) should be populated by this value not unset:
<img width="1502" alt="oktaImage" src="https://github.com/okta/terraform-provider-okta/assets/31548861/a7a252dd-3abf-4aee-91f1-a4bcadb1c53d">

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

Yes

### Actual Behavior

I get an error (as seen above) and it gets wiped out in the GUI

### Steps to Reproduce

1. `terraform apply` on a `okta_brand` resource that has a `default_app_classic_application_uri` value

### Important Factoids

I am doing this on an Okta org that is using the classic engine

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-675530

**Comment by duytiennguyen-okta** [comment]
Close with #1877
