### ISSUE TITLE
When running `Terraform apply` on the `okta_brand` it unlinks the vanity email address associated with the brand

### ISSUE THREAD

**Issue by mvitt** [okta/terraform-provider-okta#1847]
When running `Terraform apply` on the `okta_brand` it unlinks the vanity email address associated with the brand. This seems to be due to Terraform wanting to remove the `links` argument (Which I believe should actually be an non-editable attribute instead) 

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
1.5.7

### Affected Resource(s)

- `okta_brand`

### Terraform Configuration Files

```hcl
resource "okta_brand" "custom_brand" {
  name                                = var.brand_name
  default_app_classic_application_uri = var.brand_app_redirect_url
  remove_powered_by_okta              = true
}
```

### Debug Output

<img width="785" alt="Screenshot 2023-12-07 at 10 24 44 AM" src="https://github.com/okta/terraform-provider-okta/assets/31548861/a57c8a6f-fc2d-4f38-bd0a-0811c6acc029">

### Expected Behavior

The vanity email that is associated with the brand should not be unlinked and, most likely, the `links` argument should not be an argument, but an attribute.

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

Yes

### Actual Behavior

I get an error (as seen above) and it gets wiped out in the GUI

### Steps to Reproduce

1. `terraform apply` on a `okta_brand` resource that has a  vanity email domain associated with it.

### Important Factoids

I am doing this on an Okta org that is using the classic engine

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-675530

**Comment by duytiennguyen-okta** [comment]
I have checked this issue. `Links` has always been computed and was never overwritten. The `links` before and after update is the same. That probably just terraform issue
