### ISSUE TITLE
Add request throttling to avoid rate limit violations

### ISSUE THREAD

**Issue by adw1n** [okta/terraform-provider-okta#186]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Terraform Okta provider causes rate limit violations. This is problematic for users who have apps that rely on certain Okta APIs. A rate limit violation caused by Terraform Okta provider often effectively causes app downtime. Some organizations that are on the highest pricing plan might have significantly higher rate limits than other organizations on lower pricing plans. Because of that this problem might have gone unnoticed thus far.

Example: `terraform plan` and `terraform apply` cause `/api/v1/apps` API endpoint rate limit violation by making lots of these requests:
1. GET /api/v1/apps/{app_id}/groups?limit=200
2. GET /api/v1/apps/{app_id}/users?limit=200
3. GET /api/v1/apps/{app_id}/groups/{group_id}

We got confirmation from Okta team that all of these endpoints share the same underlying `/api/v1/apps` endpoint rate limit.

Imagine for a moment that your app uses Okta API endpoints that share the `/api/v1/apps` rate limit. When a rate limit violation caused by Terraform Okta provider happens your users start to see errors because some of your app's functionality that relies on `/api/v1/apps` stops working until the rate limit resets.

### Proposal

I suggest we add a new provider config argument https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs#argument-reference:

> `max_requests` - (Optional) (Experimental) controls how many requests can be made to each Okta endpoint by the provider. It's used to prevent rate limit violations. By default request throttling is disabled meaning provider might cause rate limits violations. Expects an integer representing a percentage value - e.g. `40`. `40` means that provider is allowed to use up to 40% of the rate limit. E.g. assuming rate limit for `/api/v1/apps` endpoint is 25, up to 10 requests will be made that burn `/api/v1/apps` rate limit. Currently request throttling works only for `/api/v1/apps` rate limit.

I'd mark this feature as "Experimental" for 2 months to get some feedback from early adopters. I know for sure my organization will start using this feature on day one.

Accepting a signle percentage value is the easiest feature to implement. A more advanced config could look like this:
```
{
	"/api/v1/apps": 40,
	"/api/v1/apps/{id}": 100,
	"/api/v1/groups/{id}": 80
}
```

### Solution

I propose we start with only supporting throttling of requests that burn the `/api/v1/apps` rate limit. It's by far the most pressing problem because `/api/v1/apps` rate limit is significantly lower than any other endpoint.

I think we should use http client's transport to throttle the requests. I propose we change https://github.com/oktadeveloper/terraform-provider-okta/blob/b563d6cbbb2d9e69f76f2ca2ed0ae5a217f221ef/okta/config.go#L48 to:
```
	httpClient.Transport = logging.NewTransport("Okta", httpClient.Transport)
	if c.max_requests < 100 {
		httpClient.Transport = NewRequestThrottleTransport(httpClient.Transport, c.max_requests)
	}
```
RequestThrottleTransport pseudocode:
```
type RequestThrottleTransport struct {
	base http.RoundTripper
	maxRequests int
}
func (throttleTransport *RequestThrottleTransport) RoundTrip(req *http.Request) (res *http.Response, err error) {
	// Check if req uses one of the supported endpoints that we know how throttle.
	// Check how many requests were made during current rate limit interval.
	// Do time.Sleep(...) before making the request if needed.
	resp, err := throttleTransport.base.RoundTrip(req)
	// check response headers, save relevant information
	return resp, err
}
```

Please check https://github.com/oktadeveloper/terraform-provider-okta/pull/187

### Problem with rate limit docs

https://developer.okta.com/docs/reference/rl-global-mgmt/ rate limit documentation is really confusing. By reading the docs you'd never guess that these requests:
1. GET /api/v1/apps/{app_id}/groups?limit=200
2. GET /api/v1/apps/{app_id}/users?limit=200
3. GET /api/v1/apps/{app_id}/groups/{group_id}

share the same rate limit with `/api/v1/apps` endpoint. It will be very hard to implement correct rate limit handling of rate limits other than `/api/v1/apps` for community members that aren't Okta employees.

### FAQ
1. > Does `backoff`, `min_wait_seconds` and `max_wait_seconds` solve your issue?

    No because these settings control the provider's behavior after the rate limit violation happened. We want to avoid rate limit violation from happening at all cost.
2. > Can't you use `-parellelism=1` as in `terraform apply -parellelism=1` to mitigate this issue?

    Even with `-parellelism=1` enough requests are made to Okta to cause a rate limit violation.
3. > What about `sleep()`? Does that help?

    sleep will have no inpact on the `plan` phase which causes the rate limit violations.
4. > Is there any workaround that Terraform Okta provider users can use right now?

    You have to either maintain a custom fork or use a proxy that slows down requests made to Okta. With proxy you have to be really careful to not cause timeouts and if you are a Terraform Cloud user you can't use the proxy workaround.

5. > Latest Golang Okta SDK offers request retries on 429 response status code. Surely that solves your problem, right?

    It doesn't help us at all. We can't afford to have the rate limit completely exhausted by terraform-provider-okta. If terraform-provider-okta uses the whole rate limit allowance our app will become unusable until the rate limit resets. We want to tell terraform-provider-okta to only use up to 25% of the rate limit and leave the remaining 75% for our app.

**Comment by ymylei** [comment]
Excellent idea! I'm glad you're starting work on this type of control for the provider!

The main comment I have is regarding how we'll detect / manage the API limits. I think we may be able to avoid a lot of hard-coding of the various endpoints by using a combination of the URI, `X-Rate-Limit-Limit`, and `X-Rate-Limit-Remaining` headers. 

Key doc: https://developer.okta.com/docs/reference/rl-best-practices/

In theory, I think we can store an object of some kind which records the last reported values for the two rate limiting headers with each applicable URI we're being limited on. Then we can use the configuration to allow people to set the percentage values they want to start throttling at or raw values.

What're your initial thoughts on that? I'll do a little pondering and play around with a clone of your feature branch to see if I can put this idea to code.

**Comment by adw1n** [comment]
> I think we may be able to avoid a lot of hard-coding of the various endpoints by using a combination of the URI, X-Rate-Limit-Limit, and X-Rate-Limit-Remaining headers.

@ymylei I disagree, to an extent. We should certainly use `X-Rate-Limit-*` and uri path but I am afraid the hardcoding is impossible to avoid for people that don't have internal, undocumented Okta know-how. I really think that throttling only the `/api/v1/apps` endpoint will suffice for most organizations. This endpoint has much lower rate limit, for many organizations just 25 requests per minute. Most other endpoints that the Terraform Okta Provider will reallistacly use have rate limits of >= 100 regardless of the pricing plan. With a rate limit of >= 100 you could probably use `-parallelism 1` and Okta provider would make less than 50 requests a minute to any given endpoint which is a good enough workaround for most people. 

Please check these counter examples (pseudocode):
1. User defines max_requests parameter as:
	```
	{
		"/api/v1/apps": 25%,
		"/api/v1/apps/{app_id}/groups": 25%,
		"/api/v1/apps/{app_id}/users": 25%,
		"/api/v1/apps/{app_id}/groups/{group_id}": 25%,
		"/api/v1/apps/{app_id}": 25%
	}
	```
	Because the setting is always 25% he expects that Terraform Okta Provider will never violate the rate limit on its own. But the user is mistaken because first 4 requests share the exact same rate limit and `4*25% == 100%`.

2. User defines `max_requests` as `25%`.
2.1 5 requests are made to `/api/v1/apps/{app_id}/groups`, we observe `X-Rate-Limit-Remaining` going down from 24 to 20.
2.2 A request is made to `/api/v1/apps/{app_id}/users` and we observe `X-Rate-Limit-Remaining` value 19.
2.3 A request is about to be made again to `/api/v1/apps/{app_id}/users`. Should we sleep before making the request? You could make an argument for both answers but without hardcoding it's impossible to make the decision with certainty.
2.3.1 Answer `yes` because `X-Rate-Limit-Remaining` is 19 out of 25. So our provider used more than 25% of allowed rate limit. Problem is that 5 requests that burned `/api/v1/apps/{app_id}/users` rate limit might have came from user's app instead of the provider in which case we'll sleep unnecesairly.
2.3.2 Answer `no` because  we recorded only 1 `/api/v1/apps/{app_id}/users` request being made from the provider. Okta provider will make another request to `/api/v1/apps/{app_id}/users` which violates users wishes of burning at most `25%` of the rate limit. At this point 7 requests that use `/api/v1/apps` rate limit were made and only `25*25% == 6.25` requests were allowed.


> Then we can use the configuration to allow people to set the percentage values they want to start throttling at or raw values.

I agree that giving the user an option to choose between percentage value or raw value is ideal. I think we should initialy keep it very simple and provide only one option, percentage should be better for most people. Otherwise the PR might drag for months. The `Experimental` label on this config parameter gives us the ability to change the config parameter format over time.

**Comment by adw1n** [comment]
This issue should still be open.

**Comment by gstotts** [comment]
Cloudflare accomplishes this on their provider  with the following.  Not sure if that helps but would love to see something like this on this provider:
- [Cloudflare Example in Docs](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs)
- [Cloudflare Provider RPS](https://github.com/cloudflare/terraform-provider-cloudflare/blob/5d39f78721c55f06c628b77e1bc7025d1a66108b/cloudflare/provider.go#L53-L58)
- [Cloudflare Go SDK RPS Use](https://github.com/cloudflare/cloudflare-go/blob/d372118b194b1e98c4046fc1f5e0daa31cae715c/cloudflare.go#L52-L65)

**Comment by mcrobbj** [comment]
I get rate limiting too, which I dont really undertand when there is only a small change required, Is that not the point of the state file? Alos seems to wrongly think thank I am modifying resources when I am not - resource "okta_app_oauth"
