### ISSUE TITLE
Provider crashes with panic: runtime error: invalid memory address or nil pointer dereference when using data okta_brand

### ISSUE THREAD

**Issue by GraemeMeyerGT** [okta/terraform-provider-okta#1865]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
PS > terraform -v
Terraform v1.6.6
on windows_amd64
```

### Affected Resource(s)

- okta_brand

``` terraform
data "okta_brand" "default" {
  brand_id = "default"
}
```

### Terraform Configuration Files

```hcl
###
# main.tf
###
data "okta_brand" "default" {
  brand_id = "default"
}
```

### Debug Output

https://gist.github.com/GraemeMeyerGT/445e91dedc4f3494fbc63afb1a36ff0b

(I've done my best to redact this)

### Panic Output

```
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.      
╵
╷
│ Error: Plugin did not respond
│
│   with data.okta_brand.default,
│   on main.tf line 1, in data "okta_brand" "default":
│    1: data "okta_brand" "default" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.    
╵

Stack trace from the terraform-provider-okta_v4.6.3.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x139adc6]

goroutine 106 [running]:
github.com/okta/terraform-provider-okta/okta.getDefaultBrand({0x1aacaa8?, 0xc00027dce0?}, {0x1738a60?, 0xc0003db680?})
        github.com/okta/terraform-provider-okta/okta/brand.go:76 +0x226
github.com/okta/terraform-provider-okta/okta.dataSourceBrandRead({0x1aacaa8, 0xc00027dce0}, 0x0?, {0x1738a60?, 0xc0003db680})
        github.com/okta/terraform-provider-okta/okta/data_source_okta_brand.go:34 +0xd5    
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0003a5a40, {0x1aacae0, 0xc00027cd80}, 0xd?, {0x1738a60, 0xc0003db680})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:795 
+0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0003a5a40, {0x1aacae0, 0xc00027cd80}, 0xc0004ff300, {0x1738a60, 0xc0003db680})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:1015 +0x150
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0003293e0, {0x1aacae0?, 0xc0006791a0?}, 0xc0006a4160)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/grpc_provider.go:1249 +0x38f
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadDataSource(0x1aaca38?, {0x1aacae0?, 0xc000678e40?}, 0xc0006a4160)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5muxserver/mux_server_ReadDataSource.go:36 +0x1b5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc00030c6e0, {0x1aacae0?, 0xc0006782a0?}, 0xc000818280)
        github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov5/tf5server/server.go:699 
+0x403
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x17ee1a0?, 0xc00030c6e0}, {0x1aacae0, 0xc0006782a0}, 0xc00079a080, 0x0)      
        github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:503 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ac5a0, {0x1aacae0, 0xc0006781e0}, {0x1ab2218, 0xc0004869c0}, 0xc0008d6000, 0xc0004669c0, 0x25000e8, 0x0)
        google.golang.org/grpc@v1.59.0/server.go:1343 +0xe49
google.golang.org/grpc.(*Server).handleStream(0xc0001ac5a0, {0x1ab2218, 0xc0004869c0}, 0xc0008d6000)
        google.golang.org/grpc@v1.59.0/server.go:1737 +0xca6
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.59.0/server.go:986 +0x8c
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.59.0/server.go:997 +0x15c

Error: The terraform-provider-okta_v4.6.3.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

PS >
```

### Expected Behavior

The default brand for Okta should be imported as data

#### Can this be done in the Admin UI?

No

#### Can this be done in the actual API call?

I don't know 

### Actual Behavior

Provider crash

### Steps to Reproduce

Terraform apply with a single data okta_brand resource as shown in the config.

### Important Factoids

I get this crash/error with a development instance of Okta, which seems to have picked up new brand customization features compared to our production instance. I do not get this error with our prodction instance of Okta. This could indicate that these are new features, and/or that the API has changed. I couldn't see anything relevant in the [release notes](https://developer.okta.com/docs/release-notes/2023-okta-identity-engine/), however. We use Okta with OIE upgrade.

You can see the different features available in this screenshot:

![image](https://github.com/okta/terraform-provider-okta/assets/107847353/11ee902a-3c6c-449e-b91c-92ecc740743d)

### References

This seems like it's probably related to https://github.com/okta/terraform-provider-okta/issues/1763, but that issue is closed with a merged commit, so I can't be sure it's 100% the same.

- #1763

**Comment by GraemeMeyerGT** [comment]
Did a little testing with [the Brands api](https://developer.okta.com/docs/reference/api/brands/#get-brands) in our dev tenant and it seems to work - allowing you to list the brands (there is only one apparently), get the properties of the brand, and then list the associated themes of the brand. Not sure why this issue suddenly started occurring for us on the 6th of December. The exact same code was running fine before that.

**Comment by GraemeMeyerGT** [comment]
I think I have confirmed that Okta themselves are the problem - the API response has changed between our Dev and Prod tenants.

Production returns more attributes for the list-all-brands API call, including `name` and `isDefault`:

```PowerShell
PS > curl -s -X GET -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: SSWS REDACTED" "https://REDACTED.okta.com/api/v1/brands/" | ConvertFrom-Json

id                         : bnd1nz5nkz7Xt8AU91d8
name                       : prod-tenant
removePoweredByOkta        : False
customPrivacyPolicyUrl     :
agreeToCustomPrivacyPolicy : False
isDefault                  : True
defaultApp                 : @{appInstanceId=0oa1nz5nl1nsc1rnA1d8; appLinkName=; classicApplicationUri=}
_links                     : @{themes=; self=}
```

In the Development tenant - I presume slightly further ahead in the release calendar - fewer attributes are returned, and no name is returned.
```PowerShell
PS > curl -s -X GET -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: SSWS REDACTED" "https://dev-REDACTED.okta.com/api/v1/brands/" | ConvertFrom-Json

id                         : bnd731q6h7UFBJIxJ5d7
removePoweredByOkta        : False
customPrivacyPolicyUrl     :
agreeToCustomPrivacyPolicy : False
_links                     : @{themes=; self=}
```

Since the [okta_brand data source](https://registry.terraform.io/providers/okta/okta/latest/docs/data-sources/brand) can obtain the default brand using `brand_id = "default"`, I assume it is relying on the `name` or `isDefault` attributes. Since they are not available, it would explain the crash. (I'm not qualified to look through the code and confirm this, but reasonable guess I think).

As a work around, you can use the `okta_brands` data source and pick the first element in the returned list to get the ID of the default brand. Like so:

```terraform
data "okta_brands" "all_brands" {
}

data "okta_brand" "default" {
  brand_id = tolist(data.okta_brands.all_brands.brands)[0].id
}
```

**Comment by GraemeMeyerGT** [comment]
I think I have confirmed that Okta themselves are the problem - the API response has changed between our Dev and Prod tenants.

Production returns more attributes for the list-all-brands API call, including `name` and `isDefault`:

```PowerShell
PS > curl -s -X GET -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: SSWS REDACTED" "https://REDACTED.okta.com/api/v1/brands/" | ConvertFrom-Json

id                         : bnd1nz5nkz7Xt8AU91d8
name                       : prod-tenant
removePoweredByOkta        : False
customPrivacyPolicyUrl     :
agreeToCustomPrivacyPolicy : False
isDefault                  : True
defaultApp                 : @{appInstanceId=0oa1nz5nl1nsc1rnA1d8; appLinkName=; classicApplicationUri=}
_links                     : @{themes=; self=}
```

In the Development tenant - I presume slightly further ahead in the release calendar - fewer attributes are returned, and no name is returned.
```PowerShell
PS > curl -s -X GET -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: SSWS REDACTED" "https://dev-REDACTED.okta.com/api/v1/brands/" | ConvertFrom-Json

id                         : bnd731q6h7UFBJIxJ5d7
removePoweredByOkta        : False
customPrivacyPolicyUrl     :
agreeToCustomPrivacyPolicy : False
_links                     : @{themes=; self=}
```

Since the [okta_brand data source](https://registry.terraform.io/providers/okta/okta/latest/docs/data-sources/brand) can obtain the default brand using `brand_id = "default"`, I assume it is relying on the `name` or `isDefault` attributes. Since they are not available, it would explain the crash. (I'm not qualified to look through the code and confirm this, but reasonable guess I think).

As a work around, you can use the `okta_brands` data source and pick the first element in the returned list to get the ID of the default brand. Then , and then pull the default brand directly via it's ID (rather than it's name). Like so:

```terraform
data "okta_brands" "all_brands" {
}

data "okta_brand" "default" {
  brand_id = tolist(data.okta_brands.all_brands.brands)[0].id
}
```

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-682420

**Comment by duytiennguyen-okta** [comment]
Close with #1870

**Comment by duytiennguyen-okta** [comment]
I will release this later this week @GraemeMeyerGT
