### ISSUE TITLE
`okta_domain` fails verification immediately

### ISSUE THREAD

**Issue by skaessnerdistillai** [okta/terraform-provider-okta#1868]
I cannot get the `okta_domain` resource to work or function as expected. I have tried using the `okta_domain_verification` and a few other permutations to get it to work, but nothing will get me around this initial issue. I was able to create my domain and verify it with the UI just fine.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- `okta_domain`

### Terraform Configuration Files

```hcl
resource "okta_brand" "test" {
  name = "test-brand"

}
resource "okta_domain" "auth_domain" {
  name = "test.mydomain.com"
  certificate_source_type = "OKTA_MANAGED"
  brand_id = okta_brand.test.id
}
```

### Debug Output

```bash
okta_domain.auth_domain: Creating...
╷
│ Error: failed to verify domain: FAILED_TO_VERIFY is not a valid DomainValidationStatus
│ 
│   with okta_domain.auth_domain,
│   on main.tf line 26, in resource "okta_domain" "auth_domain":
│   26: resource "okta_domain" "auth_domain" {
│ 
╵
```

### Expected Behavior

I imagine this should have put the status in "VERIFYING"

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

I don't know

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Running recently created organizations.

### References

N/A

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-682417

**Comment by skaessnerdistillai** [comment]
Thanks @duytiennguyen-okta for triaging. Do you have an ETA on a fix for this? This is blocking me from getting my Okta implementation completed. 


I am happy to open a PR if helpful. I'm familiar with writing Terraform Providers, but I wasn't clear exactly what the change here needed to be - seemed like it might be further upstream in the API or the go API Client.

**Comment by duytiennguyen-okta** [comment]
It is the validation on the okta-sdk-golang. DId you try this with API call?

**Comment by duytiennguyen-okta** [comment]
@skaessnerdistillai I think you need to open a support ticket on why the verification fail. I will fixed the creation issue, so okta_domain will be created but it status will still be failed_to_verify
