### ISSUE TITLE
okta_app_group_assignments in version 4.6.3 removes groups not specified even though documentation does say all groups need to be specified

### ISSUE THREAD

**Issue by anderskotsalaineneqt** [okta/terraform-provider-okta#1871]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Okta provider Version
4.6.3

### Terraform Version
Our terraform cloud workspace is running terraform version 1.6.6

### Affected Resource(s)
- okta_app_group_assignments
-
### Terraform Configuration Files
```hcl
resource "okta_group" "create_okta_group_cloudflare_access" {
  for_each    = toset(local.okta_group_to_create)
  name        = "app_${var.app_name}_${replace("${var.zone}", ".", "_")}_${var.env}"
  description = "Grants access to ${var.app_name}.${var.zone} through Cloudflare Access. Created by team: ${var.team}"
}

resource "okta_app_group_assignments" "assign_cloudflare_access" {
  for_each = toset(local.okta_group_to_create)
  app_id   = var.cloudflare_access_application_id # Cloudflare Access
  group {
    id = okta_group.create_okta_group_cloudflare_access[each.key].id
  }
}
```
The local.okta_group_to_create evaluates to ["module-cf-access-test"] so the okta_app_group_assignments app should assign an app (cloudflare access) to one group (being created by the okta_group resource.

### Expected Behavior
My expectation is that when I apply my TF-config the Okta group "app_module-cf-access-test_ms_eqtstage_com_stage" that is created by TF config, will be assigned the cloudflare access application, AND that any existing Okta groups who have the cloudflare access application assigned are not affected by this application assignment to my new group. 

I'm basing my expectation on the fact that if one goes to the [documentation](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_group_assignments) for the okta_app_groups_assignments in version 4.6.3, the documentation does NOT state any longer the following warning

> When using okta_app_group_assignments it is expected to manage ALL group assignments for the target application.

 that was present in okta_app_group_assignments [documentation](https://registry.terraform.io/providers/okta/okta/3.35.0/docs/resources/app_group_assignments) for version 3.35.0

#### Can this be done in the Admin UI?

I don't know

#### Can this be done in the actual API call?

I don't know

### Actual Behavior
**Okta provider 4.6.3**
When I'm using Okta provider 4.6.3 and I apply the TF config I get a plan showing that the Okta group that will be created will
be assigned the cloudflare access app. So far so good.

<img width="1155" alt="image" src="https://github.com/okta/terraform-provider-okta/assets/111284232/7ca5d8f2-1df3-4d65-9e58-783bfe2a3d23">

However after applying this plan when I go and look in Terraform state at my okta_app_group_assigments resource I see that the state now contains two groups assigned to this app. The second okta group has been assigned the app through the Okta UI so Terraform has not been involved at all with that app-group assignment.

<img width="1023" alt="image" src="https://github.com/okta/terraform-provider-okta/assets/111284232/864076e5-16a4-4b80-80bd-8f2d648a99fd">

When I then run a plan Terraform wants to remove the app from the second group "00goyygktij9Xmkvm0h7" which makes sense as my Terraform config does not state that this group should be assigned the app. So my issue is that the Okta provider is for some reason adding a second group to the state of the okta_app_group_assigments resource. I actually applied this plan just to check if Terraform really removes the app assignment for group "00goyygktij9Xmkvm0h7" and Terraform did remove that group assignment. After this I manually added back app assignment to the group "00goyygktij9Xmkvm0h7" via the Okta UI as that was how original app assigment for this group had been done.

**Okta provider 3.35.0**
If I switch to using Okta version 3.35.0 where documentation explicitly states that:

> When using okta_app_group_assignments it is expected to manage ALL group assignments for the target application.

the behaviour is exactly the opposite of the warning, and in line with what I want, and what the 4.6.3 documentation describes. So for version 3.35.0 when I apply the TF config I get the same plan:

<img width="1155" alt="image" src="https://github.com/okta/terraform-provider-okta/assets/111284232/7ca5d8f2-1df3-4d65-9e58-783bfe2a3d23">

and when I apply this plan and go and look at the state I now only see my new okta group being assigned the app

<img width="1020" alt="image" src="https://github.com/okta/terraform-provider-okta/assets/111284232/42fe01de-7a8f-465e-a162-33f0b87f3075">

and so when I run the next plan Terraform does NOT want to remove okta app assignment for group "00goyygktij9Xmkvm0h7" (the group which had the app assignment done via Okta UI)

I need to understand what is the expected behaviour for the okta_app_group_assignments resource. Is it so that one can only use this resource in on Terraform workspace connected to a Okta instance, and in that resource one has to list all Okta groups that are being assigned to an app? If so that is very inconvenient as we have 10+ Terraform cloud workspaces that can create resources in Okta and each one of them uses the okta_app_group_assignments resources. This has been working great so far when these workspaces use the Okta provider 3.35.0 but we noticed this unwanted behaviour (explained above), that is not in line with the documentation, when switching a workspace over to version 4.6.3

**Comment by anderskotsalaineneqt** [comment]
I did some digging in the Okta provider code in the 4.6.3 tag and I can see that the code seems to retrive all groups assigned to a spefic app, including those that have been click-opsed like the app in my particular case.

<img width="1074" alt="image" src="https://github.com/okta/terraform-provider-okta/assets/111284232/74d2c3dc-7d57-44ad-a03b-6774884ae7ad">

So it seems like okta_app_group_assignments in the 4.6.3 provider does in fact work in an authoritative manner  where one can only use this resource once per combination of Okta instance and Okta application. If this can be confirmed then the documentation for this version of the provider should be updated so that the warning present in the 3.35.0 is added back as that is extremely important information.

**Comment by jgrumboe** [comment]
I ran into the same problem.
I think it also has to do that `okta_app_group_assignments` accepts these dynamic `group` blocks which also define the priority order.
And yes, also my click-opsed groups went into the pastebin using this resource.

I switched to `okta_app_group_assignment` and `foreach`, which does a singular app/group assignment and does not conflict with click-ops.

**Comment by anderskotsalaineneqt** [comment]
@jgrumboe thanks I also realized that it's a better option to use a okta_app_group_assignment and lopp over my groups. Thanks for your input!
