### ISSUE TITLE
Release builds are failing on Github Actions

### ISSUE THREAD

**Issue by SamMurphyDev** [okta/terraform-provider-okta#1879]
Github Actions are failing to release new versions. Looks like the Git Tags are not aligned with the expected commit.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

N/A

### Affected Resource(s)

N/A

### Terraform Configuration Files

N/A

### Debug Output
https://github.com/okta/terraform-provider-okta/actions/runs/7646338009/job/20834922210
https://github.com/okta/terraform-provider-okta/actions/runs/7646207219/job/20834521045
https://github.com/okta/terraform-provider-okta/actions/runs/7616297951/job/20742732277

etc

### Panic Output

N/A

### Expected Behavior

New version created when a PR is merged

#### Can this be done in the Admin UI?

N/A

#### Can this be done in the actual API call?

N/A

### Actual Behavior

N/A

### Steps to Reproduce

N/A

### Important Factoids

N/A

### References

N/A

**Comment by randomVariable2** [comment]
@duytiennguyen-okta @monde I think this is a pretty high priority item as it blocks creation of new releases other PRs don't take affect

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-673015

**Comment by SamMurphyDev** [comment]
Given the 4.7.0 release has been published using the Go Releaser, I'll mark this issue as solved.

https://github.com/okta/terraform-provider-okta/releases/tag/v4.7.0
