### ISSUE TITLE
okta_auth_server => trusted servers?

### ISSUE THREAD

**Issue by brentlyjdavid** [okta/terraform-provider-okta#1891]
In the Security => API section of Okta.  There are Auth Servers, and those auth servers have a section under them after you create it called 'Trusted Servers' for Token Exchanges

Is there a way to add those using terraform?  I cannot seem to find the right object from the docs https://registry.terraform.io/providers/okta/okta/latest/docs/resources/auth_server

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-693024

**Comment by duytiennguyen-okta** [comment]
We currently don't have that feature right now on terraform

**Comment by brentlyjdavid** [comment]
Okay.  I will watch this Issue for when it makes it into the provider.

Thanks

**Comment by jvpernis** [comment]
I am interested in this feature as well. However, I cannot find a related endpoint in the [OpenAPI spec](https://github.com/okta/okta-management-openapi-spec), so I'm curious whether we can expect this anytime soon.

**Comment by niyazhussain** [comment]
@duytiennguyen-okta What is the recommendation? Do we need to provision the auth server without Terraform? Or should we provision the auth server with Terraform and then manually update the trusted servers? Is there any guarantee that this will not reset the Trusted Servers config for any changes later, or once the support is available?

**Comment by duytiennguyen-okta** [comment]
@jvpernis that is the old spec. I can see that the new spec has that endpoint

**Comment by duytiennguyen-okta** [comment]
@niyazhussain We do not have a resource for trusted server yet. You would still need to use the admin UI for now

**Comment by niyazhussain** [comment]
Okay we are planning to provision this with UI console and later once this is available we will upgrade the provider version and import the auth server

**Comment by brentlydavid-ubt** [comment]
What's the timeframe look like for this?  It prevents token exchanges entirely and has huge security benefits of using multiple auth servers within your ecosystem vs just the default one w/o the extra SKU cost.
