### ISSUE TITLE
`data_source_okta_user` - Add "skip_roles" to okta_user data source documentation

### ISSUE THREAD

**Issue by stargonautone** [okta/terraform-provider-okta#1900]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `skip_roles` argument was removed from the documentation for the `okta_user` data source as of version 4.0.0, yet is still available and required if being used by a non-SuperAdmin (if `skip_roles = true` is omitted, non-SuperAdmin may get the error `Error: failed to set user's roles: failed to get roles: the API returned an error: You do not have permission to perform the requested action`). 

https://registry.terraform.io/providers/okta/okta/4.7.0/docs/data-sources/user

The `skip_roles` argument should be added back in to the documentation, or `okta_user` should be brought in line with the `okta_users` data source which uses the optional `include_roles` argument which is assumed false if not specified in terraform. 

### New or Affected Resource(s)

- okta_user

### Potential Terraform Configuration

```hcl
data "okta_user" "foobar" {
    # skip_roles = true
  search {
    name = "profile.firstName"
    value = "foo"
  }

  search {
    name = "profile.lastName"
    value = "bar"
  }
}
```

### References

- #1216 
- #1844

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-699599

**Comment by duytiennguyen-okta** [comment]
Close via #1705
