### ISSUE TITLE
Support userVerification in possessionConstraints

### ISSUE THREAD

**Issue by MScottBlake** [okta/terraform-provider-okta#1903]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great if the [possessionConstraints struct](https://github.com/okta/terraform-provider-okta/blob/master/sdk/v2_possessionConstraint.go#L4-L12) supported the `userVerification` property that is defined in the [Policy API docs](https://developer.okta.com/docs/reference/api/policy/#constraints).

### New or Affected Resource(s)

- okta_app_signon_policy_rule

### Potential Terraform Configuration

```hcl
resource "okta_app_signon_policy_rule" "example" {
  policy_id = okta_app_signon_policy.example.id
  name      = "example"

  factor_mode = "1FA"
  constraints = [
    jsonencode(
      {
        possession = {
          phishingResistant  = "REQUIRED"
          deviceBound        = "REQUIRED"
          hardwareProtection = "REQUIRED"
          userPresence       = "REQUIRED"
          userVerification   = "REQUIRED"
        }
      }
    )
  ]
}
```

### References

- https://developer.okta.com/docs/reference/api/policy/#authentication-policy
- https://developer.okta.com/docs/reference/api/policy/#constraints

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-699610

**Comment by MScottBlake** [comment]
Is there a way to track any progress on that ticket?

**Comment by lukas-hetzenecker** [comment]
Also interested in making "userVerification" configurable via terraform. 

Without this attribute, any kind of MFA requirements can be easily circumvented (see e.g. https://www.reddit.com/r/okta/comments/15h2ryj/enforce_users_into_using_biometrics_okta_oie/ )

It should be fairly trivial to add this, I created a PR here: #1930
