### ISSUE TITLE
Cannot modify default MFA policy

### ISSUE THREAD

**Issue by khitrenovich** [okta/terraform-provider-okta#191]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.13.2

### Affected Resource(s)

* okta_policy_mfa

### Terraform Configuration Files

```hcl
data "okta_group" "group_everyone" {
  name = "Everyone"
}

resource "okta_factor" "okta_google_otp_mfa_factor" {
  provider_id = "google_otp"
  active      = true
}

resource "okta_factor" "okta_duo_mfa_factor" {
  provider_id = "duo"
  active      = true
}

resource "okta_policy_mfa" "okta_default_mfa_policy" {
  name        = "Default Policy"
  description = "The default policy applies in all situations if no other policy applies."
  status      = "ACTIVE"

  google_otp = {
    enroll = "OPTIONAL"
  }
  duo = {
    enroll = "REQUIRED"
  }

  groups_included = [data.okta_group.group_everyone.id]
}
```

### Expected Behavior

Terraform should be able to update Default MFA policy.

### Actual Behavior

Terraform was unable to modify Default MFA policy - 
```
Error: Default Policy is immutable

  on modules/okta/okta.tf line 46, in resource "okta_policy_mfa" "okta_default_mfa_policy":
  46: resource "okta_policy_mfa" "okta_default_mfa_policy" {


error Command failed with exit code 1.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Any MFA policy, including Default Policy, can be updated via Okta REST API.
https://developer.okta.com/docs/reference/api/policy/#multifactor-mfa-enrollment-policy

However, Terraform blindly marks any `Default ...` resource as immutable -
https://github.com/oktadeveloper/terraform-provider-okta/blob/71e363be2678f66f999699351f57a98350e52ddb/okta/utils.go#L248

### References

There was similar issue (#50) about default password policy and #51 that was supposed to track future work on a general case, but both were closed by a bot as stale.

**Comment by khitrenovich** [comment]
Please don't close.

**Comment by khitrenovich** [comment]
@bogdanprodan-okta Something is wrong with the stale issues bot. Can you reopen this one manually, please?

**Comment by bogdanprodan-okta** [comment]
@khitrenovich thanks for the issue! I'll try to deal with it and other related issues this week.

**Comment by bogdanprodan-okta** [comment]
Hi there! The default policies have certain limitations compared to the non-default ones. I think I can build a logic that will support that behavior using the existing resources or create new resources for each default policy. In the first case, there will certain limitations for field setup because `name`, `description`, `status`, and `priority` are immutable in default policies. In the second case, default policies will be just without these fields. I'm not sure what is a better option here, but I'll definitely want to make default policies manageable.

**Comment by khitrenovich** [comment]
> Hi there! The default policies have certain limitations compared to the non-default ones. I think I can build a logic that will support that behavior using the existing resources or create new resources for each default policy. In the first case, there will certain limitations for field setup because `name`, `description`, `status`, and `priority` are immutable in default policies. In the second case, default policies will be just without these fields. I'm not sure what is a better option here, but I'll definitely want to make default policies manageable.

Thank you for looking into that!
I'm fine with either approach as long as it works, but I'm in no means a TF expert here...

**Comment by khitrenovich** [comment]
@bogdanprodan-okta -
Do you have a usage example? Will the config snippet I posted above work as is now, or some changes are needed?

**Comment by khitrenovich** [comment]
> @bogdanprodan-okta -
> Do you have a usage example? Will the config snippet I posted above work as is now, or some changes are needed?

@bogdanprodan-okta Do you have any update on the above, please?

**Comment by bogdanprodan-okta** [comment]
Hi @khitrenovich! Here is example of how to use default MFA policy
```hcl
resource "okta_policy_mfa_default" "test" {
  google_otp = {
    enroll = "OPTIONAL"
  }
  depends_on      = [okta_factor.google_otp]
}
```
Basically, all the fields are computed except the factors.

The next release will probably this week. The only problem is that provider has migrated from `oktadeveloper` to `okta` and I don't know if I will be able to release it with the current `gpg` key.
There is always a possibility to use [in-house provider ](https://www.terraform.io/docs/cloud/run/install-software.html#in-house-providers) built from source. Basically, you run `go install`, copy the binary into your `terraform.d` dir and run `terraform init`.

**Comment by khitrenovich** [comment]
Oh, I just realized the change is not out yet... That explains why it's not covered in the docs :)
