### ISSUE TITLE
Missing arguments to okta_idp_saml

### ISSUE THREAD

**Issue by SarkisFesliyan** [okta/terraform-provider-okta#1911]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform is missing the option to set the factor type. There are 2 factors if you look in the UI. By default the factor will be set to SSO only. Im not a terraform expert so i may be missing something here.

![Image](https://github.com/okta/terraform-provider-okta/assets/65836961/d0d579ec-a875-4352-b104-cc7def7a7dd2)

 I couldnt find a API reference within Okta documents but found one using AI. So when i tested using Postman i was able to update this attribute with this payload

![Image](https://github.com/okta/terraform-provider-okta/assets/65836961/887d65c0-d488-43a8-8965-407b2130caec)

### New or Affected Resource(s)

- okta_idp_saml

### Potential Terraform Configuration

```resource "okta_idp_saml" "example" {
  name                     = "testAcc_replace_with_uuid"
  acs_type                 = "INSTANCE"
  sso_url                  = "https://idp.example.com"
  sso_destination          = "https://idp.example.com"
  sso_binding              = "HTTP-POST"
  username_template        = "idpuser.email"
  kid                      = "${okta_idp_saml_key.test.id}"
  issuer                   = "https://idp.example.com"
  request_signature_scope  = "REQUEST"
  response_signature_scope = "ANY"
  # settings = jsonencode({"sso": {"idp": {"restrictions": {"factor": true}}}})
}
```

### References

- #0000

**Comment by aogail** [comment]
@SarkisFesliyan I'm in need of this behavior as well and am wondering why you closed this issue as completed. Did you discover a way to configure the factor only setting? Could you share here?
