### ISSUE TITLE
okta_app_saml  SSO certificate management

### ISSUE THREAD

**Issue by VladSSO** [okta/terraform-provider-okta#1926]
Hello,
My appologies if this is not the right place.
okta_app_saml resource doesn't allow to clone SSO certs between saml applications or activate SSO certs. Combining with REST API is not helping as well, the next apply restores a previous certificate. The whole  SSO certificate renewal automation  withTerraform doesn't look possible.  An Admin needs to do activation with GUI.
What is the point of okta_app_saml, create an app and not able to replace a certificate in a year?

Thanks,
Vlad

**Comment by duytiennguyen-okta** [comment]
Unfortunately, the terraform is dependent on the REST API to make it works. I think you can file a support ticket to get this issue notice, but other than that, there is not much I can do @VladSSO
