### ISSUE TITLE
Update Provider Docs URL(s)

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1940]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Expected Behavior

Links to documentation should go to the latest or a recent-ish version of the provider docs

### Actual Behavior

When I visit [www.terraform.io/docs/providers/okta](https://www.terraform.io/docs/providers/okta)  
I get redirected to [registry.terraform.io/providers/oktadeveloper/okta/latest/docs](https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs)

### Proposed Fix 

Replace the Docs URLs in code and Repo description
Old - https://www.terraform.io/docs/providers/okta/
New - https://registry.terraform.io/providers/okta/okta/

**Comment by duytiennguyen-okta** [comment]
I will talk with Hashicorp to update the link

**Comment by exitcode0** [comment]
We can also update the URL in the terraform-provider-okta Github repo description as this currently redirects to the oktadev/okta provider

**Comment by duytiennguyen-okta** [comment]
@exitcode0 which one are you talking about?

**Comment by exitcode0** [comment]
> @exitcode0 which one are you talking about?

The link in the screenshot at the bottom of this comment has a link
https://www.terraform.io/docs/providers/okta/  
This link redirects me to  
https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs  
If we change this to  
https://registry.terraform.io/providers/okta/okta  
This should resolve the problem while we wait on Hashicorp to put a redirect from `oktadev/okta` to `okta/okta`  

As far as I know this link is the Github repo's description I don't believe this one can be updated via PR, so this one will need to be updated by someone from Okta staff or a repo maintainer


![Screenshot 2024-04-07 at 01 34 21](https://github.com/okta/terraform-provider-okta/assets/38837341/6e6d4239-28c2-472a-8c1f-e965fd7315d6)

**Comment by exitcode0** [comment]
Hey @duytiennguyen-okta

It looks like this link still points at the old provider docs 
Just wanted to bump this one to ask if you needed any more info from me or if there was anything I can do to help with this one?

Thankfully this shoudl be a pretty quick and easy fix to update this URL in github
Assuming the person in question has the correct permissions it should be less than 5mins

**Comment by exitcode0** [comment]
Hey @duytiennguyen-okta,

Any progress on this one internally?
If Hashicorp isn't able to redirect this URL for y'all, we can update the URL on this repo in the mean time to point to the correct documentation?
The latter should be pretty quick and easy for a Okta Github admin to action

**Comment by duytiennguyen-okta** [comment]
It is updated
