### ISSUE TITLE
Include permission conditions in custom admin roles

### ISSUE THREAD

**Issue by king-millez** [okta/terraform-provider-okta#1943]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At the moment, the `okta_admin_role_custom` `permissions` only allow a list of permission strings (e.g., `okta.users.userprofile.manage`). It would be helpful to include more fine grained permissions. For example, in the Okta Admin Console, users can narrow down the `okta.users.userprofile.manage` so that it only applies to certain profile attributes, etc.

I'm not particularly familiar with writing Terraform providers, let alone Go, so I haven't given this a try yet. I suspect the suggested pattern would be a new resource that takes an existing `okta_admin_custom_role` ID as an argument. This makes sense after looking at Okta's API for the permission conditions.

### New or Affected Resource(s)

- `okta_admin_role_permission_condition` (New)
- `okta_admin_role_custom`

### Potential Terraform Configuration

```hcl
resource "okta_admin_role_custom" "magic_custom_role" {
  label       = "Magic custom role"
  description = "This role grantw write access to certain profile attributes."
  permissions = [
    "okta.users.userprofile.manage"
  ]
}

resource "okta_admin_role_permission_condition" "restrict_profile_editing" {
  custom_role_id = okta_admin_role_custom.magic_custom_role.id
  permission_conditions = {
    "okta.users.userprofile.manage" = {
      include = ["zipCode"]
      exclude = ["email", "firstName", "lastName"]
    }
  }
}
```

### References

https://help.okta.com/oie/en-us/content/topics/security/custom-admin-role/permission-conditions.htm?cshid=csh-permission-conditions

- #0000

**Comment by exitcode0** [comment]
I think this is a duplicate of #1571

**Comment by duytiennguyen-okta** [comment]
Close due to duplication
