### ISSUE TITLE
Provider crash during import of okta_id_social with type "X509"

### ISSUE THREAD

**Issue by jplanza** [okta/terraform-provider-okta#1946]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v1.7.5
on darwin_amd64
+ provider registry.terraform.io/okta/okta v4.8.0
```

### Affected Resource(s)

- okta_idp_social

### Terraform Configuration Files

```hcl
resource "okta_idp_social" "example" {
  account_link_action  = "AUTO"
  deprovisioned_action = "NONE"
  groups_action        = "NONE"
  issuer_mode          = "ORG_URL"
  name                 = "EXAMPLE"
  protocol_type        = "OAUTH2"
  provisioning_action  = "AUTO"
  scopes               = []
  status               = "ACTIVE"
  subject_match_type   = "USERNAME"
  suspended_action     = "NONE"
  type                 = "X509"
  username_template    = "idpuser.email"
}

resource "okta_idp_social" "example_2" {
  name                 = "EXAMPLE 2"
  scopes               = []
  type                 = "X509"
}
```

### Panic Output

https://gist.github.com/jplanza/93fa28bcc4fe23c328523a9a7e402c2f

### Expected Behavior

Resource is imported from API into state

#### Can this be done in the Admin UI?

I don't know

#### Can this be done in the actual API call?

I don't know

### Actual Behavior

The provider crashes while attempting to read an `okta_idp_social` with type `X509`

### Steps to Reproduce

1. Create Okta IDP with type X509 (Smart Card)
2. `terraform import okta_idp_social.example xxxxxxxxxxxxxxxx`

### Important Factoids

- Based on where the crash occurs (resource_okta_idp_social.go:108), I suspect that the provider is trying to read the `provisioning_action` or `deprovisioned_action` attributes from the IDP.  Since these attributes are not part of an X509 IDP, we get a nil pointer dereference.  
- If you look at the HCL above, running a plan with `example_2` will attempt to create a resource that looks like `example`.  From this, I believe that all of the `*_action` attributes are invalid for type `X509`.

### References

- #0000

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-717446

**Comment by duytiennguyen-okta** [comment]
@jplanza you're correct that it is trying to read deprovisioned_action. I will put out a release next week

**Comment by jplanza** [comment]
@duytiennguyen-okta Does `groups_action` need to be handled as well?

**Comment by duytiennguyen-okta** [comment]
No, there is already a check on that
