### ISSUE TITLE
`okta_auth_server_claim` - Support Import

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1949]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
As far as I can tell from the docs and the code `okta_auth_server_claim` doesn't currently support import
Please let me know if this is not the case, i'd love to be wrong here :) 

### New or Affected Resource(s)
- `okta_auth_server_claim`

### Potential Terraform Configuration
N/A

### References
N/A

**Comment by duytiennguyen-okta** [comment]
@exitcode0 I am seeing this at the[ docs site ](https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/auth_server_claim#import)
