### ISSUE TITLE
Defaults for `grant_types` on `okta_app_oauth` not being picked up

### ISSUE THREAD

**Issue by skemper-sd** [okta/terraform-provider-okta#1952]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform 1.7.3
Okta provider v4.7.0

### Affected Resource(s)

- okta_app_oauth resource

### Terraform Configuration Files

```hcl
resource "okta_app_oauth" "this" {
    label = "MyApp"
    type = "web"
    redirect_uris = ["REDACTED"]
    hide_ios = true
    hide_web = true
    omit_secret = true
}
```

### Debug Output

None yet; can pull if it's strictly necessary

### Panic Output

```
okta_app_oauth.this: Creating...
╷
│ Error: failed to create OAuth application: failed conditional validation for field "grant_types" of type "web", it can contain authorization_code, implicit, refresh_token, client_credentials, urn:ietf:params:oauth:grant-type:saml2-bearer, urn:ietf:params:oauth:grant-type:token-exchange, urn:ietf:params:oauth:grant-type:device_code, interaction_code and must contain authorization_code, received 
│ 
│   with okta_app_oauth.this,
│   on app.tf line 6, in resource "okta_app_oauth" "this":
│    6: resource "okta_app_oauth" "this" {
│ 
╵

Exited with code exit status 1
```

### Expected Behavior

The provider should have selected the default grant types for the application type ("web") as specified [in the code](https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_app_oauth.go#L40).

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

N/A

### Actual Behavior

The provider did not apply the expected defaults to the field, causing it to be empty and throw an exception.

I suspect this is because of a bug in the resource's create and update functions.  Application of the defaults is done in [okta/resource_okta_app_oauth.go line 728](https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_app_oauth.go#L728), as part of the `buildAppOauth()` function.  However, in both `resourceAppOAuthCreate()` and `resourceAppOAuthUpdate()`, `buildAppOauth()` is called _after_ the function `validateGrantTypes()`, which is what's throwing this error.

If folks concur, I'm happy to submit a PR, but wanted to get this bug report in to start the conversation.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nothing special.

### References

N/A

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-717450
