### ISSUE TITLE
Issue with `okta_authenticator` when updating `webauthn` - `security_key` requires `provider_` settings

### ISSUE THREAD

**Issue by theDabca** [okta/terraform-provider-okta#1957]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.7.5
on linux_amd64
+ provider registry.terraform.io/okta/okta v4.7.0
```

### Affected Resource(s)

- okta_authenticator

### Terraform Configuration Files

```hcl
resource "okta_authenticator" "webauthn" {
  name = "webauthn"
  key = "webauthn"
  status = "INACTIVE"
}
```

### Error

```
Error: for authenticator type 'security_key' fields 'provider_hostname', 'provider_auth_port', 'provider_shared_secret' and 'provider_user_name_template' are required
```

### Expected Behavior

Update to the `webauthn` authenticator, without needing to provide these `provider_` fields. These fields are used by other `security_key` types, but as far as I am aware are not used by `webauthn`. 

The provider utilizes this conditional to build the requirements for the `security_key` type authenticators. It needs to be more closely scoped for non-webauthn authenticators. 

Current conditional:

```go
	if d.Get("type").(string) == "security_key" {
		authenticator.Provider = &sdk.AuthenticatorProvider{
			Type: d.Get("provider_type").(string),
			Configuration: &sdk.AuthenticatorProviderConfiguration{
				HostName:     d.Get("provider_hostname").(string),
				AuthPortPtr:  int64Ptr(d.Get("provider_auth_port").(int)),
				InstanceId:   d.Get("provider_instance_id").(string),
				SharedSecret: d.Get("provider_shared_secret").(string),
				UserNameTemplate: &sdk.AuthenticatorProviderConfigurationUserNamePlate{
					Template: "",
				},
			},
		}
```

To achieve the expected behavior:

```go
	if d.Get("type").(string) == "security_key" && d.Get("key") != "webauthn" {
		authenticator.Provider = &sdk.AuthenticatorProvider{
			Type: d.Get("provider_type").(string),
			Configuration: &sdk.AuthenticatorProviderConfiguration{
				HostName:     d.Get("provider_hostname").(string),
				AuthPortPtr:  int64Ptr(d.Get("provider_auth_port").(int)),
				InstanceId:   d.Get("provider_instance_id").(string),
				SharedSecret: d.Get("provider_shared_secret").(string),
				UserNameTemplate: &sdk.AuthenticatorProviderConfigurationUserNamePlate{
					Template: "",
				},
			},
		}
```

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

Yes

### Actual Behavior

Initial creation of the authenticator gave no errors, however once an update is attempted, it throws the error, requiring updates to the `provider_` fields (`provider_hostname`, `provider_auth_port`, `provider_shared_secret` and `provider_user_name_template`)

### Steps to Reproduce

1. `terraform apply`

**Comment by duytiennguyen-okta** [comment]
Close due to duplication with #1925
