### ISSUE TITLE
Custom attributes to the default Okta group profile

### ISSUE THREAD

**Issue by dmitrii-didenko** [okta/terraform-provider-okta#1960]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As far as I understand there are no options of adding custom attributes to the default Okta group profile. Basically, I'd like to terraform the following action https://help.okta.com/oie/en-us/content/topics/users-groups-profiles/usgp-add-custom-group-attributes.htm.

Please sorry if I've missed something and this is already possible somehow. Let me know please if it so. Thanks.

**Comment by duytiennguyen-okta** [comment]
Please use [okta_group_schema_property](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/group_schema_property)
