### ISSUE TITLE
`content_security_policy_setting` not being applied in `okta_preview_signin_page` and `okta_customized_signin_page`

### ISSUE THREAD

**Issue by mvitt** [okta/terraform-provider-okta#1961]
When applying `content_security_policy_setting` block in both `okta_preview_signin_page` and `okta_customized_signin_page` it seems that that block is ignored.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
1.5.7

### Affected Resource(s)

- okta_preview_signin_page
- okta_customized_signin_page

### Terraform Configuration Files

```hcl
resource "okta_preview_signin_page" "custom_brand_test_signin_page_preview" {
  brand_id       = okta_brand.custom_brand.id
  page_content   = templatefile("${path.module}/html_templates/test.html", merge(local.test_template_vars, { logo_url = okta_theme.custom_brand_theme.logo_url }))
  widget_version = var.test_signin_page_version
  content_security_policy_setting {
    mode       = "report_only"
    report_uri = ""
    src_list   = local.csp_urls
  }
  widget_customizations {
    widget_generation = "G2"
  }
}

resource "okta_customized_signin_page" "custom_brand_test_signin_page" {
  brand_id       = okta_brand.custom_brand.id
  page_content   = templatefile("${path.module}/html_templates/test.html", merge(local.test_template_vars, { logo_url = okta_theme.custom_brand_theme.logo_url }))
  widget_version = var.test_signin_page_version
  content_security_policy_setting {
    mode       = "report_only"
    report_uri = ""
    src_list   = local.csp_urls
  }
  widget_customizations {
    widget_generation = "G2"
  }
}
```

### Debug Output

No errors, just seems to ignore the block entirely

### Panic Output

No errors, just seems to ignore the block entirely

### Expected Behavior

Updates the `content_security_policy_setting` page with the correct URLS

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

Yes

### Actual Behavior

Just seems to ignore the block entirely

**Comment by johnodonnell1** [comment]
Thanks Matt for adding this:  Let me check with product (JohnO)

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-720093

**Comment by thatguysimon** [comment]
@johnodonnell1 @duytiennguyen-okta For us, not only is the CSP setting not applied, but it also overrides any manual configuration back to its default setting.
We have `mode = "report_only"`, which isn't applied like this issue reports, so we configure it manually in the admin console. After making a change to `page_content` and running `apply`, I find that the CSP setting in Okta changes back to "Enforced". This means that I then have to manually change the setting back to "Not enforced" manually in each Okta tenant.
