### ISSUE TITLE
okta_customized_signin_page raises 403 Forbidden

### ISSUE THREAD

**Issue by thatguysimon** [okta/terraform-provider-okta#1964]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v1.6.3

### Affected Resource(s)

- okta_customized_signin_page

### Terraform Configuration Files

```terraform
resource "okta_customized_signin_page" "my_customized_signin_page" {
  brand_id       = local.my_brand_id
  page_content   = file("${path.module}/assets/html/pages/sign_in_page.html")
  widget_version = "^7"

  content_security_policy_setting {
    mode = "report_only"
  }

  widget_customizations {
    widget_generation = "G2"
  }
}

```

- Our configuration authenticates using a service app private key. 
- The app has the Super Admin role assigned to it.
- The `okta.brands.manage` and `okta.brands.read` scopes are granted to the service app in Okta
- The `okta.brands.manage` and `okta.brands.read` scopes are included in the `scopes` field of the `okta` provider config.

### Expected Behavior

The customized sign in page should be successfully updated

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

Yes. When calling this API with cURL and the same client, same private key and same scopes - it works as expected.

### Actual Behavior

```
okta_customized_signin_page.my_customized_signin_page: Creating...
╷
│ Error: failed to update customized sign in page
│ 
│   with okta_customized_signin_page.my_customized_signin_page,
│   on brands.tf line 32, in resource "okta_customized_signin_page" "my_customized_signin_page":
│   32: resource "okta_customized_signin_page" "my_customized_signin_page" {
│ 
│ 403 Forbidden
╵
```

Is the full API error being logged? Okta's `errorSummary` and `errorCauses` fields might help understand where exactly the issue is.

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

Thank you!!

**Comment by duytiennguyen-okta** [comment]
This error is coming from the API sides. To view the full log, you can run `TF_LOG=debug terraform apply` @thatguysimon

**Comment by thatguysimon** [comment]
Hi @duytiennguyen-okta, the issue ended up being my fault. I was passing the default brand's ID.
Many folks (like us) use automated Terraform tools like [Atlantis](https://www.runatlantis.io/) these days, where debugging with `TF_LOG=debug` may be problematic due to lack of permissions, access policies etc. It would be really awesome if the Okta provider would print out the Okta API errors (at least the `errorSummary`) by default.

```
{
  "errorCode": "E0000213",
  "errorSummary": "Cannot update page content for the default brand.",
  "errorLink": "E0000213",
  "errorId":   
  "errorCauses": []
}
```

But anyway, thanks for the help!
