### ISSUE TITLE
Bad Okta domain causes Terraform panic

### ISSUE THREAD

**Issue by cdhunt** [okta/terraform-provider-okta#197]
This error was causing terraform to crash instead of just reporting a useful error message.

`panic: your Okta domain should not contain -admin. Current value: https://dev-11111-admin.okta.com. You can copy your domain from the Okta Developer Console. Follow these instructions to find it: https://bit.ly/finding-okta-domain`

The only message reported outside of the debug log is `rpc error: code = Unavailable desc = transport is closing`.

**Comment by bogdanprodan-okta** [comment]
Hi @cdhunt! Thanks for submitting this issue! Panic was triggered by `okta-sdk-golang`, which is used by the provider for API calls. This was fixed some time ago and now it should just error out.
