### ISSUE TITLE
Provider crash/panic in okta_idp_oidc

### ISSUE THREAD

**Issue by n-oden** [okta/terraform-provider-okta#1973]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v1.5.3
on darwin_arm64
```

### Affected Resource(s)

- okta_idp_oidc (or at least this is my guess from the panic output)

### Terraform Configuration Files

```hcl
resource "okta_idp_oidc" "customer_idp" {
  name = "${var.client_name} Entra Directory"

  authorization_url       = "https://login.microsoftonline.com/${var.tenant_id}/oauth2/v2.0/authorize"
  authorization_binding   = "HTTP-REDIRECT"
  token_url               = "https://login.microsoftonline.com/${var.tenant_id}/oauth2/v2.0/token"
  token_binding           = "HTTP-POST"
  user_info_url           = "https://graph.microsoft.com/oidc/userinfo"
  user_info_binding       = "HTTP-REDIRECT"
  jwks_url                = "https://login.microsoftonline.com/${var.tenant_id}/discovery/v2.0/keys"
  jwks_binding            = "HTTP-REDIRECT"
  scopes                  = ["email", "openid", "profile"]
  client_id               = var.client_id
  client_secret           = var.client_secret
  issuer_url              = "https://login.microsoftonline.com/${var.tenant_id}/v2.0"
  username_template       = "idpuser.email"
  subject_match_type      = "USERNAME_OR_EMAIL"
  issuer_mode             = "DYNAMIC"
  request_signature_scope = "NONE"

  groups_action     = "ASSIGN"
  groups_assignment = [var.okta_sso_users_group_id]
  profile_master    = true
}
```

Full module HCL here: https://gist.github.com/n-oden/f43f94af8252c27d5635d2493690b25f

### Debug Output

https://gist.github.com/n-oden/d8ba491c02179106ab54786abf387aef

### Panic Output

https://gist.github.com/n-oden/d8ba491c02179106ab54786abf387aef
(this is running in terraform cloud, so there is no separate crash.log -- the panic output is at the bottom)

### Expected Behavior

Create the designated resource

#### Can this be done in the Admin UI?

I don't know

#### Can this be done in the actual API call?

I don't know

### Actual Behavior

Panic!

### Steps to Reproduce

1. `terraform apply`

**Comment by n-oden** [comment]
FWIW:

The panic seems to be here: https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_idp_oidc.go#L232 in `func buildIdPOidc`:

```go
	pkceVal := d.GetRawConfig().GetAttr("pkce_required")
	if !pkceVal.IsNull() {
		client.PKCERequired = boolPtr(d.Get("pkce_required").(bool))
	}
```

That code was added in commit https://github.com/okta/terraform-provider-okta/commit/c558d588403d8eb5acf7428e1597605a511eab22 by @duytiennguyen-okta , and that commit added a `pkce_required` schema definition at L57, but in the current HEAD commit the schema definition is absent as far as I can tell.  This feels like maybe a merge gone very wrong?

**Comment by duytiennguyen-okta** [comment]
@n-oden yeah it is, I am aware of it and will create a new release asap. For now, stay with v4.8.0

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-721731

**Comment by duytiennguyen-okta** [comment]
Close via #1984
