### ISSUE TITLE
Network zone deletion failure 

### ISSUE THREAD

**Issue by dancudds** [okta/terraform-provider-okta#1975]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.7.5
on darwin_arm64
+ provider registry.terraform.io/okta/okta v4.8.1

### Affected Resource(s)

okta_network_zone

### Terraform Configuration Files

```hcl
resource "okta_network_zone" "zone" {
  name     = "Zone"
  type     = "IP"
  gateways = ["1.2.3.4/32"]
}
```

### Debug Output

│ Error: failed to delete network zone: the API returned an error: Api validation failed: The zone: Jamf Security Cloud is an active zone. Active zones cannot be deleted.. Causes: errorSummary: id: The zone: nzoe3fc8nbGj4oBAG1d7 is an active zone. Active zones cannot be deleted., Status: 400 Bad Request

### Expected Behavior

Zone should be moved to inactive and then deleted per destroy

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

Yes

### Actual Behavior

Must manually move to inactive

- #0000

**Comment by duytiennguyen-okta** [comment]
In the admin UI, do you have to deactivate the zone and then delete the network zone?

**Comment by dancudds** [comment]
Yes - furthermore, creating a networkzone with status `INACTIVE` does not work. So even creating a network zone that's INACTIVE or trying to update to INACTIVE won't help.

**Comment by duytiennguyen-okta** [comment]
You cannot create a network zone with status `INACTIVE`. But update to `INACTIVE` allowed terraform to deactivate and destroy. I have just done that. You'll need to disconnect the network zone from whatever you're connecting it with, deactivate it to be able to destroy the network zone

**Comment by dancudds** [comment]
I see - so to destroy a plan you first have to update all Zones to be INACTIVE? Can Terraform not attempt to do this? It doesn't allow to a closed-loop template if we have to update the Zones to be INACTIVE before destroying.

**Comment by duytiennguyen-okta** [comment]
It currently cannot do that. You can open a new issue to request that
