### ISSUE TITLE
Delete Network Zones on destroy

### ISSUE THREAD

**Issue by dancudds** [okta/terraform-provider-okta#1985]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Network Zones are not destroyed unless they're Inactive. Ideally TF should attempt move Zones to Inactive and then delete.

### New or Affected Resource(s)

okta_network_zone

### Potential Terraform Configuration

```hcl
resource "okta_network_zone" "zone" {
  name     = "Zone"
  type     = "IP"
  gateways = ["1.2.3.4/32"]
}
```

### References

- #0000

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-724382
