### ISSUE TITLE
'The DPoP proof JWT header is missing' when authenticating with terraform

### ISSUE THREAD

**Issue by sharvesh06** [okta/terraform-provider-okta#1989]
### Terraform Version

Terraform v1.7.5

### Affected Resource(s)

- okta_group

### Debug Output
```

 Error: failed to create group: the API returned an error: The DPoP proof JWT header is missing.
│ 
│   with module.okta_groups["terraform-test"].okta_group.group,
│   on ../modules/groups/groups.tf line 2, in resource "okta_group" "group":
│    2: resource "okta_group" "group" {
```

**Comment by exitcode0** [comment]
Duplicate https://github.com/okta/terraform-provider-okta/issues/1904

**Comment by duytiennguyen-okta** [comment]
We are implementing dpop for terraform at the moment. We will update this issue once it is released. Close due to duplication #1904
