### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1992]
I can see that this repo has two paths for documentation `./docs` and `./website/docs`
Do these end up being published in different locations? 
Curious if these can be consolidated and/or which I should be updating if I want to contribute

**Comment by duytiennguyen-okta** [comment]
The path to `./docs` is the documentation generated by [tfplugin docs](https://github.com/hashicorp/terraform-plugin-docs). The path `./website/docs` is manually being curated. I am trying to move the documentation away from manually and to default generation. Please update on the `./docs` folder
