### ISSUE TITLE
Replace Okta Brand Pages via Terraform

### ISSUE THREAD

**Issue by chhauss-a** [okta/terraform-provider-okta#1996]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

TL;DR: We would like to adjust the Okta-Brand-Pages with terraform.

We have 3 environments (dev, test, prod) and would like to adjust e.g. the sign-in page until it fits on dev and then distribute these changes from within our ci/cd pipeline to test and prod via terraform. Kind of like it seems to be possible with the [Replace Customized SignIn Page](https://developer.okta.com/docs/api/openapi/okta-management/management/tag/Customization/#tag/Customization/operation/replaceCustomizedSignInPage)-Endpoint but from within terraform instead of writing an extra script.

### New or Affected Resource(s)

- okta_brand (affected?)
- okta_page (new?)

### Potential Terraform Configuration

```hcl
resource "okta_page" "custom_sign_in_page" {
    brand_id = okta_brand.my_brand.id
    page_type = "SIGNIN_PAGE | END_USER_DASHBOARD | ERROR_PAGE"
    page_content = templatefile("path/to/template.html")
}
```

### References

- none

**Comment by duytiennguyen-okta** [comment]
There is already support signin page. See if that works for you https://github.com/okta/terraform-provider-okta/blob/master/docs/resources/customized_signin_page.md

**Comment by chhauss-a** [comment]
Ah alright, we will try that. Thanks for pointing it out!

It seems like that resource didn't make it into the [terraform registry documentation ](https://registry.terraform.io/providers/okta/okta/latest/docs). Is there a reason for that?

**Comment by duytiennguyen-okta** [comment]
We were having issue when switching documentation but it should be up for the v4.9.0
