### ISSUE TITLE
key_years_valid defaults to 1 when importing okta_app_saml version 3.5.0 of plugin

### ISSUE THREAD

**Issue by btsteve** [okta/terraform-provider-okta#201]
When importing a resource from okta the terraform provider tries to set key_years_valid to 1 eventhough it was imported as null and setting as null in the resource still tries to set to 1 when running plan. 

"key_years_valid": null, from state

from plan:
  + key_years_valid            = 1

from resource: 

    key_years_valid            = null

**Comment by btsteve** [comment]
There was a previous issue that keeps getting marked as stale.

https://github.com/oktadeveloper/terraform-provider-okta/issues/73

**Comment by rnikoopour** [comment]
This happens in with provider version `3.5.1` and `3.4.1` as well.

**Comment by bogdanprodan-okta** [comment]
Hi @btsteve! This issue will be fixed in the new 3.7.2 version so after the import `key_name` and `key_years_valid` will be set to `null`

**Comment by bogdanprodan-okta** [comment]
Hi @btsteve! The issue should be fixed in the latest 3.7.2 version. In case it still exists, please reopen this issue.
