### ISSUE TITLE
okta_app_signon_policy_rule doesn't see excludedAuthenticationMethods and authenticationMethods

### ISSUE THREAD

**Issue by shk3bq4d** [okta/terraform-provider-okta#2029]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.6.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.6.1
+ provider registry.terraform.io/okta/okta v4.9.1
```

### Affected Resource(s)

- okta_app_signon_policy_rule

### Terraform Configuration Files

The actual json to encode the constraints was retrieved by an API call after having successfully created the rule in the Admin GUI

```hcl
resource "okta_app_signon_policy_rule" "example1" {
  name                        = "example1"
  priority                    = 1
  groups_excluded             = []
  groups_included             = []
  access                      = "ALLOW"
  policy_id                   = okta_app_signon_policy.not_included.id
  factor_mode                 = "2FA"
  re_authentication_frequency = "PT12H"
  constraints = [jsonencode(
    {
      "knowledge" : {
        "authenticationMethods" : [
          {
            "key" : "okta_password",
            "method" : "password"
          }
        ],
        "required" : false
      },
      "possession" : {
        "authenticationMethods" : [
          {
            "key" : "okta_email",
            "method" : "email"
          },
          {
            "key" : "webauthn",
            "method" : "webauthn"
          }
        ],
        "required" : false,
        "userPresence" : "REQUIRED"
      }
    }
  )]
}

resource "okta_app_signon_policy_rule" "example2" {
  name                        = "example2"
  priority                    = 2
  groups_excluded             = []
  groups_included             = []
  access                      = "ALLOW"
  policy_id                   = okta_app_signon_policy.not_included.id
  factor_mode                 = "2FA"
  re_authentication_frequency = "PT12H"
  constraints = [jsonencode(
    {
      "possession" : {
        "excludedAuthenticationMethods" : [
          {
            "key" : "okta_verify",
            "method" : "totp"
          },
          {
            "key" : "okta_verify",
            "method" : "push"
          },
          {
            "key" : "phone_number",
            "method" : "sms"
          }
        ],
        "required" : false,
        "userPresence" : "OPTIONAL"
      }
    }
  )]
}
```

### Expected Behavior

authenticationMethods and excludedAuthenticationMethods are taken into account

#### Can this be done in the Admin UI?

Yes

#### Can this be done in the actual API call?

I don't know

### Actual Behavior

the policy rules get created, but with different contstraints then expected.

Subsequent applies keeps wanting to enforce changes though with no further actual modifications

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-744794

**Comment by joecarterbooking** [comment]
I've also observed that if you manage an authentication policy rule via Terraform and then subsequently set via the UI any factor to allowed/disallowed (because the provider doesn't support this yet), any subsequent Terraform run will undo that change.  This basically means that if you want to use the allow/disallow specific authenticators, you cannot manage the auth policies using Terraform at all.

**Comment by lucascantor** [comment]
Is this a duplicate of https://github.com/okta/terraform-provider-okta/issues/1932 as well?

**Comment by duytiennguyen-okta** [comment]
@lucascantor it should be. Thanks for mentioning it
