### ISSUE TITLE
resource_okta_app_bookmark produces RPC issue when planning

### ISSUE THREAD

**Issue by duy-ng-12354** [okta/terraform-provider-okta#204]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.29 **(running on Terraform Enterprise)**

### Affected Resource(s)

okta_app_bookmark

### Terraform Configuration Files

```hcl
resource "okta_app_bookmark" "<name>" {
  label = "<app label>"
  url   = <from local variable>

  lifecycle {
    ignore_changes = [
      users,
    ]
  }
}
```

### Debug Output

https://gist.github.com/duy-ng-12354/275d267ca7f7a864be038d5b3d87e987

### Expected Behavior

It should work without throwing "rpc error: code = Unavailable desc = transport is closing"

### Actual Behavior

The terraform planning cannot be success because of mentioned error.

### Steps to Reproduce

"terraform plan" with the mentioned codes

**Comment by bogdanprodan-okta** [comment]
Hi @duy-ng-12354! I don't think RPC errors have something to do with the provider itself, it's likely related to the connectivity issues.
