### ISSUE TITLE
Terrafrom documentation is missing params for okta_app_bookmark

### ISSUE THREAD

**Issue by ghost** [okta/terraform-provider-okta#205]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
all versions

### Affected Resource(s)

* okta_app_bookmark

### Terraform Configuration Files
-
### Debug Output
-

### Panic Output
-

### Expected Behavior
Terraform docs would document https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/app_bookmark all options which we can use. For example `groups` is missing there.

### Actual Behavior

TF documentation do not mention all options: https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/app_bookmark
however example repo has more options: https://github.com/oktadeveloper/terraform-provider-okta/blob/master/examples/okta_app_bookmark/basic_updated.tf

not sure if that are all options which we can use or there is something else missing

### Steps to Reproduce
-
### Important Factoids

-

### References
* https://github.com/oktadeveloper/terraform-provider-okta/blob/master/examples/okta_app_bookmark/basic_updated.tf
* https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/app_bookmark

**Comment by bogdanprodan-okta** [comment]
Hi @dusan-dragon! Sorry for such a late reply. There is an intention to review and update all the documents in Okta terraform provider, so supposedly all the fixes will be published in v3.7.2.

**Comment by bogdanprodan-okta** [comment]
Hi @dusan-dragon! The issue should be fixed in the latest 3.7.2 version. In case it still exists, please reopen this issue.
