### ISSUE TITLE
`app_group_assignments.min_items` prevents explicit zero group assignments

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#2068]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
N/A

### Affected Resource(s)
- okta_app_group_assignments

### Terraform Configuration Files
```hcl
resource "okta_app_group_assignments" "example" {
  app_id = okta_app_bookmark.example.id

  # This application should never have a group assigned to it

}
```

### Debug/panic Output

Terraform validate fails stating that at least one group block is required

### Expected Behavior

I should be able to explicitly manage that an application should have no groups assigned to it

#### Can this be done in the Admin UI?
N/A

#### Can this be done in the actual API call?
N/A

### Actual Behavior
Terraform validate fails on the `okta_app_group_assignments` resource and states that at least one group block is required due to the `min_items` in the resource schema

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
This might be a dupe as I feel like i've raised this in the past
but if there is an existing issue for this, I couldn't find it ¯\\_(ツ)_/¯ 

### References
- #0000

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-795144

**Comment by exitcode0** [comment]
@duytiennguyen-okta I've raise a PR for this #2069
