### ISSUE TITLE
Configuration parameters parallelism, min_wait_time, and backoff are not used

### ISSUE THREAD

**Issue by ymylei** [okta/terraform-provider-okta#210]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.29

### Affected Resource(s)

N/A

### Terraform Configuration Files

config.go 
provider.go
provider_test.go
utils.go

```go
Config struct {
		orgName              string
		domain               string
		apiToken             string
		retryCount           int
		parallelism          int
		backoff              bool
		maxWait              int
		articulateOktaClient *articulateOkta.Client
		oktaClient           *okta.Client
		supplementClient     *sdk.ApiSupplement
		ctx                  context.Context
	}
```

```go
articulateClient, err := articulateOkta.NewClientWithDomain(httpClient, c.orgName, c.domain, c.apiToken)
```

```go
ctx, client, err := okta.NewClient(
		context.Background(),
		okta.WithOrgUrl(orgUrl),
		okta.WithToken(c.apiToken),
		okta.WithCache(false),
		okta.WithHttpClient(*httpClient),
		okta.WithRequestTimeout(int64(c.maxWait)),
		okta.WithRateLimitMaxRetries(int32(c.retryCount)),
		okta.WithUserAgentExtra("okta-terraform/3.6.0"),
	)
```

```go
c.supplementClient = &sdk.ApiSupplement{
		BaseURL:         fmt.Sprintf("https://%s.%s", c.orgName, c.domain),
		Client:          httpClient,
		Token:           c.apiToken,
		RequestExecutor: client.GetRequestExecutor(),
	}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The configuration variables parallelism, min_wait_time, and backoff would be consumed by one of client api interfaces to alter behavior.

### Actual Behavior

These do not appear to be used in any of the client libraries.

### Steps to Reproduce

N/A

### References

N/A

* #0000

**Comment by jfriv** [comment]
Looks like the application of those values on the http client was removed here:
https://github.com/oktadeveloper/terraform-provider-okta/commit/d92e7743ac44c67e18ce32eb6756eab49e276309#diff-943c1ebd2e94122586bfc4772625552a6af0f781fe16140c99c66c64e394eb12L66

**Comment by jfriv** [comment]
Downgrading and pinning the okta provider version to v3.5.1 resolved our rate limit issues

**Comment by bogdanprodan-okta** [comment]
Hi @jfriv! We are aware of this issue and there is already a PR to fix that. Once it will be merged and a new version of SDK will be rolled out, I will update providers modules, so the new version will no longer have this issue.
