### ISSUE TITLE
`okta_policy_mfa_default` sending priority from terraform state causes API errors

### ISSUE THREAD

**Issue by tmonck** [okta/terraform-provider-okta#2107]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.9.8
on darwin_arm64
+ provider registry.terraform.io/okta/okta v4.11.0
```
### Affected Resource(s)

- okta_policy_mfa_default

### Terraform Configuration Files

```hcl
resource "okta_policy_mfa_default" "default_policy" {
  is_oie = false

  okta_otp = {
    enroll = "OPTIONAL"
  }

  google_otp = {
    enroll = "OPTIONAL"
  }

  okta_email = {
    enroll = "REQUIRED"
  }
}

```

### Debug Output

│ Error: failed to update default MFA policy: the API returned an error: Cannot modify the priority attribute because it is read-only.
│ 
│   with okta_policy_mfa_default.default_policy,
│   on mfa.tf line 25, in resource "okta_policy_mfa_default" "default_policy":
│   25: resource "okta_policy_mfa_default" "default_policy" {
│ 

### Expected Behavior

The default MFA policy should not error during updates.

#### Can this be done in the Admin UI?

No
#### Can this be done in the actual API call?

I don't know
### Actual Behavior

The default MFA policy errors out due to priority being passed.
### Steps to Reproduce

1. `terraform apply`
2. Add another mfa policy either via the UI
3. `terraform apply`
4. Remove the newly added policy via the UI
5. `terraform apply`
6. Update the terraform to have a modification on the default MFA policy. (Change something from required to optional or not allowed)
7. `terraform apply`

Step 7 should error out.

Any changes that cause the priority value in the terraform state to differ from what is actually returned via the API for policies seems to trigger the error condition.

### References

- #0000

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-822267

**Comment by tmonck** [comment]
I tried to implement a fix for this, but it seems that this issue is caused by the Policy API. Even though the `priority` attribute is an optional value, when the policy is the default Policy it seems that it must be passed and it must be the value that is currently stored on it.

I would think that if `priority` is `read-only` on the default policies then the API should handle not providing the value appropriately and only reject if it supplied. If the API decides to reject only when supplied for the Default Policy then this provider would require an update to not send the value in the API call.

**Comment by duytiennguyen-okta** [comment]
@tmonck I wasn't able to reproduce the problem using your description, but I managed to get it error out another way. Basically my understanding is because of the newly added policy, priority for the default policy is changed. And now the default policy is unable to update because of mismatch priority. Sounds about right?

**Comment by tmonck** [comment]
Yea that's about right.
