### ISSUE TITLE
Generate new SAML App Signing Cert available via this Terraform provider?

### ISSUE THREAD

**Issue by brandongblack** [okta/terraform-provider-okta#212]
Hello,

I am wondering if the following functionality is supported in this terraform provider.. I see some references to it in the code but not seeing it - are you able to confirm if this is officially supported or not? If it is supported how would we implement? Rather which resource should be used

https://developer.okta.com/docs/reference/api/apps/#generate-new-application-key-credential

Here is the line reference
https://github.com/oktadeveloper/terraform-provider-okta/blob/9ed9da02e8b319f0dec570d2ef76ef05bf4cd844/okta/resource_okta_app_saml.go#L567

Thank You

**Comment by noinarisak** [comment]
@brandongblack  We missing documentation on the `key_name` attribute that will determine to generate another cert for the saml app. Let me attached @bogdanprodan-okta to confirm my observation at [line of code](https://github.com/oktadeveloper/terraform-provider-okta/blob/0dad1ef71abbedf5cb454de0bdc2929321e77778/okta/resource_okta_app_saml.go#L538) and we should update the our documentation and add example. Thanks!

**Comment by bogdanprodan-okta** [comment]
Hi @brandongblack! There is a new 3.7.1 version of the provider with `key_name` in the documentation. Could you please try using that to create new certificate?

**Comment by brandongblack** [comment]
Excellent thank you for the update! - will give it a try

**Comment by bogdanprodan-okta** [comment]
Hi @brandongblack! I'm closing this issue because it seems that using `key_name` fixed the problem. If it did not, please reopen this issue. Thanks!
