### ISSUE TITLE
okta_oauth_app default value for consent_method argument (EA feature)

### ISSUE THREAD

**Issue by PurrBiscuit** [okta/terraform-provider-okta#213]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
terraform -v
Terraform v0.12.29
+ provider.aws v3.13.0
+ provider.consul v2.10.1
+ provider.datadog v2.15.0
+ provider.local v2.0.0
+ provider.ohdear v1.0.0
+ provider.okta v3.6.0
+ provider.vault v2.15.0
```

### Affected Resource(s)

* okta_oauth_app

### Terraform Configuration Files

```hcl
resource "okta_oauth_app" "example_frontend" {
  label          = "example-frontend"
  type           = "browser"
  consent_method = var.env == "stage" ? "TRUSTED" : null

  grant_types = [
    "implicit",
  ]

  redirect_uris = [
    "https://frontend.example.com/callback"
  ]

  post_logout_redirect_uris = [
    "https://frontend.example.com/auth-logout"
  ]

  response_types = [
    "id_token",
    "token",
  ]

  login_uri                                   = "https://frontend.example.com/auth-callback"
  issuer_mode                            = "CUSTOM_URL"
  groups                                     = [data.okta_everyone_group.all.id]
  token_endpoint_auth_method = "none"
}
```

### Expected Behavior

The `consent_method` argument's value on the `okta_oauth_app` resource should be ignored if a `null` value is passed to it since this is an `Early Access` feature still and we don't have it enabled in some of our production Okta accounts.  We have some Okta accounts in stage that do have that EA feature enabled however and we're using a ternary to set that value or keep it `null` to ignore it, example  `consent_method = var.env == "stage" ? "TRUSTED" : null`.  This worked fine up until version `3.6.0` of the Okta provider.

We're getting perpetual diffs now that are trying to add this argument to our oauth apps in our production accounts even though it doesn't exist.  It looks like a default value was added in this PR that was merged a couple weeks ago -> https://github.com/oktadeveloper/terraform-provider-okta/pull/203.  According to [Okta core docs](https://www.terraform.io/docs/configuration/expressions.html) this is expected behavior for `null` if a default value exists for the resource.

>null: a value that represents absence or omission. If you set an argument of a resource or module to null, Terraform behaves as though you had completely omitted it — it will use the argument's default value if it has one, or raise an error if the argument is mandatory. null is most useful in conditional expressions, so you can dynamically omit an argument if a condition isn't met.

Can the DefaultValue be removed once again until this feature is no longer EA in Okta?

### Actual Behavior

Setting the `okta_oauth_app` `consent_method` argument to `null` is causing a perpetual diff in our production Okta accounts that don't have the EA consent_method feature enabled.

### Steps to Reproduce

1. Setup terraform to configure an Okta without the EA consent_method feature enabled for Oauth Apps.
2. Use the example terraform code above and set `consent_method` to `null`.
3. Observe terraform trying to set this to the default of `"TRUSTED"` on subsequent terraform plans/applies.

**Comment by bogdanprodan-okta** [comment]
Hi @PurrBiscuit ! Thanks for submitting this issue. Fix for your problem is currently in PR #215. Hopefully, we will merge it soon and roll out the `3.6.1` version of the terraform provider.

**Comment by PurrBiscuit** [comment]
@bogdanprodan-okta looks like that `consent_method` attribute just got released as a General Availability Feature with the last Okta Production release for November - [User Consent for OAuth 2.0 Flows in API Access Management](https://help.okta.com/en/prod/Content/Topics/ReleaseNotes/production.htm).  The Okta Apps API also no longer lists it as `EA` and makes it a `required` attribute.  It's probably safe to leave the DefaultValue there now after all.  Thanks for the work on this though. 👍

**Comment by bogdanprodan-okta** [comment]
Hi @PurrBiscuit! The `consent_method` attribute still has a default value, but I put a safety `if` statement in case some orgs still don't have it. I'm closing this issue for now, but we can always reopen it though!
