### ISSUE TITLE
os_expression is not working as expected when a okta_policy_rule_idp_discovery resource is imported with os_type = "OTHER"

### ISSUE THREAD

**Issue by rajnadimpalli** [okta/terraform-provider-okta#2138]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

![image](https://github.com/user-attachments/assets/7ac5bd71-73d3-4f90-8e99-70497e773fdf)

### Affected Resource(s)

- okta_policy_rule_idp_discovery

### Issue summary
When an IDP discovery policy rule is created via Okta admin console with `OS_TYPE = "OTHER"` and the resource `okta_policy_rule_idp_discovery` is imported using `terraform import`, the exported resource has `os_expression` set to `""`.
When running a `terraform apply `, it fails because `os_expression` doesn't accept `""` value.

Please see error below:
`Error: failed to create app sign on policy rule: the API returned an error: Api validation failed: conditions.platform. Causes: errorSummary: conditions.platform: The condition 'platform' must have os.expression if os.type is OTHER.`

### Terraform Configuration Files

```hcl
resource "okta_policy_rule_idp_discovery" "dummy_rule1" {
  idp_id                    = null
  idp_type                  = null
  name                      = "Test rule"
  network_connection        = "ANYWHERE"
  network_excludes          = null
  network_includes          = null
  policy_id                 = "00p1k7y5zwMDBASDD1d7"
  priority                  = 1
  status                    = "ACTIVE"
  user_identifier_attribute = null
  user_identifier_type      = null
  platform_include {
    os_expression = ""
    os_type       = "ANY"
    type          = "ANY"
  }
}
```

### Steps to Reproduce

1. Create an IDP discovery rule via Okta admin console with os_type = "OTHER"
2. Import the IDP discovery rule rule to terraform
3. Run `terraform plan`

When an IDP discovery rule is created with os_type = "OTHER" and it is retrieved via API, notice that os_expression = "", however terraform resource doesn't accept the same value.

### References

- #0000

**Comment by duytiennguyen-okta** [comment]
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-832970
