### ISSUE TITLE
Too many refreshing states

### ISSUE THREAD

**Issue by Reflejo** [okta/terraform-provider-okta#2145]
Every time I sync terraform I see hundreds of:

`okta_app_user.<app>[user]: Refreshing state... [id=xxx]`

As a matter of fact I see it (# apps x # users) times. This consumes all our API limits and makes syncing extremely slow. Am I doing something wrong here or that's expected?

**Comment by duytiennguyen-okta** [comment]
If you are using terraform refresh, then terraform will have to read every state in the of okta_app_user. That is something the provider cannot control

**Comment by Reflejo** [comment]
Not sure what you mean by refresh? This is every time a terraform plan is done on CI.

**Comment by Reflejo** [comment]
Sorry I know this was closed but this is not only extremely slow, it also consumes APIs limits and I only have 15 employees. How is this suppose to scale to 1000s? We ran terraform on CI (as I presume most? so state is fresh). Is there a plan to make batch API calls as opposed to one per user per app?

**Comment by Reflejo** [comment]
@duytiennguyen-okta Coming back to this. I understand we don't control the refresh, but you do control *how* you refresh, no?. I'm trying to understand how anyone is using the tf provider with hundreds of users? In my case a terraform plan literally makes `# apps x # users` requests. Instead for example, the provider might call `GET /api/v1/apps/{appId}/users` once instead of once per user per app no?
