### ISSUE TITLE
Profile mapping changes replaced 

### ISSUE THREAD

**Issue by venkatakanupuru** [okta/terraform-provider-okta#2156]
Hi Team.

Using the resource "okta_profile_mapping" during initial configuring of the IDP, I am able to configure the profile mapping. However, after some troubleshooting from the console and changes which were done manually when I update the TF script reflecting the changes and run a plan it shows the profile mapping will be replaced.

Not sure what is the timeline for the profile mapping import is but it would be really helpful if profile mapping can be imported.
OKTA internal reference https://oktainc.atlassian.net/browse/OKTA-717456

Found issues reported for importing the profile mapping but not of this kind which I am facing.
Please ignore if reported or link to something similar.

**Terraform Version**

Terraform v1.4.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.76.1
+ provider registry.terraform.io/okta/okta v4.11.0

**Affected Resource(s)**
resource "okta_profile_mapping"

**Terraform Configuration Files**

  # module.test-idp.okta_profile_mapping.test-idp is tainted, so must be replaced
-/+ resource "okta_profile_mapping" "test-idp" {
      ~ id                 = "prm********5d7" -> (known after apply)
      ~ source_name        = "saml_idp" -> (known after apply)
      ~ source_type        = "appuser" -> (known after apply)
      ~ target_name        = "user" -> (known after apply)
      ~ target_type        = "user" -> (known after apply)
        # (4 unchanged attributes hidden)

        # (10 unchanged blocks hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Thank you for the help

**Comment by duytiennguyen-okta** [comment]
Similar to #1955
