### ISSUE TITLE
Add okta_idp_oidc data resource

### ISSUE THREAD

**Issue by eatplaysleep** [okta/terraform-provider-okta#222]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to be able to retrieve details about an OIDC Idp from Okta.

### New Resource

* okta_idp_oidc

### Potential/Suggested Terraform Configuration

```hcl
data "okta_idp_oidc" "idp" {
   name = "some_oidc_idp"
}
```
_or_
```hcl
data "okta_idp_oidc" "idp" {
   id = "123456"
}
```

**Comment by bogdanprodan-okta** [comment]
Hi @eatplaysleep! Thanks for submitting this issue! After the holidays, there will be an internal discussion around which new resources should be added to v3.8.0, so I'll add another comment after.
