### ISSUE TITLE
Terraform failed to retrieve authentication checksums for provider

### ISSUE THREAD

**Issue by vpedosyuk** [okta/terraform-provider-okta#229]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.13.5

### Affected Resource(s)

provider initialization affected

### Terraform Configuration Files

the very basic config fails:
https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs#example-usage

### Debug Output

```
Initializing the backend...

Initializing provider plugins...
- Finding oktadeveloper/okta versions matching "~> 3.6"...

Error: Failed to install provider

Error while installing oktadeveloper/okta v3.6.1: could not query provider
registry for registry.terraform.io/oktadeveloper/okta: failed to retrieve
authentication checksums for provider: 404 Not Found
```

**Comment by svanharmelen** [comment]
Using Terraform 0.14.x gives the same error since some 45 minutes ago (give or take)

**Comment by tgoodsell-tempus** [comment]
Looks like something caused the v3.6.1 release data to get messed up, since it's no longer tagged as "latest" and the artifacts and release notes are gone.

**Comment by bogdanprodan-okta** [comment]
@vpedosyuk Hi! Sorry for this mess :( The issue should be fixed right now. Could you try and confirm that it's fixed?

**Comment by svanharmelen** [comment]
Yes, looks to be working again! Thanks 👍🏻
