### ISSUE TITLE
What happened to v3.6.1?

### ISSUE THREAD

**Issue by isometry** [okta/terraform-provider-okta#230]
Apologies for the non-standard format, but there's not much to say…

Provider version v3.6.1 was originally released 22 days ago, but seems to have gone AWOL 4 hours ago. What happened? `terraform init` on new modules requiring the features in v3.6.1 is currently failing.

**Comment by joe-a-t** [comment]
Duplicate of https://github.com/oktadeveloper/terraform-provider-okta/issues/229
