### ISSUE TITLE
No clear how to have pkce on an application

### ISSUE THREAD

**Issue by mcrobbj** [okta/terraform-provider-okta#231]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
When creating an application resource there doesnt seem to be a means of using pkce

### New or Affected Resource(s)

- okta_app_oauth

### Potential Terraform Configuration

```hcl
resource "okta_app_oauth" "MobileApp" {
  label          = "Mobile App"
  type           = "native"
  grant_types    = ["authorization_code", "refresh_token"]
  redirect_uris  = ["myApp://redirectToLogin"]
  consent_method = "REQUIRED"
  omit_secret    = true
  lifecycle {
    ignore_changes = [groups]
  }
}
```

### References

- #0000

**Comment by maxyms** [comment]
@mcrobbj 
Didn't check for `type = native`, but for SPA (`type = browser`) worked for me setting `token_endpoint_auth_method` to `none`.
Found example at: https://github.com/oktadeveloper/okta-dac/blob/master/terraform/main.tf

**Comment by mcrobbj** [comment]
> @mcrobbj
> Didn't check for `type = native`, but for SPA (`type = browser`) worked for me setting `token_endpoint_auth_method` to `none`.
> Found example at: https://github.com/oktadeveloper/okta-dac/blob/master/terraform/main.tf

Ok that works for native too, thanks

**Comment by mcrobbj** [comment]
Closed as options above work
