### ISSUE TITLE
issue when applying changes to a `okta_user_schema`

### ISSUE THREAD

**Issue by recintoit** [okta/terraform-provider-okta#234]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
terraform 0.14.2 
But this also happens on .13

### Affected Resource(s)

okta_user_schema

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
resource "okta_user_schema" "ca_regsrc" {
  index       = "registration_source"
  title       = "Registration Source"
  type        = "string"
  description = "Name of the business unit that registered the user."
  scope       = "NONE"
  # min_length  = 1
  # max_length  = 200
  permissions = "READ_ONLY"
  master      = "PROFILE_MASTER"


}

### Debug Output

<!---
Please provide a link to a GitHub Gist containing the complete debug output. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

To obtain the debug output, see the [Terraform documentation on debugging](https://www.terraform.io/docs/internals/debugging.html).
--->

### Panic Output

<!--- If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`. --->

### Expected Behavior

<!--- What should have happened? --->
A new custom attribute in the Okta User profile should have been created.  
It sometimes is created, sometimes this shows when running an apply against an already created custom attribute

When applying changes to okta_user_schema.ca_regsrc, provider
2020-12-12T01:22:20.4152573Z "registry.terraform.io/terraform-providers/okta" produced an unexpected new
2020-12-12T01:22:20.4154031Z value: Root resource was present, but now absent.

<!--- What actually happened? --->

### Steps to Reproduce

Run terraform apply to an org and the error happens for me

1. `terraform apply`

### Important Factoids

<!--- Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? --->

### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor documentation? For example:
--->

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi @recintoit! Thanks for submitting this issue! I will investigate it and get back with the result shortly!

**Comment by recintoit** [comment]
I tried to revert to version 13.1, but the error is still there.  This time it seemed to create one of the custom attributes but not the other.  One custom attribute was created with no error.
2020-12-14T17:15:36.8118933Z [1m[31mError: [0m[0m[1mProvider produced inconsistent result after apply[0m
2020-12-14T17:15:36.8119848Z 
2020-12-14T17:15:36.8120431Z [0mWhen applying changes to okta_user_schema.ca_regsrc, provider
2020-12-14T17:15:36.8121848Z "registry.terraform.io/terraform-providers/okta" produced an unexpected new
2020-12-14T17:15:36.8122443Z value: Root resource was present, but now absent.
2020-12-14T17:15:36.8122733Z 
2020-12-14T17:15:36.8124996Z This is a bug in the provider, which should be reported in the provider's own
2020-12-14T17:15:36.8125803Z issue tracker.
2020-12-14T17:15:36.8126059Z [0m[0m
2020-12-14T17:15:36.8126293Z [31m
2020-12-14T17:15:36.8126895Z [1m[31mError: [0m[0m[1mProvider produced inconsistent result after apply[0m
2020-12-14T17:15:36.8127328Z 
2020-12-14T17:15:36.8129394Z [0mWhen applying changes to okta_user_schema.ca_cci_master, provider
2020-12-14T17:15:36.8131862Z "registry.terraform.io/terraform-providers/okta" produced an unexpected new
2020-12-14T17:15:36.8134053Z value: Root resource was present, but now absent.
2020-12-14T17:15:36.8134409Z 
2020-12-14T17:15:36.8136504Z This is a bug in the provider, which should be reported in the provider's own
2020-12-14T17:15:36.8139230Z issue tracker.
2020-12-14T17:15:36.8139366Z [0m[0m
2020-12-14T17:15:37.4464002Z ##[error]PowerShell exited with code '1'.

**Comment by recintoit** [comment]
I tried a 'depends on' to try to get the tf to acknowledge the other custom attributes.  I recieve this error. I am starting to think there is a dependency issue that I'm missig to get this to work.  The main goal is to be able to create more that one okat_user_schema (custom attribute) in one file.
I am trying now to create two separate .tf files with the end goal as modules for each custom attribute.

Below is the output after I tried 'depends on':  

resource "okta_user_schema" "ca_cci_master" {
  index       = "cci_master_id"
  title       = "CCI Master ID"
  type        = "string"
  description = "Used as the unique identifier across all of Common Customer Identity, including target spokes. Excluding employee Okta."
  scope       = "NONE"
  min_length  = 1
  max_length  = 200
  permissions = "READ_ONLY"
  master      = "PROFILE_MASTER"

  depends_on = [okta_user_schema.ca_idp_source, okta_user_schema.ca_regsrc]
}

resource "okta_user_schema" "ca_idp_source" {
  index       = "idp_source"
  title       = "IDP Source"
  type        = "string"
  description = "For Common Customer, tells which Okta org the identity is mastered in"
  scope       = "NONE"
  min_length  = 1
  max_length  = 200
  permissions = "READ_ONLY"

  depends_on = [okta_user_schema.ca_cci_master, okta_user_schema.ca_regsrc]
}

resource "okta_user_schema" "ca_regsrc" {
  index       = "registration_source"
  title       = "Registration_Source"
  type        = "string"
  description = "ID's which app created the user"
  scope       = "NONE"
  min_length  = 1
  max_length  = 200
  permissions = "READ_ONLY"

  depends_on = [okta_user_schema.ca_cci_master, okta_user_schema.ca_idp_source]
}


Error: Cycle: okta_user_schema.ca_cci_master, okta_user_schema.ca_idp_source, okta_user_schema.ca_regsrc

**Comment by recintoit** [comment]
I tried to perform a work around and create a module to create custom okta_user_schema and I get the errors after one of the attributes is created.  I would like to know if this issue is a bug or something I am leaving out in the config.  But I am creating very basic attriutes.


This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent result after apply

When applying changes to module.createccid.okta_user_schema.ca_cci_master,
provider "registry.terraform.io/terraform-providers/okta" produced an
unexpected new value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Comment by recintoit** [comment]
If it helps, I have tried this on 4 completely different Okta Orgs that I have as well as my company's.

**Comment by bogdanprodan-okta** [comment]
Hi @recintoit ! Thanks for the investigation and detailed output. I will get back to you with the solution to this problem.

**Comment by bogdanprodan-okta** [comment]
Hi @recintoit! The problem is not in the provider itself, it's in sometimes OKTA is not keeping up with custom attributes creation. During the provider's flow `create` ->  `read` -> `check state`, `read` step sometimes doesn't return created custom property, although it's there (I've checked like dozen times). Running `terraform apply` the second time solves the problem. From my side, I can add a retry action in case OKTA doesn't return the correct result so that it will make several attempts during the `read` step.

**Comment by eatplaysleep** [comment]
Have also been experiencing this issue for quite some time but usually just run apply over and over and over again until it finally finishes. Very annoying when you have hundreds of fields.... would love to see a fix!

**Comment by bogdanprodan-okta** [comment]
> Have also been experiencing this issue for quite some time but usually just run apply over and over and over again until it finally finishes. Very annoying when you have hundreds of fields.... would love to see a fix!
That is not specific when you creating a resource, it also happens when you update one.
