### ISSUE TITLE
Terraform resource for okta self service registration.

### ISSUE THREAD

**Issue by venkatakanupuru** [okta/terraform-provider-okta#235]
Hi Team,

Can you please suggest how I can automate/ implement Self Service Registration  using terraform ?(UI steps are listed below)
Are there any terraform resources available for direct implementation or should I use third party / external tools ?

**Self Service Registration in Okta UI**

1.In the Admin Console, go to Directory > Self-Service Registration.
2.Click Edit.
3.In the Self-service registration list, select Enabled.
4.Complete these fields:
  Add to Sign-In widget: Optional. 
  Assign to group: Enter the names of existing groups that users will be added to automatically when they self register.
5.In the REGISTRATION FORM area, complete these fields:
Login field form label: Optional. Enter a label for the Email field on the Create Account registration form.

Password field form label: Optional. Enter a label for the Password field on the Create Account registration form.

Registration form fields: Select the fields you want included on the Create Account registration form. You can accept the default field label value, or optionally enter a field name in the Form label field. Select the Required check box to make the field mandatory. To require additional fields, click Add Field. To change the priority of a field, click and drag it to a new location. To remove a field, click X.

The registration form supports string, number, Boolean, and integer data types, as well as enum data types for strings, numbers, and integers.

6.In the POST REGISTRATION area, complete these fields:
Activation requirements: Optional. Select User must verify email address to be activated to automatically send users a register activation email. If you don't select the check box, and users are not required to verify their email address for activation, a Registration Verification email using Okta email templates is sent. See Email and SMS Options.

Default redirect: Select User dashboard to redirect users to your org’s Okta homepage, or select Custom URL to redirect users to your custom app, OIDC portal, or SAML portal.

7.Click Save.
8.Optional. If you added fields to the registration form in step 5, go to Directory > Profile Editor. 
Select the profile that contains your new attribute.
Find the new attribute, and then click its information icon.
In the User permission drop-down box, select Read - Write.
Click Save Attribute. End users can modify this field after registration in their settings page.

Please Help. Thanks in advance.
Venkata

**Comment by tgoodsell-tempus** [comment]
There does not appear to be API support for managing the self-service registration options. Therefore this terraform provider would not be able to support managing it either.

Reference: https://developer.okta.com/docs/reference/

**Comment by noinarisak** [comment]
Hi @venkatakanupuru! @tgoodsell-tempus is correct. Sorry! 😞

**Comment by venkatakanupuru** [comment]
Hi @tgoodsell-tempus @noinarisak, Is there any work around for this ?
How can we automate it ? Any suggestions please.
I am looking for both okta self service registration and customizing sign in widget.

Thank you

**Comment by noinarisak** [comment]
@venkatakanupuru Unfortunately, only option which is not ideal since it is fragile approach, is a web crawler/browser simulation using something like Selenium, but I don't recommend it. 

Please submit a Okta idea at https://support.okta.com/help/s/article/Okta-Ideas-Overview-FAQ?language=en_US so the request is visible outside of this repo. Thanks and sorry again!

**Comment by mcrobbj** [comment]
Added an idea for this, https://ideas.okta.com/app/#/case/171390, I also think its linked to https://ideas.okta.com/app/#/case/106554
