### ISSUE TITLE
Cannot import saml_app and then use the app_settings, aws app, Invalid reference

### ISSUE THREAD

**Issue by lohman** [okta/terraform-provider-okta#236]
Hi there,

Struggling to use the app_settings_json with an okta_app_saml resource.  Is this a bug?  Or could documentation be written to help us understand how to write the app_settings_json?

I manually created a saml2 app in Okta (aws) and then I imported it in to my state.  I am now attempting to translate that in to my tf file.  When I run a plan, it's hanging up on the roleValuePattern in the app_settings.

```
resource "okta_app_saml" "aws_tf_test" {
    accessibility_self_service = false
    app_settings_json          = jsonencode(
        {
            appFilter           = "okta"
            awsEnvironmentType  = "aws.amazon"
            groupFilter         = "awstftest_(?{{accountid}}\\d+)_(?{{role}}[a-zA-Z0-9+=,.@\\-_]+)"
            identityProviderArn = "arn:aws:iam::123456789012:saml-provider/okta"
            joinAllRoles        = true
            roleValuePattern    = "arn:aws:iam::${accountid}:saml-provider/okta,arn:aws:iam::${accountid}:role/${role}"
            sessionDuration     = 43200
            useGroupMapping     = true
        }
    )
    features                   = [
        "PUSH_NEW_USERS",
        "PUSH_PROFILE_UPDATES",
    ]
    id                         = "stuff"
    key_id                     = "longer stuff"
    label                      = "AWS TF TEST"
    preconfigured_app          = "amazon_aws"
}
```

It seems to be unhappy with the variables in that string.

> Error: Invalid reference
> 
>   on apps.tf line 13, in resource "okta_app_saml" "aws_tf_test":
>   13:             roleValuePattern    = "arn:aws:iam::${accountid}:saml-provider/okta-christopher-dev,arn:aws:iam::${accountid}:role/${role}"
> 
> A reference to a resource type must be followed by at least one attribute
> access, specifying the resource name.
> 
> Error: Invalid reference
> 
>   on apps.tf line 13, in resource "okta_app_saml" "aws_tf_test":
>   13:             roleValuePattern    = "arn:aws:iam::${accountid}:saml-provider/okta-christopher-dev,arn:aws:iam::${accountid}:role/${role}"
> 
> A reference to a resource type must be followed by at least one attribute
> access, specifying the resource name.
> 
> Error: Invalid reference
> 
>   on apps.tf line 13, in resource "okta_app_saml" "aws_tf_test":
>   13:             roleValuePattern    = "arn:aws:iam::${accountid}:saml-provider/okta-christopher-dev,arn:aws:iam::${accountid}:role/${role}"
> 
> A reference to a resource type must be followed by at least one attribute
> access, specifying the resource name.

Can you provide any suggestions on how to make the roleValuePattern work?

**Comment by bogdanprodan-okta** [comment]
Hi @lohman! the problem is that terraform treats `$` as a special [escape sequence](https://www.terraform.io/docs/configuration/expressions/strings.html#escape-sequences), so you need to use `$$` to make things work.
```
  "roleValuePattern": "arn:aws:iam::$${accountid}:saml-provider/OKTA,arn:aws:iam::$${accountid}:role/$${role}",
```

**Comment by lohman** [comment]
@bogdanprodan-okta awesome...  That would be a good one for the docs.  Thanks very much.
