### ISSUE TITLE
Terraform resource for custom sign in widget.

### ISSUE THREAD

**Issue by venkatakanupuru** [okta/terraform-provider-okta#240]
Hi Team,

Can you please suggest how I can automate/ implement custom sign in widget using terraform ?(UI steps are listed below)
Are there any terraform resources available for direct implementation or should I use third party / external tools ?

Okta-hosted Sign-In Widget
Edit the sign-in page 
Change the Okta Sign-In Widget version
1.To make changes to the major and minor versions, select Edit in the Okta Sign-In Widget Version section header.
2.Make your changes, and then click Save at the bottom of the page.

Use the embedded HTML editor
1.Make changes directly in the embedded editor.
2.Click Preview to preview your changes before you publish.
3.Click Reset to Default if you need to remove all of your customizations and restore the default HTML/CSS and JavaScript code.
4.Click Save and Publish when you finish.

Please Help. Thanks in advance.
Venkata

**Comment by tgoodsell-tempus** [comment]
There does not appear to be a management API for the Okta UI modifications, therefore this would not be something that this terraform provider could do for you.

Reference: https://developer.okta.com/docs/reference/
