### ISSUE TITLE
Fresh v3.7 crashes on refresh of user attributes resources

### ISSUE THREAD

**Issue by khitrenovich** [okta/terraform-provider-okta#241]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.13.2
TF Okta provider v3.7

### Affected Resource(s)

- okta_user_base_schema
- okta_user_schema

### Terraform Configuration Files

Any base or custom attribute "works", for eample - 

```hcl
resource "okta_user_base_schema" "first_name" {
  index       = "firstName"
  title       = "First name"
  type        = "string"
  master      = "OKTA"
  required    = true
  permissions = "READ_WRITE"
}
```

### Debug Output

The following error is displayed while refreshing state:
```
Error: failed to get user base schema: failed to get user type: json: cannot unmarshal array into Go value of type okta.UserType
```

### Panic Output

None.

### Expected Behavior

Terraform should be able to refresh state....

### Actual Behavior

Terraform fails to refresh state.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* We are running Terraform against Okta Preview (`...oktapreview.com`) tenant.
* I'm able to make this work again by pinning provider version to `= 3.6.1`.
* I suspect the issue originates from https://github.com/oktadeveloper/terraform-provider-okta/pull/183

**Comment by bogdanprodan-okta** [comment]
Hi @khitrenovich ! Thanks for submitting this issue! This error occurs if `user_type` is empty, so instead of returning not found error, Okta API returns a list of user types, which courses mentioned error.
I've managed to reproduce it with the following example.
```
resource "okta_user_base_schema" "firstName" {
  index       = "firstName"
  master      = "PROFILE_MASTER"
  permissions = "READ_ONLY"
  title       = "First name"
  type        = "string"
  user_type   = ""
}
```
Probably today I will fix this issue and release v3.7.1

**Comment by bogdanprodan-okta** [comment]
As it turns out, terraform sets `"user_type": ""` in the state file. You can fix this issue by setting `"user_type": "default"` manually.

**Comment by bogdanprodan-okta** [comment]
I've created PR that fixes this issue #242. Fix probably will be released today.

**Comment by khitrenovich** [comment]
@bogdanprodan-okta I'm somehow hesitant to patch our production state files manually. Hope to see v3.7.1 out soon!

**Comment by bogdanprodan-okta** [comment]
@khitrenovich new version v.3.7.1 has been released! Please try to refresh the state again to check if the issue still exists.

**Comment by khitrenovich** [comment]
@bogdanprodan-okta I'll know for sure in a couple of hours, but for now I've tested the fix in one of our lower environments and it looks fine. Thank you for the quick turnaround!

**Comment by khitrenovich** [comment]
I can confirm that the fix worked, we can close the issue. Thank you!
