### ISSUE TITLE
SCIM v2 app

### ISSUE THREAD

**Issue by karlsequeira** [okta/terraform-provider-okta#249]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Need to keep users and groups in sync with the on prem systems.  Will be using SCIM v2 app to help achieve this. 

http://www.simplecloud.info/

This is critical functionality to keep OKTA app profile and users in sync with the on prem systems.

Would be good to be able to use terraform to configure the  Provisioning and assignments  tabs to start with.
### New or Affected Resource(s)

-  "okta_app_scimv2"
### Potential Terraform Configuration

```hcl

```

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi @karlsequeira! Thanks for submitting this issue! After the holidays, there will be an internal discussion around which new resources should be added to v3.8.0, so I'll add another comment after.
