### ISSUE TITLE
Hide Sensitive Attributes

### ISSUE THREAD

**Issue by karlsequeira** [okta/terraform-provider-okta#253]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Making an Okta user profile attribute sensitive hides information stored in attribute fields.

https://help.okta.com/en/prod/Content/Topics/users-groups-profiles/usgp-hide-sensitive-attributes.htm
### New or Affected Resource(s)

- "okta_app_user_schema" 

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

sensitive  = true

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi @karlsequeira! Thanks for submitting this issue! You can use the 0.14 version of Terraform which [provides functionality](https://www.hashicorp.com/blog/terraform-0-14-adds-the-ability-to-redact-sensitive-values-in-console-output) to hide sensitive data.

**Comment by karlsequeira** [comment]
Hi, This request is not to hide the data on the output. This is to hide the data on the Okta console.

As per the Okta docs, 
In the Admin Console, go to Directory > Profile Editor.
Select Okta in the FILTERS list.
Click Profile for Okta User (default).
In the attribute list, click information  for the attribute you want to make sensitive.
Select the Sensitive data check box.
Click Save Attribute.
The sensitive attribute displays as asterisks in the user's profile.

Thanks

**Comment by noinarisak** [comment]
@bogdanprodan-okta and @karlsequeira. This feature request requires Early Access feature flag that is not self services and requires Okta support staff to activate. I was not able to find [docs](https://developer.okta.com/docs/reference/api/schemas/) around this attribute. I would labeled `no-api` and `wont fix` until both Self-Service activation is enabled and public documentation are publish. Those are my thoughts.

**Comment by karlsequeira** [comment]
@noinarisak is this still not available.
