### ISSUE TITLE
Add okta_app_oauth data resource

### ISSUE THREAD

**Issue by pedromctech** [okta/terraform-provider-okta#266]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like getting all attributes from any OIDC application. For example:

```
data "okta_app_oauth" "example" {
  label = "Example App"
}
```

And get from there these parameters:
- `type`
- `grant_types`
- `redirect_uris`
- `response_types`

### New or Affected Resource(s)

- okta_app_oauth

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi @pedrodotmc! Thanks for submitting this issue! After the holidays, there will be an internal discussion around which new resources should be added to v3.8.0, so I'll add another comment after.
