### ISSUE TITLE
Auth secret in inline hooks are showed in plan output

### ISSUE THREAD

**Issue by moein** [okta/terraform-provider-okta#268]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.13.5

### Affected Resource(s)

- okta_inline_hook

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    okta = {
      source = "oktadeveloper/okta"
      version = "~> 3.6"
    }
  }
}

# Configure the Okta Provider
provider "okta" {
  org_name  = var.okta_org_name
  base_url  = var.okta_base_url
  api_token = var.okta_api_token
}

resource "okta_inline_hook" "inline_hook" {
  name    = "test"
  version = "1.0.0"
  type    = "com.okta.user.pre-registration"

  channel = {
    version = "1.0.0"
    uri     = "https://test.com"
    method  = "POST"
    type    = "HTTP"
  }

  auth = {
    key   = "someheader"
    type  = "HEADER"
    value = "SHOULD NOT APPEAR"
  }
}
```

### Expected Behavior

Auth secret in inline hooks should not be shown in plan output.
```hcl
  + resource "okta_inline_hook" "inline_hook" {
      + auth    = {
          + "key"   = "someheader"
          + "type"  = "HEADER"
          + "value" = (sensitive value)
        }
      + channel = {
          + "method"  = "POST"
          + "type"    = "HTTP"
          + "uri"     = "https://test.com"
          + "version" = "1.0.0"
        }
      + id      = (known after apply)
      + name    = "test"
      + status  = "ACTIVE"
      + type    = "com.okta.user.pre-registration"
      + version = "1.0.0"
    }

```

### Actual Behavior

Auth secret appears in plain text when running plan
```hcl
  + resource "okta_inline_hook" "inline_hook" {
      + auth    = {
          + "key"   = "someheader"
          + "type"  = "HEADER"
          + "value" = "SHOULD NOT APPEAR"
        }
      + channel = {
          + "method"  = "POST"
          + "type"    = "HTTP"
          + "uri"     = "https://test.com"
          + "version" = "1.0.0"
        }
      + id      = (known after apply)
      + name    = "test"
      + status  = "ACTIVE"
      + type    = "com.okta.user.pre-registration"
      + version = "1.0.0"
    }

```

### Steps to Reproduce

1. `terraform plan`

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi @moein! Thanks for creating this issue! I've made some investigation and based on terraform documentation it's not possible to hide a single value from `auth`, so it can only look like this:
```
+ resource "okta_inline_hook" "inline_hook" {
      + auth    = (sensitive value)
      + channel = {
          + "method"  = "POST"
          + "type"    = "HTTP"
          + "uri"     = "https://test.com"
          + "version" = "1.0.0"
        }
      + id      = (known after apply)
      + name    = "test"
      + status  = "ACTIVE"
      + type    = "com.okta.user.pre-registration"
      + version = "1.0.0"
    }
```

Another option is to use the 0.14 version of Terraform which [provides functionality](https://www.hashicorp.com/blog/terraform-0-14-adds-the-ability-to-redact-sensitive-values-in-console-output)  to hide sensitive data.

**Comment by moein** [comment]
Hi Bogdan,

Thanks for the tip on 0.14! I will have a look.

About the current behaviour to be honest I think it's better to be safe than sorry. I doubt anyone would prefer to show the secret only because they want to see the header name in the plan :D

Cheers

**Comment by moein** [comment]
@bogdanprodan-okta I'm trying to update to tf 0.14 but I'm facing a very strange issue (this does not happen with 0.13.5)

```
Error: Computed attribute cannot be set

  on ../modules/applications/myapp/application.tf line 10, in resource "okta_app_oauth" "myapp":
  10: resource "okta_app_oauth" myapp {
```

Here is the resource
```hcl
resource "okta_app_oauth" myapp {
  label                     = "My app"
  type                      = "web"
  login_uri                 = "https://admin.${var.env_domain}/login"
  grant_types               = ["authorization_code"]
  post_logout_redirect_uris = ["https://somedomain.com/login/logout"]
  redirect_uris = concat(
    ["https://somedomain.com"],
    local.extra_redirect_urls
  )
  response_types = ["code"]
  consent_method = "TRUSTED"
  issuer_mode    = "CUSTOM_URL"
  omit_secret    = true
  lifecycle {
    ignore_changes = [users, groups]
  }
}
```

As you can see non of the fields I'm setting is a computed value :/

Do you have any idea this might be happening?

Cheers

**Comment by moein** [comment]
Sorry finally the issue was with lifecyle.
We had 2 users assigned in the state and for some reason by updating to 0.14 it was causing this error.

**Comment by noinarisak** [comment]
Looks like was resolved, closing the issue.
