### ISSUE TITLE
Provisioning  option on SWA App.

### ISSUE THREAD

**Issue by karlsequeira** [okta/terraform-provider-okta#272]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please make button_field - (Optional).

Leaving password_field and  username_field out throws the following error.

failed to create SWA application: The API returned an error: Api validation failed: usernameField. Causes: errorSummary: usernameField: The field cannot be left blank, errorSummary: passwordField: The field cannot be left blank

If I generate the app with the fields above, I do not get the Provisioning  checkbox for Enable SCIM provisioning on the general tab. I can configure the Provisioning  manually once the app is generated if that's not an option.

### New or Affected Resource(s)

- resource "okta_app_swa" "example" {
  label          = "example"
  button_field   = "btn-login"
  password_field = "txtbox-password"
  username_field = "txtbox-username"
  url            = "https://example.com/login.html"
}

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi @karlsequeira! Thanks for submitting this issue! I'll get back to you after the investigation of this error.

**Comment by bogdanprodan-okta** [comment]
Hi @karlsequeira! The problem is, that the `checkbox` field in the app settings is missing both from [official docs](https://developer.okta.com/docs/reference/api/apps/#add-plugin-swa-application) and Okta Golang SDK. However, it's clearly present on the UI and in the API response:
```go
"settings": {
        "app": {
            "loginUrlRegex": null,
            "usernameField": "txtbox-username",
            "redirectUrl": null,
            "buttonField": "btn-login",
            "checkbox": null,
            "passwordField": "txtbox-password",
            "url": "https://example.com/login.html"
        }
```
I'll try to figure out when will it be available via API.

**Comment by narbit-EDR** [comment]
@bogdanprodan-okta is there any update on this?
