### ISSUE TITLE
okta_app_saml description

### ISSUE THREAD

**Issue by karlsequeira** [okta/terraform-provider-okta#273]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

Adding description throws an error. 
```
resource "okta_app_saml" "example" {
  label                    = "example"
  description         = "Sample description"
  sso_url                  = "http://example.com"
  recipient                = "http://example.com"
  destination              = "http://example.com"
  audience                 = "http://example.com/audience"
  subject_name_id_template = "$${user.userName}"
  subject_name_id_format   = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
  response_signed          = true
  signature_algorithm      = "RSA_SHA256"
  digest_algorithm         = "SHA256"
  honor_force_authn        = false
  authn_context_class_ref  = "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"

  attribute_statements {
    type         = "GROUP"
    name         = "groups"
    filter_type  = "REGEX"
    filter_value = ".*"
  }
}
 ```
### Affected Resource(s)

- okta_app_saml

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Actual Behavior
An argument named "description" is not expected here.

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi @karlsequeira! Thanks for submitting this issue! I've investigated this error and turns out, that app-related resources don't have `description` field at all. However, app data resources have one, but they shouldn't. According to the official [documentation](https://developer.okta.com/docs/reference/api/apps/#application-properties), apps don't have this field, so it will be removed from Okta terraform provider.
