### ISSUE TITLE
Allow for fetching client_secret from imported okta_app_oauth

### ISSUE THREAD

**Issue by aguynamedjoetoo** [okta/terraform-provider-okta#274]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When importing an `okta_app_oauth` resource to be managed by terraform, you cannot fetch the `client_secret` to be used elsewhere in terraform. I suspect this is because the API itself returns a very similar result when doing a GET on the app.

### New or Affected Resource(s)

- okta_app_oauth

### Potential Terraform Configuration

N/A

### References
N/A

**Comment by bogdanprodan-okta** [comment]
Hi @Joeskyyy! Thanks for the issue! I'll do some investigation whether it's possible to customize import in the way to get this field and will get back to you with the news asap.

**Comment by bogdanprodan-okta** [comment]
Hi @Joeskyyy! Sorry for making you wait so long for the response. We had an internal discussion with @noinarisak and decided that we won't be able to implement this feature. The only way you can see the client secret is by importing the resource and then updating it with the new `client_secret`. @noinarisak, please correct me if I'm wrong.

**Comment by aguynamedjoetoo** [comment]
@bogdanprodan-okta I'm assuming this is just because the `client_secret` is not available in the API? Is there a reason we can't have this implemented functionally? As an operator, I can already retrieve the `client_secret` from the Okta UI, and being able to do so programatically would be a huge benefit for automation.

**Comment by bogdanprodan-okta** [comment]
Based on the [official documentation](https://developer.okta.com/docs/reference/api/apps/#oauth-credential-object):
```
If a `client_secret` isn't provided on creation, and the `token_endpoint_auth_method` requires one,
Okta generates a random `client_secret` for the client application. The `client_secret` is only shown when 
an OAuth 2.0 client app is created or updated (and only if the `token_endpoint_auth_method` is one 
that requires a client secret).
```
Because `import` is basically a `read` operation, `client_secret` is not returned via API, but only when you make `update` or `create` operations. 
@noinarisak ^^

**Comment by aguynamedjoetoo** [comment]
@bogdanprodan-okta Yeah I figured it was all purely a limitation in the API just given what is returned when hitting the REST endpoints. That being said, a ticket to Okta support was triaged to create a request here.

We've actually tried to import an app and then make a change to a field, thereby pushing an update to the app, and still no client_secret appears to be returned so I believe the API documentation is not entirely accurate.

All that being said, there appears to be some form of action to get client secrets, since as an operator in the UI I can retrieve them at anytime:

![image](https://user-images.githubusercontent.com/4296375/104757854-6c200e00-5712-11eb-8331-8cfc943e2b13.png)

Being able to do the same programmatically would essentially fix this issue for the provider I'd imagine. Even if we could introduce the feature but limit the scope of tokens that are allowed to do it would be fairly secure given app admins themselves can already do this in the UI, I don't see the difference in security implications.

**Comment by bogdanprodan-okta** [comment]
Hi @Joeskyyy! As for `pushing an update to the app, and still no client_secret appears to be returned`, that [will be fixed](https://github.com/oktadeveloper/terraform-provider-okta/blob/master/okta/resource_okta_app_oauth.go#L429) in the upcoming v3.8.0

**Comment by MattSurabian** [comment]
Of note a data request of `okta_app_oauth` is able to return the client secret, has the Okta API possibly changed so import could be modified now?
