### ISSUE TITLE
okta_user_roles

### ISSUE THREAD

**Issue by karlsequeira** [okta/terraform-provider-okta#276]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
We need to generate users that have specific access to generate tokens for the api's. Would like to have this in terraform. 

We need  lifecycle { } added to okta_user as the current roles assigned manually are lost when we rerun the terraform.

### New or Affected Resource(s)

- okta_user_roles
- okta_admin_role

### Potential Terraform Configuration

resource "okta_user_roles" "example" {
  user_id    = "user id"
  admin_roles = ["APP_ADMIN","GROUP_MEMBERSHIP_ADMIN"]
}

resource "okta_admin_role" "example_app" {
  user_id    = "user id"
  role_id    = "APP_ADMIN"
  app_id = ["0oa94xj233QGYfUU1d6","0oa94xj456QGYfUU1d6"]
}
resource "okta_admin_role" "example_group" {
  user_id    = "user id"
  role_id    = "GROUP_MEMBERSHIP_ADMIN"
  group_id = ["0oa94xj233QGYf111d6","0oa94xj456QGYf111d6"]
}
app_id  and group_id  would be optional and needed depending on the role id. 
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi @karlsequeira! Thanks for submitting this issue! We will have an internal meeting this week regarding new resources, so this might go in the next release if approved.

**Comment by tohcnam** [comment]
Are there some news around this?

**Comment by bogdanprodan-okta** [comment]
Hi @tux-manchot! Yes, I'm currently working to add this functionality to the next version.

**Comment by bogdanprodan-okta** [comment]
Hi, @tux-manchot! Just a quick update. I think creating `"okta_user_roles"` would be a little bit extra because you can get all the roles from `admin_roles` field in `okta_user` resource.

Example of usage:
```
resource "okta_user" "not_me" {            // <-- existing resource
  admin_roles = ["APP_ADMIN","GROUP_MEMBERSHIP_ADMIN"]
  email       = "john_doe@okta.com"
  first_name  = "John"
  last_name   = "Doe"
  login       = "john_doe@okta.com"
  status      = "ACTIVE"
}

resource "okta_admin_role" "example_group" { // <-- resource to be added in the new version
  user_id = okta_user.not_me.id
  role_id = okta_user.not_me.admin_roles[1]
  group_id = ["0oa94xj233QGYf111d6","0oa94xj456QGYf111d6"]
}

resource "okta_admin_role" "example_app" {
  user_id = okta_user.not_me.id
  role_id = okta_user.not_me.admin_roles[0]
  app_id = ["0oa94xj233QGYfUU1d6","0oa94xj456QGYfUU1d6"]
}
```

However, if there is a need in managing just the roles, not the entire user, I think I can add `"okta_user_roles"` as well.
