### ISSUE TITLE
Values for the "features" argument in okta_app_saml resources not being applied

### ISSUE THREAD

**Issue by stilljake** [okta/terraform-provider-okta#282]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

- 0.13.6

### Affected Resource(s)

- okta_app_saml

### Terraform Configuration Files

```hcl
resource "okta_app_saml" "gsuite" {
  preconfigured_app   = "google"
  label               = "G Suite - Terraform"
  groups = [
    # okta_group.app-gsuite-users.id
  ]
  features = [
    "PUSH_NEW_USERS",
    "PUSH_USER_DEACTIVATION",
    "GROUP_PUSH",
    "REACTIVATE_USERS",
    "IMPORT_USER_SCHEMA",
    "IMPORT_NEW_USERS",
    "PUSH_PROFILE_UPDATES"
  ]
}
```

### Expected Behavior

The features should be applied in Okta.

### Actual Behavior
Terraform shows that the resource was created correctly. In Okta, the app is also created, however the features described in the terraform file are not enabled
```hcl
okta_app_saml.gsuite: Creating...
okta_app_saml.gsuite: Creation complete after 5s [id=0oa3rxxw8I90HGrPX5d6]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

When running `terraform apply` a second time it shows that changes are required

```hcl
 ~ features                   = [
          + "GROUP_PUSH",
          + "IMPORT_NEW_USERS",
          + "IMPORT_USER_SCHEMA",
          + "PUSH_NEW_USERS",
          + "PUSH_PROFILE_UPDATES",
          + "PUSH_USER_DEACTIVATION",
          + "REACTIVATE_USERS",
        ]

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @stilljake! Thanks for submitting this issue! I'll investigate this but and try to add the fix in the upcoming release.

**Comment by bogdanprodan-okta** [comment]
Hi, @stilljake! Based on the [official docs](https://developer.okta.com/docs/reference/api/apps/#features):
```
Note: You can't currently configure provisioning features via the API. Use the administrator UI.
```
Thus this feature isn't working currently. I'll try to find out whether Okta is planning to enable changes via API, but right now this issue will remain.

**Comment by stilljake** [comment]
Thanks for the explanation. Would it make sense to remove this from the supported arguments? Since It is not a supported argument right now.

**Comment by bogdanprodan-okta** [comment]
I think that makes sense since only have encountered this bug, so it won't affect a lot of people. I can also suppress the diff for now as you can still import and get a list of features.
