### ISSUE TITLE
User Assignment to Service App Causes Panic

### ISSUE THREAD

**Issue by BrentSouza** [okta/terraform-provider-okta#292]
An admin assigned themselves to an OAuth application of type service in the user screen of the Okta admin site. After this happened, terraform plans started crashing on the `okta_app_oauth` resource. Removing the user assignment resolved the issue.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.14.2

### Affected Resource(s)

okta_app_oauth

### Debug Output

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xedcdc6]

goroutine 32 [running]:
github.com/oktadeveloper/terraform-provider-okta/okta.syncGroupsAndUsers(0x13c1fa0, 0xc00007b440, 0xc0002cdc40, 0x14, 0xc0005c4f00, 0x10797a0, 0xc0005c2510, 0x0, 0x0)
	github.com/oktadeveloper/terraform-provider-okta/okta/app.go:433 +0x406
github.com/oktadeveloper/terraform-provider-okta/okta.resourceAppOAuthRead(0x13c1fa0, 0xc00007b440, 0xc0005c4f00, 0x10797a0, 0xc0005c2510, 0xc000429f40, 0xc0004c38f0, 0x40e0f8)
	github.com/oktadeveloper/terraform-provider-okta/okta/resource_okta_app_oauth.go:378 +0xa26
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00014a900, 0x13c1f20, 0xc0005fc500, 0xc0005c4f00, 0x10797a0, 0xc0005c2510, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.0/helper/schema/resource.go:297 +0x1ea
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00014a900, 0x13c1f20, 0xc0005fc500, 0xc000162d90, 0x10797a0, 0xc0005c2510, 0xc00000ecc8, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.0/helper/schema/resource.go:564 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00018c140, 0x13c1f20, 0xc0005fc500, 0xc0005fc540, 0xc0005fc500, 0x1163e20, 0x11b3220)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.0/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc000245c20, 0x13c1f20, 0xc0005fc500, 0xc00007aea0, 0xc000245c20, 0xc0003ff080, 0xc000261ba0)
	github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/server/server.go:297 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x11b3220, 0xc000245c20, 0x13c1fe0, 0xc0003ff080, 0xc00007ae40, 0x0, 0x13c1fe0, 0xc0003ff080, 0xc000424000, 0x25a)
	github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b8c40, 0x13cd5c0, 0xc0000c5c80, 0xc0005b0600, 0xc000180ae0, 0x1a1fef0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc0001b8c40, 0x13cd5c0, 0xc0000c5c80, 0xc0005b0600, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd05
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000a8560, 0xc0001b8c40, 0x13cd5c0, 0xc0000c5c80, 0xc0005b0600)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
```

### Panic Output

Sorry, don't have the output from crash.log

### Expected Behavior

The plan succeeds

### Actual Behavior

The provider crashes :'(

### Steps to Reproduce

1. Write some tf for an oauth app of type service
2. Run `terraform plan/apply` to create the app in Okta
3. In the admin UI, assign a user to the app (this has to be done from the user screen)
4. Run `terraform plan` and it should crash

### Important Factoids

Seems like this is a potential problem: https://github.com/oktadeveloper/terraform-provider-okta/blob/c79db0a92f791a014b782c705a302a0fb4d555f5/okta/app.go#L434

The call to get the app user assignments returns a user with a `null` value for `credentials`:

```json
{
  "id": "12345",
  "externalId": null,
  "created": "2021-01-20T16:50:29.000Z",
  "lastUpdated": "2021-01-20T16:50:29.000Z",
  "scope": "USER",
  "status": "ACTIVE",
  "statusChanged": "2021-01-20T16:50:29.000Z",
  "passwordChanged": null,
  "syncState": "DISABLED",
  "credentials": null,
  ...
}
```

**Comment by BrentSouza** [comment]
But maybe the fix is just not to call `syncGroupsAndUsers` for service apps

**Comment by bogdanprodan-okta** [comment]
> But maybe the fix is just not to call `syncGroupsAndUsers` for service apps

Hi @BrentSouza! Thanks for creating this issue! We should still keep groups and user assignments, but I will add `nil` check for that part of the code.
