### ISSUE TITLE
 v3.7.4 okta_user_base_schema appears to be forcing master = "PROFILE_MASTER"

### ISSUE THREAD

**Issue by M1st-gunna** [okta/terraform-provider-okta#294]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.24

### Affected Resource

- okta_user_base_schema

### Details

I'm attempting to upgrade from Terraform v0.12.24 + provider.okta v3.6.1 to provider.okta v3.7.4. The okta_user_base_schema resource appears to be forcing master = "PROFILE_MASTER" the [documentation for the resource](https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/user_base_schema) notes that the argument is optional. The argument is not in our current tfstate file. I'm assuming that master is now a requirement and that "PROFILE_MASTER" is now default, based on the `terraform plan`, but there's nothing in documentation to confirm. Did a recent change switch this from optional to required?

### Expected Behavior

no registered change to master

### Actual Behavior

master = "PROFILE_MASTER" is being registering as an addition to the tfstate file

**Comment by bogdanprodan-okta** [comment]
Hi, @M1st-gunna! Thanks for submitting this issue! Yes, I'm afraid, `master` is "PROFILE_MASTER" by default, and even if you don't set it, Okta API will set it as the default one. I had to make it "PROFILE_MASTER" by default as well, otherwise `terraform plan` command will always be non-empty for `master = ""` or when it hasn't been set at all.

Request body for `POST /api/v1/meta/schemas/apps/0oawixa531RKhQ1w20h7/default`
```json
{
 "definitions": {
  "custom": {
   "id": "#custom",
   "properties": {
    "roles": {
     "items": {
      "enum": [
       "test",
       "1",
       "2"
      ],
      "oneOf": [
       {
        "const": "test",
        "title": "test"
       },
       {
        "const": "1",
        "title": "1"
       },
       {
        "const": "2",
        "title": "2"
       }
      ],
      "type": "string"
     },
     "permissions": [
      {
       "action": "READ_WRITE",
       "principal": "SELF"
      }
     ],
     "required": false,
     "scope": "NONE",
     "title": "roles",
     "type": "array",
     "union": "ENABLE"
    }
   },
   "type": "object"
  }
 }
}
```
Response body
```json
{
 "id": "https://terraform-provider-okta.oktapreview.com/meta/schemas/apps/0oawixa531RKhQ1w20h7/default",
 "$schema": "http://json-schema.org/draft-04/schema#",
 "name": "terraformproviderokta_testaccreplacewithuuid2_3",
 "title": "testAcc_replace_with_uuid2 User",
 "lastUpdated": "2021-01-21T16:47:41.000Z",
 "created": "2021-01-21T09:05:20.000Z",
 "definitions": {
  "custom": {
   "id": "#custom",
   "type": "object",
   "properties": {
    "roles": {
     "title": "roles",
     "type": "array",
     "scope": "NONE",
     "items": {
      "type": "string",
      "enum": [
       "test",
       "1",
       "2"
      ],
      "oneOf": [
       {
        "const": "test",
        "title": "test"
       },
       {
        "const": "1",
        "title": "1"
       },
       {
        "const": "2",
        "title": "2"
       }
      ]
     },
     "union": "ENABLE",
     "master": {
      "type": "PROFILE_MASTER"
     }
    }
   },
   "required": []
  },
  "base": {
   "id": "#base",
   "type": "object",
   "properties": {
    "userName": {
     "title": "Username",
     "type": "string",
     "required": true,
     "scope": "NONE",
     "maxLength": 100,
     "master": {
      "type": "PROFILE_MASTER"
     }
    }
   },
   "required": [
    "userName"
   ]
  }
 },
 "type": "object",
 "properties": {
  "profile": {
   "allOf": [
    {
     "$ref": "#/definitions/custom"
    },
    {
     "$ref": "#/definitions/base"
    }
   ]
  }
 }
}
```

In addition, [documentation](https://help.okta.com/en/prod/Content/Topics/users-groups-profiles/usgp-define-attribute-profile-master.htm]) also states that it is a default value
```
Inherit from profile source: Default. Select this option to make the profile source the attribute source.
```

**Comment by M1st-gunna** [comment]
@bogdanprodan-okta thanks for the quick reply and clarification! We'll try things out in Staging, based on  your info. If we run into any issues, we'll reach back out.
