### ISSUE TITLE
okta_app_saml nulling key_years_valid in v 3.7.4 when not explicitly set

### ISSUE THREAD

**Issue by M1st-gunna** [okta/terraform-provider-okta#295]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.24

### Affected Resource(s)

- okta_app_saml

### Issue

I'm trying to upgrade from okta provider v 3.6.1 to 3.7.4. When I run a `terraform plan` against our current resources, key_years_valid is registering a change from `= 1` to `= null`. This attribute isn't noted in the documentation, is not explicitly set in our terraform code, not indicated in the Okta UI from what I can see as a super admin, and is not currently in our tfstate file. We are unsure of the impact of the change. In attempting to set the `key_years_valid = 1` in our code so no change registers, we got the following error.

`Error: expected [{{} key_years_valid}] to be in range (2 - 10), got 1`

Not sure if this is a bug or documentation is just missing.

**Comment by bogdanprodan-okta** [comment]
Hi @M1st-gunna! Thanks for submitting this issue! There were two problems with that value in the previous versions: first, according to the [official documentation](https://developer.okta.com/docs/reference/api/apps/#request-parameters-20), the valid range is 2-10, so setting it to 1 would've caused an error. Secondly, this value is only used along with `key_name` to generate a new application key credential, thus if `key_name` is not set, this will be `null` and there will be no impact on the resource whatsoever. 
BTW, thanks for noting about invalid documentation, I will fix that in the upcoming release

```
- `key_years_valid` - Number of years the certificate is valid (2 - 10 years).

- `key_name` - Certificate name. This modulates the rotation of keys. New name == new key. Required to be set with `key_years_valid`.
```

**Comment by M1st-gunna** [comment]
@bogdanprodan-okta thanks for the quick reply and clarification! We'll try things out in our Staging environment, based on the info you provided. If we run into any issues, we'll reach back out.
