### ISSUE TITLE
"Long" email templates are not updated as expected

### ISSUE THREAD

**Issue by ghost** [okta/terraform-provider-okta#305]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/archive v1.3.0
+ provider registry.terraform.io/oktadeveloper/okta v3.7.4

### Affected Resource(s)

- okta_template_email

### Terraform Configuration Files

```hcl
resource "okta_template_email" "change_email_confirmation" {
  type = "email.emailChangeConfirmation"

  translations {
    language = "en"
    subject  = "Confirm email address change"
    template = file("${path.module}/templates/email-templates/other/changeEmailConfirmation.html")
  }
}
```

### Debug Output

https://gist.github.com/IrmantasM/8ba21a7c70ffe5410f19df1c38b59c7f

### Panic Output

N/A

### Expected Behavior

Provider should update an email template and during next plan show no changes to it.

### Actual Behavior

After making changes to email template and applying them, terraform reported that changes were applied, however they were not (changes not visible via UI and generating new plan shows that same changes will be applied again).

So far from testing it seems like there is a character limit on the html template, because debug output shows a cut off html in the response.

### Steps to Reproduce

1. Make a custom email template with over ~3400 characters
1. `terraform apply`

### Important Factoids

Issue is happening in Okta preview instance. Haven't tested in non-preview.

### References

N/A

**Comment by bogdanprodan-okta** [comment]
Hi @IrmantasM! Thanks for submitting this issue! There is another one #48 issue opened, so I'll try to investigate them both and hopefully fix the problem.

**Comment by bogdanprodan-okta** [comment]
Hi @IrmantasM! I think the root cause of this is in the `type` value. Because it acts like `id`, it's only being set during the creation, but completely neglected during read/update. Basically, if you change the type, `id` will still be the old value. 
I'll add `forceNew==true` to the `type`, so every time you change it, terraform will recreate the resource.
```
"type": {
		Type:        schema.TypeString,
		Required:    true,
		Description: "Email template type",
		ForceNew:    true,
	},
```
Other than that, I've tried to run `plan` after `apply`, and the result was always `No changes. Infrastructure is up-to-date.`

**Comment by ghost** [comment]
@bogdanprodan-okta  thanks a lot for a quick response! I will test it by adding force recreate and let you know the results soon!

**Comment by ghost** [comment]
@bogdanprodan-okta  hello, I have tested with lifecycle rule to create_before_destroy but it didn't help. I think I misunderstood your suggestion.

I am not changing the type, only HTML content (template).

How should I force a new resource?

**Comment by bogdanprodan-okta** [comment]
@IrmantasM! Could you try using these parameters? https://gist.github.com/bogdanprodan-okta/3c4938e1985d577dcda7eaae426be7e4

I've tested it several times and still cannot reproduce this issue.

**Comment by ghost** [comment]
@bogdanprodan-okta  sorry, but I don't understand how your parameters are different from mine, to me they look identical :(

```
I'll add forceNew==true to the type, so every time you change it, terraform will recreate the resource.
```

What does this mean, how did you add forceNew? Did you release a new version of the provider?

Edit 1: I can see that in your example you are using a different version of the provider. I'll try upgrading to 3.8.0.

**Comment by ghost** [comment]
Tried after upgrading to 3.8.0, same result:

```bash
% terraform -v
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/archive v1.3.0
+ provider registry.terraform.io/oktadeveloper/okta v3.8.0

%  terraform apply "tfplan-lab"
module.global-configuration.okta_template_email.forgot_password_denied: Modifying... [id=email.forgotPasswordDenied]
module.global-configuration.okta_template_email.email_change_confirmed_notification: Modifying... [id=email.emailChangeConfirmation]
module.global-configuration.okta_template_email.forgot_password_denied: Modifications complete after 2s [id=email.forgotPasswordDenied]
module.global-configuration.okta_template_email.email_change_confirmed_notification: Modifications complete after 2s [id=email.emailChangeConfirmation]

Apply complete! Resources: 0 added, 2 changed, 0 destroyed.

% terraform plan -out=tfplan-lab -input=false -var-file="environments/lab.tfvars"
....
Plan: 0 to add, 2 to change, 0 to destroy.
```

Are there any additional details I could provide you with to help resolve this issue?

**Comment by bogdanprodan-okta** [comment]
Hi @IrmantasM! It's still very strange why are you still receiving these errors. Could you try manually create these templates, import them into terraform, redact resources based on `terraform.tfstate` file and run `terraform plan` again. 

PS: I'm still not able to reproduce your scenario. Here is my terraform:
```
resource "okta_template_email" "change_email_confirmation" {
  type = "email.emailNewAlreadyChangedNotification"

  translations {
    language = "en"
    subject  = "Confirm email address change2"
    template = file("1.html")
  }
}

resource "okta_template_email" "forgot_password_denied" {
  type = "email.forgotPasswordDenied"

  translations {
    language = "en"
    subject  = "account password reset"
    template = file("2.html")
  }
}
```

And my templates [1.html](https://gist.github.com/bogdanprodan-okta/58e2ffb72e8dc4a225f7c74d3c6836db) and [2.html](https://gist.github.com/bogdanprodan-okta/976f0e24a4b0ec173df318d53904fe90)

I'll try to ask people in Okta who is responsible for that functionality, maybe they could help.
