### ISSUE TITLE
user_name_template not applying correctly to state

### ISSUE THREAD

**Issue by Nordle** [okta/terraform-provider-okta#308]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`Terraform v0.13.3`
`provider registry.terraform.io/oktadeveloper/okta v3.7.4`

### Affected Resource(s)

`okta_app*` resources with the field `user_name_template`. Tested with `okta_app_swa` and `okta_app_saml` with the same results.

### Expected Behavior

Applying a change results in the attribute being updated.

### Actual Behavior

After applying a change which includes the default field `user_name_template`, the change is not made and subsequent `terraform apply` commands show the change yet to be made.

### Steps to Reproduce

Create a resource with `okta_app_swa`, do not include the field `user_name_template`. Apply the change and TF will want to include this attribute by default. After applying, run `terraform apply` again and the change is asking to be made again.

**Comment by bogdanprodan-okta** [comment]
Hi @Nordle! Thanks for submitting this issue! I'll try to reproduce it and fix it.
