### ISSUE TITLE
Add Support for Group Push Configuration

### ISSUE THREAD

**Issue by lukiffer** [okta/terraform-provider-okta#312]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add `GROUP_PUSH` to the `features` array in any okta_app_* resource that supports provisioning. Add new resources for configuring group push.

### New or Affected Resource(s)

- okta_app_group_push_rule
- okta_app_group_push_assignment

### Potential Terraform Configuration

```hcl
resource "okta_app_group_push_rule" "example" {
  name = "Example Group Push Rule"
  app_id = okta_app_saml.example.id

  condition {
    expression_type = "urn:okta:expression:1.0"
    expression_value = "String.startsWith(group.name, \"Group\")"
  }

  condition {
    expression_type = "urn:okta:expression:1.0"
    expression_value = "String.startsWith(group.description, \"Something\")"
  }
}

resource "okta_app_group_push_assignment" "example" {
  app_id = okta_app_saml.example.id
  group_id = okta_group.example.id
}
```

**Comment by bogdanprodan-okta** [comment]
Hi @lukiffer! Thanks for submitting this issue! I'll do some investigation next week around this new resource and when it'll be possible to implement it.

**Comment by tgoodsell-tempus** [comment]
Is there an API available for this?

**Comment by bogdanprodan-okta** [comment]
> Is there an API available for this?

For the features - no. As stated in the [official docs](https://developer.okta.com/docs/reference/api/apps/#features):
```
Note: You can't currently configure provisioning features via the API. Use the administrator UI.
```

**Comment by lukiffer** [comment]
Understand that the lack of an API makes this impossible to implement from a Terraform perspective, but is there an forum or contact for making product requests such as the requisite API?

**Comment by noinarisak** [comment]
Hi @lukiffer, please submit your request to https://ideas.okta.com, to increase the visibility beyond this repo.

**Comment by ChefAustin** [comment]
In case anyone runs across this issue and also wants to see this implemented by Okta, please upvote this feature request in Okta Ideas portal => https://ideas.okta.com/app/#/case/167182

**Comment by brian-nomi** [comment]
Thank you for the link. Okta, this is totally unacceptable. We can't have a fully IaC provisioning solution since we have to log in to the console to push our groups.

**Comment by ChefAustin** [comment]
Official response on the [corresponding submission to Okta Ideas portal](https://ideas.okta.com/app/#/case/167182):
> Someone from the Product Management team at Okta has recently reviewed this Idea and has chosen to keep it under consideration for Product Review. This means that while it’s not on the roadmap yet, it’s still top of mind for us as we build out our future plans. We will follow up to make sure the Public API is available to include the functionality in the provider.
> Thank you so much for the feedback. We’ll be sure to update this item once per quarter. In the meantime, please continue to add any additional comments, clarifications, and general feedback.

Doesn't sound like we should hold our breath on this getting implemented anytime soon.

**Comment by majormoses** [comment]
I am reaching out to my account team to discuss this. The purpose of a push group is to automate the pushing of a group, why that would be desirable to manage this via an entirely manually process when we can automate the creation of the group, app, etc makes no sense to me.

**Comment by MrYeske-SA** [comment]
Yep... needed this when we first started discussing it with our Partner rep 2-3 years ago...

**Comment by ahublersos** [comment]
Highlighting this in case it wasn't obvious for anyone else: Once you [manually create the group push rule](https://help.okta.com/en-us/Content/Topics/users-groups-profiles/usgp-enable-group-push.htm) any existing groups that match the rule pattern as well as any matching groups created in the future will be pushed automatically.

**Comment by jgrumboe** [comment]
Although it's not supported to use an INTERNAL Okta API, I managed to create pushgroup rules and assignments with the [restapi](https://registry.terraform.io/providers/Mastercard/restapi) provider.

An example code looks like:
```hcl
terraform {
  required_providers {
    restapi = {
      source = "Mastercard/restapi"
      version = "1.18.2"
    }
  }
}

provider "restapi" {
  uri = "https://${var.okta_tenant_name}-admin.okta.com"
  # Configuration options
  headers = {
    "Authorization" = "SSWS ${var.okta_api_token}",
    "Content-Type"  = "application/json"
  }
  write_returns_object = true
}

resource "restapi_object" "push_group_rule" {
  path         = "/api/internal/instance/${var.okta_application_id}/grouppushrules"
  id_attribute = "mappingRuleId"
  data = jsonencode({
    name                            = "name-of-the-rule",
    searchExpression                = "group-starts-with-term",
    searchExpressionType            = "STARTS_WITH",
    descriptionSearchExpression     = "description-starts-with-term",
    descriptionSearchExpressionType = "STARTS_WITH",
    status                          = "ACTIVE",
    sourceAppInstanceId             = null
  })
  destroy_data = jsonencode({
    action = "DELETE_MAPPINGS_AND_DELETE_APP_GROUPS"
  })
}

resource "restapi_object" "push_group" {
  path           = "/api/internal/instance/${var.okta_application_id}/grouppush"
  destroy_method = "POST"
  destroy_path   = "/api/internal/instance/${var.okta_application_id}/grouppush/{id}/delete"
  id_attribute   = "mappingId"
  data = jsonencode({
    status      = "ACTIVE",
    userGroupId = var.okta_user_group_id
  })
  destroy_data = jsonencode({
    deleteAppGroup = true
  })
}
```

**Comment by jgrumboe** [comment]
There seems to be some movement: https://github.com/okta/terraform-provider-okta/issues/1409#issuecomment-2683393001
A public API for push groups seems to be on the roadmap for Q3 2025
