### ISSUE TITLE
`scope` attribute of okta_app_user_schema does not update

### ISSUE THREAD

**Issue by eatplaysleep** [okta/terraform-provider-okta#317]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform 0.14.5
Okta-provider 3.7.4

### Affected Resource(s)

- okta_app_user_schema

### Steps to Reproduce

1. Attempt to update an existing schema property to change the `scope` value. 
2. If `scope` in Okta == `SELF`, attempt to update it to `NONE`

#### Expected Outcome
* CLI output should show that `scope` updated.
* `scope` should be updated.

#### Actual Outcome
* CLI output shows that scope was updated successfully.
* Refresh comes back with the original scope and sets the state with value from Okta

### Important Factoids

In reviewing the Okta API specs, the `scope` value is _read only_. 

![image](https://user-images.githubusercontent.com/37595884/106422891-3d917b00-6414-11eb-8ef6-61a8ab0ce24d.png)

Either this needs to be changed in the Okta API, or it likely needs to result in destroying the attribute in order to change the `scope`.

Attributes created in Okta itself are set with scope == `SELF` by default but the TF provider defaults to `NONE`.

**Comment by bogdanprodan-okta** [comment]
Hi @eatplaysleep! Thanks for submitting this issue! I'll investigate the problem and fix it ASAP.
