### ISSUE TITLE
SAML subject_match_attribute for CUSTOM_ATTRIBUTE fails

### ISSUE THREAD

**Issue by karlsequeira** [okta/terraform-provider-okta#319]
Create a customname on the OKTA user profile. When I try to use that in the subject match, it fails with the following error

Error: failed to update SAML identity provider: The API returned an error: Api validation failed: IdpTrust. Causes: errorSummary: The policy.subject.matchAttribute is invalid.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform version 13

Okta Terraform Provider 3.8.0

### Affected Resource(s)

- okta_idp_saml

### Terraform Configuration Files

```

resource "okta_idp_saml" "inbound" {
  name                     = var.label
  acs_binding              = "HTTP-POST"
  acs_type                 = "INSTANCE"
  sso_url                  = var.sso_url
  sso_destination          = var.destination
  sso_binding              = "HTTP-POST"
  username_template        = "idpuser.subjectNameId"
  kid                      = "${okta_idp_saml_key.inbound.id}"
  issuer                   = var.sso_url
  request_signature_scope  = "REQUEST"
  response_signature_scope = "ANY"

  subject_match_type       = "CUSTOM_ATTRIBUTE"
  subject_match_attribute  = "customname"
  request_signature_algorithm = "SHA-256"
  response_signature_algorithm = "SHA-256"
  max_clock_skew           = 60
  groups_action            = "ASSIGN"
  groups_assignment        = [okta_group.inbound.id] 
}
```

### Debug Output

Error: failed to update SAML identity provider: The API returned an error: Api validation failed: IdpTrust. Causes: errorSummary: The policy.subject.matchAttribute is invalid.

### Expected Behavior

The new match attribute should be visible on the console.

### Actual Behavior

Fails to update the idp saml 

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @karlsequeira! Thanks for submitting this issue! There is a [reference in the API docs](https://developer.okta.com/docs/reference/api/idps/#subject-policy-object) about `subject_match_attribute` field. 
```
The` matchAttribute` (corresponds to the `subject_match_attribute` field in the provider) must be a valid Okta User profile attribute of one of the following types:

String (with no format or 'email' format only)
Integer
Number
```
Could you please double-check that `customname` is present in the Okta User profile? However, if you create that field via terraform as well, you need to be sure that it's been created before the `okta_idp_saml` resource (you can use dependsOn, or set value to `subject_match_attribute` referencing from the attribute itself)

**Comment by karlsequeira** [comment]
I did create this in the Okta profile. I also tried it using the rest api and that worked.

**Comment by bogdanprodan-okta** [comment]
Thanks for the reply! I'll try to reproduce it and get back to you ASAP.

**Comment by karlsequeira** [comment]
I tried by creating everything with terraform but that still fails. 
resource "okta_user_schema" "inbound" {
  index       = "myattribute"
  title       = "myattribute"
  type        = "string" 
  description = "myattribute used for SSO"
  master      = "OKTA"
}

resource "okta_group" "inbound" {
  name        = "My SSO Group"
  description = var.label
}

resource "okta_idp_saml" "inbound" {
  name                     = var.label
  acs_binding              = "HTTP-POST"
  acs_type                 = "INSTANCE"
  sso_url                  = var.sso_url
  sso_destination          = var.destination
  sso_binding              = "HTTP-POST"
  username_template        = "idpuser.subjectNameId"
  kid                      = "${okta_idp_saml_key.inbound.id}"
  issuer                   = var.sso_url
  request_signature_scope  = "REQUEST"
  response_signature_scope = "ANY"
  #subject_match_type       = "USERNAME"
  subject_match_type       = "CUSTOM_ATTRIBUTE"
  subject_match_attribute  = "myattribute"
  request_signature_algorithm = "SHA-256"
  response_signature_algorithm = "SHA-256"
  max_clock_skew           = 60
  groups_action            = "ASSIGN"
  groups_assignment        = [okta_group.inbound.id] 
  depends_on = [okta_user_schema.inbound,]
}
Thanks a lot for your help on this.

**Comment by bogdanprodan-okta** [comment]
It's definitely a bug. This is a`subject` that UI is sending to the backend:
```
"subject":{
         "userNameTemplate":{
            "template":"idpuser.subjectNameId"
         },
         "filter":"",
         "matchType":"CUSTOM_ATTRIBUTE",
         "matchAttribute":"myattribute"
}
```
vs terraform:
```
"subject": {
   "matchType": "CUSTOM_ATTRIBUTE",
   "userNameTemplate": {
    "template": "idpuser.subjectNameId"
   }
  }
```
It doesn't send `matchAttribute` at all. I'll fix that and create a corresponding PR. 
Thanks again for submitting this issue!
