### ISSUE TITLE
Plan shows profile mappings will be destroyed even when 'delete_when_absent = false'

### ISSUE THREAD

**Issue by CodyDunlap** [okta/terraform-provider-okta#324]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v0.14.4

### Affected Resource(s)

- okta_profile_mapping

### Terraform Configuration Files

```hcl

resource "okta_idp_oidc" "external_idp" {
  name = "External IdP"
  issuer_url = "<redacted>"
  authorization_url = "<redacted"
  authorization_binding = "HTTP-REDIRECT"
  token_url = "<redacted>"
  token_binding = "HTTP-POST"
  jwks_url = "<redacted>"
  jwks_binding = "HTTP-REDIRECT"
  user_info_url = "<redacted>"
  user_info_binding = "HTTP-REDIRECT"
  client_id = "<redacted>"
  client_secret = "<redacted>"
  status = "ACTIVE"
  scopes = [
    "openid",
    "profile",
    "email",
  ]
  groups_action = "ASSIGN"
  groups_assignment = [
    okta_group.end_users.id
  ]
  subject_match_type = "USERNAME_OR_EMAIL"
}

resource "okta_user_type" "end_user" {
  name = "endUser"
  display_name = "End User"
  description = "End User"
}

resource "okta_profile_mapping" "arbiter_end_user" {
  source_id = okta_idp_oidc.external_idp.id
  target_id = okta_user_type.end_user.id
  delete_when_absent = false

  mappings {
    expression = "appuser.gender"
    id = okta_user_schema.end_user_gender.index
  }

  mappings {
    expression = "appuser.birthdate"
    id = okta_user_schema.end_user_birthdate.index
  }

  mappings {
    expression = "appuser.picture"
    id = okta_user_schema.end_user_picture_url.index
  }
}
```

### Expected Behavior

The default mappings that are absent from my config should be appropriately ignored by `terraform plan` when using `delete_when_absent = false`

### Actual Behavior

The mappings I provide are added but the `terraform plan` command result shows that the default profile mappings are going to be destroyed. When running `terraform apply` they aren't destroyed though.

Because they aren't being deleted (expected behavior) these resources show up as if they will be destroyed on every subsequent `terraform plan`

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

None

### References

None

**Comment by bogdanprodan-okta** [comment]
Hi @CodyDunlap! Thanks for submitting this issue! I'll investigate the problem ASAP and create a PR to fix it.
