### ISSUE TITLE
Creating SWA app using predefined app Sentry is defaulting to SAML sign on mode

### ISSUE THREAD

**Issue by Nordle** [okta/terraform-provider-okta#327]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.13.3
+ provider registry.terraform.io/oktadeveloper/okta v3.8.0

### Affected Resource(s)

- okta_app_swa

### Expected Behavior

An swa app is created for preconfigured app Sentry

### Actual Behavior

A SAML app is created for preconfigured app Sentry

### Steps to Reproduce

Create `okta_app_swa` resource, with `sentry` as the `preconfigured_app`:

```
resource "okta_app_swa" "okta_app" {
  label             = "Sentry"
  preconfigured_app = "sentry"
  hide_ios          = false
  hide_web          = false
}
```
After applying, the sign on method is not swa, but SAML

![Screenshot from 2021-02-12 11-41-55](https://user-images.githubusercontent.com/35959480/107758564-5a3c8580-6d27-11eb-83c7-4e0dabe3f59d.png)

**Comment by bogdanprodan-okta** [comment]
Hi @Nordle! Thanks for submitting this issue! I'll investigate the problem ASAP and create a PR to fix it.

**Comment by Nordle** [comment]
👏🏻

**Comment by bogdanprodan-okta** [comment]
Hi @Nordle! Just FYI, you can achieve the same result if you use `okta_app_auto_login` resource:
```
resource "okta_app_auto_login" "okta_app" {
  label             = "Sentry"
  preconfigured_app = "sentry"
  hide_ios          = false
  hide_web          = false
}
```
