### ISSUE TITLE
okta_idp_social as data source

### ISSUE THREAD

**Issue by hendstephen** [okta/terraform-provider-okta#334]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Request to add okta_idp_social as a data source. Right now it is only available as a resource, and I cannot reference social IDP's as data sources through the `okta_idp_oidc` data source.

### New or Affected Resource(s)

- okta_idp_social

### Potential Terraform Configuration

```hcl
data "okta_idp_social" "google" {
  name = "Google"
}
```

**Comment by bogdanprodan-okta** [comment]
Hi @hendstephen! Thanks for submitting this issue! I'll try to add the `okta_idp_oidc` as a data source into our next release, which will be available by the end of this month.

**Comment by hendstephen** [comment]
@bogdanprodan-okta Just want to confirm, do you mean `okta_idp_social`? The `okta_idp_oidc` resource already exists as a data source, but I can't import social providers using it.

**Comment by bogdanprodan-okta** [comment]
> @bogdanprodan-okta Just want to confirm, do you mean `okta_idp_social`? The `okta_idp_oidc` resource already exists as a data source, but I can't import social providers using it.

yes, that's what I meant :)

**Comment by hendstephen** [comment]
@bogdanprodan-okta Awesome, thanks for the quick reply! I'll keep an eye out for it.
