### ISSUE TITLE
Validation error when using login_mode (okta_app_oauth) due to validation done in CustomizeDiff

### ISSUE THREAD

**Issue by fatbasstard** [okta/terraform-provider-okta#339]
The validation of the `login_uri` is done in the `CustomizeDiff` which breaks when a computed value is used.

Computed value (from a module):

```
locals {
  application_fqdn = var.subdomain != null ? "${var.subdomain.name}.${data.aws_route53_zone.current[0].name}") : null
}  
 ```

Output:

```
output "fqdn" {
  value       = local.application_fqdn
  description = "FQDN of the route53 endpoint"
}
``` 

Usage:

```
resource "okta_app_oauth" "default" {
  login_mode   = "SPEC"
  login_uri    = "https://${module.xxx.fqdn}/"
```

Results in the following error:

```
Error: you have to set up 'login_uri' to configure any 'login_mode' besides 'DISABLED'
  on xxx.tf line xxx, in resource "okta_app_oauth" "default":
```

Computed values are not supported in `CustomizeDiff`: https://www.terraform.io/docs/extend/resources/customizing-differences.html

This has also been reverted/removed in this repository before ("Stop doing validation in CustomizeDiff"): https://github.com/oktadeveloper/terraform-provider-okta/commit/ab36a554d824d9004a2a3ff4035ab18921b4a414

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform:`Terraform v0.14.7`
Provider: `oktadeveloper/okta v3.9.0`

### Affected Resource(s)

- `okta_app_oauth`

### Terraform Configuration Files

See above

### Expected Behavior

No validation error

### Actual Behavior

Validation error

**Comment by bogdanprodan-okta** [comment]
Hi, @fatbasstard! Thanks for submitting this issue! I'll move this validation out of `CustomizeDiff` function, so the error won't appear. Fix will be available in the next release (probably tomorrow or on Monday).

**Comment by fatbasstard** [comment]
Superfast response. Thanks!
