### ISSUE TITLE
Group role unable to target application

### ISSUE THREAD

**Issue by pmaterer** [okta/terraform-provider-okta#345]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`v0.13.5`

### Affected Resource(s)

- `okta_group_role`

### Terraform Configuration Files

```hcl
resource "okta_group_role" "main" {
  group_id  = "var.main_group"
  role_type = "APP_ADMIN"
}
```

### Expected Behavior

I am unable to target a specific app when giving a group the "APP_ADMIN" role type. The `target_group_list` is there for specifying groups, but there should be a similar argument for apps. 

I'd image it would look something like

```hcl
resource "okta_group_role" "main" {
  group_id = var.group_id
  role_type = "APP_ADMIN"

  # this is the new optional field, only supported when the role type is 'APP_ADMIN'
  target_app_list = [
    okta_app_saml.google.id
  ]
```

**Comment by bogdanprodan-okta** [comment]
Hi, @pmaterer! Thanks for submitting this issue! Sounds like a good idea to add this field. I'll create the corresponding PR and include this field in the next release.
