### ISSUE TITLE
Error: at least "user_whitelist" or "group_whitelist" should be provided when using 'implicit' in "grant_type_whitelist"

### ISSUE THREAD

**Issue by chrusty** [okta/terraform-provider-okta#347]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.12.26

### Affected Resource(s)

- okta_auth_server_policy_rule

### Terraform Configuration Files

```hcl
resource "okta_auth_server_policy_rule" "tsem" {
  auth_server_id       = okta_auth_server.tsem.id
  policy_id            = okta_auth_server_policy.tsem.id
  status               = "ACTIVE"
  name                 = var.app_name
  priority             = 1
  grant_type_whitelist = ["client_credentials", "implicit", "authorization_code"]
  group_whitelist      = [okta_group.app_tsem.id]
  scope_whitelist      = ["*"]
}
```

### Expected Behavior

I'd hope this would provision a server policy rule

### Actual Behavior

`Error: at least "user_whitelist" or "group_whitelist" should be provided when using 'implicit' in "grant_type_whitelist"`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I can get past this:
- temporarily remove "implicit" from the grant_type_whitelist
- terraform apply
- add "implicit" back to the grant_type_whitelist
- terraform apply

This works, but is obviously annoying, and is hard to automate.

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi @chrusty! Thanks for submitting this issue! The problem is in the resource validation. I'll create a corresponding PR to fix this issue.
