### ISSUE TITLE
Okta factor for TOTP

### ISSUE THREAD

**Issue by venkatakanupuru** [okta/terraform-provider-okta#350]
Hi Team,

Can you please suggest how I can automate/ implement TOTP using terraform ?(UI steps are listed below)
Are there any terraform resources ?

okta factors supported are : 
"duo", "fido_u2f", "fido_webauthn", "google_otp", "okta_call", "okta_otp", "okta_push", "okta_question", "okta_sms", "rsa_token", "symantec_vip" or "yubikey_token".

1. From the admin console, navigate to Security > Multifactor. The Multifactor settings page is displayed.
2. Click TOTP to view settings for the custom TOTP factor.
3. To add a new custom TOTP factor, click Add TOTP Factor. The Add TOTP Factor window is displayed.
4.Fill out the following fields:
Name
TOTP Length (6,8,10)
HMAC Algorithm (HmacSHA1, HmacSHA256, HmacSHA512)
Time step (15, 30, 60 seconds)
Clock drift interval (3, 5, 10 seconds)
Shared secret encoding (Hexadecimal, Base 32, Base64)
Click Add TOTP Factor to save your settings. Once the TOTP factor is created, the factor profile ID will appear on the Multifactor page.

5. Click Copy to copy the Factor Profile ID to your clipboard. The factor profile ID is used to enroll a user in the TOTP factor using the factors API.
6. Navigate to Factor Enrollment settings and add the Custom TOTP factor to your org's factor enrollment policy so that it appears to end users once they sign in to their org.
7. Use the factor profile ID to enroll a user in the TOTP factor by referring to the API documentation Enroll Custom HOTP Factor.
The API call should contain the following attributes and hardware token shared secret:

Profile ID
Factor Type
Provider
Note: You must enroll a user with a factor profile ID that matches that of the user's assigned hardware token. If the correct profile ID is not used, an error will occur when the user attempts to authenticate.

8. Verify that authentication is successful for a single user before enrolling all other users.
Note: A misconfigured profile requires re-enrollment of all users to a new custom TOTP profile.

Please Help. Thanks in advance.
Venkata

**Comment by bogdanprodan-okta** [comment]
Hi, @venkatakanupuru! Thanks for submitting this issue! I put some info together and get back to you ASAP.

**Comment by bogdanprodan-okta** [comment]
Hi, @venkatakanupuru! Sorry for the long response! As it turns out, terraform provider doesn't have a user factor resource. Thus to make the flow you've provided feasible, a new resource should be created. I think I'll have to investigate the official docs and make a corresponding PR.

**Comment by bogdanprodan-okta** [comment]
Hi, @venkatakanupuru! I'm currently working on this issue and will add the corresponding resource to the provider. It will be released in `3.12.0` version next month. Cheers!
