### ISSUE TITLE
No way to change the App server default claim sub ( can do through the web console)

### ISSUE THREAD

**Issue by mcrobbj** [okta/terraform-provider-okta#359]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v0.14.5 okta provider v3.10.1

### Affected Resource(s)

- okta_auth_server
- okta_auth_server_claim

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
resource "okta_auth_server" "mysAuthServer" {
  audiences   = [var.audiences]
  description = format("%s-%s", var.my_prefix, "Auth Server")
  name        = format("%s-%s", var.my_prefix, "Auth Server")
  issuer_mode = "ORG_URL"
  status      = "ACTIVE"
}
resource "okta_auth_server_claim" "sub" {
  auth_server_id = okta_auth_server.myAuthServer.id
  name           = "sub"
  value          = "(appuser != null) ? appuser.customerId : app.clientId"
  claim_type     = "RESOURCE"
}

### Expected Behavior

I should be able to modify the standard claim when creating the auth server or amend it later

### Actual Behavior

Ther are no options to modify on creation of the auth server and you can modify only create NEW claims
Error: failed to create auth server claim: The API returned an error: Api validation failed: name. Causes: errorSummary: name: ''name'' must be unique within an authorization server.

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @mcrobbj! Thanks for submitting this issue! I'll check what can be done when the claim already exists and get back to you asap.

**Comment by bogdanprodan-okta** [comment]
Hi, @mcrobbj! I've created a [separate resource](https://github.com/okta/terraform-provider-okta/pull/392) for default claims, so it will be easier to manage them.

**Comment by dgallub** [comment]
Hey @bogdanprodan-okta - thank you for making this change! Do you know when the next release is going to be?

**Comment by bogdanprodan-okta** [comment]
Hi, @dgallub! 
The next release will probably this week. The only problem is that provider has migrated from `oktadeveloper` to `okta` and I don't know if I will be able to release it with the current `gpg` key.
There is always a possibility to use [in-house provider ](https://www.terraform.io/docs/cloud/run/install-software.html#in-house-providers) built from source. Basically, you run `go install`, copy the binary into your `terraform.d` dir and run `terraform init`.
