### ISSUE TITLE
okta_policy_mfa  okta_email retrieves from okta_sms

### ISSUE THREAD

**Issue by mikemuth** [okta/terraform-provider-okta#361]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.13.4 Okta Provider version 3.10.1

### Affected Resource(s)

okta_policy_mfa - specifically okta_email argument 

### Expected Behavior / Actual Behavior 

We are trying to set okta_email enroll to REQUIRED. When we ran terraform apply it updated the Okta tenant to REQUIRED, but when we ran terraform plan afterwards to confirm the change it pulled back the value that was set in the tenant for okta_sms instead of the value that was set in the tenant for okta_email.

      ~ okta_email      = {
            "consent_type" = "NONE"
          ~ "enroll"       = "NOT_ALLOWED" -> "REQUIRED"

**Comment by bogdanprodan-okta** [comment]
Hi, @mikemuth! Thanks for submitting this issue! I'll investigate the problem and will get back to you asap.
