### ISSUE TITLE
Okta provider crashes after replacing okta certificate

### ISSUE THREAD

**Issue by gilShin** [okta/terraform-provider-okta#364]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

12.20

### Affected Resource(s)

- okta_3.10.1

### Terraform Configuration Files

I haven't changed the code since the certificate had been replaced

### Debug Output

https://gist.github.com/gilShin/f8eaa0ac226fb4cc42c580bd3cba4da1

### Panic Output

The panic error is in the above gist

### Expected Behavior

terraform should complete successfully

### Actual Behavior

It crashes

**Comment by bogdanprodan-okta** [comment]
Hi, @gilShin! Thanks for submitting this issue! I've created PR that should fix the problem. It will be present in the next release
