### ISSUE TITLE
okta_oauth_app with Okta-mastered groups claim filter

### ISSUE THREAD

**Issue by dkulchinsky** [okta/terraform-provider-okta#365]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello folks, this is mostly a follow-up on https://github.com/okta/terraform-provider-okta/issues/65 which seem to have been closed without any further updates.

We're setting up a new Okta domain using the provider and we need to include our Okta-mastered groups in the groups claim, but it seems there's no way to enable this using the provider.

We tried adding the claim to the default Authorization Server and also followed the example here: https://github.com/okta/terraform-provider-okta/blob/master/examples/okta_app_oauth/group_for_groups_claim.tf which doesn't seem to work.

Perhaps we're missing some configuration bit or there's a known workaround, configuring the filter manually in the application works as expected, so for now we're provisioning everything through Terraform and then manually configure the filter.

### New or Affected Resource(s)

- okta_oauth_app

### Potential Terraform Configuration

Hard to say, as I'm not sure if this is technically possible.

### References

- https://github.com/okta/terraform-provider-okta/issues/65

**Comment by bogdanprodan-okta** [comment]
Hi, @dkulchinsky! Thanks for submitting this issue! I'll try to investigate the problem and get back to you asap.

**Comment by dkulchinsky** [comment]
Thanks @bogdanprodan-okta!

As a temporary workaround, I've used a `null_resource` with a `local-exec` provisioner to curl the internal API endpoint (was able to figure out from watching the network events in the browser when applying the same configuration from the UI), below are snippets of the code in case anyone stumbles on the same issue.

This workaround is sub-optimal of course, but does the job right now, we could of-course adjust these Applications manually after they were created with Terraform, but for compliance purposes everything has to be done with code so that's not an option in our case.

```hcl
resource "null_resource" "oidc_app_groups_claim" {
  triggers = {
    app_groups_claim_regex = base64encode(var.app_groups_claim_regex)
  }

  provisioner "local-exec" {
    command = "${path.module}/scripts/oidc_app_groups_claim.sh"
    environment = {
      OKTA_API_TOKEN = var.okta_api_token
      OKTA_APP_ID    = okta_app_oauth.oidc_app.id
      OKTA_DOMAIN    = var.okta_domain
      REGEX          = var.app_groups_claim_regex
    }
  }
}
```

and the script itself:
```sh
#!/bin/bash

die() {
  echo "error: $*" 1>&2
  exit 1
}

echo "Updating OIDC Groups Claim for Application ID: $OKTA_APP_ID"

STATUS_CODE=$(curl -X POST --silent -o /dev/null -w "%{http_code}" \
"https://${OKTA_DOMAIN}/api/v1/internal/apps/${OKTA_APP_ID}/settings/oauth/idToken?issuerHint=true" \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
-H "Authorization: SSWS ${OKTA_API_TOKEN}" \
-d "{ \
\"valueType\": \"GROUPS\", \
\"groupFilterType\": \"REGEX\", \
\"instanceId\": \"${OKTA_APP_ID}\", \
\"issuer\": \"https://${OKTA_DOMAIN}\", \
\"orgUrl\": \"https://${OKTA_DOMAIN}\", \
\"customUrl\": null, \
\"audience\": \"${OKTA_APP_ID}\", \
\"issuerMode\": \"ORG_URL\", \
\"name\": \"groups\", \
\"value\": \"${REGEX}\" \
}")

case "$STATUS_CODE" in
  200) echo "configuration applied"; exit 0 ;;
    *) die "failed updating configuration, status code $STATUS_CODE"
esac
```

**Comment by dkulchinsky** [comment]
still quite relevant 😄

**Comment by gstotts** [comment]
Don't suppose there is any indication of a time frame around when this might be worked on?

**Comment by dkulchinsky** [comment]
> Don't suppose there is any indication of a time frame around when this might be worked on?

Might be way off here, but I believe the gap here is that this specific configuration is not possible through Okta's public API, hopefully folks here can help push for them to close this gap 🙏🏼 

and for what it's worth, we've been using the above "hack" for few months now and it works fairly well.

**Comment by bogdanprodan-okta** [comment]
Hi, @gstotts! As @dkulchinsky stated there is currently no public API endpoint for this. I'll ask about whether it's possible to temporarily add custom call to `internal` API (works fine with `SSWS` auth).
