### ISSUE TITLE
Terraform resource "okta_app_saml" single_logout_issuer 

### ISSUE THREAD

**Issue by venkatakanupuru** [okta/terraform-provider-okta#367]
Hi Team,

For the terraform resource "okta_app_saml" the attribute single_logout_issuer needs to be changed to string instead of validating it is url. Can you please verify and fix this. (ValidateDiagFunc: stringIsURL)

"single_logout_issuer": {
				Type:             schema.TypeString,
				Optional:         true,
				Description:      "The issuer of the Service Provider that generates the Single Logout request",
				ValidateDiagFunc: stringIsURL(validURLSchemes...),
				RequiredWith:     []string{"single_logout_url", "single_logout_certificate"},
			},

Thank you 
Venkata

**Comment by bogdanprodan-okta** [comment]
Hi, @venkatakanupuru! Thanks for submitting this issue. It will be fixed in the next release.
