### ISSUE TITLE
`okta_app_saml` output metadata url for dynamic configuration

### ISSUE THREAD

**Issue by z0rc** [okta/terraform-provider-okta#369]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently `okta_app_saml`'s `metadata_url` is accessible only when logged into Okta. I'm looking for getting metadata url as seen in admin page, url behind `Identity Provider metadata` specifically. This url has different format `https://<org_name>.okta.com/app/<entity_key>/sso/saml/metadata` and accessible without authentication.

<img width="752" alt="Screen Shot 2021-03-05 at 18 53 03" src="https://user-images.githubusercontent.com/787519/110148272-4dbac280-7de5-11eb-8574-b8e9cdaac54d.png">

### New or Affected Resource(s)

- okta_app_saml

### Context

Public url is needed by Redash, https://redash.io/help/user-guide/users/authentication-options#How-to-Configure-Okta. I tired `metadata_url` returned by the resource, and that didn't work on the app side.

Probably this url can be constructed from other attributes, but it would be nice to have it available natively.

**Comment by bogdanprodan-okta** [comment]
Hi, @z0rc! Thanks for submitting this issue! There is field `entity_key` (computed value) in `okta_app_saml` resource. You can try to use it to build a metadata URL.

**Comment by z0rc** [comment]
Thanks, that should work.

Seems this metadata url isn't provided by okta api, so I'm a bit uncertain whether this info should be returned via terraform provider. Feel free to close this request, as my case is resolved.

**Comment by bogdanprodan-okta** [comment]
Always glad to help!
