### ISSUE TITLE
Terraform resource "okta_app_oauth" login_uri

### ISSUE THREAD

**Issue by venkatakanupuru** [okta/terraform-provider-okta#370]
Hi Team,

For the terraform resource "okta_app_oauth" the attribute login_uri is expecting to have a url, needs to be changed to string instead of validating it to url. Can you please verify and fix this. 

Error: invalid URL: expected login_uri to have a url with schema of: "http,https",

Thank you
Venkata

**Comment by bogdanprodan-okta** [comment]
Hi, @venkatakanupuru! Thanks for submitting this issue! Based on the [official docs](https://developer.okta.com/docs/reference/api/apps/#settings-10), `login_uri` is 
```
URL string that a third party can use to initiate a sign in by the client
```

**Comment by mikemuth** [comment]
we also use this as a string not a full URL

**Comment by bogdanprodan-okta** [comment]
Yes, I understand that, but when providing an invalid URL for `login_uri`, Okta API will error out:
```
The API returned an error: Api validation failed: initiate_login_uri. Causes: errorSummary: initiate_login_uri: ''initiate_login_uri'' must be an absolute URI.
```

**Comment by venkatakanupuru** [comment]
Hi @bogdanprodan-okta how to handle this situation for a mobile URL with no http or https

I am receiving an Error: invalid URL: expected login_uri to have a url with schema of: "http,https",

**Comment by noinarisak** [comment]
@venkatakanupuru  Here is a snippet of my iOS application configuration. Hope that helps resolve your question.

```hcl
...
resource "okta_app_oauth" "ios" {
  label                      = "iOS (Generated by UDP)"
  type                       = "native"
  grant_types                = ["authorization_code", "refresh_token", "implicit", "password"]
  redirect_uris              = ["com.okta.browser-sign-in:/callback"]
  login_uri                  = "com.okta.browser-sign-in:/callback"
  response_types             = ["code", "id_token", "token"]
  omit_secret                = true
  post_logout_redirect_uris  = ["com.okta.browser-sign-in:/callback"]
  token_endpoint_auth_method = "none"
  groups                     = ["${data.okta_group.all.id}"]
}
...
```

**Comment by venkatakanupuru** [comment]
Hi @noinarisak thank you for the response, I have similar configuration but I am not able to add the login_uri. 
Actually the app is configured manually and now I am importing the app to terraform script, importing is done
$ terraform import okta_app_oauth.myapp <app id>

Because of this login_uri, I am getting the error.

Error: invalid URL: expected login_uri to have a url with schema of: "http,https", got  xxxxx://callback
If there is http or https it is not throwing any error.

And If  login_uri = xxxxx:///callback.  or login_uri = xxxxx:/callback
then Error: invalid URL: expected 'login_uri' to have a host

Thank you
