### ISSUE TITLE
Ability to inactivate the default auth server

### ISSUE THREAD

**Issue by chrusty** [okta/terraform-provider-okta#373]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Thank you for the Okta Terraform provider! It has enabled me to define a complex configuration as-code with 100% repeatability. So far I've been able to do everything I needed - except for being able to inactivate the default auth server.

This is really just about being able to control an unused access route.

### New or Affected Resource(s)

The default auth server in an Okta account.

- okta_auth_server_default?

### Potential Terraform Configuration

```hcl
resource "okta_auth_server_default" "default" {
  status = "INACTIVE"
}
```

**Comment by bogdanprodan-okta** [comment]
Hi, @chrusty! Thanks for submitting this issue! I'll do some investigation on whether it's possible to disable the default auth server. If it is, I'll create a new resource and add it to the upcoming release. Cheers!

**Comment by chrusty** [comment]
Hello @bogdanprodan-okta, wow that is a quick response!

I suspect that it would take 2 API calls:

- GET /api/v1/authorizationServers?q=default to discover its ID
- PUT /api/v1/authorizationServers/id_of_default_auth_server with the new config

I'm just not sure about how a partial update would work with that PUT call.
