### ISSUE TITLE
okta_app_group_assignment priority attribute is constantly changing and causing diffs

### ISSUE THREAD

**Issue by dkulchinsky** [okta/terraform-provider-okta#377]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
❯ terraform -v
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/oktadeveloper/okta v3.10.1
```

### Affected Resource(s)

- okta_app_group_assignment

### Terraform Configuration Files

```hcl
resource "okta_app_group_assignment" "group_assignment" {
  for_each = toset(var.groups)

  app_id   = var.app_id
  group_id = data.okta_group.group[each.value].id

  profile  = jsonencode({})

  // priority changes over time as groups are added/removed from the app
  lifecycle {
    ignore_changes = [priority]
  }
}
```

### Debug Output

The information in the log is considered sensitive and I cannot provide it as-is, but happy to extract specifics if you want me to, though the issue should be easily reproducible.

### Panic Output

N/A

### Expected Behavior

`Priority` is a computed value, and if not set explicitly is updated on Okta side after the group assignment is created, the provider should retrieve the value and updated it in the state as-is

### Actual Behavior

when assigning groups to an app the `priority` attribute for all assigned groups changes in Okta causing constant diffs.

e.g.:
```
  # okta_app_group_assignment.foo["bar"] will be updated in-place
  ~ resource "okta_app_group_assignment" "foo" {
        id                = "<id>"
      - priority          = 1 -> null
        # (4 unchanged attributes hidden)
    }
```

we also tried to workaround this issue with:
```hcl
  lifecycle {
    ignore_changes = [priority]
  }
```
but didn't help.

### Steps to Reproduce

1. create an OIDC app
2. create an Okta-mastered grouup
3. use `okta_app_group_assignment` to assigned said group to said app
4. terraform apply
5. subsequent applies should have the priority changes
6. adding more groups to the app also causes diffs to the existing `okta_app_group_assignment` as the priorities reshuffle

**Comment by bogdanprodan-okta** [comment]
Hi, @dkulchinsky! Thanks for submitting this issue! I'll investigate the root cause and create a corresponding PR.

**Comment by roulettedares** [comment]
i'm getting constant priority changes from
```tf
data "okta_groups" "looker" {
  q = local.okta_group_assignment_prefix
}

resource "okta_app_group_assignments" "looker" {
  app_id = okta_app_saml.looker.id

  dynamic "group" {
    for_each = [for group in data.okta_groups.looker.groups : group.id]
    content {
      id = group.value
    }
  }
}
```

**Comment by bogdanprodan-okta** [comment]
> i'm getting constant priority changes from
> 
> ```terraform
> data "okta_groups" "looker" {
>   q = local.okta_group_assignment_prefix
> }
> 
> resource "okta_app_group_assignments" "looker" {
>   app_id = okta_app_saml.looker.id
> 
>   dynamic "group" {
>     for_each = [for group in data.okta_groups.looker.groups : group.id]
>     content {
>       id = group.value
>     }
>   }
> }
> ```

Hi @joshuasimon-taulia! Could you please create this as a separate issue since the error is in the `okta_app_group_assignments` resource. Thanks!
