### ISSUE TITLE
okta_app_oauth Add Support for Login Initated by and Login flow to resource

### ISSUE THREAD

**Issue by shanepikeCN** [okta/terraform-provider-okta#379]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There are some login features available when creating an application in the UI that do not currently exist when creating applications using the Terraform provider. The only option is to manually change these settings after the application has been created. It would be good if the following options from the UI could be added:

#### Login initiated by 
- App only
- Either Okta or App
#### Login flow 
- Redirect to app to initiate login (OIDC Compliant)
- Send ID Token directly to app (Okta Simplified)

### New or Affected Resource(s)

- okta_app_oauth

### Potential Terraform Configuration

```hcl
resource "okta_app_oauth" "application" {

  label         = "My Application"
  type          = "web"
  grant_types   = ["authorization_code", "client_credentials"]
  redirect_uris = ["http://test-domain/oauth2/callback"]
  login_uri     = "http://test-domain/oauth2/callback"

  login_initiated_by = ["okta", "app"]
  login_flow_type    = "redirect"

  lifecycle {
    ignore_changes = [groups]
  }
}
```

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @shanepikeCN! Thanks for submitting this issue! Currently, Okta API doesn't contain these fields, so we can not include them in the provider. I'll make an internal request to check if there plans of adding them.

**Comment by jkgeyti** [comment]
> Hi, @shanepikeCN! Thanks for submitting this issue! Currently, Okta API doesn't contain these fields, so we can not include them in the provider. I'll make an internal request to check if there plans of adding them.

Hi @bogdanprodan-okta . Did you get a response to the internal request?

**Comment by bogdanprodan-okta** [comment]
Hi, @jkgeyti! Currently, I don't have any news regarding these fields. I'll ping the other team again. Thanks for the reminder!

**Comment by bogdanprodan-okta** [comment]
Hi, @jkgeyti! I believe this functionality is available via `login_mode` and `login_scopes`
1)

```hcl
login_mode = "DISABLED"
```

<img width="611" alt="Screenshot 2021-08-28 at 17 11 10" src="https://user-images.githubusercontent.com/71279414/131220706-4221b6fe-91e6-47c4-9aa0-a61e368ad830.png">

2) 
```hcl
login_mode = "SPEC"
```
<img width="611" alt="Screenshot 2021-08-28 at 17 08 17" src="https://user-images.githubusercontent.com/71279414/131220614-620fd31c-e43a-4f79-9fef-e81d5dfc3f6d.png">

3) 

```hcl
login_mode = "OKTA"
login_scopes = ["profile"]
```

<img width="603" alt="Screenshot 2021-08-28 at 17 10 04" src="https://user-images.githubusercontent.com/71279414/131220671-4496f6f0-34a9-45de-b51e-664981a6629c.png">



Just in case, here is my test example
```hcl
resource "okta_app_oauth" "test" {
  label          = "LoginInitiatedBy"
  type           = "browser"
  grant_types    = ["authorization_code", "implicit"]
  redirect_uris  = ["http://d.com/"]
  response_types = ["token", "id_token", "code"]
  admin_note     = "admin note"
  enduser_note   = "enduser note"
  login_mode     = "DISABLED"
  login_scopes   = ["profile"]
  login_uri      = "https://example.com"
}
```

I'm closing this issue, but if you have any concerns, please leave a comment here. Cheers!
