### ISSUE TITLE
okta_group_role inconsistent apply

### ISSUE THREAD

**Issue by tgoodsell-tempus** [okta/terraform-provider-okta#383]
An inconsistent apply was detected for the resource `okta_group_role` which occurred during a period of heavy API load.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.14.5

### Affected Resource(s)

- okta_group_role

### Terraform Configuration Files

Output of a `for_each`:

```hcl
resource "okta_group_role" "admin_roles" {

  group_id  = okta_group.admin_group.id
  role_type = "ORG_ADMIN"

}


resource "okta_group_role" "admin_roles" {

  group_id  = okta_group.admin_group.id
  role_type = "READ_ONLY_ADMIN"

}
```

### Debug Output

N/A

### Panic Output

```
Error: Provider produced inconsistent result after apply


When applying changes to

module.prod_org_admin.okta_group_role.admin_roles["READ_ONLY_ADMIN"], provider

"registry.terraform.io/oktadeveloper/okta" produced an unexpected new value:

Root resource was present, but now absent.


This is a bug in the provider, which should be reported in the provider's own

issue tracker.



Error: Provider produced inconsistent result after apply


When applying changes to

module.prod_org_admin.okta_group_role.admin_roles["ORG_ADMIN"], provider

"registry.terraform.io/oktadeveloper/okta" produced an unexpected new value:

Root resource was present, but now absent.


This is a bug in the provider, which should be reported in the provider's own

issue tracker.
```

### Expected Behavior

Consistent applies

### Actual Behavior

Inconsistent apply detected

### Steps to Reproduce

1. `terraform apply` during a period of heavy api load

### Important Factoids

Occurred during a period of heavy API load, was only a subset of all of the `okta_admin_roles` applied.

### References

- #0000

**Comment by tgoodsell-tempus** [comment]
Follow up applies reveal this error:

```
Error: failed to assign role ORG_ADMIN to group 00g7hrt74btElee2g297: The API returned an error: The role specified is already assigned to the user.


Error: failed to assign role READ_ONLY_ADMIN to group 00g7hrt74btElee2g297: The API returned an error: The role specified is already assigned to the user.
```

**Comment by bogdanprodan-okta** [comment]
Hi, @tgoodsell-tempus! Thanks for submitting this issue! I'll investigate the root cause and get back to you asap.

**Comment by tgoodsell-tempus** [comment]
Cheers! My plan was to modify the line here https://github.com/okta/terraform-provider-okta/blob/65c8da66202e2b0dc69720a582f18c3a64d8e1dc/okta/resource_okta_group_role.go#L121

and change it to `return nil` since it seems like it's an API lag issue.

**Comment by bogdanprodan-okta** [comment]
> Cheers! My plan was to modify the line here
> 
> https://github.com/okta/terraform-provider-okta/blob/65c8da66202e2b0dc69720a582f18c3a64d8e1dc/okta/resource_okta_group_role.go#L121
> 
> and change it to `return nil` since it seems like it's an API lag issue.

If there is a lag, I'll add a retry logic similar to this:
https://github.com/okta/terraform-provider-okta/blob/65c8da66202e2b0dc69720a582f18c3a64d8e1dc/okta/resource_okta_group_membership.go#L54
