### ISSUE TITLE
Orphaned users when group_rule is deleted

### ISSUE THREAD

**Issue by edulop91** [okta/terraform-provider-okta#384]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Any

### Affected Resource(s)

- [okta_group_rule](https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/group_rule)

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "okta_group_rule" "example" {
  name              = "example"
  status            = "ACTIVE"
  group_assignments = ["<group id>"]
  expression_type   = "urn:okta:expression:1.0"
  expression_value  = "String.startsWith(user.firstName,\"andy\")"
}
```

### Expected Behavior
Users should be unassigned from Okta groups when the rule that assigned them is deleted.

### Actual Behavior
Users are orphaned and continue being assigned to a group (showing up as Manually managed) even after the rule is deleted.

### Steps to Reproduce
- Create an empty group FOO (no users)
- Create a rule BAR that assigned some users to group FOO.
- Verify group FOO indeed has some users managed by the rule
- Delete rule BAR (comment out the terraform resource)
- Verify group FOO sill has the users assigned, but now managed "Manually"

### References
Okta Support mentioned there is a query param you can configure to delete the users that were managed by said rule:
`/api/v1/groups/rules/${ruleId}?removeUsers=true`

**Comment by bogdanprodan-okta** [comment]
Hi, @edulop91! Thanks for submitting this issue! I think a good solution here will be to add an extra property like `retain_assigned_users` (`true` by default) or something so I don't change the current behavior of the resource. I'll create a corresponding PR and tag this issue.

**Comment by edulop91** [comment]
Thank you so much!
