### ISSUE TITLE
There is no way to make general settings

### ISSUE THREAD

**Issue by mcrobbj** [okta/terraform-provider-okta#393]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is way to change the General Security settings:
- Security Notification emails
- Organisatuon *Activation emails are valid for etc

### New or Affected Resource(s)

- okta_security_general

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @mcrobbj! Thanks for submitting this issue! I'll investigate the possibility to change the General Security settings via API and get back to you asap.

**Comment by mcrobbj** [comment]
Still no update

**Comment by bogdanprodan-okta** [comment]
Hi, @mcrobbj! Currently, there are no public endpoints for org settings, thus I can not include them in Terraform provider.

**Comment by ahmei0** [comment]
waiting on this

**Comment by trzpiot** [comment]
Hi @bogdanprodan-okta,

Unfortunately, the "General - Organization" configurations still cannot be set via Terraform (the PR https://github.com/okta/terraform-provider-okta/pull/728 does not change this, unfortunately):

- "Remember Me" checkbox on sign in
- Activation emails are valid for
- Enforce device binding for creating sessions

btw: Thanks for ur awesome work!

**Comment by nissimnago** [comment]
any updates?
