### ISSUE TITLE
okta_app_group_assignments: leverage assignment bulk endpoints to avoid rate limiting

### ISSUE THREAD

**Issue by edulop91** [okta/terraform-provider-okta#396]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Okta rate limiting is a fairly pervasive problem when trying to manage Okta through Terraform. I have been maintaining a fork of this provider to work around these limitations. One of these is trying to work around [okta_app_group_assignment](https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/app_group_assignment). The way this resource works you end up consuming a shared rate limit pull for each (app,group) pair. Hitting the rate limit is most problematic when performing the Read operation.  

To work around this, I created an `app_group_assignments` resource that would consume rate limit (when reading) for each app instead of each (app, group) . This lets us get away with more efficient use of the available rate limit (in particular when performing Read part of the lifecycle). 

I'd be happy to contribute this code if appropriate.

### New or Affected Resource(s)

- okta_app_group_assignments

### Potential Terraform Configuration

```hcl
resource "okta_app_group_assignments" "example" {
  app_id   = "<app id>"
  retain_assignment = <true|false>
  
  group {
    id = "<group id>"
    profile = "JSON profile"
  }
  
  group {
     id = "<another group id>"
     profile = "JSON profile"
  }
}
```

**Comment by bogdanprodan-okta** [comment]
Hi, @edulop91! Thanks for submitting this issue! It seems like a very useful resource to decrease the number of API calls. If you want to contribute, feel free to create a PR!

**Comment by dsalaza4** [comment]
@bogdanprodan-okta Are there any plans to release this anytime soon? I am already hitting the api rate limits :crying_cat_face:

**Comment by bogdanprodan-okta** [comment]
Hi, @dsalaza4! It all depends on Hashicorp. Please read the [note](https://github.com/okta/terraform-provider-okta#important-note).
