### ISSUE TITLE
Add Refresh Token Rotation support for OIDC Apps

### ISSUE THREAD

**Issue by paulverrone** [okta/terraform-provider-okta#398]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

Okta has a new feature flag "Refresh Token Rotation".  Add support for setting enabling this on an application.

### New or Affected Resource(s)

okta_app_oauth

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @paulverrone! Thanks for submitting this issue! Currently, Okta Golang SDK doesn't have this field, so first, we need to add it to the App model. Only after that, I'll create a PR to support the "Refresh Token Rotation" property.

**Comment by dangoslen** [comment]
@bogdanprodan-okta 

Glad this is being worked on! Do you know when the SDK will support this feature? We are attempting to use it in our Okta environments but we manage our OAuth applications using terrafrom. This means that any applications using the Refresh Token grant that is allowed when this new feature is enabled get blown away every time we run our terrafrom.

I'm happy to help make contributions if that would be beneficial

**Comment by juangelos-sdc** [comment]
Hi there! Its there any advance of plan for this issue? It would be very useful to have it available.

There is any  possibility to not invalidate adding refresh_token grant type on "browser" types, and accept defaults  refresh_token ("rotation_type": "ROTATE", "leeway": "60"). (I mean just follow Okata web app behaviour on creating browser app)

Thanks!

**Comment by bogdanprodan-okta** [comment]
`refresh_token_rotation` and `refresh_token_leeway` are available in the latest version of the provider, closing this issue
