### ISSUE TITLE
Additional Outputs for okta_group

### ISSUE THREAD

**Issue by ambrosy-eric** [okta/terraform-provider-okta#406]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The resource `okta_group` should output the name and Id of the group so that you can reference that group via `okta_group.group.name` & `.id` instead of feeding in the name string again or having to do a separate data lookup to find the group id.

### New or Affected Resource(s)

- okta_group

### Potential Terraform Configuration

```
+ resource "okta_group" "group" {
      + id     = (known after apply)
      + name   = "okta-group"
}
```

### References

- The Add Group return in the [groups docs](https://developer.okta.com/docs/reference/api/groups/#response-example) show this data being returned

**Comment by bogdanprodan-okta** [comment]
Hi, @ambrosy-eric! Thanks for submitting this issue! You can always do that without creating an extra data source to get group name and ID. Here is a simple example:
```
resource "okta_group" "test1" {
  name        = "testAcc_1"
  description = "testing, testing 1"
}

resource "okta_policy_signon" "test" {
  name            = "testAccUpdated_replace_with_uuid"
  status          = "ACTIVE"
  description     = "Terraform Acceptance Test SignOn Policy"
  groups_included = [okta_group.test1.id]
}

output "test" {
  value = okta_group.test1.name
}
```
Basically, if you are referencing fields from a resource that is not yet created, terraform will first create these resources and only after that the ones that have references.

**Comment by ambrosy-eric** [comment]
Thanks @bogdanprodan-okta do you want me to close this, or leave for a PR to update the [docs](https://github.com/okta/terraform-provider-okta/blob/master/website/docs/r/group.html.markdown#attributes-reference) as there are few other resources (users, app_oauth, etc.) where outputs exist but are not documented.

**Comment by bogdanprodan-okta** [comment]
I think I'm gonna close this one as I was planning to review all the docs this month anyway.
