### ISSUE TITLE
okta_app_*: users and groups field deprecation/removal

### ISSUE THREAD

**Issue by edulop91** [okta/terraform-provider-okta#407]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Looking at the documentation for the [okta_app_*](https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/app_oauth) resources I see that `users` and `groups` fields are deprecated and instead it is recommended to use the `okta_app_user` or `okta_app_group_assignment`. As stated https://github.com/okta/terraform-provider-okta/issues/396, I've been maintaining a fork to deal with Rate limiting issues by more efficiently using the okta bulk endpoints (particularly during Read ops). Part of the changes I introduce in the fork is to remove the `groups` and `users` fields from the appBaseSchema so that `okta_app_*` resources do not consume extra API requests -- in particular since I'm handling assignments through the corresponding assignment resources anyways. 

I was wondering, and I know this is a fairly big breaking change, if it is worth starting a "formal" deprecation + removal of the `users` and `groups` fields of the `okta_app_*` resources. This would help:

- stay under the rate limits 
- avoid having to add to every app a  
```
 lifecycle {
     ignore_changes = [users,groups]
  } 
```

- consolidate the user/groups assignment code paths for easier maintainability, etc

### New or Affected Resource(s)

- okta_app_*

**Comment by bogdanprodan-okta** [comment]
Hi, @edulop91! Thanks for submitting this issue! You are right, `users` and `groups` probably will be removed in the 4.x.x version of the provider, since it's more efficient to manage them outside from app_* related resourced. I will be reviewing and removing/deprecating some of the resources for the cases where you can manage the same thing from multiple places.

**Comment by edulop91** [comment]
Perfect, thank you so much! Do you know if there's a rough timeline for a 4.X release?

**Comment by bogdanprodan-okta** [comment]
No, not really. We totally depend on the new `gpg` key that Hashicorp should provide and I have no updates on this matter.
