### ISSUE TITLE
Unnecessary force new on Okta User Resource

### ISSUE THREAD

**Issue by tgoodsell-tempus** [okta/terraform-provider-okta#409]
The Okta API should allow for the update operation on the `login` field, without requiring a full replacement of the user. This should allow us to remove the linked line and remove a unnecessary destructive operation.

https://github.com/okta/terraform-provider-okta/blob/4eefddd6b5a77479a1c45447eb2b0e8ac1496a45/okta/resource_okta_user.go#L165

I will do some testing and confirm this behavior holds true.

**Comment by bogdanprodan-okta** [comment]
Hi, @tgoodsell-tempus! Thanks for submitting this issue! Seems like you are right about this, so I'll try to create a PR next week to fix this.

**Comment by ymylei** [comment]
I've created #435 for this
