### ISSUE TITLE
Support for domain APIs

### ISSUE THREAD

**Issue by weald** [okta/terraform-provider-okta#410]
We are standing up a new SaaS product using Okta as our IdP. We are standing up the infrastructure sing Terraform and Terraform Cloud.  We'd like support for the [domain APIs](https://developer.okta.com/docs/reference/api/domains/) in the Okta Terraform provider.

As a DevOps engineer I would like to configure a custom domain in Okta via Terraform so that no manual configuration is needed, which is always error prone.

**Comment by bogdanprodan-okta** [comment]
Hi, @weald! Thanks for submitting this issue! Despite `Domain APIs` are still in early access, I can try to create a new resource to support them. I'll create a PR and link this issue to keep you updated.
