### ISSUE TITLE
List of email template types

### ISSUE THREAD

**Issue by weald** [okta/terraform-provider-okta#411]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Need to know the list of email template types.  Can't find them anywhere.

### New or Affected Resource(s)

- okta_template_email

### Potential Terraform Configuration

```hcl

resource "okta_template_email" "change_email_confirmation" {
  type = "email.emailChangeConfirmation"
  # What at the list of email template types?
```

### References

- https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/template_email
- This seems to have something, but does not appear to match: https://support.okta.com/help/s/article/Okta-Admin-Email-List?language=en_US
- Seems that the provider code is referencing v2 Golang SDK github.com/okta/okta-sdk-golang/v2/okta that does not appear to be public.

**Comment by weald** [comment]
I managed to find the list by performing a GET on {{url}}/api/v1/templates/emails
Here here is the list:
"type": "email.welcome",
        "type": "email.forgotPassword",
        "type": "email.emailLinkRecoveryResetFactor",
        "type": "email.emailLinkRecoveryResetPwdFactor",
        "type": "email.emailLinkRecoveryAdResetFactor",
        "type": "email.emailLinkRecoveryAdResetPwdFactor",
        "type": "email.emailLinkRecoveryLdapResetPwdFactor",
        "type": "email.forgotPasswordDenied",
        "type": "email.tempPassword",
        "type": "email.ad.welcome",
        "type": "email.ad.forgotPassword",
        "type": "email.ad.forgotPasswordReset",
        "type": "email.sunone.welcome",
        "type": "email.sunone.forgotPassword",
        "type": "email.sunone.forgotPasswordDenied",
        "type": "email.selfServiceUnlock",
        "type": "email.emailLinkRecoveryUnlockFactor",
        "type": "email.emailLinkRecoveryAdUnlockFactor",
        "type": "email.emailLinkRecoveryUnlockPwdFactor",
        "type": "email.emailLinkRecoveryAdUnlockPwdFactor",
        "type": "email.emailLinkRecoveryLdapUnlockPwdFactor",
        "type": "email.ad.selfServiceUnlock",
        "type": "email.pushVerifyActivation",
        "type": "email.accountLockout",
        "type": "email.emailTransactionVerification",
        "type": "email.emailLinkAuthenticationTransaction",
        "type": "email.emailActivation",
        "type": "email.signInFromNewDevice",
        "type": "email.registrationActivation",
        "type": "email.emailChangeConfirmation",
        "type": "email.emailNewChangeNotification",
        "type": "email.emailNewAlreadyChangedNotification",
        "type": "email.registrationEmailVerification",
        "type": "email.emailLinkFactorVerification",
        "type": "email.selfServiceUnlockOnUnlockedAccount",
        "type": "email.endUserScheduledLifecycleStatusChange",
        "type": "email.adminUsersListScheduledLifecycleStatusChange",
        "type": "email.factorEnrollment",
        "type": "email.factorReset",
        "type": "email.authenticatorEnrollment",
        "type": "email.authenticatorReset",
        "type": "email.automation",
        "type": "email.passwordChanged",

**Comment by bogdanprodan-okta** [comment]
Hi, @weald! Thanks for submitting this issue and for the list of template types! I will add this list to the email type validation, so can be printed.
