### ISSUE TITLE
Extend okta_group for group filtering

### ISSUE THREAD

**Issue by mfergus1** [okta/terraform-provider-okta#412]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

data.okta_group currently supports only a single lookup by name query. This is similar to all of the okta calls managed through the workflows, which can be frustratingly limited. In our organization, we have many automated okta_groups based on our HRIS. We would like to extend / wrap / propagate the members of those groups to various ones should they not fit our naming convention. Enable a filter by name or other field to return a list of okta groups from data. 
### New or Affected Resource(s)

data: 
- okta_group

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by fatbasstard** [comment]
Hi @mfergus1,

I think the feature you're looking for is released with the latest version (`3.11`):

- https://github.com/okta/terraform-provider-okta/blob/master/CHANGELOG.md#3110-march-26-2021
- https://github.com/okta/terraform-provider-okta/pull/103

**Comment by travisty-** [comment]
@bogdanprodan-okta It looks like the latest version of the provider published to the Terraform registry is `3.10.1`. Any chance we could get version `3.11.0` published in the near future? The new `okta_groups` resource would be helpful in managing our Terraform configuration. Thanks!

**Comment by bogdanprodan-okta** [comment]
Hi, @travisty-! Please read this [important note](https://github.com/okta/terraform-provider-okta#important-note). As for the ETA, that depends totally on Hashicorp.

**Comment by travisty-** [comment]
@bogdanprodan-okta I must have missed the README update, thanks for the clarification!

**Comment by mfergus1** [comment]
hi @fatbasstard  thanks for that info - will the docs be updated with that release shortly? i scraped through the docs but i'm a little unclear on a few things and getting the checksum for the provider

**Comment by bogdanprodan-okta** [comment]
@mfergus1 `3.12.0` will be released next month and will include the `okta_groups` data resource.

**Comment by bogdanprodan-okta** [comment]
Hi @mfergus1! May I close this one or this is still an issue for you?
