### ISSUE TITLE
Provider version 3.11.0 is missing in Terraform Registry

### ISSUE THREAD

**Issue by dkulchinsky** [okta/terraform-provider-okta#414]
Hey @bogdanprodan-okta 👋🏼 

It looks like the latest version of the provider (v3.11.0) is missing from the Terraform Registry and it still shows v3.10.1 as latest.

https://registry.terraform.io/providers/oktadeveloper/okta/latest

Thanks!

**Comment by bogdanprodan-okta** [comment]
Hi, @dkulchinsky! Thanks for submitting this issue! Please refer to [this comment ](https://github.com/okta/terraform-provider-okta/issues/405#issuecomment-810056944) that describes the nature of the problem.

**Comment by dkulchinsky** [comment]
ohhh... thanks for pointing me to that comment!

Perhaps add a note of this in the README to avoid folks stumbling on the same issue? and maybe have an open issue to track it until this is resolved?

Was really looking forward to try 3.11 😄

**Comment by tgoodsell-tempus** [comment]
@bogdanprodan-okta @noinarisak Any updates from Hashicorp on fixing your GPG key + release? They've blown their "few weeks" estimate out of the water a bit

**Comment by xanonid** [comment]
The most recent provider version seems to be available again via terraform registry: https://registry.terraform.io/providers/okta/okta/latest

It could make sense to update the README.md ...
