### ISSUE TITLE
Okta saml app attribute_statements ignored or not applying

### ISSUE THREAD

**Issue by cru-Luis-Rodriguez** [okta/terraform-provider-okta#418]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.35.0
+ provider registry.terraform.io/oktadeveloper/okta v3.10.1
```

### Affected Resource(s)

- okta_app_saml

### Terraform Configuration Files

```hcl
resource "okta_app_saml" "bomgar" {
  label             = "Bomgar"
  preconfigured_app = "bomgarsaml"
  app_settings_json = jsonencode(
    {
      baseUrl             = "example.org"
      emailAttributeValue = "true"
    }
  )
  attribute_statements {
    type         = "GROUP"
    name         = "Groups"
    filter_type  = "REGEX"
    filter_value = ".*"
    namespace    = "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
  }
}
```

### Expected Behavior

Configure the group match show on step 13 of the okta-bomgar integration [documentation](https://saml-doc.okta.com/SAML_Docs/How-to-Configure-SAML-2.0-for-Bomgar.html). 
![image](https://user-images.githubusercontent.com/6875635/114200834-92290900-9923-11eb-9216-0fbfaed59332.png)

### Actual Behavior

The attribute statement is ignored or does not apply. 

### Steps to Reproduce

1. create an okta_app_saml with a preconfigured_app (bomgarsaml)
2. apply the code

### Important Factoids

I've attempted to configure the okta application from the okta console and then run `terraform import` to see if that group match configuration gets imported but it does not seem to be included on the state.

**Comment by bogdanprodan-okta** [comment]
Hi, @cru-Luis-Rodriguez! Thanks for submitting this issue! I think this is related to #415. I'll do the investigation and create a PR asap to fix this.

**Comment by bogdanprodan-okta** [comment]
Hi, @cru-Luis-Rodriguez! Seems like the preconfigured app `Bomgar` doesn't support `attribute_statements` by default. 
If you take a look at **General** tab in your `Bomgar` app, you won't find `SAML Settings` section. Because attribute statements reside in that section, you won't be able to config them via terraform. I'll ask around whether it's possible to enable that functionality and get back to you asap.

**Comment by cru-Luis-Rodriguez** [comment]
@bogdanprodan-okta 
Thank you.

**Comment by bogdanprodan-okta** [comment]
Hi, @cru-Luis-Rodriguez! Please read the [top comment](https://github.com/okta/terraform-provider-okta/pull/439#issue-622030948) in the linked PR. Thanks!

**Comment by plynch-magnolia** [comment]
These options mentioned in #439 are not available in the Admin Features section....and attribute statements are also not working
