### ISSUE TITLE
Add support for Behavior Detection

### ISSUE THREAD

**Issue by natefredette** [okta/terraform-provider-okta#421]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

New `resource` and `data` source  against the okta api's `/api/v1/behaviors` endpoint: `okta_behavior`. `data` would support lookup by `name`, resource would support import by `id`. Example json model from api:
```json
{
  "status": "ACTIVE",
  "type": "ANOMALOUS_IP",
  "name": "New IP (Managed by terraform)",
  "settings": {
    "maxEventsUsedForEvaluation": 20,
    "minEventsNeededForEvaluation": 0
  }
}
```

### New or Affected Resource(s)

- okta_behavior

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @natefredette! Thanks for submitting this issue! I'll investigate how to handle this and create a PR asap.

**Comment by bogdanprodan-okta** [comment]
Hi, @natefredette! I've added `okta_behavior` data source and is should be available in the newest version. The resource will be added shortly. Cheers!

**Comment by bogdanprodan-okta** [comment]
`okta_behavior` is now available. Closing this issue.
