### ISSUE TITLE
okta_app_user_schema inconsistent apply

### ISSUE THREAD

**Issue by ashwini-desai** [okta/terraform-provider-okta#425]
An inconsistent apply is detected for the resource okta_app_user_schema when applied inside `count`. 

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.14.9

### Affected Resource(s)

- `okta_app_user_schema`

### Terraform Configuration Files

```hcl
variable "custom_attributes" {
  type = list(object({name = string, displayName = string, type = string, required = bool}))
 default = [ 
  {
      name : "firstName",
      type : "string",
      displayName : "First Name",
      required : true
    },
    {
      name : "lastName",
      type : "string",
      displayName : "Last Name",
      required : true
    }
 ]
}
resource "okta_app_user_schema" "custom_attributes" {
  count       =  2
  app_id      = "abcd"
  index       = var.custom_attributes[count.index].name
  title       = var.custom_attributes[count.index].displayName
  type        = var.custom_attributes[count.index].type
  description = var.custom_attributes[count.index].displayName
  required    = var.custom_attributes[count.index].required
  master      = "OKTA"
  scope       = "SELF"
  permissions = "READ_WRITE"
}
```

### Debug Output

N/A

### Panic Output

![image](https://user-images.githubusercontent.com/3282241/114709304-0875a300-9d4a-11eb-80f7-44011b9200ac.png)

### Expected Behavior

Consistent applies

### Actual Behavior

Inconsistent apply detected

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi @ashwini-desai! Thanks for the issue and the PR! I'll review and merge it if everything is OK.

**Comment by ashwini-desai** [comment]
@bogdanprodan-okta - This issue doesn't seem to be completely solved. The inconsistency issue remains even after setting the timeout for resource creation to as high as 100s. We tried to make these changes locally and use it as a local provider.
Please let me know if I should raise a new issue.
