### ISSUE TITLE
Unable to manage the "display name" when configuring "okta_auth_server_scope"

### ISSUE THREAD

**Issue by ht128** [okta/terraform-provider-okta#430]
I've been working with configuring my Okta instance using terraform and the Okta provider. As part of this, I'm adding new scopes to our authorization server.

Using `okta_auth_server_scope`, I'm able to define it as needed except for the **display name** property.

I've been using the documentation here: https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/auth_server_scope#argument-reference and have not been able to find any specific information for the display name. 

The net result is that the scope gets created with a Name, Description and other attributes but no display name. I'd eventually be using the display name when requesting user consent as part of some of the flows.

I've attached an image.
![image](https://user-images.githubusercontent.com/48846331/115082795-b22c6f80-9ec3-11eb-9677-43a374f0cb02.png)

Wondering if this was just a miss.

**Comment by bogdanprodan-okta** [comment]
Hi, @ht128! Thanks for submitting this issue! I'll try to reproduce the problem you have with this field and get back to you asap. If this is a bug, I'll create a PR and link this issue. Have a nice weekend!
