### ISSUE TITLE
Help: where can I get the source id

### ISSUE THREAD

**Issue by amine250** [okta/terraform-provider-okta#431]
Hello,
I'd like to write terraform code that would manage profile mappings for me, so I followed the example in https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/profile_mapping.

However, I'm struggling with the `source_id` field as I don't what I should put in there.
```
source_id - (Required) Source id of the profile mapping.
```

I put something like `oidc_client_xxxx349`  but I got an error like:
```
Error: failed to get profile mapping: The API returned an error: The request was not valid: Invalid source or target id. Source or target id must be of either App Instance or UserType id, Status: 400 Bad Request

  on 01-profile-mapping.tf line 4, in resource "okta_profile_mapping" "this":
   4: resource "okta_profile_mapping" "this" {
```

**Comment by bogdanprodan-okta** [comment]
Hi, @amine250! Thanks for submitting this issue! Terraform repo has a lot of [examples](https://github.com/okta/terraform-provider-okta/tree/master/examples) of how to use the resources. Here is an example for `okta_profile_mapping` resource:
```
resource "okta_profile_mapping" "test" {
  source_id          = okta_idp_social.google.id
  target_id          = data.okta_user_profile_mapping_source.user.id
  delete_when_absent = true

  mappings {
    id         = "firstName"
    expression = "appuser.firstName"
  }

  mappings {
    id         = "lastName"
    expression = "appuser.lastName"
  }

  mappings {
    id         = "email"
    expression = "appuser.email"
  }

  mappings {
    id         = "login"
    expression = "appuser.email"
  }
}

resource "okta_idp_social" "google" {
  type          = "GOOGLE"
  protocol_type = "OAUTH2"
  name          = "testAcc_google_replace_with_uuid"

  scopes = [
    "profile",
    "email",
    "openid",
  ]

  client_id         = "abcd123"
  client_secret     = "abcd123"
  username_template = "idpuser.email"
}

data "okta_user_profile_mapping_source" "user" {
  depends_on = [okta_idp_social.google]
}
```

**Comment by bogdanprodan-okta** [comment]
If there are no more questions, feel free to close this issue. Thanks!

**Comment by amine250** [comment]
Hi @bogdanprodan-okta and thanks for your help.

I've succeeded to create a mapping.

Compared to doing it on the console, I can't know if the Terraform action will or will not apply the mappings to all users with the current profile?

![image](https://user-images.githubusercontent.com/7514608/115521400-698e0100-a28b-11eb-8408-f8d08b8430cd.png)

Is this step relevant when working with mappings in Terraform ?
Is the [`push_status`](https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/profile_mapping#push_status) argument in the `mappings` block what I need here ?

Sorry, I'm very new to Okta, and these questions might be out of place.
Thanks again.

**Comment by bogdanprodan-okta** [comment]
Hi! Yes, basically you are right. This is the [official docs ](https://developer.okta.com/docs/reference/api/mappings/#property-mapping-object) explaining this.
