### ISSUE TITLE
Office365 App and manual WS-Federation

### ISSUE THREAD

**Issue by cru-Luis-Rodriguez** [okta/terraform-provider-okta#434]
Do you have a resource to set up an Office365 App with manual WS-Federation?

**Comment by cru-Luis-Rodriguez** [comment]
is it possible to use the okta_app_saml like so?

```
resource "okta_app_saml" "office365" {
  label             = "office365-example.com"
  signOnMode        = "WS_FEDERATION"
  preconfigured_app = "office365"
  app_settings_json = jsonencode(
    {
      audienceRestriction: "urn:example:app",
      groupName: null,
      groupValueFormat =  "windowsDomainQualifiedName",
      realm =  "urn:example:app",
      wReplyURL =  "https://example.com/",
      attributeStatements =  null,
      nameIDFormat =  "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified",
      authnContextClassRef =  "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
      siteURL =  "https://example.com",
      wReplyOverride =  false,
      groupFilter =  null,
      usernameAttribute =  "username"
  }
  )
}
```

**Comment by bogdanprodan-okta** [comment]
Hi, @cru-Luis-Rodriguez! Thanks for submitting this issue! I'm not sure whether to not it's possible because I've never done this before, but I'll do some investigation and get back to you asap.

**Comment by cru-Luis-Rodriguez** [comment]
Hello, @bogdanprodan-okta Thanks for investigating. A co-worker of mine found the following [post](https://onlinehelp.opswat.com/metaaccess/Okta_IdP_with_O365_using_SAML_2.0.html) that configures office365 as a SAML app in Okta with federation. Granted I'm unsure if this is the same as `WS-Federation` or a workaround, but it at least shows that it might be possible to use the `okta_app_saml` to configure the app. What do you think?

**Comment by cru-Luis-Rodriguez** [comment]
@bogdanprodan-okta So I ran a test to try to setup the office365 as a saml app as described in the post and was not success full. I'm going to close this inquiry and maybe open a request for a new feature TF resource that support the office365 integration.

**Comment by bogdanprodan-okta** [comment]
Hi, @cru-Luis-Rodriguez! Currently, the provider doesn't support `SignOnMode=WS_FEDERATION`. I can start to work on adding a new `okta_app_ws_federation` resource next week.

**Comment by cru-Luis-Rodriguez** [comment]
@bogdanprodan-okta Can you incorporate allowing manual federation? I'm not 100% sure, but I think `signOnMode=WS_FEDERATION` is only for an automatic federation where okta takes care of federating the domains for the customer. Still, there is also manual federation where the customer has to run a PowerShell Script to federate the domain. I believe that uses `signOnMode": "SAML_1_1` at least that is what I've discovered from my testing.

**Comment by bogdanprodan-okta** [comment]
We need two resources then: `SAML_1_1` (Federated Authentication with SAML 1.1 WebSSO) and `WS_FEDERATION` (Federated Authentication with WS-Federation Passive Requestor Profile)
