### ISSUE TITLE
Update provider environment variable handling

### ISSUE THREAD

**Issue by ymylei** [okta/terraform-provider-okta#436]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The provider currently supports a number of environment variables documented [here](https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs#environment-variables). 

These variables are not the same as those accepted by the [okta-sdk-golang](https://github.com/okta/okta-sdk-golang#environment-variables).

IMO the provider should update the environment variables in the next breaking change to match the pattern set by the `okta-sdk-golang`.

### New or Affected Resource(s)

N/A

### Potential Terraform Configuration

N/A

### References

Provider Environment Variable Docs: https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs#environment-variables

Okta SDK Golang Environment Variables Docs: https://github.com/okta/okta-sdk-golang#environment-variables

**Comment by bogdanprodan-okta** [comment]
Hi, @ymylei! Thanks for submitting this issue! Yes, this is a breaking change for the provider. I think we can change it in the 4.x version.

**Comment by monde** [comment]
@ymylei @bogdanprodan-okta We could probably do an option (via env var, cli, or config) that would toggle which env variable convention is used. Something like `OKTA_ENV_VAR_TYPE=okta-sdk-golang`. The toggling logic might be in `envDefaultSetFunc` https://github.com/okta/terraform-provider-okta/blob/master/okta/provider.go#L346-L358  to make it work. A couple of implementionts come to mind. I think we could do it in a way that isn't a breaking change.

**Comment by monde** [comment]
keeping this active
