### ISSUE TITLE
v3.11.0 is not available in Terraform Registry

### ISSUE THREAD

**Issue by bulebuk** [okta/terraform-provider-okta#437]
```
Could not retrieve the list of available versions for provider
oktadeveloper/okta: no available releases match the given constraints 3.11.0
```

Please push the latest version to the Terraform registry so that it may be used.

**Comment by bogdanprodan-okta** [comment]
Please read the note in the [README](https://github.com/okta/terraform-provider-okta#important-note)

**Comment by bulebuk** [comment]
Can 3.11.0, and newer, be published under the old name namespace until Hashicorp can rename?

The README workaround doesn't provide much recourse for Terraform Cloud users or enterprises with strict software sourcing.
