### ISSUE TITLE
okta_group fails to load users when the terraform state is started from nothing

### ISSUE THREAD

**Issue by Yohan460** [okta/terraform-provider-okta#438]
### Description
[This code block](https://github.com/okta/terraform-provider-okta/blob/5229dd7a3fc0083514831cd9204e9d3abc23de41/okta/resource_okta_group.go#L108-L110) is causing the terraform state file to not populate okta users into the state when a `terraform refresh` is executed when the `"users"` key in the terraform state file is either `null` or not defined.
https://github.com/okta/terraform-provider-okta/blob/5229dd7a3fc0083514831cd9204e9d3abc23de41/okta/resource_okta_group.go#L108-L110

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
TF: v0.12.29
Okta: v3.11.0

### Affected Resource(s)

- okta_group

### Expected Behavior
The provider should populate the users of said group into the terraform state file irregardless of what the current state is

### Actual Behavior
When the `"users"` key is not defined  or set to `null` for the group in the terraform state file. Upon a `terraform refresh` it will not fill the users list with the actual users of the group

### Steps to Reproduce

1. Have a proper TF state file with an `okta_group` resource
2. Open the TF state file
3. Delete the `users` key under said group
4. Run a `terraform refresh`
5. The users will not update, or will be `null`. This does not match the remote state

### Important Factoids
Delete [this code block](https://github.com/okta/terraform-provider-okta/blob/5229dd7a3fc0083514831cd9204e9d3abc23de41/okta/resource_okta_group.go#L108-L110) and it should be resolved
https://github.com/okta/terraform-provider-okta/blob/5229dd7a3fc0083514831cd9204e9d3abc23de41/okta/resource_okta_group.go#L108-L110

### References
https://github.com/okta/terraform-provider-okta/blob/5229dd7a3fc0083514831cd9204e9d3abc23de41/okta/resource_okta_group.go#L108-L110

**Comment by bogdanprodan-okta** [comment]
Hi, @Yohan460! Thanks for submitting this issue! I have a question though: why do ever need to change `terraform.tfstate` file manually? It's intended to be used by the terraform cli itself, not the user.

**Comment by Yohan460** [comment]
Hey @bogdanprodan-okta,

At Coinbase we use a tool called [GeoEngineer](https://github.com/coinbase/geoengineer) (Geo) as a wrapper for terraform to standardize generating terraform code from YAML GPS files. As apart of this process it [generates a skeleton terraform state](https://github.com/coinbase/geoengineer/blob/master/lib/geoengineer/cli/terraform_commands.rb#L6-L17) file with the remote IDs, looked up by a separate API layer with the remove service. Then it executes a [`terraform refresh`](https://github.com/coinbase/geoengineer/blob/master/lib/geoengineer/cli/terraform_commands.rb#L51) to populate the details of those objects. This skeleton filling out process is what is currently broken due to the `users` key being undefined in this skeleton. 

Happy to schedule some time chat about it if you'd like.
