### ISSUE TITLE
Missing credentials_sheme in okta_app_swa

### ISSUE THREAD

**Issue by dsalaza4** [okta/terraform-provider-okta#443]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Resource `okta_app_swa` does not support parameters for shared passwords:

1. `credentials_scheme`.
1. `shared_username`.
1. `shared_password`.

Is it possible to add these attributes so one can create swa apps with `SHARED_USERNAME_AND_PASSWORD`?

### New or Affected Resource(s)

1. `okta_app_swa`

### Potential Terraform Configuration

N/A

### References

1. https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/app_swa#argument-reference

**Comment by bogdanprodan-okta** [comment]
Hi, @dsalaza4! Thanks for submitting this issue! If these fields are present in the official SDK, I'll add them shortly.

I think this requires creating a new resource for https://developer.okta.com/docs/reference/api/apps/#set-swa-shared-credentials in the provider.

**Comment by dsalaza4** [comment]
That would work too. Though, to be honest, it's kinda weird that other resources support it directly and this one does not. Thank you very much for your time!

**Comment by bogdanprodan-okta** [comment]
> That would work too. Though, to be honest, it's kinda weird that other resources support it directly and this one does not. Thank you very much for your time!

No problem!
