### ISSUE TITLE
Allow null username for okta_app_user

### ISSUE THREAD

**Issue by dsalaza4** [okta/terraform-provider-okta#447]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `username` argument is required for creating an `okta_app_user` resource.
When trying to assign a `SHARED_USERNAME_AND_PASSWORD` app to a user,
there are 3 possible paths, 2 of them do not work, 1 of them does not work completly fine:

1. Making `username = okta_app_auto_login.app1.shared_username`. This returns the following error:
    ```
    Error: failed to assign user to application: The API returned an error: Credentials should not be set on this resource based on the scheme.. Causes: errorSummary: User level credentials should not be provided for this scheme.
    ```
    It makes sense, `username` indeed should not be provided for apps with shared username.
1. Making `username = null`. This returns the following error:
    ```
    Error: Missing required argument
    The argument "username" is required, but no definition was found.
    ```
1. Making `username = ""`. With this one, resource creation in possible.
    The downside is that every terraform plan returns the resource will be changed:
    ```
    Terraform will perform the following actions:

      # okta_app_user.app1_user1 will be updated in-place
      ~ resource "okta_app_user" "app1_user1" {
            app_id            = "xxxxxxxxxxxxxxxx"
            id                = "xxxxxxxxxxxxxxxxxx"
            profile           = jsonencode({})
            retain_assignment = false
            user_id           = "xxxxxxxxxxxxxxx"
          - username          = "xxxxxxxx@xxxxxxx.com" -> null
        }

    Plan: 0 to add, 1 to change, 0 to destroy.
    ```
    If terrafom apply is executed, terraform returns the change was successfully made, but in the next plan, it says the resource will change again with the exact same message (`"xxxxxxxx@xxxxxxx.com" -> null`).

Is it possible to make the `username ` argument not required?

### New or Affected Resource(s)

1. okta_app_user

### Potential Terraform Configuration

```hcl
resource "okta_user" "user1" {
  email       = "user1@gmail.com"
  first_name  = "user1"
  last_name   = "user1"
  login       = "user1@gmail.com"
  admin_roles = []
}

resource "okta_app_auto_login" "app1" {
  label               = "app1"
  status              = "ACTIVE"
  preconfigured_app   = null
  credentials_scheme  = "SHARED_USERNAME_AND_PASSWORD"
  shared_username     = "xxxxx"
  shared_password     = "xxxxx"
  sign_on_url         = "xxxxxx"
  auto_submit_toolbar = true

  lifecycle {
    ignore_changes = [
      groups,
      users,
    ]
  }
}

resource "okta_app_user" "app1_user1" {
  app_id   = okta_app_auto_login.app1.id
  user_id  = okta_user.user1.id
  username = ""
}
```

### References

1. https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/app_user#username

**Comment by dsalaza4** [comment]
Something important to note is that although the resource creation fails when manually assigning the `shared_username` from the app, that's the actual value it ends up getting when assigning the empty string (`""`).

Another solution could be making the `Credentials should not be set on this resource based on the scheme` error go away by validating `username == app.shared_username`

**Comment by bogdanprodan-okta** [comment]
Hi, @dsalaza4! Thanks for submitting this issue! I'll try to reproduce your steps and get back to you asap.

**Comment by bogdanprodan-okta** [comment]
Hi @dsalaza4! I've created a PR so it should fix this issue. Basically, it will ignore `username` field when app has ` credentials_scheme = "SHARED_USERNAME_AND_PASSWORD"` scheme. The only issue is when you changing the `credentials_scheme`, you can only set `username` in `okta_app_user` only after running `terraform apply` (so the changes to the app will be applied), because in the terraform you can not read info from a different resource.

**Comment by dsalaza4** [comment]
Thank you very much!
