### ISSUE TITLE
Conflict between okta_group_rule and okta_group users

### ISSUE THREAD

**Issue by dsalaza4** [okta/terraform-provider-okta#449]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Declaring `users` within a `okta_group` resource, overwrites assgined users by a `okta_group_rule` resource tied to the group.

Is it possible to make `okta_group` to dynamically generate the user list by taking into the account the users assigned by `okta_group_rule`?

### New or Affected Resource(s)

1. okta_group
2. okta_group_rule

### Potential Terraform Configuration

```hcl
resource "okta_user" "user1" {
  email       = "user1@hotmail.com"
  first_name  = "user1"
  last_name   = "user1"
  login       = "user1@hotmail.com"
  admin_roles = []
}

resource "okta_user" "user2" {
  email       = "user2@gmail.com"
  first_name  = "user2"
  last_name   = "user2"
  login       = "user2@gmail.com"
  admin_roles = []
}

resource "okta_group" "group1" {
  name        = "group-1"
  users       = [
    okta_user.user1.id
  ]
}

resource "okta_group_rule" "gmail_users" {
  name             = "gmail users"
  status           = "ACTIVE"
  expression_type  = "urn:okta:expression:1.0"
  expression_value = String.stringContains(user.email,"@gmail.com")

  group_assignments = [
    okta_group.group1.id
  ]
}
```

When testing this configuration, `user2` is added to the group by `okta_group_rule.gmail_users`,
but then removed by `okta_group.group1` as only `user1` is declared in `users`.

### References

1. https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/group_rule#group_assignments
2. https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/group#users

**Comment by bogdanprodan-okta** [comment]
Hi, @dsalaza4! Thanks for submitting this issue! I don't think this is possible, because of how the terraform works. It can not control what Okta does under the hood when you creating a rule. The only thing you can do is create `okta_group_rule` with `status = "INACTIVE"`, so it won't add users on resource creation (and activate it later). Another option is to not add the users into `okta_group` at all and set `lifecycle { ignore_changes = ["users"] }` so the plan ignores that field.

**Comment by dsalaza4** [comment]
@bogdanprodan-okta I think that by using `okta_group_membership` instead of declaring `users` within the  group itself would allow to comlpetely disable the `users` attribute by using the lifecycle policy you mentioned. Maybe this approach would allow to manage both rules and users for the same group. I will give it a try and let you know. Thank you so much!

**Comment by dsalaza4** [comment]
@bogdanprodan-okta I can confirm that using `okta_group_membership` instead of declaring `users` within the `okta_group` worked. Closing this issue.
