### ISSUE TITLE
okta_app_oauth login_uri does not support generic URIs

### ISSUE THREAD

**Issue by dmpratt** [okta/terraform-provider-okta#450]
When configuring an okta_app_oauth with type = "native" for a mobile native app, the login, logout and redirect URIs use a special format "application.code:/callback" This is a valid uri, but throws an error: invalid URL: expected 'login_uri' to have a host. Okta allows the update so I would expect terraform to treat it as a URI, not a URL. Thanks!

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.15.1
on darwin_amd64
+ provider registry.terraform.io/oktadeveloper/okta v3.10.1

### Affected Resource(s)

- okta_app-oauth

### Terraform Configuration Files

```hcl
resource "okta_app_oauth" "enable_mobile" {
  label                      = "App Name"
  status                     = "ACTIVE"
  type                       = "native"
  groups                     = ["123..."]
  response_types             = ["code"]
  grant_types                = ["authorization_code", "refresh_token"]
  token_endpoint_auth_method = "none"
  auto_key_rotation          = true
  issuer_mode                = "ORG_URL"
  logo_uri                   = "https://mylogo.here.com"
  login_uri                  = "app.name:/callback"
  post_logout_redirect_uris  = ["app.name:/splash"]
  redirect_uris              = ["app.name:/callback"]
}
```

### Expected Behavior

URI should have been accepted just like it is for post_logout_redirect_uris and redirect_uris.

### Actual Behavior

Error prevents setting appropriate value for login_uri.

### Steps to Reproduce

1. `terraform plan`

**Comment by bogdanprodan-okta** [comment]
Hi, @dmpratt! Thanks for submitting this issue! There was similar issue #370 and I've already closed it. The problem is that this fix is not yet released into terraform registry. Please read this [note.](https://github.com/okta/terraform-provider-okta#important-note).
