### ISSUE TITLE
Unnecessary ForceNew on okta_user_schema one_of/enum

### ISSUE THREAD

**Issue by kristian-lesko** [okta/terraform-provider-okta#451]
When adding a new item to the `enum`/`one_of`/`array_enum`/`array_one_of` parameters of the `okta_user_schema` attribute, replacement of the whole resource is forced:
```
okta_user_schema.this: Refreshing state... [id=team]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # okta_user_schema.this must be replaced
-/+ resource "okta_user_schema" "this" {
      ~ enum        = [ # forces replacement
            # (54 unchanged elements hidden)
            "Team1",
          + "NewTeamTest",
        ]
      ~ id          = "team" -> (known after apply)
      - max_length  = 0 -> null
      - min_length  = 0 -> null
        # (9 unchanged attributes hidden)

      + one_of { # forces replacement
          + const = "NewTeamTest"
          + title = "NewTeamTest"
        }
        # (55 unchanged blocks hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

------------------------------------------------------------------------
```

This seams unnecessary, since in the Okta UI, it is possible to add/remove items from the enumeration of string/array attributes even without their recreation.

In other words, it seems like a few `ForceNew` items might not be needed:
* [array_enum](https://github.com/okta/terraform-provider-okta/blob/master/okta/user_schema.go#L22)
* [array_one_of](https://github.com/okta/terraform-provider-okta/blob/master/okta/user_schema.go#L28)
* [enum](https://github.com/okta/terraform-provider-okta/blob/master/okta/user_schema.go#L66)
* [one_of](https://github.com/okta/terraform-provider-okta/blob/master/okta/user_schema.go#L73)

**Comment by bogdanprodan-okta** [comment]
Hi, @kristian-lesko! Thanks for submitting this issue! I'll test this resource without `ForceNew` and create a PR if it works.

**Comment by kristian-lesko** [comment]
Hello @bogdanprodan-okta, any news about this, please?

**Comment by bogdanprodan-okta** [comment]
Hi, @kristian-lesko! Sorry for the late reply, I'll start to work on this tomorrow!
