### ISSUE TITLE
okta_app_saml preconfigured accepts custom attributes

### ISSUE THREAD

**Issue by gstotts** [okta/terraform-provider-okta#453]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Would like the ability to add attributes that are available in the API for preconfigured SAML apps - such as tenant ids, etc.  While each app may vary here, it would be nice to provide a block that contains these in order to pair configs with what is existing if a user chooses to use a preconfigured app.

### New or Affected Resource(s)

- okta_app_saml

### Potential Terraform Configuration

```hcl
resource "okta_app_saml" "sample" {
  preconfigured_app = "some-app"
  preconfigured_settings = [
    {
      name = "tenant_id"
      value = "124231409123840123"
    },
    {
      name = "nameIdValue"
      value = false
    },
  ]
}
```

### References

- n/a

**Comment by bogdanprodan-okta** [comment]
Hi, @gstotts! Thanks for submitting this issue! I think the field `app_settings_json` is the one you are looking for. Here is an example of pre-configured SAML app:
```hcl
resource "okta_app_saml" "sumo_logic" {
  label               = "SumoLogic"
  preconfigured_app   = "sumologic"
  auto_submit_toolbar = true
  app_settings_json   = <<JSON
  {
    "baseUrl": "https://service.sumologic.com",
    "organizationID": 108525159
  }
}
```

**Comment by gstotts** [comment]
Ahh did not see that field in docs.  Thank you.
