### ISSUE TITLE
Missing credentials_sheme in okta_app_three_field

### ISSUE THREAD

**Issue by dsalaza4** [okta/terraform-provider-okta#458]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Resource `okta_app_three_field` does not support parameters for shared passwords:

1. `credentials_scheme`.
2. `shared_username`.
3. `shared_password`.

Is it possible to add these attributes so one can create `three_field` apps with SHARED_USERNAME_AND_PASSWORD?

### New or Affected Resource(s)

1. `okta_app_three_field`

### Potential Terraform Configuration

N/A

### References

1. https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/app_three_field

Note: Although the provided example for the app includes a `credentials_scheme` attribute, in reality it does not exist for the resource.

**Comment by bogdanprodan-okta** [comment]
Hi, @dsalaza4! Thanks for submitting this issue! I'll try to add these fields to the resource and create a corresponding PR.

**Comment by dsalaza4** [comment]
Thank you so much  @bogdanprodan-okta!
