### ISSUE TITLE
okta_app_three_field does not assign groups correctly

### ISSUE THREAD

**Issue by dsalaza4** [okta/terraform-provider-okta#459]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

N/A

### Affected Resource(s)

1. `okta_app_three_field`

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

A `okta_app_three_field` resource should give access to the groups specified in the `groups` attribute,
just like all other apps do.

### Actual Behavior

When a `okta_app_three_field` resource is created with groups declared within the `groups` attribute,
the resource is created successfully, the tfstate shows the `groups` attribute is correct,
but the access itself is not given. When looking at the app from the Okta GUI,
no groups are assgined to it.

### Steps to Reproduce

1. Create a `okta_app_three_field` resource and assign a group to it:
    ```
    resource "okta_group" "test" {
      name = "test"
    }

     resource "okta_app_three_field" "test" {
      label                = "three field test"
      status               = "ACTIVE"
      button_selector      = "#button"
      username_selector    = "#username"
      password_selector    = "#password"
      extra_field_selector = "#extra"
      extra_field_value    = "12345"
      url                  = "https://whatever.com"
      auto_submit_toolbar  = true

      groups = [
        okta_group.test.id,
      ]
    }
    ```

1. Apply changes with `terraform apply`
2. Go to the app via GUI, you'll notice the test group was not assigned to the app.

### Important Factoids

N/A

### References

1. https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/app_three_field#groups

**Comment by dsalaza4** [comment]
For now, I managed to assign groups to `okta_app_three_field` apps by using `okta_app_group_assignment`, although it kinda leaves me in a lose-lose situation, because having a `okta_app_group_assignment` for every group assignment burns my api calls very fast and I end up hitting the rate limits. That's why I had to go back to the `groups` attribute in the first place, even though I know it is deprecated now. :crying_cat_face:

**Comment by bogdanprodan-okta** [comment]
Hi, @dsalaza4! Thanks for submitting this issue! Try using different resource for group assignments (it's not yet released though):
```hcl
resource "okta_app_group_assignments" "test" {
  app_id   = okta_app_oauth.test.id

  group {
    id = okta_group.test1.id
    priority = 1
  }
  group {
    id = okta_group.test2.id
    priority = 2
  }
  group {
    id = okta_group.test3.id
    priority = 3
  }
}
```
