### ISSUE TITLE
SAML_1_1

### ISSUE THREAD

**Issue by gstotts** [okta/terraform-provider-okta#460]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
O365 Integration with Okta set as WS-Federation appears to have a signOnMode of SAML_1_1.  When I go to use the `app_okta_saml` object I get a type mismatch error... probably because it assumes SAML_2_0?  Need a way to integrate something easy like this -- especially since its a rather extensively used product.  If there is another method I've missed please let me know.

### New or Affected Resource(s)

- okta_saml1_1_app

### Potential Terraform Configuration

Similar to `okta_saml_app` but does not expect signOnMode of SAML_2_0.
### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @gstotts! Thanks for submitting this issue! I'll investigate what I can do and get back to you asap.

**Comment by gstotts** [comment]
@bogdanprodan-okta  Any updates?  This is one of the last things left in our migration to using TF for the apps so just looking for a rough estimate on timing for our project manager.

**Comment by bogdanprodan-okta** [comment]
Hi @gstotts! Sorry for the late reply! I'll look into this and try to figure out how to include this in the next release. Cheers!

**Comment by bogdanprodan-okta** [comment]
Hi there! I'll probably add the new property `saml_version` or `saml_type` to this resource. By default, it will be `SAML_2_0`, but it will be possible to change it to `SAML_1_0`.

**Comment by bogdanprodan-okta** [comment]
Hi @gstotts! I will be adding `saml_version` field to the `okta_app_saml`, so it can be configured
