### ISSUE TITLE
app_settings_json for okta_app_auto_login apps

### ISSUE THREAD

**Issue by dsalaza4** [okta/terraform-provider-okta#462]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating `okta_app_auto_login` apps with `preconfigured_app`, sometimes
you must pass some configurations for the preconfigured app.
An `app_settings_json` attribute similar to the one existing in `okta_app_saml` would allow to pass such configurations.

### New or Affected Resource(s)

1. `okta_app_auto_login`

### Potential Terraform Configuration

```
resource "okta_app_auto_login" "apps" {
  label               = "google test"
  status              = "ACTIVE"
  preconfigured_app   = "google"
}
```

When trying to create an auto_login google app, you get:

```
Error: failed to create auto login application: The API returned an error: Api validation failed: domain. Causes: errorSummary: domain: The field cannot be left blank
```

This happens because there is no way to pass app settings to the resource.

### References

1. https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/app_auto_login
2. https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/app_saml#app_settings_json

**Comment by bogdanprodan-okta** [comment]
Hi, @dsalaza4! Thanks for submitting this issue! I'll add this field to the resource and create a corresponding PR.

**Comment by dsalaza4** [comment]
@bogdanprodan-okta Thank you!
