### ISSUE TITLE
RPS Setting for Provider

### ISSUE THREAD

**Issue by gstotts** [okta/terraform-provider-okta#463]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Would like to have a Requests Per Second setting that can be manipulated so as not to have to hit rate limits.  Cloudflare's TF provider has something similar to this which helps keep from hitting the rate limit and having to wait additional time in the first place. 

### New or Affected Resource(s)

- Okta provider resource

### Potential Terraform Configuration

```hcl
terraform {
  required_providers {
    okta = {
      source = "oktadeveloper/okta"
      version = "~> 3.6"
    }
  }
}

# Configure the Okta Provider
provider "okta" {
  org_name  = "dev-123456"
  base_url  = "oktapreview.com"
  api_token = "xxxx"
  rps = 10
}
```

### References

- [Cloudflare Example in Docs](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs)
- [Cloudflare Provider RPS](https://github.com/cloudflare/terraform-provider-cloudflare/blob/5d39f78721c55f06c628b77e1bc7025d1a66108b/cloudflare/provider.go#L53-L58)
- [Cloudflare Go SDK RPS Use](https://github.com/cloudflare/cloudflare-go/blob/d372118b194b1e98c4046fc1f5e0daa31cae715c/cloudflare.go#L52-L65)

**Comment by gstotts** [comment]
Related to #186

**Comment by bogdanprodan-okta** [comment]
Hi, @gstotts! Thanks for submitting this issue! We are aware of this issue and currently, another team is working on some functionality that will help us implement rate-limiting functionality.

**Comment by gstotts** [comment]
@bogdanprodan-okta Would you prefer I close this issue out then since it looks like the other Issue is tracking as well?

**Comment by bogdanprodan-okta** [comment]
@gstotts! Sure you can close it
