### ISSUE TITLE
resource_okta_app_oauth does not allow setting "refresh_token"  as grant type for browser app when Refresh token rotation is enabled.

### ISSUE THREAD

**Issue by ruZZil** [okta/terraform-provider-okta#465]
resource_okta_app_oauth does not allow setting "refresh_token"  as grant type for browser app. 

This feature is indeed not available, unless enabling the setting for Refresh token rotation.

Once Refresh token rotation has been activated, I should be able to add "refresh_token" to grant type.

Limitation is seen in okta/resource_okta_app_oauth.go

	"browser": {
		ValidGrantTypes: []string{
			implicit,
			authorizationCode,
		},

In the meanwhile, once I enable the refresh_token grant type in the web UI, I can no longer use terraform which either removes it, or fails the validation. 

Thanks,

**Comment by bogdanprodan-okta** [comment]
Hi, @ruZZil! Thanks for submitting this issue! I'll try to reproduce your scenario and create a corresponding PR.

**Comment by jeffg-archive** [comment]
@bogdanprodan-okta I was working on a PR for this, by coincidence. There is also the `settings.oauthClient.refresh_token` that needs `{"rotation_type": "ROTATE", "leeway": 30}` config managed. It is already in the go SDK.

**Comment by ruZZil** [comment]
Thanks for the fast turnaround. Compiled from source, solves the issue. 

There may be a problem if someone tries to add refresh_token if the feature is disabled in settings,  though that may just result in an api call failure. 

Working for our use case though. Thanks! 👍

**Comment by bogdanprodan-okta** [comment]
> Thanks for the fast turnaround. Compiled from source, solves the issue.
> 
> There may be a problem if someone tries to add refresh_token if the feature is disabled in settings, though that may just result in an api call failure.
> 
> Working for our use case though. Thanks! 👍

Yes, it will return either 400 or 500 error.
