### ISSUE TITLE
Email & SMS Sender

### ISSUE THREAD

**Issue by klaushauschild1984** [okta/terraform-provider-okta#469]
Is there actually a resource present to configure email and SMS sender via Terraform?
If not please add it.

![image](https://user-images.githubusercontent.com/3625449/117834799-c02da000-b277-11eb-99b2-4d5f9d287e7c.png)

**Comment by bogdanprodan-okta** [comment]
Hi, @klaushauschild1984! Thanks for submitting this issue! If there is a public API for that, then yes, I'll add it shortly.

**Comment by klaushauschild1984** [comment]
I fear there isn't I figured out after my research. May reach out to Okta support.

**Comment by bogdanprodan-okta** [comment]
@klaushauschild1984 another thing is to manage Email Sender Configuration. This will require the creation of two resources, like `okta_mail_sender` and `okta_mail_sender_dns_config`
