### ISSUE TITLE
Possibility to set "Requestable SSO URLs" via okta_app_saml

### ISSUE THREAD

**Issue by summersonne** [okta/terraform-provider-okta#470]
Is it possible to set "Requestable SSO URLs" via okta_app_saml?

Can someone provide any examples?

**Comment by summersonne** [comment]
acs_endpoints = ["https://example.com", "https://okta.com"]

An argument named "acs_endpoints" is not expected here.

Trying to do like in example.
Is the anyone on this planet has a working documentation for okta_app_saml?

**Comment by bogdanprodan-okta** [comment]
Hi, @summersonne! Thanks for submitting this issue! Could you please provide example of the resource you are trying to create?

**Comment by summersonne** [comment]
I am just trying to use code from here https://github.com/okta/terraform-provider-okta/blob/master/examples/okta_app_saml/updated.tf

And terraform return error An argument named "acs_endpoints" is not expected here.
What minimal version of terraform do I need to use?

**Comment by bogdanprodan-okta** [comment]
I've tested it with the lates published v3.10.1 and it works fine.

**Comment by summersonne** [comment]
I am using:
provider "okta"
  version = "3.6.1"

**Comment by bogdanprodan-okta** [comment]
> I am using:
> provider "okta"
> version = "3.6.1"

You can easily update to the latest version (as it is backward compatible) and try again.

**Comment by summersonne** [comment]
>>it is backward compatible

Not completely. There was a lot of issues after we updated it
