### ISSUE TITLE
resource default okta_auth_server_policy

### ISSUE THREAD

**Issue by jeffg-archive** [okta/terraform-provider-okta#471]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Manage okta auth server default policy via terraform.

### New or Affected Resource(s)

- okta_auth_server_policy_default

### Example possible terraform config

```hcl
resource "okta_auth_server_policy_default" "default" {
  status           = "ACTIVE"
  name             = "Default Policy"
  description      = "<desc>"
  priority         = 10
  client_whitelist = []
  auth_server_id   = "<id>"
}
```

### References

- #51

**Comment by jeffg-archive** [comment]
I'll put something up for this, time permitting.

**Comment by bogdanprodan-okta** [comment]
Hi, @jeffg-hpe! Thanks for submitting this issue! This resource should definitely be added to the terraform.
