### ISSUE TITLE
Support for Radius applications

### ISSUE THREAD

**Issue by dsalaza4** [okta/terraform-provider-okta#475]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The provider lacks a `okta_app_radius` resource for RADIUS apps:

https://help.okta.com/en/prod/Content/Topics/integrations/Okta_Radius_App.htm

### New or Affected Resource(s)

- `okta_app_radius`

### Potential Terraform Configuration

N/A

### References

1. https://help.okta.com/en/prod/Content/Topics/integrations/Okta_Radius_App.htm

**Comment by bogdanprodan-okta** [comment]
Hi, @dsalaza4! Thanks for submitting this issue! I'll investigate whether this is supported via public API and add the corresponding resource.

**Comment by bogdanprodan-okta** [comment]
Hi @dsalaza4! The problem with Radius apps is that a lot of the properties you can set up via UI are not available in public API. I will ask the team responsible for this functionality and maybe get some ETA. Cheers!

**Comment by dsalaza4** [comment]
Shouldn't this issue be reopened?

**Comment by bogdanprodan-okta** [comment]
> Shouldn't this issue be reopened?

There is still no proper API available for the Radius apps, but I'll keep this issue open.

**Comment by boekkooi-lengoo** [comment]
Shouldn't this issue be reopened?

**Comment by monde** [comment]
> Shouldn't this issue be reopened?

Hi @boekkooi-lengoo there isn't a Radius application type in Okta's Public API https://developer.okta.com/docs/reference/api/apps/ . As a rule, the terraform provider interacts with Okta's public API through okta-sdk-golang. Please open a support ticket asking for Radius application support in the public API so that your request is noted within our internal tracking.

**Comment by noinarisak** [comment]
Hey @boekkooi-lengoo and @dsalaza4, can one of you also submit this to https://ideas.okta.com/ and the other vote on it? The increase visibility to other customers help increase possibility/priority on to the APIs roadmap. 😉

**Comment by boekkooi-lengoo** [comment]
@noinarisak I'm not sure this is still valid because they are launching? some new ideas program (at least) that what I see with most items in ideas.okta.com.

> We’re excited to let you know that we’re just about ready to launch an all-new &, enhanced Okta Ideas program, which will dramatically improve the way we capture requests from our Okta customer community.
