### ISSUE TITLE
Support all dynamic zones options for okta_network_zone 

### ISSUE THREAD

**Issue by lilley2412** [okta/terraform-provider-okta#476]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The okta_network_zone resource does not support all dynamic zone configuration options.  Only country codes may be provided, and the IP Type is always "Any".   The okta_network_zone resource should support the Tor Anonymizer proxy and ISP ASN fields.

### New or Affected Resource(s)

okta_network_zone

### Potential Terraform Configuration

```hcl
resource "okta_network_zone" "example" {
  name     = "example"
  type     = "DYNAMIC"
  ip_type = "Any | Any Proxy | Tor anonymizer proxy | Not Tor anonymizer proxy"
  locations = ["ISO-CODE"]
  isp_asns = ["asn"]
}
```

### References

n/a

**Comment by bogdanprodan-okta** [comment]
Hi, @lilley2412! Thanks for submitting this issue! I'll investigate the possibility to add these and create a corresponding PR.

**Comment by lucascantor** [comment]
It looks like this is at least partially resolved in https://github.com/okta/terraform-provider-okta/pull/522
