### ISSUE TITLE
Deprecate & Remove User/Group Handling From App Resources

### ISSUE THREAD

**Issue by ymylei** [okta/terraform-provider-okta#483]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We have resources like:
* `okta_app_user`
* `okta_app_group_assignments`

Which follow the "better" practice of having the separate API endpoint (`apps/<id>/groups` / `apps/<id>/users`) be separated out to their own resources. Since we have those already, and should encourage their use over the direct assignment. The plan I propose is:

1. Mark the `users` and `groups` schema in the base app schema as deprecated, pointing people to the mentioned resources. (#482)
2. Create a `okta_app_user_assignments` resource (which would mimic the creation of `okta_app_group_assignments` compared with the original `okta_app_group_assignment` as a consolidation for many user assignment calls to the same app) as a update/replacement to `okta_app_user`. (#484)
3. Create `data_app_user_assignments` and `data_app_group_assignments` as replacement data sources for the users and groups assigned to an application.
    - `data_app_group_assignments` (#498) 
4. Remove the `users` and `groups` schema from the base apps, as well as all the handling code, in a breaking change. This due to the fact when the resources previously mentioned are used, this becomes completely redundant and are wasted API calls. (#495)

### New or Affected Resource(s)

- okta_app_user_assignments
- okta_app_group_assignments
- okta_app*

### Potential Terraform Configuration

TBD

### References

https://developer.okta.com/docs/reference/api/apps/#application-operations

**Comment by bogdanprodan-okta** [comment]
Hi @ymylei! Thanks for submitting this issue! I'll be removing these fields from the provider so they won't be present in the v4. There will be some additional breaking changes in v4 and I can't give the exact date, but I'm planning to do the release in late June, early July.

**Comment by ymylei** [comment]
Added a PR which is the removal of the associated users and groups handling from the app code, will also add a couple tasks to create replacement data sources for said data.

**Comment by ymylei** [comment]
Added PR for group assignments data source

**Comment by Omicron7** [comment]
I've got a few SAML apps with the `Everyone` group assigned. For us, thats approximately 700k users. Just planning a simple change on the one app is taking over 1000 requests to the API currently. I'm hoping this change will drastically reduce that.

**Comment by phi1ipp** [comment]
> Hi @ymylei! Thanks for submitting this issue! I'll be removing these fields from the provider so they won't be present in the v4. There will be some additional breaking changes in v4 and I can't give the exact date, but I'm planning to do the release in late June, early July.

Bogdan, what is ETA for v4 you mentioned above?

Thx

**Comment by bogdanprodan-okta** [comment]
Hi @phi1ipp! Currently I'm working on fixing the bugs in the provider to stabilise it before releasing v4
