### ISSUE TITLE
Rename okta_user_schema to okta_user_schema_property

### ISSUE THREAD

**Issue by thatguysimon** [okta/terraform-provider-okta#488]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The resource name `okta_user_schema` is somewhat misleading.
I would expect it to refer to the entire user schema, but instead it refers to just a single property of the schema, as explained by the resource's own description:

> Creates a User Schema property.
This resource allows you to create and configure a custom user schema property.

The resource name should be something like `okta_user_schema_property` to adhere to the [Okta Schemas API] terminology (https://developer.okta.com/docs/reference/api/schemas/#add-property-to-user-profile-schema).

### New or Affected Resource(s)

- okta_user_schema

**Comment by bogdanprodan-okta** [comment]
Hi, @thatguysimon! Thanks for submitting this issue! I'll deprecate the old resource name and use the new one to express the nature of the resource. Cheers!
