### ISSUE TITLE
Getting an error downloading latest version saying it doesn't exist yet I see the .zip file present

### ISSUE THREAD

**Issue by sarainsley** [okta/terraform-provider-okta#489]
registry.terraform.io/oktadeveloper/okta v3.11.1 does not have a
package available for your current platform, linux_amd64

my provider file is set to grab the latest version.

**Comment by noinarisak** [comment]
hmm. Do see the download binary in https://github.com/okta/terraform-provider-okta/releases/tag/v3.11.1 as you mention. I wonder if the push to registry.terraform.io for `linux_amd64` was corrupted. 

Wondering if the following thread could solve your issue with the state file. https://github.com/okta/terraform-provider-okta/issues/480#issuecomment-848256097.

**Comment by joshowen** [comment]
see https://github.com/okta/terraform-provider-okta/issues/480#issuecomment-847937483

**Comment by mikemuth** [comment]
Here is what I did to get around the problem, after the first apply the tfstate file was updated correctly.
cd .terraform//plugins/registry.terraform.io
cp -r okta/ oktadeveloper
