### ISSUE TITLE
Missing packages for darwin_amd64.

### ISSUE THREAD

**Issue by YoniMataraso** [okta/terraform-provider-okta#491]
I'm trying to upgrade my Okta terraform provider to the latest version 3.11.1 and when running terraform init --upgrade I'm getting the following error:

Error: Incompatible provider version

Provider registry.terraform.io/oktadeveloper/okta v3.11.1 does not have a
package available for your current platform, darwin_amd64.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.

I'm using Mac OS 11.3.1
Terraform version 0.15.4

**Comment by kostacasa** [comment]
Same for `linux_amd64`

**Comment by kenchrcum** [comment]
Same is happening for me on MacOS and on Linux machine where I get 
"Provider registry.terraform.io/oktadeveloper/okta v3.11.1 does not have a package available for your current platform, linux_amd64."

**Comment by bogdanprodan-okta** [comment]
Hi! Please refer to this comment https://github.com/okta/terraform-provider-okta/issues/480#issuecomment-854943860
