### ISSUE TITLE
okta_app_user_schema deleting the resource on change

### ISSUE THREAD

**Issue by karlsequeira** [okta/terraform-provider-okta#492]
When we update the values, its causing the resource to be deleted and removes the attribute from all the users assigned to the app. It should update in place
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_app_user_schema

### Terraform Configuration Files

```hcl
resource "okta_app_user_schema" "user_role" {
  app_id   =  data.okta_app.application.id
  master   = "PROFILE_MASTER"  
  index    = "user_role"      
  title    = "User Role"
  type     = "string"
     
  enum     = var.user_roles[*].const
  
  dynamic "one_of" {
    for_each = var.user_roles
    content {
      const =  one_of.value["const"]
      title =   one_of.value["title"]
    }
  }
  description = "User Role."
  required    = false
  permissions = "READ_WRITE"     
  depends_on = [
    okta_app_user_schema.firm_parent,
  ]     
}
```
### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi @karlsequeira! Thanks for submitting this issue! This issue was fixed in [this PR](https://github.com/okta/terraform-provider-okta/pull/531/files#diff-7c9c4d4f1759fd38cb9cb4e2bad5c7e137de9ec546f25b26cdb97f6d5619ddf8) and will be released by the end of a month. Cheers!
