### ISSUE TITLE
Saml hook configuration via okta terraform saml app

### ISSUE THREAD

**Issue by ksumitathenahealth** [okta/terraform-provider-okta#493]
I would like to have a configuration parameter for saml hook too in saml app properties. Currently Okta terraform doesn't have any way to link saml hook to saml app. I need to do that manually via login to Okta.

https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/app_saml

Can we have a parameter for the same so it would be easy to manage saml app completely via terraform.

**Comment by bogdanprodan-okta** [comment]
Hi @ksumitathenahealth! Assertion Inline Hook in SAML Settings now can be set via `inline_hook_id` argument. Closing this issue.
