### ISSUE TITLE
Create User with Imported Hashed Password - okta_user

### ISSUE THREAD

**Issue by vavra5** [okta/terraform-provider-okta#503]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Create User with Imported Hashed Password.  The new user is able to sign in immediately after activation with the specified password. This flow is common when migrating users from another data store in cases where we want to allow the users to retain their current passwords.

Supported Hashes:
BCRYPT, SHA-512, SHA-256, SHA-1 or MD5

### New or Affected Resource(s)

- okta_user

### Potential Terraform Configuration

```hcl
resource "okta_user" "example" {
  first_name         = "John"
  last_name          = "Smith"
  login              = "john.smith@example.com"
  email              = "john.smith@example.com"
  password_hash {
    algorithm        = "BCRYPT"
    workFactor       = 10
    salt             = "rwh3vH166HCH/NT9XV5FYu"
    value            = "qaMqvAPULkbiQzkTCWo5XDcvzpk8Tna"
  }
}

resource "okta_user" "example" {
  first_name         = "John"
  last_name          = "Smith"
  login              = "john.smith@example.com"
  email              = "john.smith@example.com"
  password_hash {
    algorithm        = "SHA-512"
    salt             = "TXlTYWx0"
    saltOrder        = "PREFIX"
    value            = "QrozP8a+KfoHu6mPFysxLoO5LMQsd2Fw6IclZUf8xQjetJOCGS93vm68h+VaFX0LHSiF/GxQkykq1vofmx6NGA=="
  }
}

resource "okta_user" "example" {
  first_name         = "John"
  last_name          = "Smith"
  login              = "john.smith@example.com"
  email              = "john.smith@example.com"
  password_hash {
    algorithm        = "SHA-256"
    salt             = "MPu13OmY"
    saltOrder        = "PREFIX"
    value            = "Gjxo7mxvvzQWa83ovhYRUH2dWUhC1N77Ntc56UfI4sY"
  }
}


resource "okta_user" "example" {
  first_name         = "John"
  last_name          = "Smith"
  login              = "john.smith@example.com"
  email              = "john.smith@example.com"
  password_hash {
    algorithm        = "SHA-1"
    salt             = "UEO3wsAsgzQ="
    saltOrder        = "POSTFIX"
    value            = "xjrauE6J6kbjcvMjWSSc+PsBBls="
  }
}

resource "okta_user" "example" {
  first_name         = "John"
  last_name          = "Smith"
  login              = "john.smith@example.com"
  email              = "john.smith@example.com"
  password_hash {
    algorithm        = "MD5"
    salt             = "TXlTYWx0"
    saltOrder        = "PREFIX"
    value            = "jqACjUUFXM1XE6NiLALAbA=="
  }
}

```

### References

https://developer.okta.com/docs/reference/api/users/#create-user-with-imported-hashed-password
https://developer.okta.com/docs/reference/api/users/#hashed-password-object

https://pkg.go.dev/github.com/okta/okta-sdk-golang/v2@v2.3.1/okta#PasswordCredential
https://pkg.go.dev/github.com/okta/okta-sdk-golang/v2@v2.3.1/okta#PasswordCredentialHash

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi @vavra5! Thanks for submitting this issue! I'll investigate it later next week. Cheers!

**Comment by vavra5** [comment]
Hi @bogdanprodan-okta. Perfect, thank you so much.
