### ISSUE TITLE
Unable to set App Logo for SAML apps

### ISSUE THREAD

**Issue by joshowen** [okta/terraform-provider-okta#506]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.14.10
Okta Provider built from https://github.com/okta/terraform-provider-okta/commit/56e5b6be7bfcd6a1ad54e9b8644664b4635e8403

### Affected Resource(s)

- okta_app_saml

### Terraform Configuration Files

```hcl
resource "okta_app_saml" "this" {
  label                    = var.label
  sso_url                  = "https://${var.fqdn}/saml2_auth/acs/"
  recipient                = "https://${var.fqdn}/saml2_auth/acs/"
  destination              = "https://${var.fqdn}/saml2_auth/acs/"
  audience                 = "https://${var.fqdn}/saml2_auth/acs/"
  subject_name_id_template = "$${user.userName}"
  subject_name_id_format   = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
  response_signed          = true
  assertion_signed         = true
  signature_algorithm      = "RSA_SHA256"
  digest_algorithm         = "SHA256"
  honor_force_authn        = true
  authn_context_class_ref  = "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"
  logo                     = var.logo_filename
  hide_web                 = false

```

### Debug Output

```
{
 "errorCode": "App instance has no login link to set logo for",
 "errorSummary": null,
 "errorLink": "App instance has no login link to set logo for",
 "errorId": "oaelxekIJNkQF6DVVUzjyORsQ",
 "errorCauses": []
}
```

### Expected Behavior

App logo should have been uploaded and created

### Actual Behavior

Error due to missing App login link which doesn't appear to be configurable.

### Steps to Reproduce

1. `terraform apply`

**Comment by gavinbunney** [comment]
@joshowen I was tracking down the same issue, and found out you need to enable the Early Access flag for app management in your Okta admin console:

![image](https://user-images.githubusercontent.com/409207/123017708-fb94b180-d381-11eb-91c9-81994f8151bc.png)

Looks like it's still an early feature. Enabling that allows app logos to upload successfully.

**Comment by joshowen** [comment]
@gavinbunney thanks for sharing that!  Unfortunately we already have it enabled.  

This was a new SAML application which was entirely configured via terraform, with no point/clicking in the admin console, and it didn't appear to create the "login link".  I couldn't find good documentation how to create a "login link", and we tried a few things in a fork of the provider but we couldn't come up with a fix.

**Comment by gavinbunney** [comment]
@joshowen I'm hitting this as well now :) Same error.. looks to only happen with SAML apps:

```
HTTP/2.0 400 Bad Request
{
 "errorCode": "App instance has no login link to set logo for",
 "errorSummary": null,
 "errorLink": "App instance has no login link to set logo for",
 "errorId": "oaeXR8mDW0GSPilhLhE7XTqbQ",
 "errorCauses": []
}
```

FWIW I had a look at the saml application object, and the app links are there ([mentions in the api docs](https://developer.okta.com/docs/reference/api/apps/#application-logo-operations) they are required):
> Note: You must have a valid login appLinks object to update the logo of an application.

```json
{
 ...
 "visibility": {
  "autoLaunch": false,
  "autoSubmitToolbar": false,
  "hide": {
   "iOS": false,
   "web": false
  },
  "appLinks": {
   "dev-XXXXXX_myapp_1_link": true
  }
 },
 ...
 "_links": {
  ...
  "appLinks": [
   {
    "name": "dev-XXXXXX_myapp_1_link",
    "href": "https://dev-XXXXX.okta.com/home/dev-XXXXXX_myapp_1/XXXXXX/XXXXX",
    "type": "text/html"
   }
  ],
  ...
 }
}
```

**Comment by gavinbunney** [comment]
This also happens for OIDC apps as well :( Only bookmark apps I've managed to successfully create from scratch and set a logo.

```hcl
resource "okta_app_oauth" "blender" {
  ... # cut for brevity
   logo = "${path.module}/../../assets/app.png"
}
```

```
HTTP/2.0 400 Bad Request
X-Okta-Request-Id: YNZeiP8g0f23eEUn-RMb-AAAB9w
{
 "errorCode": "App instance has no login link to set logo for",
 "errorSummary": null,
 "errorLink": "App instance has no login link to set logo for",
 "errorId": "oaeFYHIGbAfTqSks91vg3Q-tA",
 "errorCauses": []
}
```

**Comment by gavinbunney** [comment]
Finding this for applications even created via the web ui, the API for uploading logos fails. Posted question on Okta developer forums: https://devforum.okta.com/t/unable-to-upload-application-logo-for-oidc-and-saml-apps/14933

**Comment by bogdanprodan-okta** [comment]
Hi, @joshowen @gavinbunney The error you are getting in the response is from the Okta API itself, not the terraform itself. I'm not sure what is the root cause of this bug, but I'll ask the team responsible for this functionality.

**Comment by monde** [comment]
@joshowen @gavinbunney there is a known bug where the application icon is able to be updated in the Okta UI but not via the API. It is on the backlog of the responsible team. I will monitor the issue on our end and provide updates here.

Internal reference: [OKTA-373430](https://oktainc.atlassian.net/browse/OKTA-373430)

**Comment by fatbasstard** [comment]
FYI: Hitting the same issue when trying to add a logo to an existing OAuth app:

```{
 "errorCode": "App instance has no login link to set logo for",
 "errorSummary": null,
 "errorLink": "App instance has no login link to set logo for",
 "errorId": "oaeQHZaBLboSm6gpqLBvzcglA",
 "errorCauses": []
}
```

Too bad the error coming from TF does not show the actual API error (so needed to run in debug mode):

```
Error: failed to upload logo for OAuth application: The API returned an error: 
```

**Comment by fatbasstard** [comment]
Hi @monde,

Got any update on the issue by any chance?

**Comment by monde** [comment]
@fatbasstard the bug is still on the responsible team's backlog but has not been triaged yet. I'll reference this discussion to illustrate importance.

**Comment by reecewilliams7** [comment]
I also raised this yesterday via my company's Okta support channel, referencing the above internal ticket, and was told it's still under investigation with no ETA. But hopefully the more questions they receive regarding it, the higher priority it will get.

**Comment by guillaumelecerf** [comment]
Hi @monde,

Gentle ping to get an update on this issue please ;)

**Comment by sklarsa** [comment]
I'm also experiencing this issue and would love to see a resolution, thanks!

I'm using an `okta_app_oauth`, and this is working fine for bookmark apps

**Comment by monde** [comment]
@guillaumelecerf @sklarsa I'm looking to see when this will be prioritized by the corresponding internal feature team. I will post an update when I find out new information.

**Comment by miguelpuiggarcia** [comment]
Do we have any update on this one?
thanks!

**Comment by monde** [comment]
@miguelpuiggarcia I've pinged the feature team responsible for this part of the Okta API and am trying to get it into an upcoming sprint.

**Comment by fatbasstard** [comment]
Hi @monde,

Back to the "question of the month": Any update?

I've also created a case now (refering to this issue and the internal reference you've provided earlier) in the hope that it might speed up a bit

**Comment by monde** [comment]
> Hi @monde,
> 
> Back to the "question of the month": Any update?
> 
> I've also created a case now (refering to this issue and the internal reference you've provided earlier) in the hope that it might speed up a bit

@fatbasstard I'm using our internal process to escalate the issue with the responsible feature team.

**Comment by monde** [comment]
Okta internal escalation: [OKTA-439102](https://oktainc.atlassian.net/browse/OKTA-439102) /cc @fatbasstard @joshowen .

FWIW the terraform provider is calling this API endpoint for logo uploads [POST
/api/v1/apps/${applicationId}/logo](https://developer.okta.com/docs/reference/api/apps/#application-logo-operations)

**Comment by monde** [comment]
> Okta internal escalation: [OKTA-439102](https://oktainc.atlassian.net/browse/OKTA-439102) /cc @fatbasstard @joshowen .
> 
> FWIW the terraform provider is calling this API endpoint for logo uploads [POST /api/v1/apps/${applicationId}/logo](https://developer.okta.com/docs/reference/api/apps/#application-logo-operations)

The feature team responsible for that Okta API endpoint is now looking for a fix in its current sprint.

**Comment by virgofx** [comment]
I'm seeing a similar but different error. Was about to post new issue but saw this one. I also confirmed we don't have that EA feature listed any more in one of the workarounds above.

```
│ Error: failed to upload logo for OAuth application: the API returned an unknown error
```

**Comment by monde** [comment]
UPDATE: @fatbasstard @joshowen @virgofx @miguelpuiggarcia @sklarsa @guillaumelecerf @ReeceWilliams7 @gavinbunney 

The feature team responsible for the endpoint where app logos are uploaded to has fixed this bug. However, the fix won't be released to production until mid-November given the way releases are proved and promoted within Okta.

**Comment by fatbasstard** [comment]
Super, thanks for hunting people @monde !!

Can we keep this issue open until it is released? Not sure if this will be mentioned in the release notes from Okta, so that would be nice :D

**Comment by bogdanprodan-okta** [comment]
@fatbasstard yes, this issue will stay open until it's resolved.

**Comment by bogdanprodan-okta** [comment]
@fatbasstard @joshowen @virgofx @miguelpuiggarcia @sklarsa @guillaumelecerf @ReeceWilliams7 @gavinbunney I've tested logo on two different `*.oktapreview.com` orgs and it worked! Could you please try to set logos in your orgs?

**Comment by reecewilliams7** [comment]
> @fatbasstard @joshowen @virgofx @miguelpuiggarcia @sklarsa @guillaumelecerf @ReeceWilliams7 @gavinbunney I've tested logo on two different `*.oktapreview.com` orgs and it worked! Could you please try to set logos in your orgs?

Hi @bogdanprodan-okta - funnily enough I tested this on our preview instance yesterday and meant to update on here. Pleased to report it worked. Thanks for your help (and @monde) in getting this prioritised on your side - much appreciated!

**Comment by bogdanprodan-okta** [comment]
Thanks for everyone's patience. I'm closing this issue for now. Feel free to comment here or create another issue if necessary. Cheers!

**Comment by virgofx** [comment]
✔️ Just following up. The `logo` parameter worked for me for all use cases that were previously broken. Tested using client credentials and token API against tenant in `okta.com`. Thanks so much @bogdanprodan-okta

**Comment by fatbasstard** [comment]
Sweet, can confirm it works here too now! 🎉 

Another "manual" action removed, long live automation!
