### ISSUE TITLE
Behavioral properties support

### ISSUE THREAD

**Issue by YoniMataraso** [okta/terraform-provider-okta#507]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of today there is no support for Behavioral patterns when setting a sign on policy, in example in the console you can set what behavioral pattern should trigger an MFA challenge but there is no way to set those up in terraform.

### New or Affected Resource(s)

okta_policy_rule_signon

**Comment by bogdanprodan-okta** [comment]
It's going to added in #526
