### ISSUE TITLE
Error: failed to create SMS template

### ISSUE THREAD

**Issue by dethstrobe** [okta/terraform-provider-okta#508]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform: v1.0.0
okta provider: 3.10.1

### Affected Resource(s)

- okta_xxx

### Terraform Configuration Files

```hcl
resource "okta_template_sms" "sms2FA" {
  type = "SMS_VERIFY_CODE"
  template = "Your ${company} security code is $${code}."

  translations {
    language = "de"
    template = "Ihr Sicherheitscode für ${company} lautet $${code}."
  }

  translations {
    language = "en"
    template = "Your ${company} security code is $${code}."
  }

  translations {
    language = "es"
    template = "Tu código de seguridad de ${company} es $${code}."
  }

  translations {
    language = "fr"
    template = "Votre code de sécurité ${company} est $${code}."
  }

  translations {
    language = "it"
    template = "Il tuo codice di sicurezza per ${company} è $${code}."
  }

  translations {
    language = "ja"
    template = "お客様の${company}のセキュリティコードは$${code}です。"
  }

  translations {
    language = "nl_NL"
    template = "Je beveiligingscode voor ${company} is $${code}."
  }

  translations {
    language = "pt_BR"
    template = "O código de segurança do ${company} é $${code}."
  }

  translations {
    language = "zh_CN"
    template = "您的版${company}的安全码为$${code}。"
  }

}

```

### Debug Output

I'm sorry. I'm not super clear how to get better error logging. I'm running this from my local machine and not a server, if that makes any difference.

```
│ Error: failed to create SMS template: The API returned an error: Api validation failed: saveCustomSmsTemplate. Causes: errorSummary: Too many custom sms templates. Only one per type is supported.
│ 
│   with okta_template_sms.sms2FA,
│   on sms.tf line 1, in resource "okta_template_sms" "sms2FA":
│    1: resource "okta_template_sms" "sms2FA" {
```

### Expected Behavior

Upload the sms templates to okta

### Actual Behavior

Get an error

### Steps to Reproduce

1. `terraform apply`
2. `yes` to changes
3. Error

**Comment by bogdanprodan-okta** [comment]
Hi, @dethstrobe! Thanks for submitting this issue! I was a bit distracted away from the terraform provider for a while, but I'll try to fix this asap. Cheers!

**Comment by bogdanprodan-okta** [comment]
Hi, @dethstrobe! Are you still seeing this error? I've tested your code using the 3.11.1 provider version and everything works fine.
<img width="791" alt="Screenshot 2021-07-13 at 15 49 03" src="https://user-images.githubusercontent.com/71279414/125454452-1c0b845c-6830-4987-bb38-5461badb4c70.png">

**Comment by dethstrobe** [comment]
I think this might be a configuration issue with our QA OKTA environment. Because I'm not seeing this in our development environment or our production environment. I'll see if I can't find out what the difference is.

**Comment by dethstrobe** [comment]
I wasn't able to figure out what the problem is before I moved on from my employer. I hope someone else follows up on this problem. But I'm closing this since I won't be able to investigate it any longer.
