### ISSUE TITLE
Output app ID for okta_app_swa to be used okta_app_group_assignment

### ISSUE THREAD

**Issue by teaguecole** [okta/terraform-provider-okta#509]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The okta_app_swa resource has a variable named groups that suggests using okta_app_group_assignment for more flexibility.  One of the inputs for okta_app_groups_assignemnt is app_id.  For resources like okta_app_saml, it outputs the id for the application, which you can pass to okta_app_group_assignment, but for okta_app_swa, that is not possible as far as I am aware. 

### New or Affected Resource(s)

- okta_app_swa
- okta_app_group_assignment

### Potential Terraform Configuration

```hcl
resource "okta_app_swa" "example" {
<--- fill in variables --->
}

resource "okta_app_swa" {
    app_id = okta_app_swa.example.id <-- I want to do that, but its not listed as an attribute reference. 
}
```

### References

No

**Comment by teaguecole** [comment]
I am open to working on this. Just need to understand how  attributes get exposed.  Seems like something I can find out by example in other resources.

**Comment by bogdanprodan-okta** [comment]
Hi, @teaguecole! Thanks for submitting this issue! Yes, the documentation is a bit messy, but you can actually do this for all the resources. For example:
```
resource "okta_app_swa" "example" {
<--- fill in variables --->
}

data "okta_app" "data_app" {
  id = okta_app_swa.example.id
}
```

**Comment by teaguecole** [comment]
Oh, thanks @bogdanprodan-okta,.  Will close the issue then.
