### ISSUE TITLE
Cannot use okta provider with token and alias

### ISSUE THREAD

**Issue by iva-bashmat** [okta/terraform-provider-okta#528]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/google v3.66.1
+ provider registry.terraform.io/okta/okta v3.11.1
```

### Affected Resource(s)

- okta provider

### Terraform Configuration Files

```hcl
provider "okta" {
  alias = "test"

  org_name  = "some"
  base_url = "oktapreview.com"
  api_token = "VALID TOKEN"

}
```

### Expected Behavior

No error returned

### Actual Behavior
Error is returned:

```
Error: [ERROR] Error initializing the Okta SDK clients: when using AuthorizationMode 'PrivateKey', you must supply 'ClientId', 'Scopes', and 'PrivateKey'

  on <empty> line 0:
  (source code not available)
```

### Steps to Reproduce

In working code sample, add alias to okta provider
Run `terraform apply`

**Comment by monde** [comment]
Hi @iva-bashmat , thanks for the report. The error is coming from the configuration validator in the okta/okta-sdk-golang package https://github.com/okta/okta-sdk-golang/blob/master/okta/validator.go#L69-L84

I short term work around might be to provide meaningless values for the package. I will look into this situation. Also, @bogdanprodan-okta might have a suggestion as well.

**Comment by iva-bashmat** [comment]
@monde thanks for response!

Could you please provider more details on workaround? @bogdanprodan-okta any help is very appreciated. 

Thanks.

**Comment by bogdanprodan-okta** [comment]
Hi @iva-bashmat! I'll try to debug how the provider reading the config and see what can be fixed.

**Comment by iva-bashmat** [comment]
It looks like that you have to have one default provider (see example below). 


```
provider "okta" {
  # alias = "test_okta_preview"  

  org_name  = "test"
  base_url  = "oktapreview.com"
  api_token = "VALID TOKEN"
}

provider "okta" {
  alias = "test_okta"

  org_name  = "test"
  base_url  = "okta.com"
  api_token = "VALID TOKEN"
}
```

If I uncomment alias in first provider it throws error:
```
Error: [ERROR] Error initializing the Okta SDK clients: when using AuthorizationMode 'PrivateKey', you must supply 'ClientId', 'Scopes', and 'PrivateKey'

  on <empty> line 0:
  (source code not available)
```

I would prefer not to have default provider as it is easy to make a mistake: if provider will not be specified in any of resources it will get applied to default provider.

**Comment by noinarisak** [comment]
Hi @iva-bashmat, not sure if your use case is trying to manage different environments (ie, DEV, STG, PRD). If it is, you could use `terraform workspace` and place the okta environment variable within their separate `.tfvars` file and only have one `provider` reference in your HCL. Here is an example:

```bash
# I like to keep my config files in /config.

# stg.okta.tfvars
org_name  = "dev-302083"
base_url  = "oktapreview.com"
api_token = "xxxx"

# prd.okta.tfvars
org_name  = "dev-302083"
base_url  = "okta.com"
api_token = "xxxx"

# Example app.tf
variable "org_name" {}
variable "api_token" {}
variable "base_url" {}

terraform {
  required_providers {
    okta = {
      version = "~> 3.13"
      source  = "okta/okta"
    }
  }
  required_version = ">= 0.13"
}

provider "okta" {
  org_name  = var.org_name
  api_token = var.api_token
  base_url  = var.base_url
}

# Setup workspace 
$ terraform workspace new stg && terraform workspace new prd

# Set stage as the current context
$ terraform workspace select stg

# Confirm workspace context, output list of workspace and current context
$ terraform workspace list

# Execute regular terraform actions 
$ terraform init

$ terraform plan \
   -var-file=config/stg.okta.tfvars \
   -out=stg.okta.tfplan

$ terraform apply "stg.okta.tfplan"

# Switch to production 
$ terraform workspace select prd

# Repeat but reference prod.okta.tfvars this time.

```
