### ISSUE TITLE
Application User Schema union flag updated setting shown in GUI but it is not effective

### ISSUE THREAD

**Issue by kevin-chiu-dragon** [okta/terraform-provider-okta#533]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v0.12.31

### Affected Resource(s)

- okta_app_user_schema

### Terraform Configuration Files

```hcl
esource "okta_app_user_schema" "tfe_team_membership_prod" {
  app_id      = okta_app_saml.tfe_prod.id
  index       = local.tfe_saml_attribute_member_of_groups
  title       = "TFE Teams"
  type        = "array"
  array_type  = "string"
  description = "The TFE teams user belongs to"
  master      = "PROFILE_MASTER"
  union       = true
}
```

### Expected Behavior

`Combine values across groups` is set and SAML assertion will combine all the attributes of assigned group for an user as value

### Actual Behavior

`Combine values across groups` is set as shown in GUI, while SAML assertion does not combine all the attributes of assigned group for an user as value

### Steps to Reproduce

1. `union` was set to `false` and being applied
2. `Combine values across groups` was verified not set and not effective
3. `union` was then updated to `true` and being applied
4. `Combine values across groups` was verified being set when look at Okta GUI, while it's not effective when validate with SAML sign-in
5. In Okat GUI, the group priority was then changed to `Use Group Priority`, save it, then changed back to `Combine values across groups` and save again, then the setting was validated to be effective

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi @kevin-chiu-dragon! Thanks for submitting the issue! I'll investigate the root cause and will get back to you asap. Cheers!

**Comment by bogdanprodan-okta** [comment]
Hi @kevin-chiu-dragon! Is this bug can be reproduced purely via Okta UI? The reason I'm asking is that terraform can only influence Okta behavior via API.

**Comment by kevin-chiu-dragon** [comment]
> Hi @kevin-chiu-dragon! Is this bug can be reproduced purely via Okta UI? The reason I'm asking is that terraform can only influence Okta behavior via API.

Hi @bogdanprodan-okta , no I am not able to reproduce this purely via Okta UI.
And I just tested with both `okta_app_user_schema` and `okta_app_user_schema_property` with okta provider version 3.19.0 and issue persist. May this be re-opened?
