### ISSUE TITLE
Unexpected Breaking Change: `okta_group` Resource Unexpected User Removals

### ISSUE THREAD

**Issue by tgoodsell-tempus** [okta/terraform-provider-okta#539]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.15.3

### Affected Resource(s)

- `okta_group`

### Terraform Configuration Files

```hcl
resource "okta_group" "entitlement" {
  name        = "test"
  description = "test"
}
```

### Panic Output

N/A

### Expected Behavior

Okta groups we do not specify a user list for do not track the membership.

### Actual Behavior

A recent change (https://github.com/okta/terraform-provider-okta/pull/442) now causes all instances of `okta_group` to track membership. This is causing terraform to start planning / removing users from groups we did not expect would have membership managed by. 

### Steps to Reproduce

1. Create Okta group on 3.11.1
2. Apply, add members manually / outside of terraform
3. Update to 3.12.0
4. Plan, see plan attempt to remove members from the group

### References

- #0000

**Comment by tgoodsell-tempus** [comment]
While I understand that the long term (and probably better practice from terraform) is to use:
```
lifecycle {
    ignore_changes = [users]
  }
  ```

Since this is now required for the "old" behavior, that still counts as a breaking change in my book

**Comment by tgoodsell-tempus** [comment]
Based on https://github.com/okta/terraform-provider-okta/blob/63b82d9ba7648574ec9866b3a66ff48f3ac65c4e/okta/resource_okta_group.go#L115, I don't expect any changes to actually be performed, however the `plan` log will like to indicate it will clear out the group membership.

**Comment by tgoodsell-tempus** [comment]
> Based on
> 
> https://github.com/okta/terraform-provider-okta/blob/63b82d9ba7648574ec9866b3a66ff48f3ac65c4e/okta/resource_okta_group.go#L115
> , I don't expect any changes to actually be performed, however the `plan` log will like to indicate it will clear out the group membership.

Ya, I've validated that no changes are actually getting applied, however without the lifecycle ignore the plan will show continual removal of users. 

This probably can get classified as a standard bug, however since the output shown in the plan/apply process does indicate user change attempts, this is a bit of non trivial noise.

**Comment by bogdanprodan-okta** [comment]
Hi @tgoodsell-tempus! Thanks for submitting this issue! Yes, the bug was that `okta_group` didn't track the `users` if the field wasn't set, so the resource didn't work properly (and still doesn't for that matter, because it should remove the users from the group if `users` is empty). I will revert this change just to not break stuff. Currently, this field is deprecated and will be removed in the v4.0.0 version. Cheers!
