### ISSUE TITLE
Resource argument doesn't save [v3.12]

### ISSUE THREAD

**Issue by mbelang** [okta/terraform-provider-okta#540]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
terraform -v
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.50.0
+ provider registry.terraform.io/okta/okta v3.12.0

Your version of Terraform is out of date! The latest version
is 1.0.2. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

- okta_app_oauth attribute `wildcard_redirect`
- okta_app_user_schema_property attribute `permissions`

### Terraform Configuration Files

```hcl
resource "okta_app_oauth" "my_app" {
  label          = "lable"
  type           = "web"
  grant_types    = ["authorization_code"]
  redirect_uris  = ["https://rediret_url"]
  response_types = ["code"]
}
```
```hcl
resource "okta_app_user_schema_property" "my_prop" {
  for_each    = toset(local.datadog_app_ids)
  app_id      = okta_app_saml.id
  index       = "role"
  title       = "Role"
  type        = "string"
  description = "Description"
  enum        = ["admin", "standard", "readonly"]
  permissions = "READ_WRITE"
  required    = true

  one_of {
    const = "admin"
    title = "Admin"
  }
  one_of {
    const = "standard"
    title = "Standard"
  }
  one_of {
    const = "readonly"
    title = "Read Only"
  }

}
```
### Expected Behavior

After apply, I'm expecting  that the resources do not show up as modified.

### Actual Behavior

After migration to v3.12 version of the provider, the resources above always show as modified even if apply has been made.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply` again same output

```tf
  ~ resource "okta_app_oauth" "my_app" {
        id                         = "xxxxxxx"
        name                       = "oidc_client"
      + wildcard_redirect          = "DISABLED"
        # (22 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

```tf
  ~ resource "okta_app_user_schema_property" "my_prop" {
        id          = "xxxxxxx/role"
      + permissions = "READ_WRITE"
        # (13 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

```
### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi @mbelang! Thanks for submitting this issue!
1. As for `permissions = "READ_WRITE"`, seems like Okta API doesn't return this field for base properties anymore. I'll double-check again to be 100% sure.
2. I'll fix the `wildcard_redirect` and release a new version asap.

Cheers!

**Comment by rubenmromero** [comment]
Additionally to what has been reported, I am trying to set the the `wildcard_redirect` argument to `SUBDOMAIN"`, but after applying the modification the actual value stored in the TF state is this:

```
"wildcard_redirect": ""
```

So it seems that the `wildcard_redirect` argument is never set to a proper value (`"DISABLED"` or `"SUBDOMAIN"`) , and this is the reason why I guess it always tries to modify it.

**Comment by bogdanprodan-okta** [comment]
@rubenmromero `wildcard_redirect` is an [Early Access](https://developer.okta.com/docs/reference/api/apps/#settings-10) feature, that's probably why you can not set it.

**Comment by rubenmromero** [comment]
I see your point, @bogdanprodan-okta. The case is that I have tried to enable it in our Okta account going to Settings -> Features, but I wasn't able to find this feature in the list of early access features (neither in Okta preview). Any clue about how to enable this feature in Okta? Or maybe is there something that has to be done in Terraform? 🤔

**Comment by bogdanprodan-okta** [comment]
@rubenmromero I think you should request this feature vie Okta Helpdesk.
