### ISSUE TITLE
Provider v3.12.0 crashes with SegFault/nil pointer dereference

### ISSUE THREAD

**Issue by sklarsa** [okta/terraform-provider-okta#541]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
$ terraform version
Terraform v1.0.0
```

### Affected Resource(s)

- resource_okta_policy_rule_signon

### Terraform Configuration Files
Part of a larger module

```hcl
resource "okta_policy_signon" "this" {
  name            = var.customer_name
  status          = "ACTIVE"
  description     = var.customer_name
  groups_included = [okta_group.customer_group.id]
  priority        = 1

  lifecycle {
    ignore_changes = [priority]
  }
}

resource "okta_policy_rule_signon" "this" {
  policyid = okta_policy_signon.this.id
  name     = var.customer_name
  priority = 1

  lifecycle {
    ignore_changes = [priority]
  }
}
```

### Debug Output

https://gist.github.com/sklarsa/8284e188c63dcf98db23e6265f8cc1f0

### Panic Output

https://gist.github.com/sklarsa/7ade7c59f247fc6de47f6ae1b2174345

### Expected Behavior

`terraform plan` completes with exit code 0

### Actual Behavior

`terraform plan` fails

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Running inside a GitLab pipeline with docker executor on an ubuntu-based image

**Comment by sklarsa** [comment]
After some very preliminary investigation (and pardon my unfamiliarity with the library), could this be the issue?

Stack Trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf2fb1d]
goroutine 135 [running]:
github.com/okta/terraform-provider-okta/okta.resourcePolicySignOnRuleRead(0x13a5eb8, 0xc00096a960, 0xc000421600, 0x103c480, 0xc00019a540, 0xc000214470, 0xc0001c3908, 0x40e0f8)
	github.com/okta/terraform-provider-okta/okta/resource_okta_policy_rule_sign_on.go:163 +0x43d
...
```

https://github.com/okta/terraform-provider-okta/blob/63b82d9ba7648574ec9866b3a66ff48f3ac65c4e/okta/resource_okta_policy_rule_sign_on.go#L163

`rule` is instantiated by `getPolicyRule`: https://github.com/okta/terraform-provider-okta/blob/63b82d9ba7648574ec9866b3a66ff48f3ac65c4e/okta/policy_rule.go#L165

`getPolicyRule` returns a `PolicyRule` object, that has a `Conditions` attribute of type `*okta.PolicyRuleConditions`:  https://github.com/okta/terraform-provider-okta/blob/63b82d9ba7648574ec9866b3a66ff48f3ac65c4e/sdk/policy_rule.go#L24

https://github.com/okta/okta-sdk-golang/blob/a5b26e82ebd9fbeb45e04bcd002f2629fcb47660/okta/policyRuleConditions.go#L38

If the server never returns a `RiskLevel` (which I don't see in responses from the rules endpoint on my admin dashboard), it's possible that `Conditions.RiskLevel == nil`, although I'm not quite sure what the `omitempty` annotation does

FWIW I can reproduce this behavior on my local mac as well

**Comment by bogdanprodan-okta** [comment]
Hi @sklarsa! Thanks for submitting this issue! I guess you are right about nil pointer. I'll try to reproduce this and create the PR. This fix will be in 3.12.1 next week. Cheers!

**Comment by bogdanprodan-okta** [comment]
Hi @sklarsa! This is the JSON response for the sign-on policy rule:
```
{
    //...
    "conditions": {
        "people": {
            "users": {
                "exclude": []
            }
        },
        "network": {
            "connection": "ANYWHERE"
        },
        "authContext": {
            "authType": "ANY"
        },
        "risk": {
            "behaviors": []
        },
        "riskScore": {
            "level": "ANY"
        }
    },
//....
}
```
Sign-on policy rule:
<img width="552" alt="Screenshot 2021-07-23 at 13 03 42" src="https://user-images.githubusercontent.com/71279414/126767276-55a7c062-1147-4471-b5e3-8fc7f642df1c.png">

**Comment by sklarsa** [comment]
My policy rule modal looks different :-(

<img width="773" alt="Screen Shot 2021-07-23 at 9 37 23 AM" src="https://user-images.githubusercontent.com/1929541/126789933-555f383b-7b14-4fea-bf51-c8fa5978a750.png">
