### ISSUE TITLE
How to import `okta_group_memberships`?

### ISSUE THREAD

**Issue by ChristophShyper** [okta/terraform-provider-okta#546]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Now it's deprecated to define `users` list in `okta_group` resource and we should use `okta_group_memberships` 

```
╷
│ Warning: Argument is deprecated
│
│   with okta_group.aws_users_bip,
│   on main.tf line 65, in resource "okta_group" "aws_users_bip":
│   65:   users       = [for user in local.aws_users_bip : data.okta_user.sso_users[user].id]
│
│ The `users` field is now deprecated for the resource `okta_group`, please
│ replace all uses of this with: `okta_group_memberships`
│
│ (and 3 more similar warnings elsewhere)
╵
```

How to do it without without removing them from a group and adding them again with a new resource?
There is no information about importing a group membership to this new resource.
We have a lot of users and a lot of groups. Working around the world so there is no window for breaking and fixing.

When I try to use group id for import I'm getting:
```
╷
│ Error: resource okta_group_memberships doesn't support import
│
│
╵
```

### New or Affected Resource(s)

- okta_group
- okta_group_memberships

### Potential Terraform Configuration

Given
```hcl
locals {
  my_users = ["foo.bar@example.com", "bar.baz@example.com"]
}

data "okta_user" "sso_users" {
  for_each = local.my_users

  search {
    name  = "profile.login"
    value = each.value
  }
}
```

Before
```hcl
resource "okta_group" "my_group" {
  name        = "My Group"
  users       = [for user in local.my_users : data.okta_user.users[user].id]
}
```

After
```hcl
resource "okta_group" "my_group" {
  name        = "My Group"
}

resource "okta_group_memberships" "my_group" {
  group_id = okta_group.my_group.id
  users       = [for user in local.my_users : data.okta_user.users[user].id]
}
```

**Comment by bogdanprodan-okta** [comment]
Hi @ChristophShyper! I think you may try setting `ignore_changes` on users:
```
resource "okta_group" "my_group" {
  name        = "My Group"
  lifecycle {
    ignore_changes = [users]
  }
}
```

**Comment by ChristophShyper** [comment]
@bogdanprodan-okta What kind of API calls will `okta_group_memberships` do? 
Will it not cause errors when trying to add a user who is already member of the group?

**Comment by bogdanprodan-okta** [comment]
I've just tested it and it didn't raise any errors:
1. Before
```
resource "okta_group" "my_group" {
  name = "My Group 1"
  users = ["00uulbehbcE52T4Ef0h7"]
}
```
2. After
```
resource "okta_group" "my_group" {
  name = "My Group 1"
  lifecycle {
    ignore_changes = [
      users]
  }
}

resource "okta_group_memberships" "my_group" {
  group_id = okta_group.my_group.id
  users = [
    "00uulbehbcE52T4Ef0h7"]
}
```

**Comment by ChristophShyper** [comment]
Confirming it works without triggering any errors. 
But still it isn't elegant solution to leave `ignore_changes` everywhere and possibility to migrate between both solutions would be nice to have.

**Comment by bogdanprodan-okta** [comment]
@ChristophShyper yes, it's not the best solution, but removing the fields is considered to be a breaking change. All the deprecated fields will be removed in the 4.0.0 version, so `ignore_changes` won't be necessary anymore.

**Comment by ChristophShyper** [comment]
One remark, when `priority` is not defined for each `group` block in `okta_app_group_assignments` it creates update loops.

I have 3 groups defined, but only the first one doesn't trigger the changes:
```
  # okta_app_group_assignments.aws_clientvpn will be updated in-place
  ~ resource "okta_app_group_assignments" "my_app" {
        id     = "0oaaaaaaaaaaa"
        # (1 unchanged attribute hidden)

      - group {
          - id       = "00g1111111111" -> null
          - priority = 1 -> null
          - profile  = jsonencode({}) -> null
        }
      + group {
          + id = "00g1111111111"
        }
      - group {
          - id       = "00g22222222222" -> null
          - priority = 2 -> null
          - profile  = jsonencode({}) -> null
        }
      + group {
          + id = "00g22222222222"
        }
      + group {
          + priority = 1
          + profile  = jsonencode({})
        }
      + group {
          + priority = 2
          + profile  = jsonencode({})
        }
        # (1 unchanged block hidden)
    }
```

Setting `priority` for each block fixes the issue.

**Comment by bogdanprodan-okta** [comment]
Hi @ChristophShyper! Yeah, I will look into it. I'll either fix the `priority` field issue or make it required.

**Comment by posquit0** [comment]
Is there any update for optional `priority` field? Need to be optional for `okta_app_group_assignments`.

**Comment by ChristophShyper** [comment]
@bogdanprodan-okta I have another connected issue happening for the last few days.
My resource is defined as:
```hcl
resource "okta_app_group_assignments" "my_app" {
  app_id = okta_app_saml.my_app.id

  group {
    id       = okta_group.my_app_nonprod.id
    priority = 0
  }

  group {
    id       = okta_group.my_app_prod.id
    priority = 1
  }

  group {
    id       = okta_group.my_app_shared.id
    priority = 2
  }
}
```

And `terraform plan` is showing sometimes:
```
  # okta_app_group_assignments.aws_clientvpn will be updated in-place
  ~ resource "okta_app_group_assignments" "my_app" {
        id     = "0oa4kskdjskdjiYk0i7"
        # (1 unchanged attribute hidden)

      ~ group {
            id       = "00g4oykhoykhoykK80i7"
          ~ priority = 0 -> 1
            # (1 unchanged attribute hidden)
        }
        # (2 unchanged blocks hidden)
    }
```

Was something changed in `v3.13.13` around it? My priority is fixed but provider still is scrambling it randomly.

**Comment by bogdanprodan-okta** [comment]
I'm closing this issue for now. If you have any errors regarding the`okta_group_memberships` behavior, please create another issue. Thanks!
