### ISSUE TITLE
Okta Signon Policy Rule Fails on 3.12.1

### ISSUE THREAD

**Issue by Mrorya** [okta/terraform-provider-okta#553]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform 0.13.5
provider 3.12.1

### Affected Resource(s)

- okta_policy_rule_signon

### Terraform Configuration Files

```hcl
resource "okta_policy_rule_signon" "blank_deny_non_network" {
  policy_id          = okta_policy_signon.blank_signon_policy.id
  name               = "Deny non-network IP"
  status             = "ACTIVE"
  priority           = 1
  access             = "DENY"
  network_connection = "ZONE"
  network_excludes = [
    okta_network_zone.redacted.id,
  ]
  risc_level = "ANY"
}
```

### Expected Behavior

Expected provider to create a signon policy rule - this is actually the same signon policy we had used on 3.11.1 however we received this error upon upgrading as we modified the resource to utilize policy_id vs. policyid (deprecated) - which led to an attempt to destroy the old rule and create the new one (the old rules appear to still be there, the new rules have failed to be created)

### Actual Behavior

Policy rule failed to create - old policy rule that was setup with 3.11.1 still appears to be there - assuming that a successful creation would create duplicate rules that we could clean up via the UI (and that's ok... if we can get this workin!)
```
Error: failed to create sign-on policy rule: failed to create policy rule: The API returned an error: Api validation failed: conditions. Causes: errorSummary: conditions: Invalid condition type specified: riskScore.

  on signon_policies.tf line 8, in resource "okta_policy_rule_signon" "blank_deny_non_network":
   8: resource "okta_policy_rule_signon" "blank_deny_non_network" {
```

### References

- https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_rule_signon
- Did not find any other issues relating to this

**Comment by bogdanprodan-okta** [comment]
Hi @Mrorya! Thanks for submitting this issue! I tested the code you've provided and it works fine in my test org. Here is the screenshot of the rule:
<img width="568" alt="Screenshot 2021-07-29 at 22 40 37" src="https://user-images.githubusercontent.com/71279414/127555672-021be373-8594-4c37-8197-895b0669b66a.png">

**Comment by bogdanprodan-okta** [comment]
Hi @Mrorya! Thanks for submitting this issue! I tested the code you've provided and it works fine in my test org. Here the screenshot of the rule
![Uploading Screenshot 2021-07-29 at 22.40.37.png…]()

**Comment by Mrorya** [comment]
So, would this possibly be due to us not having a risk score/device trust implemented? Is this a feature flag gap on our Okta instance/part of OIE?
![image](https://user-images.githubusercontent.com/3143796/127556667-e34bf272-cb6b-4392-9482-95e94cf6a3ed.png)

fwiw - we got the same error when _not_ including the risc_score attribute - though clearly I see we can leave that out now :)

**Comment by bogdanprodan-okta** [comment]
@noinarisak ^^
P.S. API documentation [risk-score-condition-object](https://developer.okta.com/docs/reference/api/policy/#risk-score-condition-object)

**Comment by bogdanprodan-okta** [comment]
@Mrorya please read the [Note](https://developer.okta.com/docs/reference/api/policy/#device-condition-object)

**Comment by Mrorya** [comment]
> @Mrorya please read the [Note](https://developer.okta.com/docs/reference/api/policy/#device-condition-object)

Foiled by Okta Identity Engine again :(

Would this mean that this version of the TF provider is only compatible with OIE?

**Comment by bogdanprodan-okta** [comment]
From my side, I will make a possibility to set `risc_level` to an empty string, so it won't be present in the request. It will be available in 3.13.0 today.

**Comment by bogdanprodan-okta** [comment]
@Mrorya You also can enable the `RISK_SCORING` feature flag to make this feature work:
<img width="733" alt="Screenshot 2021-07-29 at 23 11 41" src="https://user-images.githubusercontent.com/71279414/127559405-bfdc3128-4d71-4836-82b4-138bafdce046.png">

**Comment by Mrorya** [comment]
> From my side, I will make a possibility to set `risc_level` to an empty string, so it won't be present in the request. It will be available in 3.13.0 today.

Awesome! Thank you for the quick update here - will save me from having to figure out how to get downgrading versions working ;)

> @Mrorya You also can enable the `RISK_SCORING` feature flag to make this feature work:
> <img alt="Screenshot 2021-07-29 at 23 11 41" width="733" src="https://user-images.githubusercontent.com/71279414/127559405-bfdc3128-4d71-4836-82b4-138bafdce046.png">

We'll reach out to support to request this as well. Thanks so much for the help today!

**Comment by bogdanprodan-okta** [comment]
@Mrorya my pleasure!

**Comment by Mrorya** [comment]
@bogdanprodan-okta is it worth reopening this, or should I create a new issue? despite the version upgrade + getting the risk_scoring flag turned on, we're still getting the same API response (although it does appear that the rules are being created?)


```
Error: failed to create sign-on policy rule: failed to create policy rule: The API returned an error: Api validation failed: conditions. Causes: errorSummary: conditions: Invalid condition type specified: riskScore.

  on signon_policies.tf line 62, in resource "okta_policy_rule_signon" "redacted_restrict_network":
  62: resource "okta_policy_rule_signon" "redacted_restrict_network" {
```

![image](https://user-images.githubusercontent.com/3143796/127575640-b36d72fa-af1e-41f4-a943-64be52a2c2f7.png)

Super confusing here, since the rules appear to be created, but the apply output is still the same? Saw the error whether we had risc_level set in the plan or not

**Comment by Mrorya** [comment]
scratch that - the rules actually did get removed with the apply - i'll create a new issue since this one's closed out - appreciate the help here
