### ISSUE TITLE
Okta Sign On Policy Rule Fails on 3.13.0

### ISSUE THREAD

**Issue by Mrorya** [okta/terraform-provider-okta#555]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment
### Terraform Version

terraform 0.13.5
provider 3.13.0

### Affected Resource(s)

- okta_policy_rule_signon

### Terraform Configuration Files

```hcl
resource "okta_policy_rule_signon" "blank_deny_non_network" {
  policy_id          = okta_policy_signon.blank_signon_policy.id
  name               = "Deny non-network IP"
  status             = "ACTIVE"
  priority           = 1
  access             = "DENY"
  network_connection = "ZONE"
  network_excludes = [
    okta_network_zone.redacted.id,
  ]
}
```

### Expected Behavior

Policy Rule Created from TF

### Actual Behavior

```
Error: failed to create sign-on policy rule: failed to create policy rule: The API returned an error: Api validation failed: conditions. Causes: errorSummary: conditions: Invalid condition type specified: riskScore.

  on signon_policies.tf line 8, in resource "okta_policy_rule_signon" "blank_deny_non_network":
   8: resource "okta_policy_rule_signon" "blank_deny_non_network" {
```

This triggers even if risc_level is not set. I could see in the plan after a fresh PR that the terraform plan includes the "risc_level" attribute set to ANY even if it was removed from the .tf files

### Important Factoids

- Removed the note about RISK_SCORING - actually got the flag turned on the wrong Okta tenant - so we're still reaching out to get that turned on that will likely resolve this (tho if others don't have the flag enabled, it will likely still error out so I'd imagine this bug is still valid :) )

### References

- https://github.com/okta/terraform-provider-okta/issues/553

**Comment by bogdanprodan-okta** [comment]
@Mrorya I've added a note [here](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_rule_signon#risc_level)

**Comment by bogdanprodan-okta** [comment]
As a workaround, `risc_level` can be set to an empty string, thus not won't be causing any errors.

**Comment by Mrorya** [comment]
> @Mrorya I've added a note [here](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_rule_signon#risc_level)

got it - this makes sense now - we had originally left it empty, but I realize in your docs that the correct method would be to define it as empty rather than just not declaring the attribute. thanks for the help here
