### ISSUE TITLE
Terraform 0.12.X pinned to Okta provider v3.11.0 after okta -> oktadeveloper swapover

### ISSUE THREAD

**Issue by Yohan460** [okta/terraform-provider-okta#557]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v0.12.29 but also duplicated on v0.12.31

### Affected Resource(s)
All

### Terraform Configuration Files

```json
{
  "provider": [
    {
      "oktadeveloper/okta": {
        "org_name": "dev",
        "base_url": "oktapreview.com",
        "api_token": "...",
        "version": "3.13.0"
      }
    }
  ]
}

```

### Debug Output
https://gist.github.com/Yohan460/22d92b3b73d4e85abec0ebe14398bc40

### Expected Behavior
It should automatically pull the v3.13.0 version

### Actual Behavior
It pulls the v3.11.0 version as latest

### Steps to Reproduce

1. `terraform init`

### Important Factoids
This issue is a result of the `okta` -> `oktadeveloper/okta` switch over.

When pulling the `okta` provider release info from hasicorp the following json blob is retrieved from https://registry.terraform.io/v1/providers/-/okta/versions
https://gist.github.com/Yohan460/284dbaa2a047808e1d48501d384ad56f

This blob has protocol 4.0 supported for all releases, indicating terraform v0.12.x support.

When we check the new `oktadeveloper/okta` provider release info from here https://registry.terraform.io/v1/providers/oktadeveloper/okta/versions the following json blob is returned
https://gist.github.com/Yohan460/6402598768dc80f88a0c85917ba9cd48

This blob only has the 5.0 protocol supported. Effectively dropping support for terraform v0.12.x from version 3.11.0 onward.

Is this intentional? or should we expect a fix for this?

**Comment by bogdanprodan-okta** [comment]
Hi @Yohan460!  Thanks for submitting this issue! Currently, we don't support the provider placed in `oktadeveloper/okta`. We just kept it in case someone still uses it, but it will be removed in the furure.

**Comment by ghost** [comment]
@bogdanprodan-okta sorry your comment does not make sense to me. Can you please check it out if it is saying what you are thinking?

Again:
```
 "id": "terraform-providers/okta",
 "moved_to": "oktadeveloper/okta",
 ```
 
 If you plan to remove oktadeveloper/okta why did you move it there?
 
 So what is the correct usage of okta provider 3.13.7 in TF version 0.12.31 ?

**Comment by ghost** [comment]
Oh I see so you actually moved from `terraform-providers/okta` -> `oktadeveloper/okta` -> `okta/okta`

However it does not work on tf 0.12.31 last working version of okta provider is 3.11.0

**Comment by bogdanprodan-okta** [comment]
@dusan-dragon yes, I'm afraid you have to use v0.13.x or newer in order to use that latest provider version. 
```
terraform {
  required_providers {
    okta = {
      source = "okta/okta"
      version = "3.13.8"
    }
  }
  required_version = ">= 0.13"
}
```
