### ISSUE TITLE
Error while installing oktadeveloper/okta v3.13.0: provider  registry.terraform.io/oktadeveloper/okta 3.13.0 is not available for linux_amd64

### ISSUE THREAD

**Issue by ilyinon** [okta/terraform-provider-okta#562]
I use Terraform 0.13.5 and try to update oktadeveloper/okta for any newer than 3.10.1
If I set 3.11 or newer I get the following error:

> Error: Failed to install provider
> 
> Error while installing oktadeveloper/okta v3.13.0: provider
> 
> registry.terraform.io/oktadeveloper/okta 3.13.0 is not available for linux_amd64

My version.tf is

> terraform {
>   required_providers {
>     okta = {
>       source = "oktadeveloper/okta"
>       version = "= 3.13.0"
>     }
>   }
>   required_version = ">= 0.13"
> }

Please advise what is the proper way to install oktadeveloper/okta newer than 3.10.1 ? Thanks!

**Comment by bogdanprodan-okta** [comment]
Hi @ilyinon! Please change `source = "oktadeveloper/okta"` to `source = "okta/okta"` and run `terraform state replace-provider oktadeveloper/okta okta/okta`

**Comment by ilyinon** [comment]
Thanks, @bogdanprodan-okta!
I will try it.

**Comment by ilyinon** [comment]
@bogdanprodan-okta 
It works for me.
Thank you very much!
