### ISSUE TITLE
Could not retrieve the list of available versions for provider okta/okta: no available releases match the given constraints ~> 3.11.1, ~> 3.13.0

### ISSUE THREAD

**Issue by mcrobbj** [okta/terraform-provider-okta#563]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.03

### Affected Resource(s)

- okta_xxx

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Updated to the latest release

### Actual Behavior

Could not retrieve the list of available versions for provider okta/okta: no available releases match the given constraints ~> 3.11.1, ~> 3.13.0

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi @mcrobbj! Thanks for submitting this issue! I've tried to roll back to 3.11.1 and that update to 3.13.0, and it worked just fine. Same when removing providers from the cache

**Comment by mcrobbj** [comment]
[image: image.png]
The doc isnt consisitient, plus:

terraform init -upgrade
[0m[1mUpgrading modules...[0m
- events in ..\..\..\..\modules\events
- groups in ..\..\..\..\modules\groups
- signon in ..\..\..\..\modules\signon
- social in ..\..\..\..\modules\social
- testAutomation in ..\..\..\..\modules\users\testAutomation[0m[1mInitializing
the backend...[0m[0m[1mInitializing provider plugins...[0m
- Finding hashicorp/azurerm versions matching "2.70.0"...
- Finding okta/okta versions matching "~> 3.11.1, 3.13.1"...
- Using previously-installed hashicorp/azurerm v2.70.0
[31m[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mFailed to query available provider
packages[0m
[31m│[0m [0m
[31m│[0m [0m[0mCould not retrieve the list of available versions for
provider okta/okta: no available releases match the given constraints ~>
3.11.1, 3.13.1
[31m╵[0m[0m

what provider details do you use and what is the syntax of the init?

**Comment by bogdanprodan-okta** [comment]
1. Execute `terraform init` with this config:
```
required_providers {
    okta = {
      source = "okta/okta"
      version = "3.11.1"
    }
  }
```
2. Execute `terraform init -upgrade` with this config:
```
required_providers {
    okta = {
      source = "okta/okta"
      version = ">= 3.11.1"
    }
  }
```
You can also try to manually remove 3.11.1 provider from the local dir`terra/.terraform/plugins/registry.terraform.io/okta/okta`

**Comment by bogdanprodan-okta** [comment]
Hi @mcrobbj! Is this still an issue or may I close this one?

**Comment by mcrobbj** [comment]
You can close, seems to be working with the latest version.
