### ISSUE TITLE
okta_app_oauth causing changes not shown in plan/apply

### ISSUE THREAD

**Issue by jdorothy** [okta/terraform-provider-okta#564]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.15.1

### Affected Resource(s)

- `okta_oauth_app` (and maybe `okta_app_group_assignment`)

### Terraform Configuration Files

```hcl
resource "okta_app_oauth" "app" {
  label = local.is_prod ? "App" : "App (${var.env})"
  type  = "web"
  grant_types = [
    "authorization_code",
    "implicit"
  ]
  redirect_uris = concat(var.redirect_urls, [
    "https://${var.env}.app.org/app"
  ])
  response_types = [
    "code",
    "id_token",
    "token"
  ]
  login_uri                 = var.app_url
  post_logout_redirect_uris = var.logout_redirect_uris
  hide_ios                  = false
  hide_web                  = false

  lifecycle {
    ignore_changes = [
      groups
    ]
  }
}

resource "okta_app_group_assignment" "users" {
  count    = length(var.user_groups)
  app_id   = okta_app_oauth.app.id
  group_id = element(var.user_groups, count.index)
}

resource "okta_app_group_assignment" "prime_users" {
  app_id   = okta_app_oauth.app.id
  group_id = data.okta_group.prime_users.id
}
```

### Expected Behavior

When running `terraform apply -target module.okta.okta_app_oauth.app`, we got the following expected output, which was to remove one of the `redirect_uris` that was no longer being used:

```
Terraform will perform the following actions:

  # module.okta.okta_app_oauth.app will be updated in-place
  ~ resource "okta_app_oauth" "app" {
        id                         = "redacted"
        name                       = "oidc_client"
      ~ redirect_uris              = [
          - "qa-api.qa-app.org"
            # (8 unchanged elements hidden)
        ]
        # (21 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Actual Behavior

What _actually_ happened is that the apply timed out after 20 minutes of waiting. The reason is that during the deploy the provider made so many API calls relating to users and groups that it caused our API key to be rate limited. Due to the rate limiting, the provider presumably could not complete the apply and was terminated by the timeout.

I opened a support ticket for this, and was directed to file this issue as part of the investigation. According to support, all the requests to ` /api/v1/apps/abcdefg/users` were GETs, presumably checking user group membership, while all of the group requests were removals from the app. I don't have the API call made for the group removal, but I'm assuming a DELETE to `
/api/v1/apps/${applicationId}/groups/${groupId}`?

The result was the removal of a large number of groups from the app in production.

### Steps to Reproduce

I'm not 100% sure what happened, but the steps seem to be:
* Create an OIDC app with groups assigned to it
* Run the code snippets above

**Comment by bogdanprodan-okta** [comment]
Hi @jdorothy! Thanks for submitting this issue! Yeah, That's definitely a bug. The problem is in the code and I'll try to fix it asap.

**Comment by jdorothy** [comment]
@bogdanprodan-okta looks great - thank you!

**Comment by jdorothy** [comment]
I just tested out the new release and I can confirm that this is fixed.

**Comment by bogdanprodan-okta** [comment]
I'm glad I could help!
