### ISSUE TITLE
Invalid Session for okta_app_oauth groups claim

### ISSUE THREAD

**Issue by kennyko** [okta/terraform-provider-okta#568]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v1.0.0

### Affected Resource(s)

- okta_app_oauth

### Terraform Configuration Files

```hcl
resource "okta_app_oauth" "test_app" {
  label          = "test_app"
  type           = "web"
  omit_secret    = true
  login_mode     = "DISABLED"
  grant_types    = ["authorization_code"]
  redirect_uris  = ["http://localhost/oauth2.idpresponse"]
  response_types = ["code"]

  lifecycle {
    ignore_changes = [groups]
  }
}
```

### Debug Output

Debug Gist https://gist.github.com/kennyko/b8bde9bf450218db034333c020be05cd

### Expected Behavior
Terraform should be able to apply the resource

### Actual Behavior
The okta provider errors out on The API returned an error: Invalid session

### Steps to Reproduce

1. Configure the Okta provider using an Oauth Application 
```
provider "okta" {
  org_name    = ""
  base_url    = "okta.com"
  client_id   =
  private_key =
  scopes = [
    "okta.apps.manage",
    "okta.clients.manage",
    "okta.factors.manage",
    "okta.groups.manage",
    "okta.idps.manage",
    "okta.policies.manage",
    "okta.roles.manage",
    "okta.templates.manage",
    "okta.users.manage",
  ]
}
```
2. `terraform apply`

### Important Factoids

Required to use client_id and private_key for provider

### References

- #468 Introduced groups claim

**Comment by bogdanprodan-okta** [comment]
Hi @kennyko! Thanks for submitting this issue! I'll try to reproduce it and get back to you asap. Cheers!

**Comment by kouk** [comment]
Seems like the `/api/v1/internal/apps/xyz/settings/oauth/idToken` endpoint being used to read group claims doesn't work with OAuth token, but works with SSWS token.
Maybe related: https://github.com/okta/terraform-provider-okta/issues/44

**Comment by JaseKirby** [comment]
I am still experiencing this exact same issue in the latest `v3.13.13` version of the provider and can confirm the source code for that release does not contain the fix in the pull request. I assume it will be in the next release whenever that happens???

**Comment by bogdanprodan-okta** [comment]
@JaseKirby new version is going to be released this week. It will include this fix.
