### ISSUE TITLE
okta_app_oauth unusable with a large user base

### ISSUE THREAD

**Issue by kensykora** [okta/terraform-provider-okta#572]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.4
on linux_amd64
okta provider 3.13.1

### Affected Resource(s)

- okta_app_oauth

### Terraform Configuration Files

```hcl

resource "okta_app_oauth" "cusprofile" {
  label       = "Customer Profile App"
  type        = "web"
  grant_types = ["authorization_code", "implicit"]
}

```

Running the command `terraform import okta_app_oauth.cusprofile <appid>` causes 2 things to happen:

1) Read the app from the API (expected)
2) Read ALL the user records associated with the app from the API

Because we have over 50,000 users associated with the app (Via a group assignment) this completely locks up terraform and ultimately fails. This makes the resource completely unusable for our purposes, as we aren't planning on managing those direct user associations (only group assignments).

I know the user / groups has been deprecated, but this is completely blocking us from using this resource type. Is there a workaround?

### Debug Output

I can supply debug output if requested, but you can observe the behavior on a smaller app/sample.

### Expected Behavior

App resource should not pull in users, or a way to opt out of this behavior

### Actual Behavior

App resource reads all users associated with the app and presumably tries to store them into state, which causes rate limiting unnecessarily, and for large user bases makes terraform state file unmanageable

### Steps to Reproduce

1. `terraform import okta_app_oauth.cusprofile <appid>`

**Comment by bogdanprodan-okta** [comment]
Hi @kensykora! Could you try setting this into your resource?
```
  lifecycle {
    ignore_changes = ["users"]
  }
```

**Comment by kensykora** [comment]
Something to consider as an implementation for the short term until the users and groups aspect of the apps goes away, could we consider a provider config option to ignore users and groups in the application resource types? something like

I'd take a crack at it but I've got the learning curve of go and terraform internals go get over. I might give it a shot.

```hcl
terraform {
  required_providers {
    okta = {
      source = "okta/okta"
      version = "~> 3.10"
    }
  }
}

# Configure the Okta Provider
provider "okta" {
  org_name  = "dev-123456"
  base_url  = "oktapreview.com"
  api_token = "xxxx"

  ignore_app_users_and_groups = true
}
```
