### ISSUE TITLE
Enabling Federation broker mode for SAML applications

### ISSUE THREAD

**Issue by venkatakanupuru** [okta/terraform-provider-okta#576]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

- okta_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

Hi Team,

For OIDC application resource "okta_app_oauth" for enabling federation broker mode,  implicit_assignment can be set.
For a SAML application resource "okta_app_saml" is there any attribute to set for enabling federation broker mode ?
For now we are enabling this manually by logging in and under the Sign on tab of the application >> Federation Broker Mode, this can be found.

Please Help.

Thank you
Venkata

**Comment by bogdanprodan-okta** [comment]
Hi @venkatakanupuru! Thanks for submitting this issue! Adding this feature depends on whether it's available via Okta API. I'll see what I can do and get back to you ASAP.

**Comment by ashwini-desai** [comment]
@bogdanprodan-okta : I see that `implicit_assignment` code of resource `okta_app_oauth` uses code to fetch application usrs and groups. The verified that same Okta APIs do return users and groups for SAML apps too. So I am thinking it would be about making this parameter available and re-using the same code behind that parameter.
If I am on the right track, can I attempt this?
