### ISSUE TITLE
Breaking change(s) in 3.13.3 prevent creating okta_user_schema_property resource

### ISSUE THREAD

**Issue by lucascantor** [okta/terraform-provider-okta#578]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform 1.0.4
on linux_amd64
okta provider 3.13.3
```

### Affected Resource(s)

- `okta_user_schema_property`

### Terraform Configuration Files

```hcl
resource "okta_user_schema_property" "manager_email" {
  index       = "managerEmail"
  title       = "Manager Email"
  description = "Workday user profile data"
  type        = "string"
  permissions = "READ_ONLY"
  master      = "PROFILE_MASTER"
}
```

### Debug Output

https://gist.github.com/lucascantor/3332e5b4e45f164d7bb263c2bd0778e1

### Panic Output

N/A

### Expected Behavior

Successful creation of resource okta_user_schema_property manager_email

### Actual Behavior

Okta API error indicating invalid schema:
```
Schema validation failed on the property pattern: value has incorrect type (found null, expected one of [string])
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

N/A

**Comment by bogdanprodan-okta** [comment]
Hi @lucascantor! Thanks for submitting this issue! I've already created a PR that should fix this issue.

**Comment by lucascantor** [comment]
@bogdanprodan-okta my pleasure, and thanks so much for the help!

It's the least I could do, given how valuable the Okta Terraform provider is to us.
