### ISSUE TITLE
Cant create or update a okta_app_oauth with token_endpoint_auth_method of "none"

### ISSUE THREAD

**Issue by mcrobbj** [okta/terraform-provider-okta#580]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform 1.0.3
okta prrovider: 3.1..1. 

### Affected Resource(s)

- okta_app_oauth

### Terraform Configuration Files

```hcl
resource "okta_app_oauth" "WebApp" {
  label                      = format("%s-%s", var.choices_prefix, "web")
  type                       = "web"
  grant_types                = ["authorization_code"] #, "implicit", "client_credentials"
  redirect_uris              = ["https://localhost", "https://www.thunderclient.io/oauth/callback"]
  response_types             = ["code"] # , "token","id_token"
  **token_endpoint_auth_method = "none"**
  consent_method             = "REQUIRED"
  omit_secret                = true
}
```
### Expected Behavior

It should create the app with a token endpoint auth method of none

### Actual Behavior

failed to update OAuth application: The API returned an error: Api validation failed: token_endpoint_auth_method. Causes: errorSummary: token_endpoint_auth_method: 'token_endpoint_auth_method' is invalid. Valid values: [client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt]

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi @mcrobbj! Thanks for submitting this issue! It's clearly a bug from the Okta API itself. According to the [official documentation](https://developer.okta.com/docs/reference/api/apps/#credentials), `none` is a valid value, so I'll try to request assistance from the team responsible for this functionality.

**Comment by monde** [comment]
hello @mcrobbj creating a web app which has a client_secret `none` can’t be used for `token_endpoint_auth_method` e.g. `client_secret_basic, client_secret_post, client_secret_jwt: Use one of these methods when the client has a client secret. Public clients (such as single-page and mobile apps) that can't protect a client secret must use none below.`
https://developer.okta.com/docs/reference/api/oidc/#client-authentication-methods

**Comment by mcrobbj** [comment]
If it helps it used to work, or certainly not error.
I have another resource that I created a few months ago with those settings.

**Comment by monde** [comment]
@mcrobbj is this something you can work around? I'll pass this issue along and see what other information I can gather.

**Comment by mcrobbj** [comment]
I need to check what happens when you create from the portal - it seems
from terraform and possibly the api if you dont specify anything the
default to client_secret_basic

John

**Comment by monde** [comment]
@mcrobbj I discussed this with the feature team that does federation and showed them your feedback. This was their response "we have had this check for a long time now, this is not something that changed recently. If the client's grantTypes contains authorization_code, we allow only browser and native clients to create the app with token_endpoint_auth_method=none. We do not have this restriction if the grantType is implicit."

Let me know if there is anything else @bogdanprodan-okta or myself can do for you.

**Comment by mcrobbj** [comment]
That's not the case. The Gant type is Auth code and doesn't allow none. If
I comment the token_endpoint_auth_method out it defaults to basic. I have
talked to support and confirmed this.

**Comment by bogdanprodan-okta** [comment]
Here is the JSON payload that is used to create this app:
```
{
 "credentials": {
  "oauthClient": {
   "autoKeyRotation": true,
   "token_endpoint_auth_method": "none"
  }
 },
 "label": "testAcc_AUTH",
 "name": "oidc_client",
 "settings": {
  "implicitAssignment": false,
  "oauthClient": {
   "application_type": "web",
   "consent_method": "REQUIRED",
   "grant_types": [
    "authorization_code"
   ],
   "idp_initiated_login": {
    "default_scope": [],
    "mode": "DISABLED"
   },
   "issuer_mode": "ORG_URL",
   "redirect_uris": [
    "https://localhost",
    "https://www.thunderclient.io/oauth/callback"
   ],
   "response_types": [
    "code"
   ],
   "wildcard_redirect": "DISABLED"
  }
 },
 "signOnMode": "OPENID_CONNECT",
 "visibility": {
  "autoSubmitToolbar": false,
  "hide": {
   "iOS": true,
   "web": true
  }
 }
}
```
And it's clear that `grant_types` contains `authorization_code`

**Comment by bellis-ai** [comment]
so... Is this just left broken or something? Literally impossible to create an SPA App integration with this if I can't select "none" when setting an auth code flow.

The official documentation **explicitly** says to set this to none.
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_oauth#token_endpoint_auth_method

> token_endpoint_auth_method - (Optional) Requested authentication method for the token endpoint. It can be set to "none", "client_secret_post", "client_secret_basic", "client_secret_jwt", "private_key_jwt". To enable PKCE, set this to "none".

**Comment by bellis-ai** [comment]
> so... Is this just left broken or something? Literally impossible to create an SPA App integration with this if I can't select "none" when setting an auth code flow.
> 
> The official documentation **explicitly** says to set this to none. https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_oauth#token_endpoint_auth_method
> 
> > token_endpoint_auth_method - (Optional) Requested authentication method for the token endpoint. It can be set to "none", "client_secret_post", "client_secret_basic", "client_secret_jwt", "private_key_jwt". To enable PKCE, set this to "none".

Nvm, looks like you just need to make sure the type is "browser" if you're going to make an SPA. It would help if the values of the "type" variable were made a bit more distinct in the documentation ("browser" vs "web"... really???)

**Comment by monde** [comment]
I’ll update the docs, no problem!

**Comment by monde** [comment]
https://developer.okta.com/docs/reference/api/apps/#add-oauth-2-0-client-application

Parameter | Description | DataType
-- | -- | --
application_type | The type of client application | web, native, browser, or service


Application Type | Valid Grant Type | Requirements
-- | -- | --
browser | authorization_code, implicit |  
native | authorization_code, implicit, password, refresh_token | Must have at least authorization_code
service | client_credentials | Works with OAuth 2.0 flow (not OpenID Connect)
web | authorization_code, implicit, refresh_token | Must have at least authorization_code

**Comment by richard-collette-precisely** [comment]
Additional facts, should you have landed here.

* You cannot set "token_endpoint_auth_method": "none", after initial application creation.  You will get an incessant error about client_credentials grant not being valid with "token_endpoint_auth_method": "none", event though "client_credentials" appears nowhere in your configuration.  The provider will not delete and recreate.  You must delete the application and re-create it in two steps.  Seems like a bug, but it's 11:30pm EST and I'm just too worn to go through the steps of filing a bug.
* resfresh_token is a valid grant type with application type = "browser" and having "token_endpoint_auth_method": "none"
* When   "token_endpoint_auth_method" is "none autoKeyRotation must be set to false
* When tokenEndpointAuthMethod === "none" pkce must be required.

The provider needs a major overhaul to do validations, etc.
