### ISSUE TITLE
TFlint ruleset okta

### ISSUE THREAD

**Issue by vazuev** [okta/terraform-provider-okta#581]
Hi!
There is nothing to check TF code for Okta.
We have found one restriction for the name attribute of okta_auth_server_policy. It should be no longer than 50 characters.
I have written TF linter for this [https://github.com/vazuev/tflint-ruleset-okta](https://github.com/vazuev/tflint-ruleset-okta).
I would like to write more linter rules, but there is no information about other restrictions or code conventions.
I'd like you to help me find information or show me directions to look for.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

- okta_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @vazuev! Thanks for submitting this issue! I think you can find some of the restrictions in the [official documentation](https://developer.okta.com/docs/reference/core-okta-api/), however, I think some of the validation info might be missing from there.
