### ISSUE TITLE
okta_group_schema_property possible feature?

### ISSUE THREAD

**Issue by mihzaidi** [okta/terraform-provider-okta#582]
Hello,
     I just wanted to ask if there's any way we can also add the addition of group custom attributes as well. The api to do so is documented [here](https://developer.okta.com/docs/reference/api/schemas/#add-property-to-group-profile-schema). If I by mistake missed this capability in another object, I apologize, and please point me in the right direction.

thank you!

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

- okta_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi @mihzaidi! Thanks for submitting this issue! We have plans to add it to the official SDK first and then implement it here.

**Comment by bogdanprodan-okta** [comment]
Hi @mihzaidi! It's currently in progress to be added to Okta OpenAPI specification and then to the SDK. It's going to be added to the provider's next version.

**Comment by CodyDunlap** [comment]
Would this also include the ability to set values for Group Level attributes for specific application assignments in a group? We can do this through the console but I haven't discovered a way to do this via Terraform as of yet.
