### ISSUE TITLE
"Cannot unmarshal array into Go value of type okta.NetworkZone" while creating dynamic zone

### ISSUE THREAD

**Issue by patoarvizu** [okta/terraform-provider-okta#584]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v0.13.5

### Affected Resource(s)

- [`okta_network_zone`](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/network_zone)

### Terraform Configuration Files

```hcl
resource okta_network_zone tor {
  name               = "TOR Blocker"
  type               = "DYNAMIC"
  usage              = "BLOCKLIST"
  dynamic_proxy_type = "TorAnonymizer"
}
```

### Debug Output

https://gist.github.com/patoarvizu/134d058b633e26c076f2551cc0b35b83

### Expected Behavior

The dynamic zone is created.

### Actual Behavior

Terraform returns the error `Error: failed to get network zone: json: cannot unmarshal array into Go value of type okta.NetworkZone`. The zone does get created in Okta itself, but is not in the Terraform state, so attempting to run `terraform apply` again would result in Terraform trying to create the resource again.

This seems to only happen for network zones of `type = "DYNAMIC"`.

### Steps to Reproduce

1. Create resource as described above (it's almost identical to the example in the provider documentation, [here](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/network_zone#example-usage---dynamic-tor-blocker)).
1. Run `terraform apply`.

### Important Factoids

This is on an Okta Developer/Starter plan.

### References

- #0000

**Comment by patoarvizu** [comment]
Actually, I was also able to reproduce this with a network zone of `type = "IP"`. The strange thing in this case is that the resource definition was exactly identical to one I was successfully able to create just a few minutes before it started failing.

**Comment by bogdanprodan-okta** [comment]
Hi @patoarvizu! Thanks for submitting this issue! I'll try to reproduce the bug and get back to you asap.

**Comment by patoarvizu** [comment]
Thanks!! 👍

**Comment by bogdanprodan-okta** [comment]
@patoarvizu will be released today.
