### ISSUE TITLE
okta_app_oauth ignoring users still calls API to download all of them

### ISSUE THREAD

**Issue by dziedrius** [okta/terraform-provider-okta#585]
I have a resource
```
resource "okta_app_oauth" "web" {
  // stuff

  lifecycle {
    ignore_changes = [users]
  }
}
```
and I've noticed, that in production plan runs very long time, so I've attached proxy to see what is going on and it seems that it tries to download all the users for that app:
![image](https://user-images.githubusercontent.com/772162/129541195-8ef70c95-4514-45bc-a948-e68d4fc2c9cf.png)
which in our case can be tens of thousands and 99% of them are assigned to app through group, not directly.

Usually that ends with rate limit warning emails, which is not a fun thing to have in prod.

May be it would be possible to skip calling API for stuff that is in ignore_changes?

I'm using 13.3.1 version (it seems couple minor versions are released after, but none of them are tackling this issue, I could test with newer version if that would help).

**Comment by bogdanprodan-okta** [comment]
Hi @dziedrius! Thanks for submitting this issue! I'll work on this issue this week so the fix can be released asap.

**Comment by dziedrius** [comment]
@bogdanprodan-okta, thanks a lot for quick reaction.

**Comment by kensykora** [comment]
This is related to #572

**Comment by kensykora** [comment]
@bogdanprodan-okta Any update on this? Anxiously awaiting a method for managing Okta apps without user associations

**Comment by bogdanprodan-okta** [comment]
Hi @kensykora! I was on vacation but I will start to work on this issue on Monday since it's affecting a lot of clients.

**Comment by bryantbiggs** [comment]
hi @bogdanprodan-okta any update on this?

**Comment by bogdanprodan-okta** [comment]
Hi @bryantbiggs! Yes, I'm currently working to make all the `groups` and `users` 'importable'/'readable' if the property is explicitly set in the terraform file.

**Comment by bryantbiggs** [comment]
thank you!
