### ISSUE TITLE
3.15.3 Plugin Crash

### ISSUE THREAD

**Issue by kennyko** [okta/terraform-provider-okta#591]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.0

### Affected Resource(s)

- okta_template_sms.sms_templates

### Terraform Configuration Files

```hcl
resource "okta_template_sms" "example" {
  type = "SMS_VERIFY_CODE"
  template = "Your $${org.name} code is: $${code}"
  translations {
    language = "en"
    template = "Your $${org.name} code is: $${code}"
  }
}
```

### Panic Output

https://gist.github.com/kennyko/f58f29ae14310bef5b1443ac9a586368

### Expected Behavior

Plugin should not have crashed

### Actual Behavior

Plugin crashed

### Steps to Reproduce

1. `terraform plan`

### References

- #589 
https://github.com/okta/terraform-provider-okta/commit/a88a3bda8dc8eb1a5b65cfc3c7a0e833b2ae6fa7#diff-81b49f2eb02ef300c3c9a993658bfa80df64dcfc516367ee942d02d1acf68e0bR74

**Comment by bogdanprodan-okta** [comment]
Hi @kennyko! Thanks for submitting this issue! I was able to reproduce it by using this script:
```
resource "okta_template_sms" "example" {
  type = "SMS_VERIFY_CODE"
  template = "Your $${org.name} code is: $${code}"
}
```
I'll release the fix shortly.
