### ISSUE TITLE
Skipping users import for okta_group

### ISSUE THREAD

**Issue by phi1ipp** [okta/terraform-provider-okta#595]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It'd be helpful, if users can be skipped when importing okta_group. 

We have a group in our environment, whose members are manage with a rule, and it does not require terraform management. If I want to create an application, which uses this group for assignment, I have to have it in the state, and I need to import it. This group has ~10k users in it. There is no practical value to import all of them. 

Is there a way to avoid doing that, which I'm missing?

I put my current config below for the reference

### New or Affected Resource(s)

- okta_group

### Potential Terraform Configuration

```hcl
 resource "okta_group" "eua_users" {
  name        = "EUA Users"
  description = "EUA Users"

  lifecycle {
    ignore_changes = [
      users
    ]
  }
}

resource "okta_app_oauth" "cat" {
  label                      = "xxx - xxx"
  type                       = "web"
  grant_types                = ["authorization_code"]
  redirect_uris              = ["http://localhost:8080/authorization-code/callback"]
  post_logout_redirect_uris  = ["http://localhost:8080"]
  response_types             = ["code"]
}

resource "okta_app_group_assignments" "cbt" {
  app_id   = okta_app_oauth.cbt.id

  group {
    id = okta_group.eua_users.id
    priority = 1
  }
}
```

**Comment by bogdanprodan-okta** [comment]
Hi @phi1ipp! Thanks for submitting this issue! I'm currently working on adding "skip" functionality for apps and groups.
