### ISSUE TITLE
okta_auth_server_policy_rule misses token lifetimes during import

### ISSUE THREAD

**Issue by phi1ipp** [okta/terraform-provider-okta#598]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.5

### Affected Resource(s)

- okta_auth_server_policy_rule

### Terraform Configuration Files

```hcl
resource "okta_auth_server" "cbt" {
  name        = "ITSP - CBT"
  description = "ITSP - CBT"
  audiences   = ["itsp_cbt"]
  issuer_mode = "CUSTOM_URL"
}

resource "okta_auth_server_policy" "cbt" {
  auth_server_id   = okta_auth_server.cbt.id
  status           = "ACTIVE"
  name             = "ITSP - CBT"
  description      = "ITSP - CBT"
  priority         = 1
  client_whitelist = [okta_app_oauth.cbt.id]
}

data "okta_group" "all" {
  name = "Everyone"
}

resource "okta_auth_server_policy_rule" "a30m" {
  auth_server_id       = okta_auth_server.cbt.id
  policy_id            = okta_auth_server_policy.cbt.id
  status               = "ACTIVE"
  name                 = "access 30 mins"
  priority             = 1
  grant_type_whitelist = ["authorization_code"]
  scope_whitelist      = ["*"]
  access_token_lifetime_minutes = 30
  group_whitelist      = ["EVERYONE"]
}
```

### Debug Output

https://gist.github.com/phi1ipp/0b7d5071a0ffe74ad147f89e30ad5beb

### Expected Behavior

Import should capture tokens lifetime from the rule, so that plan do not reflect changes to be introduced for the resource

### Actual Behavior

`terraform plan` suggests to add properties to a rule
```
  # okta_auth_server_policy_rule.a30m will be updated in-place
  ~ resource "okta_auth_server_policy_rule" "a30m" {
      + access_token_lifetime_minutes = 30
        id                            = "0pr9gsli9qWw6PqvH297"
        name                          = "access 30 mins"
      + refresh_token_window_minutes  = 10080
        # (11 unchanged attributes hidden)
    }
```

### Steps to Reproduce

1. `terraform import okta_auth_server_policy_rule.xxx <guid>`
2. `terraform plan`

**Comment by bogdanprodan-okta** [comment]
Hi @phi1ipp! Thanks for submitting this issue! I'll try to reproduce it and fix it.

**Comment by phi1ipp** [comment]
Hi @bogdanprodan-okta , I submitted PR https://github.com/okta/terraform-provider-okta/pull/600 for you to check if it's enough for the issue to be fixed.

Please review
