### ISSUE TITLE
okta_app_user_schema_property fails during create for newly created application

### ISSUE THREAD

**Issue by phi1ipp** [okta/terraform-provider-okta#604]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.5
on darwin_amd64
\+ provider registry.terraform.io/okta/okta v3.13.3
### Affected Resource(s)

- okta_app_user_schema_property

### Terraform Configuration Files

```hcl
resource "okta_app_saml" "hdt-haa" {
  label                    = "HDT - HAA"
  sso_url                  = "redacted"
  recipient                = "redacted"
  destination              = "redacted"
  audience                 = "redacted"
  subject_name_id_template = "$${user.userName}"
  subject_name_id_format   = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
  response_signed          = true
  signature_algorithm      = "RSA_SHA256"
  digest_algorithm         = "SHA256"
  honor_force_authn        = false
  authn_context_class_ref  = "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"

  attribute_statements {
	    type         = "EXPRESSION"
	    name         = "UID"
	    namespace    = "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
	    values       = [ "String.toUpperCase(user.login)" ]
  }
  attribute_statements {
	    type         = "EXPRESSION"
	    name         = "cn"
	    namespace    = "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
	    values       = [ "user.firstName + \" \" + user.lastName" ]
  }
  attribute_statements {
	    type         = "EXPRESSION"
	    name         = "cmsRoles"
	    namespace    = "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
	    values       = [ "user.cmsRoles" ]
  }
  attribute_statements {
	    type         = "EXPRESSION"
	    name         = "cmsSubmitterID"
	    namespace    = "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
	    values       = [ "appuser.CMSSubmitterID" ]
  }

  groups = [ data.okta_group.hdt-users.id, data.okta_group.hdt-testers.id ]

  lifecycle {
    ignore_changes = [
      groups
    ]
  }
}

resource "okta_app_user_schema_property" "cms-submitter-id" {
  app_id      = okta_app_saml.hdt-haa.id
  index       = "CMSSubmitterID"
  title       = "CMS Submitter ID"
  type        = "string"
  description = "CMS Submitter ID"
  required    = false
  permissions = "READ_ONLY"
  master      = "PROFILE_MASTER"
  scope       = "SELF"
}
```

### Debug Output

https://gist.github.com/phi1ipp/fd13b6251fd5f6b32703a08517006232
### Expected Behavior

A new attribute should be created in the application profile

### Actual Behavior

Error: failed to update custom app user schema property: the API returned an error: Schema is invalid., x-okta-request-id=YSAsTHKngEDCNdF-srD-eAAABZk
### Steps to Reproduce

1. configure new application first
2. `terraform apply`
3. then add application user profile attribute into config
4. `terraform apply`

**Comment by phi1ipp** [comment]
I think the problem is that schema property being sent to Okta doesn't match API description

https://developer.okta.com/docs/reference/api/schemas/#app-user-profile-schema-property-object

Things like:
* pattern
* permissions
are not listed among allowed ones

**Comment by phi1ipp** [comment]
I tried to run the following request and it worked fine
```
curl --location --request POST 'https://redacted.okta.com/api/v1/meta/schemas/apps/0oa9hwqkfuPZqlrcx297/default' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: SSWS redacted' \
--data-raw '{
	"definitions": {
		"custom": {
            "id": "#custom",
            "type": "object",
            "properties": {
                "SubmitterID": {
                    "title": "CMS Submitter ID",
                    "description": "HETS/HDT requirement",
                    "type": "string",
                    "scope": "SELF",
                    "master": {
                        "type": "PROFILE_MASTER"
                    }
                }
            },
            "required": []
		}
	}
}'
```

What is interesting, when I do addition of an attribute in the browser, I see a different API calls happening:
`PUT /api/v1/apps/user/types/oty9hwqkg2jV3K8DU297/schemas/sch9hwqkg1WhXfiOp297` with the following body
```json
{"id":"sch9hwqkg1WhXfiOp297","displayName":"Custom","name":"custom","schema":{"properties":{"CMSSubmitterID":{"title":"CMS Submitter ID","type":"string","description":"CMS Submitter ID","required":false,"settings":{},"scope":"SELF"}}}}
```
where `oty9hwqkg2jV3K8DU297` is coming from `GET /api/v1/apps/user/types` for the selected application.

**Comment by phi1ipp** [comment]
@bogdanprodan-okta , it seems that a fix maybe as easy as this PR https://github.com/okta/terraform-provider-okta/pull/606

Please have a look, when you have a chance

**Comment by monde** [comment]
@phi1ipp, fyi @bogdanprodan-okta will be back from vacation 8/30/2021

**Comment by phi1ipp** [comment]
ty @monde , I hope he is not the only one working on this produce :)

**Comment by bogdanprodan-okta** [comment]
> ty @monde , I hope he is not the only one working on this produce :)

![benedict-cumberbatch-endgame](https://user-images.githubusercontent.com/71279414/131229180-f23f549b-85db-4c9c-9eb8-7b8915d368af.gif)
