### ISSUE TITLE
app_links_json for okta_app_auto_login apps

### ISSUE THREAD

**Issue by dsalaza4** [okta/terraform-provider-okta#608]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating `okta_app_auto_login` apps with `preconfigured_app`, sometimes
you want to pass some link configurations for the app.
An `app_links_json` attribute similar to the one existing in `okta_app_saml` would allow to pass such configurations.

### New or Affected Resource(s)

1. `okta_app_auto_login`

### Potential Terraform Configuration

```
resource "okta_app_auto_login" "apps" {
  label               = "google test"
  status              = "ACTIVE"
  preconfigured_app   = "google"
  app_settings_json = jsonencode({
    afwOnly = false
    domain = "test.com"
  })
  app_links_json = jsonencode({
    accounts = false
    calendar = false
    drive = false
    keep = false
    mail = true
    sites = false
  })
}
```

### References

1. https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/app_auto_login
2. https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/app_saml#app_links_json

**Comment by dsalaza4** [comment]
Would it be better to support both `app_settings_json` and `app_links_json` for all applications?

**Comment by monde** [comment]
@dsalaza4, fyi @bogdanprodan-okta will be back from vacation 8/30/2021

**Comment by bogdanprodan-okta** [comment]
@dsalaza4 `app_links_json` gonna be available for all the apps. As for `app_settings_json`, I need to add it where it's applicable because some of the apps already have it or the settings themselves have names (like `button_selector` or `username_selector` is app settings in `okta_app_three_field`)
