### ISSUE TITLE
okta_app_user_schema_property fails update from okta_app_user_schema

### ISSUE THREAD

**Issue by elena-rico** [okta/terraform-provider-okta#610]
Unable to upgrade resource from `okta_app_user_schema` to `okta_app_user_schema_property` 

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.5
on darwin_amd64

### Affected Resource(s)

-  okta_app_user_schema_property

### Terraform Configuration Files

```
data "okta_app" "ldap" {
  label = var.ldap_base_dn
}
```

```
resource "okta_app_user_schema_property" "role" {
  app_id        = data.okta_app.ldap.id
  index         = "role"
  title         = "Roles"
  external_name = "role"
  type          = "array"
  array_type    = "string"
  description   = "The roles assigned to the user"
  master        = "PROFILE_MASTER"
  permissions   = "READ_ONLY"
}
```

```
resource "okta_profile_mapping" "one_id_ldap" {
  source_id          = data.okta_app.ldap.id
  target_id          = data.okta_user_profile_mapping_source.user.id
  delete_when_absent = true

  mappings {
    id          = okta_user_schema.roles.index
    expression  = "appuser.${okta_app_user_schema_property.role.index}"
    push_status = "PUSH"
  }
}
```

### Debug Output

Terraform plan [output](https://github.com/elena-rico/tf-logs/blob/main/terraform.plan)
 [Logs](https://github.com/elena-rico/tf-logs/blob/main/error.log)

### Expected Behavior

Application property is created with the updated.

### Actual Behavior

Tries to delete the property that was created with the deprecated resource and fails.

### Steps to Reproduce

1. configure the application
2. Create a property with `okta_app_user_schema`
2. `terraform apply`
3. update the property to use `okta_app_user_schema_property` as suggested by the warnings
4. `terraform plan` shows new resources(role) to be created and the old one to be deleted.
5. `terraform apply`

### References

- #0000

**Comment by dathdev** [comment]
I'd recommend removing the resource from the tfstate by running `terraform state rm okta_app_user_schema.role` and import the new resource with `terraform import okta_app_user_schema_property.role <user type id>/<role index>`. Then you should be able to `terraform apply`

**Comment by monde** [comment]
@elena-rico, fyi @bogdanprodan-okta will be back from vacation 8/30/2021

**Comment by bogdanprodan-okta** [comment]
Hi @elena-rico! Try using this as a reference https://github.com/okta/terraform-provider-okta/issues/587#issuecomment-899650911

**Comment by elena-rico** [comment]
Thanks @bogdanprodan-okta this strategy works. Do you mind explaining why updating a deprecated resource requires this many manual steps? This unfortunately break our automation, usually replacing deprecated arguments is backwards compatible.

**Comment by bogdanprodan-okta** [comment]
@elena-rico I think the problem is that the `terraform state mv` command only allows moving items within the same type. The steps I've provided were based on [this tutorial](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/migrating-between-renamed-resources).

**Comment by bogdanprodan-okta** [comment]
If there are no more questions I'm closing this issue. If you have any other concerns, feel free to write them here. Cheers!

**Comment by elena-rico** [comment]
Thanks, @bogdanprodan-okta 

> If there are no more questions I'm closing this issue. If you have any other concerns, feel free to write them here. Cheers!
