### ISSUE TITLE
terraform-provider-okta_v3.13.6 plugin did not respond

### ISSUE THREAD

**Issue by elena-rico** [okta/terraform-provider-okta#614]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.4  
on Ubuntu 20.04.2

### Affected Resource(s)

- terraform-provider-okta_v3.13.6 plugin

### Terraform Configuration Files

```hcl

  required_providers {
    okta = {
      source  = "okta/okta"
      version = "~> 3.13.5"
    }
  }

provider "okta" {
  org_name         = var.okta_org_name
  base_url         = var.okta_base_url
  api_token        = local.customer_okta_api_token
  max_api_capacity = 70
}
```

### Panic Output

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
details.
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-okta_v3.13.6 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xbddec9]

goroutine 331 [running]:
github.com/okta/terraform-provider-okta/okta/internal/transport.(*GovernedTransport).postRequestHook(0xc000519aa0, 0xeb61bd, 0x3, 0xc0001baa9f, 0x27, 0x0)
	github.com/okta/terraform-provider-okta/okta/internal/transport/governed_transport.go:77 +0x29
github.com/okta/terraform-provider-okta/okta/internal/transport.(*GovernedTransport).RoundTrip(0xc000519aa0, 0xc000cbae00, 0xc000519aa0, 0x0, 0x0)
	github.com/okta/terraform-provider-okta/okta/internal/transport/governed_transport.go:50 +0x137
net/http.send(0xc000cbae00, 0xfda480, 0xc000519aa0, 0x0, 0x0, 0x0, 0xc0006f6068, 0xc0005f2dc8, 0x1, 0x0)
	net/http/client.go:251 +0x454
net/http.(*Client).send(0xc0005197d0, 0xc000cbae00, 0x0, 0x0, 0x0, 0xc0006f6068, 0x0, 0x1, 0x48)
	net/http/client.go:175 +0xff
net/http.(*Client).do(0xc0005197d0, 0xc000cbae00, 0x0, 0x0, 0x0)
	net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
	net/http/client.go:585
github.com/okta/okta-sdk-golang/v2/okta.(*RequestExecutor).doWithRetries.func2(0xc000c5b710, 0xc000c5b710)
	github.com/okta/okta-sdk-golang/v2@v2.6.0/okta/requestExecutor.go:329 +0x152
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer(0xc0005f2ce8, 0xfe4518, 0xc000c5b710, 0x0, 0xfe99b8, 0xc0006f6058, 0x0, 0x0)
	github.com/cenkalti/backoff/v4@v4.1.1/retry.go:55 +0x102
github.com/cenkalti/backoff/v4.RetryNotify(...)
	github.com/cenkalti/backoff/v4@v4.1.1/retry.go:34
github.com/cenkalti/backoff/v4.Retry(...)
	github.com/cenkalti/backoff/v4@v4.1.1/retry.go:28
github.com/okta/okta-sdk-golang/v2/okta.(*RequestExecutor).doWithRetries(0xc000522420, 0xfedc20, 0xc000657a70, 0xc000cbad00, 0x3, 0xc0001baa88, 0x17)
	github.com/okta/okta-sdk-golang/v2@v2.6.0/okta/requestExecutor.go:356 +0x1ac
github.com/okta/okta-sdk-golang/v2/okta.(*RequestExecutor).Do(0xc000522420, 0xfedc20, 0xc000657a70, 0xc000cbad00, 0xd3a300, 0xc000526540, 0x0, 0xc000cbad00, 0x0)
	github.com/okta/okta-sdk-golang/v2@v2.6.0/okta/requestExecutor.go:264 +0x1be
github.com/okta/okta-sdk-golang/v2/okta.(*Response).Next(0xc000b4bad0, 0xfedc20, 0xc000657a70, 0xd3a300, 0xc000526540, 0xc8, 0x0, 0x0)
	github.com/okta/okta-sdk-golang/v2@v2.6.0/okta/requestExecutor.go:399 +0xea
github.com/okta/terraform-provider-okta/okta.listApplicationUsers(0xfedc20, 0xc000657a70, 0xc000192300, 0xc0005ea900, 0x14, 0xc00005e401, 0xc000657a70, 0xc0005f3118, 0x4978a6, 0xe46240)
	github.com/okta/terraform-provider-okta/okta/app.go:448 +0x225
github.com/okta/terraform-provider-okta/okta.listAppUsersAndGroups(0xfedc20, 0xc000657a70, 0xc000192300, 0xc0005ea900, 0x14, 0xc000526528, 0xfedc20, 0xc000657a70, 0x0, 0x0, ...)
	github.com/okta/terraform-provider-okta/okta/app.go:598 +0x65
github.com/okta/terraform-provider-okta/okta.syncGroupsAndUsers(0xfedbe8, 0xc000523b00, 0xc0005ea900, 0x14, 0xc00042e680, 0xd98d60, 0xc00044f040, 0x0, 0x0)
	github.com/okta/terraform-provider-okta/okta/app.go:473 +0x116
github.com/okta/terraform-provider-okta/okta.resourceAppOAuthRead(0xfedbe8, 0xc000523b00, 0xc00042e680, 0xd98d60, 0xc00044f040, 0xc0004a3490, 0xc000557908, 0x40e0f8)
	github.com/okta/terraform-provider-okta/okta/resource_okta_app_oauth.go:521 +0x1905
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0000b2ee0, 0xfedb78, 0xc00060a140, 0xc00042e680, 0xd98d60, 0xc00044f040, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:347 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0000b2ee0, 0xfedb78, 0xc00060a140, 0xc00031c850, 0xd98d60, 0xc00044f040, 0xc000783398, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0003c6a08, 0xfedb78, 0xc00060a140, 0xc00060a180, 0xc00060a140, 0x40b965, 0xe3f6c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc000419a00, 0xfedc20, 0xc00060a140, 0xc000523500, 0xc000419a00, 0xc0003e54d0, 0xc0001e0ba0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0xe75280, 0xc000419a00, 0xfedc20, 0xc0003e54d0, 0xc0005234a0, 0x0, 0xfedc20, 0xc0003e54d0, 0xc0006d6000, 0x3d4)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000200c40, 0xff61b8, 0xc00008af00, 0xc000293400, 0xc0003e4540, 0x14ce7b0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000200c40, 0xff61b8, 0xc00008af00, 0xc000293400, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000042550, 0xc000200c40, 0xff61b8, 0xc00008af00, 0xc000293400)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-okta_v3.13.6 plugin crashed!

### Expected Behavior

Plan: 1 to add, 0 to change, 1 to destroy.

### Actual Behavior

panic

### Steps to Reproduce

1. `terraform plan`

### References

- #0000

**Comment by monde** [comment]
Hello @elena-rico we released 3.13.7 of the okta provider. It specifically addressed the panic you've experienced in the 3.13.6 version. Let me know how 3.13.7 works for you https://registry.terraform.io/providers/okta/okta/latest
