### ISSUE TITLE
Add exclusion of users in `okta_group_rule`.

### ISSUE THREAD

**Issue by Omicron7** [okta/terraform-provider-okta#620]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add the ability to exclude users in the `okta_group_rule` resource. The [Okta API](https://developer.okta.com/docs/reference/api/groups/#create-group-rule) supports this as `conditions.people.users.exclude` property. We currently use this feature in a few group rules and are unable to import them into terraform because of the missing feature.

### New or Affected Resource(s)

- okta_group_rule

### Potential Terraform Configuration

```hcl
  name   = "All Larrys"
  status = "ACTIVE"
  group_assignments = [
    okta_group.all_larrys.id
  ]
  expression_type  = "urn:okta:expression:1.0"
  expression_value = "String.startsWith(user.firstName,\"Larry\")"
  users_excluded = [
    okta_user.the_one_larry.id
  ]
```

### References

- [Okta API Rule object](https://developer.okta.com/docs/reference/api/groups/#rule-object)

**Comment by bogdanprodan-okta** [comment]
Hi @Omicron7! Thanks for submitting this issue! I'll create a corresponding PR to add this functionality asap.
