### ISSUE TITLE
Provider crashes when importing a SAML application

### ISSUE THREAD

**Issue by MatthewJDavis** [okta/terraform-provider-okta#625]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/okta/okta v3.13.8

### Affected Resource(s)

okta_app_saml

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    okta = {
      source = "okta/okta"
      version = "~> 3.10"
    }
  }
}

provider "okta" {
  org_name  = var.org_name
  base_url  = var.base_url
}

resource "okta_app_saml" "ca_app" {
  # (resource arguments)
}
```

### Debug Output

[Crash report](https://gist.github.com/MatthewJDavis/5f17aeeead6b4ea81ef2949c7498e324)

Let me know if you would like the full debug - will need to remove some information from it.

--->

### Expected Behavior

SAML application is imported and can be manged via Terraform.

### Actual Behavior

Error: Plugin did not respond
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details

....

Error: The terraform-provider-okta_v3.13.8 plugin crashed!

### Steps to Reproduce

1. `terraform import okta_app_saml.example 012345ABC`

### Important Factoids

- Can import applications OK with okta_app_oauth.
- Can create SAML applications all OK.
- Error when importing SAML app
- Same error also with version v3.13.7

**Comment by bogdanprodan-okta** [comment]
Hi @MatthewJDavis! Thanks for submitting this issue! As a temp solution, you can put either admin or user notes in this app (is that's possible) so you don't get this error. I'll fix this asap and create the corresponding PR. Cheers!
<img width="391" alt="Screenshot 2021-09-01 at 23 02 53" src="https://user-images.githubusercontent.com/71279414/131736491-69e5dda9-4d33-4851-976d-fb1a65b18489.png">

**Comment by MatthewJDavis** [comment]
Hello @bogdanprodan-okta,
Thanks for that quick response - the workaround of adding **Application notes for admins** worked and I was able to import the SAML app to terraform successfully.
