### ISSUE TITLE
Failure to execute plan / refresh

### ISSUE THREAD

**Issue by raulbarreto-delivion** [okta/terraform-provider-okta#635]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.5

### Affected Resource(s)

- okta_profile_mapping

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

https://gist.github.com/raulbarreto-delivion/55dac04fd09e1bb68333de41edb6475e

### Panic Output

Not generated

### Expected Behavior

Not Crashing

### Actual Behavior

Crashing

### Steps to Reproduce

1. `terraform apply`
2. `terraform init`
3. `terraform refresh`

### Important Factoids

Running on an instance with 8GB.

The target_id was changed, generating this error.

**Comment by goerge** [comment]
@raulbarreto-delivion I bet you prefer to switch "Expected" and "Actual" ;-)

**Comment by raulbarreto-delivion** [comment]
Thanks @goerge

**Comment by bogdanprodan-okta** [comment]
Hi, @raulbarreto-delivion! Thanks for submitting this issue! Could you also include example of the resource you are trying to create?

**Comment by shk3bq4d** [comment]
@raulbarreto-delivion : were you updating ? I also had a crash trying to update from 3.12.1 to 3.13.8.

I then tried (and failed) to upgrade from 3.12.1 to 3.13.7

but had success to go from minor to minor 3.12.1 (terraform 1.0.4), 3.13.0 (terraform 1.0.6), 3.13.1, 3.13.2, 3.13.3, 3.13.4, 3.13.5, 3.13.6, 3.13.7, 3.13.8

**Comment by raulbarreto-delivion** [comment]
@bogdanprodan-okta Here is an example:

```hcl
data "okta_user_profile_mapping_source" "user" {}

resource "okta_profile_mapping" "client-mappings" {
  source_id = data.okta_user_profile_mapping_source.user.id
  target_id = okta_app_oauth.client.id

  dynamic "mappings" {
    for_each = var.custom_claims
    content {
      id          = okta_app_user_schema.client-attribute[mappings.key].index
      expression  = "user.${mappings.key}"
      push_status = "PUSH"
    }
  }

  mappings {
    id          = okta_app_user_schema.client-group-filter-prefix.index
    expression  = "\"${var.group_filter_prefix}\""
    push_status = "PUSH"
  }
}
```

**Comment by raulbarreto-delivion** [comment]
@shk3bq4d The resource was created on an older version of the module but the change was on the newest version. I am not sure if this caused the issue.

**Comment by shk3bq4d** [comment]
> @shk3bq4d The resource was created on an older version of the module but the change was on the newest version. I am not sure if this caused the issue.

Same for me, while I guess it would be nice to fix the underlying issue, at least you probably have a workaround that I explained in my previous comment (update through all minor versions), should you need it.

**Comment by ahmei0** [comment]
@raulbarreto-delivion I need a quick help - I'm creating custom property and mapping but when I run terraform destroy I get error that property cannot be deleted. This is because it doesn't remove the mapping first. Any idea how to force terraform to remove mapping first before attempting to delete property?
