### ISSUE TITLE
SAML App Provisioning API Integration

### ISSUE THREAD

**Issue by drewmullen** [okta/terraform-provider-okta#636]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great if we could pass API credentials directly to the saml app configuration. currently this is a manual step:

![image](https://user-images.githubusercontent.com/3812162/132686727-c3abbeb6-7d98-43d3-aa52-7a685db1f512.png)

### New or Affected Resource(s)

- okta_app_saml

### Potential Terraform Configuration

```hcl
api_integration {
  access_key = ""
  secret_key  = ""
}
```

_secret_key_ should be marked as `sensitive`

### References

Seems like this is a known limitation but i didnt see a FR for it so /shrug: https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_saml#features

**Comment by bogdanprodan-okta** [comment]
Hi @drewmullen! Thanks for submitting this issue! I'll check whether all the operations are available via public API. If they are I'll add them to the provider. Cheers!

**Comment by drewmullen** [comment]
@bogdanprodan-okta thanks for your update! were you, by chance, able to find an API endpoint? we're looking at making the commands via automation while waiting until the tf provider to be updated - if possible

**Comment by exitcode0** [comment]
looks like this is the endpoint a resource would need to use here
[set-default-provisioning-connection-for-application](https://developer.okta.com/docs/reference/api/apps/#set-default-provisioning-connection-for-application)
The edge case here would be applications that use Oauth for provisioning, this would still require manual click-ops setup in the okta admin console

**Comment by jackson-theisen** [comment]
> looks like this is the endpoint a resource would need to use here [set-default-provisioning-connection-for-application](https://developer.okta.com/docs/reference/api/apps/#set-default-provisioning-connection-for-application) The edge case here would be applications that use Oauth for provisioning, this would still require manual click-ops setup in the okta admin console

The API call you've linked takes a [provisioning-connection-profile-object](https://developer.okta.com/docs/reference/api/apps/#provisioning-connection-profile-object). Per the docs - currently, only token based authentication is supported. So this still leaves a gap for more than just apps w/ OAuth provisioning. Particularly, I am most interested in automated app provisioning/API integration (i.e. programmatic mechanism to set/rotate AWS access keys/secrets)  for federated AWS applications.

**Comment by joerg** [comment]
Seems like there is an API endpoint available now: https://developer.okta.com/docs/reference/api/apps/#application-provisioning-connection-operations . It would be nice if we could have a resource for this. @bogdanprodan-okta

**Comment by monde** [comment]
Reopening to see if we can use the recently published API endpoint to implement this behavior.

Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-544413

**Comment by msvechla** [comment]
we are also highly interested in provisioning API support, to configure our org2org setup

**Comment by msvechla** [comment]
I started an implementation draft here: https://github.com/okta/terraform-provider-okta/pull/1362

This creates an in-line resource block on the `okta_app_saml`, as currently, the only supported app in the okta-sdk is the org2org application:

```hcl
  default_provisioning_connection {
      activate = true
      profile {
          auth_scheme = "TOKEN"
          token = "helloworld"
      }
  }
```

What do you think? Does it make sense to implement it like this, or should we move this to a separate resource instead?

**Comment by MrYeske-SA** [comment]
Wonder if plans have changed six (6) months later?
