### ISSUE TITLE
okta_app_saml.app_settings_json should exist as its own resource

### ISSUE THREAD

**Issue by drewmullen** [okta/terraform-provider-okta#637]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`okta_app_saml` has a circular dependency to `aws_iam_saml_provider`.

1. `okta_app_saml` creates the saml metadata
2. `aws_iam_saml_provider` requires the metadata
3. `okta_app_saml.app_settings_json` requires the arn for the idp from step 2

Proposed solution requires a new resource and a deprecation to existing resource attribute

### New or Affected Resource(s)

- okta_app_saml
- okta_app_saml_app_settings

### Potential Terraform Configuration

```hcl
resource "okta_app_saml_app_settings" "example" {
      saml_app_id = ""
      settings = jsonencode(
            appFilter           = "okta2"
            awsEnvironmentType  = "aws.amazon"
            groupFilter         = "aws_(?{{accountid}}\\d+)_(?{{role}}[a-zA-Z0-9+=,.@\\-_]+)"
            identityProviderArn = "arn:aws:iam::<redacted>:saml-provider/Okta"
            joinAllRoles        = false
            loginURL            = "https://console.aws.amazon.com/ec2/home"
            roleValuePattern    = "arn:aws:iam::$${accountid}:saml-provider/OKTA,arn:aws:iam::$${accountid}:role/$${role}"
            sessionDuration     = 3600
            useGroupMapping     = false
      )
}
```

## Example usage:
```hcl
resource "okta_app_saml" "example" {
   ...
}

resource "aws_iam_saml_provider" "example" {
  name                   = "okta2"
  saml_metadata_document = okta_app_saml.example.metadata
}

resource "okta_app_saml_app_settings" "example" {
      saml_app_id = okta_app_saml.example.id
      settings = jsonencode(
            appFilter           = "okta2"
            awsEnvironmentType  = "aws.amazon"
            groupFilter         = "aws_(?{{accountid}}\\d+)_(?{{role}}[a-zA-Z0-9+=,.@\\-_]+)"
            identityProviderArn = "arn:aws:iam::<redacted>:saml-provider/Okta"
            joinAllRoles        = false
            loginURL            = "https://console.aws.amazon.com/ec2/home"
            roleValuePattern    = "arn:aws:iam::$${accountid}:saml-provider/OKTA,arn:aws:iam::$${accountid}:role/$${role}"
            sessionDuration     = 3600
            useGroupMapping     = false
      )
}
```

**Comment by bogdanprodan-okta** [comment]
Hi @drewmullen! Thanks for submitting this issue! This seems like a reasonable thing to add. I'll start to work on this asap. Cheers!
