### ISSUE TITLE
group create fails on read (sometimes)

### ISSUE THREAD

**Issue by jeffg-archive** [okta/terraform-provider-okta#647]
When doing a standard okta_group create operation, we experienced an issue yesterday where the group create API call succeeded, but the group read that happens immediately after the create (internal to the provider implementation) fails with a 404.

We get a valid groupID and can observe the group is created in the Okta org, but the GET call fails with 404.

We suspect this is a timing issue, perhaps Okta has some eventual consistency where the read-immediately-after-create is failing for a brief time, just long enough for the provider to fail.

The problem is that this leaves the resource create in a failed state from terraform's standpoint, marking the resource as tainted and on the next run it destroys and recreates. The only workaround is to manually remove from state, and manually import the okta_group using the group ID.

Perhaps you could add a couple retries with a delay for group read-after-create in case this problem occurs, so that the read has a chance to succeed if the first attempt with a valid ID 404s?

**Comment by bogdanprodan-okta** [comment]
Hi @jeffg-hpe! Thanks for submitting this issue! I'll add a retry mechanism for this resource (like I did for several others), so it will retry GET request several times after resource creation.
