### ISSUE TITLE
okta_group_role with target_app_list always re-created at plan/apply

### ISSUE THREAD

**Issue by phi1ipp** [okta/terraform-provider-okta#648]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.6
on darwin_amd64
\+ provider registry.terraform.io/okta/okta v3.13.10
### Affected Resource(s)

- okta_group_role

### Terraform Configuration Files

```hcl
data "okta_app_saml" "hcqis-cloudbee-jenkins" {
  label = "HCQIS - Cloudbees Jenkins"
}

resource "okta_group" "hcqis-cloudbee-jenkins-admins" {
  name = "HCQIS - Cloudbee Jenkins Okta Admins"
}

resource "okta_group_role" "hcqis-cloudbee-jenkins-admins" {
  group_id  = okta_group.hcqis-cloudbee-jenkins-admins.id
  role_type = "APP_ADMIN"

  target_app_list = [format("%s.%s", data.okta_app_saml.hcqis-cloudbee-jenkins.name, data.okta_app_saml.hcqis-cloudbee-jenkins.id)]
}
```

### Debug Output

https://gist.github.com/phi1ipp/caf1c41e7dc8cc84e96b312fba81bf3e

### Expected Behavior

no need to replace the group_role

### Actual Behavior

okta_group_role must be replaced (produced by plan/apply)
https://gist.github.com/phi1ipp/2063de9598dbcdd57ccaddcd2ef05f34

### Steps to Reproduce

1. `terraform plan`

**Comment by bogdanprodan-okta** [comment]
Hi @phi1ipp! Thanks for submitting this issue! I'll try to fix it by the next release

**Comment by bogdanprodan-okta** [comment]
Hi @phi1ipp! I've investigated the problem, and the problem is as follows:
```
data "okta_app_saml" "hcqis-cloudbee-jenkins" {
  label = "HCQIS - Cloudbees Jenkins"
}
```
App in the data source has `id` field
Request:
`GET /api/v1/apps?filter=status+eq+%22ACTIVE%22&limit=1&q=HCQIS+-+Cloudbees+Jenkins`
Response:
```
[
 {
  "id": "0oa11l18bi4PPB7V00h8",
  "name": "terraform-provider-okta_hcqiscloudbeesjenkins_1",
  "label": "HCQIS - Cloudbees Jenkins",
...
  }
]
```
However, when `okta_group_role.hcqis-cloudbee-jenkins-admins` resource makes a request to get list of target apps:
Request:
`GET /api/v1/groups/00g11l1hljlwyX6sz0h8/roles/IFIFAX2BIRGUSTQ/targets/catalog/apps?limit=200&status=ACTIVE`
Response:
```
[
 {
  "name": "terraform-provider-okta_hcqiscloudbeesjenkins_1",
  "displayName": "HCQIS - Cloudbees Jenkins",
  "description": "URL: http://example.okta.com Host: example.okta.com",
  "status": "ACTIVE",
  "lastUpdated": "2021-09-16T11:52:57.000Z",
  "category": "APP_WIZARD",
  "verificationStatus": "NEW",
  "website": "http://example.okta.com",
  "signOnModes": [
   "SAML_2_0"
  ],
  "_links": {
   "logo": [
    {
     "name": "medium",
     "href": "https://op1static.oktacdn.com/assets/img/logos/default.6770228fb0dab49a1695ef440a5279bb.png",
     "type": "image/png"
    }
   ],
   "self": {
    "href": "https://terraform-provider-okta.oktapreview.com/api/v1/catalog/apps/terraform-provider-okta_hcqiscloudbeesjenkins_1"
   }
  }
 }
]
```
The endpoint doesn't return the `id` in the response, so terraform presumes that the format is not `name.id` but just `name` and terraform builds the list of target apps based on this response body.

Ok, long story short, the easiest thing to do here is to change the `okta_group_role` resource to this (just use the `name` in `target_app_list`)
```
data "okta_app_saml" "hcqis-cloudbee-jenkins" {
  label = "HCQIS - Cloudbees Jenkins"
}

resource "okta_group" "hcqis-cloudbee-jenkins-admins" {
  name = "HCQIS - Cloudbee Jenkins Okta Admins"
}

resource "okta_group_role" "hcqis-cloudbee-jenkins-admins" {
  group_id  = okta_group.hcqis-cloudbee-jenkins-admins.id
  role_type = "APP_ADMIN"

  target_app_list = [data.okta_app_saml.hcqis-cloudbee-jenkins.name]
}
```
I've tested it locally and it works fine.
Here is another example where the format for the target app is `name.id`
```
data "okta_app_saml" "hcqis-cloudbee-jenkins" { // <-- app created using `Create App Integration` button
  label = "HCQIS - Cloudbees Jenkins"
}

data "okta_app_saml" "jenkins" {// <-- app from the App Catalog
  label = "Jenkins"
}

resource "okta_group" "hcqis-cloudbee-jenkins-admins" {
  name = "HCQIS - Cloudbee Jenkins Okta Admins"
}

resource "okta_group_role" "hcqis-cloudbee-jenkins-admins" {
  group_id  = okta_group.hcqis-cloudbee-jenkins-admins.id
  role_type = "APP_ADMIN"

  target_app_list = [data.okta_app_saml.hcqis-cloudbee-jenkins.name, format("%s.%s", data.okta_app_saml.jenkins.name, data.okta_app_saml.jenkins.id)]
}
```

**Comment by phi1ipp** [comment]
Doh, I think, I've seen it mentioned somewhere in the document, that different formats are used for target_app_list, depending if it's OIN vs custom.

Thank you for looking into it, @bogdanprodan-okta and sorry for bothering you. My bad, should've read the doc thoroughly!
