### ISSUE TITLE
Is the "Update Application Profile for Assigned User" endpoint implemented?

### ISSUE THREAD

**Issue by sklarsa** [okta/terraform-provider-okta#649]
Is this endpoint implemented by the provider? https://developer.okta.com/docs/reference/api/apps/#update-application-profile-for-assigned-user

I'm trying to update user <> app profiles for users who are assigned to an app through a group assignment.  It seems like this is what I need?  If so, I'll look at implementing it since my team needs this quickly

**Comment by bogdanprodan-okta** [comment]
Hi @sklarsa! Yes, this endpoint is used by `okta_app_user` resource. Check [this](https://github.com/okta/terraform-provider-okta/blob/master/examples/okta_app_user/basic_profile.tf) example.

**Comment by sklarsa** [comment]
Thanks! I tried using it with an oauth app and got this error:
```
│ Error: 'username' is required (the only exception is when the assigned app has 'SHARED_USERNAME_AND_PASSWORD' credentials scheme)
```

This is my resource:
```
resource "okta_app_user" "customer_users" {
    app_id = okta_app_oauth.test.id
    user_id = data.okta_user.test.id
    profile = jsonencode({
        .....
    })
}
```

Also what is the behavior of this resouce if a user is already assigned the application via a group assignment?  Is a separate user-based assignment created?

**Comment by bogdanprodan-okta** [comment]
Could you try to add username to the resource?
```
resource "okta_app_user" "customer_users" {
    app_id = okta_app_oauth.test.id
    user_id = data.okta_user.test.id
    username = data.okta_user.test.email
    profile = jsonencode({
        .....
    })
}
```

**Comment by sklarsa** [comment]
Nice! that worked. thanks!
