### ISSUE TITLE
Error: failed to delete application user schema property

### ISSUE THREAD

**Issue by ahmei0** [okta/terraform-provider-okta#650]
getting following error while running terraform destory

Error: failed to delete application user schema property

Got following resources in code to create custom properties and mapp them

okta_profile_mapping
okta_app_user_schema_property 

Looks like it tries to delete custom property while mapping still exist. We need to somehow tell terraform to remove mapping first and then delete the property

Same behaviour on ui. Please provide help on how to create dependency between okta_app_user_schema_property and okta_profile_mapping so that mapping is deleted first before it attempts to delete property

![image](https://user-images.githubusercontent.com/62230464/133554218-698ac0fb-1f56-476a-8c1d-57cb036a22e5.png)

**Comment by bogdanprodan-okta** [comment]
Hi @ahmei0! Thanks for submitting this issue! There are basically two solutions:
* Use [depends_on](https://www.terraform.io/docs/language/meta-arguments/depends_on.html) meta argument, so `okta_app_user_schema_property` will be a 'child' of the `okta_profile_mapping`
* Use targeted destroy `terraform destroy -target=okta_profile_mapping.my_mapping`, and then remove the rest of the infrastructure.

**Comment by ahmei0** [comment]
I tried depends_on already but didn't help, I have multiple properties so I have a multiple values in depends_on list

2nd option wouldn't be ideal as every time we have a new property we'd have to fiddle with this

![image](https://user-images.githubusercontent.com/62230464/133613458-90b4f73d-9590-4089-8f90-b809b1d7e6de.png)

Also, while defining mapping I'm referring to property index which should itself create a dependency without explicitly defining it, I believe

![image](https://user-images.githubusercontent.com/62230464/133613627-97e35d7e-f8ee-46c1-8ad3-155e78f510e5.png)

**Comment by ahmei0** [comment]
dependency looks fine as it tries to delete in right order and even confirms deletion of mapping as highlighted in the screenshot but then fails to delete property. If I go to the portal, mapping still exist and manual deletion of property also fails with same error. So something weird is happening here

![image](https://user-images.githubusercontent.com/62230464/133614422-9f4c976c-506f-4848-bc7e-7b99d0f76712.png)

**Comment by ahmei0** [comment]
Here's the error on portal 
![image](https://user-images.githubusercontent.com/62230464/133615085-ae5a87d2-5e99-4474-9569-5ba7ef21ade7.png)

**Comment by bogdanprodan-okta** [comment]
@ahmei0 and get weirder, because the method responsible for removing the mapping doesn't do anything
```
func resourceProfileMappingDelete(context.Context, *schema.ResourceData, interface{}) diag.Diagnostics {
	return nil
}
```
I'll start to investigate this, as it's clearly not the expected behavior. Thanks again for the issue!

**Comment by ahmei0** [comment]
At least that explains the behaviour :D

**Comment by bogdanprodan-okta** [comment]
Hi, @ahmei0! I've created the PR that should fix the issue. Basically, I'm setting all the mappings to `nil` value thus [removing property mapping](https://developer.okta.com/docs/reference/api/mappings/#remove-property-mapping).
