### ISSUE TITLE
skip_users/skip_groups not used "retroactively"

### ISSUE THREAD

**Issue by fschmager** [okta/terraform-provider-okta#652]
We have a large user base and the okta provider started syncronizing users of apps. Those users are not part of the terraform state. Everytime we plan the okta provider compares the users in the state with the users in okta. That's taking a really long time due to low rate limits. 

We added `skip_users = true` to our `okta_app_oidc` and `okta_app_saml`. In addition to `ignore_changes = [users, groups]`. That works nicely for apps configured going forward. Users will not be synced. 

However, it doesn't fix the problem of having synced all users already. We already have users in the terraform state. Now, every time we `plan` terraform checks all users as part of "Refreshing state". Taking a long time. The debug logs highlight this by printing `skip values: skip_users=false skip_groups=false` which gets logged during state refresh and seems to be using the property values of the state, not of the "to be planned terraform changes".

Once we `apply` a change having `skip_users = true` this goes away. Our problem is that we can't get `plan` to succeed. It keeps failing with `context deadline exceeded`.

How can we make terraform stop syncing users already part of the terraform state?

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.4
on darwin_amd64
Go runtime version: go1.16.4
okta/okta v3.13.10

### Affected Resource(s)
- `okta_app_oidc`
- `okta_app_saml`

### Terraform Configuration Files

```hcl
resource "okta_app_oauth" "my_app" {
  label                     = "My App"
  type                      = "browser"
  grant_types               = ["authorization_code"]
  redirect_uris             = var.my_app_redirect_uris
  post_logout_redirect_uris = var.my_app_post_logout_redirect_uris
  response_types            = ["code"]
  consent_method            = "TRUSTED"
  hide_ios                  = true
  hide_web                  = true
  skip_users                = true
  skip_groups               = true
  issuer_mode = "CUSTOM_URL"
  token_endpoint_auth_method = "none"
  lifecycle {
    ignore_changes = [
      groups,
      users,
    ]
  }
}
```

### Debug Output
```
okta_app_oauth.my_app: Refreshing state... [id=1234]
2021-09-15T10:38:31.239-0400 [DEBUG] provider.terraform-provider-okta_v3.13.10: 2021/09/15 10:38:31 [INFO]  skip values: skip_users=false skip_groups=false
2021-09-15T10:38:31.239-0400 [DEBUG] provider.terraform-provider-okta_v3.13.10: 2021/09/15 10:38:31 [INFO]  Throttling API requests, sleeping for 60 seconds until rate limit reset ("app-id":99/600)
```
### Panic Output

`Error: failed to get OAuth application: Get "https://mydomain.okta.com/api/v1/apps/1234": context deadline exceeded`

### Expected Behavior

okta provider should not query Okta API for users and groups

### Actual Behavior

okta provider queries Okta API for users and group

### Steps to Reproduce

1. `terraform apply`

### References

- #633
- #585 
- #572

**Comment by bogdanprodan-okta** [comment]
Hi @fschmager! Thanks for submitting this issue! In this case, you can try something like this
1. Copy the `id` for `okta_app_oauth.my_app` (or you can copy it from the state backup file later)
2. Run `terraform state rm okta_app_oauth.my_app` (it removes the resource from the state without actually removing the real underlying app)
3.  Run `terraform import okta_app_oauth.my_app <app id>/skip_groups/skip_users`. Terraform will just re-read the app using the API, but because import contains the `skip_groups/skip_users` part, it won't call get users/groups endpoints.

Does this make sense?

**Comment by fschmager** [comment]
Hey @bogdanprodan-okta,
Thanks for the quick reply. I was afraid you would suggest something like this.

This is a very labor intensive process. We have tens of application, repeated across multiple okta tenants, that means I would have to repeat those steps for over 50 apps swapping in different API keys and looking up all the ID. Lots of places to make errors.

**Comment by bogdanprodan-okta** [comment]
I have the last two options here:
1. Manually add `skip_users` to the state file (which is also annoying)
2. I can create a branch and remove all the group/users from the app resources, so you can clone the repo, build the binary (simple `go install`), and use binary directly. Because there won't be other changes other than removing `users` and `groups` from the app-related resource, you can then switch back to the official release.
3. Wait 2-3 weeks for the 4.0.0 version where there won't be any users/groups.

**Comment by fschmager** [comment]
Let's hold off on 2. I don't want to create more work for you and distract you from getting 4.0.0 out the door :)

I'll experiment with adding `skip_users` to the state. That feels the most convenient. 

Will that leave "tombstone" users in the state or will that get cleaned up automatically or is that something I shouldn't have to worry about?

**Comment by bogdanprodan-okta** [comment]
No, terraform will just skip the check for users/groups

**Comment by fschmager** [comment]
Understood. Thanks. OK, let me do a little experimentation. I'll report what I find for anyone running into this as well.

**Comment by fschmager** [comment]
Removing the apps from the state and then re-importing did the trick. Planning is much faster now.

Here my script for removing and reimporting all `okta_app_oauth` and `okta_app_saml` resources:
```bash
echo "Cleaning up apps.."
echo "Getting terraform state"
terraform show -json | jq --raw-output \
'.values.root_module.resources[]
  | select (.address | startswith("okta_app"))
  | select (.type == "okta_app_saml" or .type == "okta_app_oauth")
  | [.address, .values.id]
  | join(",")
 ' |
  while IFS=',' read -r address app_id; do
    echo "Deleting state of $address (id=$app_id)"
    terraform state rm $address
    echo "Importing $address (id=$app_id)"
    terraform import $address $app_id/skip_groups/skip_users
  done
```
Thanks for your quick replies as always. Looking forward to 4.0.0 :)

**Comment by bogdanprodan-okta** [comment]
I'm closing this issue for now, since there is nothing to be done at this point.
