### ISSUE TITLE
How to configure Okta provider with JWKS

### ISSUE THREAD

**Issue by akashkarve** [okta/terraform-provider-okta#657]
I am trying to configure Okta Provider using Client ID and JWKS (private key).

I am not able to find how to set private key. 

I followed all the steps mentioned in https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/overview/#use-the-client-credentials-grant-flow and it worked with Okta .NET SDK.

Can some help me in configuring same thing in Terraform. 

edit from @monde:
Don't use internet websites for production secrets and audit all software used to generate secrets. Here is a better example of using Terraform to create a PEM and JWKS:
https://github.com/okta/terraform-provider-okta/issues/1249#issuecomment-1301238359

**Comment by bogdanprodan-okta** [comment]
Hi, @akashkarve! Thanks for submitting this issue! Here are the steps I take to configure terraform provider:
* Generate JWK using [this link](https://mkjwk.org/)
* Convert it to private/public keys using [this link](https://8gwifi.org/jwkconvertfunctions.jsp)
* Add JWK key to the service app.
* In that service app grand necessary scopes in Okta API Scopes tab.
* Create `a.pem` file with your private key there (you can put this file somewhere in your terraform project)
* Config provider to look something like this:
```
provider "okta" {
  org_name  = "my_org"
  base_url  = "okta.com"
  private_key = file("a.pem")
  client_id = "0oFzdwjh3wTJdfeRW0h7" // <- from service app
  scopes = ["okta.apps.manage", "okta.users.read", "okta.users.manage", "okta.policies.manage", "okta.groups.manage"]
}
```
* Run terraform

**Comment by bogdanprodan-okta** [comment]
Hi, @akashkarve! Have you managed to make it work?

**Comment by akashkarve** [comment]
@bogdanprodan-okta , I've one question what if I need to rotate public/private key. Do I need to register JWK key in service app again?

**Comment by bogdanprodan-okta** [comment]
Yes, because JSON Web Key Set (JWKS) is a set of keys containing the public keys used to verify any JSON Web Token (JWT) issued by the authorization server. If you change the private key, verification will fail.

**Comment by monde** [comment]
An example of using Terraform to create a PEM, JWKS, and Okta OAuth app:
https://github.com/okta/terraform-provider-okta/issues/1249#issuecomment-1301238359

**Comment by rrs-mckinsey** [comment]
Was able to make it work with generating JWKS key within Okta. Essentially, the Okta SDK is expecting older private_key PEM format for RSA but the generated cert within Okta is using new format. I am using okta provider 3.11, followed these steps.

1.  Generate public keys in okta
2. Copy the PEM form of private key
3. Convert it to older format using `openssl rsa -in generated.key -out new.key`
4. Assigned the resulting key to environment variable OKTA_API_PRIVATE_KEY
