### ISSUE TITLE
okta_app_saml.groups deprecated but okta_app_group_assignments not recognized in state

### ISSUE THREAD

**Issue by pc-mrousseau** [okta/terraform-provider-okta#658]
Hello Team 

When trying to assign groups to an `okta_app_saml` object, you get the following error message if doing so using the `groups` parameter. 

```
╷
│ Warning: Argument is deprecated
│ 
│   with okta_app_saml.test,
│   on test.tf line 15, in resource "okta_app_saml" "test":
│   15:   groups = [ "test_group_id" ]
│ 
│ The direct configuration of groups in this app resource is deprecated, 
| please ensure you use the resource `okta_app_group_assignments` for this functionality.
│ 
╵
```

That's all nice and fine however if you remove that line from the `okta_app_saml.test` object and instead use a `okta_app_group_assignments` like this: 

```
resource "okta_app_group_assignments" "test" {
  app_id   = resource.okta_app_saml.test.id
  group {
    id = resource.okta_group.test.id
    priority = 1
  }
}
```

### Expected Behavior

Using `terraform apply` should result in the groups being assigned (it does). And subsequently running `terraform plan` should show "no changes". 

### Actual Behavior

```
Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # okta_app_group_assignments.test has been changed
  ~ resource "okta_app_group_assignments" "test" {
        id     = "guid-redacted"
        # (1 unchanged attribute hidden)

      - group {
          - id       = "guid-redacted" -> null
          - priority = 1 -> null
        }
      + group {
          + id       = "guid-redacted"
          + priority = 1
          + profile  = jsonencode({})
        }
    }
  # okta_app_saml.test has been changed
  ~ resource "okta_app_saml" "test" {
      ~ groups                     = [
          + "guid-redacted",
        ]
        id                         = "guid-redacted"
        name                       = "test"
        # (28 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond
to these changes.
```

So you're stuck in kind of an infinite loop here since changes that terraform made aren't recognized as changes terraform made. From there basically you can run infinitely `terraform apply` it will never be happy and understand the state has not changed.

### Versions used
Terraform v1.0.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.58.0
+ provider registry.terraform.io/okta/okta v3.13.10

**Comment by pc-mrousseau** [comment]
A potential ugly workaround that can be used is the following in the okta_saml_app block:

```
  lifecycle {
    ignore_changes = [ groups ]
  }
```

**Comment by exitcode0** [comment]
@pc-mrousseau this doesn't seem to work for me 
I still seem to get Terraform attempting to replace the group assignments resource on each apply

```
okta_app_group_assignments.<APPNAME-REDACTED> has been changed
  ~ resource "okta_app_group_assignments" "<APPNAME-REDACTED>" {
        id     = "<APPID-REDACTED>"
        # (1 unchanged attribute hidden)

      - group {
          - id       = "<GROUPID-1-REDACTED>" -> null
          - priority = 3 -> null
        }
      + group {
          + id       = "<GROUPID-1-REDACTED>"
          + priority = 3
          + profile  = jsonencode({})
        }
      - group {
          - id       = "<GROUPID-2-REDACTED>" -> null
          - priority = 1 -> null
        }
      + group {
          + id       = "<GROUPID-2-REDACTED>"
          + priority = 1
          + profile  = jsonencode({})
        }
      - group {
          - id       = "<GROUPID-3-REDACTED>" -> null
          - priority = 2 -> null
        }
      + group {
          + id       = "<GROUPID-3-REDACTED>"
          + priority = 2
          + profile  = jsonencode({})
        }
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.
```

**Comment by bogdanprodan-okta** [comment]
Hi, @pc-mrousseau! Thanks for submitting this issue! Currently, you have to use `ignore_changes` in this resource to avoid constant plan change. However, I'm working on the 4.0.0 version now and all the deprecated fields/resources will be removed. 
Regarding @exitcode0 's issue, there will be a new release today which should fix this problem.

**Comment by pc-mrousseau** [comment]
Sounds great @bogdanprodan-okta - to be fair the workaround is also called out in the documentation: 
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_group_assignment

Hoping to see 4.0 soon and hopefully that includes some of the newer APIs as well so we can manage things that are currently not possible to!
