### ISSUE TITLE
skip_users for okta_groups not working for existing group memberships

### ISSUE THREAD

**Issue by gambitran** [okta/terraform-provider-okta#660]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform 0.14.5

### Affected Resource(s)

- okta_group

### Terraform Configuration Files

```hcl
resource "okta_group" "role-aws" {
  name       =  "role-aws"
  skip_users = true
}
```

### Expected Behavior

okta_groups should not attempt to remove existing users from group. No infrastructure changes.

### Actual Behavior

okta_groups attempts to remove existing users from group.

```hcl
 # okta_group.role-aws will be updated in-place
  ~ resource "okta_group" "role-aws" {
        id         = "xxxxxxxxxxxxxxx"
        name       = "role-aws"
      + skip_users = true
      ~ users      = [
          - "00u1xxxxxxxxxxx",
          - "00ucxxxxxxxxxxx",
        ]
    }
```

### Steps to Reproduce

1. `terraform plan`

**Comment by dawiki** [comment]
this is happening to us as well .. since yesterday we lost some user group memberships that are managed outside of okta and we now run into timeouts because the groups are trying to be refreshed and we have ~17000 users in the group

I think it is very _unfortunate_ or actually worrying that such a change is happening in a patch release.

**Comment by bogdanprodan-okta** [comment]
Hi, @Gambitran! Thanks for submitting this issue! To avoid users sync you should also put igmore_changes into your resource
```
lifecycle {
    ignore_changes = [
      users
    ]
  }
```
In addition, please read the comments in [this issue](https://github.com/okta/terraform-provider-okta/issues/652) on how to avoid users sync after adding `skip_users = true` field.

**Comment by dawiki** [comment]
We actually did the lifecycle ignore_changes as well .. but it still is loading the whole user list. At least it takes 20min to refresh the state for some groups (with many users)

So the ignore_changes thing does not solve the issue fully

I have no idea how this really works but could it be a problem that in https://github.com/okta/terraform-provider-okta/blob/8cc0d8669c189cd10537c6031021b8c3113ac3ef/okta/resource_okta_group.go#L154 it actually loads the remote state before checking the skip_users flag 3 lines down?

**Comment by bogdanprodan-okta** [comment]
@dawiki even if you set `skip_users = true`, terraform will still use the values from the old state and refresh the resource. The easiest thing to do is to remove the resource from the state (but not from the terraform script) and then just import it back. In this case it will pick up new fields and won't sync the users.

**Comment by dawiki** [comment]
Yeah that is unfortunate .. we have about 700 groups in terraform.

As I said before this is quite worrying to be happening with a patch release - because we did not change anything and pinned the provider version to 3.13.* and then suddenly this happens :(

**Comment by bogdanprodan-okta** [comment]
@dawiki I'll make a fix to this resource today and release a new version.

**Comment by bogdanprodan-okta** [comment]
@dawiki new release gonna be available within 15mins or so

**Comment by dawiki** [comment]
thank you guys .. we already see it working 👍

**Comment by bogdanprodan-okta** [comment]
@dawiki no problem and sorry again for the inconvenience!
