### ISSUE TITLE
Getting "Invalid session" error when using okta_user_profile_mapping_source datasource

### ISSUE THREAD

**Issue by BalaGanaparthi** [okta/terraform-provider-okta#667]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
1.0.6

### Affected Resource(s)

- data "okta_user_profile_mapping_source" "user" {}

### Terraform Configuration Files

```hcl
data "okta_user_profile_mapping_source" "user" {}

resource "okta_profile_mapping" "example" {
  source_id          = "0oa1f42x30V2LCnR91d7"
  target_id          = data.okta_user_profile_mapping_source.user.id
  delete_when_absent = true

  mappings {
    id         = "firstName"
    expression = "appuser.firstName"
  }
...
}
```

### Debug Output
-----------------------------------------------------: timestamp=2021-09-24T05:50:05.261Z
2021-09-24T05:50:05.265Z [INFO]  provider.terraform-provider-okta_v3.13.10: 2021/09/24 05:50:05 [DEBUG] Okta API Request Details:
---[ REQUEST ]---------------------------------------
GET /api/v1/meta/schemas/apps/0oa1ah9792Dti4NAT1d7/default HTTP/1.1
Host: balaganaparthi-ciam.oktapreview.com
User-Agent: okta-sdk-golang/2.6.2 golang/go1.17 linux/amd64 okta-terraform/3.13.10 
Accept: application/json
Authorization: Bearer eyJraWQiOiI5UG9GS2pmdlp5Vk5zc2ZiMmtTMUduSHduRnV4bnJEQThOUEpUcURtenJvIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULkZQWGI1Y3Nja0NjV2puWWw2LUs2RGZjajQtY2I1NHQtMk1FQmNFQ1RDbEUiLCJpc3MiOiJodHRwczovL2JhbGFnYW5hcGFydGhpLWNpYW0ub2t0YXByZXZpZXcuY29tIiwiYXVkIjoiaHR0cHM6Ly9iYWxhZ2FuYXBhcnRoaS1jaWFtLm9rdGFwcmV2aWV3LmNvbSIsInN1YiI6IjBvYTE2c3A5aHRhME5jeDUyMWQ3IiwiaWF0IjoxNjMyNDYyNjA1LCJleHAiOjE2MzI0NjYyMDUsImNpZCI6IjBvYTE2c3A5aHRhME5jeDUyMWQ3Iiwic2NwIjpbIm9rdGEudXNlcnMubWFuYWdlIiwib2t0YS5wb2xpY2llcy5tYW5hZ2UiLCJva3RhLmdyb3Vwcy5tYW5hZ2UiLCJva3RhLnNjaGVtYXMucmVhZCIsIm9rdGEuc2NoZW1hcy5tYW5hZ2UiLCJva3RhLnJvbGVzLm1hbmFnZSIsIm9rdGEuYXBwcy5tYW5hZ2UiLCJva3RhLmlkcHMubWFuYWdlIl19.asMmuNH1vKAwJyp7B1_WxLeZuL99f23yNAPB9a0GMhrTurHUBhDMCxgSeDmcwVJLgoUl3hVu1VyyT0vdmZDFHABMN4zCz-q71uTIU6jHZlDUNfDYkgMpVou0_t6kEDZ4Xqak54LsVpFYSUWdwIcN7hoV-SRjqqZYYvS93APdEryz4jnyQSeQsd5Sm3I2FtCQ1jf0MeXV_tQsJ6nFy4QEc0aUFz1Awo4XBxTkwGv5KrKr_CSKxftLoVHO8is64d3GTcZxW83AWAtQRF_-is6gPGnS-s3ik6M0_KV1hIJgCj0GxBST6SkP2QO74ktBnvl34iGMv0pBgns6dISoz_55yQ
Accept-Encoding: gzip

-----------------------------------------------------: timestamp=2021-09-24T05:50:05.262Z
2021-09-24T05:50:05.442Z [INFO]  provider.terraform-provider-okta_v3.13.10: 2021/09/24 05:50:05 [DEBUG] Okta API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 403 Forbidden
Content-Type: application/json
Date: Fri, 24 Sep 2021 05:50:05 GMT
P3p: CP="HONK"
Public-Key-Pins-Report-Only: pin-sha256="jZomPEBSDXoipA9un78hKRIeN/+U4ZteRaiX8YpWfqc="; pin-sha256="axSbM6RQ+19oXxudaOTdwXJbSr6f7AahxbDHFy3p8s8="; pin-sha256="SE4qe2vdD9tAegPwO79rMnZyhHvqj3i5g1c2HkyGUNE="; pin-sha256="ylP0lMLMvBaiHn0ihLxHjzvlPVQNoyQ+rMiaj0da/Pw="; max-age=60; report-uri="https://okta.report-uri.com/r/default/hpkp/reportOnly"
Server: nginx
Set-Cookie: sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
Strict-Transport-Security: max-age=315360000; includeSubDomains
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Okta-Request-Id: YU1nDba@DTG5PDg-NQU6kQAACXU
X-Xss-Protection: 0

{
 "errorCode": "E0000005",
 "errorSummary": "Invalid session",
 "errorLink": "E0000005",
 "errorId": "oaeB3oCG1P5SWWO1Q5EnG1fXw",
 "errorCauses": []
}

### Panic Output

╷
│ Error: failed to find profile mapping source: the API returned an error: Invalid session
│ 
│   with module.troubleshoot.data.okta_user_profile_mapping_source.user,
│   on modules/troubleshoot/main.tf line 1, in data "okta_user_profile_mapping_source" "user":
│    1: data "okta_user_profile_mapping_source" "user" {}
│ 

### Expected Behavior

Should return the id of the okta_user_profile_mapping_source

or 

If there is insufficient scopes to perform the operation then report as insufficient scopes to perform the operation

### Actual Behavior

Error : Invalid session

### Steps to Reproduce

1. Create a TF file with datasource "data "okta_user_profile_mapping_source" "user" {}"

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
https://github.com/okta/terraform-provider-okta/pull/676#issuecomment-946096443
