### ISSUE TITLE
To have a config setting to preserve some capacity for rate limits

### ISSUE THREAD

**Issue by phi1ipp** [okta/terraform-provider-okta#673]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It'd be nice to have an ability to preserve some capacity from Okta rate limits for other participants in a tenant. I figured that during applying configurations I might occasionally hit limits, which can affect other users of my tenant.

### New or Affected Resource(s)

- all

### Potential Terraform Configuration

```hcl
terraform {
  required_providers {
    okta = {
      source  = "okta/okta"
      version = "~> 3.10"
      api_pct_usage = 50
    }
  }
}
```

**Comment by bogdanprodan-okta** [comment]
Hi @phi1ipp! You can use [this field](https://registry.terraform.io/providers/okta/okta/latest/docs#max_api_capacity) to set rate limits.

**Comment by phi1ipp** [comment]
hi @bogdanprodan-okta , thank you for the prompt response! I'm sorry, I should've read documentation more thoroughly

**Comment by phi1ipp** [comment]
@bogdanprodan-okta , is it currently supported or not? Below is what I got, trying to apply the config param, which you mentioned
```hcl
terraform {
  required_providers {
    okta = {
      source  = "okta/okta"
      version = "~> 3.10"
      max_api_capacity = 70
    }
  }
}
```

```log
Invalid required_providers object
│
│   on okta.tf line 6, in terraform:
│    6:       max_api_capacity = 70
│
│ required_providers objects can only contain "version", "source" and
│ "configuration_aliases" attributes. To configure a provider, use a "provider"
│ block.
```

**Comment by bogdanprodan-okta** [comment]
@phi1ipp in the comment above you are trying to set terraform's config. You should put this setting in provider's config instead
```
# Configure the Okta Provider
provider "okta" {
  org_name = "terraform-provider-okta"
  base_url = "oktapreview.com"
  max_api_capacity = 70
}  
```

**Comment by phi1ipp** [comment]
Doh, thank you, @bogdanprodan-okta! Sorry for the silly question
