### ISSUE TITLE
Add resource okta_domain_validation

### ISSUE THREAD

**Issue by frousselet** [okta/terraform-provider-okta#681]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am terraforming the Okta custom domain, including the domain verification.

Since I am creating the TXT record with the information provided by `okta_domain` itself, the verification always fails since the record does not exist yet and it never retries.

The solution can be a new resource dedicated to this validation, depending on the TXT record creation. It will retry the validation and timeout if the status stays in failure.

### New or Affected Resource(s)

- `okta_domain_validation` (new resource)
- `okta_domain` (flag `verify` as deprecated)

### Potential Terraform Configuration

```hcl
# Example with Amazon Route 53

resource "okta_domain" "custom_domain" {
  name = "okta.mycompany.com"
}

data "aws_route53_zone" "dns_zone" {
  name = "mycompany.com"
}

resource "aws_route53_record" "custom_domain" {
  count = 2

  name    = okta_domain.custom_domain.dns_records[count.index].fqdn
  type    = okta_domain.custom_domain.dns_records[count.index].record_type
  records = okta_domain.custom_domain.dns_records[count.index].values
  ttl     = 30
  zone_id = data.aws_route53_zone.dns_zone.id
}

resource "okta_domain_validation" "custom_domain" {
  domain_id = okta_domain.custom_domain.id

  depends_on = [
    aws_route53_record.custom_domain
  ]
}
```

**Comment by bogdanprodan-okta** [comment]
Hi @frousselet! Thanks for submitting this issue! I've started to work on adding this into the next release. 
Question: what do you think about resource behavior?
1. Keep trying to validate until the `VERIFIED` status is returned and just fail after several attempts if not.
2. Try to validate, don't retry, and just set the status. Keep validating after every plan-refresh until status is `VERIFIED`

**Comment by frousselet** [comment]
Hi @bogdanprodan-okta,

Thanks for the feedback!

Yes option 1 makes sense too since 'verify' is a status and it doesn't really make sense to destroy it, however the verification will be performed in background (because the DNS provider needs the TXT record information from `okta_domain`), and it implies having to go on Okta GUI (or somewhere else) and check the status after the apply.

What I like in my solution is that we can directly see in the Terraform logs if something went wrong since the process is not performed in background. It's the same process as AWS ACM validation.

However I don't really understand the behavior 2. Do you mean for each `terraform apply` on `okta_domain` it will request the domain/verify API if and only if the status is not `VERIFIED`?

**Comment by bogdanprodan-okta** [comment]
@frousselet so the `okta_domain_validation` will make only one attempt to validate the domain and set's the status returned in the response. If you run `terraform apply` once more time, the provider will check the status that is stored in the state. If it's not `VERIFIED`, then it will do another API call to try to verify it and so on. As you said in prev comment, the first option seems more logical, since why do you need to create the `okta_domain_validation` resource in the first place if don't want the domain to be verified?

**Comment by frousselet** [comment]
Hi @bogdanprodan-okta,

We need `okta_domain` to finish its process to get the TXT record information (we both agreed on that).

That means we can't let the resource `okta_domain` creation timeout when verify is not successful (we both agreed on that).

That means, with this solution, we have to do this verify process in background, without letting know the status to Terraform (or most of the time not `VERIFIED`, but Terraform won't fail in any case). I think we also both agreed on that.

And that means, with this solution, we cannot have a clear feedback from Terraform of the verify status, and the status of the `terraform apply` won't be clear (since it can fail without having visual error).

That also means the status will change between two applies without any change in the HCL.

The `okta_domain_validation` will loop while the status is not `VERIFIED` and timeout after some minutes. With this option, Terraform will print a clear status of the verify step.
