### ISSUE TITLE
Add app_settings_json to okta_app_swa

### ISSUE THREAD

**Issue by Mrorya** [okta/terraform-provider-okta#683]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There are OIN apps that support provisioning but do not support SAML/SCIM. At least one of these is the Amplitude OIN app. The Amplitude OIN app has an attribute in the App Settings titled "OrgID" - but we're unable to set this via terraform. An optional argument app_settings_json similar to the optional argument in the app_oauth/app_saml apps would enable use to use terraform for this app.

### New or Affected Resource(s)

- okta_app_swa

### Potential Terraform Configuration

```hcl
resource "okta_app_swa" "amplitude_scim" {
  preconfigured_app = "amplitude"
  label             = "Amplitude [SCIM]"
  status            = "ACTIVE"
  app_settings_json = jsonencode({ organizationId : "XXXXX", })
}
```

### References

- https://www.okta.com/integrations/amplitude/#overview
- https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_saml
- https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_swa

**Comment by bogdanprodan-okta** [comment]
Hi, @Mrorya! It might look weird, but could you try to use the `okta_app_auto_login` resource to create this app?

The problem is that according to official docs, this is the body for browser plugin app settings:
```
"settings": {
    "app": {
      "buttonField": "btn-login",
      "passwordField": "txtbox-password",
      "usernameField": "txtbox-username",
      "url": "https://example.com/login.html",
      "loginUrlRegex": "REGEX_EXPRESSION"
    }
  }
```
If you want to add [custom SWA app](https://developer.okta.com/docs/reference/api/apps/#add-custom-swa-application), you have to use the `okta_app_auto_login` resource type.

**Comment by Mrorya** [comment]
@bogdanprodan-okta - How would that work if we've already created the app as an "okta_app_swa" resource? Is there a 'migrate from resource to resource' option here? We created the app as an okta_app_swa app and applied the settings json manually - I'd be concerned about losing the config if I terminated the okta_app_swa resource that's already been created.

**Comment by bogdanprodan-okta** [comment]
@Mrorya I think the best approach here would be:
1. Create new resource in the terraform file
```
resource "okta_app_auto_login" "amplitude_scim" {
}
```
2. Import the existing app `terraform import okta_app_auto_login.amplitude_scim <app_id>`
3. Set all the required fields (or just copy-paste from the old `okta_app_swa` resource)
4. Remove old `okta_app_swa` resource from the state `terraform state rm okta_app_swa.amplitude_scim`. This will just remove the resource from the state, but not the actual app. Terraform will also automatically create the state's backup file.

**Comment by Mrorya** [comment]
> @Mrorya I think the best approach here would be:
> 
> 1. Create new resource in the terraform file
> 
> ```
> resource "okta_app_auto_login" "amplitude_scim" {
> }
> ```
> 
> 1. Import the existing app `terraform import okta_app_auto_login.amplitude_scim <app_id>`
> 2. Set all the required fields (or just copy-paste from the old `okta_app_swa` resource)
> 3. Remove old `okta_app_swa` resource from the state `terraform state rm okta_app_swa.amplitude_scim`. This will just remove the resource from the state, but not the actual app. Terraform will also automatically create the state's backup file.

This worked for us, thanks for the help here
