### ISSUE TITLE
Client authentication on SPA app

### ISSUE THREAD

**Issue by ahmei0** [okta/terraform-provider-okta#685]
When I create SPA app using app_oauth resource it create app with Client authentication not enabled.

Could you pls advise parameter below I need to use so "Client authentication" is set to "Use PKCE (for public clients)"

https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_oauth

**Comment by bogdanprodan-okta** [comment]
Hi, @ahmei0! Thanks for submitting this issue! Here is an example of the app that has "Client authentication" set to "Use PKCE (for public clients)":
```
resource "okta_app_oauth" "test" {
  label                      = "testAcc_replace_with_uuid"
  type                       = "browser"
  grant_types                = ["authorization_code"]
  redirect_uris              = ["https://d.com/"]
  response_types             = ["code"]
  token_endpoint_auth_method = "none"
  consent_method             = "REQUIRED"
  auto_key_rotation          = true
}
```
The key value you are looking for is `type = "browser"`

**Comment by bogdanprodan-okta** [comment]
You can also use `type = "native"`, and set `token_endpoint_auth_method = "none"` ("Client authentication" set to "Use PKCE (for public clients)") or `token_endpoint_auth_method = "client_secret_basic"` ("Client authentication" set to "Use Client Authentication")

**Comment by bogdanprodan-okta** [comment]
@ahmei0 I'm closing this issue for now. If have more questions, feel free to post them here. Cheers!
