### ISSUE TITLE
Metadata format unsuitable for AWS Opensearch integration

### ISSUE THREAD

**Issue by pbygrave-lucid** [okta/terraform-provider-okta#686]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently an okta_app_saml resource produces 2 different metadata outputs, "metadata" which outputs the value in raw XML format, and "metadata_url" which outputs a URL which services that support metadata retrieval automatically can use to pull the values directly.

My issue is that I am trying to automate the creation of an AWS Opensearch (formerly Elasticsearch) cluster with SAML integration and the format of the "metadata" attribute is incompatible with the resource "aws_elasticsearch_domain_saml_options". It expects a value for saml_options > idp > metadata_content, but since the "metadata" attribute contains all the raw XML formatting in addition to the actual content, AWS returns that the SAML configuration is invalid.

Is there a way of returning only the md fields from the metadata? I can't imagine this is the only automation chain that doesn't work with the metadata attribute that the okta provider generates?

### New or Affected Resource(s)

- okta_app_saml

**Comment by bogdanprodan-okta** [comment]
Hi, @pbygrave-lucid! Thanks for submitting this issue! I'll take a look into this and try to solve your problem. Meanwhile, could you try using `local_file` resource to store the metadata into a local file, and then use that file in the `metadata_content` field?
```
resource "local_file" "saml_app_metadata" {
  content  = okta_app_saml.test.metadata
  filename = "metadata.xml"
}

resource "aws_elasticsearch_domain_saml_options" "example" {
  domain_name = aws_elasticsearch_domain.example.domain_name
  saml_options {
    enabled = true
    idp {
      entity_id        = "https://example.com"
      metadata_content = file("./metadata.xml")
    }
  }
  depends_on = [local_file.saml_app_metadata]
}
```

**Comment by pbygrave-lucid** [comment]
@bogdanprodan-okta I am massively sorry to have wasted your time, I was reporting this issue on behalf of another engineer and we have subsequently found that the invalid SAML configuration was being caused by an incorrect subject_key being passed, it was actually nothing to do with the metadata and the direct referencing works correctly. I will close this issue so as not to waste anyone's time further!
