### ISSUE TITLE
max_api_capacity not working properly

### ISSUE THREAD

**Issue by phi1ipp** [okta/terraform-provider-okta#696]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.6
on darwin_amd64
\+ provider registry.terraform.io/okta/okta v3.14.0

### Affected Resource(s)

- all?

### Terraform Configuration Files

```hcl
provider "okta" {
  org_name         = "..."
  base_url         = "okta.com"
  api_token        = "... redacted ..."
  max_api_capacity = 80
}
```

### Debug Output

https://gist.github.com/phi1ipp/c8b01eab5f32ec6bfe96afc418aa4ed1

### Expected Behavior

Refresh state operation should be executed as there is a lot of unused capacity. 
### Actual Behavior
Terraform pauses with a message to sleep for XX seconds to preserve the limit. When I saw a message `sleeping for 60 seconds until rate limit reset ("app-id":98/1800` and then inspected all API calls above it in the log, I was not able to find where remaining `X-Rate-Limit-Remaining` would be 98 and `X-Rate-Limit-Limit` would be 1800.

Other suspicious factor is, that `/api/v1/apps` is not 1800 for sure, even though we have increased limit for this endpoint

### Steps to Reproduce

1. `terraform apply`

**Comment by monde** [comment]
Thanks for details @phi1ipp . I'm looking into this today.

**Comment by phi1ipp** [comment]
@monde , @bogdanprodan-okta , I submitted #699 to address it

I believe there is something wrong with how mutex is updated/read, but at least this fix helps to sort things out for now, as you had wrong distribution of keys for the cases which I mentioned in the commit

**Comment by phi1ipp** [comment]
@bogdanprodan-okta , @monde 
I think it's still not working properly...
`2021-10-12T09:27:27.686-0500 [DEBUG] provider.terraform-provider-okta_v3.15.0: 2021/10/12 09:27:27 [INFO]  Throttling API requests; sleeping for 36 seconds until rate limit reset (path class "other": 95 remaining of 1800 total); current request "GET /api/v1/apps/0oa9jyw49f9U19vvB297/users"`

**Comment by monde** [comment]
@phi1ipp can you get me another debug log of your latest run so I can look that the HTTP calls that are made? Thanks!

**Comment by phi1ipp** [comment]
@monde , here it is https://gist.github.com/phi1ipp/d60b6f34a1958113868ca99aef611150

**Comment by phi1ipp** [comment]
@monde , I think that normalize function is wrong. Please check what I suggested in my PR, you got it wrong a bit

Here is what you have
https://github.com/okta/terraform-provider-okta/blob/2506db256b7a06971c392d7a6bb1e7cab88b544c/okta/internal/apimutex/apimutex.go#L131-L134

and here is what I suggested
```go
case regexp.MustCompile("/api/v1/apps/[^/]+$").MatchString(endPoint):
    result = APPID_KEY
case strings.Contains(endPoint, "/api/v1/apps"):
    result = APPS_KEY
```

everything that doesn't match string `/api/v1/apps/xxxxxx` but has `/api/v1/apps` goes under second case. In your implementation you lose `/api/v1/apps/xxxxx/groups` as an example, which goes to the default case branch

**Comment by monde** [comment]
> @monde , I think that normalize function is wrong. Please check what I suggested in my PR, you got it wrong a bit
> 
> Here is what you have
> 
> https://github.com/okta/terraform-provider-okta/blob/2506db256b7a06971c392d7a6bb1e7cab88b544c/okta/internal/apimutex/apimutex.go#L131-L134
> 
> and here is what I suggested
> 
> ```go
> case regexp.MustCompile("/api/v1/apps/[^/]+$").MatchString(endPoint):
>     result = APPID_KEY
> case strings.Contains(endPoint, "/api/v1/apps"):
>     result = APPS_KEY
> ```
> 
> everything that doesn't match string `/api/v1/apps/xxxxxx` but has `/api/v1/apps` goes under second case. In your implementation you lose `/api/v1/apps/xxxxx/groups` as an example, which goes to the default case branch

@phi1ipp excellent eyes, that is awesome you picked up on that subtlety. Can you make a PR to fix it?

**Comment by phi1ipp** [comment]
@monde , pls see #709
