### ISSUE TITLE
okta_user_schema_property  - failed to get user custom schema: json: cannot unmarshal number into Go struct field 

### ISSUE THREAD

**Issue by ahmei0** [okta/terraform-provider-okta#701]
I'm getting this weird error

│ 
│   with okta_user_schema_property.user_channelId,
│   on app_oauth_native.tf line 17, in resource "okta_user_schema_property" "user_channelId":
│   17: resource "okta_user_schema_property" "user_channelId" {
│ 
╵
╷
│ Error: failed to get user custom schema: json: cannot unmarshal number into Go struct field UserSchemaAttributeItems.definitions.custom.properties.items.enum of type string
│ 
│   with okta_user_schema_property.user_roles,
│   on app_oauth_native.tf line 25, in resource "okta_user_schema_property" "user_roles":
│   25: resource "okta_user_schema_property" "user_roles" {
│ 
╵
╷
│ Error: failed to get user custom schema: json: cannot unmarshal number into Go struct field UserSchemaAttributeItems.definitions.custom.properties.items.enum of type string
│ 
│   with okta_user_schema_property.user_isActiveInAST,
│   on app_oauth_native.tf line 64, in resource "okta_user_schema_property" "user_isActiveInAST":
│   64: resource "okta_user_schema_property" "user_isActiveInAST" {

My code is as below, all of them were of type string which I changed to what you see below and now I'm stuck with this error. Even if I remove resources from the code I still get this error
```
resource "okta_user_schema_property" "user_channelId" {
  index       = "channelId"
  title       = "channelId"
  type        = "number"
  description = "channelId"
  master      = "OKTA"
  scope       = "SELF"
}
resource "okta_user_schema_property" "user_roles" {
  index       = "roles"
  title       = "roles"
  type        = "array"
  array_type  = "number"
  description = "roles"
  master      = "OKTA"
  scope       = "SELF"
  array_enum  = ["none"]
  array_one_of {
    title = "none"
    const = 0
  }
}
```

**Comment by bogdanprodan-okta** [comment]
Hi, @ahmei0! Thanks for submitting this issue! I'll investigate the root cause of this issue and create a fix asap.

**Comment by ahmei0** [comment]
@bogdanprodan-okta  thanks for quick response. What was the issue btw

**Comment by ahmei0** [comment]
@bogdanprodan-okta  waiting on this merge,  now my pipeline is failing with same error on string attributes in same account

```
okta_auth_server_policy_rule.okta_auth_server_policy_rule_MFA_Skip[0]: Refreshing state... [id=0prwpx720BlVxmqKl3l6]
module.myaccount_app.okta_auth_server_policy_rule.okta_auth_server_policy_rule: Refreshing state... [id=0pruqstv4YJQcpZR23l6]
╷
│ Error: failed to get user custom schema property: json: cannot unmarshal number into Go struct field UserSchemaAttributeItems.definitions.custom.properties.items.enum of type string
│ 
│   with okta_user_schema_property.user_myAccount,
│   on app_oauth_spa.tf line 24, in resource "okta_user_schema_property" "user_myAccount":
│   24: resource "okta_user_schema_property" "user_myAccount" {

```

code is

```
#user profile custom attributes
resource "okta_user_schema_property" "user_myAccount" {
  index       = "myAccount"
  title       = "myAccount"
  type        = "string"
  description = "myAccount"
  master      = "OKTA"
  scope       = "SELF"
}
```

**Comment by bogdanprodan-okta** [comment]
@ahmei0 could you please run `TF_LOG=TRACE terraform apply` and paste here a response from `GET /api/v1/meta/schemas/user/default` (specifically part for `myAccount`). Here is how does it look in my org:
```
 "myAccount": {
     "title": "myAccount",
     "description": "myAccount",
     "type": "string",
     "mutability": "READ_WRITE",
     "scope": "SELF",
     "permissions": [
      {
       "principal": "SELF",
       "action": "READ_ONLY"
      }
     ],
     "master": {
      "type": "OKTA"
     }
    }
   },
   ```

**Comment by ahmei0** [comment]
This got fixed with above update.

**Comment by ahmei0** [comment]
But I am having similar issue on another resource in another pipeline - raised it as separate https://github.com/okta/terraform-provider-okta/issues/706
