### ISSUE TITLE
user profile to app mapping isn't working as expected

### ISSUE THREAD

**Issue by ahmei0** [okta/terraform-provider-okta#704]
Hi, I'm using following code to map custom attributes and it works fine

```
data "okta_user_profile_mapping_source" "ast_user" {
  depends_on = [okta_app_oauth.ast_app_oauth]
}
resource "okta_profile_mapping" "okta_profile_mapping" {
  source_id          = okta_app_oauth.ast_app_oauth.id
  target_id          = data.okta_user_profile_mapping_source.ast_user.id
  delete_when_absent = true
  mappings {
    id         = okta_app_user_schema_property.appuser_channelId.index
    expression = "appuser.${okta_user_schema_property.user_channelId.index}"
  }
  }
```
and I can see following mapping on app to user mapping tab
![image](https://user-images.githubusercontent.com/62230464/136694739-5ee41359-42d7-44f1-98f5-b529c02771bd.png)

but I don't see mapped parameters on user to app maping tab
![image](https://user-images.githubusercontent.com/62230464/136694785-1b53b159-cc03-4eff-aded-00366aec3373.png)

where it should appear as user.channelId on left side

Please advise. Do I need to define another block like above and switch source_id and target_id or user.xxx mappings should come by itself?

Sometimes I do see them, probably just the first time and if I remove the mapping and redo it never seem to come back on user.* tab, looks like update of mapping is not working correctly

for example I defined another block of above resource like below without any mapping definition. Now it has has removed all the mapping from user.x tab (appuser.x tab is fine) and even if I remove this resource and redploy it doesn't bring the mapping back

```
resource "okta_profile_mapping" "okta_profile_mapping" {
  source_id          = data.okta_user_profile_mapping_source.ast_user.id
  target_id          = okta_app_oauth.ast_app_oauth.id
  delete_when_absent = true
  }
```

![image](https://user-images.githubusercontent.com/62230464/136694858-0e1101df-22fc-46eb-bedd-c8f523b6ede3.png)

**Comment by bogdanprodan-okta** [comment]
Hi, @ahmei0! Thanks for submitting this issue! 
1. To preserve mappings that are set outside of the terraform, you should set `delete_when_absent = false`.
2. As for `okta_profile_mapping`, to set `user -> app` mapped parameters, you have to create another one with `source_id` set to a user_profile_mapping_source.

Here is an example I've used to test this:
```
resource "okta_app_oauth" "ast_app_oauth" {
  label                      = "testAcc_AUTH"
  type                       = "web"
  grant_types                = ["authorization_code"] #, "implicit", "client_credentials"
  redirect_uris              = ["https://localhost", "https://www.thunderclient.io/oauth/callback"]
  response_types             = ["code"] # , "token","id_token"
  consent_method             = "REQUIRED"
  omit_secret                = true
}

resource "okta_app_user_schema_property" "appuser_channelId" {
  app_id      = okta_app_oauth.ast_app_oauth.id
  index       = "customAttribute123"
  title       = "terraform acceptance test"
  type        = "string"
  description = "terraform acceptance test updated"
  required    = true
  master      = "OKTA"
  scope       = "SELF"
}

resource "okta_user_schema_property" "user_channelId" {
  index  = "customAttribute123"
  title  = "terraform acceptance test"
  type   = "string"
  master = "PROFILE_MASTER"
}

data "okta_user_profile_mapping_source" "ast_user" {
  depends_on = [okta_app_oauth.ast_app_oauth]
}

resource "okta_profile_mapping" "okta_profile_mapping" {
  source_id          = okta_app_oauth.ast_app_oauth.id
  target_id          = data.okta_user_profile_mapping_source.ast_user.id
  mappings {
    id         = okta_app_user_schema_property.appuser_channelId.index
    expression = "appuser.${okta_user_schema_property.user_channelId.index}"
  }
}

resource "okta_profile_mapping" "okta_profile_mapping_user" {
  source_id          = data.okta_user_profile_mapping_source.ast_user.id
  target_id          = okta_app_oauth.ast_app_oauth.id
  mappings {
    id         = okta_user_schema_property.user_channelId.index
    expression = "user.${okta_app_user_schema_property.appuser_channelId.index}"
  }
}
```

**Comment by bogdanprodan-okta** [comment]
Hey, @ahmei0! Did my comment help to solve your issue?

**Comment by ahmei0** [comment]
Thanks @bogdanprodan-okta  yeah I already defined another resource with reverse source and target and it worked.
