### ISSUE TITLE
Data source: okta_user_profile_mapping_source throwing failed to find profile mapping source: could not locate profile mapping source with name 'user' and type 'user' error after spinning up a new Okta tenet

### ISSUE THREAD

**Issue by mvitt** [okta/terraform-provider-okta#707]
I recently requested that Okta create a new tenet for me. After it was spun up I attempted to run my Terraform code against it. It failed with the following error: `Error: failed to find profile mapping source: could not locate profile mapping source with name 'user' and type 'user'`. After some digging I found what might be the issue. It seems that behind the scenes Okta changed the default user type from `'user'` to `'Okta'`.

<img width="801" alt="Screen Shot 2021-10-12 at 9 36 07 AM" src="https://user-images.githubusercontent.com/31548861/136977731-60be2da3-00e5-4379-86e2-cc38ea18751c.png">

I ran the same Terraform code against an older Okta tenet and did not experience this issue.

**Comment by bogdanprodan-okta** [comment]
Hi, @mvitt! Thanks for submitting this issue! I'll investigate this name change and fix it asap.

**Comment by bogdanprodan-okta** [comment]
Hi, @mvitt! Could you please paste the API response the `mapping` endpoint returns in your new tenet?
```
curl --location --request GET 'https://my-company.okta.com/api/v1/mappings' \
--header 'Authorization: SSWS my_token' 
```
I've tried different test orgs and everything works fine.

**Comment by mvitt** [comment]
Hey @bogdanprodan-okta I tried to run the terraform script again (with no changes) and it started to work. I am not sure why I was getting that error, but it seems to have been fixed. So feel free to close this.
