### ISSUE TITLE
okta_app_saml.features reset by provider

### ISSUE THREAD

**Issue by pc-mrousseau** [okta/terraform-provider-okta#710]
Working with imported applications that are configured for SCIM, we noticed that the provider will actually detect this as a "change" and flip back the features like SCIM back to off. Obviously, that's not great as it breaks SCIM and actually drop the configurations. 

## Expected Behavior
The documentation here states 
`Notice: you can't currently configure provisioning features via the API. `
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_saml

I would expect either one of two things here: 

1) The provider completely ignores the "features" property, or;
2) The provider configures them properly. 

## Steps to reproduce
Configure an app directly in Okta and activate SCIM feature. Import this app in terraform (e.g.; `terraform import okta_app_saml.test_app okta_guid`), assuming you have previously defined the test_app obviously. 

If you run `terraform plan` the following changes will be detected:

```
  # okta_app_saml.artifactory has been changed
  ~ resource "okta_app_saml" "test_app" {
      ~ features                   = [
          + "SCIM_PROVISIONING",
        ]
```

If you apply this change the app's SCIM features are removed. The behavior is the same even if you add `features = [ "SCIM_PROVISIONING" ]` into the terraform code. The behavior is the same also if you do `lifecycle { ignore_changes = [ features ] }`

## Versions
Terraform v1.0.7
on darwin_amd64
+ provider registry.terraform.io/okta/okta v3.15.0

**Comment by bogdanprodan-okta** [comment]
Hi, @pc-mrousseau! Thanks for submitting this issue! Yeah, you can't currently configure provisioning features via the API, so I'll just remove that from the provider.

**Comment by sabrinaklinning** [comment]
Hi! I am checking for an update on whether the okta_app_swa and okta_app_saml resources now support scim provisioning natively in the latest versions of the provider.

I noticed that the previous documentation warnings regarding API parity—specifically the note stating, "Notice: you can't currently configure provisioning features via the API"—have been removed. However, the resource arguments for SCIM configuration (endpoint, token, and status) still appear to be missing from the schema.

Is there now a supported way to manage these provisioning settings natively, or is the recommendation still to configure them out-of-band and use lifecycle ignores to prevent the configuration from being reset during subsequent applies?
Thank you!
