### ISSUE TITLE
which resource to use for general config

### ISSUE THREAD

**Issue by ahmei0** [okta/terraform-provider-okta#717]
I need to configure "Security Notification Emails" section and "Okta ThreatInsight Settings" under Security -> General. Pls advise which resource used for this config

**Comment by bogdanprodan-okta** [comment]
Hi, @ahmei0! Thanks for submitting this issue! Currently, you can not manage the "Security Notification Emails" and  "Okta ThreatInsight Settings" sections via Terraform. I will check whether they are available via API and start to work on these resources asap. Cheers!

**Comment by bogdanprodan-okta** [comment]
Duplicate of #393
