### ISSUE TITLE
network zone question

### ISSUE THREAD

**Issue by ahmei0** [okta/terraform-provider-okta#720]
I have multiple apps with their own git repos and workspaces (per app per env) e.g. and I have a global repo for common or shared config (e.g. enabling mfa factors)

* app1
* app2
* app3
* global

We need to lock signon to Australia only. So I'm trying to decide whether I create network zone just once in global repo/workspace and refer it in app workspaces as remote resource or create network zone separate for every app/workspace.

Please advise

**Comment by noinarisak** [comment]
Hey @ahmei0, I think your approach is sound. Currently, it does not look like we have a data source for `okta_network_zone` that you would reference at your app-level HCL file, which would be ideal for your situation and a lot cleaner. @bogdanprodan-okta, we should add a data source for `okta_network_zone` so it can be used by the other resource like `okta_policy_rule_signon`. 

A workaround could be to export to share file using [templatefile function](https://www.terraform.io/docs/language/functions/templatefile.html), so you can reference the exported file into your app-level HCL file.

**Comment by ahmei0** [comment]
Thanks. You guys are super quick. Yes I was exporting network zone in global workspace and importing as remote resource in app.
