### ISSUE TITLE
default signon policy

### ISSUE THREAD

**Issue by ahmei0** [okta/terraform-provider-okta#721]
is there a resource to edit default signon policy or edit default signon policy rule or edit default signon policy rul

**Comment by bogdanprodan-okta** [comment]
Hi, @ahmei0! Thanks for submitting this issue! Default sign-on policy and default sign-on policy rule are immutable, so they can not be changed via API.

**Comment by ahmei0** [comment]
@bogdanprodan-okta  but you can add a new rule to Default signon policy using control panel so why can't we have it using API

**Comment by bogdanprodan-okta** [comment]
Sure you can add new rules to the default sign-on policy:
```
data "okta_policy" "default" {
  name = "Default Policy"
  type = "OKTA_SIGN_ON"
}

resource "okta_policy_rule_signon" "test" {
  policy_id       = data.okta_policy.default.id
  name           = "My New Rule"
  status         = "ACTIVE"
}
```

**Comment by ahmei0** [comment]
Thanks that worked like a charm.
