### ISSUE TITLE
app_settings_json in okta_app_swa not exists? How to use JSON inserts for SWA?

### ISSUE THREAD

**Issue by summersonne** [okta/terraform-provider-okta#722]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.31

### Affected Resource(s)

okta_app_swa

### Expected Behavior

Data inserted into app in Okta

### Actual Behavior

Error: Unsupported argument

  on okta_app_mailjet.tf line 8, in resource "okta_app_swa" "mailjetgroup":
   8:   app_settings_json = <<JSON

An argument named "app_settings_json" is not expected here.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

resource "okta_app_swa" "mailjetgroup" {
  label             = "Mailjet"
  preconfigured_app = "mailjet"
  url               = "https://app.mailjet.com/signin"

  app_settings_json = <<JSON
{
"some": "settings"
}
JSON

If I add login / pass from UI next terraform run will stop with:

Error: failed to update SWA application: The API returned an error: Operation on application settings failed.. Causes: errorSummary: sharedUsername: The field cannot be left blank, errorSummary: sharedPassword: The field cannot be left blank

But at the same time I cannot just insert data from JSON as I usually do for okta_app_saml

How can I do this for SWA app?

**Comment by bogdanprodan-okta** [comment]
Him @summersonne! Thanks for submitting this issue! I've created a PR that should fix your issue. Here is an example of the config I've used to test this change:
```
resource "okta_app_shared_credentials" "test" {
  label             = "Mailjet"
  preconfigured_app = "mailjet"
  // url               = "https://app.mailjet.com/signin"
  shared_username = "sdfsfd"
  shared_password = "dkbfsmndfb"
}
```
I'm not sure, but `url` field is missing from JSON API response.

**Comment by mbelang** [comment]
I would also like to have the `app_json_settings` to the swa app. Using this [app](https://www.okta.com/integrations/1password-business/#capabilities) and it requires a field in the settings that I cannot set via terraform.

```
╷
│ Error: failed to update SWA application: the API returned an error: Operation on application settings failed.. Causes: errorSummary: subDomain: The field cannot be left blank
│ 
│   with okta_app_swa.one_password,
│   on 1password.tf line 1, in resource "okta_app_swa" "one_password":
│    1: resource "okta_app_swa" "one_password" {
```

**Comment by bogdanprodan-okta** [comment]
@mbelang you can try using this config:
```
resource "okta_app_auto_login" "onePass" {
  label               = "1Password Business"
  preconfigured_app   = "1password_business"
  auto_submit_toolbar = true
  reveal_password     = true
  app_settings_json   = jsonencode(
  {
    "regionType" : "com",
    "subDomain" : "terra"
  }
  )
  skip_groups         = true
  skip_users          = true
}
```

**Comment by mbelang** [comment]
@bogdanprodan-okta it works nicely except for a missing configuration and I'm not sure where to get it.
```
okta_app_auto_login.one_password: Modifying... [id=0oa4covfyrFyXdFjA5d6]
╷
│ Error: failed to update auto login application: the API returned an error: Api validation failed: PublicAppInstance. Causes: errorSummary: The settings.signOn object doesn't match the type indicated by signOnMode value or is ill defined, Status: 400 Bad Request
│ 
│   with okta_app_auto_login.one_password,
│   on 1password.tf line 1, in resource "okta_app_auto_login" "one_password":
│    1: resource "okta_app_auto_login" "one_password" {
│ 
╵
ERRO[0005] 1 error occurred:
	* exit status 1
```

I found out that `sign_on_mode` value is `BROWSER_PLUGIN` but setting this in `settings.signOn` makes terraform to see a diff.

```tf
Terraform will perform the following actions:

  # okta_app_auto_login.one_password will be updated in-place
  ~ resource "okta_app_auto_login" "one_password" {
      ~ app_settings_json          = jsonencode(
          ~ {
              + signOn     = "BROWSER_PLUGIN"
                # (2 unchanged elements hidden)
            }
        )
        id                         = "<REDACTED>"
        name                       = "1password_business"
        # (18 unchanged attributes hidden)

        # (157 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by bogdanprodan-okta** [comment]
You don't need to set `"signOnMode": "BROWSER_PLUGIN"` in the settings. 
This is JSON example of the one_password app I've created using the script provided above
```{
 "id": "0oa2e8m6kxFPdSqxG5d7",
 "name": "1password_business",
 "label": "1Password Business 2",
 "status": "ACTIVE",
 "lastUpdated": "2021-10-26T20:32:46.000Z",
 "created": "2021-10-26T20:24:37.000Z",
 "accessibility": {
  "selfService": false,
  "errorRedirectUrl": null,
  "loginRedirectUrl": null
 },
 "visibility": {
  "autoLaunch": true,
  "autoSubmitToolbar": true,
  "hide": {
   "iOS": false,
   "web": true
  },
  "appLinks": {
   "1password_business_link": true
  }
 },
 "features": [],
 "signOnMode": "BROWSER_PLUGIN",
 "credentials": {
  "scheme": "SHARED_USERNAME_AND_PASSWORD",
  "userNameTemplate": {
   "template": "${source.login}",
   "type": "BUILT_IN"
  },
  "userName": "heello",
  "password": {},
  "revealPassword": false,
  "signing": {}
 },
 "settings": {
  "app": {
   "regionType": "eu",
   "subDomain": "terra"
  },
  "notifications": {
   "vpn": {
    "network": {
     "connection": "DISABLED"
    },
    "message": null,
    "helpUrl": null
   }
  },
  "notes": {
   "admin": null,
   "enduser": "Hello"
  }
 }
}
```

**Comment by mbelang** [comment]
If I do that, I get the error I pasted above. I even tried to set `settings.signOn` to `""` and terraform always see a diff but the api seems happy about it.

**Comment by bogdanprodan-okta** [comment]
Could you please send me the example of the resource you are trying to create so I can try and reproduce it?

**Comment by mbelang** [comment]
```hcl
resource "okta_app_auto_login" "one_password" {
  label                   = "1Password"
  preconfigured_app       = "1password_business"
  credentials_scheme      = "EDIT_PASSWORD_ONLY"
  auto_submit_toolbar     = true
  user_name_template      = "user.email"
  user_name_template_type = "CUSTOM"

  app_settings_json = jsonencode({
    "regionType" : "com",
    "subDomain" : "redacted",
  })

  admin_note = <<EOF
Provisioning: Fully automated. Assign vaults with based on groups.
Deprovisioning: Fully automated.
Configuration: 1Password groups are managed manually in 1Password by admin.

See 1Password in Okta Runbook.
EOF

  # Even set to true, those 2 options doesn't seem to skip if the lifecycle is removed
  skip_groups = true
  skip_users  = true

  lifecycle {
    ignore_changes = [
      groups, #Groups are assigned using okta_app_group_assignment resource
      users   #Skip for now until we manage users with groups otherwise, everyone would be kicked out.
    ]
  }

}
```

**Comment by mbelang** [comment]
Ok, after removing again the `settings.signOn` the apply works nicely. There was probably something bogus in the state :shrug:

**Comment by bogdanprodan-okta** [comment]
@mbelang awesome!

**Comment by mbelang** [comment]
Appreciate the help :)
