### ISSUE TITLE
SAML JIT Settings 

### ISSUE THREAD

**Issue by karlsequeira** [okta/terraform-provider-okta#729]
### Community Note
Please allow for updating for this is an option under JIT Settings.
- Update of attributes for existing users check. 
- Reactivation Settings

### New or Affected Resource(s)

- okta_app_saml

update_attr_existing_users
reactiveate_deactivated_users
unsuspend_suspended_users

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @karlsequeira! Thanks for submitting this issue! I'll try to find Okta API that manages SAML JIT Settings and try to add it to the provider. Cheers!

**Comment by karlsequeira** [comment]
@bogdanprodan-okta  any update on this?

**Comment by karlsequeira** [comment]
@bogdanprodan-okta  this has been closed for inactivity. Can we please reopen.

**Comment by monde** [comment]
@karlsequeira I'll be looking in to this.

**Comment by monde** [comment]
@karlsequeira can you give me a pseudo code example of what this config would look like if it existed? Also, seems like you read through the API documentation about the behavior, give me a link to what you referenced if you have that handy also.

**Comment by monde** [comment]
Closing for now, please reopen when there is more information.

**Comment by karlsequeira** [comment]
@bogdanprodan-okta  Can you please reopen. Every time I run the update on using okta_idp_saml, JIT turns off.

**Comment by MrFishFinger** [comment]
hi @monde , @bogdanprodan-okta , could you please reopen this ticket?

it would be great if it was possible to manage the JIT settings of a SAML IdP provider using the `okta_app_saml` resource.

In particular, we would like to be able to manage the group list found in the `.policy.provisioning.groups.filter` field of the object.

The Okta API for this is documented here: https://developer.okta.com/docs/reference/api/idps/#provisioning-policy-object

**Comment by exitcode0** [comment]
> hi @monde , @bogdanprodan-okta , could you please reopen this ticket?
> 
> it would be great if it was possible to manage the JIT settings of a SAML IdP provider using the `okta_app_saml` resource.
> 
> In particular, we would like to be able to manage the group list found in the `.policy.provisioning.groups.filter` field of the object.
> 
> The Okta API for this is documented here: https://developer.okta.com/docs/reference/api/idps/#provisioning-policy-object
> 
> i imagine pseudocode might look something like this:
> 
> ```
> resource "okta_app_saml" "PSEUDOCODE" {
>   label   = "example"
>   sso_url = "https://example.com"
>   ...
> 
>   jit_provisioning {
>     ...
>     groups_filter = ["000dummmygroupid0001", "000dummmygroupid0002"]
>     ...
>   }
> }
> ```

I believe the API reference you've linked here pertains to SAML IDPs rather than SAML Applications?

We should also void the necropost if we can and instead create a new issue
