### ISSUE TITLE
`okta_app_oauth_api_scope` Doesn't Diff `scopes` Properly resulting in Changes For Subsequent Plan/Applies

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#730]
The `okta_app_oauth_api_scope` resource will detect a change based on the ordering of `scopes`. Subsequent `terraform plan` or `terraform apply` commands will constantly show changed order after a successful `terraform apply`. The behavior of the resource should properly detect ordering issues from API and show as not changed.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
`1.0.9`

### Affected Resource(s)

- `okta_app_oauth_api_scope`

### Terraform Configuration Files

```hcl
resource "okta_app_oauth" "sample_app" {
  label                      = "test-service"
  type                       = "service"
  response_types             = ["token"]
  grant_types                = ["client_credentials"]
  token_endpoint_auth_method = "private_key_jwt"
  jwks {
    kty = "RSA"
    e   = "AQAB"
    n   = "invalid-test"
  }
}

resource "okta_app_oauth_api_scope" "default" {
  app_id = okta_app_oauth.sample_app.id
  issuer = "https://{okta-domain}.okta.com"
  scopes = [
    "okta.apps.manage",
    "okta.authorizationServers.manage",
    "okta.factors.manage",
    "okta.groups.manage",
    "okta.users.manage",
    "okta.roles.manage",
  ]
}
```

### Expected Behavior

Subsequent plan/applies should not pick up a diff based. Observe the sample command output. Applying the changeset and then re-planning/applying results in continued diff.

### Actual Behavior
```
Terraform will perform the following actions:

  # okta_app_oauth_api_scope.default will be updated in-place
  ~ resource "okta_app_oauth_api_scope" "default" {
        id     = "xxxxxxxxxxxxxxxx"
      ~ scopes = [
          - "okta.authorizationServers.manage",
            "okta.apps.manage",
          + "okta.authorizationServers.manage",
          + "okta.factors.manage",
            "okta.groups.manage",
            "okta.users.manage",
          - "okta.factors.manage",
            "okta.roles.manage",
        ]
        # (2 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform apply`

**Comment by bogdanprodan-okta** [comment]
Hi, @virgofx! Thanks for submitting this issue! I'll try to reproduce it and create a fix asap. Cheers!
