### ISSUE TITLE
Datasource for reading claims of an authorization server

### ISSUE THREAD

**Issue by ashwini-desai** [okta/terraform-provider-okta#733]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Need a terraform datasource for reading claims of an authorization server.

### New or Affected Resource(s)

- okta_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by ashwini-desai** [comment]
@bogdanprodan-okta : I can see that okta-sdk-golang already has ability to read the claims [here](https://github.com/okta/okta-sdk-golang/blob/master/okta/authorizationServer.go#L146-L164). We currently need this. 
Planning to follow [this](https://github.com/okta/terraform-provider-okta/blob/a43cd9c0fd1075b5e989a6289344f5eff1ab3bfa/okta/data_source_okta_auth_server_scopes.go) datasource code for reading scopes. If I am on the right path, I can give this a try.

**Comment by bogdanprodan-okta** [comment]
Hi @ashwini-desai! Thanks for submitting this issue! I'll create a PR shortly and add this data source to the next release

**Comment by ashwini-desai** [comment]
@bogdanprodan-okta : Okay, by when can we expect the next release?

**Comment by bogdanprodan-okta** [comment]
@ashwini-desai hopefully this Friday :)

**Comment by ashwini-desai** [comment]
@bogdanprodan-okta : Thank you so much for the quick PR 👍
