### ISSUE TITLE
Resource okta_app_group_assignment receive HTTP code 500 from OKTA API

### ISSUE THREAD

**Issue by faurel** [okta/terraform-provider-okta#738]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`v1.0.6`

### Affected Resource(s)

- okta_app_group_assignment

### Terraform Configuration Files

```hcl
resource "okta_app_group_assignment" "assignment" {
  app_id   = <myappid>
  group_id = <mygroupid>
}
```

### Debug Output

```
---[ REQUEST ]---------------------------------------
PUT /api/v1/apps/__REDACTED__/groups/__REDACTED__ HTTP/1.1
Host: __REDACTED__.okta.com
User-Agent: okta-sdk-golang/2.8.0 golang/go1.17.1 linux/amd64 okta-terraform/3.15.0 
Content-Length: 15
Accept: application/json
Authorization: SSWS __REDACTED__
Content-Type: application/json
Accept-Encoding: gzip

{
 "priority": 0
}
......

---[ RESPONSE ]--------------------------------------
HTTP/2.0 500 Internal Server Error
.....
{
 "errorCode": "E0000009",
 "errorSummary": "Internal Server Error",
 "errorLink": "E0000009",
 "errorId": "oaeJ8leHuEPRAOzDePDymyZQA",
 "errorCauses": []
}
```

### Expected Behavior

`<mygroupid>` should be assigned to application `<myappid>` and `terraform apply` should end successfully.

### Actual Behavior

We have successfully created more than 200 groups assignment using that terraform resource. Now that we want to add one extra group assignment, terraform is constantly failing with the error
```
Error: failed to create application group assignment: Put "https://__REDACTED__.okta.com/api/v1/apps/__REDACTED__/groups/__REDACTED__": the API returned an error: Internal Server Error, x-okta-request-id=__REDACTED__ giving up after 6 attempt(s)
```
By enabling terraform debug output, we see an HTTP code 500 on the first call to OKTA API

To narrow down the issue, I tried the following

1. I performed the same operation from OKTA console: **SUCCESS !** The group was successfully assigned (the PUT on OKTA API returns 200)
2. I used `curl` to perform the same API call, I used this [example](https://developer.okta.com/docs/reference/api/apps/#request-example-35): **SUCCESS  !** I received a response with HTTP code 200
3. I reused the same `curl` command as previously but added the body below as the `okta_app_group_assignment` resource is doing:
```
{
 "priority": 0
}
```
**FAILURE:** I managed to reproduce the same behavior as the OKTA provider.
I don't know what this priority is about, it is not even documented in [OKTA API documentation](https://developer.okta.com/docs/reference/api/apps/#assign-group-to-application) but I would suggest to take it out :smile:

### Steps to Reproduce

Try to create lot of group assignments using `okta_app_group_assignment` resource. The failure should come up at some point in time.

**Comment by bogdanprodan-okta** [comment]
Hi, @faurel! Thanks for submitting this issue! I've tried to reproduce this issue, but just couldn't. You can also refer to [this comment](https://github.com/okta/terraform-provider-okta/issues/736#issuecomment-949540683) and also submit the request via Okta support. 
I've created a PR, so the priority field won't be present in the request unless it's specified in the resource.

**Comment by fatbasstard** [comment]
Small FYI: We've been hitting this issue as well on "random" workspaces almost. After opening and having a call with Okta they also suggested to leave out the priority if the order is not needed explicitly (we've been setting all assignments to priority `1`). 

So this being fixed is really ready for us as well.
