### ISSUE TITLE
Datasource for reading trusted origin of an Authorisation server enhancement new-data-source

### ISSUE THREAD

**Issue by Shrirang97** [okta/terraform-provider-okta#740]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Need a terraform datasource for reading trusted origins of an Authorisation server.

### New or Affected Resource(s)

- okta_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- https://github.com/okta/okta-sdk-golang/blob/master/okta/trustedOrigin.go

**Comment by Shrirang97** [comment]
@bogdanprodan-okta : I can see that [okta-sdk-golang](https://github.com/okta/okta-sdk-golang/) already has ability to read the trusted origins [here](https://github.com/okta/okta-sdk-golang/blob/master/okta/trustedOrigin.go#L120). We currently need this. If I am on the right path, I can give this a try.

**Comment by bogdanprodan-okta** [comment]
Hi, @Shrirang97! Thanks for submitting this issue! If you like, you can go ahead and create a PR, you gonna help alot. I'll gladly review it!

**Comment by Shrirang97** [comment]
@bogdanprodan-okta Can you please review the PR?
