### ISSUE TITLE
okta_app_group_assignment removes users on 2nd plan&apply

### ISSUE THREAD

**Issue by tlotter** [okta/terraform-provider-okta#742]
### Terraform Version
terraform -v                         
Terraform v1.0.9
on darwin_amd64
+ provider registry.terraform.io/okta/okta v3.15.0

### Affected Resource(s)
- okta v3.15.0

### Terraform Configuration Files

okta.tf
```hcl
variable "org_name" {}
variable "api_token" {}
variable "base_url" {}

terraform {
 required_providers {
   okta = {
     source = "okta/okta"
     version = "~> 3.15"
   }
 }
}

provider "okta" {
 org_name  = var.org_name
 api_token = var.api_token
 base_url  = var.base_url
}

resource okta_app_oauth tf-example-app {
 label                      = "example from Terraform"
 type                       = "web"
 grant_types                = ["authorization_code"]
 redirect_uris              = ["http://localhost:8000"]
 response_types             = ["code"]
}

data okta_group everyone {
 name = "Everyone"
}

resource okta_app_group_assignment tf-example-app {
 app_id   = "${okta_app_oauth.tf-example-app.id}"
 group_id = "${data.okta_group.everyone.id}"
}
```
okta.tfvars
```hcl
org_name        = "YOURSUBDOMAIN"
api_token       = "YOURAPITOKEN"
base_url        = "okta.com"
```

### Expected Behavior

I run terraform plan & apply and it created the application  "example from Terraform" and assigned the group "Everyone".
I run terraform plan & apply a second time and the group "Everyone" should still be assigned to the application, but it's not.

### Actual Behavior

After running plan & apply a second time, all users are removed from the application.

### Steps to Reproduce

Create the two terraform files shown above.
Run the following commands, they will create the application and assign everyone.

```console
terraform init
terraform plan -var-file okta.tfvars
terraform apply -var-file okta.tfvars
```

Run the following commands and all users will be removed from the application.
```console
terraform plan -var-file okta.tfvars
terraform apply -var-file okta.tfvars
```

We reproduced this issue with multiple colleagues. I'm an Okta employee, you can also slack me for more questions.

**Comment by bogdanprodan-okta** [comment]
Hi, @tlotter! Thanks for submitting this issue! If you want to manage groups/users outside the app resource, set `skip_users` and `skip_groups` values to `true`. In this case, terraform will skip these fields altogether. 
Currently, `users` and `groups` fields are deprecated in all app-related resources and will be removed once we release the 4.0.0 version of the Okta provider.
