### ISSUE TITLE
Okta MFA Policy Default Rules

### ISSUE THREAD

**Issue by agosto-lorinronken** [okta/terraform-provider-okta#744]
Hello,

I am working on creating some MFA Enrollement Policies in Okta via Terraform and running into a minor issue with attempting to create a "Default Rule" via Terraform.  Essentially, I am looking to create a rule in each of the policies I create named "Default Rule" to stay consistent with the rules in the Default MFA Policy, however, when I do that I encounter the following error:

```
Error: failed to create MFA policy rule: Default Rule is immutable
```

Is there a possible work around for this?  I know I can manually create the rules in Okta named 'Default Rule' within each Policy, but would like to do it in Terraform if possible.  Maybe this is just a limitation of the Okta API, however would it be possible to implement something similiarly to how the Default MFA policy resource works ([okta_policy_mfa_default](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_mfa_default))?  Possibly creating another resource named `okta_policy_rule_mfa_default` (just an idea). 

Thank you!

**Comment by virgofx** [comment]
I noticed there wasn't a `_default` for the default policy signon as well. 

However, you can easily just import it once you have the ID and then still manage it. Same applies for it's default rule.

e.g.
```
# Note: This policy is mostly immutable so the following name/description need to remain consistent.
resource "okta_policy_signon" "default" {
  name            = "Default Policy"
  description     = "The default policy applies in all situations if no other policy applies."
  status          = "ACTIVE"
  groups_included = ["${data.okta_group.everyone.id}"]
}
```

**Comment by bogdanprodan-okta** [comment]
Hi, @agosto-lorinronken! Have you managed to import the MFA policy default rule?

**Comment by agosto-lorinronken** [comment]
Hi,

Sorry for the late reply.  Yes, I managed to import the rule and get it working per the suggested way.

Thank you!
