### ISSUE TITLE
okta_policy_rule_mfa resource support for users accessing specific applications

### ISSUE THREAD

**Issue by hueydn** [okta/terraform-provider-okta#745]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Can we add the ability to update specific mfa policy rules beyond what is currently available. Specifically support to assign specific apps only using the rule. I see that this is available in the API so it should be doable
```
[
    {
        "id": "0pr1neypylU0mh3Qt1d7",
        "status": "ACTIVE",
        "name": "MFA Rule",
        "priority": 1,
        "created": null,
        "lastUpdated": null,
        "system": false,
        "conditions": {
            "people": {
                "users": {
                    "exclude": []
                }
            },
            "network": {
                "connection": "ANYWHERE"
            },
            **"app": {
                "include": [
                    {
                        "type": "APP",
                        "id": "0oap6hpcaCBsto0v61d6"
                    },
                    {
                        "type": "APP",
                        "id": "0oaqov3lhp2TSBmFp1d6"
                    }
                ],**
                "exclude": [
                    {
                        "type": "APP_TYPE",
                        "name": "okta"
                    }
                ]
            }
        },
        "actions": {
            "enroll": {
                "self": "LOGIN"
            }
        },
```

### Affected Resources
- okta_policy_rule_mfa

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @huy-keydata! Thanks for submitting this issue! I'll start to work on this functionality asap.

**Comment by hueydn** [comment]
> Hi, @huy-keydata! Thanks for submitting this issue! I'll start to work on this functionality asap.

Thanks this will help with my deployment because it seems that every time my terraform deployment runs and makes a change to this resource it removes all the apps assigned even though I can't set values for the app assignments.

**Comment by bogdanprodan-okta** [comment]
Hi, @huy-keydata! I will add this functionality to the rule. Just FYI, app conditions within the MFA enrollment policies are currently not supported on OIE, but still gonna work in 'classic' orgs.

**Comment by hueydn** [comment]
> Hi, @huy-keydata! I will add this functionality to the rule. Just FYI, app conditions within the MFA enrollment policies are currently not supported on OIE, but still gonna work in 'classic' orgs.

Ok good to know we are currently still on classic so it won't be a problem for us until we migrate to OIE. Also can a flag be set to uncheck Okta access and only allow Application access in the rule settings?

**Comment by hueydn** [comment]
How about adding support for this too:
"exclude": [
                    {
                        "type": "APP_TYPE",
                        "name": "okta"
                    }

Or do you need me to open another issue?
