### ISSUE TITLE
Event Hook verification

### ISSUE THREAD

**Issue by mcrobbj-abrdn** [okta/terraform-provider-okta#748]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is no way to trigger a verification of an event hook via terraform

### New or Affected Resource(s)

- okta_event_hook

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @mcrobbj-abrdn! Thanks for submitting this issue! All create new `okta_event_hook_verification` (with the same behavior as `okta_domain_verification`) and add it to the provider asap.
