### ISSUE TITLE
okta_org_configuration doesn't pick up logo - an example would help

### ISSUE THREAD

**Issue by mcrobbj-abrdn** [okta/terraform-provider-okta#754]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_org_configuration

### Terraform Configuration Files

resource "okta_org_configuration" "myOrg" {
  company_name = "myOrg"
  website      = "https://myOrg.com"
  logo         = "myOrg.png"
}

myOrg.png is in the same directory as the terraform files and where the command is being executed from

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Create Org with logo

### Actual Behavior

Complains it cant find the logo

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @mcrobbj-abrdn! Thanks for submitting this issue! I've just tested the script you've provided and it works fine.
`terra.tf` is my terraform file and `orgLogo.jpeg` file was used for the logo.
```
resource "okta_org_configuration" "myOrg" {
  company_name = "Hashicorp CI Terraform Provider Okta"
  website = "https://terraform.com"
  logo = "orgLogo.jpeg"
}
```
<img width="290" alt="Screenshot 2021-10-28 at 17 48 06" src="https://user-images.githubusercontent.com/71279414/139281229-8b73a9bd-d917-446f-8e24-94b9199725ef.png">

**Comment by bogdanprodan-okta** [comment]
Closing this issue for now. If the problem still exists, please leave a comment here or create another one.
