### ISSUE TITLE
Okta OIDC Application Custom URL

### ISSUE THREAD

**Issue by agosto-lorinronken** [okta/terraform-provider-okta#756]
Hello,

I am having trouble deploying an OIDC Oauth Application using a custom URL via Terraform.  When I set the attribute `issuer_mode` to `CUSTOM_URL` it is expecting a custom domain to be configured, however, I don't currently see an option for this (such as `issuer`).   Could someone help me identify what the Terraform setting is for setting the custom domain?  I have included the error message below for reference:

```
Error: failed to create OAuth application: the API returned an error: Api validation failed: issuerMode. Causes: errorSummary: issuerMode: 'issuerMode' can not be set to CUSTOM_URL without a custom domain configured.
```

Thank you!

**Comment by bogdanprodan-okta** [comment]
Hi, @agosto-lorinronken! Thanks for submitting this issue! The reason for that is you don't have a custom domain configured. You can read more details [here](https://developer.okta.com/docs/reference/api/apps/#details). You have to [configure a custom domain](https://developer.okta.com/docs/guides/custom-url-domain/overview/) for this issuer mode. You can use terraform resources for that as well.
 - [Custom domain](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/domain)
 - [Domain certificate](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/domain_certificate)
 - [Domain verification](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/domain_verification)

**Comment by bogdanprodan-okta** [comment]
Closing this issue for now. If you have more questions, please leave a comment here or create another issue.
