### ISSUE TITLE
Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by ahmei0** [okta/terraform-provider-okta#758]
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ okta_profile_mapping.app_to_user_profile_mapping_local[0] to include new
│ values learned so far during apply, provider
│ "registry.terraform.io/okta/okta" produced an invalid new value for
│ .always_apply: was cty.False, but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ okta_profile_mapping.app_to_user_profile_mapping to include new values
│ learned so far during apply, provider "registry.terraform.io/okta/okta"
│ produced an invalid new value for .always_apply: was cty.False, but now
│ null.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
##[error]Error: The process '/usr/local/bin/terraform' failed with exit code 1

**Comment by bogdanprodan-okta** [comment]
Hi, @ahmei0! Thanks for submitting this issue! Please provide an example of scripts so I can reproduce this bug.

**Comment by ahmei0** [comment]
ok_profile_mapping created using version 3.16.0 or lower.

re-ran tf using version 3.17.0 and got this error probably because behaviour of always_apply changed as this attribute was introduced in 3.17.0. Expectation here to be backward compatible even if I don't add always_apply to my scripts. If I have to add it, what value I set it that won't give above error? I tried with always_apply=false but it still gave me same error

```
resource "okta_profile_mapping" "okta_profile_mapping" {
  source_id          = okta_app_oauth.myacc_spa.id
  target_id          = data.okta_user_profile_mapping_source.myaccount_user.id
  delete_when_absent = true

  mappings {
    id         = "login"
    expression = "appuser.userName"
  }
  mappings {
    id         = "firstName"
    expression = "appuser.given_name"
  }
  mappings {
    id         = "lastName"
    expression = "appuser.family_name"
  }
  mappings {
    id         = "login"
    expression = "appuser.userName"
  }
  mappings {
    id         = "email"
    expression = "appuser.userName"
  }
  mappings {
    id         = okta_user_schema_property.user_myAccount.index
    expression = "appuser.${okta_app_user_schema_property.appuser_myAccount.index}"
  }
  depends_on = [
    okta_app_user_schema_property.appuser_myAccount,
    okta_user_schema_property.user_myAccount
  ]
}

**Comment by bogdanprodan-okta** [comment]
@ahmei0 what terraform version are using? I used v1.0.9 to reproduce the error, but no luck.

I've created `okta_profile_mapping` using 3.16.0 and the script above. State file:
```
"schema_version": 0,
          "attributes": {
            "delete_when_absent": true,
            "id": "prm12k1h7xzbO04ya0h8",
            "mappings": [
              {
                "expression": "appuser.email",
                "id": "email",
                "push_status": "DONT_PUSH"
              },
```              
Updated the provider to 3.17.0 using `terraform init -upgrade`. Run `terraform apply`. State file:
```
 {
          "schema_version": 0,
          "attributes": {
            "always_apply": null,
            "delete_when_absent": true,
            "id": "prm12k1h7xzbO04ya0h8",
            "mappings": [
              {
                "expression": "appuser.email",
                "id": "email",
                "push_status": "DONT_PUSH"
              },
```
Set `always_apply = false` in the terraform scripts and run `terraform apply`. No error whatsoever.

**Comment by ahmei0** [comment]
Terraform v1.0.9

I did not run 'terraform init -upgrade' . 

Just normal terraform init and apply. Since I don't have fixed okta provider version so it picks the latest one and fails with above error

**Comment by ahmei0** [comment]
tried exactly same as you.
tf version 1.0.9 and terraform init -upgrade, didn't work. 

Just realised user -> app mapping works but above error is on app -> user mapping only. Did you try this scenario?
![image](https://user-images.githubusercontent.com/62230464/139517406-33a18048-c712-4297-9bcc-0189f42b969b.png)

**Comment by ahmei0** [comment]
![image](https://user-images.githubusercontent.com/62230464/139517486-041b5a97-330b-4ca3-b9a5-d52be088931c.png)

**Comment by ahmei0** [comment]
![image](https://user-images.githubusercontent.com/62230464/139517500-c5d497ff-9c84-4137-aac4-3b3829afb955.png)

**Comment by ahmei0** [comment]
apparently, resource created in previous versions have '"always_apply": null' and new version isn't able to change null to false. That means current provider version isn't backward compatible.

I edited state file manually, changed null to false and it worked even without adding  'always_apply =false' to the code

**Comment by ahmei0** [comment]
@bogdanprodan-okta   any update on this

**Comment by bogdanprodan-okta** [comment]
No, no updates. I've asked several people to reproduce the problem and they weren't able to do so. Maybe someone from the community will hit the same issue and post the steps here.
