### ISSUE TITLE
Issue on apply with okta_policy_rule_signon  errorSummary: conditions: Invalid condition type specified: riskScore.

### ISSUE THREAD

**Issue by codelkirby** [okta/terraform-provider-okta#759]
I'm trying to apply a policy rule to a signon policy but it fails with the following:

okta_policy_rule_signon.SignonMFARule: Creating...
╷
│ Error: failed to create sign-on policy rule: failed to create policy rule: the API returned an error: Api validation failed: conditions. Causes: errorSummary: conditions: Invalid condition type specified: riskScore.
│ 
│   with okta_policy_rule_signon.SignonMFARule,
│   on mfa_policy.tf line 37, in resource "okta_policy_rule_signon" "SignonMFARule":
│   37: resource "okta_policy_rule_signon" "SignonMFARule" {
│ 

Not sure if I missed a dependency.

If create the rule manually in okta and then import it in terraform, the import works, but then any subsequent terraform apply will fail with the same error, when I run terraform destroy, this is the state terraform has from the import:

   okta_policy_rule_signon.SignonMFARule will be destroyed
  - resource "okta_policy_rule_signon" "SignonMFARule" {
      - access              = "ALLOW" -> null
      - authtype            = "ANY" -> null
      - id                  = "0pr52o5j0f0qHmhjt696" -> null
      - mfa_lifetime        = 0 -> null
      - mfa_prompt          = "ALWAYS" -> null
      - mfa_remember_device = false -> null
      - mfa_required        = true -> null
      - name                = "SignonMFARule" -> null
      - network_connection  = "ANYWHERE" -> null
      - policy_id           = "00p52ih1kX83yNoP3696" -> null
      - priority            = 1 -> null
      - session_idle        = 120 -> null
      - session_lifetime    = 0 -> null
      - session_persistent  = false -> null
      - status              = "ACTIVE" -> null
      - users_excluded      = [] -> null
    }

Using Okta 3.17

The complete example:

data "okta_group" "everyone" {
}
resource "okta_policy_signon" "SignonMFAPolicy" {
  name            = "SigonMFA Policy"
  status          = "ACTIVE"
  description     = "Enable MFA for everyone"
  groups_included = ["${data.okta_group.everyone.id}"]
}

resource "okta_policy_rule_signon" "SignonMFARule" {
  access              = "ALLOW"
  authtype            = "ANY"
  mfa_lifetime        = 0
  mfa_prompt          = "ALWAYS"
  mfa_remember_device = false
  mfa_required        = true
  name                = "SignonMFARule"
  network_connection  = "ANYWHERE"
  policy_id           = okta_policy_signon.SignonMFAPolicy.id
  priority            = 1
  session_idle        = 120
  session_lifetime    = 0
  session_persistent  = false
  status              = "ACTIVE"
  users_excluded      = []
}

**Comment by bogdanprodan-okta** [comment]
Hi, @codelkirby! Thanks for submitting this issue! I think it’s because of this feature flag - `RISK_SCORING`. It is disabled in your org, and that's why you get this error.

**Comment by bogdanprodan-okta** [comment]
@codelkirby another workaround would be to set `risc_level = ""`. In this case, you won't get any errors. I'm closing this issue for now. If you have other questions, please leave a comment here or create another issue.

**Comment by conodelial2f** [comment]
@bogdanprodan-okta, another feather your cap my friend! that did the trick. Thank you.

**Comment by yuko12** [comment]
it seems that workaround mentioned above `risc_level = ""` doesn't work in okta terraform provider v4.8.1 anymore.

**Comment by kathleen-vg** [comment]
I can confirm that risc_level = "" no longer works.  Is there an update on recommendations for this?

**Comment by yuko12** [comment]
> I can confirm that risc_level = "" no longer works. Is there an update on recommendations for this?

You can specify it like below to make it work:

```
resource "okta_policy_rule_signon" "aws_vpn_whitelisting_deny_rule" {
  policy_id          = okta_policy_signon.aws_vpn_whitelisting.id
  name               = "aws-vpn-whitelisting-deny-rule"
  access             = "DENY"
  status             = "ACTIVE"
  network_connection = "ZONE"
  identity_provider  = "ANY"
  network_excludes   = [okta_network_zone.remoteaccessvpn.id]
  risk_level         = ""
  risc_level         = ""
}
```

**Comment by posquit0** [comment]
I reopened this as a new issue: #2504
