### ISSUE TITLE
Resource okta_app_saml attribute metadata is a heredoc, not "raw SAML metadata in XML"

### ISSUE THREAD

**Issue by jimrazmus** [okta/terraform-provider-okta#768]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.10
on darwin_amd64

### Affected Resource(s)

- okta_app_saml (metadata attribute)

### Terraform Configuration Files

```hcl
provider "okta" {
  org_name  = var.okta_org_name
  base_url  = var.okta_base_url
  api_token = var.okta_api_token
}

data "template_file" "app_settings" {
  template = file("${path.module}/app-settings.json.tpl")
  vars = {
    AWS_ACCT_ID = var.aws_acct_id
  }
}

resource "okta_app_saml" "saml" {
  app_settings_json = data.template_file.app_settings.rendered
  label             = "AWS SAML - ${var.aws_acct_id}"
  preconfigured_app = "amazon_aws"
}

output "metadata" {
  value = okta_app_saml.saml.metadata
}
```

### Expected Behavior

The metadata attribute should provide "raw SAML metadata in XML" as per the docs that is suitable for passing into the saml_metadata_document argument of an "aws_iam_saml_provider" resource.

### Actual Behavior

The metadata attribute begins and ends with the heredoc declarations "<<EOT" and "EOT"

### Steps to Reproduce

1. `terraform apply`

**Comment by bogdanprodan-okta** [comment]
Hi, @jimrazmus! Thanks for submitting this issue! I think this is [expected behavior](https://github.com/hashicorp/terraform/issues/27162) for the terraform. You can use `terraform output -raw metadata` to print the metadata without EOTs.

**Comment by bogdanprodan-okta** [comment]
Hi, @jimrazmus! Is this still an issue for you?

**Comment by bogdanprodan-okta** [comment]
Closing this issue for now. If you have any questions, please write them here or create another issue. Cheers!

**Comment by jimrazmus** [comment]
This is not an issue and closing the ticket is fine.
