### ISSUE TITLE
You do not have permission to access the feature

### ISSUE THREAD

**Issue by karlsequeira** [okta/terraform-provider-okta#773]
### Community Note
Getting the following when applying in prod. This works fine in lower environments.  I am using an admin token with the same access in other environments. Please do let me know if I can missing some feature access. 

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.13

### Affected Resource(s)

- okta_user_profile_mapping_source

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior
data.okta_user_profile_mapping_source.user: Reading...

Error: failed to find profile mapping source: the API returned an error: You do not have permission to access the feature you are requesting

  on main.tf line 55, in data "okta_user_profile_mapping_source" "user":
  55: data "okta_user_profile_mapping_source" "user" {

**Comment by bogdanprodan-okta** [comment]
Hi, @karlsequeira! Thanks for submitting this issue! You should reach Okta Support so they enable this feature in your org.

**Comment by bogdanprodan-okta** [comment]
Hi, @karlsequeira! Have you managed to fix this?

**Comment by karlsequeira** [comment]
Yes. Okta support was able to enable the feature that was missing. Thanks a lot for all the support.
