### ISSUE TITLE
okta_idp_saml azure ad

### ISSUE THREAD

**Issue by ahmei0** [okta/terraform-provider-okta#774]
I need to use okta_idp_saml to configure azure ad idp. Please advise how I assign aad certificate value to kid

Example here doesn't really help as it is creating app first and getting cert from app attribute, not sure why.
https://github.com/okta/terraform-provider-okta/blob/master/examples/okta_idp_saml/datasource_id.tf

**Comment by bogdanprodan-okta** [comment]
Hi, @ahmei0! Thanks for submitting this issue! You can find information regarding the certs here
 - https://developer.okta.com/docs/reference/api/idps/#add-x-509-certificate-public-key
 - https://registry.terraform.io/providers/okta/okta/latest/docs/resources/idp_saml_key#example-usage

**Comment by ahmei0** [comment]
Thanks, got that working :)
