### ISSUE TITLE
custom attribute for saml user profile

### ISSUE THREAD

**Issue by ahmei0** [okta/terraform-provider-okta#776]
I'm creating a custom attribute for saml idp profile, trying to figure out what user_type value would I use for saml idp profile?

```
resource "okta_user_schema_property" "upn" {
  index       = "upn"
  title       = "AAD upn"
  type        = "string"
  external_name = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
  master      = "OKTA"
  scope       = "SELF"
  user_type   = ""
}

![image](https://user-images.githubusercontent.com/62230464/140059048-4b25d557-c384-4b04-a14c-4c5913646fa9.png)

**Comment by bogdanprodan-okta** [comment]
Hi, @ahmei0! Thanks for submitting this issue! You can use `default` or an ID of the custom user types.

**Comment by ahmei0** [comment]
Wouldn't default set attribute on User default profile? I need to set custom attribute on SAML Idp profile as given on this screenshot 
![image](https://user-images.githubusercontent.com/62230464/140060512-eeb5bee8-ffd9-434e-9853-78ce341c61ff.png)

**Comment by bogdanprodan-okta** [comment]
You can try something like this:
```
data "okta_user_type" "azure" {
  name = "saml_idp"
}

resource "okta_user_schema_property" "upn" {
  index       = "upn"
  title       = "AAD upn"
  type        = "string"
  external_name = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
  master      = "OKTA"
  scope       = "SELF"
  user_type   = okta_user_type.azure.id
}
```

**Comment by ahmei0** [comment]
Did not work 

```
data "okta_user_type" "saml_idp_profile" {
  name = "azure-ad User"
}


│ Error: user type 'azure-ad User' does not exist
│ 
│   with data.okta_user_type.saml_idp_profile,
│   on idp_saml.tf line 77, in data "okta_user_type" "saml_idp_profile":
│   77: data "okta_user_type" "saml_idp_profile" {

**Comment by ahmei0** [comment]
Error: user type 'saml_idp' does not exist
│ 
│   with data.okta_user_type.saml_idp_profile,
│   on idp_saml.tf line 77, in data "okta_user_type" "saml_idp_profile":
│   77: data "okta_user_type" "saml_idp_profile" {

**Comment by bogdanprodan-okta** [comment]
In your case, you can use `default`, since you only have one user type for all the providers. You can create your own, so it will look something like this:
<img width="774" alt="Screenshot 2021-11-03 at 15 11 12" src="https://user-images.githubusercontent.com/71279414/140066050-eb6ad494-5a03-43e7-9054-bf4bc307eae1.png">
 
 If you want to create a property for users in specific app, you should use `okta_app_user_schema_property` resource

**Comment by ahmei0** [comment]
I tried with default already but I think you are not getting my point. I have 3 types of profiles.

1- Okta - User default
2- Apps - app profiles
3- IDP - SAML

First 2 are working fine, but I'm trying to figure out how to add attributes to IDP profile. Setting user_type = default adds custom attribute to 1 above not 3. What you are suggesting is for 1 

![image](https://user-images.githubusercontent.com/62230464/140067258-345a24b0-698e-4f31-a7d4-70d5bc77d44a.png)

**Comment by bogdanprodan-okta** [comment]
You should use `okta_app_user_schema_property` to add custom attributes to your IDP providers.

**Comment by ahmei0** [comment]
What would I use for app_id in that case ? actually I tried that as well to start with, didn't work. 

![image](https://user-images.githubusercontent.com/62230464/140070177-1df3fe8d-d129-499f-9730-5b2930780220.png)

**Comment by bogdanprodan-okta** [comment]
```
data "okta_idp_saml" "test" {
  name = "Name of the IdP"
}

resource "okta_app_user_schema_property" "test" {
  app_id      = okta_idp_saml.test.id
 //...
}
```

**Comment by ahmei0** [comment]
fails with following error. It doesn't recognise it as idp. It tries to treat it as an app and find it as app and fails

Error: failed to update custom app user schema property: the API returned an error: Not found: Resource not found: 0oa11kxpdsaLgdl3T3l7 (AppInstance)
│ 
│   with okta_app_user_schema_property.upn,
│   on idp_saml.tf line 78, in resource "okta_app_user_schema_property" "upn":
│   78: resource "okta_app_user_schema_property" "upn" {
│ 
╵
╷
│ Error: failed to update custom app user schema property: the API returned an error: Not found: Resource not found: 0oa11kxpdsaLgdl3T3l7 (AppInstance)
│ 
│   with okta_app_user_schema_property.adGroups,
│   on idp_saml.tf line 88, in resource "okta_app_user_schema_property" "adGroups":
│   88: resource "okta_app_user_schema_property" "adGroups" {

**Comment by bogdanprodan-okta** [comment]
I've used this ID for the `app_id` in that resource:
<img width="1058" alt="Screenshot 2021-11-03 at 15 53 41" src="https://user-images.githubusercontent.com/71279414/140073019-c44592c9-5646-48d1-bacc-78821cf3c1b0.png">

State file
```
      "mode": "data",
      "type": "okta_idp_saml",
      "name": "test",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "acs_binding": "HTTP-POST",
            "acs_type": "INSTANCE",
            "audience": "https://www.okta.com/saml2/service-provider/spppxsipyxmbvvqvjiqj",
            "id": "0oa12p2db5wBzetGA0h8",
// ...
```
Script:
```
data "okta_idp_saml" "test" {
  name = "testAcc_replace_with_uuid"
}

resource "okta_app_user_schema_property" "test" {
  app_id      = okta_idp_saml.test.id
  index       = "testAcc_replace_with_uuid"
  title       = "terraform acceptance test"
  type        = "string"
//...
```  
<img width="1012" alt="Screenshot 2021-11-03 at 15 57 30" src="https://user-images.githubusercontent.com/71279414/140073632-3b80bd61-d0ab-484f-b75d-e882cb8c29b3.png">

**Comment by ahmei0** [comment]
Ok, it worked but I found the issue why it was failing.


![image](https://user-images.githubusercontent.com/62230464/140084556-36ab71fe-63ae-402f-b96c-7886e5cf0f41.png)

okta_idp_saml resource was set to be INACTIVE thats why it was failing when referred in custom attribute. I set it to ACTIVE and it worked. Is that expected behaviour ?

![image](https://user-images.githubusercontent.com/62230464/140084696-431a676f-f40e-4c91-886e-dff9957c7099.png)

**Comment by bogdanprodan-okta** [comment]
I'm not sure about this, because clearly, you can edit the properties for inactive IdPs via UI. I'll ask the team responsible for this functionality. For now, I'm closing this issue. Feel free to post comments here or create another one.
