### ISSUE TITLE
azure ad saml idp custom attribute issue

### ISSUE THREAD

**Issue by ahmei0** [okta/terraform-provider-okta#778]
I'm creating custom attribute for azure ad idp profile. 
As per the instructions below I have to delete attributes first and recreate them as external name is not editable

https://help.okta.com/en/prod/Content/Topics/Provisioning/azure/azure-map-attributes.htm

![image](https://user-images.githubusercontent.com/62230464/140192664-9c378e6a-0e3b-48b3-a3a9-5c99ff4fd86b.png)

Wondering how would I automate this with tf? Can I delete attributes and mappings that I didn't create with tf first? and then create them correctly?

**Comment by bogdanprodan-okta** [comment]
Hi, @ahmei0! Thanks for submitting this issue! I have to investigate this properly in order to come up with a solution.
