### ISSUE TITLE
terraform registry docs inaccurate - okta_user_base_schema

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#779]
`okta_user_base_schema` is deprecated as per [here](https://github.com/okta/terraform-provider-okta/blob/09b8db99ed924f170dd4dfdba95dbe3c99db9c83/website/docs/r/user_base_schema.html.markdown?plain=1#L7) however it doesn't appear to show as deprecated [here](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/user_base_schema)

**Comment by bogdanprodan-okta** [comment]
Hi, @exitcode0! Thanks for submitting this issue! I'll fix the doc asap.
