### ISSUE TITLE
Custom URL value for issuer_mode in okta_app_oauth keeps resetting to org url

### ISSUE THREAD

**Issue by stmyers** [okta/terraform-provider-okta#780]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform version: 1.0.7

### Affected Resource(s)

- okta_app_oauth

### Terraform Configuration Files

```hcl
resource "okta_app_oauth" "example_app" {
  label                     = "example app"
  type                      = "web"
  grant_types               = ["authorization_code", "refresh_token"]
  redirect_uris             = ["https://example.company.com/okta-authorize"]
  post_logout_redirect_uris = ["https://example.company.com/okta-logout-user"]
  response_types            = ["code"]
  issuer_mode               = "CUSTOM_URL"
  skip_groups               = true
  skip_users                = true
}
```

### Expected Behavior

I created an OIDC app via the UI with CUSTOM_URL set and then imported it, and reconciled the TF code.

I would expect that Issuer uses configured custom URL, but on first run after import, it sets it back to org url.

### Actual Behavior
On first run after import, it sets it back to org url.

Subsequent runs, plan output says it's going to change it to CUSTOM_URL but does not change it:
```hcl
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # okta_app_oauth.example_app will be updated in-place
  ~ resource "okta_app_oauth" "example_app" {
        id                         = <redacted>
      ~ issuer_mode                = "ORG_URL" -> "CUSTOM_URL"
        name                       = "oidc_client"
        # (31 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
If I set it to CUSTOM_URL in the UI, during the planning phase it acknowledges change happened via UI and states that no changes will occur, but after running this, it actually changes it back to org url  (???)
```hcl
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # okta_app_oauth.example_app has been changed
  ~ resource "okta_app_oauth" "example_app" {
        id                         = <redacted>
      ~ issuer_mode                = "ORG_URL" -> "CUSTOM_URL"
        name                       = "oidc_client"
        # (31 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.
```

### Steps to Reproduce

1. Create new OIDC app via UI with custom url set
2. `terraform import okta_app_oauth.example_app "<redacted id>/skip_users/skip_groups"`
3. Set TF config as above
4. `terraform plan` 

I feel like I'm missing something obvious...

**Comment by bogdanprodan-okta** [comment]
Hi, @stmyers! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.

**Comment by bogdanprodan-okta** [comment]
Hi, @stmyers! I couldn't reproduce the issue you were getting. My steps were:
1. Create a custom domain.
2. Verify custom domain.
3. Add certificates.
4. Create an OIDC web app and then import it.  The`issuer_mode` had `"CUSTOM_URL"` value after import.

**Comment by mrproper** [comment]
Im hitting the exact same problem, using provider:
```
terraform {
  required_providers {
    okta = {
      source = "okta/okta"
      version = "~> 3.20"
    }
  }
  required_version = ">= 0.14"
}
```


Using terraform code:
```
variable "name" {
  type = string
}
variable "type" {
  type = string
}
variable "login_uri" {
  type = string
}
variable "consent_method" {
  type    = string
  default = "REQUIRED"
}
variable "grant_types" {
  type    = list(any)
  default = ["authorization_code"]
}
variable "redirect_uris" {
  type    = list(any)
  default = []
}
variable "post_logout_redirect_uris" {
  type = list(any)
}
variable "issuer_mode" {
  type    = string
  default = "CUSTOM_URL"
}
variable "response_types" {
  type    = list(any)
  default = ["code"]
}
variable "groups_claim_name" {
  type    = string
  default = "groups"
}
variable "groups_claim_value" {
  type    = string
  default = ".*"
}
resource "okta_app_oauth" "default" {
  label                     = var.name
  type                      = var.type
  consent_method            = var.consent_method
  grant_types               = var.grant_types
  issuer_mode               = var.issuer_mode
  login_uri                 = var.login_uri
  post_logout_redirect_uris = var.post_logout_redirect_uris
  redirect_uris             = var.redirect_uris
  response_types            = var.response_types
  groups_claim {
    type = "FILTER"
    filter_type = "REGEX"
    name        = var.groups_claim_name
    value       = var.groups_claim_value
  }
  lifecycle {
    # We dont control groups and users directly on an application but rather on a rule that assigns them to it
    ignore_changes = [groups, users]
  }
}
```

This ends up with every run with:
```
  # okta_app_oauth.default will be updated in-place
  ~ resource "okta_app_oauth" "default" {
        id                         = "XXX"
      ~ issuer_mode                = "ORG_URL" -> "CUSTOM_URL"
        name                       = "oidc_client"
        # (31 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

**Comment by mrproper** [comment]
Ahh i've found why you cant replicate it, you need to use a groups_claim block and the code that does that has "ORG_URL" hard coded in it https://github.com/okta/terraform-provider-okta/pull/468/files#diff-4a5904220b736cd8cd158c3c3e4814fda830aff6ccae710cecbd52aedcac897cR400

So the api is hit and sets the issuer_mode to "CUSTOM_URL" then the groups_claim comes in and sets it back to "ORG_URL" and the cycle repeats

**Comment by tantran-falconx** [comment]
+1, same issue. custom_url with groups_claim

**Comment by jessicastenning** [comment]
+1, also seeing this issue - any plans to fix this?

**Comment by monde** [comment]
We'll investigate this further.

**Comment by bretterer** [comment]
@monde check to see if #1167 fixes this issue

**Comment by monde** [comment]
Confirmed, #1167 fixed this issue:
* If resource okta_app_oauth has a groups_claim, make the groups claim issuer mode be the same as the app (instead of hard coded to ORG_URL)
* okta_app_oauth.groups_claim.issuer_mode is a read-only attribute
