### ISSUE TITLE
Linked Objects

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#784]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be good to be able to define our linked objects in Terraform (and potentially their values)
https://developer.okta.com/docs/reference/api/linked-objects/
### New or Affected Resource(s)

- okta_user
- okta_user_schema_property
- okta_user_schema_linked_object

### Potential Terraform Configuration

```hcl
resource "okta_user_schema_linked_object" "manager" {
    index = "supervisor"
    title = "Supervisor"
    description = "This user's supervisor."
    user_type = "${data.okta_user_type.example.id}"
}

resource "okta_user" "john_smith" {
  first_name         = "John"
  last_name          = "Smith"
  login              = "john.smith@example.com"
  email              = "john.smith@example.com"
  custom_profile_attributes = jsonencode({
      supervisor = data.okta_user.tony_stark.id
  })
}

resource "okta_user_schema_linked_object" "owner" {
    index = "owner"
    title = "Owner"
    description = "the user that owns this service account."
    user_type = "${data.okta_user_type.example.id}"
}

resource "okta_user" "my_billion_dollar_start_up_service_account" {
  first_name         = "first"
  last_name          = "last"
  login              = "first.last@example.com"
  email              = "first.last@example.com"
  custom_profile_attributes = jsonencode({
      owner = data.okta_user.tony_stark.id
  })
}
```

### References

- https://developer.okta.com/docs/reference/api/linked-objects/

**Comment by bogdanprodan-okta** [comment]
Hi, @exitcode0! Thanks for submitting this issue! I'll start to work on this asap.
