### ISSUE TITLE
backend configured as "pg" causes terraform to look in oktadeveloper/okta for provider

### ISSUE THREAD

**Issue by pmjensen** [okta/terraform-provider-okta#788]
With versions of the okta provider newer that 3.10.0 and backend set as "pg" Terraform is unable to initialize because it is looking in oktadeveloper/okta for the provider binaries.  

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of okta/okta from the dependency lock file
- Finding latest version of oktadeveloper/okta...
- Installing okta/okta v3.18.0...
- Installed okta/okta v3.18.0 (signed by a HashiCorp partner, key ID 6438EEBF187672EE)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Warning: Additional provider information from registry
│
│ The remote registry returned warnings for registry.terraform.io/oktadeveloper/okta:
│ - For users on Terraform 0.13 or greater, this provider has moved to okta/okta. Please update your source in required_providers.
╵

╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/oktadeveloper/okta v3.18.0 does not have a package available for your current platform, linux_amd64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have
│ different platforms supported.
╵

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.10
on linux_amd64
+ provider registry.terraform.io/okta/okta v3.18.0

### Affected Resource(s)

- okta provider

### Terraform Configuration Files

terraform {
  backend "pg" {}
  required_providers {
    okta = {
      source  = "okta/okta"
      version = "~> 3.18.0"
    }
  }
}

provider "okta" {
  org_name  = "xxxxxx"
  base_url  = "okta.com"
  api_token = "xxx"
}

### Debug Output

https://gist.github.com/pmjensen/26100b2b9bd39a8683adb601cf28f944

### Expected Behavior

Terraform should complete init without error.

### Actual Behavior

Terraform failed the init.

### Steps to Reproduce

1. Configure terraform backend as "pg"
2. Configure okta provider and set required_providers.
3. Run "terraform init"

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @pmjensen! Thanks for submitting this issue! I couldn't reproduce the same error, but I think you should check the contents of the `.terraform.lock.hcl`. It still might contain info about `oktadeveloper/okta`, thus causing this error.

**Comment by noinarisak** [comment]
Including what @bogdanprodan-okta stated to check your `.terraform.lock.hcl`. Since you using `pg` as remote backend state. `pg` needs to be aware to be aware to pull from `okta/okta` could be the issue.  

This may resolve your issue, however, I have never Postgres as option a my remote state backend.

```bash
terraform state replace-provider oktadeveloper/okta okta/okta
```

[More detail](https://www.terraform.io/docs/cli/commands/state/replace-provider.html).

**Comment by pmjensen** [comment]
Thank you!  The 'replace-provider' worked.
