### ISSUE TITLE
Okta SDK Panics on bad URI or Token

### ISSUE THREAD

**Issue by quantumew** [okta/terraform-provider-okta#8]
### Expected Behavior

Nice pretty error when consumer provides an invalid Okta URI or Token. We should recover from this panic or even better, the panic never happen!

### Actual Behavior

PANIC at the disco. 

https://github.com/terraform-providers/terraform-provider-okta/blob/0c1611a960c7c7b35c14ca2edbf99649c970119a/vendor/github.com/okta/okta-sdk-golang/okta/okta.go#L87

### Steps to Reproduce

1. configure Okta provider with invalid params
2. run it against anything

**Comment by icebal** [comment]
ok, getting somewhere with this. my variable for the api was misconfigured. there is an error that is passed only sometimes in debug mode saying no api key found (how i noticed). is there a way to pass this to an actual TF error? when i hard coded the api in, it looks to be working, i'm now just getting a misformed body error.  here is the whole okta TF.
error:
 `2020/02/20 15:15:28 [ERROR] <root>: eval: *terraform.EvalSequence, err: The API returned an error: The request body was not well-formed.`

TF:
```
provider "okta" {
  org_name  = "dev-438690"
  base_url  = "okta.com"
  api_token = "xxxxxxxxx"
}

resource "okta_app_saml" "app-saml-dev" {
  label                    = "dev app"
  sso_url                  = "https://app-dev.comp.com/wg/saml/SSO/index.html"
  recipient                = "https://app-dev.comp.com/wg/saml/SSO/index.html"
  destination              = "https://app-dev.comp.com/wg/saml/SSO/index.html"
  audience                 = "https://app-dev.comp.com"
  subject_name_id_template = "$${user.userName}"
  subject_name_id_format   = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
  response_signed          = true
  assertion_signed         = true
  signature_algorithm      = "RSA_SHA256"
  digest_algorithm         = "SHA256"
  honor_force_authn        = true
  authn_context_class_ref  = "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"

  attribute_statements {
    name         = "username"
    filter_value = "user.login+\".local\""
  }
}
```

**Comment by icebal** [comment]
i have narrowed the above to the attribute_statements block, even doing something simple like below errors as not well formed body:

 attribute_statements {
    name         = "username"
    filter_value = "user.login"
  }

**Comment by bogdanprodan-okta** [comment]
Hi @icebal @quantumew! I think the problem is that `attribute_statements.type` can be `EXPRESSION` or `GROUP`, but with different sets of other fields.
It's clearly not good, that Okta API returns not a very obvious error message. I'll create a PR to fix this issue.

PS: you can fix TF by making `attribute_statements` like this:
```
attribute_statements {
    name         = "username"
    filter_value = "user.login+\".local\""
    type = "GROUP"
}
```

**Comment by bogdanprodan-okta** [comment]
The following errors will appear if the `attribut_statement` is not well-formed:
```
errors.New("invalid 'attribute_statements': when setting 'filter_value' or 'filter_type', value of 'type' should be set to 'GROUP'")
```
and
```
errors.New("invalid 'attribute_statements': when setting 'values', 'type' should be set to 'EXPRESSION'")
```
