### ISSUE TITLE
OIE capabilities for okta_policy_rule_signon : “Secondary factor"

### ISSUE THREAD

**Issue by BalaGanaparthi** [okta/terraform-provider-okta#802]
Description

Need to configure to control "Secondary factor" from okta_policy_rule_signon

“Secondary factor” is a check box on Okta Sign-on Policy Rule and is checked in the UI by default.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

- okta_policy_rule_signon

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @BalaGanaparthi! Thanks for submitting this issue! You can use this example to enable a secondary factor:
1. 
```
resource "okta_policy_rule_signon" "test" {
  policy_id      = okta_policy_signon.test.id
  name           = "testAcc_replace_with_uuid"
  status         = "ACTIVE"
  primary_factor = "PASSWORD_IDP_ANY_FACTOR"
  mfa_required   = true
  mfa_prompt     = "SESSION"
  mfa_lifetime   = 2
}
```
<img width="594" alt="Screenshot 2021-11-14 at 13 17 06" src="https://user-images.githubusercontent.com/71279414/141678658-cc429f66-7f4b-4b2a-92e9-1b79fa4c58f1.png">

2.
```
resource "okta_policy_rule_signon" "test" {
  policy_id      = okta_policy_signon.test.id
  name           = "testAcc_replace_with_uuid"
  status         = "ACTIVE"
  primary_factor = "PASSWORD_IDP_ANY_FACTOR"
}
```
<img width="591" alt="Screenshot 2021-11-14 at 13 18 55" src="https://user-images.githubusercontent.com/71279414/141678696-e15b465c-1fb4-44c0-b525-02251759cdc8.png">

**Comment by BalaGanaparthi** [comment]
Thank you Bogdan. Appreciate your detailed response with an example
