### ISSUE TITLE
Using Client Credentials Results in Requesting OIDC token for every Resource

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#805]
When using the Okta provider with client credentials, it appears that each resource might be making a call to get an OIDC token. This is causing high rate usage limit warnings to occur. I believe in other providers like AWS, they use a connection pooler that will request this once and then re-use the tokens. When you see the screenshot below you can see the timestamp is the same as these are all generated from a single terraform apply.

### System Log Screenshot 
![image](https://user-images.githubusercontent.com/739719/141833608-cc606fda-b5aa-4b44-8767-82e77a6425db.png)

### Sample Terraform Apply Output 
```
okta_app_bookmark.***: Refreshing state... [id=0oa4wfbhfYQn7OOsE696]
okta_app_bookmark.***: Refreshing state... [id=0oa5on0layd89OQTL696]
okta_app_bookmark.***: Refreshing state... [id=0oa5o3eb7eo8AClNE696]
okta_app_bookmark.***: Refreshing state... [id=0oa5nfei5wbRYe0Ii696]
okta_app_bookmark.***: Refreshing state... [id=0oa4r8blmntQjWtv3696]
okta_app_bookmark.***: Refreshing state... [id=0oa4r6ge6Pj2K2PZI696]
okta_app_bookmark.***: Refreshing state... [id=0oa5nchkrOinP7a6V696]
okta_app_group_assignments.***["***"]: Refreshing state... [id=0oa46za92MGxRJIGZ696]
okta_app_group_assignments.***["***"]: Refreshing state... [id=0oa46za92MGxRJIGZ696]
okta_app_group_assignments.***["***"]: Refreshing state... [id=0oa46za92MGxRJIGZ696]
okta_app_group_assignments.***["***"]: Refreshing state... [id=0oa46za92MGxRJIGZ696]
okta_app_group_assignments.***["***"]: Refreshing state... [id=0oa46za92MGxRJIGZ696]
okta_app_group_assignments.***["***"]: Refreshing state... [id=0oa46za92MGxRJIGZ696]
okta_app_group_assignments.***["***"]: Refreshing state... [id=0oa46za92MGxRJIGZ696]
okta_app_group_assignments.***: Refreshing state... [id=0oa3bc65rUVgLvdnX696]
okta_app_group_assignments.***: Refreshing state... [id=0oa4wfbhfYQn7OOsE696]
okta_app_group_assignments.***: Refreshing state... [id=0oa5on0layd89OQTL696]
okta_app_group_assignments.***: Refreshing state... [id=0oa5o3eb7eo8AClNE696]
okta_app_group_assignments.***: Refreshing state... [id=0oa5nfei5wbRYe0Ii696]
okta_app_group_assignments.***: Refreshing state... [id=0oa4r8blmntQjWtv3696]
okta_app_group_assignments.***: Refreshing state... [id=0oa4r6ge6Pj2K2PZI696]
okta_app_group_assignments.***: Refreshing state... [id=0oa5nchkrOinP7a6V696]
okta_app_oauth.***: Refreshing state... [id=0oa4kdsk2jl8hZ2mE696]
okta_app_oauth.***: Refreshing state... [id=0oa6dkv7akokRTfgo696]
okta_app_saml.***: Refreshing state... [id=0oa46za92MGxRJIGZ696]
okta_app_saml.***: Refreshing state... [id=0oa3bc65rUVgLvdnX696]
okta_auth_server.***: Refreshing state... [id=aus4ke9h95BiF06V0696]
okta_factor.***: Refreshing state... [id=fido_u2f]
okta_factor.***: Refreshing state... [id=google_otp]
okta_factor.***: Refreshing state... [id=okta_otp]
okta_group.***["***"]: Refreshing state... [id=00g4qxqd4vxGPpYTg696]
okta_group.***["***"]: Refreshing state... [id=00g4qx3phyKaRZrsF696]
okta_group.***["***"]: Refreshing state... [id=00g4r1id2lJirHmUz696]
okta_group.***["***"]: Refreshing state... [id=00g4r1b7oxgSDNTiB696]
okta_group.***["***"]: Refreshing state... [id=00g4qxdpxmp3pegpH696]
okta_group.***["***"]: Refreshing state... [id=00g4qx9l0nMo77hHO696]
okta_group.***["***"]: Refreshing state... [id=00g4qwvx6IGfBO4yL696]
okta_group.***: Refreshing state... [id=00g4qtofrpEyUQwd5696]
okta_group.***: Refreshing state... [id=00g4wfwb1hoyJNMA1696]
okta_group.***["***"]: Refreshing state... [id=00g6gnf53xKm7wfGR696]
okta_group.***["***"]: Refreshing state... [id=00g6gqwgr2ohJHAuV696]
okta_group.***["***"]: Refreshing state... [id=00g6gjs47jhnrUy5T696]
okta_group.***["***"]: Refreshing state... [id=00g6gpngx8zh3RNAv696]
okta_group.***["***"]: Refreshing state... [id=00g6gpngv66C5OBmI696]
okta_group.***["***"]: Refreshing state... [id=00g6glx8zQrh8FQ9K696]
okta_group.***["***"]: Refreshing state... [id=00g6gpa2fE7blAn4q696]
okta_group.***["***"]: Refreshing state... [id=00g6gp9i3hZfeZsH0696]
okta_group_memberships.***["***"]: Refreshing state... [id=00g4qx9l0nMo77hHO696]
okta_group_memberships.***: Refreshing state... [id=00g4wfwb1hoyJNMA1696]
okta_group_memberships.***[0]: Refreshing state... [id=00g4qtofrpEyUQwd5696]
okta_group_rule.***["***"]: Refreshing state... [id=0pr6gt0etfgLCR7WF696]
okta_group_rule.***["***"]: Refreshing state... [id=0pr6gy0u9akYantUZ696]
okta_group_rule.***["***"]: Refreshing state... [id=0pr6grzm7Idut4mEV696]
okta_group_rule.***["***"]: Refreshing state... [id=0pr6gsgemcS3peYnX696]
okta_group_rule.***["***"]: Refreshing state... [id=0pr6gq33bsqwnewfp696]
okta_group_rule.***["***"]: Refreshing state... [id=0pr6gn2xbqUbtX7tH696]
okta_group_rule.***["***"]: Refreshing state... [id=0pr6gs7t1nkHF2sFU696]
okta_group_rule.***["***"]: Refreshing state... [id=0pr6gpqjrPgthsyhK696]
okta_policy_mfa.***: Refreshing state... [id=00p4ls2x8gy36DTPr696]
okta_policy_mfa_default.***: Refreshing state... [id=00p2ca6c9C5PevbND696]
okta_policy_password.***: Refreshing state... [id=00p4lxagvokKhwjID696]
okta_policy_password_default.***: Refreshing state... [id=00p2ca6bxcRDtnKKp696]
okta_policy_rule_mfa.***: Refreshing state... [id=0pr4ltkrhcFpYJRwa696]
okta_policy_rule_password.***: Refreshing state... [id=0pr4lwqzvygUlzctE696]
okta_policy_rule_signon.***: Refreshing state... [id=0pr4mtv0qv3ZmRbOb696]
okta_policy_signon.***: Refreshing state... [id=00p2ca6b5oKxOwMX8696]
okta_policy_signon.***: Refreshing state... [id=00p4mgf1eOwmhUwNN696]
okta_user.***["***"]: Refreshing state... [id=00u4n1h651hwCP3RQ696]
okta_user.***["***"]: Refreshing state... [id=00u4r90m7CNNbg7ho696]
okta_user.***["***"]: Refreshing state... [id=00u6jj4m9XaL0nK1P696]
okta_user_schema_property.***: Refreshing state... [id=***]
okta_user_schema_property.***: Refreshing state... [id=***]
```

### DebugContext from One of the Logs
```
AuthenticationContext
DisplayMessage        OIDC access token is granted
EventType             app.oauth2.token.grant.access_token
Outcome
Published             2021-11-15T16:35:36.620Z
SecurityContext
Severity              INFO
System
  DebugContext
    DebugData
      ClientAuthType  private_key_jwt
      GrantType       client_credentials
      GrantedScopes   okta.apps.manage, okta.groups.manage, okta.policies.manage, okta.schemas.manage, okta.authorizationServers.manage, okta.users.manage, okta.factors.manage
      RequestId       YZKMWGCN0K4IRrfeJkmHPwAAA-Q
      RequestUri      /oauth2/v1/token
      RequestedScopes okta.apps.manage, okta.groups.manage, okta.policies.manage, okta.schemas.manage, okta.authorizationServers.manage, okta.users.manage, okta.factors.manage
      ThreatSuspected false
      Url             /oauth2/v1/token?client_assertion=***&client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&grant_type=client_credentials&scope=okta.apps.manage+okta.groups.manage+okta.policies.manage+okta.schemas.manage+okta.authorizationServers.manage+okta.users.manage+okta.factors.manage
      LegacyEventType app.oauth2.token.grant.access_token_success
      Transaction
      UUID            0fa19766-4632-11ec-bbdd-cf4a074f0f09
      Version         0
```

### Versions
```
Terraform 1.0.10
Okta Provider 3.19.0
```

**Comment by monde** [comment]
Hey @virgofx , @bogdanprodan-okta looked at this and points out that the default okta-sdk-golang doesn't operate with a caching manager (https://github.com/okta/okta-sdk-golang#extending-or-creating-new-cache-manager). As you point out  this includes any bearer tokens. We need to change the sdk to cache the bearer token properly to eliminate unnecessary requests regardless of okta-sdk-golang running with a custom cache manager. I'll write up an issue in okta-sdk-golang and see about implementing a fix.

**Comment by monde** [comment]
ref: https://github.com/okta/okta-sdk-golang/issues/269

**Comment by virgofx** [comment]
Thanks @monde !  Appreciate the upstream support. Obviously, this would be beneficial as less redundant API calls on the Okta side. Happy to test/confirm any releases.

**Comment by monde** [comment]
@bogdanprodan-okta there is already some token juggling in okta-sdk-golang https://github.com/okta/okta-sdk-golang/blob/master/okta/requestExecutor.go#L124-L213 and past feedback about it https://github.com/okta/okta-sdk-golang/pull/140 . But overall, it seems like the history of okta-sdk-golang has been not to have an opinion about bearer tokens.

@bogdanprodan-okta it seems like the terraform provider might want to implement its own cachemanager for its okta-sdk-client https://github.com/okta/terraform-provider-okta/blob/master/okta/config.go#L93-L112 and have an opinion about caching a bearer token. Or, have such as a feature flag on the provider. What do you think?

**Comment by monde** [comment]
Another thought, @virgofx if you set a long lived bearer token named `OKTA_ACCESS_TOKEN` as an environment variable in the shell that you run `terraform` does this resolve the rate limit issues you are running into? As can be seen in the okta-sdk-golang code it will always use that value if it is set rather than doing a new token request https://github.com/okta/okta-sdk-golang/blob/master/okta/requestExecutor.go#L125-L128

**Comment by virgofx** [comment]
Sure that makes sense. I haven't tried that ... it may work, would be happy to one-time test. Currently; however, we have an OAuth application specific for our Terraform/Atlantis that generates client credentials. Instead of codifying the logic for obtaining the bearer token, we simply use the native functionality of the provider making it easier in our outside environment (containers/runners) such that they only need environment variables.  I do believe this is somewhat best practice. Our terraform looks like:

```
# The following environment variables are set:
#   OKTA_API_CLIENT_ID
#   OKTA_API_SCOPES
#   OKTA_API_PRIVATE_KEY
provider "okta" {
  org_name = local.okta_org_name
  base_url = local.okta_base_url
}
```

So ... I still think this would be valuable to just cache or pool the first generated token somehow and wrap all subsequent resource calls around it :)

**Comment by monde** [comment]
@virgofx @bogdanprodan-okta the more I contemplate this I think the terraform provider should have a cache manager option that is enabled by configuration setting. Something like `cache_bearer_tokens` that enables a caching manager to do such on the okta-sdk-golang client.

**Comment by virgofx** [comment]
Hi @monde - Any thoughts on prioritizing this or getting it on the roadmap?

**Comment by monde** [comment]
hi @virgofx , coincidentally in my sync with @bogdanprodan-okta today he mentioned a caching tokens feature is on his lists of wants for our Q1 work in the next two/three months. I will let him elaborate. I'm not certain if @virgofx does any golang coding, if so, that would be neat to get you could help out on a PR for the provider so that it behaves in a way given a real world use case driving development.

**Comment by virgofx** [comment]
My golang experience is limited (but growing). I've been attempting to help with some smaller PRs, however due to the advanced nature of this ... I'd probably recommend someone with more experience with this repo and feature set tackle this :)

**Comment by virgofx** [comment]
Hey @monde Any chance we could re-open this? We're going to be approaching limits here as result of this pretty soon. In the following use case were hitting 600 reqs/min (on a production rollout 10% complete) on what could theoretically be 1-2 reqs/min if these were cached. It would also drastically improve performance for all terraform runs that use OIDC/OAuth

![image](https://user-images.githubusercontent.com/739719/161327944-e72817ec-ee5c-48be-845d-18966cfe6005.png)

**Comment by monde** [comment]
I'll reopen this @virgofx , no problem

**Comment by monde** [comment]
@virgofx fyi, the work to fix this is in my current sprint.

Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-519225

**Comment by virgofx** [comment]
Great, thanks @monde !  This is a double benefit if fixed - It will reduce API load to Okta by a fair amount (well from those that use OAuth heavily like we do via Terraform) as well as very slightly improve performance just a tad

**Comment by monde** [comment]
fyi, incoming https://github.com/okta/terraform-provider-okta/pull/1263
