### ISSUE TITLE
Why `okta_group_membership` is deprecated?

### ISSUE THREAD

**Issue by borissavelev** [okta/terraform-provider-okta#813]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Could you please explain why `okta_group_membership` is deprecated? (11ba6e8f)
Looks like it can be replaced by `okta_group_memberships` or `okta_user_group_memberships` but it's not.
This resource is for granular management of group membership.

I guess if I'll use okta_group_memberships in separate TF states they will conflict somehow. Or use `ignore_changes`?
If so - question how it will be if I want remove user from one group?

(Another topic deprecating note is missed in docs https://registry.terraform.io/providers/okta/okta/latest/docs/resources/group_membership)

### New or Affected Resource(s)

- okta_group_membership

### Potential Terraform Configuration

one state:
```hcl
resource "okta_group" "test" {
  name        = "testAcc_replace_with_uuid"
  description = "testing, testing"
}

resource "okta_group_memberships" "test" {
  group_id = okta_group.test.id
  users = [
    okta_user.test1.id,
    okta_user.test2.id,
  ]
}
```

another state:
```hcl
resource "okta_group" "test2" {
  name        = "test2Acc_replace_with_uuid"
  description = "another testing, testing another"
}

resource "okta_group_memberships" "test" {
  group_id = okta_group.test2.id
  users = [
    okta_user.test1.id,
    okta_user.test2.id,
  ]
}
```

### References

- 11ba6e8f

**Comment by bogdanprodan-okta** [comment]
Hi, @borissavelev! Thanks for submitting this issue! The reason `okta_group_membership` is deprecated is that `okta_group_memberships` gives you the same functionality, but you can also assign multiple users. As for `okta_user_group_memberships`, it allows assigning multiple groups to a single user.
