### ISSUE TITLE
Validation for email customization fails

### ISSUE THREAD

**Issue by Marek26** [okta/terraform-provider-okta#816]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

- terraform_0.14.3
- okta v3.10.1

### Affected Resource(s)

- okta_okta_template_email.forgotPassword

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Api validation failed: customTemplate. Causes: errorSummary: The Message contains an invalid expression

### Expected Behavior

I am not sure if this issue is really caused by terraform or the Okta APIs, but within our preview tenant we have some troubles updating the custom mail templates via terraform. It seems as some of the new Velocity features are also part of the old templates, causing some issues.

For custom mail templates, I am not longer able to send Test emails. The following message is being displayed:

> We detected custom code.
> Email previews in Branding may no longer reflect what your end users will experience. All users will receive the default language selected unless you add translations manually. To revert to the default email template, click Reset to Default.

I observed the following behaviour:

${user.login} changed to ${user.profile.login} in welcome mails (but does still work)

Default Forgot Password contains $StringTool.escapeHtml($user.profile.firstName), however in the documentation (https://help.okta.com/en/prod/Content/Topics/Settings/settings-EL-password.htm) the function is still ${f:escapeHtml(user.firstName)}.

Main issue: ${recoveryToken} changed to $oneTimePassword.

I wanted to fix this issue by run terraform apply, inserting the following attributes:

- ${f:escapeHtml(user.firstName)}
- ${f:escapeHtml(user.lastName)}
- ${recoveryToken}
- ${resetPasswordLink}

### Actual Behavior

Api validation failed: customTemplate. Causes: errorSummary: The Message contains an invalid expression

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @Marek26! Thanks for submitting this issue! The best solution here would be to ma a request directly to Okta Support since I don't possess detailed documentation on this feature.

**Comment by Marek26** [comment]
Hi @bogdanprodan-okta,

the templates themselves are now working again but I am not able to send test mails due to "old" variables.

Enabling the Velocity Feature would cause changes in variables within the deployed mail templates in Okta.
These changes must then be also made in the templates being stored in terraform.

Is there any plan to provide a migration plan on variables and macros currently being used in mail templates and their updated version within Velocity Templates?

**Comment by monde** [comment]
@Marek26 I will be releasing a new resource for the updated email templates endpoint by the end of this month.

**Comment by monde** [comment]
@Marek26 `okta_template_email` is deprecated now. Please switch over to the `okta_email_customization` resource.  https://registry.terraform.io/providers/okta/okta/latest/docs/resources/email_customization
