### ISSUE TITLE
Fix new `okta_rate_limiting` Resource Documentation Errors

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#825]
Actual resource name is `okta_rate_limiting` but the documentation has numerous places that refer to `okta_rate_limit`.

See screenshot for examples. There may be more but this was my first pass. Might be worth doing a search in code just to be safe.

![image](https://user-images.githubusercontent.com/739719/143138324-738dce06-fd55-4b14-a65c-e71d165d59c0.png)

**Comment by bogdanprodan-okta** [comment]
Hi, @virgofx! Thanks for submitting this issue! Yes, seems like I forgot to fix naming in the documentation. The name of the resource should be `okta_rate_limiting`.

**Comment by virgofx** [comment]
> Hi, @virgofx! Thanks for submitting this issue! Yes, seems like I forgot to fix naming in the documentation. The name of the resource should be `okta_rate_limiting`.

No worries. I'd submit a PR; however, holiday/short week so you'll likely get to it first. Any insights when this as well as other recent account / settings features APIs will be available via OAuth scopes?

**Comment by bogdanprodan-okta** [comment]
> > Hi, @virgofx! Thanks for submitting this issue! Yes, seems like I forgot to fix naming in the documentation. The name of the resource should be `okta_rate_limiting`.
> 
> No worries. I'd submit a PR; however, holiday/short week so you'll likely get to it first. Any insights when this as well as other recent account / settings features APIs will be available via OAuth scopes?

Unfortunately no, I don't.
