### ISSUE TITLE
Question : How to assign Apps to Profile Enrollment?

### ISSUE THREAD

**Issue by BalaGanaparthi** [okta/terraform-provider-okta#826]
With the current resources can create profile enrollment and its rule (with okta_policy_profile_enrollment and okta_policy_rule_profile_enrollment ), but could not find any resource that can assign apps to the profile enrollment entity

Require a resource for adding apps to the profile enrollment entity.

If missing the resource, please accept this issue as an enhancement else an example will be helpful

**Comment by bogdanprodan-okta** [comment]
Hi, @BalaGanaparthi! Thanks for submitting this issue! Currently, there is no documentation available for this feature. I need to make a request to the team responsible for this functionality in order to implement it correctly.
FYI, this is the request used for adding apps to the policy:
```
curl 'https://*****.oktapreview.com/api/v1/policies/rst1yogxkmc84rwkX1d7/mappings?forceCreate=true' \
  --data-raw '{"resourceType":"APP","resourceId":"0oa1xlkne6z0bhtAT1d7"}' \
  --compressed
```

**Comment by BalaGanaparthi** [comment]
Thanks @bogdanprodan-okta
