### ISSUE TITLE
[session_lifetime] value  in [okta_policy_rule_signon] resource not getting applied to {Session expires after} in UI

### ISSUE THREAD

**Issue by BalaGanaparthi** [okta/terraform-provider-okta#828]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/okta/okta v3.19.0

### Affected Resource(s)

- okta_policy_rule_signon

### Terraform Configuration Files

```hcl
resource "okta_policy_rule_signon" "xyz" {
  policy_id              = okta_policy_signon.xyz_policy.id
  name                    = "XYZ Rule"
  status                   = "ACTIVE"
  primary_factor     = "PASSWORD_IDP_ANY_FACTOR"
  mfa_required       = true
  mfa_prompt         = "ALWAYS"
  session_lifetime   = "90"
}
```

### When providing `session_lifetime` value less than 120
*Error: failed to create sign-on policy rule: failed to create policy rule: the API returned an error: Api validation failed: actions.signon.session. Causes: errorSummary: actions.signon.session: Session policy property maxSessionIdleMinutes must be less than or equal to the maxSessionLifetimeMinutes property*

### When providing `session_lifetime` value greater than 120
Value for `Session expires after` in the ui is set to 2 hrs

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @BalaGanaparthi! Thanks for submitting this issue! If you want to change `Session expires after` you should use `session_idle` (MaxSessionIdleMinutes), not the `session_lifetime` (MaxSessionLifetimeMinutes). [Docs](https://developer.okta.com/docs/reference/api/policy/#signon-session-object)
