### ISSUE TITLE
okta_authenticator to control phone methods (voice and sms)

### ISSUE THREAD

**Issue by BalaGanaparthi** [okta/terraform-provider-okta#829]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently the resource only allow uses (authN and recovery) to be controlled by the resource for phone with no ability to control the methods (voice and sms) to be activated | deactivated.

API did not provide a setting option for phone methods to be used in the resource : https://developer.okta.com/docs/reference/api/authenticators-admin/#authenticator-properties

However, digging through the HALs in authenticator APIs revealed to control the phone methods..
/api/v1/authenticators/{{authenticatorId}}/methods/{voice|sms}/lifecycle/{activate|deactivate}

### New or Affected Resource(s)

- okta_authenticator

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by MikeMondragon-okta** [comment]
not stale

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-558861
