### ISSUE TITLE
Getting 405 when trying to refresh/plan/apply auth_server_scope resources

### ISSUE THREAD

**Issue by rcastelino-cbh** [okta/terraform-provider-okta#830]
As of this morning (~11:30am PST), my previously working terraform scripts started to fail when running plan/apply on a configuration involving auth_server_scopes. I'm getting the following error:

"Error: failed to get auth server scope: the API returned an error: The endpoint does not support the provided HTTP method, Status: 405 Method Not Allowed"

I tried reverting my code to older version which had been working, but those versions are also failing now with the same issue. I think this might be caused by an update to the Okta Developers API more than the Okta TF Provider though?

**Comment by bogdanprodan-okta** [comment]
Hi, @rcastelinoCrate! I'm not sure what is causing this issue! Could you please extract the `x-okta-request-id` response header for the request that is failing (you can run terraform commands with ` TF_LOG=TRACE` env var to see all the requests/responses)
FYI I just tested create/update/delete for `okta_auth_server_scope` and everything works fine

**Comment by rcastelino-cbh** [comment]
Hmmm... I'll take a look to see if there's anything I missed since it does sound like it's a local issue.

In the meantime, I tried another request (which unfortunately failed) with x-okta-request-id of YaA@vTVeUflWoQDjykYTLgAADuc

**Comment by bogdanprodan-okta** [comment]
Hi! As for `x-okta-request-id=YaA@vTVeUflWoQDjykYTLgAADuc`, the response to this request (GET /api/v1/users/me) was 200

**Comment by rcastelino-cbh** [comment]
Ah, figured it it out! For some reason, my terraform state file had wiped the auth_server_id fields so when refreshing it was posting a GET to api/v1/AuthorizationServers//scopes/.... rather than api/v1/AuthorizationServers/<authorization server id>/scopes. The former is an invalid url causing the script to crash.
