### ISSUE TITLE
Thoughts on Adding Capability For extra API call to expire password on new user creation

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#831]
For the `okta_user` resource, we can currently generate new users in the `ACTIVE` state with temporary password credentials via the `password` field.  It would be nice to have another flag that would force new users to be required to change their password.

Currently, forcing a user to change their password is done from the UI or API via the [PASSWORD EXPIRED API](https://developer.okta.com/docs/reference/api/users/#expire-password).

I would like to add a new flag into `okta_user` something along the lines:

`expire_password_on_create = true`

Behind the scenes. This flag would simply call the API endpoint at the conclusion of the `Create` schema for `okta_user`.  This would be an opt-in approach via a new parameter/flag that defaults to `false`, thus no backwards-incompatible changes.

Having this would allow us to automate 100% user generation.

Happy to submit a PR for this if it made sense. Thoughts @bogdanprodan-okta ?

**Comment by bogdanprodan-okta** [comment]
Hi, @virgofx! Thanks for submitting this issue! I think it's possible to add this flag. I need to investigate all possible scenarios when this operation is permitted.

**Comment by monde** [comment]
@virgofx this sounds like a cool feature. Do you think you would like to submit a PR on this and then we can collaborate?

**Comment by virgofx** [comment]
Sure, I'll take a stab at this one.
