### ISSUE TITLE
okta_policy_mfa assigns overlapping priority to Authenticators enrollment policy

### ISSUE THREAD

**Issue by BalaGanaparthi** [okta/terraform-provider-okta#832]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/okta/okta v3.19.0

### Affected Resource(s)

- okta_policy_mfa

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

Create multiple (4) enrollment policies using `okta_policy_mfa` resource without priority property mentioned in the resource

perform terraform apply

Enrollment policies gets created successfully in the org, but the priorities will be overlapping (multiple policies will be created with the same priority.. at times even overlapping with the default policy)

1. `terraform apply`

### Important Factoids

apply executes normally

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
This needs investigation on Okta's side, closing this issue for now.
