### ISSUE TITLE
Intermittently encountering "Internal Server Error" when executing multiple instances of okta_policy_rule_signon resources

### ISSUE THREAD

**Issue by BalaGanaparthi** [okta/terraform-provider-okta#836]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v1.0.11

### Affected Resource(s)

- okta_policy_rule_signon

### Terraform Configuration Files

```hcl
resource "okta_policy_rule_signon" "allow_signon_rule" {
  policy_id          = okta_policy_signon.allow_signon_policy.id
  name               = "Allow SignOn Rule"
  status             = "ACTIVE"
  network_connection = "ZONE"
  network_includes   = [okta_network_zone.xyz_networkzone.id]
  primary_factor     = "PASSWORD_IDP"
}

resource "okta_policy_rule_signon" "deny_signon_rule" {
  policy_id          = okta_policy_signon.deny_signon_policy.id
  name               = "Deny SignOn Rule"
  status             = "ACTIVE"
  access             = "DENY"
  network_connection = "ZONE"
  network_excludes   = [okta_network_zone.xyz_networkzone.id]
}
```

however the issue is not encountered if the resource is setup with the depends_on property as shown below

```hcl
resource "okta_policy_rule_signon" "allow_signon_rule" {
  policy_id          = okta_policy_signon.allow_signon_policy.id
  name               = "Allow SignOn Rule"
  status             = "ACTIVE"
  network_connection = "ZONE"
  network_includes   = [okta_network_zone.xyz_networkzone.id]
  primary_factor     = "PASSWORD_IDP"
}

resource "okta_policy_rule_signon" "deny_signon_rule" {
  policy_id          = okta_policy_signon.deny_signon_policy.id
  name               = "Deny SignOn Rule"
  status             = "ACTIVE"
  access             = "DENY"
  network_connection = "ZONE"
  network_excludes   = [okta_network_zone.xyz_networkzone.id]
  depends_on = [okta_policy_rule_signon.allow_signon_rule]
}
```
### Panic Output

`Error: failed to create sign-on policy rule: failed to create policy rule: the API returned an error: Internal Server Error, x-okta-request-id=YabNmQ54@BMAr5-1zpGe9gAADDc`

### Expected Behavior

Both the rules must get created

### Actual Behavior

fails to create one of the resource with internal server error 

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @BalaGanaparthi! Thanks for submitting this issue! Unfortunately, there is nothing that can be done from the provider's side. It's purely an Okta back-end problem.

**Comment by bogdanprodan-okta** [comment]
Internal reference [OKTA-450317](https://oktainc.atlassian.net/browse/OKTA-450317)

**Comment by monde** [comment]
Need to see if the fix in https://github.com/okta/terraform-provider-okta/pull/1248 for `okta_auth_server_policy_rule` is what would work here.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-524189
