### ISSUE TITLE
custom domain certificate_chain issue

### ISSUE THREAD

**Issue by ahmei0** [okta/terraform-provider-okta#837]
as per docs certificate_chain is an optional field.

https://registry.terraform.io/providers/okta/okta/latest/docs/resources/domain_certificate#certificate_chain

But I get following error when certificate_chain is not provided. This field seems to be mandatory

│ Error: failed to create domain's certificate: the API returned an error: Api validation failed: certificateChain. Causes: errorSummary: certificateChain: The field cannot be left blank

**Comment by bogdanprodanj** [comment]
Hi, @ahmei0! Thanks for submitting this issue! I think Okta has changed the requirements recently and now this field is required in the request. I will update terraform documentation accordingly.
