### ISSUE TITLE
Custom Sign In question

### ISSUE THREAD

**Issue by ahmei0** [okta/terraform-provider-okta#839]
Is there a way to update custom sign on html  section?
![image](https://user-images.githubusercontent.com/62230464/144184555-3b0e6991-154f-411e-a891-462337e45635.png)

**Comment by bogdanprodan-okta** [comment]
Hi, @ahmei0! Thanks for submitting this issue! Unfortunately, there is no public API available for this functionality.

**Comment by monde** [comment]
@ahmei0 I'm going to close this issue. As @bogdanprodan-okta mentioned, the Okta Terraform provider will only make publicly documented API calls found in the developer documentation. https://developer.okta.com/docs/reference/core-okta-api/ . Some functionality in the Okta UI is based on private API calls and shouldn't be considered stable or maintained.

**Comment by kensykora** [comment]
@monde is there a channel where we can make a feature request to the Okta API team? My org would like to manage this through infrastructure as code as well.

**Comment by monde** [comment]
hi @kensykora. Apologies for the slow reply. Please let your Customer Success Manager at Okta know that you'd like to see this enhancement to the API.
