### ISSUE TITLE
Social IdP (Apple) no examples for Key ID or Team ID

### ISSUE THREAD

**Issue by isaiahtech** [okta/terraform-provider-okta#841]
Documentation does not have an example or details on how to send the Key ID or Team ID with Oka Terraform provider.
https://registry.terraform.io/providers/okta/okta/latest/docs
https://developer.okta.com/docs/guides/add-an-external-idp/apple/main/

ASK: I just need an example of how to setup Apple as a Social IdP.

Okta Postman collection sends these values as 'kid' and 'teamId' respectively, neither of which seems to work here.

Postman Collection - Identity Providers (Okta API) - Add an Apple IdP
{
"type": "APPLE",
"name": "Apple Identity Provider",
"protocol": {
"type": "OIDC",
"scopes": ["openid", "email", "name"],
"credentials": {
"client": {
"client_id": "your-client-id"
},
"signing": {
"privateKey": "{privateKey_from_Apple}",
"kid": "test key id",
"teamId": "test team id"
<snip>

**Comment by bogdanprodan-okta** [comment]
Hi, @isaiahtech! Thanks for submitting this issue! I need to investigate this and figure out what parts are missing from terraform provider.
