### ISSUE TITLE
Custom Domains Cannot be Imported without subsequent recreation

### ISSUE THREAD

**Issue by quantumew** [okta/terraform-provider-okta#844]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v1.0.3

### Affected Resource(s)

- okta_domain

### Terraform Configuration Files

Simple okta_domain as outlined in documentation.

### Expected Behavior

Import a domain, and it not be recreated on subsequent runs

### Actual Behavior

Domain requires recreation due to the name property not being set on import or refresh

### Steps to Reproduce

1. `terraform import` existing custom domain
2. Run a plan, notice it will be recreated

### References

I noticed I cannot import an existing custom domain without subsequent applies recreating it. It appears to be due to the fact that the read function does not set the `name` property. The name property should be sync'd in the read function.

https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_domain.go#L89

**Comment by quantumew** [comment]
Anyway we could get this in a patch release? Thanks!

**Comment by bogdanprodan-okta** [comment]
yes, I think I can make a minor release today. I just need some PRs to be merged first.
