### ISSUE TITLE
DOC: okta_app_oauth_redirect_uri not listed in documentation

### ISSUE THREAD

**Issue by tl24** [okta/terraform-provider-okta#846]
The okta_app_oauth_redirect_uri resource is not listed in the documentation on terraform's site: https://registry.terraform.io/providers/okta/okta/latest/docs, but the resource seems to exist in the code.

**Comment by bogdanprodan-okta** [comment]
Hi, @tl24! Thanks for submitting this issue! I'll update the documentation asap.
