### ISSUE TITLE
Terraform Resource to Enable Asynchronous application reports

### ISSUE THREAD

**Issue by Namita1201** [okta/terraform-provider-okta#847]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This is a new feature request to add Terraform resource to Enable "Asynchronous application reports" in OIE. This feature turns the generation of Application usage and the Application Password Health reports into an asynchronous process.

This setting is found:
From the Admin Console, navigate to Reports > Reports.
Click Application Usage.
Click App Password Health.

![image](https://user-images.githubusercontent.com/95382706/144917931-6d9f6046-75ea-462f-8d1f-af3536fba3fb.png)
![image](https://user-images.githubusercontent.com/95382706/144918633-81ec4932-0d91-4695-84b4-446dcbebce26.png)

### New or Affected Resource(s)

- okta_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @Namita1201! Thanks for submitting this issue! I'll investigate this functionality and try to implement it in the terraform.

**Comment by Namita1201** [comment]
Hi, @bogdanprodan-okta thanks for looking into this. Could you please provide an update on this implementation?

**Comment by bogdanprodan-okta** [comment]
@Namita1201 I'm currently working on some SDK for Identity Engine and will get back to terraform next week

**Comment by monde** [comment]
@Namita1201 unfortunately we won't be able to create this resource. Asynchronous application reports, as seen in the Okta UI, are operated by a private Okta APIs that support the UI. The Okta Terraform Provider only operates against Okta's public facing APIs. Okta public APIs are published with documentation, have customer and developer support, and have interfaces that will not be modified once published.

However, I have opened a Jira ticket with the responsible team asking for their consideration to make this report functionality available through public APIs.

I'm going to close this feature request for now.

Internal reference [OKTA-460783](https://oktainc.atlassian.net/browse/OKTA-460783)
