### ISSUE TITLE
Okta: Test Environment Only: Password change notification email configuration is missing in the UI console

### ISSUE THREAD

**Issue by pandeyabhishek7** [okta/terraform-provider-okta#859]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_xxx

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Password change notification email configuration should be available at the UI console as enabled

### Actual Behavior

Password change notification email configuration is missing in the UI console

### Steps to Reproduce

Login to Okta Test environment https://cvsh-test-admin.okta.com
Go to the Admin console
Go to Security --> General

###NOTE: Rally defect number
[DE101302](https://rally1.rallydev.com/#/?detail=/defect/618454053323&fdp=true)

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodanj** [comment]
Hi, @pandeyabhishek7! Thanks for submitting this issue! Could you provide a resource example so I can reproduce the problem?

**Comment by pandeyabhishek7** [comment]
@bogdanprodan-okta 
***Test Environment: Password changed notification email configuration is missing at the admin console. We need Password changed notification email configuration in the Test environment as well. Please check screen shot from the Lab env below.
![image](https://user-images.githubusercontent.com/63614026/147157002-d5b788c6-4682-4749-bba7-88bb838be99f.png)

***Lab Environment: Password changed notification email configuration is available at the admin console
![image](https://user-images.githubusercontent.com/63614026/147157050-eb0197f4-aa64-45a5-ba46-1b2a96ff2982.png)

**Comment by pandeyabhishek7** [comment]
@bogdanprodanj. I can still reproduce this issue. Can you please check again? Please let me know if a quick call can help? Thank you.

**Comment by bogdanprodan-okta** [comment]
Hi, @pandeyabhishek7! Could you please reach to the Okta support folks, since there is no possibility to add this on UI using terraform.
