### ISSUE TITLE
Okta : Unable to update the notification type status to subscribed for certain notification types

### ISSUE THREAD

**Issue by pandeyabhishek7** [okta/terraform-provider-okta#861]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_xxx

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Notification type status should be subscribed

### Actual Behavior

Notification type status is unsubscribed

### Steps to Reproduce

We are trying to setup subscriptions for admin roles such as: ORG_ADMIN,APP_ADMIN,API_ADMIN,USER_ADMIN and READ_ONLY_ADMIN

1) Try below endpoint in any environment

POST
/api/v1/roles/ORG_ADMIN/subscriptions/RATELIMIT_NOTIFICATION/subscribe

POST
/api/v1/roles/API_ADMIN/subscriptions/REPORT_SUSPICIOUS_ACTIVITY/subscribe
/api/v1/roles/API_ADMIN/subscriptions/OKTA_ISSUE/subscribe

POST
/api/v1/roles/USER_ADMIN/subscriptions/REPORT_SUSPICIOUS_ACTIVITY/subscribe
/api/v1/roles/USER_ADMIN/subscriptions/USER_DEPROVISION/subscribe

POST
/api/v1/roles/READ_ONLY_ADMIN/subscriptions/IWA_AGENT/subscribe
/api/v1/roles/READ_ONLY_ADMIN/subscriptions/REPORT_SUSPICIOUS_ACTIVITY/subscribe
/api/v1/roles/READ_ONLY_ADMIN/subscriptions/RATELIMIT_NOTIFICATION/subscribe

2) Then try the Get call for an admin and verify the status of the above mentioned notification types

e.g.

GET
/api/v1/roles/READ_ONLY_ADMIN/subscriptions/IWA_AGENT

Response:
{
    "notificationType": "IWA_AGENT",
    "channels": [
        "email"
    ],
    "status": "unsubscribed",
    "_links": {
        "subscribe": {
            "href": "https://cvs-olympus.oktapreview.com/api/v1/roles/READ_ONLY_ADMIN/subscriptions/IWA_AGENT/subscribe",
            "hints": {
                "allow": [
                    "POST"
                ]
            }
        },
        "self": {
            "href": "https://cvs-olympus.oktapreview.com/api/v1/roles/READ_ONLY_ADMIN/subscriptions/IWA_AGENT"
        }
    }
}

###NOTE: Rally ticket number:
[DE100562](https://rally1.rallydev.com/#/?detail=/defect/616615636139&fdp=true)

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodanj** [comment]
Hi, @pandeyabhishek7! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.

**Comment by pandeyabhishek7** [comment]
@bogdanprodanj please share if you have any update on this?

**Comment by bogdanprodan-okta** [comment]
@pandeyabhishek7 currently I'm busy working with some other stuff and going to get back to terraform next month.

**Comment by bogdanprodan-okta** [comment]
Hi, @pandeyabhishek7! Sorry for taking so long with the response! I've found [this page](https://help.okta.com/oie/en-us/Content/Topics/Security/custom-admin-role/administrator-email-settings.htm) regarding the role subscriptions. This table show the limitation regarding the notifications for each specific role. I will add additional validation to the provider and updated the documentation.
