### ISSUE TITLE
Counter Intuitive Resource - okta_policy_rule_idp_discovery

### ISSUE THREAD

**Issue by nottooshort** [okta/terraform-provider-okta#862]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The okta resources for okta_policy_rule are largely counter intuitive as the resource requires a policy_id arguement when the resource itself should be creating the rule in okta and storing the policy_id in state. Instead, the resource is largely dependent on an import to manage the object in okta.

You have to ask yourself, where do I get the policy_id? There's no data source for this object, and because we're setting up the org2org hub and spoke architecture, the routing rule (which is how this resource should be properly named) needs to be created first. Once created, you have to be crafty to get the payload information on the web to get any idea what value is supposed to be used.

Example:

my_tenant.okta.com > admin > security > identity providers > routing rules > create \ modify rule > `inspect` > save

Output:
```
POST: https://my_tenant.okta.com/api/v1/policies/<PolicyID>/rules/<RuleID>
Payload:
{type: "IDP_DISCOVERY", id: "****", name: "BPO", priority: 1, status: "ACTIVE",…}
actions: {idp: {providers: [{id: "****"}]}}
idp: {providers: [{id: "****"}]}
conditions: {network: {connection: "ANYWHERE"},…}
app: {include: [], exclude: []}
network: {connection: "ANYWHERE"}
platform: {include: [{type: "ANY", os: {type: "ANY"}}], exclude: []}
userIdentifier: {patterns: [{matchType: "EQUALS", value: "Employee"}], type: "ATTRIBUTE", attribute: "userType"}
created: null
id: "***"
lastUpdated: null
name: "Employee"
priority: 1
status: "ACTIVE"
system: false
type: "IDP_DISCOVERY"
_links: {,…}
```

I was only able to properly perform the terraform import function by monitoring the POST api call and recognizing that the values I needed to import where in the URI

```
POST: https://my_tenant.okta.com/api/v1/policies/<PolicyID>/rules/<RuleID>
```

```
$ terraform import okta_policy_rule_idp_discovery.example <PolicyID>/<RuleID>
```

There's little to no documentation on how to create \ modify these resources through terraform, so it was by shear luck that I got this far. Now that I'm cleaning up my code, the argument "policy_id" doesn't feel like terraform and that you shouldn't have to create the object in okta prior to bringing that resource into terraform state. It's also both an input and output because of this requirement. This is largely counter-intuitive, which seems to extend to all of the other okta_policy_rule resources.

### New or Affected Resource(s)

okta_policy_rule_idp_discovery

### Potential Terraform Configuration

```
resource "okta_policy_rule_idp_discovery" "turo_oktapreview" {
  policy_id                 = <Policy ID>
  name                      = local.policy_name
  idp_id                    = okta_idp_saml.my_idp.id
  idp_type                  = "SAML2"
  network_connection        = "ANYWHERE"
  priority                  = 1
  status                    = "ACTIVE"
  user_identifier_attribute = "userType"
  user_identifier_type      = "ATTRIBUTE"
  platform_include {
    os_type = "ANY"
    type    = "ANY"
  }
  user_identifier_patterns {
    match_type = "EQUALS"
    value      = "Employee"
  }
}
```

### References

[policy_rule_idp_discovery](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_rule_idp_discovery)

**Comment by bogdanprodanj** [comment]
Hi, @nottooshort ! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.

**Comment by exitcode0** [comment]
I had a similar issue to this and worked around this via the following 
@nottooshort does this resolve your problem?

https://github.com/okta/terraform-provider-okta/issues/874#issuecomment-1009600614

**Comment by nottooshort** [comment]
@exitcode0 

A data resource is meant to lookup existing resources in the service. This issue relates to a catch-22 where the okta provider should be able to create any and all resources, however it instead requires a resource be create prior to terraform execution. There shouldn't be a case where an administrator needs to create the resource prior to bringing it into terraform state.
