### ISSUE TITLE
Terraform provider crash when "Rate Limiting Communications" is disabled. (terraform-provider-okta_v3.20.0)

### ISSUE THREAD

**Issue by farzadmahjobi** [okta/terraform-provider-okta#864]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_xxx

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Stack trace from the terraform-provider-okta_v3.20.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x17c41c2]

goroutine 108 [running]:
github.com/okta/terraform-provider-okta/okta.resourceRoleSubscriptionRead({0x1ae8fe8, 0xc000672840}, 0x22bbf18, {0x1890d20, 0xc00022b450})
	github.com/okta/terraform-provider-okta/okta/resource_okta_role_subscription.go:83 +0x182
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0004490a0, {0x1ae8f78, 0xc000c2a280}, 0x24, {0x1890d20, 0xc00022b450})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/resource.go:358 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004490a0, {0x1ae8f78, 0xc000c2a280}, 0xc00011f450, {0x1890d20, 0xc00022b450})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000462ea0, {0x1ae8f78, 0xc000c2a280}, 0xc000c2a2c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0004cab20, {0x1ae9020, 0xc00034e1e0}, 0xc0006722a0)
	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:298 +0x1fb
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1963100, 0xc0004cab20}, {0x1ae9020, 0xc00034e1e0}, 0xc000672240, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000c2a80, {0x1af8ad0, 0xc000698000}, 0xc000762000, 0xc0004cd350, 0x207e0f0, 0x0)
	google.golang.org/grpc@v1.41.0/server.go:1279 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0000c2a80, {0x1af8ad0, 0xc000698000}, 0xc000762000, 0x0)
	google.golang.org/grpc@v1.41.0/server.go:1608 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.41.0/server.go:923 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.41.0/server.go:921 +0x294

Error: The terraform-provider-okta_v3.20.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce

1) Login to Okta console and go to "Settings"-->"Account" tab page. On this page under "Rate Limiting Communications" uncheck "Enable Rate Limiting" and save.

![Screen Shot 2021-12-16 at 9 14 54 AM](https://user-images.githubusercontent.com/86008645/146388138-b8c178ad-86ff-4148-9d98-a3508845541c.png)

2) Now from the command line issue any Terraform plan/apply, you will notice that the "terraform-provider-okta" will crash during command execution.

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodanj** [comment]
Hi, @farzadmahjobi! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.

**Comment by bogdanprodan-okta** [comment]
Hi, @farzadmahjobi! The bug was caused by invalid subscription, since the roles have different sets of notification types, e.g.  `/api/v1/roles/REPORT_ADMIN/subscriptions/AGENT_AUTO_UPDATE_NOTIFICATION` request will return an empty response. I'll added additional validation for this resource as well as nil check. It will be available in the next version.
