### ISSUE TITLE
Add user type id to output of IdP resources.

### ISSUE THREAD

**Issue by CodyDunlap** [okta/terraform-provider-okta#865]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For custom SAML and OIDC IdPs, it would be nice if the IdP resource produced the id of the user type that is generated in relation to the IdP so that we can add custom attributes and mappings for that profile.

### New or Affected Resource(s)

- okta_idp_oidc
- okta_idp_saml

**Comment by bogdanprodanj** [comment]
Hi, @CodyDunlap! Thanks for submitting this issue! I'll start to work on this asap.
