### ISSUE TITLE
Terraform import okta_factor

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#866]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently attempting to terraform import a okta_factor results in an error 
`terraform import okta_factor.google_otp google_otp` 
`Error: failed to find factor: json: cannot unmarshal array into Go value of type sdk.OrgFactor`
I expect this is because this functionality was never implemented

It would be great to have this functionality as having a terraform plan result of no changes gives confidence when importing existing resources that your configuration matches the current state and won't affect unexpected changes

### New or Affected Resource(s)

- okta_factor

**Comment by bogdanprodanj** [comment]
Hi, @exitcode0! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.
