### ISSUE TITLE
okta_policy_password auth_provider = "LDAP"

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#867]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.67.0
+ provider registry.terraform.io/okta/okta v3.20.0

Your version of Terraform is out of date! The latest version
is 1.1.1. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

- okta_policy_password

### Terraform Configuration Files

```hcl
resource "okta_policy_password" "ldap_policy" {
  priority    = 2
  status      = "ACTIVE"
  name        = "LDAP Policy"
  description = "The LDAP policy contains settings that apply to users using delegated authentication from LDAP integrations."
  groups_included = [
    "<REDACTED>",
  ]

  auth_provider        = "LDAP"
}
```

### Expected Behavior

the attribute `auth_provider` on the resource `okta_policy_password` should have an additional valid value of `LDAP`

### Actual Behavior

importing a `okta_policy_password` with `auth_provider` with value `LDAP`
terraform will throw an error `Error: expected value to be one of 'OKTA', 'ACTIVE_DIRECTORY', got 'LDAP'`
When viewing the resource in the UI I can see that the auth provider is indeed `LDAP`
the state file will reflect the `LDAP` value in the `auth_provider` attribute

Work around is
```HCL
lifecycle {
  ignore_changes = [
      auth_provider
  ]
}
```

### Steps to Reproduce

1. TF import `okta_policy_password` with `auth_provider` with value `LDAP`
2. `terraform apply`

**Comment by bogdanprodanj** [comment]
Hi, @exitcode0! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.
