### ISSUE TITLE
Importing okta_policy_rule_mfa omits "enroll" attribute

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#868]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Importing `okta_policy_rule_mfa` omits `enroll` attribute. It also seems that this is omitted in the state import as well, this causes `terraform plan` to return a plan with "in place" changes even if you then define the `enroll` attribute to reflect your existing resources existing `enroll` configuration, this may cause confusion among some users

### New or Affected Resource(s)

- okta_policy_rule_mfa

**Comment by bogdanprodanj** [comment]
Hi, @exitcode0! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.
