### ISSUE TITLE
Which TF resource to use to add SAML roles in AWS app user assignment?

### ISSUE THREAD

**Issue by nsharma-fy** [okta/terraform-provider-okta#869]
I am trying to provision the "AWS Account Federation" app with TF. I am not able to find a suitable resource to assign the AWS SAML role to the use assignment (in the circle in the attached image), "okta_app_user" works for a simple assignment but does not have the option to specify the SAML role. 

 
<img width="666" alt="Screen Shot 2021-12-16 at 8 11 26 PM" src="https://user-images.githubusercontent.com/79729374/146488637-6adb1fa0-c38d-4a7f-9395-875db949da28.png">

**Comment by exitcode0** [comment]
`okta_app_group_assignment` or `okta_app_group_assignments` both have the `profile` attribute which you can pass a Json object

**Comment by nsharma-fy** [comment]
Thanks, @exitcode0  for your response. Using group resources may not work as we don't have okta groups, can we use profile attribute directly with okta users.  Also is there an example or documentation on how to use AWS SAML roles in profile. I couldn't find it at https://developer.okta.com/docs/reference/api/apps/#profile-object

**Comment by exitcode0** [comment]
looks like you can use `okta_app_user` with the following lifecycle meta argument on the `okta_app`
```HCL
lifecycle {
  ignore_changes = [
      users
  ]
}
```

**Comment by nsharma-fy** [comment]
Actually adding a profile like below in `okta_app_user` works, thank you @exitcode0 for the pointer on using profile 

```
profile  = jsonencode(
            {
               samlRoles    = [
                   "saml-role-name",
                ]
            }
        )
```
