### ISSUE TITLE
okta_policy_signon_default

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#870]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently we have `okta_policy_mfa_default` for MFA policies and we have `okta_policy_password_default` for password policies
Would be good to have `okta_policy_signon_default` for signon policies for consistency

Perhaps this has been intentionally omitted as there isn't anything to be configured on the default Signon policy?

### New or Affected Resource(s)

- okta_policy_signon_default

**Comment by bogdanprodanj** [comment]
Hi, @exitcode0! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.

**Comment by bogdanprodan-okta** [comment]
@exitcode0 yes, the reason is `okta_policy_signon_default` is immutable to any updates. It is however possible to get it using data source. Closing this issue for now. 
```
data "okta_policy" "test" {
  name = "Default Policy"
  type = "OKTA_SIGN_ON"
}
```
