### ISSUE TITLE
Error when modifying attribute statements in a SAML app

### ISSUE THREAD

**Issue by tmatilai** [okta/terraform-provider-okta#871]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.1.1
on darwin_amd64
+ provider registry.terraform.io/okta/okta v3.20.2
```

### Affected Resource(s)

- `okta_app_saml` resource (custom, not a pre-defined app)

### Expected Behavior

- Changes to `attribute_statements` would be successfully applied
- Also, the order of the statemetnts should not matter

### Actual Behavior

- It seems that all changes to the attribute statements causes a 403 error from a POST call to `/api/v1/apps/<APP_ID>/lifecycle/activate`.
    <details><summary>The error body</summary>

    ```json
    {
      "errorCode": "E0000143",
      "errorSummary": "App instance operation not allowed.",
      "errorLink": "E0000143",
      "errorId": "oaeAVGghzs-Qr2xiOb9org3zg",
      "errorCauses": [
       {
        "errorSummary": "The requested action cannot be supported for this application."
       }
      ]
    }
    ```
  
  </details>
- Another issue with attribute statements are that they are handled as an ordered list. At least after manual editing of the SAML configurations (like enabling the assertion encryption), the attribute statements are sorted by `type`, which can cause a diff in `plan` if they are in other order in the Terraform code. This might lead into constant  `apply` chain, but can't test because of the previous error.

### Steps to Reproduce

1. Create an `okta_app_saml` resource, with or without `attribute_staments` blocks
1. `terraform apply`
1. Make changes to the `attribute_staments`
1. `terraform apply`

### Important Factoids

Tested with the Preview version of Okta.

**Comment by nottooshort** [comment]
Terraform v0.14.9
+ provider registry.terraform.io/okta/okta v3.20.0

I agree that the order in which dictionary values of an attribute statement should be entirely agnostic. I've ran into similar issues when applying resources, then the terraform state gets modified and introduces new arguments that during subsequent runs, terraform constantly tries to make changes.

One helpful tool I've used in the import function for new apps. Make changes in okta (admin), then plan and match the diffs entirely.

I can only surmise that the logic behind the diff and the api expects the dictionary values to fit the following order of key \ value pairs. The following has worked for me without error.

```
  attribute_statements {
    type         = "GROUP"
    name         = "groups"
    filter_type  = "STARTS_WITH"
    namespace    = "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
    filter_value = "my-group-"
  }
```

Utilizing the plans in this manner also helps with lifecycle mappings such as `lifecycle { ignore_changes = [groups, users] }`  for managing the okta provider resource state.

It's also worth noting that setting an application from Inactive to Active is not possible via terraform. The transition from Active > Inactive is possible via terraform, however this unfortunately puts the application in a state of limbo which apparently is not modifiable from the api to reactivate. For this reason, we've made the decision to only deploy "Active" applications and hide the okta tile or remove users from an application group when necessary.

**Comment by bogdanprodanj** [comment]
Hi, @tmatilai! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.

**Comment by tmatilai** [comment]
> I agree that the order in which dictionary values of an attribute statement should be entirely agnostic.

In my case this is especially clumsy to work around, as the attribute statements come as a map to a common module, where the configuration blocks are created with `dynamic`, thus automatically sorted by the map key (`name` in this case).

I took a look at the implementation, and unfortunately I think a similar kind of matching logic would be needed as e.g. with the [aws_security_group_rule](https://github.com/hashicorp/terraform-provider-aws/blob/v3.70.0/internal/service/ec2/security_group_rule.go)s. Hopefully not as complicated though.

**Comment by tmatilai** [comment]
It seems that I can't reproduce the problems any more. 🤔 

Both our current production version tenant (`Version 2021.12.1 C`) and the Preview tenant (`Version 2021.12.2 C`) seem to work.

After configuring the assertion encryption in the admin console, the next Terraform run still wants to reorder the attribute statements, but the `apply` succeeds, and the state will be clean afterwards.

Was something changed? (Note that I didn't test this on production system at the time of filing the issue.)

**Comment by bogdanprodan-okta** [comment]
@tmatilai I didn't change anything in the provider itself

**Comment by nottooshort** [comment]
@bogdanprodan-okta @tmatilai - Perhaps it's not the provider but instead how the API handles the calls had changed?

**Comment by tmatilai** [comment]
Yes, as I tries to say in the description, the first error come from the API (which of course could have been a client error, too).  And at the time I only tested with a Preview Sandbox tenant. Later it worked there, and with a production version tenant.

So I suspect there was a bug in the Preview version, which was later fixed.

I'll close the issue. Thanks for the attention. 🙂

**Comment by CastleArg** [comment]
We are getting this exact same error, after successfully applying a SAML app (Google Workspace)
and then attempting to change values in the ` app_settings_json` and `user_name_template` properties.
We get 403 errors doing this, even when we attempt to put it back how it was.
This is being applied against a free dev instance, but we will also want to apply it to a paid instance once we get it working.
Any tips on how to proceed here?
