### ISSUE TITLE
TF import okta_group_schema_property omits index

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#872]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.67.0
+ provider registry.terraform.io/okta/okta v3.20.0

Your version of Terraform is out of date! The latest version
is 1.1.2. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

- okta_group_schema_property

### Expected Behavior

Terraform importing `okta_group_schema_property` should import the `index` attribute and TF plan should evaluate to no changes

### Actual Behavior

Terraform importing `okta_group_schema_property` omits the `index` attribute in state
This attribute is a required attribute meaning that it must be defined in config, but this attribute forces a replacement
the result is that you must replace your resource on a TF import

### Steps to Reproduce

1.  terraform import existing `okta_group_schema_property`
2. terraform state show -no-color >> main.tf
3. trim state-only attributes from resource
4. TF plan
5. `│ Error: Missing required argument`
6. `│ The argument "index" is required, but no definition was found.`

**Comment by bogdanprodanj** [comment]
Hi, @exitcode0! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.
