### ISSUE TITLE
Feature Request - okta_policy_idp_discovery_default

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#874]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently when defining `okta_policy_rule_idp_discovery` resources there doesn't seem to be any way to avoid hard coding the `policy_id`
a data source for `okta_policy_idp_discovery_default` would allow me to reference the policy_id dynamically

### New or Affected Resource(s)

- okta_policy_idp_discovery_default

### Potential Terraform Configuration

```hcl
data "okta_policy_idp_discovery_default" "default_idp_discovery" {}
```

**Comment by bogdanprodan-okta** [comment]
Hi, @exitcode0! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.

**Comment by exitcode0** [comment]
looks like I ended up working around this by doing the following 
This can be marked as resolved, perhaps some doco updates might be helpful for the next person running into this like I did

```hcl
data "okta_policy" "idp_discovery_policy" {
  name = "Idp Discovery Policy"
  type = "IDP_DISCOVERY"
}
resource "okta_policy_rule_idp_discovery" "example" {
  policy_id = data.okta_policy.idp_discovery_policy.id
}
```
