### ISSUE TITLE
Data source `okta_auth_server_policy` doesn't return its priority number

### ISSUE THREAD

**Issue by Shrirang97** [okta/terraform-provider-okta#875]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

- The data source [okta_auth_server_policy](https://registry.terraform.io/providers/okta/okta/latest/docs/data-sources/auth_server_policy) does not return its `priority number`. We need that to set the `priority` of other auth server policies.
- Also add `status` and other properties in return output.

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

https://github.com/okta/okta-sdk-golang/blob/master/okta/authorizationServerPolicy.go

**Comment by bogdanprodan-okta** [comment]
Hi, @Shrirang97! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.
