### ISSUE TITLE
Set negative priority number for `okta_auth_server_policy`

### ISSUE THREAD

**Issue by Shrirang97** [okta/terraform-provider-okta#876]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

- Set resource `okta_auth_server_policy` priority number to be last or last second and so on.
- Currently, only positive number is accepted.
- `-1` means last, `-2` means second last, and so on.

### New or Affected Resource(s)

- resource `okta_auth_server_policy`

### References

- https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_auth_server_policy.go
- https://github.com/okta/okta-sdk-golang/blob/master/okta/authorizationServerPolicy.go

**Comment by bogdanprodan-okta** [comment]
Hi, @Shrirang97! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.

**Comment by bogdanprodan-okta** [comment]
hi @Shrirang97! Unfortunately, bases on the [specs](https://developer.okta.com/docs/reference/api/policy/#policy-priorities) the priority can only be positive integer. This applies to all the priorities in all the resources. You can make a suggestion to Okta Support if you want this feature to be implemented in the future. Closing this issue for now.
