### ISSUE TITLE
`okta_authenticator` doesn't support import

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#877]
### Issue

When attempting to use the Okta Authenticator resource to import existing authenticators, the following error is reported:

```
terraform import okta_authenticator.email idXXXXXXXXXXXXXXXXX
Acquiring state lock. This may take a few moments...
okta_authenticator.email: Importing from ID "idXXXXXXXXXXXXXXXXX"...

│ Error: resource okta_authenticator doesn't support import
```

### Terraform Version
```
Terraform v1.1.2
on windows_amd64
+ provider registry.terraform.io/okta/okta v3.20.2
```

### Affected Resource(s)

- `okta_authenticator`

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bogdanprodan-okta** [comment]
Hi, @virgofx! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.
