### ISSUE TITLE
Okta Authenticator doesn't support FIDO2 (WebAuthn)

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#878]
### Issue

When attempting to use the Okta Authenticator resource to create a new FIDO2 (WebAuthn) resource, the provider doesn't allow it. 
![image](https://user-images.githubusercontent.com/739719/147505774-edfcc16d-5fa9-4925-a1d1-0c507c531760.png)

### Sample Config

```
resource "okta_authenticator" "fido2_webauthn" {
  name   = "Security Key or Biometric"
  status = "ACTIVE"
  key    = "webauthn"
}
```

####  Error 
```
│ Error: expected value to be one of 'okta_email', 'google_otp', 'okta_verify', 'onprem_mfa', 'okta_password', 'phone_number', 'rsa_token', 'security_question', 
'duo', got 'webauthn'
│
│   with okta_authenticator.fido2_webauthn,
│   on XXXXXXX.tf line 43, in resource "okta_authenticator" "fido2_webauthn":
│   43:   key    = "webauthn"
│
```

Additionally, because this resource can't be imported as result of https://github.com/okta/terraform-provider-okta/issues/877, this currently is a blocker.

### Terraform Version
```
Terraform v1.1.2
on windows_amd64
+ provider registry.terraform.io/okta/okta v3.20.2
```

### Affected Resource(s)

- `okta_authenticator`

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bogdanprodan-okta** [comment]
Hi, @virgofx! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.
