### ISSUE TITLE
Resource `okta_policy_mfa` doesn't support Identity Engine `okta_verify`

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#880]
Identity Engine uses `okta_verify`

![image](https://user-images.githubusercontent.com/739719/147507584-6f655dfa-3c12-42a3-98ec-3a1bee7e580f.png)

This isn't supported via the `okta_policy_mfa` Terrraform provider arguments.

https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_mfa

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bogdanprodan-okta** [comment]
Hi, @virgofx! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.

**Comment by virgofx** [comment]
Update: `okta_verify` is specific to Authenticators and not Factors (which is what the current resource supports)

Upon reviewing the source code it appears that the `okta_policy_mfa` is using policies and specifically `Factors` as the core component which is specific to Classic Engine. Thus to migrate and support OIE the `Authenticators` settings need to be incorporated into both `okta_policy_mfa` and `okta_policy_mfa_default`. Likely a few more helper functions and potentially updating the SDK as well.

I'm not sure on the best approach since the top level keys are all specific for factors. We could refactor so the top level entries are either:
- `factors` and  (then move all current top level factor keys into this)
- `authenticators`  (and then add support for the new authenticators that are for OIE)

I can implement a fix for above ^^; however, I'm not sure if there's a better way.

**Comment by bogdanprodan-okta** [comment]
Yes, the idea is to keep this backward compatible, so the resource is available for both Classic and OIE orgs.

**Comment by virgofx** [comment]
Do you want me to take a stab at what I suggested above (or this might extend my Go experience and better that you handle it?) Effectively:

- Update `okta_policy_mfa` and `okta_policy_mfa_default`
- Create new `factors` attribute and note this is the way moving forward
- Create new `authenticators` attribute and have those write out appropriate policy authenticator settings
- Mark existing top level primary factor keys as DEPRECATED as these will all need to be done inside `factors`
- Update documentation

**Comment by bogdanprodan-okta** [comment]
You can keep the existing structure, but add the missing fields into `type PolicySettings struct`. In addition, add a computed field `is_oie` to the resource, so when you read the resource, you can check if the `factors` or `authenticators` field is present. Based on this flag, you can create a model for both OIE and Classical orgs.
