### ISSUE TITLE
`okta_authenticator` settings doesn't diff whitespace changes

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#881]
When using the `okta_authenticator` the `settings` attribute is not properly diffed to account for whitespace changes. This results in permanent changes detected.

```
resource "okta_authenticator" "okta_verify" {
  name   = "Okta Verify"
  status = "ACTIVE"
  key    = "okta_verify"
  settings = jsonencode({
    "userVerification" : "PREFERRED",
    "channelBinding" : {
      "required" : "NEVER",
      "style" : "NUMBER_CHALLENGE"
    },
    "compliance" : {
      "fips" : "OPTIONAL"
    }
  })
```

```
  # okta_authenticator.okta_verify will be updated in-place
  ~ resource "okta_authenticator" "okta_verify" {
        id                          = "autahjkfkpXXXXXXXXXXXXX"
        name                        = "Okta Verify"
      ~ settings                    = jsonencode( # whitespace changes
            {
                channelBinding   = {
                    required = "NEVER"
                    style    = "NUMBER_CHALLENGE"
                }
                compliance       = {
                    fips = "OPTIONAL"
                }
                userVerification = "PREFERRED"
            }
        )
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

As you can tell, there are no changes. Re-running this will continue to output 1 changed resource.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v1.1.2
on windows_amd64
+ provider registry.terraform.io/okta/okta v3.20.2
````

### Affected Resource(s)

- okta_authenticator

**Comment by bogdanprodan-okta** [comment]
Hi, @virgofx! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.
