### ISSUE TITLE
Allow `okta_domain_verification` to succeed when existing status is "COMPLETED"

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#882]
There are now 2 domain options when creating a domain in the API with the new EA Lets Encrypt / Okta managed domains. I believe that the `okta_domain` may need to be updated to handle both variations.

Additionally, verification may come outside or via UI. Thus, we should be able to create the verification record and have it succeed since it can't be imported. That way it can still be managed via Terraform in the event that at some point it fails.

### Sample configuration
```
resource "okta_domain" "default" {
  name = "okta.my-custom-domain.com"
}

# DNS records handled externally, validated externally

resource "okta_domain_verification" "default" {
  domain_id = okta_domain.default.id
}
```

### Output
```
╷
│ Error: failed to verify domain after several attempts, current validation status: COMPLETED
│
│   with okta_domain_verification.default,
│   on customizations-domain.tf line 9, in resource "okta_domain_verification" "default":
│    9: resource "okta_domain_verification" "default" {
│
╵
```

The expected output should be that this succeeds because it's already complete.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.1.2
on windows_amd64
+ provider registry.terraform.io/okta/okta v3.20.2
```

### Affected Resource(s)

- okta_domain_verification

**Comment by bogdanprodan-okta** [comment]
Hi, @virgofx! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.
