### ISSUE TITLE
Support Configuring Features for `okta_app_saml`

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#883]
The features API exists. It should be configurable via `okta_app_saml` or a linked new resource (which would help with the prior issue where it was ignored internally as these were changed via UI.)

API reference: https://developer.okta.com/docs/reference/api/apps/#update-feature-for-application

Seeing as there is additional configuration for the features, I'd likely lean towards deprecating the `features` from the `okta_app_saml` resource and moving it to a new resource. I think this would clean up some of the lifecycle management ignoring happening internally now to make it read-only - Thus, by removing all of that into a proper CRUD resource `okta_app_saml_features` it would make more sense.

### New or Affected Resource(s)

- `okta_app_saml`

Potentially new resource
- `okta_app_saml_features`   (And then deprecate the `features` from `okta_app_saml` and include a `app_id` parameter back to the `okta_app_saml.id` value.

### Potential Terraform Configuration

```hcl
resource "okta_app_saml" "aws" {
  label              = "amazon"
  preconfigured_app  = "amazon_aws_sso"
  status             = "ACTIVE"
  user_name_template = "$${source.email}"

  # The following features would actually ENABLE these. Or move to separate resource block to enable
  features = [
    "GROUP_PUSH",
    "SCIM_PROVISIONING",
    "PUSH_NEW_USERS",
    "PUSH_PROFILE_UPDATES",
    "PUSH_USER_DEACTIVATION",
    "REACTIVATE_USERS",
  ]
  ...
}
```

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bogdanprodan-okta** [comment]
Hi, @virgofx! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.

**Comment by virgofx** [comment]
Hey @monde. Any insight on getting `features` supported via the actual API for an app. The read-only component of `features` isn't terrible; however, I have a few custom SAML apps where I configure `SCIM_PROVISIONING` in the API and every time the app is updated via the API (even when including the optional `features: ["SCIM_PROVISIONING"]`, it clears it out (Again, testing the API directly - not using Terraform). It effectively means you can't manage custom SAML apps with custom features.

If the API supported this the Terraform is pretty much ready to go with inline `features` on the app.

Note: There is not one reference to features being read-only on the API docs https://developer.okta.com/docs/reference/api/apps/.

The only reference is actually in the provider docs here (which was helpful to understand, thanks)

**Comment by monde** [comment]
@virgofx I was not aware of this issue. I've pulled off the stale tag. I will hopefully be able to address it.

**Comment by virgofx** [comment]
Thanks. Basically the original issue reference was to pull out features. That may or may not be useful as an enhancement. While investigating features, I did run into the separate issue noted above about features getting reset.

As noted in the provider docs - Features is READ_ONLY. This tends to work fine for any preconfigured SAML app. However, the new issue above is that for 100% custom SAML app with SCIM_PROVISIONING, any update via PUT to the app, will reset features to empty array.  :(  

So it's more of an internal / API issue. Not sure best place to forward this info but sounds like you'll be able to relay.

**Comment by monde** [comment]
I think @BalaGanaparthi is interested in helping out here also.

**Comment by virgofx** [comment]
Bug Update: While I thought the UI might be error free ... I found an edge case where the Okta UI breaks. Since most of the other tabs have unique sectional endpoints ... they don't break; however, if you change the logo it removes the features/SCIM provisioning (and all SCIM configured settings as well).

Attached a screenshare of the bug:

![Animation](https://user-images.githubusercontent.com/739719/164532432-492858d4-404e-40c3-af44-1b39ace64997.gif)




From a fix perspective ... if making features writable such that we can configure features (and possibly SCIM settings) is too difficult, then at least at a minimum I'd expect the backend API to ignore `features: []` 100% on a `PUT` and just re-use existing settings (that would be the safest , quick fix, although supporting configuration of features would be the best option).

**Comment by virgofx** [comment]
Hey @monde - were you ever able to reproduce the issue above?
