### ISSUE TITLE
Cannot Use Preconfigured AWS SSO App with Provider Resource `aws_app_saml`

### ISSUE THREAD

**Issue by xee5ch** [okta/terraform-provider-okta#885]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```sh
$ terraform -v
Terraform v1.1.2
on linux_amd64
+ provider github/go-gandi/gandi v2.0.0-rc3
+ provider registry.terraform.io/hashicorp/aws v3.70.0
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/okta/okta v3.20.2
```
### Affected Resource(s)

- `okta_app_saml`

### Terraform Configuration Files

My whole configuration, sans credential config and API keys for AWS, Gandi DNS, and Okta is below, errors are evident at this commit.

https://github.com/oscal-club/infrastructure/commit/9118850f5415eb50d51136e59c6fe81e5746ea33

### Debug Output

Can someone provider a less public way to share the output? Reviewing the log _I think_ I might see some sensitive data, but not sure if I need to redact or not.

### Panic Output

There was no panic.

### Expected Behavior

The `okta_app_saml` instance would be created with the `amazon_aws_sso` preconfigured app without me providing the `acsURL` and `entityID` in advance, which appear to be application specific.

### Actual Behavior

The app crashes with an error from the provider. Manually create an instance of the AWS Single Sign-On preconfigured app from my Terraform code (link above by commit).

```sh
TF_LOG=DEBUG aws-vault exec keyname -- terraform apply -auto-approve | tee -a okta_app_saml_error.log
...
│ Error: failed to create SAML application: the API returned an error: Operation on application settings failed.. Causes: errorSummary: acsURL: The field cannot be left blank, errorSummary: entityID: The field cannot be left blank
│ 
│   with module.okta_app_saml_aws.okta_app_saml.this,
│   on modules/okta/app_saml_preconfigured/main.tf line 1, in resource "okta_app_saml" "this":
│    1: resource "okta_app_saml" "this" {
│ 
```

If I import one manually created SAML app instance from the App Integration Catalog, selecting the AWS Single Sign-on application in the the Okta web console and import it into the state like so, it works fine after the fact.

```sh
aws-vault exec keyname-- terraform import module.okta_app_saml_aws.okta_app_saml.this 0oSomeOktaAppInstanceIdHere
```

Mysteriously, then the SAML configuration data is already loaded, as I confirm by clicking around in the web console.

### Steps to Reproduce

1. Set AWS creds (or comment out modules), Gandi API Key (or comment out modules), and Okta API key.
2. `terraform apply`
3. Reviews error from the creation of the `okta_app_saml` instance.

### Important Factoids

I am not sure if this is an issue with the provider, the underlying Golang SDK, the API, or more realistically how I read docs, relevant examples on GitHub, or how I fundamentally misunderstand the docs.

All I want to do is maintain in Terraform a configuration for AWS SSO app in Okta, and then configure that for the AWS SSO external identity provider in Terraform.

### References

N/A at this time.

**Comment by bogdanprodan-okta** [comment]
Hi, @xee5ch! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.

**Comment by xee5ch** [comment]
OK, thanks @bogdanprodan-okta. Let me know if I should send along the logs I collected from running `TF_LOG=debug`. I couldn't figure out if it does not, but there did look to be some credential info flying back and forth so I'd rather not attach it here on a public repo issue. :-)

**Comment by bogdanprodan-okta** [comment]
@xee5ch the fields that you got in the error are required for this app. Here is the example of the config:
```
resource "okta_app_saml" "this" {
  app_links_json     = <<JSON
  {
    "amazon_aws_sso_link" : true
  }
JSON

  // acsURL (AWS SSO ACS URL) and entityID (AWS SSO issuer URL) are required fields
  app_settings_json  = <<JSON
  {
    "acsURL" : "https://eu-west-2.signin.aws.amazon.com/platform/saml/acs/*****",
    "entityID" : "https://eu-west-2.signin.aws.amazon.com/platform/saml/*****"
  }
JSON

  label              = "AWS Single Sign-on"
  preconfigured_app  = "amazon_aws_sso"
  user_name_template = "$${source.email}"
  skip_groups        = true
  skip_users         = true
}
```

**Comment by xee5ch** [comment]
Sorry for the delayed response. I will be sure to check with this updated configuration and report back.

**Comment by monde** [comment]
Thanks @xee5ch , let me know what you find.

**Comment by monde** [comment]
Closing for now, please reopen when there is more information.

**Comment by Tmanoche** [comment]
@xee5ch Did this solve your problem? i'm having a similar issue.
