### ISSUE TITLE
Error importing user

### ISSUE THREAD

**Issue by tkjwa** [okta/terraform-provider-okta#886]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/okta/okta v3.20.2

### Affected Resource(s)

- okta_user

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "okta_user" "example" {
  email = "address@domain.com"
  first_name = "First"
  last_name = "Last"
  login = "address@domain.com"
}
```

### Expected Behavior

Import the user

### Actual Behavior

It seems like the API_TOKEN has not been used so the provider is looking for other config (client id, scopes and private key)
```
Error: [ERROR] invalid configuration: when using AuthorizationMode 'PrivateKey', you must supply 'ClientId', 'Scopes', and 'PrivateKey' or 'PrivateKeySigner'
│
│   with provider["registry.terraform.io/okta/okta"],
│   on /home/klein/jwalab/playtix/infra/okta/_main.tf line 19, in provider "okta":
│   19: provider "okta" {}
```
### Steps to Reproduce

* Create a user in okta
* Configure the okta provider with API KEY
* Import the user

1. `terraform import okta_user.example <okta_user_id>`

Thank you for your help

**Comment by tkjwa** [comment]
I've had the same issue with another resource so it might not be related to the `okta_user` resource but the import in general

**Comment by bogdanprodan-okta** [comment]
Hi, @tkjwa! Thanks for submitting this issue! There are two ways to configure terraform provider:
1) via end vars (`OKTA_ORG_NAME`, `OKTA_BASE_URL`, `OKTA_API_TOKEN`)
2) using provider's block
```
provider "okta" {
  org_name  = "my company"
  base_url  = "okta.com"
  api_token = "****"
}
```
Which one did you use?

**Comment by tkjwa** [comment]
Hello @bogdanprodan-okta 
I am using env vars through terraform cloud

**Comment by bogdanprodan-okta** [comment]
@tkjwa the error you are seeing is because the provider can not read these env vars.

**Comment by tkjwa** [comment]
Hi @bogdanprodan-okta , indeed i've just found the following which explains why I was having issues: https://www.terraform.io/cli/import#remote-backends 
Sorry for the noise and thank you for your help !
