### ISSUE TITLE
Importing okta_profile_mapping 

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#888]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the documentation states that there is no reason to import this resource
I think the ability to import these would be a nice to have as it would allow for "no change" terraform plans when importing existing resources, this makes for easy PR approvals
I believe the current workflow with this resource is to replicate your existing mappings, terraform plan will then output a plan to create the resource, this can make it harder to tell for sure if your configuration matches the current state of Okta

### New or Affected Resource(s)

- okta_profile_mapping

**Comment by bogdanprodan-okta** [comment]
Hi, @exitcode0! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.

**Comment by exitcode0** [comment]
Could we please re-open this one, I think Stale bot has done stalebot things
