### ISSUE TITLE
How to use client_id scopes and private_key?

### ISSUE THREAD

**Issue by simonweil** [okta/terraform-provider-okta#892]
I'm trying to understand the usage of client_id, scopes and private_key vs. an api_key.

Is there any documentation explaining the difference and how to obtain the values required?

Thanks
Simon

edit from @monde:
Don't use internet websites for production secrets and audit all software used to generate secrets. Here is a better example of using Terraform to create a PEM and JWKS:
https://github.com/okta/terraform-provider-okta/issues/1249#issuecomment-1301238359

**Comment by bogdanprodan-okta** [comment]
Hi, @simonweil! Thanks for submitting this issue! 
1. [API token](https://developer.okta.com/docs/guides/create-an-api-token/main/) can be created using admin Okta console Security > API > Tokens Crete Token. API tokens inherit the privilege level of the admin account that is used to create them
2. Using client_id, scopes and private_key can give more granular access to the org resources. Basically, caller exchange client_id, scopes and private_key for Bearer token and use it to make API calls. You can read more about this type of auth [here](https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/main/). 

This is simplified example of how to create and use access token:
1. Generate JWK using this https://mkjwk.org/
2. Convert it to private/public keys using this https://8gwifi.org/jwkconvertfunctions.jsp
3. Add JWK key to service app
4. Grand necessary scopes in Okta API Scopes in that app.
5. Config sample:
```
provider "okta" {
  org_name  = "my-org"
  base_url  = "okta.com"
  private_key = file("a.pem") // this is the file with the private key
  client_id = "0oazdwjh3wTJdfeRW0h7" // clientID from the service app
  scopes = ["okta.apps.manage", "okta.users.read", "okta.users.manage", "okta.policies.manage", "okta.groups.manage"]
}
```
6. Run terraform

**Comment by simonweil** [comment]
Thanks so much for the explanation!
It would be great to add it to the provider documentation :)

It says you need OKTA for developers, so if I just use OKTA platform as SSO, is this option for me?

**Comment by simonweil** [comment]
Maybe my question was missed, if I just use OKTA platform as SSO, is this option for me?

**Comment by bogdanprodan-okta** [comment]
I think yes, as long as you can create service app and add JWK key into it. I will also double-check with the team responsible for this functionality.

**Comment by noinarisak** [comment]
Hi @simonweil, feedback well heard regarding documentation! I totally agree and documentation improvements are on the roadmap from our Product Management team.

RE: Your question. Yes, if you planning to just set up/manage SSO, you can go down `client_id`, `scope`, and `private_key` route. You probably have to identify the right scopes, ie At minimal `okta.apps.manage` and etc, that aligns with the resources in your HCL script. However, using the `client_id/etc` route does have limitations due to the nature of dependence that Terraform and Okta Provider providers when it CRUDing resources on Okta tenant. At this time, for example, `okta_org_configuration`, to my understanding will not work since there is no scope defined for it yet and the only option is API Token route.  Sadly I don't have ETA if a new scope will be created that will have parity between both `client_id/etc` and API Token authentication options.

**Comment by simonweil** [comment]
Thank you for the answers @noinarisak and @bogdanprodan-okta!
This answers all the questions I had :)

**Comment by monde** [comment]
Additional details to try out if anyone is trying to get private key working for themselves https://github.com/okta/terraform-provider-okta/issues/1035#issuecomment-1079356101

**Comment by dbshelke** [comment]
> Hi, @simonweil! Thanks for submitting this issue!
> 
> 1. [API token](https://developer.okta.com/docs/guides/create-an-api-token/main/) can be created using admin Okta console Security > API > Tokens Crete Token. API tokens inherit the privilege level of the admin account that is used to create them
> 2. Using client_id, scopes and private_key can give more granular access to the org resources. Basically, caller exchange client_id, scopes and private_key for Bearer token and use it to make API calls. You can read more about this type of auth [here](https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/main/).
> 
> This is simplified example of how to create and use access token:
> 
> 1. Generate JWK using this https://mkjwk.org/
> 2. Convert it to private/public keys using this https://8gwifi.org/jwkconvertfunctions.jsp
> 3. Add JWK key to service app
> 4. Grand necessary scopes in Okta API Scopes in that app.
> 5. Config sample:
> 
> ```
> provider "okta" {
>   org_name  = "my-org"
>   base_url  = "okta.com"
>   private_key = file("a.pem") // this is the file with the private key
>   client_id = "0oazdwjh3wTJdfeRW0h7" // clientID from the service app
>   scopes = ["okta.apps.manage", "okta.users.read", "okta.users.manage", "okta.policies.manage", "okta.groups.manage"]
> }
> ```
> 
> 6. Run terraform

Above steps worked for me but If we generate-the-jwk-using-the-admin-console and use the same in PEM format i am getting below error .
https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/main/#generate-the-jwk-using-the-admin-console
PEM File Format :
-----BEGIN PRIVATE KEY-----
XXXXXX
-----END PRIVATE KEY-----

Error: failed to get SAML application: RSA private key is of the wrong type

**Comment by monde** [comment]
An example of using Terraform to create a PEM, JWKS, and Okta OAuth app:
https://github.com/okta/terraform-provider-okta/issues/1249#issuecomment-1301238359

**Comment by rrs-mckinsey** [comment]
Was able to make it work with generating JWKS key within Okta. Essentially, the Okta SDK is expecting older private_key PEM format for RSA but the generated cert within Okta is using new format. I am using okta provider 3.11, followed these steps.

1. Generate public keys in okta
2. Copy the PEM form of private key
3. Convert it to older format using `openssl rsa -in generated.key -out new.key`
4. Assigned the resulting key to environment variable OKTA_API_PRIVATE_KEY
