### ISSUE TITLE
imported okta_app_user_base_schema_property caused apply failure 

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#894]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.67.0
+ provider registry.terraform.io/okta/okta v3.20.0

Your version of Terraform is out of date! The latest version
is 1.1.3. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

- okta_app_user_base_schema_property

### Terraform Configuration Files

```hcl
resource "okta_idp_saml" "<REDACTED-IDP>" {
  ### General Settings
  name   = "<REDACTED-NAME>"
  status = "ACTIVE"

  ### Authentication Settings
  username_template = "idpuser.subjectNameId"
  # subject_filter = ""
  subject_match_type  = "USERNAME"
  account_link_action = "AUTO"
  # account_link_group_include = ""
  provisioning_action = "AUTO"

  ### JIT Settings
  profile_master       = true
  deprovisioned_action = "NONE"
  suspended_action     = "NONE"
  groups_action        = "ASSIGN"
  groups_filter        = []
  groups_assignment = [
    okta_group.<REDACTED_GROUP>.id,
  ]

  ### SAML Protocol Settings
  issuer  = "<REDACTED>"
  sso_url = "<REDACTED>"
  kid     = "<REDACTED>"

  ### Advanced Settings
  sso_binding                  = "HTTP-POST"
  request_signature_scope      = "REQUEST"
  request_signature_algorithm  = "SHA-256"
  response_signature_scope     = "ANY"
  response_signature_algorithm = "SHA-256"
  # sso_destination
  acs_type       = "INSTANCE"
  max_clock_skew = 120000

  # issuer_mode
  subject_format = []
  # name_format
  # groups_attribute
  # subject_match_attribute
}

resource "okta_group" "<REDACTED_GROUP>" {
  description = ""
  name        = "<REDACTED_GROUP>"
}

resource "okta_app_user_base_schema_property" "<REDACTED-IDP>-userName" {
  app_id   = okta_idp_saml.<REDACTED-IDP>.id
  master   = "PROFILE_MASTER"
  title    = "Username"
  index    = "userName"
  type     = "string"
  required = true
}
```

### Expected Behavior

if the resource has been terraform imported terraform should not attempt to re-create the resource

### Actual Behavior

Terraform attempts to re-create the resource, potentially due to API limitations, but because the field already exists, this fails
```Error: failed to update application user base schema: the API returned an error: Api validation failed: updateAppUserSchemas. Causes: errorSummary: Property variable name must be unique within profile. Property userName is already present.```

### Steps to Reproduce

1. Import an existing `okta_app_user_base_schema_property` resource
2. `terraform apply`

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @exitcode0! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.
