### ISSUE TITLE
Error Building Provider ` no field or method Certificate`

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#898]
I'm trying to build and test the provider locally. Following the quickstart guide in the README I'm receiving the following errors:

```
root@45fc21f24114:/main# make build
go mod tidy
==> Checking that code complies with gofmt requirements...
go install
# github.com/okta/terraform-provider-okta/okta
okta/data_source_okta_app_saml_metadata.go:67:57: desc.SSODescriptor.RoleDescriptor.KeyDescriptors[0].KeyInfo.Certificate undefined (type saml.KeyInfo has no field or method Certificate)
okta/resource_okta_app_saml.go:437:58: desc.SSODescriptor.RoleDescriptor.KeyDescriptors[0].KeyInfo.Certificate undefined 
(type saml.KeyInfo has no field or method Certificate)
okta/saml.go:45:52: desc.KeyInfo.Certificate undefined (type saml.KeyInfo has no field or method Certificate)
okta/saml.go:47:49: desc.KeyInfo.Certificate undefined (type saml.KeyInfo has no field or method Certificate)
make: *** [GNUmakefile:23: build] Error 2
```

Any insight would be great. Thanks in advance.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bogdanprodan-okta** [comment]
Hi, @virgofx! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.
