### ISSUE TITLE
Missing attribute reference in document for "okta_auth_server_scope"

### ISSUE THREAD

**Issue by tgoodsell-tempus** [okta/terraform-provider-okta#9]
Copied this over from the articulate repo.

## Expected Behavior
There appear to be other attributes exposed by an instance of the "okta_auth_server_scope" resource, such as name, which are not documented.
## Actual Behavior
Current attribute reference: https://www.terraform.io/docs/providers/okta/r/auth_server_scope.html#attributes-reference

In the documentation example for claim, it shows the use of a "name" attribute which is not documented in scope: https://www.terraform.io/docs/providers/okta/r/auth_server_claim.html#example-usage.

## Additional info
N/A

**Comment by quantumew** [comment]
@tgoodsell-tempus Thanks for copying this over. I should be able to move the remainder of the issues soon. 

Please elaborate if I am misunderstanding. `name` is documented [here](https://www.terraform.io/docs/providers/okta/r/auth_server_scope.html#argument-reference) but not [here](https://www.terraform.io/docs/providers/okta/r/auth_server_scope.html#attributes-reference). I think that is standard practice. Optional/required properties are documented in arguments section, and computed properties are documented in the attributes section. Correct me if I am wrong on that though, I am going off a single example in the AWS provider docs.

**Comment by tgoodsell-tempus** [comment]
Cheers, let me do a little digging since I'm not 100% on the best practices.

I'm under the impression is "Argument Reference" should contain all the required and optional inputs the resource can have; while "Attributes Reference" should contain all of the exposed attributes a created/usable resource object can have (all the <resource_type>.<resource_instance>.<attribute> calls)

**Comment by quantumew** [comment]
@tgoodsell-tempus cool I’ll do a little digging as well and we can decide if that needs to change. Thanks!

**Comment by tgoodsell-tempus** [comment]
I'm really struggling to find any clearly written documentation guidelines for the terraform site. 

However, I believe this PR from the AWS provider is a good example of what I'm referring to: https://github.com/terraform-providers/terraform-provider-aws/pull/10971/files

They've supported new "attributes" which aren't the things you're giving the API to create the resource but the metadata/properties of the resource once it's created. They've documented all of those in the "attributes" section.

**Comment by tgoodsell-tempus** [comment]
Another good example I think is the data source objects in the AWS provider:
https://www.terraform.io/docs/providers/aws/d/iam_policy.html

In this example, the ARN is required to "find" the policy using the API, once picked up it then has a set of attributes you can use in your TF code; including ARN. Just an example of how an object can have an argument and attribute which are the same.

**Comment by tgoodsell-tempus** [comment]
I suppose if maybe I'm miss understanding a terraform principal that both the "arguments" and "attributes" can be referenced using the `<resource>.<instance>.<item>` format, then this would be a non-issue.
