### ISSUE TITLE
`okta_app_saml`: Deprecated  `groups` attribute removes App-Group assignment made by `okta_app_group_assignment`

### ISSUE THREAD

**Issue by frousselet** [okta/terraform-provider-okta#904]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.1.3
on darwin_amd64
+ provider registry.terraform.io/okta/okta v3.20.2
```

### Affected Resource(s)

- okta_app_saml
- okta_app_group_assignment

### Terraform Configuration Files

```hcl
resource "okta_app_saml" "cognito" {
  # I won't use this since it is deprecated
  # groups = [
  #  okta_group.cognito.id
  # ]

  # SAML config...
}

resource "okta_group" "cognito" {
  name       = "cognito-${var.environment}"
  skip_users = true
}

resource "okta_app_group_assignment" "cognito" {
  app_id   = okta_app_saml.cognito.id
  group_id = okta_group.cognito.id
}
```

### Expected Behavior

App-Group assignment should remain unchanged if resource `okta_app_group_assignment` is unchanged.

### Actual Behavior

The resource `okta_app_saml` removes the App-Group assignment created by `okta_app_group_assignment` when deprecated `groups` attribute is absent.

```hcl
# okta_app_saml.cognito will be updated in-place
resource "okta_app_saml" "cognito" {
  ~ groups                     = [
      - "somegroup",
    ]
    id                         = "someapp"
    name                       = "someapp"
    # (41 unchanged attributes hidden)

    # (3 unchanged blocks hidden)
}
```

For now I prevent this with a `ignore_changes` lifecycle on `groups` attribute.

### Steps to Reproduce

1. `terraform apply`
2. Resources are created
3. `terraform apply`
4. App-Group assignment is removed by `okta_app_saml`
5. `terraform apply`
6. App-Group assignment is restored by `okta_app_group_assignment`
7. `terraform apply`
8. App-Group assignment is removed by `okta_app_saml`
9. ...

**Comment by ymylei** [comment]
@frousselet I'm pretty sure this cannot be really fixed in terraform without a breaking change. You'll need to do a
```hcl
lifecycle {
    ignore_changes = [users, groups]
  }
```
on the group resources you use these alternative assignment resources with.

**Comment by bogdanprodanj** [comment]
In addition, please use `skip_groups = true`. In this case, it won't do any API calls regarding `groups`.
