### ISSUE TITLE
`okta_app_metadata_saml`: SAML metadata file contains the wrong FQDN since the provider cannot authenticate with a custom domain

### ISSUE THREAD

**Issue by frousselet** [okta/terraform-provider-okta#905]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.1.3
on darwin_amd64
+ provider registry.terraform.io/okta/okta v3.20.2
```

### Affected Resource(s)

- data.okta_app_metadata_saml

### Terraform Configuration Files

```hcl
data "okta_app_metadata_saml" "cognito" {
  app_id = okta_app_saml.cognito.id
  key_id = okta_app_saml.cognito.key_id
}
```

### Expected Behavior

Metadata file should contains the custom domain name instead of the default `xxx.okta.com` one.

### Actual Behavior

The metadata file contains the default `xxx.okta.com` FQDN. The user is redirected to the wrong domain.

### Steps to Reproduce

1. Set OKTA environment variables
2. `terraform apply`

**Comment by stmyers** [comment]
If this is any help, I've worked around this using an outputs like this: 

```hcl
output "metadata_url" {
  description = "Public Metadata URL for SAML app"
  value       = "https://sso.customurl.com/app/${okta_app_saml.saml_app.entity_key}/sso/saml/metadata"
}
```
It looks like the URL is dynamically placed based on the URL you browse from - so if you hit the endpoint from the default URL, your metadata URL will be default, otherwise it will be custom if you use the custom URL in the metadata URL.

**Comment by frousselet** [comment]
Hi @stmyers,

Thanks, this is a good workaround, I didn't think about this way to do.

I'm pretty sure this is an issue with Okta, but maybe there is a way for the provider to manage this (for example with an attribute).
