### ISSUE TITLE
Importing okta_rate_limiting causes crash

### ISSUE THREAD

**Issue by jamesathey** [okta/terraform-provider-okta#909]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.1.3
on darwin_amd64
+ provider registry.terraform.io/okta/okta v3.20.3
```

### Affected Resource(s)

- okta_rate_limiting

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    okta = {
      source = "okta/okta"
      version = "~> 3.20"
    }
  }
}

# Configure the Okta Provider
provider "okta" {
    org_name  = "<removed for security reasons>"
    base_url  = "okta.com"
    api_token = "<removed for security reasons>"
}

resource "okta_rate_limiting" "client_based_rate_limiting" {
  login                  = "PREVIEW"
  authorize              = "PREVIEW"
  communications_enabled = true
}
```

### Debug Output

[Debug Output gist](https://gist.github.com/jamesathey/36d370d95712c3e364764303044da0ee)

### Panic Output

[crash.log](https://gist.github.com/jamesathey/aca70586817bd77115aa5fe376e5ef76)

### Expected Behavior

The docs for `okta_rate_limiting` state:

> Rate limit settings can be imported without any parameters.
>
>$ terraform import okta_rate_limiting.example .

That is what I was attempting to do for an existing Okta instance that I want to manage with terraform.

### Actual Behavior

The plugin crashed.

### Steps to Reproduce

1. Define an `okta_rate_limiting` resource in a terraform file.
1. `terraform import okta_rate_limiting.(name of resource) .`

**Comment by monde** [comment]
Thanks @jamesathey - I've opened a PR to put a nil bumper there to prevent a panic.

**Comment by monde** [comment]
Fixed and release in https://github.com/okta/terraform-provider-okta/pull/929
