### ISSUE TITLE
Manage custom domain settings.

### ISSUE THREAD

**Issue by tecnobrat** [okta/terraform-provider-okta#91]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We would like to be able to manage our custom domain settings in terraform, specifically the SSL certificate.

We manage our certificates with letsencrypt, and since we cannot automate the update of the SSL certificate with okta, its incredibly hard to keep these SSL certs updated.

**Comment by noinarisak** [comment]
Hi @tecnobrat, thanks for submitting an Issue. Unfortunately, this provider cannot manage your feature request if there is no API endpoint from Okta. 

Sadly, the best course of action is to submit a request on https://ideas.okta.com/. Sorry!

**Comment by shk3bq4d** [comment]
> Sadly, the best course of action is to submit a request on https://ideas.okta.com/. Sorry!

for those coming in here, one step is to take @noinarisak 's advice and vote on the exact same request:
* https://ideas.okta.com/app/#/case/107241

alternative okta ideas that suggest a fully-managed-by-okta automated workflow for custom domains (so no longer in the terraform scope)
* https://ideas.okta.com/app/#/case/106229
* https://ideas.okta.com/app/#/case/119838

cc: @kevin-bowers

**Comment by jlundstedt** [comment]
API for managing custom domains is available nowadays:

https://developer.okta.com/docs/reference/api/domains/

@bogdanprodan-okta FYI
