### ISSUE TITLE
Failed to set recovery.factors.recovery_question.status to INACTIVE in password policy.

### ISSUE THREAD

**Issue by Praki404** [okta/terraform-provider-okta#916]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

I am having issue on updating question_recovery in **policy_password**. I followed the documentation to set it to INACTIVE. https://github.com/okta/terraform-provider-okta/blob/master/website/docs/r/policy_password_default.html.markdown
 
![image](https://user-images.githubusercontent.com/76016438/150231086-af4c3064-063c-408e-85d3-ef69d19a9cf2.png)

### Terraform Version
1.1.3

### Terraform Configuration Files
resource "okta_policy_password" "myacc-password-pol" {
  name                   = "myacc-policy"
  status                 = "ACTIVE"
  description            = "myacc password policy"
  groups_included = [
      okta_group.MyAccountCustomers.id
  ]
  password_min_symbol = 1
  password_show_lockout_failures = true
 question_recovery = "INACTIVE"
}
### Debug Output
Terraform apply is failing to apply the question_recovery to INACTIVE.

Terraform apply output:
![image](https://user-images.githubusercontent.com/76016438/150231172-c05ee0f1-8a74-42aa-9d73-0fd719ed9db8.png)

│ Error: failed to update password policy: the API returned an error: Api validation failed: settings.recovery.factors.recovery_question.status. Causes: errorSummary: settings.recovery.factors.recovery_question.status: The recovery.factors.recovery_question.status property cannot be set to INACTIVE.
│ 
│   with okta_policy_password.myacc-password-pol,
│   on policy_password.tf line 1, in resource "okta_policy_password" "myacc-password-pol":
│    1: resource "okta_policy_password" "myacc-password-pol" {

**Comment by damianharden** [comment]
@Praki404 `question_recovery` cannot be set to `INACTIVE` unless the `DISABLE_SECURITY_QUESTION_FOR_RECOVERY` flag is set on the Okta tenant that Terraform is being run against.

Please raise a case with Okta support to set the `DISABLE_SECURITY_QUESTION_FOR_RECOVERY` flag on the Okta tenant that Terraform is being run against. Once Okta support confirms that this has been done you should be able to disable security questions via Terraform without any issues.

**Comment by Praki404** [comment]
Thanks @damianharden for your reply. I have asked okta support to turn on DISABLE_SECURITY_QUESTION_FOR_RECOVERY flag.

**Comment by pro4tlzz** [comment]
Thanks for mentioning this!
