### ISSUE TITLE
`okta_app_oauth` `logo_uri` is not applied to the Application

### ISSUE THREAD

**Issue by BalaGanaparthi** [okta/terraform-provider-okta#920]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
1.1.4

### Affected Resource(s)

- okta_app_oauth

### Terraform Configuration Files

```hcl
resource "okta_app_oauth" "sdk_app_b_pwd_another_od" {
  label                      = "SDK : App B (On-Demand model - AuthN with Pwd + Another Factor)"
  # logo_uri                   = "http://localhost:8890/sdk.png"
  type                       = "browser"
  grant_types                = ["authorization_code"]
  token_endpoint_auth_method = "none"
  redirect_uris              = ["${var.app_schema_host_port}/sdk-app-B.html"]
  post_logout_redirect_uris  = ["${var.app_schema_host_port}"]
}
```

### Expected Behavior

The logo should have been applied to the application 

### Actual Behavior

The logo is not applied to the application

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @BalaGanaparthi! I couldn't reproduce the issue and `logo_uri` works fine. 
<img width="738" alt="Screenshot 2022-02-10 at 13 43 29" src="https://user-images.githubusercontent.com/71279414/153402380-818f6222-e8e8-408d-b486-1cb75595cec4.png">

**Comment by BalaGanaparthi** [comment]
Hi @bogdanprodan-okta , 
I have assumed the `logo_uri` as the logo for the app that is shown in the admin console instead of the user consent dialog box.
If the `logo_uri` is specifically for `user consent` functionality, then its working as expected

Is there any resource that sets the logo for the app that's displayed when viewing the app from the admin console?

**Comment by bogdanprodanj** [comment]
@BalaGanaparthi you should use `logo` field for that, however, it's a file path, so you need to have that logo stored locally

**Comment by BalaGanaparthi** [comment]
@bogdanprodan-okta , Thank You. I was able to set the logo to the app with `logo` attribute

**Comment by bogdanprodan-okta** [comment]
Awesome!
