### ISSUE TITLE
Docs: okta_security_notification_emails warning not clear

### ISSUE THREAD

**Issue by thatguysimon** [okta/terraform-provider-okta#926]
Hi,
The docs page for `okta_security_notification_emails` shows the following warning:
> WARNING:
This resource is available only when using api token in the provider config.

It's not very clear. Can you explain what it means? How is that different from any other resource?

Thank you!

**Comment by rankol** [comment]
How are you setting up your Okta provider configuration? There is an `api_token` field in the below link.

https://registry.terraform.io/providers/okta/okta/latest/docs

**Comment by monde** [comment]
Thanks for responding @rankol ! @thatguysimon does this answer your question?

**Comment by thatguysimon** [comment]
@rankol @monde So the warning is there to point out that you must authenticate via an `api_token`, rather than as a service app with OAuth2 (`client_id`+`scopes`+`private_key`)?

**Comment by monde** [comment]
> @rankol @monde So the warning is there to point out that you must authenticate via an `api_token`, rather than as a service app with OAuth2 (`client_id`+`scopes`+`private_key`)?

Hi @thatguysimon , yes to make use of `okta_security_notification_emails` you need to have your config include a`api_token`.

Here is the original PR that @bogdanprodan-okta wrote for the `okta_security_notification_emails` resource https://github.com/okta/terraform-provider-okta/pull/728/files . When I look through the code flows and I can see the underlying Okta API calls for the notification emails are done with an api token.

Let me know if this answers your question. Thanks!

**Comment by thatguysimon** [comment]
@monde Got it! Thanks for your help!
