### ISSUE TITLE
Update `okta_profile_mapping` Documentation to refer to allowed Scopes

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#927]
The `okta_profile_mapping` [resource documentation](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/profile_mapping) lists:

```
WARNING:
This feature available only when using api token in the provider config.
```

This is no longer true. The required scopes for the Mapping API are `okta.profileMappings.manage` or for data `okta.profileMappings.read`

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by monde** [comment]
thanks for the PR @virgofx ! I'll get this merged tomorrow.
