### ISSUE TITLE
`okta_domain_verification` reports error in-spite of the `validationStatus`: `VERIFIED`

### ISSUE THREAD

**Issue by BalaGanaparthi** [okta/terraform-provider-okta#930]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

``` output
Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.8.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/okta/okta v3.20.3
```

### Affected Resource(s)

- okta_domain_verification

### Terraform Configuration Files

```hcl
resource "okta_domain_verification" "xyz_domain_verify" {
  domain_id = okta_domain.xyz_domain.id
  depends_on = [
    time_sleep.wait_60_seconds
  ]
}
```

### Panic Output

```output
│ Error: failed to verify domain after several attempts, current validation status: VERIFIED
│ 
│   with okta_domain_verification.xyz_domain_verify,
│   on main.tf line 57, in resource "okta_domain_verification" "xyz_domain_verify":
│   57: resource "okta_domain_verification" "xyz_domain_verify" {
│ 
```

### Expected Behavior

When checked at the DNS the `TXT` and `CNAME` data are set and when checked in Okta `({Admin Console} > {Customizations} > {Domain})`  the page was at setting the `Certificates` which is shown when the Verification is successful
 
The domain verification must be reported as successful since the `validationStatus` is reported as `VERIFIED` (as well as DNS records and at Okta the domain page shows to input certificates)

### Actual Behavior

The domain verification reports `Error` in-spite of the validation being reported as `VERIFIED`

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by virgofx** [comment]
That's weird and almost impossible from the code. If the domain status is `VERIFIED` or `COMPLETED` it should return true.

https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_domain_verification.go#L39
https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_domain_verification.go#L62-L69

Unless ... Golang switch statements don't fall through by default... and that appears to be the case. o.O

**Comment by virgofx** [comment]
Added a fix to ensure `VERIFIED` works properly.
