### ISSUE TITLE
Set Email OTP token lifetime using Terraform

### ISSUE THREAD

**Issue by Praki404** [okta/terraform-provider-okta#934]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi team,
I tried to look for the okta terraform resources to update email OTP token lifetime. However, It is available from okta dashboard UI.
![image](https://user-images.githubusercontent.com/76016438/151724823-b62b7036-b26f-4b92-aafa-684cf9737f87.png)

- okta version: 5.x
- terraform version: 1.1.3

Okta has provided the internal Api to update this token lifetime. It would be great if this feature can be updated using terraform. Writing api call just to update the email token lifetime is overwhelm as this setting is done once in a tenant lifetime.

Okta internal Api :

curl --location --request POST 'https://{OKTA_DOMAIN}/internal/v1/admin/access/mfa_policies/okta_email/settings' \
--header 'Authorization: SSWS <API token>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "tokenLifetimeInMinutes": 60
}'

**Comment by monde** [comment]
@Praki404 updating the email authentication is available in the public admin api for authenticators see:

- https://developer.okta.com/docs/reference/api/authenticators-admin/#update-authenticator-settings
- https://developer.okta.com/docs/reference/api/authenticators-admin/#authenticator-properties

`settings.tokenLifetimeInMinutes` / number / "Specifies the lifetime of an email token and only applies to the email Authenticator type. Default value is 5 minutes." / okta_email

So you can make a JSON formatted string for settings in your Okta terraform authenticator date or resource.

Implementation:
- https://github.com/okta/terraform-provider-okta/blob/master/okta/data_source_okta_authenticator.go#L32-L36
- https://github.com/okta/terraform-provider-okta/blob/master/okta/data_source_okta_authenticator.go#L97-L100

See the documentation examples.
- https://github.com/okta/terraform-provider-okta/blob/master/website/docs/r/authenticator.html.markdown
- https://github.com/okta/terraform-provider-okta/blob/master/website/docs/d/authenticator.html.markdown

I'm going to close this ticket. Reopen if you have additional details that I can debug.

**Comment by monde** [comment]
@Praki404 one caveat, is your org an Okta Classic or an Okta Identity Engine org? If it is classic then it won't have access to the authenticator admin API, that is an OIE only feature. I don't believe there are any plans to make a public API for the authenticators in the classic orgs.

**Comment by monde** [comment]
@bogdanprodan-okta has some ideas about this, fyi.

**Comment by bogdanprodan-okta** [comment]
@Praki404 I don't think we are going to implement this functionality, since all orgs will migrate from Classical to OIE very soon.
