### ISSUE TITLE
Missing company_name and job_title fields on okta_user resource

### ISSUE THREAD

**Issue by vianel** [okta/terraform-provider-okta#939]
Trying to create a new okta_app user from the provider I'm getting the company_name and jobTitle fields are now required field, I don't see those fields available in the current version of the resource, please refer more details below

Terraform and okta provider version 
```
Terraform v1.0.9
on darwin_amd64
+ provider registry.terraform.io/okta/okta v3.20.3
```

Resource
```
  # okta_user.jhon will be created
  + resource "okta_user" "jhon" {
      + email        = "jhon.smith@example.com"
      + first_name   = "jhon"
      + id           = (known after apply)
      + last_name    = "smith"
      + login        = "jhon.smith@example.com"
      + organization = "Testing Inc."
      + raw_status   = (known after apply)
      + status       = "ACTIVE"
      + title        = "Director"
    }
```

Error
```
│ Error: failed to create user: the API returned an error: Api validation failed: com.saasure.core.services.user.InvalidUserProfileException: Could not create user due to invalid profile: com.saasure.framework.validation.util.SimpleErrors: 2 errors
│ Field error in object 'newUser' on field 'jobTitle': rejected value [null]; codes [platform.cvd.profile.property.constraint.violation.required.newUser.jobTitle,platform.cvd.profile.property.constraint.violation.required.jobTitle,platform.cvd.profile.property.constraint.violation.required]; arguments [jobTitle]; default message [Required property is missing]
│ Field error in object 'newUser' on field 'companyName': rejected value [null]; codes [platform.cvd.profile.property.constraint.violation.required.newUser.companyName,platform.cvd.profile.property.constraint.violation.required.companyName,platform.cvd.profile.property.constraint.violation.required]; arguments [companyName]; default message [Required property is missing]. Causes: errorSummary: jobTitle: Value for required property jobTitle is missing, errorSummary: companyName: Value for required property companyName is missing
│
│   with okta_user.jhon,
│   on main.tf line 62, in resource "okta_user" "jhon":
│   62: resource "okta_user" "jhon" {
│
```

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_xxx

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by bogdanprodanj** [comment]
You can try setup missing fields via `custom_profile_attributes` field.

**Comment by monde** [comment]
Right, I was going to say it sounds like `jobTitle` and `companyName` are custom user attributes @vianel  https://help.okta.com/en/prod/Content/Topics/users-groups-profiles/usgp-add-custom-user-attributes.htm

I'm going to close this issue @vianel . Let me know if @bogdanprodanj suggestion of making use of `custom_profile_attributes` doesn't work for you.

**Comment by vianel** [comment]
yeah that workaround works, thanks
