### ISSUE TITLE
Documentation does not list new identity_provider option in okta_policy_rule_signon resource

### ISSUE THREAD

**Issue by gregwhorley** [okta/terraform-provider-okta#945]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_policy_rule_signon

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "okta_policy_rule_signon" "require_mfa" {
  name              = "Default"
  status            = "ACTIVE"
  mfa_required      = "true"
  mfa_prompt        = "ALWAYS"
  risc_level        = ""
  policy_id         = okta_policy_signon.require_mfa.id
}
```

### Panic Output

10:39:40  │ Error: failed to update sign-on policy rule: the API returned an error: Api validation failed: conditions. Causes: errorSummary: conditions: Invalid condition type specified: identityProvider.
10:39:40  │ 
10:39:40  │   with okta_policy_rule_signon.require_mfa,
10:39:40  │   on okta.tf line 80, in resource "okta_policy_rule_signon" "require_mfa":
10:39:40  │   80: resource "okta_policy_rule_signon" "require_mfa" {

### Expected Behavior

No error from provider and terraform apply would have succeeded

### Actual Behavior

Error pasted above occurs and terraform apply fails

### Steps to Reproduce

1. retrieve latest okta provider version: 3.20.6
2. add okta_policy_rule_signon resource as shown above
3. `terraform apply`

### References

https://github.com/okta/terraform-provider-okta/commit/3e7d51da1f11ede00e82bc5e1254d23d3c0bd3e3

**Comment by monde** [comment]
Thanks @gregwhorley I will look into this.

**Comment by gregwhorley** [comment]
I must have missed this, but the option is listed at the bottom of https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_rule_signon

However, it claims that it is optional and requires a feature flag be set...

**Comment by monde** [comment]
@gregwhorley was this working for you previously and `v3.20.6` is a breaking change for you?

**Comment by gregwhorley** [comment]
@monde Yes, last recorded version we used was 3.20.2 and the same terraform code I pasted did not result in apply failure.

**Comment by gregwhorley** [comment]
I think there's a bug here. I added the identity_provider option to the resource and still received the error during terraform apply. Re-running the apply with no code changes resulted in a successful apply.

**Comment by monde** [comment]
Thanks for the details @gregwhorley . If I get a PR done today it won't be released until tomorrow/Friday. I'll keep you posted.

**Comment by monde** [comment]
@gregwhorley , in our stand up @bogdanprodan-okta did a copy and paste from the example and it works for him. Is this still an issue for you? If so reopen the issue with more details for us to debug with. Thanks!

https://github.com/okta/terraform-provider-okta/blob/master/examples/okta_policy_rule_signon/other_identity_provider.tf
