### ISSUE TITLE
Add support for AWS Integration accounts

### ISSUE THREAD

**Issue by fatbasstard** [okta/terraform-provider-okta#947]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Just got an email from Okta Ideas about allowing the accounts in the Integration to be automatable:

```
There's been an update on your Okta Ideas request: Allow programmatically adding new accounts to the AWS integration v...

Your request status is now: Released

Here's the update from Emily Wendell of Okta Ideas:

“This request has been released! Thank you for your input. Your feedback is helping us build a better product. To see what else we have in the works, please check out our product roadmap: https://support.okta.com/help/s/productroadmap”
```

Haven't checked the API yet, but wanted to drop this already here. I'll update this issue when I have more information

### New or Affected Resource(s)

- okta_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by monde** [comment]
thanks @fatbasstard, I'm looking forward to seeing some more background on this enhancement idea.

**Comment by monde** [comment]
@fatbasstard do you have any more background on this for me? Thanks!

**Comment by fatbasstard** [comment]
Hi @monde ,

Create a ticket at Okta 2 years ago to implement the automation of the "integrations" account list since we're creating AWS accounts here and there.

Last week got an email with "It's implemented!" but I also cannot find anything related to this (yet) 😂 

Sent them an email again and will keep looking 🕵️

**Comment by monde** [comment]
Hi @fatbasstard , apologies for the delay. Can you forward or email the information Okta has sent you so I can follow up on it internally? My Okta email is mike.mondragon@okta.com . Give me names of people in Okta you've been in communication with. fwiw, I'm on the Developer Experience team and am responsible for our golang sdks and it seems like other parts of the machine have been communicating with you. Thanks!

**Comment by fatbasstard** [comment]
@monde Email is forwarded.

**Comment by monde** [comment]
Hi @fatbasstard I didn't receive the forward (checked spam folders also) - mike.mondragon@okta.com, thanks!

**Comment by fatbasstard** [comment]
Hi @monde,

It's sent. After sending it again (I thought) I saw the previous was still in draft 🤦

**Comment by monde** [comment]
@fatbasstard I still need to follow up internally on this for you @fatbasstard . Just ack'ing current state.

**Comment by monde** [comment]
@fatbasstard I'm waiting for confirmation from my colleague, but I'm thinking that the Okta Ideas email you sent me was closed in relation to a generally available feature, perhaps when [Amazon Web Services Account Federation](https://help.okta.com/en/prod/Content/Topics/DeploymentGuides/AWS/aws-deployment.htm) was released. This integration can be set up in the Okta Admin console via `Application > Applications > Browse App Catalog > (search for) "AWS Account Federation"`.

So, you can set this up via the Okta Admin console. However, this can't be done through the Okta Terraform provider. Not all of the functionality in the Okta Admin console is available through Okta's public APIs. The Okta Terraform provider only interacts with Okta core through public APIs, whereas the Okta Admin console can and does make use of private APIs.

Unfortunately, when I was researching how we could implement this in the terraform provider I found this information in the API documentation https://developer.okta.com/docs/reference/api/apps/#app-names : "The Okta Integration Network (OIN) is a catalog of applications that can be added to your Okta organization. Each application has a unique name (key) that you must specify." and "The catalog is currently not exposed via an API. While additional apps may be added via the API, only the following template applications are documented:"

So setting up an AWS integration is app is not currently possible via Okta's public API and therefore not possible with terraform either.

I'm going to close this issue for now.

**Comment by monde** [comment]
@fatbasstard one other thing that came to mind ... I bet those integration apps are just SAML apps. So, what you could do is make an AWS app via the Okta Admin console. Then access it with the data source `okta_app_saml`. Something like:

```terraform
# by label
data "okta_app_saml" "aws" {
  label = "My AWS Account"
}

# by id
data "okta_app_saml" "aws" {
  id = "abc"
}
```

If no saml, experiment with the other `okta_app_*` application types. Let me know if this helps you out, at least a little bit, I hope.

https://registry.terraform.io/providers/okta/okta/latest/docs/data-sources/app_saml

**Comment by monde** [comment]
I'm seeing this in my `/api/v1/apps` output after creating one of those apps, note the sign on mode.

```json
{
        "id": "xxx",
        "name": "amazon_aws",
        "label": "AWS Account Federation",
        "status": "ACTIVE",
        "lastUpdated": "2022-03-17T20:12:19.000Z",
        "created": "2022-03-17T20:11:35.000Z",
        "accessibility": {
            "selfService": false,
            "errorRedirectUrl": null,
            "loginRedirectUrl": null
        },
        "visibility": {
            "autoLaunch": false,
            "autoSubmitToolbar": false,
            "hide": {
                "iOS": false,
                "web": false
            },
            "appLinks": {
                "login": true
            }
        },
        "features": [],
        "signOnMode": "SAML_2_0",
        "credentials": {
            "userNameTemplate": {
                "template": "${source.login}",
                "type": "BUILT_IN"
            },
            "signing": {
                "kid": "xxx"
            }
        },
        "settings": {
            "app": {
                "appFilter": "okta",
                "groupFilter": "aws_(?{{accountid}}\\d+)_(?{{role}}[a-zA-Z0-9+=,.@\\-_]+)",
                "secretKey": null,
                "useGroupMapping": false,
                "joinAllRoles": false,
                "identityProviderArn": null,
                "overrideAcsURL": null,
                "sessionDuration": 3600,
                "roleValuePattern": "arn:aws:iam::${accountid}:saml-provider/OKTA,arn:aws:iam::${accountid}:role/${role}",
                "awsEnvironmentType": "aws.amazon",
                "accessKey": null,
                "loginURL": "https://console.aws.amazon.com/ec2/home",
                "secretKeyEnc": null
            },
            "notifications": {
                "vpn": {
                    "network": {
                        "connection": "DISABLED"
                    },
                    "message": null,
                    "helpUrl": null
                }
            },
            "notes": {
                "admin": null,
                "enduser": null
            },
            "signOn": {
                "defaultRelayState": "foo",
                "ssoAcsUrlOverride": null,
                "audienceOverride": null,
                "recipientOverride": null,
                "destinationOverride": null,
                "attributeStatements": []
            }
        }
```
