### ISSUE TITLE
Infinite loop on okta_app data source

### ISSUE THREAD

**Issue by PurrBiscuit** [okta/terraform-provider-okta#95]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
terraform -v
Terraform v0.12.23
+ provider.aws v2.54.0
+ provider.consul v2.6.1
+ provider.datadog v2.7.0
+ provider.okta v3.0.37
+ provider.vault v2.9.0
```

### Affected Resource(s)

* [data.okta_app](https://www.terraform.io/docs/providers/okta/d/app.html)

### Terraform Configuration Files

```hcl
data "okta_app" "scim_import" {
  label = "Example OIN Import"
}
```

### Debug Output

```
2020-03-26T15:19:07.477Z [DEBUG] plugin.terraform-provider-okta_v3.0.37_x4: GET /api/v1/apps??after=0oancj172zSy5Y2hJ0h7&filter=status+eq+%22ACTIVE%22&limit=200 HTTP/1.1
2020-03-26T15:19:11.235Z [DEBUG] plugin.terraform-provider-okta_v3.0.37_x4: GET /api/v1/apps??after=0oancj172zSy5Y2hJ0h7&filter=status+eq+%22ACTIVE%22&limit=200 HTTP/1.1
2020-03-26T15:19:15.693Z [DEBUG] plugin.terraform-provider-okta_v3.0.37_x4: GET /api/v1/apps??after=0oancj172zSy5Y2hJ0h7&filter=status+eq+%22ACTIVE%22&limit=200 HTTP/1.1
2020-03-26T15:19:20.046Z [DEBUG] plugin.terraform-provider-okta_v3.0.37_x4: GET /api/v1/apps??after=0oancj172zSy5Y2hJ0h7&filter=status+eq+%22ACTIVE%22&limit=200 HTTP/1.1
```

### Expected Behavior

The data source should find the app by `label` name and return the resulting `id`.

### Actual Behavior

The `terraform plan` run gets stuck waiting for the `okta_app` data source to error or return a result.  Eventually have to kill the process altogether.

Looking at the `DEBUG` logs (the ones included above as an example) it shows the same `after` pagination key being used on all subsequent requests.  The same results are returned for each of those calls to the `apps` endpoint instead of moving on to the next set of `apps` in the list.  Seems like it gets stuck in an infinite loop.

### Steps to Reproduce

1. Have an Okta org with over `200` Active Applications in it (we have close to 2000 currently)
1. `terraform plan`

**Comment by quantumew** [comment]
@noinarisak Noticed this one came across. Can you mark this as a bug? This will be a pretty nasty one, yet an easy one to fix. I am guessing something changed on Okta's API, this has been in place for a while. Here is the code that figures out how to go to the next page: https://github.com/terraform-providers/terraform-provider-okta/blob/71e363be2678f66f999699351f57a98350e52ddb/sdk/api_supplement.go#L54.

**Comment by quantumew** [comment]
Set aside a little time later today. Going to tackle this one. Feel free to assign to me @noinarisak

**Comment by noinarisak** [comment]
@quantumew issue assigned. 

Just a heads up, the Okta DevEx team plans to release a updated okta-sdk-golang in early April. We should start to talk about the new update.

**Comment by Ruffio** [comment]
Has this issue been fixed?
