### ISSUE TITLE
okta_policy_rule_signon Invalid condition type specified: identity Provider

### ISSUE THREAD

**Issue by rohit-janu** [okta/terraform-provider-okta#953]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
3.20.6

### Affected Resource(s)

Okta Identity Engine
- okta_policy_rule_signon

### Terraform Configuration Files

```hcl
**Example 1**
resource "okta_policy_rule_signon" "example"{
 access = "DENY"
 authtype = "ANY"
 behaviors = []
 users_excluded = []
 mfa_lifetime = 0
mfa_remember_device= false
name = "Deny_Access"
network_connection = "ZONE"
network_excludes = [data.okta_network_zone.company.id]
policy_id = okta_policy_signon.deny_access.id
primary_factor = "PASSWORD_IDP"
priority = 1
risc_level = ""
session_idle = 120
session_lifetime = 0
session_persistent = false
identity_provider = "SPECIFIC_IDP"
identity_provider_ids = [data.okta_idp_saml.company.id]
}

**Example 2**

resource "okta_policy_rule_signon" "example"{
 access = "DENY"
 authtype = "ANY"
 behaviors = []
 users_excluded = []
 mfa_lifetime = 0
mfa_remember_device= false
name = "Deny_Access"
network_connection = "ZONE"
network_excludes = [data.okta_network_zone.company.id]
policy_id = okta_policy_signon.deny_access.id
primary_factor = "PASSWORD_IDP"
priority = 1
risc_level = ""
session_idle = 120
session_lifetime = 0
session_persistent = false
}
```

### Debug Output

{
"type": "SIGN_ON",
"name": "Deny_Access"
"status": "ACTIVE",
"priority": 1,
"conditions": {
"authContext": {
"authType": "ANY"
},
"network": {
"connection": "ZONE",
"exclude": [
"xxxxxxxxxxxxx"
]
}
},
"actions": {
"signon": {
"access": "DENY",
"primaryFactor": "PASSWORD_IDP",
"rememberDeviceByDefault": false,
"requireFactor": false,
"session": {
"maxSessionIdeMinutes": 120,
"maxSessionLifetimeMinutes": 0,
"usePersistentCookie": false
}
}
}
}

[RESPONSE]
HTTP/2.0 400 Bad Request

{
"errorCode": "E0000001"
"errorSummary": "Api validation failed: conditions"
"errorLink": "E0000001"
"errorId": "oae......."
"errorCauses": [
{
"errorSummary": "conditions: Invalid condition type specified: identityProvider."
}
]
}

### Panic Output

Error: failed to create sign-on policy rule: failed to create policy rule: the API returned an error: Api validation failed: conditions. Causes: errorSummary: conditions: Invalid type specified: identityProvider.
### Expected Behavior

Okta Sign-on Policy Rule should have got created

### Steps to Reproduce

Create the resource as shown in example 1

1. `terraform plan`
2. `terraform apply`

Create the resource as shown in example 2

1. `terraform plan`
2. `terraform apply`
3. 
### Important Factoids

Okta Identity Engine

### References

- #0000

**Comment by rohit-janu** [comment]
I was able to reproduce the issue through Postman.  The request through terraform has the following

"identityProvider": {
"provider": "ANY"
}

If I remove the identityProvider object, then the request through Postman succeeds.  

Terraform adds the above even if it is not specified in the resource

**Comment by mit2222** [comment]
I am getting the same issue with terraform.
I am getting an error 
failed to create sign-on policy rule: failed to create policy rule: the API returned an error: Api validation failed: conditions. Causes: errorSummary: conditions: Invalid condition type specified: identityProvider.


```
resource "okta_policy_rule_signon" "example_rule" {
 access = "DENY"
 authtype = "ANY"
  name        = "example-global-policy-signon"
  policy_id = okta_policy_signon.example_policy.id
  primary_factor = "PASSWORD_IDP"
  network_connection = "ANYWHERE"
  status = "ACTIVE"
}
```

**Comment by ivan-sukhomlyn** [comment]
[@bohdanprodan-okta](https://github.com/bogdanprodan-okta) Could we please include these changes in the latest releases? I'm getting the same error using the 3.28 provider version - https://github.com/okta/terraform-provider-okta/blob/v3.28.0/okta/resource_okta_policy_rule_sign_on.go#L138
```
Error: failed to create sign-on policy rule: failed to create policy rule: the API returned an error: Api validation failed: conditions. Causes: errorSummary: conditions: Invalid condition type specified: identityProvider.
```

**Comment by mit2222** [comment]
I was able to fix my issue.  I had to use 3.20.8 version. I am not getting an error "Invalid condition type specified: identityProvider" anymore.

```
terraform {
  required_providers {
    okta = {
      source = "okta/okta"
      version = "~> 3.20.8"
    }
  }
}
resource "okta_policy_signon" "example_policy_signon" {
  name = "example-policy-signon"
  description = "Sign-On policy"
  status = "ACTIVE"
  groups_included = [okta_group.sf_example_group.id]
}

resource "okta_policy_rule_signon" "example_allow_rule_signon" {
  policy_id = okta_policy_signon.example_policy_signon.id
  name = "example-global-allow-rule"
  status = "ACTIVE"
  session_idle = 30
  session_lifetime = 30
}

resource "okta_policy_rule_signon" "example_deny_rule_signon" {
  policy_id = okta_policy_signon.example_policy_signon.id
  name = "example-global-deny-rule"
  access = "DENY"
  status = "ACTIVE"
  network_connection = "ZONE"
  network_includes = [okta_network_zone.example_network_zone_block.id]
}

resource "okta_network_zone" "example_network_zone_block" {
  name = "example-network-zone-block"
  type = "DYNAMIC"
  usage = "POLICY"
  dynamic_locations = ["US-TX"]
}
```

**Comment by rtlong** [comment]
Also see #1079 - looks like this issue regressed and was fixed there (in 0ebeae7c5e062a084809397ca93b194cdef17a94) before more recently being reverted again by 57d52bb09fe5554ae9eccd31ce43220f3c5c5838

**Comment by emanor-okta** [comment]
@rtlong - https://github.com/okta/terraform-provider-okta/issues/1166#issuecomment-1182556364

**Comment by chinelo-obitube** [comment]
can this be reopened. I have same issue with 4.12
