### ISSUE TITLE
Renaming profile property fails

### ISSUE THREAD

**Issue by ahmei0** [okta/terraform-provider-okta#954]
We are renaming a custom profile attribute but failing with following error .

I think it is happening because it tries to delete it and found it mapped. Is there a way that this resource handles unmapping before deleting a property?

This error disappears if I manually remove mapping and re run pipeline.

Error: failed to delete application user schema property: the API returned an error: Api validation failed: updateAppUserSchemas. Causes: errorSummary: Property myAccountPermissions cannot be deleted. It is used to populate user.myAccountPermissions.
│ 
│ 
╵
╷
│ Error: failed to delete user schema property myAccountPermissions: the API returned an error: Api validation failed: updateUserSchemas. Causes: errorSummary: Property myAccountPermissions cannot be deleted. It is used to populate oidc_client.myAccountPermissions.
│ 
│ 
╵

**Comment by monde** [comment]
Apologies for the delay. I'm trying to catch up on our backlog @ahmei0 are you still having this issue? Can you provide me with some sample/example Terraform config so I can attempt to reproduce what you are seeing to help me find a resolution? Thanks!

**Comment by monde** [comment]
@ahmei0 open this issue back up if it is still current for you.
