### ISSUE TITLE
`okta_group_role` `target_group_list` removes target groups on every other terraform apply

### ISSUE THREAD

**Issue by lucascantor** [okta/terraform-provider-okta#968]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
- `0.14.2`

### Affected Resource(s)

- `okta_group_role`

### Terraform Configuration Files

```hcl
resource "okta_group_role" "okta_admin_group_membership_openpath_group_membership_openpath" {
  group_id  = okta_group.okta_admin_role_groups["okta_admin_group_membership_openpath"].id
  role_type = "GROUP_MEMBERSHIP_ADMIN"
  target_group_list = [
    var.okta_groups["openpath_chicago"],
    var.okta_groups["openpath_dublin"],
    var.okta_groups["openpath_it"],
    var.okta_groups["openpath_london"],
    var.okta_groups["openpath_remote"],
    var.okta_groups["openpath_sf"],
    var.okta_groups["openpath_sydney"],
    var.okta_groups["openpath_sydney_24hrs"],
    var.okta_groups["openpath_we"],
  ]
  disable_notifications = true
}
```

### Debug Output

- https://gist.github.com/lucascantor/bd0bee0f3f957978528b8dc24d7f73cb

### Expected Behavior

No changes should be planned or applied.

### Actual Behavior

- `terraform plan` [shows a plan](https://gist.github.com/lucascantor/bd0bee0f3f957978528b8dc24d7f73cb) for target groups to be removed and re-added the `target_group_list`.
  - (effectively no net change)
- `terraform apply` removes 7 of 9 target groups from the `target_group_list`.
- Subsequent `terraform plan` and `terraform apply` re-adds the missing 7 target groups back to the `target_group_list`.
- The process repeats indefinitely on further subsequent `terraform plan` and `terraform apply` steps.

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

**Comment by lucascantor** [comment]
Wondering if this is somehow related to https://github.com/okta/terraform-provider-okta/issues/597

**Comment by monde** [comment]
@lucascantor , apologies for the delay, I'm to catch up on our backlog. Is this still occurring for you? I did do a cursory look and that seems weird that it seems like there is some sort of casing error going on, see: https://gist.github.com/lucascantor/bd0bee0f3f957978528b8dc24d7f73cb#file-okta_group_role-target_group_list-unexpected_target_group_removal-txt-L5-L6 :
```diff
          - "00g8qc8nepxc5cFrP2p7",
          + "00g8qc8nepxc5cfrp2p7",
```
Let me know where this is at for you before I put more time into. Thanks for your help!

**Comment by lucascantor** [comment]
@monde thank you so much for replying! Yes, this is unfortunately still occurring on every single terraform plan and terraform apply.

**Comment by lucascantor** [comment]
I'm not sure if something like https://github.com/okta/terraform-provider-okta/pull/1032 is preferred over possibly fixing the capitalization of the actual group IDs returned from the Okta API itself.

**Comment by lucascantor** [comment]
@monde I've closed my associated PR, and I think this issue should be closed as well, as it appears the root cause seems to be my own accidental downcasing in some of the the variables representing the target group IDs:

```
variable "okta_groups" {
  description = "map of existing Okta group IDs, to use rather than relying on group names which might change"
  type        = map(string)
  default = {
    openpath_chicago                     = "00g8qc8nepxc5cfrp2p7"
    openpath_comms                       = "00gfhvd8oe5pGixLq2p7"
    openpath_consultants                 = "00gfhan3lp8SREXzZ2p7"
    openpath_dublin                      = "00g8qc8y208xvevem2p7"
    openpath_ftes                        = "00gfhalb09z3FB5T42p7"
    openpath_it                          = "00g8qc9nyzj8epiav2p7"
    openpath_london                      = "00g8qcab3jeqjtvrb2p7"
    openpath_mothers                     = "00gfhk02utUikxUut2p7"
    openpath_remote                      = "00g8qcm6zdbsswtsl2p7"
    openpath_sf                          = "00g8qc8y2vdiardru2p7"
    openpath_stores                      = "00gfhve6ovGVBu4Sl2p7"
    openpath_sydney                      = "00g8qc9foyyfh9n5g2p7"
    openpath_sydney_24hrs                = "00gbree774mxfkniu2p7"
    openpath_we                          = "00g8qc8o1yrqtgdck2p7"
  }
}
```
