### ISSUE TITLE
okta_auth_server_claim_default - unexpected forces replacement 

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#970]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.67.0
+ provider registry.terraform.io/okta/okta v3.20.7

Your version of Terraform is out of date! The latest version
is 1.1.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

- okta_auth_server_claim_default

### Terraform Configuration Files

```hcl
resource "okta_auth_server_default" "default_auth_server" {
  status      = "ACTIVE"
  name        = "default"
  description = "Default Authorization Server for your Applications"
  audiences = [
    "api://default",
  ]
  credentials_rotation_mode = "AUTO"
  issuer_mode               = "ORG_URL"
}

resource "okta_auth_server_claim_default" "default_auth_server-email" {
  always_include_in_token = true
  auth_server_id          = okta_auth_server_default.default_auth_server.id
  name                    = "email"
}
```

### Expected Behavior

Plan should evaluate to no changes as `auth_server_id` has not actually changed value

### Actual Behavior

This issue appears similar to #969 969 where [forceNew](https://github.com/okta/terraform-provider-okta/blob/8aaa1e693dc9ef9ee1176cd73a1f06ec30637a10/okta/resource_okta_auth_server_claim_default.go#L48-L50) on the schema is forcing replacement of the resource when using an attribute reference 

### Steps to Reproduce

1. `terraform apply`

### References

- #969 969

**Comment by bogdanprodan-okta** [comment]
Hi @exitcode0! I've copy-pasted your code and run `terraform apply`. Worked just fine.

**Comment by monde** [comment]
@exitcode0 this seems like a duplicate of #971

**Comment by monde** [comment]
Hi @exitcode0 let me know where you are at on this. Please close the issue if you are good to go now. Thanks!

**Comment by monde** [comment]
@exitcode0 open this issue back up if it is still current for you.
