### ISSUE TITLE
okta_auth_server_claim & okta_auth_server_default - unclear interaction

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#971]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_auth_server_claim 
- okta_auth_server_default

### Terraform Configuration Files

```hcl
resource "okta_auth_server_default" "default_auth_server" {
  status      = "ACTIVE"
  name        = "default"
  description = "Default Authorization Server for your Applications"
  audiences = [
    "api://default",
  ]
  credentials_rotation_mode = "AUTO"
  issuer_mode               = "ORG_URL"
}

resource "okta_auth_server_scope" "default_auth_server-email" {
  auth_server_id   = okta_auth_server_default.default_auth_server.id
  consent          = "IMPLICIT"
  default          = false
  description      = "Allows this application to access your email address."
  display_name     = "email"
  metadata_publish = "ALL_CLIENTS"
  name             = "email"
}
```

### Expected Behavior

`okta_auth_server_default` would store the ID of the auth server in the state file and the config above should evaluate to no changes in the plan 

### Actual Behavior
`okta_auth_server_default` appears to store its ID as "default" this leads me to some uncertainty as to the outcome of the following plan where it suggests it wil change the `okta_auth_server_scope`'s `auth_server_id` to `default`
my expectation is that this will either:
- fail to apply as most items related to anything default are mostly immutable
- apply correctly as default may be considered a valid ID for a auth server by the Okta API

```hcl
  # okta_auth_server_scope.default_auth_server-email will be updated in-place
  ~ resource "okta_auth_server_scope" "default_auth_server-email" {
      ~ auth_server_id   = "<REDACTED1>" -> "default"
        id               = "<REDACTED2>"
        name             = "email"
        # (5 unchanged attributes hidden)
    }
```

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by monde** [comment]
@exitcode0 in following up on this I was trying out your terraform configuration.

I originally received this error:

```
│ Error: failed to create auth server scope: the API returned an error: Api validation failed: name. Causes: errorSummary: name: ''name'' for a custom scope must not be any of the following: [openid, profile, email, address, phone, offline_access].
These scopes are provided with the authorization server.
│
│   with okta_auth_server_scope.default_auth_server-email,
│   on main.tf line 25, in resource "okta_auth_server_scope" "default_auth_server-email":
│   25: resource "okta_auth_server_scope" "default_auth_server-email" {
│
``` 

After I fixed the scope, and once the `okta_auth_server_scope` has been created subsequent apply commands give `No changes`

```
terraform apply
okta_auth_server_default.default_auth_server: Refreshing state... [id=aus9hjtvalACwOxhR696]
okta_auth_server_scope.default_auth_server-email: Refreshing state... [id=scpi77osczX5oJqf0696]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

Am I missing something in trying to repo this? Also, when `terraform.tfstate` file I can see `okta_auth_server_scope` has a reference to `auth_server_id` with the actual id value for my `okta_auth_server_default`.

Let me know what I'm missing. Thanks!

**Comment by monde** [comment]
@exitcode0 let me know where you are at with this. If you are good to go please close the issue. Thanks!

**Comment by monde** [comment]
@exitcode0 open this issue back up if it is still current for you.
