### ISSUE TITLE
Add support for Features API

### ISSUE THREAD

**Issue by sboulkour** [okta/terraform-provider-okta#976]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Management of Features toggling is not currently handeled by the provider. But the provider can manage resourcesonly available when certain early access features are activated.

As an example, I can configure a custom domain, and set it to use the Okta certificate management.
But, this certificate management feature is only available as an early access feature, and we can't activate it with the provider. I currently have separated code from Terraform to manage a set of features to activate.

### New or Affected Resource(s)

- okta_features

### References

API doc : https://developer.okta.com/docs/reference/api/features/#get-started

- #0000

**Comment by monde** [comment]
Thanks @sboulkour . Features in Okta API is supported in a recent release of okta-sdk-golang v2.10.0. It is on our roadmap to upgrade the Okta Terraform Provider to include the newest released endpoints and resources from v2.10 + v2.11 okta-sdk-golang:
https://github.com/okta/terraform-provider-okta/issues/979

**Comment by monde** [comment]
`/api/v1/features` support is in okta-sdk-golang now.

**Comment by andrei-korviakov** [comment]
We are waiting for this as well. It will be very handy
