### ISSUE TITLE
Sync okta-sdk-golang v2.9, v2.10, and v2.11 into the provider

### ISSUE THREAD

**Issue by monde** [okta/terraform-provider-okta#979]
We need to sync up the endpoints and resources that are newly available in `okta-sdk-golang` with the Okta Terraform Provider. These are versions `v2.10.0`, `v2.10.1`, and the upcoming `v2.11.0`. Also, add anything missing from the v2.9 releases. I'm not certain how much of those endpoints and resources already exist the provider's vendor style [sdk](https://github.com/okta/terraform-provider-okta/tree/master/sdk) package; but whatever is there will be converted over to using `okta-sdk-golang` code paths, also adding the new resources.

- https://github.com/okta/okta-sdk-golang/releases/tag/v2.10.0
- https://github.com/okta/okta-sdk-golang/releases/tag/v2.10.1
- (not released yet) https://github.com/okta/okta-sdk-golang/releases/tag/v2.11.0
  - feature branch https://github.com/okta/okta-sdk-golang/pull/280

**Comment by phaseOne** [comment]
Looks like #1001 unblocks further development to add new resources, right?

**Comment by monde** [comment]
> Looks like #1001 unblocks further development to add new resources, right?

@phaseOne that is correct. If you have a suggestion for a new resource / feature request please open an issue. Thanks!

**Comment by bretterer** [comment]
This issue is now resolved
