### ISSUE TITLE
Support passwordless user creation

### ISSUE THREAD

**Issue by RyanSiu1995** [okta/terraform-provider-okta#980]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently, the user resource only supports the credential mode.
But in some case, we want to setup a user without credential.
https://developer.okta.com/docs/reference/api/users/#create-user-without-credentials
So, if password is not given, we should consider the user want to create the user without credentials.

### New or Affected Resource(s)
- okta_user

### Potential Terraform Configuration
```hcl
"okta_user" "my_user" {
  login = "user"
  first_name = "first"
  last_name = "last"
}
```
This resource should refer to create user without credentials.

### References
https://developer.okta.com/docs/reference/api/users/#create-user-without-credentials

**Comment by monde** [comment]
I'll look into it, thanks @RyanSiu1995

**Comment by monde** [comment]
@RyanSiu1995 check it out, I'm able to create a user without setting a password. Double check me:

My main.tf
```
terraform {
  required_providers {
    okta = {
      source = "okta/okta"
    }
  }
}

variable "org_name" {
    type = string
}

variable "base_url" {
    type = string
}

variable "api_token" {
    type = string
}

provider "okta" {
  org_name  = var.org_name
  base_url  = var.base_url
  api_token = var.api_token
}

resource "okta_user" "my_user" {
  login = "user@example.com"
  email = "user@exmaple.com"
  first_name = "first"
  last_name = "last"
}
```

In a shell
```bash
export TF_VAR_org_name=myorg
export TF_VAR_base_url=okta.com
export TF_VAR_api_token=zz987

 ○ terraform init
 ○ terraform plan

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # okta_user.my_user will be created
  + resource "okta_user" "my_user" {
      + email                     = "user@exmaple.com"
      + expire_password_on_create = false
      + first_name                = "first"
      + id                        = (known after apply)
      + last_name                 = "last"
      + login                     = "user@example.com"
      + raw_status                = (known after apply)
      + status                    = "ACTIVE"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

 ○ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # okta_user.my_user will be created
  + resource "okta_user" "my_user" {
      + email                     = "user@exmaple.com"
      + expire_password_on_create = false
      + first_name                = "first"
      + id                        = (known after apply)
      + last_name                 = "last"
      + login                     = "user@example.com"
      + raw_status                = (known after apply)
      + status                    = "ACTIVE"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

okta_user.my_user: Creating...
okta_user.my_user: Creation complete after 1s [id=00uzzzzzzzzzzzzzzzzzz]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

What I see in the admin UI Directory > People:
![image](https://user-images.githubusercontent.com/201/155433803-896f238b-18c7-4cf8-996d-992addb3cf3c.png)

**Comment by monde** [comment]
Also, my main.tf in the previous example can be seen as too complicated. This will also work using the env vars the Okta provider looks for by default

```
terraform {
  required_providers {
    okta = {
      source = "okta/okta"
    }
  }
}
provider "okta" {
}
resource "okta_user" "my_user" {
  login = "user@example.com"
  email = "user@exmaple.com"
  first_name = "first"
  last_name = "last"
}
```

```
export OKTA_API_TOKEN=zz987
export OKTA_ORG_NAME=myorg
export OKTA_BASE_URL=okta.com

 ○ terraform init
 ○ terraform plan
 ○ terraform apply
```

**Comment by RyanSiu1995** [comment]
Hi @monde, in my case, the user immediately becomes active instead of pending user action state.
All the codes are the same as yours.
Let me double check if there is any missing on my end first.

**Comment by monde** [comment]
hi @RyanSiu1995 did you find anything yet? Close this issue if you are good to go, thanks!

**Comment by RyanSiu1995** [comment]
Hi @monde, I have tried to remove the password and it works on my end.
Originally, I have set the password as null and it has that issue, the user was activated immediately.

**Comment by monde** [comment]
Thanks for following up @RyanSiu1995 , I'm going to close this issue.
