### ISSUE TITLE
No way to manage automations

### ISSUE THREAD

**Issue by mcrobbj-abrdn** [okta/terraform-provider-okta#981]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is currently no means to add new automations:
https://help.okta.com/en/prod/Content/Topics/automation-hooks/add-automations.htm

### New or Affected Resource(s)

- okta_automation
- okta_automation_condition
- okta_automation_action

### Potential Terraform Configuration

```hcl
resource "okta_automation" "example" {
  name = "Inactive User"
}

resource "okta_automation_condition" "example" {
  automation_id= okta_automation.example,id
  condition_type = "For the Groups"
  applies_to = "Everyone"
}

resource "okta_automation_action" "example" {
  automation_id= okta_automation.example,id
  action_type = "Change user lifecycle state in Okta to"
  action= "Deactivate"
}
```

### References

https://help.okta.com/en/prod/Content/Topics/automation-hooks/add-automations.htm

- #0000

**Comment by monde** [comment]
Hi @mcrobbj-abrdn . Okta hasn't exposed automation in the Okta API https://developer.okta.com/docs/reference/core-okta-api/ . The Okta Terraform Provider manages Okta resources via the public endpoints documented in the public API. Sadly, and I know this can be confusing and frustrating, everything that is available in the Okta admin UI is not available via the public APIs. If your organization has an Okta Customer Success contact I'd suggest passing your suggestion through them. I'm going to close this issue for now.

**Comment by mcrobbj-abrdn** [comment]
Hi [monde](https://github.com/monde) as this is the official OKTA provider ( and OKTA contribute) one of the contributions could be to publically expose the API which the portal uses? Then wrap it in Terraform. This is a feature request.

**Comment by mcrobbj-abrdn** [comment]
@bogdanprodanj as an OKTA contributer how about it?

**Comment by monde** [comment]
@mcrobbj-abrdn , @bogdanprodan-okta and I are on the Developer Experience team at Okta. Our team manages the Terraform Provider, samples, and language SDKs. We don't maintain the Okta monolith or the API layer where the base features originate from. We are the wrong channel to ask for the Automations you see in the Okta UI to be exposed as public APIs. Please route this request through your Okta customer success contact.

**Comment by monde** [comment]
cc @jefftaylor-okta

**Comment by antonmos** [comment]
please reopen
