### ISSUE TITLE
Missing `logo` docs in SAML app

### ISSUE THREAD

**Issue by tgoodsell-tempus** [okta/terraform-provider-okta#986]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

N/A

### Affected Resource(s)

Latest

- okta_app_saml

### Terraform Configuration Files

```hcl
resource "okta_app_saml" "aiven_saml" {
  provider = okta.prod

  label                    = "Aiven OpenSearch"
  logo                     = "./logos/aiven.png"

}
```

### Debug Output

N/A

### Expected Behavior

Expected this attribute is documented in the docs file: https://registry.terraform.io/providers/okta/okta/latest/docs/resources/idp_saml

### Actual Behavior

I do not find this referenced in the documentation there. Probably a quick update, although this may be a good ping for looking into the autogenerated docs feature I see the newer terraform template providers using.

### Steps to Reproduce

1. `terraform apply`

### References

https://github.com/hashicorp/terraform-provider-scaffolding

- #0000

**Comment by tgoodsell-tempus** [comment]
Closing since I realized I linked the wrong resource, this is not an issue.

**Comment by monde** [comment]
ok @tgoodsell-tempus
