### ISSUE TITLE
App user custom schema property forced replacement

### ISSUE THREAD

**Issue by max4t** [okta/terraform-provider-okta#989]
https://github.com/okta/terraform-provider-okta/blob/ddc7065f9f319393b125a10f92ed39c2a39e781a/okta/user_schema_property.go#L95

Changes to `external_name` force the destruction of the property (and its re-creation) but when it's referenced in the mapping it fails.
Is there a reason for the `ForceNew` ? If not, can we remove it to improve the usage with the mappings?

**Comment by monde** [comment]
I'll look into this @max4t

**Comment by monde** [comment]
@max4t I'm still looking for some internal feedback about this. I'm not sure why the original developer set the terroform schema ForceNew attribute on the okta app user schema. Reading our API documentation and looking at the commit history on the provider is not revealing an answer.

@max4t can you give me a terraform config example so I can see the error as you see it? The "when it's referenced" part of your feedback is what I'd like to be able to experience for myself. Thanks!

**Comment by monde** [comment]
@max4t is this still an active issue for you?

**Comment by max4t** [comment]
Hello @monde 
yeah still an issue. I'll try to provide you an example today or tomorrow

**Comment by max4t** [comment]
Sorry for the late response. Here is an example of my usercase:

```tf
resource "okta_app_user_schema_property" "some_prop" {
  app_id        = okta_idp_oidc.some_odp.id
  index         = "some_value"
  required      = true
  type          = "string"
  external_name = "some_uri" // <= apply then change this and re-apply
}
resource "okta_profile_mapping" "some_mapping" {
  source_id          = okta_idp_oidc.some_odp.id
  target_id          = okta_idp_oidc.some_odp.user_type_id
  delete_when_absent = true

  mappings {
    expression  = "appuser.${okta_app_user_schema_property.some_prop.index}"
    id          = "my_prop"
    push_status = "PUSH"
  }
}
```

The property is used in the profile but as it's replaced when `external_name` changes, it fails with an error like "it's still in use in the mapping...".

**Comment by techjutsu-mikeb** [comment]
@max4t - What version of the Okta Terraform Provider are you using ("title" is required on my version for "okta_app_user_schema_property" resources)?
