### ISSUE TITLE
Failed to update default password policy

### ISSUE THREAD

**Issue by mcrobbj-abrdn** [okta/terraform-provider-okta#992]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
1.1.5

### Affected Resource(s)

- okta_policy_password_default

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Default password policy is updated

### Actual Behavior

Error: [0m[0m[1mfailed to update default password policy: the API returned an error: Cannot modify the priority attribute because it is read-only.[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with okta_policy_password_default.default,

### Steps to Reproduce

resource "okta_policy_password_default" "default" {
  password_min_length            = 12
  password_min_lowercase         = 1
  password_min_uppercase         = 1
  password_min_number            = 1
  password_exclude_username      = true
  password_exclude_first_name    = true
  password_exclude_last_name     = true
  password_dictionary_lookup     = true
  password_history_count         = 3
  password_max_age_days          = 0
  password_max_lockout_attempts  = 3
  password_show_lockout_failures = true
  password_lockout_notification_channels = ["EMAIL"]
  sms_recovery                   = "ACTIVE"
  email_recovery                 = "ACTIVE"
}

1. `terraform apply`

### References

- #0000

**Comment by monde** [comment]
@mcrobbj-abrdn can you give me some more background on this? I wasn't able to repo with your terraform config. The error implies you changed the priority on your resource but I'm not seeing that in the config your copy and pasted `Cannot modify the priority attribute because it is read-only.`

I initially didn't have the `ACCOUNT_LOCKOUT_USER_EMAIL` feature flag and could only do this.

```
  # okta_policy_password_default.default will be updated in-place
  ~ resource "okta_policy_password_default" "default" {
        id                                     = "xxx"
        name                                   = "Default Policy"
      ~ password_dictionary_lookup             = false -> true
      ~ password_history_count                 = 0 -> 3
      ~ password_min_length                    = 8 -> 12
      ~ sms_recovery                           = "INACTIVE" -> "ACTIVE"
        # (25 unchanged attributes hidden)
    }

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

After I received the `ACCOUNT_LOCKOUT_USER_EMAIL` feature flag I was able to also do this.

```
  # okta_policy_password_default.default will be updated in-place
  ~ resource "okta_policy_password_default" "default" {
        id                                     = "xxx"
        name                                   = "Default Policy"
      ~ password_lockout_notification_channels = [
          + "EMAIL",
        ]
      ~ password_max_lockout_attempts          = 10 -> 3
      ~ password_show_lockout_failures         = false -> true
        # (26 unchanged attributes hidden)
    }

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

**Comment by mcrobbj-abrdn** [comment]
Yep thats whats confusing me the terraform code doesnt mention priority.

**Comment by monde** [comment]
> Yep thats whats confusing me the terraform code doesnt mention priority.

@mcrobbj-abrdn are you still receiving the error? The terraform config you originally copy and pasted in the issue `resource "okta_policy_password_default" "default" {` the actual config you are using? If I could see the entire output of the terraform command would be helpful.

**Comment by mcrobbj-abrdn** [comment]
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  [33m~[0m update in-place
[0m
Terraform will perform the following actions:

[1m  # okta_policy_password_default.default[0m will be updated in-place[0m[0m
[0m  [33m~[0m[0m resource "okta_policy_password_default" "default" {
        [1m[0mid[0m[0m                                     = "00pl1pee4oIAfVMul5d6"
        [1m[0mname[0m[0m                                   = "Default Policy"
      [33m~[0m [0m[1m[0msms_recovery[0m[0m                           = "INACTIVE" [33m->[0m [0m"ACTIVE"
        [90m# (28 unchanged attributes hidden)[0m[0m
    }

[0m[1mPlan:[0m 0 to add, 1 to change, 0 to destroy.
[0m[0m[1m
Do you want to perform these actions?[0m
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  [1mEnter a value:[0m [0myes

[0m[1mokta_policy_password_default.default: Modifying... [id=00pl1pee4oIAfVMul5d6][0m[0m
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mfailed to update default password policy: the API returned an error: Cannot modify the priority attribute because it is read-only.[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with okta_policy_password_default.default,
[31m│[0m [0m  on main.tf line 145, in resource "okta_policy_password_default" "default":
[31m│[0m [0m 145: resource "okta_policy_password_default" "default" [4m{[0m[0m
[31m│[0m [0m
[31m╵[0m[0m

**Comment by monde** [comment]
@mcrobbj-abrdn re: `main.tf line 145, in resource "okta_policy_password_default" "default"`. Is there an litteral priority attribute listed in your resource code?
```terraform
resource "okta_policy_password_default" "default" {
  priority = 9 # some number
}
```
Just double checking, let me know. If not, I'm not able to recreate this as I showed in my notes previously.

**Comment by monde** [comment]
@mcrobbj-abrdn open this issue back up if it is still current for you.

**Comment by natmariam** [comment]
I am actually getting the same error, even though I don't have **priority** attribute defined. I also tried priority = null, just to see.

**Comment by ETrejosS** [comment]
Is this going to be solved anytime soon?

I'm using version 6.9.0 and the error continues to appear when applying...
`Error: failed to update default password policy: the API returned an error: Cannot modify the priority attribute because it is read-only.`
