### ISSUE TITLE
Support for Importing Built in Okta Apps?

### ISSUE THREAD

**Issue by Mrorya** [okta/terraform-provider-okta#993]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm hoping to utilize Terraform to assign Okta App Sign On Policy rules to the built in Okta applications (Okta Dashboard, Okta Admin Console). This does not appear to be possible as they are built in apps with configuration requirements that do not match the available arguments for the `okta_app_oauth` resource or the `okta_app_saml` resource. exploring these apps with the API returns us a resource similar to the following:

```
{
    "id": "",
    "name": "saasure",
    "label": "Okta Admin Console",
    "status": "ACTIVE",
    "lastUpdated": "2022-01-24T17:51:19.000Z",
    "created": "2022-01-24T17:51:18.000Z",
    "accessibility": {
        "selfService": false,
        "errorRedirectUrl": null,
        "loginRedirectUrl": null
    },
    "visibility": {
        "autoSubmitToolbar": false,
        "hide": {
            "iOS": false,
            "web": false
        },
        "appLinks": {
            "admin": true
        }
    },
    "features": [],
    "signOnMode": "OPENID_CONNECT",
    "credentials": {
        "userNameTemplate": {
            "template": "${source.login}",
            "type": "BUILT_IN"
        },
        "signing": {
            "kid": ""
        }
    },
...
```

If there is another way to import a configuration for these apps to utilize in further resource / policy connection - let me know if I've missed it.

### New or Affected Resource(s)

- okta_app_oauth

### Potential Terraform Configuration

```hcl
resource "okta_app_oauth" "admin_console" {
    preconfigured_app = "saasure"
    label = "Okta Admin Console"
}
```

**Comment by monde** [comment]
@Mrorya if you are just trying to add rules to the dashboard (or admin), doesn't this get you where you want to be? Use app data source (Dashboard in the example) to get the sign in data source for that app. Then make a new sign on rule with the `okta_app_signon_policy_rule`

main.tf
```terraform
terraform {
  required_providers {
    okta = {
      source = "okta/okta"
    }
  }
}

# export OKTA_API_TOKEN=xxx
# export OKTA_ORG_NAME=xxx
# export OKTA_BASE_URL=xxx

# terraform init
# terraform plan
# terraform apply

data "okta_app" "dashboard" {
  label = "Okta Dashboard"
}

data "okta_app_signon_policy" "dashboard" {
  app_id = data.okta_app.dashboard.id

  depends_on = [
    data.okta_app.dashboard
  ]
}

data "okta_group" "all" {
  name = "Everyone"
}

resource "okta_app_signon_policy_rule" "example" {
  name            = "My New Policy"
  status          = "ACTIVE"
  policy_id       = data.okta_app_signon_policy.dashboard.id
  groups_included = [data.okta_group.all.id]
  priority        = 82
}

output "app_id" {
  value = data.okta_app.dashboard.id
}

output "app_label" {
  value = data.okta_app.dashboard.label
}

output "policy_name" {
  value = data.okta_app_signon_policy.dashboard.name
}

output "new_policy_rule_id" {
  value = okta_app_signon_policy_rule.example.id
}
```

Shell `terraform apply`:

```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

okta_app_signon_policy_rule.example: Creating...
okta_app_signon_policy_rule.example: Creation complete after 0s [id=ruli6qxzfEtA6mCM5696]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

app_id = "0oa9hjty3X3JNsuvJ696"
app_label = "Okta Dashboard"
new_policy_rule_id = "ruli6qxzfEtA6mCM5696"
policy_name = "Okta Dashboard"
```

**Comment by Mrorya** [comment]
> @Mrorya if you are just trying to add rules to the dashboard (or admin), doesn't this get your where you want to be? Use app data source (Dashboard in the example) to get the sign in data source for that app. Then make a new sign on rule with the `okta_app_signon_policy_rule`
> 
> main.tf
> 
> ```
> terraform {
>   required_providers {
>     okta = {
>       source = "okta/okta"
>     }
>   }
> }
> 
> # export OKTA_API_TOKEN=xxx
> # export OKTA_ORG_NAME=xxx
> # export OKTA_BASE_URL=xxx
> 
> # terraform init
> # terraform plan
> # terraform apply
> 
> data "okta_app" "dashboard" {
>   label = "Okta Dashboard"
> }
> 
> data "okta_app_signon_policy" "dashboard" {
>   app_id = data.okta_app.dashboard.id
> 
>   depends_on = [
>     data.okta_app.dashboard
>   ]
> }
> 
> data "okta_group" "all" {
>   name = "Everyone"
> }
> 
> resource "okta_app_signon_policy_rule" "example" {
>   name            = "My New Policy"
>   status          = "ACTIVE"
>   policy_id       = data.okta_app_signon_policy.dashboard.id
>   groups_included = [data.okta_group.all.id]
>   priority        = 82
> }
> 
> output "app_id" {
>   value = data.okta_app.dashboard.id
> }
> 
> output "app_label" {
>   value = data.okta_app.dashboard.label
> }
> 
> output "policy_name" {
>   value = data.okta_app_signon_policy.dashboard.name
> }
> 
> output "new_policy_rule_id" {
>   value = okta_app_signon_policy_rule.example.id
> }
> ```
> 
> Shell `terraform apply`:
> 
> ```
> Do you want to perform these actions?
>   Terraform will perform the actions described above.
>   Only 'yes' will be accepted to approve.
> 
>   Enter a value: yes
> 
> okta_app_signon_policy_rule.example: Creating...
> okta_app_signon_policy_rule.example: Creation complete after 0s [id=ruli6qxzfEtA6mCM5696]
> 
> Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
> 
> Outputs:
> 
> app_id = "0oa9hjty3X3JNsuvJ696"
> app_label = "Okta Dashboard"
> new_policy_rule_id = "ruli6qxzfEtA6mCM5696"
> policy_name = "Okta Dashboard"
> ```

This is helpful, thanks! Will go ahead and configure it this way rather than attempting to import/re-create it.

**Comment by monde** [comment]
awesome, glad to hear it @Mrorya
