### ISSUE TITLE
Various App Type Docs are Missing key fields

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#994]
As result of the various `okta_app_*` updates over the past year and how the actual fields are generated via `build**`, the documentation for app arguments failed to match the actual provider schema 100%.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by monde** [comment]
Thanks @virgofx
