### ISSUE TITLE
Create new Major release that Removes Deprecated Features

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#999]
There's a fair amount of deprecations in the current code base. It would be nice to remove things like `admin_roles`  from `okta_users` and `users`/`groups` from all `okta_app-*` and just cleanup all the deprecated items with a new major release.

**Comment by monde** [comment]
👍 @virgofx . All of the okta SDKs are on v2 and generated from this openapi spec https://github.com/okta/okta-management-openapi-spec . We are in the process of releasing a v3 spec with new tooling in the next two to three months. When that occurs okta-sdk-golang will release as v3.0.0. We should take that opportunity to do a major version release of the terraform provider then, as well as clean house of the deprecated items.

**Comment by monde** [comment]
Going to party like it's ~1999~ 999

**Comment by virgofx** [comment]
Awesome - Yeah there was no deadline here ... that sounds like a perfect plan. 🥂
